### ISSUE TITLE
Automate deployment to several servers with one command

### ISSUE THREAD

**Issue by AndreasGalster** [zodern/meteor-up#100]
Not sure if this is already possible. Currently we're running three servers, two production for SEA and one in the US as well as a staging server. We certainly are going to add more servers eventually so I'm wondering if there's an easier way to deploy than having to have three seperate folders for deployment, go to each folder and manually start the deploy process. 

Also, is it actually recommended to start using this version by now? How stable/usable is it vs mupx (which we're currently still using)?

**Comment by timbrandin** [comment]
I'm having trouble using this feature, deploying to multiple servers, gettings stuck on "Sending Environment Variables".

**Comment by mikemeier** [comment]
@timbrandin have a look at #122

**Comment by zodern** [comment]
Deploying to multiple servers should work.
