### ISSUE TITLE
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

### ISSUE THREAD

**Issue by techloverparveen** [zodern/meteor-up#1003]
Mup version (`1.4.5`):

Mup config

```js
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '52.54.66.198',
      username: 'ubuntu',
      pem: '/home/edge-1/test.pem'
      // password: 'server-password'
      // or neither for authenticate from ssh-agent
    }
  },

  app: {
    // TODO: change app name and path
    name: 'addisonhouse',
    path: '/home/edge-1/Documents/cuurentproject/Pianca/addisonhouse',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://52.54.66.198:3000',
      MONGO_URL: 'mongodb://localhost/meteor',
PORT:3000
      //MONGO_OPLOG_URL: 'mongodb://localhost/local',
    },

    docker: {
      // change to 'abernix/meteord:base' if your app is using Meteor 1.4 - 1.5
      image: 'abernix/meteord:node-8.4.0-base',
     //imagePort: 3000
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },



  // (Optional)
  // Use the proxy to setup ssl or to route requests to the correct
  // app when there are several apps

  // proxy: {
  //   domains: 'mywebsite.com,www.mywebsite.com',

  //   ssl: {
  //     // Enable Let's Encrypt
  //     letsEncryptEmail: 'email@domain.com'
  //   }
  // }
};
```

Output of command

```bash
	/built_app/programs/server/node_modules/fibers/future.js:313
							throw(ex);
							^
	MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
	    at Pool.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
	    at emitOne (events.js:115:13)
	    at Pool.emit (events.js:210:7)
	    at Connection.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
	    at Object.onceWrapper (events.js:318:30)
	    at emitTwo (events.js:125:13)
	    at Connection.emit (events.js:213:7)
	    at Socket.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:189:49)
	    at Object.onceWrapper (events.js:316:30)
	    at emitOne (events.js:115:13)
	    at Socket.emit (events.js:210:7)
	    at emitErrorNT (internal/streams/destroy.js:64:8)
	    at _combinedTickCallback (internal/process/next_tick.js:138:11)
	    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
	 
	=> Redeploying previous version of the app

```

**Comment by techloverparveen** [comment]
I have tested MongoDB running well on my machine.
I have checked via typing mongo and its work.
Also, check via netstat -tunlp it showing me the mongod running on port 27017

**Comment by techloverparveen** [comment]
Facing this issue in  x **

> Verifying Deployment: FAILED

**

**Comment by SimonSimCity** [comment]
I guess you forgot about the database and the fact that you're inside a docker-container, so this `localhost` is not the machine you want to refer to.

Please read the chapter MongoDB of the documentation to this script: http://meteor-up.com/docs.html#mongodb I think this will clear it out for you. Specially the subtopic `Multiple apps use the same database` should be of interest if you want to manage the database yourself. If you're not keen on that, I'd just take the build-in database.

**Comment by techloverparveen** [comment]
Thanks for your reply but I have tried with that as well. By adding the 
  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
in my config file but it not worked for me.

**Comment by SimonSimCity** [comment]
It was not only about adding the `mongo` section into your configuration. The environment variable must also fit. I highly doubt that `localhost` is the correct server in `MONGO_URL` because this would require that you use a different base-image than `abernix/meteord:node-8.4.0-base`.

I guess this is a test server and you just want it to work, right? Then please follow the following steps:

1. Add the mongo-section back to your configuration.
1. Call `mup setup` to make sure the mongo container is installed and running.
1. Set `MONGO_URL` in your configuration to `mongodb://mongodb:27017/meteor` (you can change `meteor` to what you want to call your app - if you want)
1. I guess you also want to use the oplog instead of constantly asking the database for updates. If yes, please set `MONGO_OPLOG_URL` to `mongodb://mongodb:27017/local` in your configuration
1. Run `mup deploy`
1. If it still fails, show the result of `mup logs --tail=200` and ssh on your server and show the result of calling `docker stats`

**Comment by techloverparveen** [comment]
Could you please help with the configuration of mup file.
I want to setup it on my Amazon ec2 instance.
What should I need to install or what will be the mongo URL for that?
Because as on local MongoDB running on +1 port of your meteor application port.

So please help me with the configuration.
Thanks

**Comment by SimonSimCity** [comment]
Because I only have limited time on this, I can just forward you to the docs 😉 http://meteor-up.com/docs.html#example-configs. Read carefully through those and I guess they'll provide you with an answer.

Otherwise it might also be a good idea to read yourself into docker and their networking ...
