### ISSUE TITLE
MUP emptied my nginx-config. Unable to restore or regenerate it.

### ISSUE THREAD

**Issue by bvanderdrift** [zodern/meteor-up#1004]
We were migrating to a new domain and were running the migration in our staging environment first. To do this we changed the domain in the config and added a custom shared NGINX file with a server block with a redirect to our new domain.

After running `mup proxy reconfig-shared` both the new and old domain refused to connect. When running `mup proxy nginx-config` I got an empty output.

Things I have tried that did not resolve the issue (see below for outputs):
* `mup deploy`
* `mup reconfig`
* `mup setup`
* `mup proxy reconfig-shared`

### Mup version (`mup --version`): 
`1.4.5`

### Mup config
```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "root"
    }
  },
  "proxy": {
    "domains": "new.domain.com",
    "ssl": {
      "letsEncryptEmail": "some@email.com"
    },
    "shared": {
      "nginxConfig": "./extra_nginx_config"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "https://new.domain.com",
      "MONGO_URL": "mongodb://user:pass@subdomain.host.com:47440/database",
      "VIRTUAL_HOST": "new.domain.com",
      "HTTPS_METHOD": "noredirect",
      "HTTP_FORWARDED_COUNT": 1,
      "LETSENCRYPT_HOST": "new.domain.com",
      "LETSENCRYPT_EMAIL": "some@email.com"
    },
    "docker": {
      "image": "abernix/meteord:node-8.11.2-base",
      "stopAppDuringPrepareBundle": true
    },
    "type": "meteor"
  }
}
```
extra nginx config:
```
server {
  server_name: old.domain.com;
  rewrite ^/(.*)$ https://new.domain.com/$1 permanent;
}
```

Output of command
`mup reconfig`: all success
`mup deploy`: all success
`mup setup`: all success
Interesting output:
```bash
...
[new.domain.com] - Pushing the Startup Script
[new.domain.com] - Pushing the Startup Script: SUCCESS
[new.domain.com] - Pushing Nginx Config
rm: cannot remove 'new.domain.com_location': No such file or directory
[new.domain.com] - Pushing Nginx Config: SUCCESS
[new.domain.com] - Cleaning Up SSL Certificates
[new.domain.com] - Cleaning Up SSL Certificates: SUCCESS
...
```
`mup proxy reconfig-shared`: all success
`mup proxy nginx-config`:
```bash
mup proxy nginx-config --verbose
===== new.domain.com ======


```

**Comment by bvanderdrift** [comment]
I found the command `mup logs proxy` which returned the following output:
```bash
...
[new.domain.com];1mnginx.1    | ;1m2018/09/10 10:03:48 [emerg] 30#30: unknown directive "server_name:" in /etc/nginx/conf.d/my_proxy.conf:2
[new.domain.com];1mnginx.1    | ;1mnginx: [emerg] unknown directive "server_name:" in /etc/nginx/conf.d/my_proxy.conf:2
[new.domain.com];1mforego     | starting nginx.1 on port 5200
[new.domain.com];1mforego     | sending SIGTERM to nginx.1
...
```

This made me realize I had put a ":" in the new Nginx config, which made it an unknown directive.

If I remember correctly after starting meteor, the `mup deploy` command does a "Verifying Deployment" step, and if that fails it prints the logs of the docker container. This might be a nice idea to do as well for the reverse proxy since that would have given me the right feedback directly.

**Comment by x5engine** [comment]
@bvanderdrift very nice notes

I never saw these in the docs

```
     "VIRTUAL_HOST": "new.domain.com",
      "HTTPS_METHOD": "noredirect",
      "HTTP_FORWARDED_COUNT": 1,
      "LETSENCRYPT_HOST": "new.domain.com",
      "LETSENCRYPT_EMAIL": "some@email.com"

```

I will try these and see how it works...
