### ISSUE TITLE
How to deploy to multiple servers faster?

### ISSUE THREAD

**Issue by elie222** [zodern/meteor-up#1010]
I have to deploy to 10+ instances. It take me hours to deploy to all the instances each time. A good 5-10 minutes per upload.

Is there a way to do this more efficiently? Best I've come up with is deploying from a deploy server. Was wondering if anyone had a better solution?

Also, would deploying to 4 ports on the same server require 4 uploads? (seem to remember it did for a while back, but wondering if the state of things is still the same here).

**Comment by zodern** [comment]
Do you have the `stopAppDuringPrepareBundle` option set to false? I can look into uploading in parallel when it is set to false.

An idea I've been considering is having an option for Meteor Up setup a private Docker registry. Mup could upload the bundle to one server, build the image, and push it to the registry. All of the other servers could then pull it from the registry.

**Comment by elie222** [comment]
I don't know about stopAppDuringPrepareBundle

Would need to take a look. Would it help?

And yes, was thinking the same thing about the private docker registry
approach. I'd be interested in playing with that myself if you could point
me to a good place to look in the code.

**Comment by zodern** [comment]
`stopAppDuringPrepareBundle` is explained in the [example config](http://meteor-up.com/docs#everything-configured) (look in the `app.docker` object). It would reduce the time each server is down. If there would be any benefit from it, uploading in parallel could be enabled when `stopAppDuringPrepareBundle` is set to false.

> Also, would deploying to 4 ports on the same server require 4 uploads? (seem to remember it did for a while back, but wondering if the state of things is still the same here).

It uploads to each server listed in `app.servers`

> And yes, was thinking the same thing about the private docker registry
approach. I'd be interested in playing with that myself if you could point
me to a good place to look in the code.

It probably would be best to create a [new plugin](https://github.com/zodern/meteor-up/tree/master/src/plugins) to manage the registry. The [`meteor push`](https://github.com/zodern/meteor-up/blob/master/src/plugins/meteor/command-handlers.js#L147) command and [prepare bundle](https://github.com/zodern/meteor-up/blob/master/src/plugins/meteor/assets/prepare-bundle.sh) script would need to be updated to only upload to one server and push the image to the registry.

**Comment by elie222** [comment]
> It uploads to each server listed in app.servers

So to upload to 2 different ports on the same server it would perform 2 uploads?

We wrote a script to handle this ourselves in the past, but was hoping it would have been native functionality as the script has its disadvantages. For others looking:
https://gist.github.com/elie222/10d8d830db341551612ba38ac6f32cd9

**Comment by zodern** [comment]
The latest [Mup 1.5](https://github.com/zodern/meteor-up/issues/893) beta adds support for private docker registries. When it is enabled, mup will only upload and run Prepare Bundle on a single server, push the image to the registry, and then use that image to deploy on the rest of the servers. The documentation is [here](https://github.com/zodern/meteor-up/blob/c8251213b05dd166bb7222eec0f3f6a66835edf3/docs/docs.md#private-docker-registry)
