### ISSUE TITLE
SSL auto renew failed

### ISSUE THREAD

**Issue by boOnii** [zodern/meteor-up#1026]
Hi, 

I use Meteor up with Reverse Proxy as described in docs and it works fine. 

The certificate expired two days ago and it does not renew automatically. In "proxy logs-le" command, I can find this info :  Certificates already exist and renewal is not necessary, exiting with status code 1"

I find any issue speaking about this problem. What can I do ? 

Thanks for your help.

**Comment by zodern** [comment]
What does `mup proxy status` show?

**Comment by boOnii** [comment]
Thank you for responding quickly. 


Here is the answer from mup proxy status: 
![2018-10-18_09h41_27](https://user-images.githubusercontent.com/34481750/47138647-43eaa000-d2ba-11e8-9071-9be9d233fd6e.png)

**Comment by boOnii** [comment]
Any ideas ?

**Comment by boOnii** [comment]
The issue came from AWS Certificate Manager

**Comment by programthis** [comment]
Hi @boOnii I know this ticket is old but what exactly did you do to resolve it? I seem to be getting the same issue as this.
