### ISSUE TITLE
Tracking current release in environment variables

### ISSUE THREAD

**Issue by SachaG** [zodern/meteor-up#1029]
I was checking out [Sentry](http://sentry.io) and one thing they support is associating errors with a specific version of your codebase: https://docs.sentry.io/learn/releases/?platform=browser

Their docs say: 

> How you make the version available to your code is up to you. For example, you could use an environment variable that is set during the build process.

Could this be integrated to Mup somehow? Every time you deploy, Mup could set a `release` env variable that includes the app name and timestamp? Or even include your last commit message?

**Comment by zodern** [comment]
Meteor 1.8.1 provides [`Meteor.gitCommitHash`](https://github.com/meteor/meteor/pull/10442) which can be used for this.
