### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by sungwoncho** [zodern/meteor-up#103]
When I run `npm install` on a freshly cloned meteor-up directory, I get:

```
> mup@1.0.0 prepublish /Users/mikecho/dev/github/clones/meteor-up
> nofat make

/Users/mikecho/dev/github/clones/meteor-up/node_modules/nofat/tasks/make/index.js:45
        throw err;
        ^

Error: Couldn't find preset "es2015" relative to directory "/Users/mikecho/dev/github/clones/meteor-up/src"
```

**Comment by joncursi** [comment]
Fixed for me by running

```
npm install --save-dev npm install babel-cli babel-preset-es2015 babel-preset-stage-3
```

in the `meteor-up` directory.

**Comment by madushan1000** [comment]
@mnmtanish It looks like we have a dependency problem in nofat.

**Comment by thani-sh** [comment]
Hi @sungwoncho and @joncursi 
What is your **npm** version? nofat doesn't work with npm v2

```
npm -v
```

If possible, can you try upgrading npm to v3.

**Comment by saitodisse** [comment]
to update npm: `npm i npm -g`
I was getting this error too: `Error If encoding is specified then the first argument must be a string`
I've installed node 5 instead node 6 and now its working.

**Comment by sungwoncho** [comment]
@mnmtanish Using npm 3.8.7, the issue was resolved. This can be closed.
