### ISSUE TITLE
Start Meteor application using the dumb-init tool

### ISSUE THREAD

**Issue by nabiltntn** [zodern/meteor-up#1033]
Hi,

Is it's possible to start the Meteor application using the the `dumb-init` https://github.com/Yelp/dumb-init ?

I have an application that launches Puppeteer ( that starts Chromium process )
Currently, if i am not wrong,  `mup` starts application with `node main.js` command which will have PID of 1.

This will result in many zombies Chromium processes because the parent Node process has ID 1.

I am not sure if this needs to be done in mup code / configuration or a custom Docker image.

Any ideas ?

**Comment by zodern** [comment]
Mup runs a docker image which takes car of starting node. This should be changed in the docker image you are using.
