### ISSUE TITLE
Setup fails with Ubuntu 18.04 server because of docker installation

### ISSUE THREAD

**Issue by luski** [zodern/meteor-up#1035]
Mup version 1.4.5:

the `mup setup` fails with Ubuntu 18.04 server. It's because ppa is outdated and the docker can be installed using snap now. Moreover when it is installed the docker service has different name.

**Comment by rashmimhatre100** [comment]
In our case deployment is not happening it is stuck at extracting tools or sometimes at Building for web.browser.legacy.

But for one of our project we are using AWS ubuntu 18.04 only and were facing issue,
Container has no IP Address, likely from it restarting.

Tried stopping/removing mongodb conatiners, re-running it using docker.
Then we checked the mongodb shell version it was different than configured in mup.js and observed version applied in mup.js and somehow it worked.

Tried to implement above in different project but didn't worked, mup deploy is stuck.

**Comment by zodern** [comment]
Setting up Ubuntu 18 works well now.
