### ISSUE TITLE
Simultaneous prepare bundle

### ISSUE THREAD

**Issue by elie222** [zodern/meteor-up#1041]
Prepare bundle stage takes a while. Would it be possible to have this run at the same time on all servers? As soon as the deploy for the first server finishes, moving to the deploy of the next server and running Prepare Bundle at the same time.

**Comment by zodern** [comment]
Mup 1.5 will be able to run Prepare Bundle on a single server instead of all of them when a private docker registry is configured. The documentation is [here](https://github.com/zodern/meteor-up/blob/c8251213b05dd166bb7222eec0f3f6a66835edf3/docs/docs.md#private-docker-registry)
