### ISSUE TITLE
Enable additional ports 

### ISSUE THREAD

**Issue by pociej** [zodern/meteor-up#1049]
I would like to have access to more than one ports, for some specific requirements i want my app to be able to listen on more than one port. Is it possible via mup config or should i modify some nginx files generated by mup?

**Comment by ddaydd** [comment]
in buildInstructions of docker ?

```
    docker: {
      image: 'abernix/meteord:node-8.11.2-base',
      "buildInstructions": [
        EXPOSE 3050"
      ],
    },
```

**Comment by ddaydd** [comment]
Hi,

https://github.com/zodern/meteor-up/issues/460#issuecomment-283455401
