### ISSUE TITLE
mupx deploy verification failed, by getting wrong version of fibers.node

### ISSUE THREAD

**Issue by ipa1981** [zodern/meteor-up#105]
Seems there are pretty similar problems in other issues (#106 for example).

I get pretty similar problem as many others on deployment:

```
/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
        throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
              ^
    Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
```

What I just found - the problem is in version of fibers file. On deployment version _node_modules/fibers/bin/linux-x64-v8-4.6/fibers.node_ is installed while server looks for _node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node_

When I install the proper version manually - everything starts working. Until next deploy, which again installs wrong version. 

Can it somehow be fixed?

**Comment by phongyewtong** [comment]
i have this problem too for 2 days already. how can we fixed this?

**Comment by julienrott** [comment]
Having same kind of issue. Did you find a workaround ?

**Comment by ipa1981** [comment]
Copy missing file manually.

**Comment by MasterJames** [comment]
And your version of Meteor I wondered? 1.3.2.4+?

**Comment by ipa1981** [comment]
@MasterJames Me, yes. 1.3.2.4

**Comment by MasterJames** [comment]
I think the problem steams from incompatible binaries.
The new version you have seemed to fix most fiber problems for people.
Only other thing other threads suggested was to delete the node_modules folder or something like that.
Some clean build is needed. Could be a dependency of a dependency? 
The Meteor plan is to allow packages to build but to include all possible binaries in the npm modules.
You might have to look up how to build manually. Update everything possibly related. 
Backup first. Then maybe...
I would start fresh with a clean target. Do a simple test with a basic meteor default, then start adding your packages and see which ones might trigger a fibers error.
Then resolve that with the package creator by building the correct binaries for the target platform if that's what's happening.
Anyway I hope this help you find the right solution. Report back your findings and hopefully solution.

**Comment by ipa1981** [comment]
@MasterJames thanks for suggestion. Unfortunately I'm very busy now, so have not time to play with plugins to check. Maybe someone else can try and give share results.

My insight here is that fibers.node files path somehow remind me kernel versions. And could it be that mupx or docker (I'm not specialist here) simply picks wrong version. As my server runs on 3.13 kernel (or 3.14 branch if I understand correctly) while file for 4.6 (??) version of fibers is installed.

Could the clue be here?
