### ISSUE TITLE
how to deploy multi mongo version on only one hosting?

### ISSUE THREAD

**Issue by thearabbit** [zodern/meteor-up#1050]
Mup version (`1.4.5`):
how to deploy multi mongo version on only one hosting?
Example:
- IP: 1.2.3.4:3000 for application `A`, use mongo 3.2
- IP: 1.2.3.4:5000 for application `B`, use mongo 3.4
How to  config `mup.js`

**Comment by zodern** [comment]
This is currently not supported using the built-in mongodb. You can run two mongo instances yourself on the server, or use two servers.

**Comment by thearabbit** [comment]
OK thanks
