### ISSUE TITLE
Where does MUP strore files on the server?

### ISSUE THREAD

**Issue by ni-vo** [zodern/meteor-up#1058]
I managed to lose part of my source code, but the test server that was deployed with MUP is still live. Where can I find the Meteor project files?

Edit: I have found the js file in /opt/{project}/tmp/bundle/programs/web.browser, but some of my helper methods are missing. Where else could they be?

Thanks

**Comment by x5engine** [comment]
Your source code will be bundled and not as you wrote it, just in minified format and almost unusable since all variables and amost all functions get renamed..
