### ISSUE TITLE
Apollo Server endpoint times out (error 504)

### ISSUE THREAD

**Issue by SachaG** [zodern/meteor-up#1061]
I have no idea if this is an issue related to Mup but I'm not sure where else to start so I thought I'd ask. 

I've noticed yesterday that my app's `/graphql` endpoint (powered by Apollo Server) errors out: https://staging.zenshome.jp/graphql

There are no errors in the logs or any other hint, it just times out. Since the endpoint works normally locally in development mode, I was thinking maybe it could be an issue with Nginx somehow? How can I debug this kind of problem?

**Comment by klokie** [comment]
hi @SachaG – how were you able to solve this? I've been seeing the same issue (deploying with Mup to Digital Ocean & CloudFlare).

**Comment by SachaG** [comment]
I don't remember exactly but I did have to turn Cloudflare off (only keeping it for DNS) and I think I haven't turned it back on yet.

**Comment by klokie** [comment]
OK thanks
