### ISSUE TITLE
Remote CI/CD compatibility

### ISSUE THREAD

**Issue by jonathanstiansen** [zodern/meteor-up#1068]
Hey guys, I love the ease that we can deploy with `mup`. One huge problem with having secrets in the `settings.json` file is that I can't figure out how to do automated CI/CD in my repo. I don't want to check in `settings.json` for obvious reasons - but I also *need* it to do `mup deploy`.

What I've tried, I tried deploying it locally with `mup deploy --settings settings.json` then hoping that it somehow was pushed to the remote machine (and persisted) so when I did `mup deploy` it wouldn't need secrets at deploy time.

That doesn't work. It needs settings.json. How do I deploy it without secrets, but have the secrets on my remote machine? 

`mup.js` is a culperate as well, since it needs to be checked in to version control, but can't have sensitive (but seemingly required entries) such as `MONGO_URL` in it. 

I've found a few tutorials but no one seems to address this problem, they just don't deploy to production from their CI/CD...

If I can figure out how to make everything use `env` instead of `settings.json` then I've got it solved, as I just added an `.env` file to the prod machine and added a flag for docker `--env-file ~/.env` in `mup.js` but it doesn't solve that `settings.json` is required and looked for, and used differently then `process.env.xxxx` variables...

**Comment by emjimadhu** [comment]
@jonathanstiansen Did you find a solution for it?

**Comment by jonathanstiansen** [comment]
@emjimadhu I haven’t :-p

**Comment by emjimadhu** [comment]
@jonathanstiansen How about use the same steps for `.env` as you mentioned and send an empty `settings.json`?

**Comment by zodern** [comment]
For a couple of my projects, I store the secrets in environment variables. Then, in my mup config it sets the values from the environment variables:
```js
module.exports = {
 // ... rest of config
 app: {
    env: {
      MONGO_URL: process.env.APP_MONGO_URL
    }
  }
}
```

For the settings.json, it has a `generate-settings.js` file which sets the secrets from environment variables, then writes it to `settings.json`. I have `pre.deploy` and `pre.reconfig` hooks to run the script.
