### ISSUE TITLE
running npm install --global mup installs beta 1.5.0-beta.2

### ISSUE THREAD

**Issue by LarsBuur** [zodern/meteor-up#1081]
Mup version (`mup --version`):1.5.0-beta.2

Mup config

```js
paste config here...
```

Output of command

```bash
npm i --global mup
```

also 1.5.0-beta.2 is listet as default on npm.

https://www.npmjs.com/package/mup

**Comment by zodern** [comment]
Sorry about that. 1.5.0-beta.2 is now on the next tag, and the latest tag is back to 1.4.6.
