### ISSUE TITLE
MUP v1.5 beta 1 & 2 doesn't work with SSL/Let's encrypt

### ISSUE THREAD

**Issue by Billybobbonnet** [zodern/meteor-up#1082]
Long story short, I debugged for many hours and overnight my app in prod because after updating it, I had a 502 error. Everything seemed to work, all the logs/status/proxy/docker settings were green.

My fix > reinstall mup@1.4.6, setup, reconfig, deploy & voilà.

I post it here to avoid others to spend time investigating an issue they didn't cause. Feel free to request more details.

**Comment by zodern** [comment]
Did you run `mup setup` after installing 1.5-beta.2?

**Comment by Billybobbonnet** [comment]
Yes, I did. I spent approx 6 hours trying to figure out what was going wrong. I checked every log, every status, listed docker containers to check if it wasn't about an issue with a container not responding. Meteor was running fine, the DB could be reached with ssh, both the proxy container and its lets encrypt counterpart were running fine and I didn't see any issue in their config. Mup status and proxy status were all fine.

I really wish I could have put my finger on the issue, but I had no clues. I tried to setup/reconfig/deploy with beta 1 and 2 but nothing changed. It is a production setup who ran for more than 2 years flawlessly and had dozens of updates using mup pre v1.5.

I can't be a backer since I'm short on funds, but if you want me to try to learn more about the issue, I'm all yours, as long as you can point me in the right direction.

Also, thank you for this great project and the good work you did.

**Comment by zodern** [comment]
It should be fixed in the latest beta.
