### ISSUE TITLE
Local MongoDB + SSL error

### ISSUE THREAD

**Issue by ChenLi0830** [zodern/meteor-up#109]
Hi there, I encountered an error when trying to setup the environment with SSL and local MongoDb. It seems to be a configuration error to me, but I couldn't seem to find a good example/documentation for this particular combination (ssl + local MongoDB). If there is a way to fix it, please let me know, thanks!

Here is the error log

```
mup setup

Started TaskList: Setup Docker
[101.201.77.89] - setup docker
[101.201.77.89] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[101.201.77.89] - Setup Environment

Started TaskList: Setup Mongo
[101.201.77.89] - setup environment
[101.201.77.89] - setup environment: SUCCESS
[101.201.77.89] - copying mongodb.conf
[101.201.77.89] - Setup Environment: SUCCESS
[101.201.77.89] - Copying SSL Certificate Bundle
Error Protocol error: expected packet type 21, got 90
```

And here is the mup.js file

```
module.exports = {
  servers: {
    one: {
      host: '101.201.77.89',
      username: '******',
      password: '******',
      // pem: './mykey',
    },
  },

  meteor: {
    name: 'appName',
    path: './',
    servers: {
      one: {},
    },

    env: {
      ROOT_URL: 'http://101.201.77.89',
      MONGO_URL: 'mongodb://localhost/meteor'
    },

     ssl: {
       crt: './ssl/edf4bc5d27a15377.crt',
       key: './ssl/ssl.key',
       port: 443
     },

    deployCheckWaitTime: 120,
    enableUploadProgressBar: true
  },

  mongo: { //optional
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },    
  },
};
```

**Comment by mbabauer** [comment]
I am getting the same issue now.  Did you ever find a fix?

One thing I noted that seems strange was that the SSL logs appear under the Mongo setup, not the Meteor setup, whereas the code performs the tasks as part of the Meteor setup in lines 45-62 of src/modules/meteor/index.js (or, at least it appears that way).  Maybe it's just a thread timing issue or something.

**Comment by MasterJames** [comment]
What's the target machine's operating system and SSH version? Your login info works fine though right? 

I wondered how to double check that the file copied but I guess not.
https://github.com/kadirahq/meteor-up/blob/master/src/modules/meteor/assets/verify-ssl-config.sh

Targets file /opt/$APPNAME/config/bundle.crt

Full DEBUG log should show this happening?
https://github.com/arunoda/nodemiral/blob/dbc96f5083650396d4f395ecc9b8c209c07e5894/lib/session.js#L82

Proper syntax is with no space. I think?

`DEBUG=* mup deploy`

**Comment by mbabauer** [comment]
It just started working, all of a sudden.  But, to help the cause, my target system is Ubuntu 14.04, ssh version is OpenSSH_6.6.1p1, which I believe is the latest.

**Comment by MasterJames** [comment]
Ironically I suspected that might happen. Something updated eventually I suspect. Just takes a little bump sometimes, either way tinkering with ideas & settings etc. helps the solution to settle out to the top. Great problem solving skills. Anyway glad it's working now.

**Comment by nilsi** [comment]
Strange it happened for me as well but I also just reran it and it worked.

**Comment by varffs** [comment]
+1 

This seems to persist but resolve without changes. I also got these inconsistent error returns:

`Error Protocol error: expected packet type 32, got 90`
`Error protocol error: rcvd type 90`
`Error Protocol error: expected packet type 21, got 90`

Then after running a few more times it went thru. I wonder if the issue is related to this package: https://www.npmjs.com/package/nodemiral which seems to be doing the copy to server command

**Comment by ghost** [comment]
This is happening to me as well... anyone find a fix? I've been getting the different errors but it hasn't gone through yet.

**Comment by sproleee** [comment]
I have the same problem. After trying about 15 tries, it suddenly went through.

Anyone know what the problem is?

**Comment by shadowcodex** [comment]
You are free to reopen this issue if this problem still persists.
