### ISSUE TITLE
Node 12 -> Unknown message digest

### ISSUE THREAD

**Issue by edemaine** [zodern/meteor-up#1091]
I can't get mup to connect to my server using Node 12, whereas everything works fine on Node 8.  According to [this issue](https://github.com/mscdex/ssh2/issues/720) and [this issue](https://github.com/mscdex/ssh2-streams/issues/110), it seems mup need to have an updated dependency on ssh2 and/or ssh2-streams. Hopefully an easy fix?

**Comment by zodern** [comment]
This will be fixed in the next 1.5 beta.
