### ISSUE TITLE
version question

### ISSUE THREAD

**Issue by anativhq** [zodern/meteor-up#1098]
Hi

The version of this module in npm is 1.5.3 but your version history does not include this version. I am trying to debug a messed up docker deployment and knowing the version with certainty is really important to me.

questions:
- Is this the repo behind the npm module mupx?
- what version is it at and what was the change to v1.5.3 if there is that version?

Thanks

**Comment by zodern** [comment]
This repository is for the npm package [mup](https://www.npmjs.com/package/mup) which is at version 1.4.6.

I think the version order is mup 0.x, then mupx, then mup 1.0.0 and newer. This package replaces mupx. There is a migration guide at http://meteor-up.com/docs.html#migrating-from-mupx.
