### ISSUE TITLE
mup setup fails to install random packages such as Stud or Node

### ISSUE THREAD

**Issue by askaliate** [zodern/meteor-up#1102]
Hello,

I am getting the following errors when trying to run **mup setup** on our various environments - does anyone know what could be going on?

Node  5.5.0
Mongo 3.2.6
Meteor 1.2.1
MUP (deployment tool) 0.11.3
Npm 3.3.12 (this should not count for much)

Started TaskList: Setup (linux)
[.cloudapp.net] - Installing PhantomJS
[.cloudapp.net] - Installing PhantomJS: SUCCESS
[.cloudapp.net] - Setting up Environment
[.cloudapp.net] - Setting up Environment: SUCCESS
[.cloudapp.net] - Installing Stud
[.cloudapp.net] x Installing Stud: FAILED

        -----------------------------------STDERR-----------------------------------
        rm: cannot remove ‘/var/cache/apt/archives/lock’: No such file or directory
        Splitting up /var/lib/apt/lists/partial/downloads-distro.mongodb.org_repo_ubuntu-upstart_dists_dist_InRelease into data and signature failedE: GPG error: http://downloads-distro.mongodb.org dist InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
        -----------------------------------STDOUT-----------------------------------
        tp://azure.archive.ubuntu.com trusty-backports/universe Translation-en
        Get:2 http://azure.archive.ubuntu.com trusty-updates/main Translation-en [582 kB]
        Get:3 http://azure.archive.ubuntu.com trusty-updates/multiverse Translation-en [7,616 B]
        Get:4 http://azure.archive.ubuntu.com trusty-updates/restricted Translation-en [4,028 B]
        Get:5 http://azure.archive.ubuntu.com trusty-updates/universe Translation-en [281 kB]
        Get:6 http://security.ubuntu.com trusty-security/universe Sources [102 kB]
        Get:7 http://azure.archive.ubuntu.com trusty/universe Sources [6,399 kB]
        Get:8 http://security.ubuntu.com trusty-security/universe amd64 Packages [294 kB]
        Get:9 http://security.ubuntu.com trusty-security/main Translation-en [448 kB]
        Get:10 http://security.ubuntu.com trusty-security/universe Translation-en [162 kB]
        Get:11 http://security.ubuntu.com trusty-security/main amd64 Packages [835 kB]
        Get:12 http://downloads-distro.mongodb.org dist InRelease
        Ign http://downloads-distro.mongodb.org dist InRelease

**Comment by zodern** [comment]
You are using a very old version of mup. Mup no longer installs stud or node itself and replaced them with nginx and docker. There is a migration guide at http://meteor-up.com/docs.html#migration-guide.
