### ISSUE TITLE
Change nginx config worker_connections 

### ISSUE THREAD

**Issue by mmueller1589** [zodern/meteor-up#1105]
I see lots of `1024 worker_connections are not enough` errors. Any idea how I can change the nginx config?

I need to update nginx.conf:

```
events {
	worker_connections **1024**;
}
```

How can I do that?

**Comment by zodern** [comment]
You can customize the nginx config: http://meteor-up.com/docs.html#custom-nginx-config
Create a file containing
```
events {
	worker_connections **1024**;
}
```
and add to your mup config:
```
proxy: {
  shared: {
    nginxConfig: './path/to/config',
  }
}
```
and run `mup proxy reconfig-shared`.

**Comment by mmueller1589** [comment]
I get this validation error:

```
2 Validation Errors
  - "proxy.domains" is required
  - "proxy" app.env.PORT is ignored when using the reverse proxy

Read the docs and view example configs at
    http://meteor-up.com/docs

The shared settings affect all apps using this reverse proxy.

Started TaskList: Configuring Proxy's Shared Settings

Started TaskList: Start proxy
```

The first one I can fix by adding `proxy.domains`. But the second one? I have no `app.env.PORT` set.

**Comment by brightchip** [comment]
Can you share your nginx configuration . I got the same error over and over .
So How do i create a default mup config file so that i could increase the worker_connections

**Comment by welkinwong** [comment]
> Can you share your nginx configuration . I got the same error over and over .
> So How do i create a default mup config file so that i could increase the worker_connections

same problem, how to fix this😭

**Comment by wildhart** [comment]
See: https://github.com/zodern/meteor-up/issues/1227#issuecomment-788317211
