### ISSUE TITLE
NGINX proxy - Are sticky sessions on by default?

### ISSUE THREAD

**Issue by ashishUthama** [zodern/meteor-up#1111]
Mup version (`mup --version`):
1.4.6

If my info is not out dated, I believe we should use sticky sessions when load balancing a meteor app. Does the NGINX proxy configured by mup do this out of the box? 

I tried to verify by looking at the conf file in the docker container and I did not see any ip hashing setup. 

Am I right in assuming that its not currently setup?

**Comment by zodern** [comment]
By default, the proxy doesn't do any load balancing. In mup 1.5, you will be able to use the `proxy.loadBalancing` option, which will enable load balancing and use sticky sessions.
