### ISSUE TITLE
Trying to deploy with bcrypt imported or wrapped as a non-core package

### ISSUE THREAD

**Issue by micahalcorn** [zodern/meteor-up#112]
I am getting `this app is not compatible with architecture 'os.linux.x86_64'` when I try to deploy an app which runs fine locally. I have tried using `import bcrypt from 'bcrypt'` or `meteor add npm-bcrypt` and both produce this error. I'm really just trying to find a way to use bcrypt similar to how it is used by Meteor's `accounts-password` package.

**Comment by MasterJames** [comment]
Make sure you've updated meteor version 1.3.2.2 (now 1.3.2.4 I think even?) helps with npm modules aspirations of 1.3 less problems with cross platform build errors like fibers and bcrypt. Hopefully that is/was the problem for you as its a recent release and has helped others.

**Comment by madushan1000** [comment]
This looks more like an error with meteor itself than meteor-up.

**Comment by micahalcorn** [comment]
I was able to resolve the issue of architecture incompatibility by upgrading from Meteor 1.3.0 to Meteor 1.3.2 thanks to @MasterJames. I am using the new `mup` now instead of `mupx` and it seems to work with `meteor add node-bcrypt`, thanks.
