### ISSUE TITLE
Mup Deploy Fails while building app with Meteor 1.9

### ISSUE THREAD

**Issue by xpressabhi** [zodern/meteor-up#1121]
meteor  --settings .deploy/settings.json Works as expected but mup deploy fails with below error

Mup version (`mup --version`):1.4.6

Mup config

{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "root"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../../app",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true,
      "debug": false
    },
    "env": {
      "ROOT_URL": "https://host.com",
      "MONGO_URL": "mongodb://mongodb:27017/my-app",
      "VIRTUAL_HOST": "domain.com",
      "HTTPS_METHOD": "redirect",
      "HTTP_FORWARDED_COUNT": 1,
      "LETSENCRYPT_HOST": "domain.com",
      "LETSENCRYPT_EMAIL": "email.com"
    },
    "docker": {
      "image": "abernix/meteord:node-12-base",
      "stopAppDuringPrepareBundle": false,
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "deployCheckWaitTime": 120,
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "proxy": {
    "domains": "domain.com",
    "ssl": {
      "forceSSL": true,
      "letsEncryptEmail": "email.com"
    }
  },
  "mongo": {
    "port": 27017,
    "version": "4.0.6",
    "servers": {
      "one": {}
    }
  }
Output of command

mup deploy --settings settings.json --verbose > output.txt
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Node#moveTo was deprecated. Use Container#append.
Errors prevented bundling:
While minifying app code:

/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63:
Unexpected token (1:8) while minifying
dynamic/imports/ui/components/answers/answerchart.html
at Object.raise
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63)
at Object.unexpected
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/util.js:160:16)
at Object.parseIdentifierName
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/expression.js:2160:18)
at Object.parseIdentifier
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/expression.js:2127:23)
at Object.parseFunctionId
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:1095:52)
at Object.parseFunction
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:1047:22)
at Object.parseFunctionStatement
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:555:17)
at Object.parseStatementContent
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:185:21)
at Object.parseStatement
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:141:17)
at Object.parseStatement
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/plugins/flow.js:1675:28)
at Object.parseBlockOrModuleBlockBody
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:860:25)
at Object.parseBlockBody
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:836:10)
at Object.parseTopLevel
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:47:10)
at Object.parseTopLevel
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/plugins/flow.js:2913:30)
at Object.parse
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/index.js:43:10)
at Object.parse
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/index.js:58:38)
at parse
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/parser.js:7:22)
at Object.minify
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:184:5)
at Object.minify (packages/babel-compiler.js:59:29)
at meteorJsMinify (packages/minifier-js.js:60:25)
at packages/minifyStdJS/plugin/minify-js.js:126:20
at Array.forEach (<anonymous>)
at MeteorBabelMinifier.processFilesForBundle
(packages/minifyStdJS/plugin/minify-js.js:118:9)

While minifying app code:

/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63:
Unexpected token (1:8) while minifying
dynamic/imports/ui/components/answers/answerchart.html
at Object.raise
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63)
at Object.unexpected
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/util.js:160:16)
at Object.parseIdentifierName
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/expression.js:2160:18)
at Object.parseIdentifier
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/expression.js:2127:23)
at Object.parseFunctionId
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:1095:52)
at Object.parseFunction
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:1047:22)
at Object.parseFunctionStatement
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:555:17)
at Object.parseStatementContent
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:185:21)
at Object.parseStatement
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:141:17)
at Object.parseStatement
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/plugins/flow.js:1675:28)
at Object.parseBlockOrModuleBlockBody
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:860:25)
at Object.parseBlockBody
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:836:10)
at Object.parseTopLevel
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:47:10)
at Object.parseTopLevel
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/plugins/flow.js:2913:30)
at Object.parse
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/index.js:43:10)
at Object.parse
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/index.js:58:38)
at parse
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/parser.js:7:22)
at Object.minify
(/Users/abhishekmaurya/.meteor/packages/standard-minifier-js/.2.6.0.16nutyv.ncxx++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:184:5)
at Object.minify (packages/babel-compiler.js:59:29)
at meteorJsMinify (packages/minifier-js.js:60:25)
at packages/minifyStdJS/plugin/minify-js.js:126:20
at Array.forEach (<anonymous>)
at MeteorBabelMinifier.processFilesForBundle
(packages/minifyStdJS/plugin/minify-js.js:118:9)

**Comment by xpressabhi** [comment]
Recreated repo to solve this.

**Comment by jankapunkt** [comment]
@xpressabhi did you resolve this issue on your own? If so, what was the cause for it?
