### ISSUE TITLE
Delete extraced bundle after Prepare Bundle finishes

### ISSUE THREAD

**Issue by zodern** [zodern/meteor-up#1127]
Mup leaves behind the extracted bundle until it is deleted during the next deploy. It is unused, and when multiple apps are deployed to the same server the disk space adds up.

**Comment by zodern** [comment]
This no longer happens when the `app.docker.useBuildKit` option is enabled, and in the future it will become the default.

**Comment by idanwe** [comment]
@zodern Hi, I'm having that problem and want to use your fix.
Is it need to be like that?
```js
docker: {
  image: ...,
  useBuildKit: true
}
```
Do you know if I can read about it somewhere?

**Comment by zodern** [comment]
That is correct @idanwe. The only place it is currently documented is in the [example config](http://meteor-up.com/docs.html#everything-configured).
