### ISSUE TITLE
mup deploy fail

### ISSUE THREAD

**Issue by yubozhao** [zodern/meteor-up#113]
App is 1.3.2.4.  When I try to deploy: 

`$ mup deploy
(node:39445) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Building App Bundle Locally
Error If encoding is specified then the first argument must be a string
`

This happen in mup(old) mupx and this mup

**Comment by yubozhao** [comment]
Link the issue from old mup:  https://github.com/arunoda/meteor-up/issues/985

**Comment by MasterJames** [comment]
Probably a dumb question but: Who's using graceful-fs your side?  Is it updated?  What version? Otherwise must be a deeper dependency maybe? I'll have to look into what graceful-fs is.

**Comment by ixdi** [comment]
Ok I think it's because graceful-fs@^4.0.0 dependency is needed as version <= 3.0.0 fails for node releases >= 6.0.
A warning appears when installing mup.
silent-npm-registry-client@2.0.0 dependency is needed. This step is easy.
Package nofat depends on mocha that depends on glob (v3.2.3) but glob@7.0.3 is the current release :( This cause graceful-fs to be outdated

**Comment by wdhif** [comment]
I can also confirm this issue for mupx https://github.com/arunoda/meteor-up/tree/mupx

**Comment by yubozhao** [comment]
@MasterJames No one is using graceful-fs.  I think it is used @ixdi has the right explanation about it.

**Comment by yubozhao** [comment]
Do we have a workaround on this?  Haven't had a chance to look into it more

**Comment by wdhif** [comment]
You just have to go back to node 5.11

**Comment by ixdi** [comment]
mocha accepted my pull request to update glob, so maybe is about few time that this is resolved.

**Comment by kylepierce** [comment]
Had to go back to 5.8 to deploy

**Comment by jacobmischka** [comment]
According to [this](https://github.com/arunoda/meteor-up/pull/1050), upgrading archiver to 1.0 fixes it. It does indeed fix it for me, but I don't have a spare ubuntu machine or vm on which to run tests, so I'm not going to submit a pull request until it's been tested. 

Thanks @mkpazon!
