### ISSUE TITLE
Deploying to AWS ec2 server and Atlas

### ISSUE THREAD

**Issue by AhmedMohamedG** [zodern/meteor-up#1132]
Hi,

I want to deploy to ec2 and atlas I want to know how to configure variables for deployment

```
env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: '',
     MONGO_URL: 'mongodb://mongodb/meteor',
      MONGO_OPLOG_URL: 'mongodb://mongodb/local',
    },
```
I think this answer is outdated   [ How to config `mup.js` whit Mongo Atlas? #930 ](https://github.com/zodern/meteor-up/issues/930)

**Comment by cunneen** [comment]
Not outdated. I used it yesterday for two different deployments, it works fine. You need to set the MONGO_URL and MONGO_OPLOG_URL to the correct values, which Atlas should provide you with.

**Comment by AhmedMohamedG** [comment]
I only have the MONGO_URL in Atlas. I don't have the MONGO_OPLOG_URL (I have already created the OPLOG user with read permissions @ local)

**Comment by cunneen** [comment]
This guide is useful for setting up atlas with meteor. See in particular step 7.2 .

https://medium.com/@cfnelson/mongodb-atlas-with-meteor-a-step-by-step-guide-da34093665f4

**Comment by AhmedMohamedG** [comment]
Thanks @cunneen I will do that

**Comment by AhmedMohamedG** [comment]
The problem is solved now and I have deployed the app to EC2 and Atlas.
This is how I have set the variables:

```
 env: {

 ROOT_URL: 'http://<EC2 instance DNS address>:80',
"MONGO_URL" : "mongodb+srv://<User Name>:<Password>@<Leave as provided by Atlas>.mongodb.net/meteor?retryWrites=true&w=majority",
	
 "MONGO_OPLOG_URL": "mongodb+srv://<User Name>:<Password>@<Leave as provided by Atlas>.mongodb.net/local?retryWrites=true&w=majority"

```
This post was very helpful

https://forums.meteor.com/t/deploy-app-galaxy-and-atlas-mongodb/49975/3
