### ISSUE TITLE
SSH upload stalled with node 14.2.0

### ISSUE THREAD

**Issue by erixtekila** [zodern/meteor-up#1148]
Mup version (`mup --version`): 
1.4.5 and 1.5.0-beta-11

On osx 10.13, with node 14.2.0 installed with `homebrew`, the ssh upload task will block at random percent.
No errors nor logs.

Donwgrading to node 12.16.3, fix the issue.
HTH

**Comment by n1kio** [comment]
@erixtekila Thank you so much, it took me one day to figure out that it was the node version preventing the deployment. 12.16.3 works, 14.2.0 does not.

**Comment by heticeric** [comment]
You're welcome @n1kio 
Same here, unfortunatly !
Sharing this info might help ohers, i hope.

**Comment by erixtekila** [comment]
You're welcome @n1kio 
Same here, unfortunatly !
Sharing this info might help ohers, i hope.

**Comment by zodern** [comment]
Could you please try again with mup 1.5.1? Some of the dependencies were updated since beta11 with fixes for node 14.

**Comment by erixtekila** [comment]
Sure @zodern !

**Comment by erixtekila** [comment]
I can confirm that mup@1.5.1 seems to fix the issue.
I've been able to upload the meteor's bundle with a fresh nodejs@14.4.0

**Comment by ryan-lgtm** [comment]
Hate to comment on a closed issue; but I had the exact same thing happen despite mup 1.5.1 and was using node 14.5.0 (installed via NVM; OS X 10.15.7).

Ryan-MacBook-Air:.deploy ryanle$ mup deploy
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[23.92.20.116] - Pushing Meteor App Bundle to the Server
[=                                      ] 5% 66.8s^X^C
Ryan-MacBook-Air:.deploy ryanle$ mup deploy
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[23.92.20.116] - Pushing Meteor App Bundle to the Server
[                                       ] 3% 92.4s^C


Did an ol' `nvm install 12.18.4`, `npm install --global mup` and re-ran `mup deploy`; no issues at all. Not sure where the conflicts are coming from, but also happy to help.
