### ISSUE TITLE
Dependencies need to be mentioned in README

### ISSUE THREAD

**Issue by mariusglauer** [zodern/meteor-up#116]
As far as i am concerned, the following dependencies are needed on the destination server (and were not installed from a standard debian 8.0 installation):
- sudo
- curl
- docker-engine

They should either be mentioned in the README or automatically installed via `mup setup`. I spent quite some time figuring out `curl` was missing on my fresh VPS installation.

**Comment by madushan1000** [comment]
Mup is currently only recommended to deploy to Ubuntu-14.04LTS only.
