### ISSUE TITLE
 network mup-proxy not found

### ISSUE THREAD

**Issue by eugle** [zodern/meteor-up#1162]
network mup-proxy not found
No such container: mup-nginx-proxy-letsencrypt

module.exports = {
	servers: {
		one: {
			host: '0.0.0.0',
			username: 'username', 
			password: 'password',
			opts: {
				port: 00,
			},
		},
		two: {
			host: '0.0.0.0',
			username: 'username',
			password: 'password',
			opts: {
				port: 00,
			},
		},
	},
	app: {
		name: 'name', 
		path: '../../', 
		type: 'meteor',
		volumes: {
			'/etc/localtime': '/etc/localtime', 
			'/home/xx/xx':'/data',
		},
		docker: {
			image: 'abernix/meteord:node-12.16.1-base',
			prepareBundle: true,
		},
		servers: {
			one: {},
			two: {},
		},
		buildOptions: {
			serverOnly: true,
			debug: false,
			allowIncompatibleUpdates: true,
		},
		env: {
			PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1,
			HTTP_FORWARDED_COUNT: 1,
			testMode: 1,
			enumCordova: 1,
			PORT: 4802,
			ROOT_URL: 'https://www.domain.com/', 
			MONGO_URL: '', 
		},
		enableUploadProgressBar: true,
		deployCheckWaitTime: 600, 
	},
	proxy: {
		servers: {
			one: {},
			two: {},
		},
		domains: 'a.com,www.a.com',
		loadBalancing: true,
		ssl: {
			forceSSL: true
		}
	},
};

Deployment log：

![image](https://user-images.githubusercontent.com/24447931/84529281-c5a30300-ad13-11ea-8ce8-0ddd7425ae89.png)

What am I doing wrong? Help me，thanks

**Comment by zodern** [comment]
What does `mup proxy setup --verbose` show?

**Comment by eugle** [comment]
mup setup

thanks

**Comment by eugle** [comment]
`docker: Error response from daemon: driver failed programming external connectivity on endpoint mup-nginx-proxy (202a63676d1d07eff41e84933e2295789575a1796f9bdbfc68ccf5287745c554): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.`

Should Nginx not be installed on Server? I installed Docker and Nginx on the server before mup Setup, and then started using mup Setup

**Comment by eugle** [comment]
Resolved, I deleted the Default profile of Nginx on the server，Is very perfect
