### ISSUE TITLE
Setup and deploy doesn't work

### ISSUE THREAD

**Issue by idanwe** [zodern/meteor-up#117]
It looks like nothing really happes
after clone the repo & npm install & npm run prepublish & npm link

I create `.deploy` dir in my project 
create `mup.js` and `settings.json` inside it by running `mup init`

then I tried to deploy and got this logs

``` bash
➜  .deploy git:(master) ✗ DEBUG=* mup setup
  mup:module:default exec => mup setup +0ms
  mup:module:docker exec => mup docker setup +8ms
```

``` bash
➜  .deploy git:(master) ✗ DEBUG=* mup deploy
  mup:module:default exec => mup deploy +0ms
  mup:module:meteor exec => mup meteor deploy +3ms
  mup:module:meteor exec => mup meteor push +8ms
Building App Bundle Locally
```

And here is my `mup.js` 

```
module.exports = {
  servers: {
    one: {
      host: meteorHost,
      username: 'root',
      pem: "~/.ssh/id_rsa"
    },
  },

  meteor: {
    name: 'app',
    path: path.resolve('..'),
    servers: {
      one: {},
    },
    env: {
      ROOT_URL: 'http://' + meteorHost,
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    dockerImage: 'gdw2/docker-meteord-buzz',
    deployCheckWaitTime: 60 // default 10
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

What am I missing?

**Comment by madushan1000** [comment]
Are those all the logs you are getting? No errors?

**Comment by idanwe** [comment]
Yes only those logs

And I success to deploy with mup and mupx from arunoda/meteor-up

My Node version is v5.2.0, should I provided more information?

**Comment by madushan1000** [comment]
That's strange. Can you check if there are any docker containers running on the server after this?

**Comment by idanwe** [comment]
There aren't

**Comment by johannchen** [comment]
I only see "Building App Bundle Locally", What other log messages suppose to show?

**Comment by MasterJames** [comment]
isn't there a `mup setup` step missing?
`mup init <project name>`

**Comment by johannchen** [comment]
No, I didn't miss the "mup setup". It seems the "mup deploy" does nothing.

**Comment by MasterJames** [comment]
Your going to need to try stepping through the code manually or putting extra console logging etc.
Or I guess there's tests?
First point here.
https://github.com/kadirahq/meteor-up/blob/d36f4edecd99b95955e337fa07fb40ee648353b7/src/modules/default/index.js#L12

Then this should test config
But you could add a log of the values etc.
https://github.com/kadirahq/meteor-up/blob/08f5f2ef2567494fff021e554cf761ff3f52b5ee/src/modules/meteor/index.js#L177

**Comment by comigor** [comment]
@idanwe mine started working when I removed the `pem: "~/.ssh/id_rsa"` line

**Comment by j6k4m8** [comment]
@idanwe @Igor1201 Using an absolute path for your pem should fix this.

**Comment by ayushchd** [comment]
Any luck here? I have an absolute path for my pem file but I am facing the same issue as the OP

```
module.exports = {
  servers: {
    one: {
      host: '{hostname}',
      username: 'ubuntu',
      pem: '{absolute_path_to_pem}',
    },
  },

  meteor: {
    name: 'project_name',
    path: '/app',
    servers: {
      one: {},
    },
    env: {
      ROOT_URL: url,
      MONGO_OPLOG_URL: mongo_oplog_url,
      MONGO_URL: mongo_url
    },
  }
};
```

**Comment by j6k4m8** [comment]
Try a `nodeVersion` of `0.10.43`, and roll back your meteor version to 1.3.1: `meteor update --release "1.3.1"`.

I can't believe this is required, and I wish the developers would find a way to make this work with latest Meteor/node. But at least in my this-needs-to-be-online-immediately case, I'm satisfied.

@madushan1000, are there fixes for this in the works?

**Comment by MasterJames** [comment]
Maybe your PEM is malformed? 
http://stackoverflow.com/questions/991758/how-to-get-an-openssl-pem-file-from-key-and-crt-files
You cat them together.

**Comment by j6k4m8** [comment]
I can confirm that with a fully valid PEM, we still encounter this error.

**Comment by mlumbroso** [comment]
@j6k4m8  I have the same problem, tried to downgrade node and Meteor as you suggested but it didn't change the fact it hangs forever on Building App Bundle Locally with no more details. Any thoughts? Were there the only steps you tried to make it work?

Thanks

**Edit** : retrying finally made it work, I can confirm your steps fixed the problem :-) Thanks a lot for this

**Comment by j6k4m8** [comment]
glad it helped!!

**Comment by idanwe** [comment]
@j6k4m8 Change to absolute path fixed it, thanks alot
