### ISSUE TITLE
mup deploy --verbose stop at Pushing Meteor App Bundle to the Server 0% (Node -v 14.4.0)

### ISSUE THREAD

**Issue by Bariyard** [zodern/meteor-up#1171]
mup deploy --verbose stop at Pushing Meteor App Bundle to the Server 0%
I try this on Macbook Pro 2020 terminal
However this problem not occur in my Old Macbook with same version
Mup version :1.5.1

Mup config

```js
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: 'my-ip',
      username: 'root',
      pem: '~/.ssh/id_rsa',
    }
  },

  app: {
    name: 'myproject',
    path: '../',
    type: 'meteor',
    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      ROOT_URL: 'https://my-ip,
    },

    docker: {
      image: 'abernix/meteord:node-12.16.1-base',
    },

    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  },

  proxy: {
    domains: 'mydomain.com,www.mydomain.com',

    ssl: {
      forceSSL: true,
      letsEncryptEmail: 'email@gmail.com',
    }
  }
};

```

Output of command

```bash
Building App Bundle Locally
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
                                           
Started TaskList: Pushing Meteor App
[myip] - Pushing Meteor App Bundle to the Server
[                                       ] 0% 0.0s
```

Edited: Reproducable on Node version 14.4.0

**Comment by PineappleIOnic** [comment]
I've been getting this issue aswell, but when I deploy using a circleCI server which seems to halt it at 0% until it eventually hits my timeout.

**Comment by cesarve77** [comment]
it was happening to mw with node 14,.
With node 12 is working again

**Comment by zodern** [comment]
@cesarve77 are you using mup 1.5.1?

**Comment by PineappleIOnic** [comment]
Node 12 also fixed it for my CI Server aswell, I don't know what might of changed between 12 and 14 I'll try looking into it

**Comment by cesarve77** [comment]
Yeah 1.5.1.

Last version

**Comment by derwaldgeist** [comment]
Same problem here. I had just updated to Node 14.4.0 and noticed that mup won't deploy anymore. Upload stops at 0%. Going back to 12.8.2 solved the problem.

**Comment by maxcrystal** [comment]
Same problem (Node 14.5.0)

**Comment by programthis** [comment]
Are there any other solution for this issue? My app is still at Node 12 but my upload stops at 0%.

**Comment by s7dhansh** [comment]
Fails on 14.12.0 too.

**Comment by krstffr** [comment]
Yep, works on 12.19.0, not versions 14.

**Comment by zodern** [comment]
Node 14.15.2 fixes this.
