### ISSUE TITLE
'#!' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by caffpain** [zodern/meteor-up#1172]
Mup version (`mup --version`):
1.5.1

Mup config
module.exports = {
  servers: {
    one: {
      host: '192.168.68.132', // WINDOWS 10 DEV VM
      username: 'slave',
      password: 'asteriskx8',
    },
  },

  app: {
    name: 'hello',
    path: '../',

    servers: {
      one: {
      },
    },

    buildOptions: {
      serverOnly: true,
      executable: 'meteor'
    },

    env: {
      ROOT_URL: 'http://192.168.68.132',
      MONGO_URL: 'mongodb://localhost/meteor',
      MONGO_OPLOG_URL: 'mongodb://mongodb/local',
    },

    docker: {
      image: 'abernix/meteord:node-12-base',
    },

    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  },
};

Output of command
$mup setup --verbose

Started TaskList: Setup Docker
[192.168.68.132] - Setup Docker
'#!' is not recognized as an internal or external command,
operable program or batch file.
[192.168.68.132] x Setup Docker: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      '#!' is not recognized as an internal or external command,
	operable program or batch file.
	
	      ------------------------------------STDOUT------------------------------------
	      
	      ------------------------------------------------------------------------------

**Comment by zodern** [comment]
What OS does the server use? Did you change the default shell?

**Comment by caffpain** [comment]
Hi,
   Server was running Windows 10

**Comment by zodern** [comment]
Meteor Up does not support deploying to Windows servers. It requires the server to be running Ubuntu.
