### ISSUE TITLE
Feature request - Command to update docker version

### ISSUE THREAD

**Issue by ninjaPixel** [zodern/meteor-up#1174]
Mup version (`mup --version`): 1.5.1

I read in the docs:
> Since mup 1.3, `mup setup` and `mup docker setup` will update Docker if it is older than 1.13.

It would be really nice to have a command that works for more recent versions of Docker (I needed to upgrade a server from Docker 18 -> 19 this morning, so that I could use the new `useBuildKit` option).

Thanks for the great work ✌️

**Comment by zodern** [comment]
This was added in mup 1.5, though missing from the changelog. You can run `mup docker update` to update Docker to the latest version.
