### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by rcsandell** [zodern/meteor-up#1176]
https://github.com/zodern/meteor-up/blob/48c5796e2a76c37834a7d8a4b85f3c1ee3581bec/src/plugins/meteor/assets/meteor-deploy-check.sh#L80

There appears is a spelling mistake in the deploy-check script. It reads "CONTAINER IP EMPTRY" when it probably should say "CONTAINER IP EMPTY".

**Comment by zodern** [comment]
Thanks @rcsandell. This is fixed in 1.5.2-beta.5.
