### ISSUE TITLE
Meteor container goes down

### ISSUE THREAD

**Issue by wizonesolutions** [zodern/meteor-up#118]
The Meteor container seems to randomly crash...sometimes it's up for weeks, sometimes one day. `mup deploy` gets it working again. Not sure if application issue or not — `mup logs` seems to only show current logs. Are more logs saved anywhere by default? Is Mongo automatically run with write concern and read preference set, or do I do that in my own `MONGO_URL`? I put `oplog: true` but I only set up one Mongo. Could that be it?

Edit: config —

``` javascript
module.exports = {
  servers: {
    appdev: {
      host: 'server.example.com',
      username: 'core',
      // password: 'toor',
      // pem: '/path/to/id_rsa',
    },
  },

  meteor: {
    name: 'app',
    path: '../',
    servers: {
      appdev: {},
    },
    env: {
      ROOT_URL: 'http://app.example.com',
      MONGO_URL: 'mongodb://localhost/meteor',
    },
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      appdev: {},
    },
  },
};
```

**Comment by madushan1000** [comment]
If you want features like oplog, you have to set up your own mongo and set `MONGO_URL`. Mup uses `meteorhacks/meteord` docker image, check its issue page to see if there any known behaviours like this. You can get your error logs by running `mup logs` after the container crashed.

**Comment by MasterJames** [comment]
To enable oplog I thought you could put this
`master=true`
into
https://github.com/kadirahq/meteor-up/blob/master/src/modules/mongo/assets/mongodb.conf
or something? no?

**Comment by wizonesolutions** [comment]
Container went down again. Checked `meteor logs`, but nothing that would indicate a crash was there. What else might I check? The node is using CoreOS on Digital Ocean.

**Comment by madushan1000** [comment]
mup/mupx both only supports deploying to ubuntu-14.04 LTS only right now. Even if you could deploy into CoreOS, I'm not sure what kind of issues there will be.

**Comment by wizonesolutions** [comment]
Hmm, but isn't Docker just Docker? Nonetheless, I'll try on Ubuntu and see
if it's more stable.

**Comment by madushan1000** [comment]
Mup uses some unix tools to setup the environment. There might be some issues running the commands. (They might work fine too). We haven't tested mup on CoreOS so we have no idea what could be the issue.

**Comment by wizonesolutions** [comment]
Yeah, everything seems ok but then the app crashes mysteriously sometimes
and has to be redeployed. docker ps only shows Mongo at such times.

**Comment by wizonesolutions** [comment]
OK, I have moved to Ubuntu 14.04 LTS now. Hopefully the uptime will be better. I'll open a separate issue if not.
