### ISSUE TITLE
mup deploy is no longer able to push to either of my servers

### ISSUE THREAD

**Issue by djlogan2** [zodern/meteor-up#1183]
I can no longer successfully push a deploy to a server. I have tried on two different servers, and sometimes it will push to a non-zero percent (say 18% or whatever) and then hang, sometimes it will just hang right out of the gate.

I have reinstalled node_modules, deleted/redefined server directories, rerun setup, ensured previous cached builds were deleted, rebooted my server, and probably more. At this point, I do not know what else to do other than ask what else I can do.

Mup version (`mup --version`):
```bash
davidlogan@DAVIDs-MacBook-Pro .deploy % mup --version
1.5.1
davidlogan@DAVIDs-MacBook-Pro .deploy % 
```
Mup config

```js
davidlogan@DAVIDs-MacBook-Pro .deploy % mup validate --show --scrub
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "david",
      "pem": "~/.ssh/pem"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true,
      "debug": true
    },
    "env": {
      "ROOT_URL": "http://subdomain.subdomain.host.com",
      "MONGO_URL": "mongodb://mongodb:27017/my-app",
      "MONGO_OPLOG_URL": "mongodb://mongodb/local"
    },
    "docker": {
      "image": "iccserver_base",
      "stopAppDuringPrepareBundle": true,
      "imagePort": 3000,
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "mongo": {
    "version": "3.6.3",
    "servers": {
      "one": {}
    },
    "dbName": "iccserver"
  }
}
✓ Config is valid
davidlogan@DAVIDs-MacBook-Pro .deploy % 
```

Output of command

```bash
davidlogan@DAVIDs-MacBook-Pro .deploy % mup deploy --verbose
Building App Bundle Locally
Unable to resolve some modules:
  "react-chessground/dist/assets/theme.css" in /Users/davidlogan/workspace/icc/iccserver/imports/ui/pages/components/AppWrapper.js (web.browser)
If you notice problems related to these missing modules, consider running:
  meteor npm install --save react-chessground
Unable to resolve some modules:
  "react-chessground/dist/assets/theme.css" in /Users/davidlogan/workspace/icc/iccserver/imports/ui/pages/components/AppWrapper.js (web.browser.legacy)
If you notice problems related to these missing modules, consider running:
  meteor npm install --save react-chessground
Unable to resolve some modules:
  "react-chessground/dist/assets/theme.css" in /Users/davidlogan/workspace/icc/iccserver/imports/ui/pages/components/AppWrapper.js (web.cordova)
If you notice problems related to these missing modules, consider running:
  meteor npm install --save react-chessground
   Building the application                
Started TaskList: Pushing Meteor App
[54.145.233.19] - Pushing Meteor App Bundle to the Server
[                                       ] 0% 0.0s
```

**Comment by kations** [comment]
Had the same problem, try to use node 12. I had this problem after upgrade to node 14

**Comment by djlogan2** [comment]
Yes, downgrading to node 12 works for me as well. Is this a node issue or a mup issue?

**Comment by derwaldgeist** [comment]
Is there any ETA for a fix? Just fell into the same trap after moving to another Mac.

**Comment by kevinashworth** [comment]
Same here; new Mac. It was stuck on `Pushing Meteor App Bundle to the Server` for the longest time. The comments in this issue saved me! Because I have [n](https://github.com/mklement0/n-install) installed, I simply ran `n 12` before running `mup deploy`. Phew.

**Comment by zodern** [comment]
The `ssh2` package is being rewritten, so it will be a while before there is a new version with the fix. I am looking into a work around, but it will likely slow down uploading the bundle.

I've read node 15 reverted the change that broke this, but I haven't tried it yet.

**Comment by derwaldgeist** [comment]
Thanks for the fast response!

**Comment by zodern** [comment]
Mup 1.5.2 will show a warning if you are using Node 14.0 - 14.15. The next version of node 14 should have the fix back ported from Node 15.
