### ISSUE TITLE
sudo: a terminal is required to read the password

### ISSUE THREAD

**Issue by caffpain** [zodern/meteor-up#1189]
Mup version (`mup --version`): 1.5.1

Mup config
{
  "servers": {
    "one": {
      "host": "192.168.68.148",
      "username": "myusername",
      "password": "mypassword",
      "pem": "~/.ssh/id_rsa"
    }
  },
  "app": {
    "name": "hello",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true,
      "executable": "meteor"
    },
    "env": {
      "ROOT_URL": "http://127.0.0.1",
      "MONGO_URL": "mongodb://mongodb:27017/hello"
    },
    "docker": {
      "image": "abernix/meteord:node-12-base",
      "stopAppDuringPrepareBundle": true,
      "imagePort": 3000,
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "mongo": {
    "version": "3.4.1",
    "servers": {
      "one": {}
    },
    "dbName": "mydb"
  }
}
✓ Config is valid

Output of command
Started TaskList: Setup Docker
[192.168.68.148] - Setup Docker
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper

Major
Minor
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[192.168.68.148] x Setup Docker: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
	sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
	sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
	sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
	sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
	sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
	
	      ------------------------------------STDOUT------------------------------------
	      
	Major
	Minor
	
	      ------------------------------------------------------------------------------

**Comment by zodern** [comment]
What operating system is the server using? You probably need to follow these directions to allow `sudo` to be used without a password: http://meteor-up.com/docs.html#ssh-based-authentication-with-sudo

**Comment by caffpain** [comment]
thanks! will now close the issue
