### ISSUE TITLE
Docker bypasses firewall rules. Simple edit of /etc/default/docker fixes.

### ISSUE THREAD

**Issue by jcheroske** [zodern/meteor-up#119]
Docker's default behavior is to add a new rule chain, called DOCKER, to iptables. This behavior, coupled with the docker publish call in `/src/modules/meteor/assets/templates/start.sh` causes the published port to be available on all interfaces regardless of existing firewall rules. Iptables wrappers, such as ufw, are totally ignorant of the change and report the current state of the rule chain incorrectly. This is a docker problem and is a known issue within the sysadmin community:

https://fralef.me/docker-and-iptables.html
http://blog.viktorpetersson.com/post/101707677489/the-dangers-of-ufw-docker

The fix is to set the docker option `"--iptables=false"` and then to punch holes in the firewall as needed. There are other, possibly more robust fixes, such as using docker networking, but they are much more complex and probably unnecessary from a mupx standpoint. 

I don't know if the `--iptables` option can be set on the command line directly. I was able to set it by editing the `/etc/default/docker` file, and adding the line:

```
DOCKER_OPTS="--iptables=false"
```

I'm deploying my mupx app to Digital Ocean, and using an nginx reverse SSL proxy in front of it. Communication between the proxy and the meteor server is via DO's private networking. To open up the meteor server's port only on the private network interface, I issued the following:

```
ufw allow to <private_ip> port <meteor_port>
```

*_I think mupx needs to make disabling docker's iptables editing the default, and then to simply inform the user that the firewall rules may need modification. Otherwise, all mupx installs could be creating security holes. *_

Because mupx, at least the version over at arunoda/meteor-up, verifies the meteor server by connecting to 127.0.0.1, the mupx deploy will succeed even if the firewall doesn't allow outside traffic. I think this is a good thing.

**Comment by madushan1000** [comment]
I can't reproduce this on a digitalocean 512MB droplet with ubuntu 14.04 using `kadirahq/meteor-up`.

**Comment by jcheroske** [comment]
If you examine your iptables rules, do you see a DOCKER chain that's
allowing all traffic to the Meteor port?

**Comment by madushan1000** [comment]
Sorry, I didn't understand the issue properly last time. I can see a docker chain 

```
Chain DOCKER (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:27017
ACCEPT     tcp  --  anywhere             172.17.0.3           tcp dpt:http
```

**Comment by jcheroske** [comment]
There are really two issues going on here. 

1) The DOCKER chain is opening up the meteor (and apparently the mongo port as well) to traffic on all interfaces. This seems to be unnecessary. Simply using the "--iptables="false" flag causes the DOCKER chain to be empty, but everything still works on my Digital Ocean VPS without it. For instance, doing a `mupx deploy` works fine, and the installation is able to be verified on `localhost:<meteor_port>`.

2) Because the iptables rules are being altered directly, tools such as ufw are ignorant that ports have been opened and incorrectly report the state of the firewall. Although this is not a mupx problem directly, mupx can surprise fewer admins by simply not allowing docker to alter iptables.

**Comment by mikemeier** [comment]
This would be fixed with https://github.com/kadirahq/meteor-up/blob/master/src/modules/meteor/assets/templates/start.sh#L31

You can override docker parameters now. It's not really a mup problem, its a docker "feature": https://fralef.me/docker-and-iptables.html
