### ISSUE TITLE
The deployment process is long and Always install Node-pre-gyp and freeze

### ISSUE THREAD

**Issue by eugle** [zodern/meteor-up#1192]
The deployment process is long and stuck in the middle; use -verbose to see the code for stop as follows

/babel-compiler/node_modules/magic-string
#10 18.51 sourcemap-codec@1.4.8 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/sourcemap-codec
#10 18.51 meteor-babel@7.9.0 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel
#10 18.51 meteor-babel-helpers@0.0.3 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel-helpers
#10 18.51 reify@0.20.12 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify
#10 18.51 typescript@3.8.3 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/typescript
#10 18.80 
#10 18.80 > core-js@3.5.0 postinstall /built_app/programs/server/npm/node_modules/meteor/url/node_modules/core-js
#10 18.80 > node -e "try{require('./postinstall')}catch(e){}"
#10 18.80 
#10 18.85 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
#10 18.85 
#10 18.85 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
#10 18.85 > https://opencollective.com/core-js 
#10 18.85 > https://www.patreon.com/zloirock 
#10 18.85 
#10 18.85 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
#10 18.85 
#10 18.86 core-js@3.5.0 /built_app/programs/server/npm/node_modules/meteor/url/node_modules/core-js
#10 20.34 
#10 20.34 > node-libcurl@2.1.1 install /built_app/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl
#10 20.34 > node-pre-gyp install --fallback-to-build
#10 20.34 
#10 20.56 node-pre-gyp WARN Using request for node-pre-gyp https download

Seems node-pre-gyp can't be installed? How should I solve using MUP 1.5.1，Thank you

**Comment by zazzool** [comment]
The same issue. Everything is freezing at Prepare Bundle step. Cannot deploy.

**Comment by eugle** [comment]
#10 182.1 Considering PhantomJS found at /usr/local/bin/phantomjs
#10 182.6 Found PhantomJS at /usr/local/bin/phantomjs ...verifying
#10 182.6 PhantomJS detected, but wrong version 1.9.8 @ /usr/local/bin/phantomjs.
#10 182.6 Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
#10 182.6 Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
#10 182.6 Receiving...

Phantomjs also causes unsuccessful deployments; is there a way to disable it
Deployed dozens of times, all without success, my location is in mainland China

**Comment by eugle** [comment]
#10 45.83 node-pre-gyp WARN Using request for node-pre-gyp https download 
#10 77.49 node-pre-gyp WARN Pre-built binaries not installable for nodejieba@2.5.1 and node@12.18.4 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
#10 77.49 node-pre-gyp WARN Hit error read ECONNRESET 

Stuck here all the time, deploy dozens of times occasionally have a success one success, is there a way to solve this problem

**Comment by eugle** [comment]
This problem does not appear on servers in Hong Kong, China. The problem appears on servers in mainland China

**Comment by eugle** [comment]
```
buildInstructions: [
				'RUN npm config set registry https://registry.npm.taobao.org',
				'RUN npm config set disturl https://npm.taobao.org/mirrors/node/',
				'RUN npm config set phantomjs_cdnurl https://npm.taobao.org/mirrors/phantomjs/',
			],
```

Configuring buildinStructions in Docker to point to Taobao source solves this problem
