### ISSUE TITLE
Is swarm required for load balancing?

### ISSUE THREAD

**Issue by edemaine** [zodern/meteor-up#1195]
* https://meteor-up.com/docs.html#swarm says that swarm is required for the features of load balancing and zero-downtime deploys:

  > Mup can setup and manage a Docker Swarm cluster. This is required for some features, such as load balancing and zero downtime deploys.

* https://zodern.me/posts/meteor-up-1-5/#load-balancing-and-zero-downtime-deploys seems to suggest that this can be done just with nginx proxy (and seems a bit discouraging about the use of Docker Swarm).

Which is right?

### Update

[On Gitter](https://gitter.im/meteor-up/Lobby?at=5f623bf4ea62d70e651728b4), @zodern wrote:

> @edemaine load balancing can be done with either swarm, or enabling the option for the proxy. This changed when 1.5 was almost finished, but the docs haven't been updated.

So this is a small documentation bug.

**Comment by carlos-olivera** [comment]
I faced problems deploying a meteor project on DigitalOcean using mup v.1.5.3, I had to init the Docker Swarm:

docker swarm init

After that the proxy related problems gone.
