### ISSUE TITLE
Meteor 1.3 change.  W/o --server-only or building mobile apps, mupx won't hot code-push to mobile

### ISSUE THREAD

**Issue by MichaelJCole** [zodern/meteor-up#121]
Hi, 

This [issue](https://github.com/arunoda/meteor-up/issues/981#issuecomment-218029367) and [pr](https://github.com/kadirahq/meteor-up/pull/120) were on the old repo.

TLDR; [Someone at meteor](https://forums.meteor.com/t/mupx-cordova-build/20745/4) commented that mupx won't build hot code pushes to mobile w/o having the android/ios platforms present when building.

Meteor mobile has two parts:  server-side hot code push and mobile app file (e.g. APK for android)

In Meteor 1.2, if there were android/ios platforms added it build build hot code push and mobile app files.  This was annoying if toolchains weren't present (e.g. ios on linux).  As a workaround, I found others were removing platforms before `mupx deploy` to avoid building the mobile apps.  I never tested it specifically, but hot code pushes seemed to be working.

In Meteor 1.3, `meteor build` won't build the hot code pushes w/o the platforms added.  But Meteor did add the 'meteor build --server-only' option to tell meteor build to build the mobile hot code pushes, but skip building the apps.  

MDG recommended changing mupx to use --server-only. 

There is already a PR for this: https://github.com/kadirahq/meteor-up/pull/120

**Comment by madushan1000** [comment]
I merged the PR for this.

**Comment by devdudeio** [comment]
is it possible to fix this for the old mupx ?
