### ISSUE TITLE
Multiple deployment not working

### ISSUE THREAD

**Issue by JWo1F** [zodern/meteor-up#122]
Hi all! Thx for mup.

I have a problem: when I try to deploy my app to multiple servers, I see just: "Pushing the Startup Script: SUCCESS". Then I waited about 1.5 hours.
1. version: last (from github)
2. my config: http://codepaste.net/8r1doj
3. ![image](https://cloud.githubusercontent.com/assets/1540715/15153868/97fffff4-16e3-11e6-9949-1ec2a8b69fcf.png)

When I try to upload to the single server all is OK.

**Comment by madushan1000** [comment]
Can you log into both the servers without a problem? and did you run `mup setup` before running `mup deploy`

**Comment by JWo1F** [comment]
@madushan1000, yeap, I can log into both servers. And I did run `mup setup`.

**Comment by madushan1000** [comment]
I can't see anything wrong with your config. does this happen every time you try to deploy?

**Comment by JWo1F** [comment]
@madushan1000  Yes, it does. I can create two test servers and try to deploy.
P.S: This feature works for you?

**Comment by madushan1000** [comment]
It worked a few commits ago, I'll try to find out what's going on.

**Comment by JWo1F** [comment]
@madushan1000 how to progress?

**Comment by madushan1000** [comment]
It looks like there something went wrong after es7 intigration. I'll look into that. Meanwhile you can checkout a commit before es7 intigration and work with it.

**Comment by cmaddalozzo** [comment]
When trying to deploy to multiple servers the process hangs at the exact same spot for me. Any progress on this?

<img width="716" alt="screenshot 2016-08-02 16 51 42" src="https://cloud.githubusercontent.com/assets/632443/17349323/8c7fd5ca-58d1-11e6-8100-5edb97819027.png">

**Comment by timbrandin** [comment]
When trying to deploy to multiple app servers, I get this, but it works to deploy to them individually by just removing the server from the list of servers to deploy to in the configuration for meteor.

```
[xxx.1] - Pushing Meteor App Bundle to The Server
[xxx.2] - Pushing Meteor App Bundle to The Server
[xxx.1] - Pushing Meteor App Bundle to The Server: SUCCESS
[xxx.1] - Pushing the Startup Script
[xxx.2] - Pushing Meteor App Bundle to The Server: SUCCESS
[xxx.2] - Pushing the Startup Script
[xxx.2] - Pushing the Startup Script: SUCCESS
[xxx.1] x Pushing the Startup Script: FAILED
    No response from server
```

Configuration for mup.json

``` js
module.exports = {
  servers: {
    one: {
      host: "xxx.1",
      username: "root"
    },
    two: {
      host: "xxx.2",
      username: "root"
    },
  },

  meteor: {
    name: "app",
    path: "../..",
    servers: {
      one: {}, two: {},
    },
    buildOptions: {
      serverOnly: true,
      debug: false,
      mobileSettings: {}
    },
    env: {
      ROOT_URL: "http://test",
      MONGO_URL: "mongodb://localhost/app",
      MONGO_OPLOG_URL: "mongodb://localhost/local"
    },
    "deployCheckWaitTime": 60,
  },
};

```

**Comment by vtocco** [comment]
Any updates on this? I am getting similar behavior. If I do one server at a time it works fine. I get a timeout error once every few times, but mainly it just hangs at:
DEBUG=\* mup deploy
  mup:module:default exec => mup deploy +0ms
  mup:module:meteor exec => mup meteor deploy +2ms
  mup:module:meteor exec => mup meteor push +4ms
Building App Bundle Locally

Started TaskList: Pushing Meteor
[server1] - Pushing Meteor App Bundle to The Server
  nodemiral:sess:server1 copy file - src: /tmp/30e07cdc-3da6-4d52-bf36-959e806ff736/bundle.tar.gz, dest: /opt/xxxxxxxx/tmp/bundle.tar.gz, vars: undefined +0ms
[server2] - Pushing Meteor App Bundle to The Server
  nodemiral:sess:server2 copy file - src: /tmp/30e07cdc-3da6-4d52-bf36-959e806ff736/bundle.tar.gz, dest: /opt/xxxxxxxx/tmp/bundle.tar.gz, vars: undefined +0ms
[server2] - Pushing Meteor App Bundle to The Server: SUCCESS
[server2] - Pushing the Startup Script
  nodemiral:sess:server2 copy file - src: /usr/lib/node_modules/mup/lib/modules/meteor/assets/templates/start.sh, dest: /opt/xxxxxxxx/config/start.sh, vars: {"appName":"xxxxxxxx","useLocalMongo":0,"port":80,"logConfig":{"opts":{"max-size":"100m","max-file":10}},"image":"abernix/meteord:base"} +1s
[server1] - Pushing Meteor App Bundle to The Server: SUCCESS
[server1] - Pushing the Startup Script
  nodemiral:sess:server1 copy file - src: /usr/lib/node_modules/mup/lib/modules/meteor/assets/templates/start.sh, dest: /opt/xxxxxxxx/config/start.sh, vars: {"appName":"xxxxxxxx","useLocalMongo":0,"port":80,"logConfig":{"opts":{"max-size":"100m","max-file":10}},"image":"abernix/meteord:base"} +1s
[server1] - Pushing the Startup Script: SUCCESS

So server 2 never finishes..

**Comment by mikemeier** [comment]
@madushan1000 When exactly was this es7 integrated? Maybe I'll have a look for a workaround. Could be for example synchron deploying instead of parallel. The bundling takes quite a lot of time, so the deployment would still speed up if this task only has to be done once.

**Comment by stefanve** [comment]
Not really related to the issue, but partly: Whats the deal with the object:

```
servers: {
      one: {},two: {}, ...etc
    },
```

are they supposed to be empty? Is it just an alternative to writing

```
servers: [
      "one", "two"
    ],
```

?

**Comment by mikemeier** [comment]
@stefanve actually not implemented but will later help to setup environmen/server vars per server.

**Comment by stefanve** [comment]
Thanks Mike. Tricky when an example file contains things that seemingly does nothing and are undocumented.

**Comment by guilcorp** [comment]
This is still an issue. Any update?

Parallel setup and deploy make errors and freeze. 
On my side mainly with SSL certificates copy and SSL verification in setup.
And for deployment, it's stuck on Pushing bundle on one of the server. 

If setup & deploy one by one works like a breeze. 

Is someone got a multi servers setup acting normally?

**Comment by mikemeier** [comment]
@guilcorp without ssl (I use haproxy for ssl termination and loadbalancing) and deployment with mup.js is only possible server after server. Ah and I dont use mongodb by meteor, I installed on 3 nodes (1 master with haproxy and mongodb / 2 nodes with meteor and mongodb) mongodb with replicaset by my self. (Provisioning done over ansible)

**Comment by guilcorp** [comment]
Thanks Mike! I use a Cisco ip loadbalancer, routing all traffic to my servers.
I tested to add the SSL on the load balancer, was not easy and not as update as needed for ssl-labs A+. I was using MUPX for months, worked great, it was a easy to setup and deploy on every server, including the copy of the SSL cert.

**Comment by PauloMarceloNogueira** [comment]
Hello!
My config is 
`servers: {
    one: {
      host: 'xxxxxxxx',
      username: 'xxxxx'
    },
    two: {
      host: 'xxxx',
      username: 'xxxxx'
    }
  },
  meteor: {
    name: 'linteMup',
    path: '../',
    servers: {
      one: {},two:{}
    },`

And doesn't work...
Any progress ?

**Comment by PauloMarceloNogueira** [comment]
@madushan1000 Any news?

**Comment by clayne11** [comment]
I have a branch where I fixed the issue by deploying in series rather than in parallel.

https://github.com/clayne11/meteor-up/tree/multi-server-deployment

There must be a race condition somewhere. Not sure about the race condition but at least this fixes the issue.
