### ISSUE TITLE
Mup supports Meteor 2.0 docker image in your mup config.

### ISSUE THREAD

**Issue by phanchanra** [zodern/meteor-up#1222]
Mup version (`mup --version`):

Mup config

```js
   My project meteor version 2.0. How can i deploy with Mup supports Meteor 2.0 docker image in my mup config.


```
![Screenshot from 2021-02-05 10-07-01](https://user-images.githubusercontent.com/8839249/106984423-26e37f00-679a-11eb-930a-71a3b2f393b4.png)
Output of command

```bash
I can not see docker images support meteor 2.0 
```

**Comment by zodern** [comment]
You can use the `zodern/meteor` image with any Node version. I will update the docs today.

**Comment by zodern** [comment]
The table has been updated: http://meteor-up.com/docs.html#meteor-support

**Comment by phanchanra** [comment]
thank your help.
