### ISSUE TITLE
module is not defined. Deploying fro Mac to AWS Ubuntu

### ISSUE THREAD

**Issue by mattiLeBlanc** [zodern/meteor-up#123]
Hi,

I am a bit puzzled we still have all those deployment issue. 
Especially when I am deploying from a mac to a clean AWS Ubuntu machine.
I thought this combo is widely supported.

Anyway,
my meteor project is currently using coffeescript and angular+meteor.
Setup works fine but when I deploy I get a 

```

    -----------------------------------STDERR-----------------------------------
    npm WARN deprecated will be bundled with a version of npm@2, which has some small
    npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
    npm WARN deprecated semver behavior.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
    => Starting meteor app on port:80

    /bundle/bundle/programs/server/node_modules/fibers/future.js:267
                            throw(ex);
                                  ^
    ReferenceError: module is not defined
        at app/mup.js:7:1
        at app/mup.js:40:4
        at /bundle/bundle/programs/server/boot.js:283:10
        at Array.forEach (native)
        at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
        at /bundle/bundle/programs/server/boot.js:133:5

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'
```

My mup.js:

```
'use strict';


// require('babel-polyfill');
// require('source-map-support/register');

module.exports = {
  servers: {
    one: {
      host: 'xxx.xxx.xxx.xxx,
      username: 'ubuntu',
      pem: '/Users/mattijsspierings/.ssh/xxxxx.pem'
    }
  },

  meteor: {
    name: 'podshark',
    path: '/Users/mattijsspierings/www/xxxxxx',
    servers: {
      one: {}
    },
    env: {
      ROOT_URL: 'xxxxxxxxxx,
      MONGO_URL: 'mongodb://localhost/27017'
    },
    deployCheckWaitTime: 60, //default 10
    enableUploadProgressBar: true

  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {}
    }
  }
};

```

Any thoughts on how to make this more stable?

**Comment by madushan1000** [comment]
This is a known issue with meteor 1.3 versions. Some newer version of meteor fixed this. Try searching the mup issues.

**Comment by mattiLeBlanc** [comment]
Sorry, but I am not finding and issue logged that looks like mine issue (when I search for module).
It can be related by still using Coffeescript for this project. I am going to port it to typescript asap and it might kill the issue too.
(having the mup.js with module expression actually triggers and error when running the meteor project purely because it is converted to ES5 which doesn't support Module)

**Comment by madushan1000** [comment]
Oh sorry, I thought this was a fibers issue without reading the full text. It looks like your `mup.js` file get bundled with your app and meteor tries to load it on the server. To prevent this from happening, move your `projectroot/mup.js` file to `projectroot/.deploy/mup.js` and adjust the paths accordingly. 
This is an issue we are going to address in the future.

**Comment by mattiLeBlanc** [comment]
will do, thanks

**Comment by mattiLeBlanc** [comment]
Yes that helped. Thanks

**Comment by semikolon** [comment]
Please fix this. It blocks deploy when it hasn't been blocked before. I just upgraded an old app that was working fine, but then someone decided mup.json was ugly or something? Sorry, I really appreciate everyone working on meteor-up and putting their time into it. Just was a little bit annoyed at this seemingly unnecessary snag.

**Comment by jaredtmartin** [comment]
This solved part of my problem, but introduced another.  Now I'm getting: (node:28271) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '.deploy/settings.json'
I get this error whether I execute map deploy from the .deploy folder or from the root folder using mup deploy --config .deploy/mup.js
I also tried copying the settings.json file into the .deploy folder, but that didn't help at all.

**Comment by adammoisa** [comment]
@jaredtmartin same here, did you find a fix?

**Comment by adammoisa** [comment]
Got a solution: in the .deploy folder, start from the `mup init` step which will create a new `settings.json` in that directory. It will automatically skip creating a new `mup.js` file though so no worries about that being overwriten. Once you've done this, `mup setup` and `mup deploy` will work fine.
