### ISSUE TITLE
load balancing, two instances on the same server

### ISSUE THREAD

**Issue by ddaydd** [zodern/meteor-up#1266]
Hello,

I can't find any info if it's possible to load balancing on the same server with two instances(or more) of the same application.

if possible, do you have a sample mup.js configuration or any help?

thank you

PS: I tested several configuration without success...

EDIT: I also tried the following solution and adding the loadBalancing option: true, no success...
https://github.com/zodern/meteor-up/issues/800#issuecomment-346887162

**Comment by zodern** [comment]
This currently isn't supported.

There might be a fairly simple way to implement this if you want the same number of instances to run on all servers, and are okay with the instances running within the same docker container on each server.

**Comment by ddaydd** [comment]
Thank you for the answer

**Comment by 1tac11** [comment]
Hi there
How would that solution be?

**Comment by ddaydd** [comment]
Sorry, at the time I didn't really understand the usefulness of load balancing, today I no longer see the usefulness of having two instances on the **same** server... looking back, I find my question completely stupid , why would you want to do this?
