### ISSUE TITLE
Option to clear logs?

### ISSUE THREAD

**Issue by graphikjunkie** [zodern/meteor-up#1267]
For an app that has been up for almost a year the log shown by `mup logs` is getting huge. I have no idea how docker is handling this internally. Would it be a good idea to add a command to reset the logs?

**Comment by zodern** [comment]
Make sure you are using the latest mup version, and have run `mup setup` and `mup reconfig` recently. Unless if I missed a container, all containers should be configured to rotate their logs so it doesn't continually grow.
