### ISSUE TITLE
Running Mongodb instance on all interfaces

### ISSUE THREAD

**Issue by davinderkumar** [zodern/meteor-up#1269]
Hi,
As of now MongoDB docker instance publishes only on localhost:27017 which cannot be used to connect from remote.
How can I bind it on all/specific interfaces so I can connect MongoDB Compass tool?
Thanks

**Comment by juanpmd** [comment]
@davinderkumar Where you able to connect through MongoDB Compass? If so, could you share with me what you did? I havent been able to connect (get Socket Closed message).
