### ISSUE TITLE
Select mongoDB version

### ISSUE THREAD

**Issue by jykae** [zodern/meteor-up#128]
Latest version hard-coded in shell script, https://github.com/kadirahq/meteor-up/blob/master/src/modules/mongo/assets/mongo-start.sh

I made it configurable for mupx fork that we are using, https://github.com/jykae/meteor-up/blob/mupx/scripts/linux/install-mongodb.sh

Reason: mongoDB 3.2 needs driver upgrade, https://github.com/meteor/meteor/issues/5809

Could we have mongoDB version configurable for cases like this?

**Comment by zodern** [comment]
This will be available in the next update.
