### ISSUE TITLE
MUP v 1.5.6 Error: Could not retrieve replica set config:

### ISSUE THREAD

**Issue by sferoze** [zodern/meteor-up#1296]
Mup version (`mup --version`): 1.5.6

<img width="1571" alt="image" src="https://user-images.githubusercontent.com/3514912/153780775-3580c991-74b2-46d3-9b04-42a46af431d8.png">

Just tried 1.5.6 and got this when running mup setup on a brand new  linux droplet 

image: 'zodern/meteor:root'

**Comment by sferoze** [comment]
Ran mup setup again and it worked. Will keep this updated as I try to dpeloy. 

Might be a timing thing with initializing the replicaSet 

{"t":{"$date":"2022-02-13T23:43:09.599+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":3200}}

**Comment by zodern** [comment]
This should be fixed in mup 1.5.7.
