### ISSUE TITLE
Mupx "stable" doesn't hot code push.  "Dev" version not listed on NPM.

### ISSUE THREAD

**Issue by MichaelJCole** [zodern/meteor-up#130]
Hey, I get that mup is in transition, but w/o the --server-only flag mup deployed servers [don't code push](https://forums.meteor.com/t/mupx-cordova-build/20745/4) with Meteor 1.3.

[Info](https://github.com/arunoda/meteor-up/issues/981#issuecomment-218029367).  The [Merged PR](https://github.com/kadirahq/meteor-up/pull/120) didn't get backported to "stable".

So, the "stable" version is broken for Meteor 1.3 cordova apps.
And the "dev" version isn't stable or listed in NPM.

Is it time to make the switch?  After spinning through several deployment options, MUP is still the best in terms of speed and low complexity.  Is it still actively maintained?

**Comment by Siphion** [comment]
+1

When the PR will be merged on Mupx stable? :)

**Comment by madushan1000** [comment]
closed by https://github.com/kadirahq/meteor-up/pull/120
