### ISSUE TITLE
Home alias (~) fails in pem path

### ISSUE THREAD

**Issue by j6k4m8** [zodern/meteor-up#135]
if you specify a pem as `pem: "~/my/file.pem"`, it fails. `/full/path/to/file.pem` succeeds.

Maybe this is expected behavior, but the `~` version gives **_no**_ output, and fails silently!

**Comment by gsabran** [comment]
I had the same issue, but had no time to do a PR: https://github.com/kadirahq/meteor-up/issues/87

**Comment by j6k4m8** [comment]
Why is this closed? Resolved in a new version..?

**Comment by madushan1000** [comment]
Duplicated issue, But it looks like it's closed too. I'll reopen this.

**Comment by jacquesblom404** [comment]
+1
