### ISSUE TITLE
mup deploy stucked at 0% when pushing to the server

### ISSUE THREAD

**Issue by adelivet** [zodern/meteor-up#1351]
I'm blocked in my deployment process.

The local build is running correctly but when pushing to the server, it stays to 0%.
It used to work perfectly until last week.

I did not update Meteor, mup or anything.

`Started TaskList: Pushing Meteor App
[XX.XX.XX.XX] - Pushing Meteor App Bundle to the Server
[                                        ] 0% 0.0s`

I've already checked several things:
- Docker image exists
- No network issue
- Tried it on several buckets

Anyone know how to fix this?

Mup version: 1.5.9

Mup config
`  meteor: {
    name: 'xxx',
    path: '..',

    servers: {
      staging1: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      ROOT_URL: 'https://staging.xxx.com',
      PORT: 3000,
      MONGO_URL: 'mongodb+srv://xxx',
      MONGO_OPLOG_URL: 'mongodb+srv://oploguser:xxx',
      HTTP_FORWARDED_COUNT: 1
    },

    docker: {
      image: 'networksforchange/meteord:node-14.18.1-base',
    },

    deployCheckWaitTime: 100,
    enableUploadProgressBar: true
  },
};`

**Comment by generalleger** [comment]
I am having the exact same problem. For me, however, it works just fine from MacOS... but the devops team is pushing from an Ubuntu Linux VM. Running with debug and --verbose adds no additional detail.  It just hangs at 0%. `mup setup` works just fine.

**Comment by generalleger** [comment]
Just an update on my end. I was able to reproduce the issue in Ubuntu 22.04.3 on an Intel Mac through UTM.  

I tried on Debian 12.2.0, also on the Intel Mac through UTM and it uploaded without error. For me, this seems to be an Ubuntu issue, though I don't know to fix it.  But I have a workaround that is working for me.

**Comment by pisacode** [comment]
I fixed it by selecting node version v20.9.0 
https://stackoverflow.com/a/77613785/5069866

**Comment by generalleger** [comment]
> I fixed it by selecting node version v20.9.0 https://stackoverflow.com/a/77613785/5069866

That worked for me as well.

**Comment by chfritz** [comment]
I had the same issue but on Linux (Ubuntu 20) using node 20 and the latest `mup`. I was able to fix it by hard-coding a node 16 binary in the shebang of `/usr/bin/mup`.

**Comment by erixtekila** [comment]
Thanks @pisacode 
Using node version 20.9.0 fix the issue, whereas version 20.12.0 (current LTS) waits forever when trying to push the app serverside. Strange !

**Comment by Sergeant61** [comment]
Hello, I have the same problem with mac. After switching my project to meteor 3.0, it gets stuck.
![image](https://github.com/zodern/meteor-up/assets/25281038/21e6a1f6-46c7-422a-894f-e8e131a2381f)

**Comment by renanlecaro** [comment]
@Sergeant61 what's your node version ? as stated above, switching to node v20.9.0 fixes the issue (it did for me)

**Comment by allenfuller** [comment]
Same issue, and also resolved by using `nvm` to switch to an older version of Node (was on v22).

**Comment by zodern** [comment]
This should be fixed with `mup@1.5.11-beta.1`.

**Comment by mikkelking** [comment]
That did the job.

**Comment by zodern** [comment]
Mup 1.5.11 has been published.
