### ISSUE TITLE
Build meteor 3 app

### ISSUE THREAD

**Issue by roman-orlovskiy** [zodern/meteor-up#1360]
Have an error:

`[194.58.108.87] - Start Mongo
[194.58.108.87] - Start Mongo: SUCCESS
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/usr/local/lib/node_modules/mup/node_modules/ssh2-classic/lib/client.js:307:10)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}

`

**Comment by Sergeant61** [comment]
Hello, I switched to meteor 3 but I cannot deploy my projects. With meteor 3, it stays as follows. I can connect with ssh and I can also send files with scp. 

<img width="1074" alt="image" src="https://github.com/user-attachments/assets/417e11ba-44b5-418d-837e-0b86bc1fe95b">

**Comment by pmogollons** [comment]
run mup with node 20.9 as a work around

**Comment by mfeuermann** [comment]
Hello @Sergeant61, can you tell me which docker image you are using with Meteor 3 ?
Thanks

**Comment by mikkelking** [comment]
> Hello, I switched to meteor 3 but I cannot deploy my projects. With meteor 3, it stays as follows. I can connect with ssh and I can also send files with scp.
> 
I hit the same problem after updating my MacOS to Sequioa

> run mup with node 20.9 as a work around

Didn't fix it :( I tried Node 16/18/19/20/21 without success

**Comment by uniquarkD** [comment]
Check your active node version. Uninstall your current node and install with nvm. It'll be easier to switch your node versions.

**Comment by zodern** [comment]
Could you please try again with `mup@1.5.11-beta.1`? We were using a very outdated ssh2 client.
