### ISSUE TITLE
Return error code on failed deployments

### ISSUE THREAD

**Issue by RobinVanCauter** [zodern/meteor-up#137]
I've tested this new version of mup against my CI & CD containers but whenever a deployment verification fails my CI (using Gitlab CI) reports the "Deployment was successful!".

I'm guessing mup doesn't return a correct exit code yet when the command stops because of a failed deployment and Gitlab CI reports everything worked out fine because the script executed perfectly.

If I remember correctly this did work in MupX.

**Comment by madushan1000** [comment]
Can you post some logs?

**Comment by RobinVanCauter** [comment]
This is what Gitlab CI returns at the end of the CI execution log. As you can see mup returns an error on verifying the deployment and at the bottom gitlab returns "build succesful" while it should not.

I checked the mup code and saw you do actually return exit codes on errors, do you think this is an issue with Gitlab CI rather than mup?

**Mup logs:**

```
Started TaskList: Start Meteor
[hostname] - Start Meteor
[hostname] - Start Meteor: SUCCESS
[hostname] - Verifying Deployment
[hostname] x Verifying Deployment: FAILED

```

```
-----------------------------------STDERR-----------------------------------
ges made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
=> Starting meteor app on port:80

/bundle/bundle/programs/server/boot.js:324
}).run();
   ^
Error: $ROOT_URL, if specified, must be an URL
    at Error (<anonymous>)
    at Meteor.absoluteUrl.options (packages/meteor/url_server.js:8:1)
    at packages/meteor/url_server.js:19:1
    at /bundle/bundle/programs/server/packages/meteor.js:1365:3
    at /bundle/bundle/programs/server/boot.js:283:10
    at Array.forEach (native)
    at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /bundle/bundle/programs/server/boot.js:133:5

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------
```

**Gitlab CI report:**
`Build succeeded.`

**Comment by RobinVanCauter** [comment]
Another instance when it fails to report the right state, well at least, that's what it seems to look like, maybe it's gitlab, not sure.

**Mup logs:**

```
Building App Bundle Locally
Errors prevented bundling:
While building for os.linux.x86_64:
imports/orders/emails/templates/index.js:3:25: Unexpected token (3:25)


=> Build Error. Check the logs printed above.
```

**Gitlab CI report:**
`Build succeeded.`

**Comment by MasterJames** [comment]
Where is this file do you think?
`
imports/orders/emails/templates/index.js:3:25: Unexpected token (3:25)
`

**Comment by RobinVanCauter** [comment]
@MasterJames My apologies if I wasn't clear enough on the subject, but this issue is not about why my apps are failing to deploy. This issue is about why GitLab CI (and possibly other CI platforms) are reporting the build went well while in reality it failed.

Which errors are causing mup to fail in deploying the app are irrelevant to this issue, the error you are pointing out has been put there on purpose to demonstrate mup is failing to report the correct error code to my Gitlab CI runner instance.

The `Build succeeded.` line is not printed by mup, it is printed by Gitlab CI as the "result" of my build.

It is possible this is an error with Gitlab CI, but since this did seem to work fine with MupX I thought I'd report it here.

**Comment by madushan1000** [comment]
The problem here is that mup redeploy the old version of the app even if the deploy failed (It doesn't check for error at that step) and reports that mup completed correctly. This is the expected behaviour. 
I don't think it would be that hard to remove the rollback code and accomplish your task. You can create a fork of mup for your CI tasks.
