### ISSUE TITLE
mup ssh feature suggestion

### ISSUE THREAD

**Issue by j6k4m8** [zodern/meteor-up#139]
At least in the early stages of this new meteor-up development, I find myself ssh'ing into my deploy server frequently to debug. I'd find it very useful to have a `mup ssh` command that auto-starts an ssh session using the current mup.js config.

If there's interest in having this feature, I'm happy to implement!

**Comment by madushan1000** [comment]
Looks like an interesting feature. Go ahead and implement it. Be sure to add a new module under `src/modules` and handle the multi-server scenarios.

**Comment by zeroasterisk** [comment]
This would be useful!

**Comment by zodern** [comment]
This will be available in 1.3.1!
