### ISSUE TITLE
mup CLI feature suggestion: inspect / status

### ISSUE THREAD

**Issue by zeroasterisk** [zodern/meteor-up#141]
I'd love to have a CLI command for `inspect` or `feature` which would connect to all configured servers and give a status on all managed processes/containers/ports/etc... maybe even ENV settings (if verbose).

**Comment by zodern** [comment]
This is implemented in mup 1.4. You can try the beta using the instructions in #870. Is there any additional information you would like to see? Anything it currently shows that isn't useful?
