### ISSUE TITLE
mup CLI feature suggestion: logs

### ISSUE THREAD

**Issue by zeroasterisk** [zodern/meteor-up#143]
This is somewhat difficult for multiple servers, but if it was somehow convenient, I'd love to get logs from all, or even just one server, right from `mup`.

Bonus points for tail support _(over SSH, from multiple servers, sounds tricky)_

Until this exists, I SSH into a server and do `docker log myapp`

**Comment by timbrandin** [comment]
This would be wonderful, similar to how docker-compose combines logs from multiple machines.

**Comment by tomitrescak** [comment]
docker log my app gives me "log is not a docker command"

**Comment by zodern** [comment]
`mup logs` has supported tailing and following logs from multiple servers. In 1.3, it will be possible to use the `--servers` option to list which servers to get the logs from.
