### ISSUE TITLE
When final version of kadirahq/meteor-up release

### ISSUE THREAD

**Issue by cyclops24** [zodern/meteor-up#146]
Hi,

Now we have three version for meteor-up. I used [arunoda/meteor-up](https://github.com/arunoda/meteor-up) later but it seems now [arunoda/meteor-up/tree/mupx](https://github.com/arunoda/meteor-up/tree/mupx) is stable.
And this repo [kadirahq/meteor-up](https://github.com/kadirahq/meteor-up) seems more active.
I'm a bit confused.

Which version of meteor-up your recommend **now**??
And
When final version of kadirahq/meteor-up (this repo version) release?
Please guide me to choose best one now and know about future of this repo version and release date.

Thanks for your attention.

**Comment by MasterJames** [comment]
Seems mupx here for now still and later or maybe now (if it's working for your situation) the new one at kadirahq.

**Comment by cyclops24** [comment]
@MasterJame, Thanks for your attention.
So you suggest https://github.com/arunoda/meteor-up/tree/mupx and then https://github.com/kadirahq/meteor-up ??

**Comment by MasterJames** [comment]
Well if the new version at kadirahq doesn't work for yoy maybe stick with this depreciated version mupx it's considered the stable one.

**Comment by cyclops24** [comment]
Thanks @MasterJame and do you have any idea about kadirahq version release date?

**Comment by MasterJames** [comment]
Your welcome. No sorry I thought it is working fine now, but feverish changes at Meteor may be complicating things not sure what's happenin lately. I think it might still lack comprehensive documentation so you'll have to ask them.
Just use it as a study guide and template to help achieve your needs. If a PR results I'm sure they will be happy for the help.
Oh wait this is the kadirahq issues forum?! Ohps I keep getting those mixed up. Anyway I'm leaving watching these for now.
