### ISSUE TITLE
SystemD support

### ISSUE THREAD

**Issue by Testato** [zodern/meteor-up#148]
many ubuntu server have already SystemD instead of Upstart.

Is it in planning for this MUP version update it to support SystemD ?

The Aronuda version do not have in planning to support it, because of Docker support, so this will be the only MUP version that we can use for deploy on SystemD whitout Docker adoption force.

**Comment by madushan1000** [comment]
No there are no plans as of now to support anything other than Ubuntu 14.04 LTS. But anyone is welcome to PR with the feature.
