### ISSUE TITLE
install mup as normal user ?

### ISSUE THREAD

**Issue by abate** [zodern/meteor-up#149]
I'm trying to install mup as a normal user but I get this message on the link phase : 

Is it possible to use mup without superuser privileges ?

ubuntu@ubuntu-amd64:~/meteor-up$ npm link
npm ERR! Linux 4.2.0-38-generic
npm ERR! argv "node" "/usr/local/bin/npm" "link"
npm ERR! node v0.10.25
npm ERR! npm  v3.9.6
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/usr/lib/node_modules'
npm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules'] errno: 3, code: 'EACCES', path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/meteor-up/npm-debug.log

**Comment by madushan1000** [comment]
`npm link` requires access to your npm lib dir. Skip that and run from the source directory.
