### ISSUE TITLE
[Improvement] Add documentation on how to set SSH port

### ISSUE THREAD

**Issue by mlumbroso** [zodern/meteor-up#150]
Hello,

my server is not connecting with port 22, and contrarily to older versions of mup, using : 

`"sshOptions": { "port" : 12345},
`
is not working anymore.

The option has changed and it's not indicated in readme, I had to inspect source to find the option. Correct way now is :  

`opts: { "port" : 44700 },
`

Can you add the comment in mup.js file?

Thanks for your great work !

**Comment by zodern** [comment]
The readme now shows this in the example file.
