### ISSUE TITLE
How to exclude folder?

### ISSUE THREAD

**Issue by fckngold** [zodern/meteor-up#151]
I have public folder with images uploaded by users? After deploy this folder is overwritten. There are some ways to avoid this?

**Comment by msj121** [comment]
Originally got the idea here: https://github.com/tomitrescak/meteor-uploads/issues/235#issuecomment-228618130

Added issue for feature upgrade here: https://github.com/kadirahq/meteor-up/issues/160

**Comment by msj121** [comment]
#160
