### ISSUE TITLE
Can I specify a server in setup and deploy command?

### ISSUE THREAD

**Issue by g41n** [zodern/meteor-up#154]
Hello to all,
I've noticed that I can set more than one server in my mup.js configuration file.

If I have something like this

```
module.exports = {
  servers: {
    stage: {
      host: '1.2.3.4',
      username: 'root',
      password: 'password'
    },
    production: {
      host: '1.2.3.5',
      username: 'root',
      password: 'secret'
    },
  },
[...]
```

can I invoke `mup deploy stage` and `mup deploy production` to deploy (or setup) only on the server I need?

If not possible can I use 2 different setting files? Since now I've used mupx and `mupx --config=mup-stage.json deploy` or `mupx --config=mup-production.json deploy`.

Any hint would be appreciated.

Thanks in advance :D

**Comment by jacobmischka** [comment]
You can do the latter, sort of. You need to put each `mup.js`/`mup.json` config file in a separate directory.

So you can do:

```
mkdir .mup/production && cd .mup/production/ && mup init
cd ../..
mkdir .mup/staging && cd .mup/staging && mup init
cd ../..
```

In `package.json`:

``` json
...
   "scripts": {
      "mup-production": "cd .mup/production && mup deploy",
      "mup-staging": "cd .mup/staging && mup deploy"
   }
...
```

You need to make sure your `meteor.path` setting in each mup config file is correct, (so `'../../'` if you put it in `.mup/production` like in my example.

I haven't tested this myself yet, but it should work.

**Comment by jacobmischka** [comment]
Er, actually if you are still using mupx it looks like you can do the --config option you mentioned directly: https://github.com/arunoda/meteor-up/tree/mupx#custom-configuration-and-settings-files

Edit: Oh, that's what you said, my mistake.

**Comment by zodern** [comment]
Both options work since Mup 1.3. You can use the `--config` option to specify which config to use, or `--servers` specify which servers in the config to use.
