### ISSUE TITLE
There's no way to use a mongo container on the same docker server of the app container

### ISSUE THREAD

**Issue by g41n** [zodern/meteor-up#157]
Hello to all,
I need to connect to an existing mongo that is in the mongodb container.

If I have

```
env: {
  MONGO_URL: 'mongodb://mongodb:27017/custom-dbname',
[...]
```

in my configuration, the deploy fails because can't find the mongodb container.

I've temporarily fixed adding `--link=mongodb:mongodb` to the `start.sh` template.

Is there a way to refer to a container in other ways without `--link`?

**Comment by madushan1000** [comment]
Do you use the mongo contained setup by mup or one of your own? 
If you use one of your own, you're going to have to expose the mongo port using `-p` docker option.

**Comment by g41n** [comment]
I use the mongo container setup by mup.

**Comment by madushan1000** [comment]
can you post your mup.js file?

**Comment by g41n** [comment]
```
module.exports = {
  servers: {
    production: {
      host: 'xxx.xxx.xxx.xxx',
      username: 'root',
      password: 'secret',
    },
  },

  meteor: {
    name: 'app-backend',
    path: '../../',
    servers: {
      production: {},
    },
    env: {
      ROOT_URL: 'http://app-backend.mydomain.com',
      PORT: 3017,
      MONGO_URL: 'mongodb://mongodb:27017/app-database'
    },
  },
};

```

**Comment by MasterJames** [comment]
What happens if you try? 
MONGO_URL: 'mongodb://localhost/app-database'

**Comment by madushan1000** [comment]
If you want to setup mongodb provided by mup, you have to specify `mongo` section in the `mup.js` file. Take a look at the sample config file in the README

**Comment by g41n** [comment]
How can I set the database name in `mongo` section? The sample is not the case...

**Comment by madushan1000** [comment]
You don't have to. Just specify it in the `MONGO_URL`. Mongo will automatically create it for you.

**Comment by g41n** [comment]
That was my initial try, but not works because I don't have the link to connect to the `mongodb` container.

**Comment by madushan1000** [comment]
you have it right in your mup.js

**Comment by MasterJames** [comment]
When you run your docker container do you use the port flag?  Maybe try  --expose=27017 as well?

**Comment by g41n** [comment]
@MasterJames how can I add that option in `mup.js`? Is there a way to add custom docker options in `mup.js`?

**Comment by MasterJames** [comment]
I thought you said you're running your own MongoDB container? How is that launched?

**Comment by g41n** [comment]
Is launched by another meteor application deployed on the same server.

**Comment by MasterJames** [comment]
Does that have a separate mup file?  Maybe post that.
You can confirm that the first one is working as expected I suppose.
If you SSH into the machine and via docker exec bash gain access into the second docker container with meteor can you test connectability to the other Mongo running? If deployment fails but theres nothing to revert it should leave stuff behind or maybe it's a feature request to avoid/skip revert (mupDebug or revertOnFail false ? @madushan1000). You can hack an exit breakpoint manually in theory too, (if that's interfering with testing what went wrong)
Anyway I'm guessing you need to look at and test the network routing firewall stuff (ingress) that must be blocking access between the different docker containers.
Are they in the same availability zone, vpc, etc?

**Comment by madushan1000** [comment]
It's not recommended (or supported) to run two meteor apps on the db setup by mup. You should set up a separate mongodb instance yourself and point both of the apps there.

**Comment by g41n** [comment]
My first `MONGO_URL` works if I patch mup like this:

```
diff --git a/src/modules/meteor/assets/templates/start.sh b/src/modules/meteor/assets/templates/start.sh
index 0d3bd11..066431c 100644
--- a/src/modules/meteor/assets/templates/start.sh
+++ b/src/modules/meteor/assets/templates/start.sh
@@ -24,6 +24,7 @@ docker run \
   --volume=$BUNDLE_PATH:/bundle \
   --hostname="$HOSTNAME-$APPNAME" \
   --env-file=$ENV_FILE \
+  --link=mongodb:mongodb \
   <% if(useLocalMongo)  { %>--link=mongodb:mongodb --env=MONGO_URL=mongodb://mongodb:27017/$APPNAME <% } %>\
   <% if(logConfig && logConfig.driver)  { %>--log-driver=<%= logConfig.driver %> <% } %>\
   <% for(var option in logConfig.opts) { %>--log-opt <%= option %>=<%= logConfig.opts[option] %> <% } %>\
```

because to make the mongo container visible to the app container, I have to set the `--link` option in the app container start command. Now is not possible to set it in another way, I suppose...

The behaviour is the same if I want to have my own mongodb instance in a container on the same docker server of the app container.

**Comment by MasterJames** [comment]
Right you said that at the beginning. This link is helpful to understand something more about it.
https://linuxconfig.org/basic-example-on-how-to-link-docker-containers
I think he is right about deploying that separately is better, but your hack is good ~ working.
If you decide to do your own MongoDB container deployment as recommended you might need to --expose the port and know what the IP of it is. 
I think the PR/suggestion is to be able to add links from the settings file and maybe expose etc. I'm guessing/recalling there has been a few ideas/PRs about adding custom docker and or docker run parameters through the settings file. It's up to the devs to decide how this one might be solved that way. I think one should be able to add some arguments like this. The thing is you might call your MongoDB container something else and need to put something other then mongodb:mongdb like mymongodb:mongodb etc. so putting that in as a default for everybody probably isn't best practice.
_Something to think about. I'm glad it's working for you and that's what matters most._

**Comment by g41n** [comment]
Ok, I'll wait until devs decide how to add custom docker options.

In the meantime I'll try to understand how to test and submit PR in order to contribute a bit, if I can...

Thanks for the support :)

**Comment by Sewdn** [comment]
I experienced the same issues (trying to connect to the same mup-managed mongodb from different apps (within the same project) all using the same db).

I also edited template/start.sh to be able to override docker start configuration.
I hope we can soon control docker run parameters from mup.js. Is there any PR or branch for this feature where we can follow (or contribute) progress? Thanks!

**Comment by mikemeier** [comment]
@Sewdn Its already implemented but not yet tagged I think: https://github.com/kadirahq/meteor-up/blob/master/src/modules/meteor/assets/templates/start.sh#L31

**Comment by hamzamu** [comment]
MONGO_URL: 'mongodb://172.17.0.3:27017/{database name} 

where is 172.17.0.3 is your docker IP 
get it thru : docker inspect mongodb ..

**Comment by Faberle** [comment]
I just wanted to add for future visitors (I was one too struggeling with this issue yesterday) :

You can simply add the docker arguments in your mup.js

```

module.exports = {
  servers: {
    production: {
      host: 'xxx.xxx.xxx.xxx',
      username: 'root',
      password: 'secret',
    },
  },

 

  meteor: {
    name: 'app-backend',
    path: '../../',
    servers: {
      production: {},
    },
    docker: {
            image: 'abernix/meteord:base',
            args:[ // lets you add/overwrite any parameter on the docker run command (optional)
                "--link=mongodb:mongodb", // linking example
            ]
    },
    env: {
      ROOT_URL: 'http://app-backend.mydomain.com',
      PORT: 3017,
      MONGO_URL: 'mongodb://mongodb:27017/app-database'
    },
  },
};
```
No need to patch the start.sh ;)

**Comment by awdjs** [comment]
the `--link` option is deprecated, check the link bellow.
https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

here is the solution in 2 steps :

**Step 1 : pull, setup and expose your Mongo container manually** 

1. pull the docker image 
`docker pull mongo:latest`

2. setup your mongo container and expose the port
`docker run --name mongodb -d -p 27017:27017 mongo`

**Step 2 : configure the mup.js file to look like the following code snippet**

```

/** export deployment configuration for Meteor up  **/
module.exports = {
  servers: {
    one: {
      host: '1.1.1.1',
      username: 'username', 
      pem: '/home/user/.ssh/id_rsa',
      opts: {
        port: 22
      }
    }
  },

  meteor: {
    name: 'my-app',
    path: '../app-folder',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      ROOT_URL: 'http://1.1.1.1', 
      MONGO_URL: 'mongodb://1.1.1.1:27017/dbname', 
      PORT: 3001
    },

    docker: {
      image: 'abernix/meteord:base',
    },

    deployCheckWaitTime: 250,
    enableUploadProgressBar: false
  },

};

```
  

> 1.1.1.1 is the remote server's ip address.

and we are done :) .

**Comment by anantonton** [comment]
Hello. Then how about encryption? Where do we put the CA file?
