### ISSUE TITLE
pre-babelify javascript code

### ISSUE THREAD

**Issue by thani-sh** [zodern/meteor-up#16]
This can make the code run faster.

**Comment by mnmtanish** [comment]
The delay is caused by update check. This does not increase code performance significantly.

**Comment by arunoda** [comment]
But if we implement this, it's easy to install mup. Because user does not
need to download a huge chunk of babel related modules.

**Comment by mnmtanish** [comment]
I didn't think of that so I deleted the branch. We can do this after porting all core features or else we'll have to run `npm run prepublish` often.

**Comment by arunoda** [comment]
We can use NPM base for this.
Use this: https://github.com/kadirahq/npm-base
