### ISSUE TITLE
Ability to mount volumes in config file

### ISSUE THREAD

**Issue by msj121** [zodern/meteor-up#160]
If you go to start.sh (found  in meteor/assets/templates/start.sh) it mounts the volume:

line 24:
`--volume=$BUNDLE_PATH:/bundle \`

What I would like to do is add a new volume to be mounted for file storage for example:

```
--volume=$BUNDLE_PATH:/bundle \
--volume=/opt/$APPNAME/uploads:/uploads \
```

I have added this manually to the "start.sh" and it worked, but it should be a config option for the server imo. Perhaps something like:

`--volume=/opt/$APPNAME/$FOLDER:/$FOLDER \`

**Comment by BenoitBro** [comment]
The example config file in the readme shows an entry for mounting volumes.

```
volumes: { //optional, lets you add docker volumes
      "/host/path": "/container/path", //passed as '-v /host/path:/container/path' to the docker run command
      "/second/host/path": "/second/container/path"
    }
```

I was hoping to use that, is it not working then?

**Comment by marcusrognes** [comment]
This was merged in #133 7 days ago and should work.
@BenoitBro @msj121

**Comment by madushan1000** [comment]
closed with https://github.com/kadirahq/meteor-up/pull/133

**Comment by msj121** [comment]
Sadly I have just tried the new approach. I didn't seem to get it to work so I forced a --volume mount by editing the mup code. I do see where it should be inserted via the for loop. Is there a way to test this?
