### ISSUE TITLE
start meteor failed

### ISSUE THREAD

**Issue by johannchen** [zodern/meteor-up#161]
After pushing meteor app bundle to the server, the server failed to start meteor.

x Start Meteor: FAILED

```
-----------------------------------STDERR-----------------------------------
Error response from daemon: No such container: app-frontend
docker: Error response from daemon: driver failed programming external connectivity on endpoint app (fcc8c500a51af4e3b308d6992cb5297253ab999e6eb9f4b0aa35f09cff166f85): Bind for 0.0.0.0:80 failed: port is already allocated.
```

**Comment by johannchen** [comment]
Never mind, I need to stop the previous meteord container first, then start meteor: success.

**Comment by Ines-K** [comment]
hey @johannchen , how exactly did you stop the previous meteor container? 
I am currently dealing with the same issue. Any input is appreciated!
