### ISSUE TITLE
How to set AUTOUPDATE_VERSION

### ISSUE THREAD

**Issue by shijunti19** [zodern/meteor-up#162]
https://github.com/meteor/meteor/blob/devel/packages/autoupdate/QA.md
I want to set a fixed value AUTOUPDATE_VERSION

When I deployed multiple times, the old version of the app can not push hot?
Is it because AUTOUPDATE_VERSION has changed?

**Comment by madushan1000** [comment]
Use the `meteor.env` section of the mup.js
