### ISSUE TITLE
Error: No such container: [app name]

### ISSUE THREAD

**Issue by mattiLeBlanc** [zodern/meteor-up#163]
Hi

Every time I deploy a new project with MUP on AWS (ubuntu) I am in for a new surprise.
This time it is:
[XX.XX.XXX.XX] Error: No such container: defconregistry

So, I removed all docker stuff and installed docker manually. After the install I rebooted and was able to execute docker -ps to see all containers.
Then I ran setup and deploy and voila, still the message No Such Container.

```
'use strict';



module.exports = {
  servers: {
    one: {
      host: 'xx.xx.xxx.xxx,
      username: 'ubuntu',
      pem: '/Users/matti/.ssh/defconregistry.pem'
    }
  },

  meteor: {
    name: 'defconregistry',
    path: '/Users/matti/www/jobApplication',
    servers: {
      one: {}
    },
    env: {
      ROOT_URL: 'http://xx.xx.xxx.xxx',
      MONGO_URL: 'mongodb://localhost/27017'
    },
    deployCheckWaitTime: 60, //default 10
    enableUploadProgressBar: true

  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {}
    }
  }
};

```

**Comment by mattiLeBlanc** [comment]
```
Started TaskList: Pushing Meteor
[xx.xx.xxx.xxxx] - Pushing Meteor App Bundle to The Server
[xx.xx.xxx.xxxx] - Pushing Meteor App Bundle to The Server: SUCCESS
[xx.xx.xxx.xxxx] - Pushing the Startup Script
[xx.xx.xxx.xxxx] - Pushing the Startup Script: SUCCESS
[: ~/www/jobApplication/deployment/prod]$ mup start

Started TaskList: Start Meteor
[xx.xx.xxx.xxxx] - Start Meteor
[xx.xx.xxx.xxxx] x Start Meteor: FAILED

  -----------------------------------STDERR-----------------------------------
  Error response from daemon: No such container: defconregistry
  Error response from daemon: No such container: defconregistry-frontend
  docker: open /opt/defconregistry/config/env.list: no such file or directory.
  See 'docker run --help'.
  -----------------------------------STDOUT-----------------------------------
  base: Pulling from meteorhacks/meteord
```

**Comment by mattiLeBlanc** [comment]
it appeared to be an issue with the settings.json. The error message wasn't really helpful this case but I figured it out.
Maybe it's an idea if possible to give a more insight in the errors while trying to run Meteor. With a broker settings file it should have generated an error I think. I didn't see that in the log unfortunately .

**Comment by THPubs** [comment]
I'm also facing the same issue. But my settings.json is empty.

**Comment by jeffreyflynt** [comment]
How did you end up figuring it out? What was your solution?

**Comment by mattiLeBlanc** [comment]
I might have had malformed setting in my settings.json.
I can't remember. Just check if it is not malformed. 
The error didn't point me into that direction, I think I stumbled upon it by accident.

Did you add empty object to your settings at least?
```{}```
I can image it doesn't like an empty settings??

**Comment by zodern** [comment]
@jeffreyflynt could you please post here the logs from `mup deploy --verbose`?

**Comment by nomadanare** [comment]
Hi, I'm having the same issue. Tried with empty settings.json file on clean AWS Ubuntu 16.04. Any help would be wonderful. 

mup deploy --settings=settings.json --verbose
Building App Bundle Locally
                                                                            
Started TaskList: Pushing Meteor App
[13.59.6.xxx] - Pushing Meteor App Bundle to the Server
[13.59.6.xxx] - Pushing Meteor App Bundle to the Server: SUCCESS
[13.59.6.xxx] - Prepare Bundle
node-8.4.0-base: Pulling from abernix/meteord
Digest: xxx
Status: Image is up to date for abernix/meteord:node-8.4.0-base
Error response from daemon: No such container: upVote
Finished Extracting
Creating Dockerfile
Finished creating Dockerfile
Building image
Sending build context to Docker daemon  281.7MB
Step 1/6 : FROM abernix/meteord:node-8.4.0-base
# Executing 1 build trigger
 ---> Using cache
 ---> d26c85c673bc
Step 2/6 : RUN mkdir /built_app
 ---> Using cache
 ---> 4847b64e282c
Step 3/6 : COPY ./ /built_app
 ---> Using cache
 ---> 32822e93649b
Step 4/6 : ENV ROOT_URL=xxx
 ---> Using cache
 ---> 9bf0bb556249
Step 5/6 : ENV MONGO_URL=mongodb://mongodb:27017/upVote
 ---> Using cache
 ---> 6f67f5b0c504
Step 6/6 : RUN cd  /built_app/programs/server &&     npm install --unsafe-perm
 ---> Running in 7516bd144ec1

> fibers@2.0.0 install /built_app/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /built_app/programs/server
> node npm-rebuild.js


> bcrypt@0.8.7 install /built_app/programs/server/npm/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory '/built_app/programs/server/npm/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
make: Leaving directory '/built_app/programs/server/npm/node_modules/bcrypt/build'
npm ERR! Invalid version: "https://registry.npmjs.org/ansi-regex/-/ansi-regex-3.0.0.tgz"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-31T21_01_22_679Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-31T21_01_22_713Z-debug.log
The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
Error response from daemon: No such container: upVote
Error: failed to start containers: upVote
[13.59.6.xxx] x Prepare Bundle: FAILED
	
	-----------------------------------STDERR-----------------------------------
	Error response from daemon: No such container: upVote
	The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
	Error response from daemon: No such container: upVote
	Error: failed to start containers: upVote
	-----------------------------------STDOUT-----------------------------------
	_MODULE(target) Release/obj.target/bcrypt_lib.node
	  COPY Release/bcrypt_lib.node
	make: Leaving directory '/built_app/programs/server/npm/node_modules/bcrypt/build'
	npm ERR! Invalid version: "https://registry.npmjs.org/ansi-regex/-/ansi-regex-3.0.0.tgz"
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2017-12-31T21_01_22_679Z-debug.log
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2017-12-31T21_01_22_713Z-debug.log
	
	----------------------------------------------------------------------------
