### ISSUE TITLE
Error response from daemon: No such container

### ISSUE THREAD

**Issue by rnevius** [zodern/meteor-up#168]
I am experiencing a `mup deploy` issue that I can't wrap my head around. `mup setup` works fine. `mup deploy` seems to run fine...until the "Start Meteor" step, at which I receive the following error:

```
[XXX.XXX.XXX.XX] x Start Meteor: FAILED

    -----------------------------------STDERR-----------------------------------
    Error response from daemon: No such container: something
    Error response from daemon: No such container: something-frontend
    docker: Error response from daemon: driver failed programming external connectivity on endpoint something-frontend (e561f99a4daded67761d6c3f4c26c1ad73929ee5ad7e6e40bd78e959505d6c5b): Bind for 0.0.0.0:443 failed: port is already allocated.
    -----------------------------------STDOUT-----------------------------------
    base: Pulling from meteorhacks/meteord
    4d690fa98655: Already exists
    a3ed95caeb02: Already exists
    0638f01c6191: Already exists
    086f3bb36259: Already exists
    Digest: sha256:684021facd5847f6a4ee2f0095fd26b4d7f5af2b776150531914d43fd0eb889b
    Status: Image is up to date for meteorhacks/meteord:base
    700ec033c3e9054284fb7637a99f744c616fa1e621e38a77f50accbbeb1b2c08
    latest: Pulling from meteorhacks/mup-frontend-server
    03e1855d4f31: Already exists
    a3ed95caeb02: Already exists
    a3ed95caeb02: Already exists
    304ae4ee074b: Already exists
    963207107048: Already exists
    d9e2907e9fa4: Already exists
    4abf3e40edd9: Already exists
    3c907a5d5f8f: Already exists
    8db38a632903: Already exists
    Digest: sha256:573a1dd3e0e7829ad16e813d87e79948e9f2ef2cfa84d17c2c4c220b6e651b12
    Status: Image is up to date for meteorhacks/mup-frontend-server:latest
    0ece3882df94685137b0223d36fee467071f781e5355f05270c71bc63b9da468
    ----------------------------------------------------------------------------
```

There are a couple of issues here:
1. The error states that there are no containers named `something` and `something-frontend`. This isn't true, because running `docker ps -a` shows both containers exist.
2. "Bind for 0.0.0.0:443 failed: port is already allocated." There's nothing else using port 443...

Here are my relevant settings:

```
module.exports = {
  servers: {
    one: {
      host: "XXX.XXX.XXX.XX",  // redacted
      username: "root",
      pem: "/home/someone/.ssh/something.ppk",
    },
  },

  meteor: {
    name: 'something',
    path: '../..',
    servers: {
      one: {},
    },
    buildOptions: {
      debug: true,
    },
    ssl: {
      "crt": "./bundle.pem",
      "key": "./something_com.key",
      "port": 443
    },
    deployCheckWaitTime: 180,
    enableUploadProgressBar: true,
    env: {
      "PORT": 443,
    },
  },
  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};

```

I have searched through all other issues (closed and open) in this forum to try to debug. I have also tried removing all docker images and containers, as well as simply restarting the service. Thoughts?

**Comment by rnevius** [comment]
This was solved by removing the `PORT` environment variable, and simply setting the port in the `ssl` section of the config.

**Comment by janjackson** [comment]
I am not using ssl right now. What is the solution then?

**Comment by tim-phillips** [comment]
@janjackson I had the same issue and realized that mup was timing out too early before my deploy had finished starting up, which I suppose was before the container noted in the error was mounted.

About a minute or two after mup quit, my meteor deployment went live. So mup is simply checking that the deploy happened and then exiting on a timeout. If the deploy hasn't completed then mup will give some random error, presumably something to do with wherever it was when it killed itself. This is confusing though, what if there's a real error? 

Since Meteor is damn slow on startup, try increasing `deployCheckWaitTime` in `mup.js`, or just wait a couple minutes after the error message and see if you can access your app.
