### ISSUE TITLE
MUP deployment is slower than meteor run 

### ISSUE THREAD

**Issue by etheleon** [zodern/meteor-up#169]
Hi, i have two projects, 1 development, 1 production. 
The page load times are very different. 

on development (node version 6.3.0), I'm hosting the site with the following command: 
`meteor run --settings settings.json --production --port 80`
the page load is 5seconds

on production i'm using MUP to deploy, both mongo and the app are on the same server. 
the page load is 16 seconds. 

please help

**Comment by shadowcodex** [comment]
Probably this is due to different server configs and hardware configuration. You are free to reopen this issue if this problem still persists.
