### ISSUE TITLE
Working with Meteor 1.4?

### ISSUE THREAD

**Issue by zeroasterisk** [zodern/meteor-up#172]
1.4 release candidates are out... 

I can run them locally, but `mup deploy` didn't work... likely a node version difference?

What's the plan for this?  Specify an alternate docker image?  Recommendations for building?

**Comment by mzygmunt** [comment]
For me didn't work also.  I've got following error during verifying of deployment (Meteor 1.4):

```
Building App Bundle Locally

Started TaskList: Pushing Meteor
[178.62.22.101] - Pushing Meteor App Bundle to The Server
[178.62.22.101] - Pushing Meteor App Bundle to The Server: SUCCESS
[178.62.22.101] - Pushing the Startup Script
[178.62.22.101] - Pushing the Startup Script: SUCCESS

Started TaskList: Configuring  Meteor Environment Variables
[178.62.22.101] - Sending Environment Variables
[178.62.22.101] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[178.62.22.101] - Start Meteor
[178.62.22.101] - Start Meteor: SUCCESS
[178.62.22.101] - Verifying Deployment
[178.62.22.101] x Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
        npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
        => Starting meteor app on port:80

        assert.js:93
          throw new assert.AssertionError({
                ^
        AssertionError: "undefined" === "function"
            at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
            at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
            at Module._compile (module.js:456:26)
            at Object.Module._extensions..js (module.js:474:10)
            at Module.load (module.js:356:32)
            at Function.Module._load (module.js:312:12)
            at Module.require (module.js:364:17)
            at require (module.js:380:17)
            at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
            at Module._compile (module.js:456:26)

        => Redeploying previous version of the app

        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------

```

**Comment by madushan1000** [comment]
Did you deploy after `npm install`? mup doesn't handle anything npm related.

**Comment by mzygmunt** [comment]
@madushan1000 Yes, my app has installed all the required NPM packages and locally works fine.

**Comment by Ben305** [comment]
@mzygmunt That happens when you use a docker image that doesn't contain Node 4.

**Comment by Aur0r** [comment]
Since the base image uses node v0.10.43 https://github.com/meteorhacks/meteord/blob/master/base/scripts/lib/install_node.sh this one has to be updated first or an other one has to be created.

I know as a quick fix just updating would probably work but I wonder if this could be made in such a way that mup has a node version configuration because node 6 support is also on its way.

Also I think that the mongodb version has to be adjusted as well so a configuration here would maybe also make sense.

**Comment by zeroasterisk** [comment]
Right... fork, update the script and docker name, then tell us about it so we can put the docker image into our mup config... 

_not it_ 😄

**Comment by abernix** [comment]
I've posted my solution here https://github.com/meteor/meteor/issues/7475#issuecomment-235229269 which uses `abernix/meteord:base` as an override `dockerImage` (configurable in your `mup.js`.  The image I created upgrades `debian` to `jessie` (from `wheezy`), uses Node 4.4.7 and (for consistency with Meteor itself) uses NPMv3.

However as I mention later, I'd rather not be the official source of this so keep that in mind before you use it.  My branch is here: https://github.com/abernix/meteord/tree/abernix

**Comment by SachaG** [comment]
For some reason even with @abernix's image I'm still not able to deploy. I get:

```
npm ERR! node v4.4.7
    npm ERR! npm  v3.10.5
    npm ERR! code ELIFECYCLE
    npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node npm-rebuild.js
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs meteor-dev-bundle
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls meteor-dev-bundle
    npm ERR! There is likely additional logging output above.
```

**Comment by prawee** [comment]
after use  this repo and then using "mup setup"  how to fixed.

Started TaskList: Start Mongo
[188.166.x.x] - start mongo
[188.166.x.x] x start mongo: FAILED

```
    -----------------------------------STDERR-----------------------------------
    docker: Error response from daemon: driver failed programming external connectivity on endpoint mongodb (02f81063312a9d2f5bf32b89394893317a8bb3fee225bd52ac1862b1a9102177): Error starting userland proxy: listen tcp 127.0.0.1:27017: bind: address already in use.
    -----------------------------------STDOUT-----------------------------------
    latest: Pulling from library/mongo
    Digest: sha256:e599c71179c2bbe0eab56a7809d4a8d42ddcb625b32a7a665dc35bf5d3b0f7c4
    Status: Image is up to date for mongo:latest
    mongodb
    692072a22e81d253530311b277702a0849e121b8e03c45290337059f8afc6c4f
    ----------------------------------------------------------------------------
```

**Comment by andy4545** [comment]
when i run "mup setup"
i get :  "update 1.0.0 => 1.0.1"

no setup occurs - I am not sure what to update - i built the npm packkage from the latest git clone.

**Comment by vedovato** [comment]
Are you trying to setup with ssh, @andy4545? When i remove this line or modify my id_rsa it works.

**Comment by vedovato** [comment]
i was able to run mup setup after updating to ver 1.0.1.
Now i'm stuck with deployment process.

➜  .deploy mup deploy
Building App Bundle Locally
Errors prevented bundling:
While processing files with ecmascript (for target web.browser):
native: Unexpected token }
at Object.parse (native)
at BabelCompiler.BCp._inferFromPackageJson
(packages/babel-compiler/babel-compiler.js:165:1)
at BabelCompiler.BCp.inferExtraBabelOptions
(packages/babel-compiler/babel-compiler.js:139:1)
at BabelCompiler.BCp.processOneFileForTarget
(packages/babel-compiler/babel-compiler.js:81:1)
at BabelCompiler.<anonymous> (packages/babel-compiler/babel-compiler.js:21:1)
at Array.forEach (native)
at BabelCompiler.BCp.processFilesForTarget
(packages/babel-compiler/babel-compiler.js:20:1)

While processing files with ecmascript (for target os.linux.x86_64):
native: Unexpected token }
at Object.parse (native)
at BabelCompiler.BCp._inferFromPackageJson
(packages/babel-compiler/babel-compiler.js:165:1)
at BabelCompiler.BCp.inferExtraBabelOptions
(packages/babel-compiler/babel-compiler.js:139:1)
at BabelCompiler.BCp.processOneFileForTarget
(packages/babel-compiler/babel-compiler.js:81:1)
at BabelCompiler.<anonymous> (packages/babel-compiler/babel-compiler.js:21:1)
at Array.forEach (native)
at BabelCompiler.BCp.processFilesForTarget
(packages/babel-compiler/babel-compiler.js:20:1)

=> Build Error. Check the logs printed above.

tried to update babel-polyfill to 6.9.1

**Comment by abernix** [comment]
@SachaG (and others) I made a slight change to the image after you posted this, but I don't believe it would have helped your situation.  Still, you might want to try again!  I am successfully using it with `mup` v2 on one 1.4 project.

Please note that currently I don't believe the changes to the `kadirahq/meteord` or `meteorhacks/meteord` dockerImage are sufficient for binary dependency rebuilding so you will need to specify in your `mup.js`, `meteor` section:

``` js
{
// ...
  meteor: {
// ...other stuff
    dockerImage: 'abernix/meteord:base',
// ...other stuff?
  },
// ...
}
```

If you're still having problems, please make me a (bare minimum possible) reproduction of a project that you can't deploy and I'll try it out.  (That being said, I'm going out of town for two weeks starting tomorrow, so no promises on when I can do this!)

**Comment by mtwalsh** [comment]
The changes @abernix mentioned above worked for me also with a 1.4 project.

**Comment by allenfuller** [comment]
Wanted to confirm -- and profusely thank -- @abernix for the docker image and terrific posts that made deployments great again.

**Comment by stephane-r** [comment]
Hi every body,

I've try this, but no result for me. My mup.json :

```
{
  // Server authentication info
  "servers": [
    {
      "host": "xx.xxx.xxx.xxx",
      "username": "root",
      "password": "password",
      // or pem file (ssh based authentication)
      // WARNING: Keys protected by a passphrase are not supported
      //"pem": "~/.ssh/id_rsa"
      // Also, for non-standard ssh port use this
      //"sshOptions": { "port" : 49154 },
      // server specific environment variables
      "env": {}
    }
  ],

  // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  "setupMongo": true,

  // Application name (no spaces).
  "appName": "app-name",

  // Location of app (local directory). This can reference '~' as the users home directory.
  // i.e., "app": "~/Meteor/my-app",
  // This is the same as the line below.
  "app": "../app",

  // Configure environment
  // ROOT_URL must be set to your correct domain (https or http)
  "env": {
    "ROOT_URL": "http://xx.xxx.xxx.xxx",
    "METEOR_SETTINGS": "$(cat ../app/settings.json )"
  },

  // ..
  "meteor": {
    "dockerImage": "abernix/meteord:base"
  },

  // Meteor Up checks if the app comes online just after the deployment.
  // Before mup checks that, it will wait for the number of seconds configured below.
  "deployCheckWaitTime": 15,

  // show a progress bar while uploading. 
  // Make it false when you deploy using a CI box.
  "enableUploadProgressBar": true
}
```

And error after mupx reconfig :

```
npm WARN deprecated semver behavior.
        npm WARN package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
        npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
        => Starting meteor app on port:80

        assert.js:93
          throw new assert.AssertionError({
                ^
        AssertionError: "undefined" === "function"
            at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
            at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
            at Module._compile (module.js:456:26)
            at Object.Module._extensions..js (module.js:474:10)
            at Module.load (module.js:356:32)
            at Function.Module._load (module.js:312:12)
            at Module.require (module.js:364:17)
            at require (module.js:380:17)
            at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
            at Module._compile (module.js:456:26)
```

**Comment by trymbill** [comment]
Can confirm @abernix's docker image working flawlessly on a 1.4 project. Great success!

@LeG3nDz Your mup file looks a bit off. Pretty sure env (as an example) is supposed to be within the meteor key as well. I'd suggest you taking another look at the example mup.js file (https://github.com/kadirahq/meteor-up#example-file)

**Comment by eric-burel** [comment]
Hi, using abernix image and Meteor 1.4.1, I can't update my app anymore. `mup deploy` works fine, but my app is not uploaed. Has anyone experienced similar issues ?

**Comment by aido179** [comment]
Just deployed a new app with Meteor 1.4 and latest mup. using @abernix's docker image got it working for me.

Mup is throwing a `Verifying Deployment:FAILED` with a curl: (56) recv failure: connection reset by peer" message, but the deployment still seems to work.

**Comment by eric-burel** [comment]
Yep, that was due to a wrong `settings.json` in my app. However `mup deploy` was giving success messages while my app was actually crashing, I opened an issue about that #242.

**Comment by SachaG** [comment]
Is using @abernix's image still needed? Otherwise maybe the 1.4-related threads could be closed?

**Comment by aido179** [comment]
For me, @abernix''s image was necessary.

  On Fri, 26 Aug, 2016 at 9:31, Sacha Greifnotifications@github.com wrote:  
Is using @abernix's image still needed? Otherwise maybe the 1.4-related threads could be closed?

**Comment by mattiLeBlanc** [comment]
```
"meteor": {
    "dockerImage": "abernix/meteord:base"
  },
```

fixed it for me with Meteor 1.4.1.
Thanks!

**Comment by torayeff** [comment]
```
"meteor": {
    "dockerImage": "abernix/meteord:base"
  },
```

 still required

**Comment by vedovato** [comment]
Is this mup ver working on Meteor 1.4.2?

**Comment by discdiver** [comment]
abernix's docker image was still needed for me as of 9/21/16. Thank you abernix!

"meteor": {
    "dockerImage": "abernix/meteord:base"
  },

**Comment by NathanJeanDevs** [comment]
Wanted to confirm @abernix solution. 

Meteor 1.4.1.2, node 4.6.0 

Mupx deploy failed, was getting this error 
`        -----------------------------------STDERR-----------------------------------
        package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
        npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
        => Starting meteor app on port:80

```
    assert.js:93
      throw new assert.AssertionError({
            ^
    AssertionError: "undefined" === "function"
        at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
        at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
        at Module._compile (module.js:456:26)

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------`
```

I changed the start.sh file by replacing "meteorhacks/meteord:base" with "abernix/meteord:base" in 3 instances in the start.sh file.

After a mupx setup the deploy worked! 

I tired uninstalling node, mupx, meteor, everything. 

This seems to be the only fix I can find after hours and hours of attempts. 

Cheers, thanks community.

**Comment by gsabran** [comment]
Hi @abernix my deployment is crashing with:

```
=> Starting meteor app on port:80
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.


/bundle/bundle/programs/server/node_modules/fibers/future.js:313
                        throw(ex);
                        ^
[object Object]
```

Do you know how I can get better logs? (I can't open issues in your repo so I'm putting it here)

**Comment by lfilho** [comment]
@gsabran that looks like wrong node version. make sure you `npm install` and bundle your app locally with the same node & npm version running inside docker. Try that.

**Comment by abernix** [comment]
@gsabran Hmm, I bumped the Node version from 4.4.7 to 4.6.1 this morning in anticipation of Meteor 1.4.2 coming out (And because of the Security Updates in 4.6.0 and 4.6.1.)

The tests all ran fine.  Did this just start today or has it worked before?

**Comment by gsabran** [comment]
I launched a new server today yes. I'll look into node versions. Thanks! @lfilho how did that looked like wrong node version ?? :) @abernix is there a npm version I should also match in my local environment?

**Comment by lfilho** [comment]
@gsabran Although I'm not sure, I remember seeing that before and fibers package is something for older versions of node IIRC and its api and compilation are not forward compatible with current node versions anymore... Roughly :-D

**Comment by gsabran** [comment]
I've downgraded node to 4.6.1 (I was running 6), made sure I'm on npm 3.10.8, reinstalled all node modules, started a fresh EC2 instance and this is still happening...

**Comment by abernix** [comment]
@gsabran What is the version of the Meteor project you're publishing?

**Comment by gsabran** [comment]
`1.4.1.1` should I get `1.4.1.2` ?

**Comment by jamesgibson14** [comment]
I am having a weird problem, it starts, and compiles and then says "pushing the startup script: SUCCESS"... and then it dies with no error and no docker image is on the server Here is the output 
` mup:module:default exec => mup deploy +0ms
 mup:module:meteor exec => mup meteor deploy +1ms
 mup:module:meteor exec => mup meteor push +3ms
uilding App Bundle Locally
urrently, it is only possible to build iOS apps on an OS X system.

tarted TaskList: Pushing Meteor
104.236.163.55] - Pushing Meteor App Bundle to The Server
 nodemiral:sess:<IPADDRESS> copy file - src: /tmp/85a4f6d2-4f19-4dd8-93e2-9e53bfa6b446/bundle.tar.gz, dest: /opt/
or/tmp/bundle.tar.gz, vars: undefined +0ms
104.236.163.55] - Pushing Meteor App Bundle to The Server: SUCCESS
104.236.163.55] - Pushing the Startup Script
 nodemiral:sess:104.236.163.55 copy file - src: /usr/lib/node_modules/mup/lib/modules/meteor/assets/templates/start.
dest: /opt/meteor/config/start.sh, vars: {"appName":"meteor","useLocalMongo":0,"port":80,"sslConfig":{"port":443,"cr
bundle.pem","key":"private"},"logConfig":{"opts":{"max-size":"100m","max-file":10}},"docker":{"dockerImage":"abernix
eord:base","imageFrontendServer":"meteorhacks/mup-frontend-server"}} +8s
104.236.163.55] - Pushing the Startup Script: SUCCESS
 mup:module:meteor exec => mup meteor envconfig +1m`

**Comment by abernix** [comment]
@gsabran Hmm.  Ok.  It's a pretty strange error and I can't be certain if it has to do with my updates today, but I guess it's safe to assume.  (Although they worked for me and the test apps on CircleCI 😖).

Your globally installed node/npm on your dev machine shouldn't matter as the outputted app from `meteor build` (which is ran by `mup`) should be a Node 4 application.  The image just installs the latest NPM v3 – whatever that is.  Shouldn't matter if it's paired with Meteor.

Honestly, I wouldn't have expected this, but I don't have much time to check into it further at the moment.  Just to be safe before I head to bed, I've re-tagged the old images on with the same tags and published the new ones with the `-node-4.6.1` extension (they'll be up in just a few minutes).  See all here: https://hub.docker.com/r/abernix/meteord/tags/

See if that fixes it for you, but do see if you can figure out the problem with the `-node-4.6.1` images if you have a chance!  You'll probably need the `-node-4.6.1` tags if you're trying out Meteor 1.4.2 beta (which technically has 4.6.0 right now, but I wouldn't have expected that to be a problem).

You can always connect directly to the docker image on a shell and play around.  `docker run -i -t --entrypoint="/bin/bash" meteorhacks/meteord:base` should work.

I've opened issues on my repo if you want to make one there.

**Comment by abernix** [comment]
@jamesgibson14 I'm not sure if your error is related at all, but the old builds are back now on the same tags (e.g. `base`, `onbuild`, `devbuild`, `binbuild`) so if it was working before it should be working again now.

**Comment by jamesgibson14** [comment]
@abernix, okay I will play around some more, it is the first time I am using mup2 normally I use mupx. Thanks for taking the time to build the image and respond online to questions.

**Comment by abernix** [comment]
@gsabran Thinking about it a bit more, sleepily, 1.4.1.1 uses Node 4.4.7 and Node 4.6.0 was a major binary update because of the OpenSSL libraries being updated.  I'm curious if you have the same experience if you update your project to Meteor 1.4.1.2 and then try again with the `abernix/meteord:base-node-4.6.1` image.

**Comment by gsabran** [comment]
Thanks a lot @abernix. I moved the discussion to [this issue](https://github.com/abernix/meteord/issues/1)

**Comment by gsabran** [comment]
In case that's of interest to some, I've found that my issue comes from the inclusion of `meteorhacks/meteorx` that's an indirect dependency of my project. Since both packages are maintained by kadirahq/aronuda, I thought there might be a chance you could understand the issue better than I do @madushan1000 :)

**Comment by stephane-r** [comment]
Hi @abernix,

I will update my Meteor APP 1.4 to 1.4.1.3. Do you think i need to change my Docker image (`image:'abernix/meteord:base'`) and run new `mup setup` ? If i run new setup, my mongodb will be reset ? :/

Maybe i need to upgrade my node version too ?

`nodeVersion: '4.4.7'` to `nodeVersion: '4.6.1'`

Thank you !

**Comment by vedovato** [comment]
Well @LeG3nDz chances are we gonna need some mod/patch/fix into abernix image. Tried to deploy last friday and just now as we were used to successfully but now even our mup logs isn't returning stuff...

Running **node 4.4.7** and **meteor 1.4.1_3**.
Meteor deploys are always a quest for me lol

**Comment by abernix** [comment]
I'm fairly sure you do not need to run `mup setup`, only `mup deploy` (In fact, I'm fairly sure you should NOT run `mup setup`).  And while Meteor 1.4.1.3 is intended to work with Node 4.6.1, I'm not sure if you will run into any problem using my current `:base` image which uses Node 4.4.7.  The Node API is definitely compatible, so I'd suggest you try, definitely on a staging server first.

That all being said, I did package up a `abernix/meteord:base-node-4.6.1` image the other day which you're welcome to try for Meteor 1.4.1.3.

**Comment by vedovato** [comment]
Yay, thank you @abernix. Gonna try it later and post here again

**Comment by stephane-r** [comment]
Thank @abernix, i'll try.

@vedovato, You can make a feedback when you have tried ? (If I have not done in the meantime) :)

**Comment by vedovato** [comment]
Tried last Friday and yesterday. Both without success on both images said above by abernix

**Comment by abernix** [comment]
@vedovato I'm fairly sure that my image is still working fine for most everyone so I believe this must be something specific to your app.  Do you get an error when you run `mup deploy`?

**Comment by vedovato** [comment]
At the end i just reset my project based on a past commit then using your regular image i made a deploy to our staging instance and it's all ok. Not sure but seems like it was this meteor patch ... anyway now i'm able to deploy normally again. Thanks for your support, @abernix.

**Comment by PolGuixe** [comment]
I just updated to 1.4.2 and I am getting this error:

```
    Error: Can't find npm module 'react/lib/ReactComponentWithPureRenderMixin'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
        at Object.require (/bundle/bundle/programs/server/boot.js:200:17)
        at options.fallback (packages/modules-runtime.js:445:18)
        at require (packages/modules-runtime.js:112:16)
        at meteorInstall.node_modules.react-addons-pure-render-mixin.index.js (packages/modules.js:17838:18)
        at fileEvaluate (packages/modules-runtime.js:181:9)
        at Module.require (packages/modules-runtime.js:106:16)
        at Module.Mp.import (/bundle/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:70:16)
        at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (/bundle/bundle/programs/server/packages/react-meteor-data.js:234:256)
        at fileEvaluate (packages/modules-runtime.js:181:9)
        at require (packages/modules-runtime.js:106:16)
```

**Comment by gsabran** [comment]
Is react part of your npm modules?

**Comment by PolGuixe** [comment]
@gsabran yes.

**Comment by gsabran** [comment]
and I guess you've checked that `$ ls node_modules/react/lib/ReactComponentWithPureRenderMixin` returns you something? If so I've no idea :)

**Comment by PolGuixe** [comment]
@gsabran the file exists.

**Comment by PolGuixe** [comment]
I have rolled back to 1.4.1.2 and it works. Does anyone has problems with 1.4.2?

**Comment by abernix** [comment]
@PolGuixe Do you have `react` in your `devDependencies` or `dependencies` in your `package.json`?  It should be noted that Meteor 1.4.2 will strip `devDependencies` (as you would have probably previously expected :wink:) thanks to https://github.com/meteor/meteor/pull/7668/commits/03e798abc95f4edf4e0eceea7bfe036f73b27080.  This is an intentional change to Meteor.

**Comment by PolGuixe** [comment]
@abernix I have it in my `dependencies`. Below is how I have it: 

``` json
"dependencies": {
    "bcrypt": "^0.8.7",
    "faker": "^3.1.0",
    "install": "^0.8.1",
    "lodash": "^4.13.1",
    "mantra-core": "^1.7.0",
    "material-ui": "^0.16.1",
    "moment": "^2.15.1",
    "money-math": "^2.4.3",
    "npm": "^3.10.6",
    "react": "^15.3.2",
    "react-dimensions": "^1.3.0",
    "react-dom": "^15.3.x",
    "react-helmet": "^3.1.0",
    "react-komposer": "^1.13.1",
    "react-komposer-plus": "^2.2.3",
    "react-mounter": "^1.0.0",
    "react-redux": "^4.4.5",
    "react-simple-di": "^1.0.1",
    "react-tap-event-plugin": "^1.0.0",
    "redux": "^3.5.2",
    "redux-form": "^6.0.1",
    "redux-form-material-ui": "^4.0.1"
  },
  "devDependencies": {
    "babel-core": "6.x.x",
    "babel-plugin-react-require": "2.x.x",
    "babel-polyfill": "6.x.x",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "6.x.x",
    "babel-preset-stage-2": "6.x.x",
    "babel-register": "^6.9.0",
    "babel-root-slash-import": "1.x.x",
    "chai": "3.x.x",
    "enzyme": "^2.2.0",
    "eslint": "2.7.x",
    "eslint-plugin-react": "4.3.x",
    "jsdom": "^8.0.4",
    "mocha": "2.x.x",
    "react-addons-test-utils": "15.3.x",
    "sinon": "1.17.x",
    "@kadira/storybook": "^2.5.2"
  }
```

**Comment by abernix** [comment]
Forgive my unfamiliarity with React components, but shouldn't `react-addons-pure-render-mixin` be in your list of `dependencies`?

Also, if this isn't the solution this really should probably be discussed elsewhere as, unless I'm mistaken, I don't believe this is related to `meteor-up` or `meteord` in any way and this would very likely happen if you did a `meteor build` and ran that `node` bundle on your own machine.  This is broadcasting out to dozens and dozens of people who are here for a different reason. :smile:

**Comment by massimosgrelli** [comment]
With linux dev station it works perfectly. Moving to Mac (Sierra) I keep having this problem. Same version of Node and npm on both stations.

It looks similar to the one @SachaG had.. After hours of work I don't know what else I can try. This is the error I got:
 
``` 
       x Verifying deployment: FAILED
	-----------------------------------STDERR-----------------------------------
	rm"
	npm ERR! node v4.6.2
	npm ERR! npm  v3.10.10
	npm ERR! code ELIFECYCLE
	npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node npm-rebuild.js
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs meteor-dev-bundle
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls meteor-dev-bundle
	npm ERR! There is likely additional logging output above.
	
	npm ERR! Please include the following file with any support request:
	npm ERR!     /bundle/bundle/programs/server/npm-debug.log
	 
	=> Redeploying previous version of the app
	 
	-----------------------------------STDOUT-----------------------------------
	
	To see more logs type 'mup logs --tail=50'
	
	----------------------------------------------------------------------------
```

Any ideas?
Thanks,
Max

**EDITED**
After another 2 hours it seems like this problem arises in a specific case: when I clone the repo of my app (developed under linux) and I make it run on a Mac, the following massage show up:

```
W20161208-19:13:42.365(1)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20161208-19:13:43.040(1)? (STDERR) While this implementation will work correctly, it is known to be
W20161208-19:13:43.040(1)? (STDERR) approximately three times slower than the native implementation.
W20161208-19:13:43.041(1)? (STDERR) In order to use the native implementation instead, run
W20161208-19:13:43.041(1)? (STDERR) 
W20161208-19:13:43.042(1)? (STDERR)   meteor npm install --save bcrypt
W20161208-19:13:43.043(1)? (STDERR) 
W20161208-19:13:43.043(1)? (STDERR) in the root directory of your application.
```

If I run `meteor npm install --save bcrypt` and then deploy the app, I get the failure above. But if I avoid running this suggested command, then `mupx deploy` goes right.

**Comment by RenSilvaAU** [comment]
And guess what?

As soon as I removed bcrypt from my mac, I was able to deploy the app via mupx deploy.

**Comment by doronsever** [comment]
I can confirm that after removing bcrypt the deployment goes smoothly.
Is there a way bcrypt can still be installed locally?

**Comment by shadowcodex** [comment]
You are free to reopen this issue if this problem still persists.
