### ISSUE TITLE
Mup failing silently with meteor 1.4

### ISSUE THREAD

**Issue by CaptainChemist** [zodern/meteor-up#179]
I'm having an issue where mup silently fails when I use it in my project. I have mup.js and settings.json in the base of my meteor project and use the following mup.js.

```
module.exports = {
  servers: {
    one: {
      host: '1.1.1.1',
      username: 'root',
      pem: "~/.ssh/mykey"
    },
  },
  nodeVersion: "4.4.7",

  meteor: {
    name: 'Meteor',
    path: './',
    servers: {
      one: {},
    },
    env: {
      PORT: 80,
      ROOT_URL: 'http://1.1.1.1',
      MONGO_URL: '"mongodb://user:pass@mlab.com:39685/production"'
    },
  },

  dockerImage: 'abernix/meteord:base',
  deployCheckWaitTime: 60,

};

```

I type mup setup and it thinks for a minute before returning the command prompt without any thing printed to the screen. If I type mup deploy, it will build it locally for a while and then return without any errors either. I used node 5.4.0 and npm 3.10.5 for building mup and then for the meteor package, I am using 1.4 and node 4.4.7 and npm 2.15.8.

**Comment by madushan1000** [comment]
try changing the relative `pem` path to an absolute one.

**Comment by vedovato** [comment]
now it works

**Comment by madushan1000** [comment]
We use `path.resolve` to resolve the strings to actual paths, in the package `~` alias for the home directory is not supported. But I need to take a look at why is it silently failing.

**Comment by CaptainChemist** [comment]
That fixed the silently failing issue, thanks!

**Comment by iamrommel** [comment]
I'm not using that pem, i'm using the plain password but still it just do nothing after type mup on my command line

**Comment by iamrommel** [comment]
is there any log files I can check to know what's really wrong?

**Comment by zodern** [comment]
Please make sure you are using the latest version of mup. A few causes for silent fails have been fixed this month.

**Comment by iamrommel** [comment]
yep, i'm using the latest version as i just downloaded it 5hours ago. I also make sure, there is no existing mupx and mup on on my node_modules global folder.

I was on window and using "mup.cmd" rather than just "mup" do the trick. i found this on https://github.com/zodern/meteor-up/issues/185#issuecomment-281560683
