### ISSUE TITLE
Meteor 1.4 and binary npm

### ISSUE THREAD

**Issue by cspecter** [zodern/meteor-up#181]
So my app makes extensive use of a couple of binary NPM modules. Up until the release of Meteor 1.4 I had been using a private Meteor package as a wrapper. With the release of Meteor 1.4 those packages have stopped working because I of the node version, plus I would prefer to use `npm install` moving forward now that Meteor is on a current version of node. I'm using the `abernix/meteord:binbuild` docker image. 

Unfortunately I'm having a ton of issues deploying and building those modules using MUPX to my DO droplets. Advice appreciated. This is my readout in my log.

```
> talib@1.0.2 install /bundle/bundle/programs/server/npm/node_modules/talib
> node ./src/lib/build.js && node-gyp configure && node-gyp build

building talib functions...
make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/talib/build'
  CXX(target) Release/obj.target/talib/src/talib.o
  SOLINK_MODULE(target) Release/obj.target/talib.node
../src/lib/lib/libta_libc_csr.a: error adding symbols: Archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status
talib.target.mk:125: recipe for target 'Release/obj.target/talib.node' failed
make: *** [Release/obj.target/talib.node] Error 1
make: Leaving directory '/bundle/bundle/programs/server/npm/node_modules/talib/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-31-generic
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /bundle/bundle/programs/server/npm/node_modules/talib
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/opt/nodejs/bin/node" "/opt/nodejs/bin/npm" "rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! talib@1.0.2 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the talib@1.0.2 install script 'node ./src/lib/build.js && node-gyp configure && node-gyp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the talib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/lib/build.js && node-gyp configure && node-gyp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs talib
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls talib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /bundle/bundle/programs/server/npm/npm-debug.log

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/opt/nodejs/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /bundle/bundle/programs/server/npm-debug.log
```

**Comment by marcoschwartz** [comment]
Same here, I can't deploy my apps that use NPM packages, I got the same error. Anyone has a solution ?

**Comment by cspecter** [comment]
Well I found a solution, but it doesn't really solve the underlying problems. I narrowed my issue down to two things. The first issue, which is shown in the error I posted above, is that one of the npm package I was using (talib) tries to download the source C++ files from another repository via subversion when installing. On my dev system (a Mac), there is no problem installing it. It downloads the source and builds fine. It also works in an Ubuntu server I set up. But in Docker, no dice, it never downloaded the source. The second issue I am having, and this affects all the binary packages i am using, is that node-gyp just doesn't work properly in Docker. Supposedly node-gyp is included with Meteor. So if you run `meteor npm install` it should work ok, but when deploying an app it always runs `npm install` so it needs node-gyp on the OS. I tried just about everything, even building my own Docker image to make sure it is being installed correctly, but node-gyp has issues running as the root. You can try my image out though, maybe it will work for you. `cspecter/meteord:alt`.

To get things working this is what I did. I removed all the binary packages from the package.json, deleted the node_modules folder and reran `npm install`. 

The next part is a pain in the butt. You are going to use a package called `bindings` `https://www.npmjs.com/package/bindings`. First you need to pre-build all your binaries for all the platforms you need. First I installed the packages on my local dev machine, then grabbed the `.node` files that were created. Make sure you label them something like `_osx` so you know what platform they are for. Then I created a Debian server (since that is what my ultimate deployment platform is), installed node and node-gyp, then installed all the binary packages there. Then you need to download those compiled `.node` files. Make sure to label them as per their platform as well. Installing in this instance seemed to work fine and I think it was because I was running node-gyp not as a root user. 

Then you need to create a `private` folder in root of your Meteor app. Put all the `.node` files in there. Then you need to use `bindings` to load them, make sure you are loading the right `.node` for the right platform. I used a key in my settings.json to denote whether I was in dev mode or not.

```
let module;
if (Meteor.settings.public.isDevelopment === true) {
    module = require('bindings')('../assets/app/module_osx.node');
} else {
    module = require('bindings')('../assets/app/module_linux.node');
}
```

FYI, this path `../assets/app/` is important. You don't use the path `/private` since the bindings package is looking for a path in the deployed app. Anything you put in `/private` goes into the `../assets/app/` after you build the app. 

This highly annoying process is how I am using the binary packages I need right now. Hopefully someone smarter than I am can get binary npm packages to work with MUP and Docker without all this hullaballoo.

**Comment by 0o-de-lally** [comment]
+1 This seems like a big problem. I've also got modules with binaries that are failing on MUP and meteord docker implementation. What I find unusual is that when I deploy to galaxy, I have no issues. Assuming galaxy uses Docker, I'm sure there is a workaround. 

@arunoda  how have you solved this in production?

**Comment by cesarve77** [comment]
+1

**Comment by cesarve77** [comment]
I can solved one time doing:

```
meteor npm install
mup setup
mup deploy
```

and works

but later after for a other version, the same problem appears again.

**Comment by sscaff1** [comment]
I get the same error

**Comment by guillim** [comment]
@sscaff1 i had similar issue so I created the docker that could overcome this. try it:
dockerImage:"guillim/meteord"

Now it works great !

It is bascially the docker created by abernix but where I updated node (from v4 to v6) and installed some npm packages i needed (including node-gyp which failed before)

**Comment by cspecter** [comment]
This is not an issue with MUP. It's an issue with Meteor. When Meteor runs `npm-rebuild.js` it's not clearing out the compiled files for your dev setup (Mac in my case) and thus failing at rebuilding the npm packages. There is a workaround at the bottom of this thread. Not perfect but will do until they address this issue in future release of Meteor. [https://github.com/meteor/meteor/issues/7730#issuecomment-266476495](https://github.com/meteor/meteor/issues/7730#issuecomment-266476495)
