### ISSUE TITLE
Meteor always starting on port 80, not on what is specified in config.

### ISSUE THREAD

**Issue by tomitrescak** [zodern/meteor-up#183]
With my deployment, Meteor always start on port 80, even when I specify differently.
any idea how can I change the port?

Here is my config

```
module.exports = {
  servers: {
    one: {
      host: '***',
      username: '****',
      // pem:
      password: '****'
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'CsNew',
    path: '/Users/tomi/Github/apps/cs',
    buildOptions: {
      serverOnly: true,
      debug: true
    },
    servers: {
      one: {}
    },
    env: {
      "PORT": 3030,
      "ROOT_URL": "http://cs.scem.uws.edu.au",
      "MONGO_URL": "*****",
      "MAIL_URL": "*****"
    },

    dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 200
  },
};
```

**Comment by bearcanrun** [comment]
@tomitrescak I was just going through this figuring out how to get multiple apps running on one server. I'm using nginx as a reverse proxy on a digital ocean VPS. 

What I found is, if you run on the server $ _docker ps_ it'll show your container with something like 0.0.0.0:[MUP-PORT]->80/tcp under ports where docker  is automatically bridging the port to 80/443. Read more [here](https://docs.docker.com/engine/userguide/networking/dockernetworks/).

If you run _curl 0.0.0.0:MUPPORT_, you should actually see your app output. Thus, you can use the server localhost:MUPPORT as an upstream and proxy pass into the desired server.

**Comment by tomitrescak** [comment]
@bearcanrun yes, that's what I'm trying to do, have multiple apps on my server. But it does not work ;(

Docker ps gives me this:

```
a28efd5d9dac        abernix/meteord:base       "/bin/sh -c 'bash $ME"   3 minutes ago       Up 2 minutes                        0.0.0.0:3030->80/tcp   CsNew
```

Last thing I see in meteor log is:

```
[hugo.scem.uws.edu.au]npm WARN meteor-dev-bundle@0.0.0 No description
[hugo.scem.uws.edu.au]npm WARN meteor-dev-bundle@0.0.0 No repository field.
[hugo.scem.uws.edu.au]npm WARN meteor-dev-bundle@0.0.0 No license field.
[hugo.scem.uws.edu.au]=> Starting meteor app on port:80
```

It also takes meteor about 2 minutes to rebuild following: `[hugo.scem.uws.edu.au]  ACTION Regenerating Makefile`

Even with this I cannot access the meteor app with:

```
tomas@hugo:~$ curl 0.0.0.0:3030
curl: (56) Recv failure: Connection reset by peer
```

Any idea? Thanks!

**Comment by bearcanrun** [comment]
@tomitrescak Right, so your app is launching correctly. Inside the container meteor is running on 80, then is bridged to 0.0.0.0:MUP_PORT then to server localhost:80. This is as it should be.

I'm pretty sure mup logs is the same as `$ docker logs <container_id>` but check to see that they match up and no new errors.

Check nginx error logs: `$ sudo tail -f /var/log/nginx/error.log`

My nginx conf is something like this (/etc/nginx/sites-available/mysite.conf):

```
upstream meteorapp {
  server 0.0.0.0:<MUP-PORT>;
  keepalive 8;
}

server {
    listen 80;
    listen [::]:80;
    server_name mysite.com;
    return 301 https://$server_name$request_uri;
}

server {
 listen [::]:443 ssl default_server;

 # SSL config
 ...

 # Make site accessible from localhost
 server_name mysite.com;

 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-Proto $scheme;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_http_version 1.1;
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "upgrade";
 proxy_set_header Host $host;
 proxy_set_header X-NginX-Proxy true;

 location / {
        proxy_pass https://meteorapp;
 }
}
```

What is your app built with? Meteor 1.4? webpack? I had a whole bunch of problems in production when upgrading to 1.4. Of course, make sure you are trying to deploy with a stupid simple app first. After I finally got my app to actually make it to the browser as blank page, I had a whole other slew of errors to deal with. I ended up removing webpack (using thereactivestack:webpack) to get things deployed finally.

**Comment by tomitrescak** [comment]
I hate this ... out of the blue I check if my app is running .. and it is ... and this is that I had "deployment failed" message from mup. So I try to deploy again, and it worked ... with no changes. I have no idea. It all works now and I even get deployment ok message. I guess.. hooray! 

Thanks for your kind help. Was very helpful. Made me go inside docker image and check whether everything is ok.

**Comment by leckylao** [comment]
@bearcanrun This is very useful. I will suggest adding the steps in README for how to set it up to work with Nginx proxy. 
Here's some extra steps I need to do to make it works:
- Create and run a mongodb container and name it mongodb
- Adds in the mongo config in mup js in order for the meteor to connect it to
  mongo: { // optional
  oplog: true,
  port: 27017,
  servers: {
    one: {},
  },
  }
- It is necessary to set env port 8080(other than 80) to overwrite the default container publish port:
  env: {
    PORT: '8080',
    ROOT_URL: 'http://xxxxxx',
    MONGO_URL: 'mongodb://mongodb/xxxxx'
  }

**Comment by ghost** [comment]
I was having this error with  `mup reconfig`, used mup deploy instead and worked.
