### ISSUE TITLE
Maximum call stack issue with mup.

### ISSUE THREAD

**Issue by CaptainChemist** [zodern/meteor-up#187]
I just installed meteor-up today using npm and I can successfully setup but when I go to deploy I get the error:

`RangeError Maximum call stack size exceeded`

while it is trying to build locally. This is my mup script:

```
module.exports = {
  servers: {
    one: {
      host: '1.1.1.1',
      username: 'root',
      pem: "/Users/user/.ssh/key"
    },
  },
  setupNode: true,
  nodeVersion: "4.4.7",

  meteor: {
    name: 'Meteor',
    path: '/Users/user/development/project',
    servers: {
      one: {},
    },
    env: {
      PORT: 80,
      ROOT_URL: 'http://1.1.1.1',
      MONGO_URL: '"mongodb://user:pass@mlab.com:39685/production"'
    },
  },
  dockerImage: 'abernix/meteord:base',
  deployCheckWaitTime: 60,
};
```

The meteor server works great locally, any suggestions? Thanks!

**Comment by Tbutnyakov** [comment]
Hi! How did you perform "mup setup" ?!
My system can't run mup.js, cause it dont know nothing about "module".

**Comment by CaptainChemist** [comment]
I installed mup using:
`npm install -g mup
`
Then I did
`mup init
`
Configured the mup.js file then:

```
mup setup
mup deploy

```

**Comment by Tbutnyakov** [comment]
@CaptainChemist  I did the same. But my OS prevents all my tries to mup setup. 
What kind of OS you use?

**Comment by CaptainChemist** [comment]
I am on a Mac but I don't think it is an os thing, it is likely a
configuration issue for you. You need to be more specific with the error
you get, "prevents" is not enough info.

**Comment by Tbutnyakov** [comment]
I got "Windows script error", first time i took error about unecspected tokens like "," after some "}". 
When, after refactor, i took err message about "'module' is not defined".

**Comment by CaptainChemist** [comment]
Okay, that clearly seems like a different issue, we should focus on answering your question in the issue you opened.

**Comment by Tbutnyakov** [comment]
Yes, I understand that. I'm sorry for offtopic

**Comment by CaptainChemist** [comment]
It seems like dockerImage doesn't seem to be doing anything, if I remove that line, it still tries to set it up using docker. That's weird right?
UPDATE: I tried hard-coding the docker images with abernix/meteord:base or kadirahq/meteord and that didn't seem to be the issue.

**Comment by madushan1000** [comment]
The config file seems a bit off, can you try using a new config file. Alter the one after you get running `mup init`.

**Comment by CaptainChemist** [comment]
Thanks for the response, I still get this error even when I run `mup init` 

```
module.exports = {
  servers: {
    one: {
      host: '138.68.27.1',
      username: 'root',
      pem: '/Users/user/.ssh/digitalocean'
    }
  },

  meteor: {
    name: 'Meteor',
    path: '/Users/user/development/react-meteor',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://138.68.27.1',
      MONGO_URL: 'mongodb://user:pass@.mlab.com:39685/production'
    },

    dockerImage: 'kadirahq/meteord',
    deployCheckWaitTime: 60
  },
};
```

**Comment by vedovato** [comment]
Hey @CaptainChemist, lemme ask you: Why do you need to mup init when u already have this mup.js? What if you type mup setup && mup deploy directly?

**Comment by CaptainChemist** [comment]
mup init will create a blank version of this document which I then filled in. mup setup works great but mup deploy gives me the stack size exceeded error.

**Comment by madushan1000** [comment]
@CaptainChemist Is there any other logs other than that error? Can you post them.

**Comment by metadan** [comment]
@CaptainChemist  Did you resolve this? I'm seeing the same issue at the moment.

edit: In my instance it seems to successfully build but then fail during the bundle.tar.gz creation.

**Comment by CaptainChemist** [comment]
I didn't end up solving this problem with mup. I used a newer mupx that had the docker container updated. I know that it isn't the ideal solution but I still cannot get this new version of mup to work today. I can `mup setup` with no issues. When I `mup deploy` I initially get the error:

`AssertionError: "undefined" === "function"
`

When I type `mup logs` I get the following error:

```
[104.131.9.10]"docker logs" requires exactly 1 argument(s).
See 'docker logs --help'.

Usage:  docker logs [OPTIONS] CONTAINER

Fetch the logs of a container
```

This is my js file:

```
module.exports = {
  servers: {
    one: {
      host: '104.131.9.10',
      username: 'root',
      pem: '/Users/user/.ssh/digitalocean'
    }
  },

  meteor: {
    name: 'meteor',
    path: '/users/user/development/project',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: '104.131.9.10',
      MONGO_URL: 'mongodb://user@pass@bla.mlab.com:39685/production'

    },

    dockerImage: 'kadirahq/meteord',
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by WayneUong** [comment]
I'm getting `"docker logs" requires exactly 1 argument(s).` as well
