### ISSUE TITLE
pem issue: Error All configured authentication methods failed

### ISSUE THREAD

**Issue by elie222** [zodern/meteor-up#188]
Hi,

Trying to move over from mupx to the new mup, but when I deploy I get this error:
"Error All configured authentication methods failed".

I assume the error is with my pem file, although this used to work with the old mup and mupx. Have there been any changes here that would stop this from working?

My file looks something like this:

```
module.exports = {
  servers: {
    one: {
      host: '123.4.5.6',
      username: 'xx',
      pem: '/Users/xx/.ssh/id_rsa_xx',
      env: {
        SOME_ENV_VAR: 'xxx'
      }
    },
```

The pem file does not have a passphrase.

**Comment by madushan1000** [comment]
It should work, You can also try removing the `pem` field and using `ssh-agent` instead.

**Comment by razlupercio** [comment]
I removed the `pem` field and used the `ssh-agent` but still have problems, what could be the problem?

**Comment by elie222** [comment]
`ssh-agent` works.
@raz-l there were some ssh issues when upgrading to OS X Sierra (these were general issues not related to mup though. All ssh to servers stopped for a lot of people).

**Comment by guilcorp** [comment]
@elie222 How did you solve it?
I made the update of OSX few hours ago but don't have any issue with ssh in terminal to my servers only with mup "Error All configured authentication methods failed". Thanks

**Comment by elie222** [comment]
Add ssh-agent: pathtopemfile
