### ISSUE TITLE
Using "~" in pem is making mup silently fail

### ISSUE THREAD

**Issue by theodorDiaconu** [zodern/meteor-up#189]
```
module.exports = {
    servers: {
        one: {
            "host": "XXX",
            "username": "ubuntu",
            "pem": "~/.ssh/lead-aws.key"
        }
    },
// the rest
};
```

$ mup deploy
Building App Bundle Locally
$

It just stops. No warning. No error. No nothing.
If I make it _/home/theodor/.ssh/lead-aws.key_ it works.
Wasted 30 minutes for this.

I also think there is an error with app path and using "~".

**Comment by twavis** [comment]
+1, been searching for this for over an hour, so glad to come across this

**Comment by MichaelJCole** [comment]
This also happens if there and extra space at the end:

Works on Linux:

```
      pem: '../../../../../../.ssh/id_rsa'
```

Doesn't work:

```
      pem: '../../../../../../.ssh/id_rsa '
```

**Comment by zodern** [comment]
Version 1.2.2 will display a message if it can not find the pem file.
