### ISSUE TITLE
Error when running the mup setup

### ISSUE THREAD

**Issue by GoChaToken** [zodern/meteor-up#190]
When I run the mup setup commend.
There's an error when the commend tries to start the mongodb. 
![image](https://cloud.githubusercontent.com/assets/13998825/17419825/431c254e-5a6d-11e6-99a8-25607e230f2d.png)

**Comment by lyquocnam** [comment]
+1

**Comment by madushan1000** [comment]
looks like you already have mongodb running in your VM.

**Comment by GoChaToken** [comment]
Yeah. I find the process which binds the port and kill the process. The error is fixed.
Thanks for help!
