### ISSUE TITLE
Custom name for mup.js

### ISSUE THREAD

**Issue by jbg77** [zodern/meteor-up#192]
I have a conflict between notepad++ and mup.
When I type mup that open notepad++.

Edit: In fact windows want to open mup.js file

**Comment by GuillaumeDeconinck** [comment]
If you still haven't found a solution, check the issue https://github.com/kadirahq/meteor-up/issues/185

**Comment by jbg77** [comment]
It's more an enhancement than an issue, I can run mup with:
`C\:"Program Files\nodejs\mup`
Thank you anyway

**Comment by madushan1000** [comment]
Install mup@1.0.2 from npm
