### ISSUE TITLE
volumes explained

### ISSUE THREAD

**Issue by aadamsx** [zodern/meteor-up#193]
The only issue I have using docker for Meteor is I have a special case.

I install executable I use to generate PDFs on the EC2 instance, the install is pdftk. Also, while generating the PDF, I use a directory outside of my Meteor application and store PDF templates there. I also write temporary files to the file system outside of the Meteor application. Would this be possible with a Docker container? Could I build a container with a directory structure store PDF templates in a folder structure outside of my Meteor application? It would be ideal to keep this directory and file structure in place and just update the Meteor application within the Docker container; that way I don't have to build this each time I do a new deployment. Or would it be better to have these folders and files outside of the docker container (keeping in mind this is a dependency)?

I've read you can put multiple instances together, I've also heard maybe I need to mount volumes, but I'm not sure where to start.

Will the volumes settings help with this issue?

volumes: { //optional, lets you add docker volumes
      "/host/path": "/container/path", //passed as '-v /host/path:/container/path' to the docker run command
      "/second/host/path": "/second/container/path"
    },

**Comment by madushan1000** [comment]
Yeah, mount your external directories as docker volumes using the `meteor.volumes` option in `mup.js`
