### ISSUE TITLE
No container deployed, mup logs fails with "No such container"

### ISSUE THREAD

**Issue by SachaG** [zodern/meteor-up#195]
I'm able to run `mup setup` and `mup deploy` fine, but no app is actually deployed, and `docker ps` on the server returns an empty list. And running `mup logs -f` returns a "no such container" error. 

Any idea what could be going on?

**Comment by madushan1000** [comment]
I'm not sure, can you post yout `mup.js` and output of the `mup setup` and `mup deploy`

**Comment by arunoda** [comment]
@SachaG try to do this against a new server. I think this is not compatible with the older version.

**Comment by SachaG** [comment]
Here's my `mup.js`: https://gist.github.com/SachaG/d6ca115dfae0eaa7d4836760816561ac

**Comment by madushan1000** [comment]
I don't see anything wrong with the config file. Any outputs from `mup setup` or `mup deploy`?

**Comment by SachaG** [comment]
mup setup: 

```
Sachas-MacBook-Pro:.deploy sacha$ mup setup

Started TaskList: Setup Docker
[138.68.20.174] - setup docker
[138.68.20.174] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[138.68.20.174] - Setup Environment
[138.68.20.174] - Setup Environment: SUCCESS
```

mup deploy: 

```
Sachas-MacBook-Pro:.deploy sacha$ mup deploy
Building App Bundle Locally

Changes to your project's package version selections:

utilities:react-list-container  upgraded from 0.1.13 to 0.1.14

Started TaskList: Pushing Meteor
[138.68.20.174] - Pushing Meteor App Bundle to The Server
[138.68.20.174] - Pushing Meteor App Bundle to The Server: SUCCESS
[138.68.20.174] - Pushing the Startup Script
[138.68.20.174] - Pushing the Startup Script: SUCCESS
```

mup logs:

```
Sachas-MacBook-Pro:.deploy sacha$ mup logs
[138.68.20.174]Error: No such container: craternova
```

docker ps:

```
root@craternova2:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

If you have time, maybe you can try deploying the latest `devel` branch of Telescope? 

https://github.com/TelescopeJS/Telescope/tree/devel

**Comment by madushan1000** [comment]
At the first glance, there is a part of deploy log missing. There should be some more information after `Pushing startup script`. 
I'll take a stab at telescope deployment.

**Comment by SachaG** [comment]
Thanks! I'm sure it's something super simple, but since I haven't used mup2 before it's hard to know how it's supposed to behave…

**Comment by madushan1000** [comment]
Looks like I can't deploy Telescope because some of the binary dependencies fail to build probably because of problems in the docker image. 
But I couldn't replicate this specific problem. I always had the docker container started in the server.

**Comment by SachaG** [comment]
Oh, you can usually solve that binary dependency problem with `meteor update meteorhacks:kadira-binary-deps` (or just remove `nova:kadira`). 

But if it works for you, could you give me your `mup.js` file so I can try again?

**Comment by madushan1000** [comment]
On a second note, It worked just fine with ubuntu 14.04 on a digitalocean droplet. 

``` javascript
module.exports = {
  servers: {
    one: {
      host: '1.2.3.4',
      username: 'root',
      // pem: './mykey',
    },
  },

  meteor: {
    name: 'tele',
    path: '../',
    servers: {
      one: {},
    },
    env: {
      ROOT_URL: 'http://1.2.3.4',
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    dockerImage: "kadirahq/meteord:base"
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by SachaG** [comment]
ok, that gives me hope. I'll try again later and report back then :)

**Comment by SachaG** [comment]
Still doesn't work :( Using the exact same mup.js: 

```
Sachas-MacBook-Pro:.deploy sacha$ mup setup

Started TaskList: Setup Docker
[159.203.185.250] - setup docker
[159.203.185.250] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[159.203.185.250] - Setup Environment

Started TaskList: Setup Mongo
[159.203.185.250] - setup environment
[159.203.185.250] - setup environment: SUCCESS
[159.203.185.250] - copying mongodb.conf
[159.203.185.250] - Setup Environment: SUCCESS
[159.203.185.250] - copying mongodb.conf: SUCCESS

Started TaskList: Start Mongo
[159.203.185.250] - start mongo
[159.203.185.250] - start mongo: SUCCESS
Sachas-MacBook-Pro:.deploy sacha$ mup deploy
Building App Bundle Locally

Started TaskList: Pushing Meteor
[159.203.185.250] - Pushing Meteor App Bundle to The Server
[159.203.185.250] - Pushing Meteor App Bundle to The Server: SUCCESS
[159.203.185.250] - Pushing the Startup Script
[159.203.185.250] - Pushing the Startup Script: SUCCESS
Sachas-MacBook-Pro:.deploy sacha$ mup logs -f
[159.203.185.250]Error: No such container: tele
```

**Comment by SachaG** [comment]
I also tried with two completely different apps on a fresh Ubuntu 14.04.5 x64 droplet and got the same result. At this point I really don't know what's going on… Is it possible my own local Mup2 is corrupted or something?

**Comment by SachaG** [comment]
Oh interesting, I tried `npm list mup` and it gave me this:

```
Sachas-MacBook-Pro:~ sacha$ npm list mup
/Users/sacha
└── mup@0.11.3
```

Is it possible that I'm somehow using the old version of mup even after running `npm install -g mup`? I feel like it might've been a good idea to give this package a new name to avoid this kind of problem?

**Comment by SachaG** [comment]
I got rid of every duplicate `mup` folder I could find and upgraded Node to 5.4.0. Still same problem, it stops halfway through `meteor deploy`.

**Comment by madushan1000** [comment]
It might be the case, can you try completely removing mup and installing mup@1.0.1?

**Comment by SachaG** [comment]
Removing and reinstalling didn't change anything.

**Comment by madushan1000** [comment]
is your mup version now 1.0.1?

**Comment by SachaG** [comment]
Well, `npm list mup` doesn't work anymore for some reason, but `which mup` does point to the right place as far as I can tell:

```
Sachas-MacBook-Pro:~ sacha$ npm list mup
/Users/sacha
└── (empty)

npm ERR! code 1
Sachas-MacBook-Pro:~ sacha$ which mup
/Users/sacha/.nvm/versions/node/v5.4.0/bin/mup
```

**Comment by madushan1000** [comment]
can you try running the deploy with `DEBUG=* mup deploy` and post the log?

**Comment by SachaG** [comment]
```
Sachas-MacBook-Pro:.deploy sacha$ DEBUG=* mup deploy
  mup:module:default exec => mup deploy +0ms
  mup:module:meteor exec => mup meteor deploy +1ms
  mup:module:meteor exec => mup meteor push +1ms
Building App Bundle Locally

Started TaskList: Pushing Meteor
[159.203.185.250] - Pushing Meteor App Bundle to The Server
  nodemiral:sess:159.203.185.250 copy file - src: /tmp/e8bd2ef7-f788-4cc5-b458-38fbd4dadfcd/bundle.tar.gz, dest: /opt/tele/tmp/bundle.tar.gz, vars: undefined +0ms
[159.203.185.250] - Pushing Meteor App Bundle to The Server: SUCCESS
[159.203.185.250] - Pushing the Startup Script
  nodemiral:sess:159.203.185.250 copy file - src: /Users/sacha/.nvm/versions/node/v5.4.0/lib/node_modules/mup/lib/modules/meteor/assets/templates/start.sh, dest: /opt/tele/config/start.sh, vars: {"appName":"tele","useLocalMongo":1,"port":80,"logConfig":{"opts":{"max-size":"100m","max-file":10}},"image":"kadirahq/meteord:base"} +31s
[159.203.185.250] - Pushing the Startup Script: SUCCESS
  mup:module:meteor exec => mup meteor envconfig +2m
```

**Comment by MasterJames** [comment]
What version of Node? Try putting 4. 
https://github.com/meteor/meteor/pull/7218
if it's not a new instance of Ubuntu 14 for the target try via SSH to purge all docker instances.

```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
```

If that doesn't help maybe try a fresh user account on your deployment system with a default meteor app (and a fresh deployment target) and then with your app.

**Comment by SachaG** [comment]
@MasterJames none of that seems to make a difference. Maybe I should try deploying from another machine…

**Comment by MasterJames** [comment]
Well I would add that inversely to adding bits in from a clean project (that deploys), you can try stripping things out in a copy until something gives.
If your saying a fresh user can't deploy a default meteor app I guess that's one way to try and isolate the issue. I would think deploying from an Ubuntu VM via VirtualBox or what have you would do the trick.

**Comment by SachaG** [comment]
I tried again deploying the Meteor to-do list app from a DO Ubuntu instance to another DO Ubuntu instance using @madushan1000's mup.js file, same thing:

```
root@craternova3:~/simple-todos-react/.deploy# mup deploy
Building App Bundle Locally

Unable to resolve some modules:

  "react" in /root/simple-todos-react/imports/ui/AccountsUIWrapper.jsx
(web.browser)
  "react-dom" in /root/simple-todos-react/imports/ui/AccountsUIWrapper.jsx
(web.browser)
  "classnames" in /root/simple-todos-react/imports/ui/Task.jsx (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save react react-dom classnames


Started TaskList: Pushing Meteor
[192.241.231.80] - Pushing Meteor App Bundle to The Server
[192.241.231.80] - Pushing Meteor App Bundle to The Server: SUCCESS
[192.241.231.80] - Pushing the Startup Script
[192.241.231.80] - Pushing the Startup Script: SUCCESS
```

**Comment by MasterJames** [comment]
what happens when you do like it says and run 
`meteor npm install --save react react-dom classnames`
and then deploy again?

**Comment by SachaG** [comment]
Same thing.

**Comment by MasterJames** [comment]
https://github.com/reactionic/reactionic-kitchensink/issues/17

```
This happens because the app folder has a symbolic link to node_modules.
The symbolic links are working right now in windows.

The quickest fix would be passing the node_modules to the app folder until we fix the symbolic link problem.
```

**Comment by SachaG** [comment]
@MasterJames I think I was only seeing that message because I hadn't run `npm install`, I don't think it's related to `mup2`?

**Comment by madushan1000** [comment]
I just tried deploying both Telescope and react-todo-list from do droplet to a do droplet(both running on ubuntu 14.04.5) . And both were successful. Here is the mup.js file

``` javascript
module.exports = {
  servers: {
    one: {
      host: '1.2.3.4',
      username: 'root'
      // pem:
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'app',
    path: '../',
    servers: {
      one: {}
    },
    env: {
      ROOT_URL: 'http://1.2.3.4',
      MONGO_URL: 'mongodb://localhost/meteor'
    },

    dockerImage: 'kadirahq/meteord',
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by ghost** [comment]
@SachaG I am experiencing this same issue. I can replicate this issue with a new Meteor 1.4.0.1 project on a new Ubuntu server.

mup.js:

```
module.exports = {
  servers: {
    one: {
      host: "SeverIP",
      username: "root",
      pem: "/Users/USERNAME/.ssh/id_rsa",
    },
  },

  meteor: {
    name: "APPNAME",
    path: "../",
    servers: {
      one: {},
    },
    env: {
      ROOT_URL: "https://URL",
      MONGO_URL: "mongodb://mongodb:27017/APPNAME",
      PORT: 3000
    },
    dockerImage: "jacquesbl/meteord",
    deployCheckWaitTime: 120
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by ghost** [comment]
@SachaG I have modified `mupx` to use a docker image which works with Meteor 1.4+ and am now using that to deploy the apps which are failing with `mup`.

I am still looking into the `mup` issue. Are you still experiencing it?

**Comment by SachaG** [comment]
@jacquesblom404 yes, I'm experiencing it. How did you modify `mupx` btw?

**Comment by queso** [comment]
Is there a setting to change the mupx docker image? Or is it hard coded into the npm src somewhere @jacquesblom404?

**Comment by ghost** [comment]
@SachaG, @queso Clone the repo and look for instances of `meteorhacks/meteord:base` with `kadirahq/meteord` (in `templates/linux/start.sh`). Then install your cloned version of mupx. Let me know if that works for you.

**Comment by emilbryggare** [comment]
@SachaG: I think mup is not setting up you environment variables correctly.

On the server verify that /opt/$APPNAME/config/env.list exists and is up to date with mup.js and settings.json.

I'm guessing the reason it worked for @madushan1000 is because he used the sample.settings.json while you used Telescopes production settings.json. Another guess of mine is that your production settings.json have trailing commas. (Or some other formatting that mup does not support)

After this output from mup

```
[1.1.1.1] - Pushing the Startup Script
[1.1.1.1] - Pushing the Startup Script: SUCCESS
```

this output is expected, but never shown in your comments above.

```
Started TaskList: Configuring  Meteor Environment Variables
[1.1.1.1] - Sending Environment Variables
[1.1.1.1] - Sending Environment Variables: SUCCESS
```

A lot of guesses from my side. But I hope it will help you pinpoint the problem. It helped me solve mine [here](https://github.com/kadirahq/meteor-up/issues/238).

**Comment by thomasspiesser** [comment]
For me it was new-lines in settings.json that prevented mup from creating the `/opt/$APPNAME/config/env.list` file.

**Comment by nicklammertyn** [comment]
Confirmed here that settings.json is the issue and cleaning it up worked, also set the settings file as a parameter with --settings, not sure if that could have an effect

**Comment by SachaG** [comment]
Well I'm having this issue with a fresh `meteor create` app that doesn't have any settings, so in my case it must be something else…

**Comment by thomasspiesser** [comment]
@SachaG did you try with a settings file that just contains `{}` or completely w/o one?

**Comment by SachaG** [comment]
@thomasspiesser oh wow, I just tried with a settings file that only contained `{}` and it finally worked!!! Thank you!! Haha, I must've tried this at least 20 times…

I haven't tried deploying my actual app yet but at least there's progress. I wish `mup` would tell you more about why it's failing though, if a `settings.json` file is required then showing an error message wouldn't be that hard and would save some time…

**Comment by thomasspiesser** [comment]
@SachaG glad it works now :) let us know how it goes with your actual app.

**Comment by SachaG** [comment]
I was _finally_ able to deploy Telescope with an empty (`{}`) settings.json file. Now to try with the real one…

Note that I also had to remove the Kadira package, because the binary made the deploy process fail.

**Comment by v3rron** [comment]
@SachaG did you get a chance to figure it out? Having exact same issue with Meteor 1.4.1 and mup2. Using abernex docker image. Everything seems successful but there is no app container created.

**Comment by SachaG** [comment]
I'm not sure what exactly made it work in the end, but it seems like a `settings.json` file is required for the deployment to work. Did you try with one?

**Comment by v3rron** [comment]
Ahh I forgot to add --settings to `mup deploy` command.
Now it works.
But thanks anyway.

**Comment by skarborg** [comment]
I also had an issue with my settings file (invalid JSON).  Fixing that solved my deploy issues.

**Comment by pablovilla83** [comment]
Extra , in the public section of the settings JSON (invalid) makes the deploy fail. It appears the "No such container" line is written during the mup setup phase, tested on a new box. Better error handling would be appreciated :) - it would be awesome if the settings and config files are checked before the build kicks off

**Comment by zodern** [comment]
I plan to improve this with 1.2.

**Comment by zodern** [comment]
Version 1.2 will improve this:

- better message if the `settings.json` is not found
- uses [parse-json](https://www.npmjs.com/package/parse-json) to give better errors on invalid json
- loads and parse the file before starting the build

 I think that fixes all of the remaining issues mentioned here.
