### ISSUE TITLE
Error spawn C:\WINDOWS\System32\cmd.exe ENOENT aka. Error spawn meteor ENOENT

### ISSUE THREAD

**Issue by Faberle** [zodern/meteor-up#197]
Whenever I try to deploy I get the following error (Debug on):

```
PS C:\[.....]\.deploy> mup deploy
    mup:module:default exec => mup deploy +0ms
    mup:module:meteor exec => mup meteor deploy +13ms
    mup:module:meteor exec => mup meteor push +9ms
Building App Bundle Locally
Error spawn C:\WINDOWS\System32\cmd.exe ENOENT
```

I have checked "C:\WINDOWS\System32\cmd.exe" exists and is working well. 
Enviroment: Win 10 x64

**Comment by Faberle** [comment]
After an hour of searching I now know that my path to my app was wrong... 
Feature request: More informative error when app can't be found xD

**Comment by Tbutnyakov** [comment]
@Faberle hi! Did you get errors while "meteor setup"? Me, and other guys can't complete "mup setup", cause windows script host didn't allow "mup" run the script automatically

**Comment by Sivli-Embir** [comment]
This also happened to me on MacOS, successfully setup but error on deploy. Issue was a malformed meteor path.

**Comment by zodern** [comment]
In 1.2.2 it will display a better message if the app path is incorrect.
