### ISSUE TITLE
Mup 1.0.1 deploy failed!!!!

### ISSUE THREAD

**Issue by wwlweihai** [zodern/meteor-up#198]
### Deploy failed with mup 1.0.1

the client node version is 4.4.7. and the server version is 4.4.7 ,too.

> ```
>     -----------------------------------STDERR-----------------------------------
>     stall script 'node npm-rebuild.js'.
>     npm ERR! Make sure you have the latest version of node.js and npm installed.
>     npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
>     npm ERR! not with npm itself.
>     npm ERR! Tell the author that this fails on your system:
>     npm ERR!     node npm-rebuild.js
>     npm ERR! You can get information on how to open an issue for this project with:
>     npm ERR!     npm bugs meteor-dev-bundle
>     npm ERR! Or if that isn't available, you can get their info via:
>     npm ERR!     npm owner ls meteor-dev-bundle
>     npm ERR! There is likely additional logging output above.
> 
>     npm ERR! Please include the following file with any support request:
>     npm ERR!     /bundle/bundle/programs/server/npm-debug.log
> 
>     > meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
>     > node npm-rebuild.js
> 
> 
>     > bcrypt@0.8.6 install /bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt
>     > node-gyp rebuild
> 
> 
>     => Redeploying previous version of the app
> ```

how to solve the problem!!!!

**Comment by vedovato** [comment]
I had successfully deployed my app with bcrypt@0.8.7. Also had to remove some non-compatible node 4.x.x packages.

**Comment by guillim** [comment]
@wwlweihai  @vedovato i had a similar issue but i didn't want do stay on v4 packages so I created a docker that could overcome this. try it out:
dockerImage:"guillim/meteord"

Now it works great !

It is bascially the docker created by abernix but where I updated node (from v4 to v6) and installed some npm packages i needed
