### ISSUE TITLE
Port issue after deploying to subdomain

### ISSUE THREAD

**Issue by lhz516** [zodern/meteor-up#200]
After I modified docker image to 'abernix/meteord:base', I could finally deploy meteor 1.4 apps to my server.

However, if I tried to deploy an app to subdomain

```
env: {
  ROOT_URL: 'http://sub.example.com'
}
```

Both `sub.example.com` and `example.com` are deployed.
How can I only deploy an app to subdomain and not to affect the main domain？

**Comment by madushan1000** [comment]
Can you post your full `mup.js` file?

**Comment by lhz516** [comment]
@madushan1000 Here's my mup.js file.

```
module.exports = {
  servers: {
    one: {
      host: '0.0.0.0',
      username: 'ubuntu',
      pem: '../../example.pem'
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'myApp',
    path: '../',
    servers: {
      one: {}
    },
    buildOptions: {
      // serverOnly: true
      // debug: true,
      // mobileSettings: {
      //   yourMobileSetting: "setting value"
      // }
    },
    env: {
      ROOT_URL: 'http://subdomain.example.com',
      MONGO_URL: 'mongodb://my_external_mongo_url'
    },

    dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 30
  }
};
```

**Comment by madushan1000** [comment]
According to the config, there is no clear way to deploying two instances. Maybe the old instance is still running at `example.com`?

**Comment by lhz516** [comment]
Hi @madushan1000 , I only saw one docker container on the server when I ran `docker ps`

```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                NAMES
90ca873d65da        abernix/meteord:base   "/bin/sh -c 'bash $ME"   27 hours ago        Up 27 hours         0.0.0.0:80->80/tcp   myApp
```

And when I run `mup stop` on my local machine. Both of the two domains were down.
I believe that I only deployed one instance, but somehow nginx forward it to two domains.

**Comment by madushan1000** [comment]
You might have to take a look at your nginx configuration and DNS records. I don't think the issue is mup related.

**Comment by lhz516** [comment]
@madushan1000 I didn't install nginx on the server.
The doc said that mup is now using nginx, but I'm not sure if mup enabled it, because I didn't config SSL in `mup.js`

**Comment by madushan1000** [comment]
No, mup doesn't use nginx by default. So the problem should be with your DNS records.

**Comment by lhz516** [comment]
@madushan1000 Fixed it. Thanks!

Closing this issue
