### ISSUE TITLE
Deploy on a server with other projects

### ISSUE THREAD

**Issue by afrantz** [zodern/meteor-up#201]
Hello,

**I already have a server with nginx and meteor projetcs (without mup). I would like to use mup on a new project with my existing nginx (port 80) and link it to the docker image (other port different than 80) and use my existing database (port 27017)**

I've never used Docker.

Is it possible to set the port of Docker without editing manually /opt/<appName>/config/start.sh 
?

I tried `mup setup` and `mup deploy` but i get this error : 

> ```
>     -----------------------------------STDERR-----------------------------------
>     package.json meteor-dev-bundle@0.0.0 No description
>     npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
>     npm WARN package.json meteor-dev-bundle@0.0.0 No README data
>     npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
>     => Starting meteor app on port:80
> 
> 
>     assert.js:93
>       throw new assert.AssertionError({
>             ^
>     AssertionError: "undefined" === "function"
>         at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
>         at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
>         at Module._compile (module.js:456:26)
>         at Object.Module._extensions..js (module.js:474:10)
>         at Module.load (module.js:356:32)
>         at Function.Module._load (module.js:312:12)
>         at Module.require (module.js:364:17)
>         at require (module.js:380:17)
>         at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
>         at Module._compile (module.js:456:26)
> 
>     => Redeploying previous version of the app
> 
>     -----------------------------------STDOUT-----------------------------------
> 
>     To see more logs type 'mup logs --tail=50'
> 
>     ----------------------------------------------------------------------------
> ```

This is my mup.js : 

``` javascript
module.exports = {
  servers: {
    one: {
      host: 'myawesomeproject.com',
      username: 'root',
      pem: 'myawesomekey'
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'myawesomeproject',
    path: '../',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      PORT: 8080,
      ROOT_URL: 'myawesomeproject.com',
      MONGO_URL: 'mongodb://localhost:27017/myawesomeproject',
    },

    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 180
  }
};
```

This is my start.sh : 

```
#!/bin/bash

APPNAME=myawesomeproject
APP_PATH=/opt/$APPNAME
BUNDLE_PATH=$APP_PATH/current
ENV_FILE=$APP_PATH/config/env.list
PORT=8080

# Remove previous version of the app, if exists
docker rm -f $APPNAME

# Remove frontend container if exists
docker rm -f $APPNAME-frontend

# We don't need to fail the deployment because of a docker hub downtime
set +e
docker pull meteorhacks/meteord:base
set -e

docker run \
  -d \
  --restart=always \
  --publish=$PORT:8080 \
  --volume=$BUNDLE_PATH:/bundle \
  --hostname="$HOSTNAME-$APPNAME" \
  --env-file=$ENV_FILE \
  \
  \
  --log-opt max-size=100m --log-opt max-file=10 \
  \
  --name=$APPNAME \
  meteorhacks/meteord:base
```

THANKS !

**Comment by madushan1000** [comment]
You don't have to change the source. Install mup again from npm `npm install -g npm`.
And set `meteor.env.PORT` to whatever port you want.

**Comment by afrantz** [comment]
Hello @madushan1000 ,

Thanks for your respsonse.
I just tried and i get same error after `mup deploy` :  

> [myawesomeproject.com] - Pushing Meteor App Bundle to The Server
> [myawesomeproject.com] - Pushing Meteor App Bundle to The Server: SUCCESS
> [myawesomeproject.com] - Pushing the Startup Script
> [myawesomeproject.com] - Pushing the Startup Script: SUCCESS
> 
> Started TaskList: Configuring  Meteor Environment Variables
> [myawesomeproject.com] - Sending Environment Variables
> [myawesomeproject.com] - Sending Environment Variables: SUCCESS
> 
> Started TaskList: Start Meteor
> [myawesomeproject.com] - Start Meteor
> [myawesomeproject.com] - Start Meteor: SUCCESS
> [myawesomeproject.com] - Verifying Deployment
> [myawesomeproject.com] x Verifying Deployment: FAILED
> 
> ```
>     -----------------------------------STDERR-----------------------------------
>     package.json meteor-dev-bundle@0.0.0 No description
>     npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
> 
>     npm WARN package.json meteor-dev-bundle@0.0.0 No README data
>     npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
>     => Starting meteor app on port:80
> 
>     assert.js:93
>       throw new assert.AssertionError({
>             ^
>     AssertionError: "undefined" === "function"
>         at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
>         at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
>         at Module._compile (module.js:456:26)
>         at Object.Module._extensions..js (module.js:474:10)
>         at Module.load (module.js:356:32)
>         at Function.Module._load (module.js:312:12)
>         at Module.require (module.js:364:17)
>         at require (module.js:380:17)
>         at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
>         at Module._compile (module.js:456:26)
> 
>     => Redeploying previous version of the app
> 
>     -----------------------------------STDOUT-----------------------------------
> 
>     To see more logs type 'mup logs --tail=50'
> 
>     ----------------------------------------------------------------------------
> ```

**Comment by madushan1000** [comment]
Use the dockerImage from `kadirahq/meteord`

**Comment by afrantz** [comment]
Hello @madushan1000,

Thank you for your response.
I inform you that having set the new image, I still have the same error :/.
