### ISSUE TITLE
Guidance on deploying to Elastic Beanstalk? Impossible?

### ISSUE THREAD

**Issue by jononomo** [zodern/meteor-up#202]
I need to deploy to Elastic Beanstalk so we can make use of our HTTPS.  I have been told that this is not possible using Meteor-Up.  However, I would appreciate confirmation here that it is indeed not possible. Thanks much.

**Comment by madushan1000** [comment]
I'm not sure about this. we never tried to use mup that way. You can certainly try and publish the results.
