### ISSUE TITLE
Problem with dockers timezone

### ISSUE THREAD

**Issue by mfeuermann** [zodern/meteor-up#204]
Hello, 

I would like to change dockers timezones in configuration. Is it possible ?
In this moment im storing data to mongo server with timezone settings Europe/Prague (+2)
In application syncing time with meteor/mizzao:timesync. Clients are in different timezones.

In app using moment() library.

In previous version of MUP everythink works fine. 
In this version with docker its not OK.

Is possible to edit docker settings for timezone ?

**Comment by madushan1000** [comment]
Create a different docker image with configurations you want using `kadirahq/meteord` as base and use it.

**Comment by mfeuermann** [comment]
Ok thanks

**Comment by AhmedKanany** [comment]
Hello , 
could you give me code example to set my own timezone please ?

**Comment by thearabbit** [comment]
I have the same problem.
+1

**Comment by ivan133** [comment]
```
    docker: {
      image: 'abernix/meteord:node-8.15.1-base',
      stopAppDuringPrepareBundle: false,
      args: ["-v /etc/timezone:/etc/timezone","-v /etc/localtime:/etc/localtime"]
    },
```

**Comment by thearabbit** [comment]
Now I manage timezone on my app.
It work fine.
