### ISSUE TITLE
'Unexpected identifier' on mup setup

### ISSUE THREAD

**Issue by allenfuller** [zodern/meteor-up#206]
Hi guys,

Trying to get setup on Digital Ocean and running into a problem. After setting up a dedicated directory, creating the droplet, and installing and initializing mup, I'm trying to run `mup setup`.

But when I do, I just get the console message "Unexpected identifier".

No other errors, warning, logs, etc.

I'm on a Mac. Installed Node originally from Homebrew. Below is my mup.js file.

```
module.exports = {
  servers: {
    one: {
      host: '1.0.0.0',
      username: 'root'
      pem: '~/.ssh/id_rsa'
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'app',
    path: '.',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
      debug: true
    },
    env: {
      ROOT_URL: 'http://app.com',
      MONGO_URL: 'mongodb://localhost/meteor'
    },

    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {}
    }
  }
};
```

Any ideas? Thanks in advance!

**Comment by allenfuller** [comment]
Update: I tried changing the SSH key link to /User/[user]/.ssh/id_rsa per issue #189, but still get "Unexpected identifier".

**Comment by allenfuller** [comment]
LOL. Missing a comma. Happens every time... Never mind!

**Comment by vangorra** [comment]
To clarify. @allenfuller is referring to the comma after the username field in the config. Took me forever to find my missing comma.

**Comment by mickdekkers** [comment]
Would be nice if mup printed the line number where the unexpected identifier was encountered.

**Comment by asakk046** [comment]
Thanks @vangorra!
