### ISSUE TITLE
Meteor Project w/o Mongo?

### ISSUE THREAD

**Issue by krishaamer** [zodern/meteor-up#208]
Hey, thanks for the awesome package! 

I'm deploying a static Meteor site without the need for a Mongo DB. However I get an error saying the MONGO_URL is required. Is there a setting to disable Mongo completely?

Thanks,
Kris

**Comment by madushan1000** [comment]
I'm not sure, that's a meteor related issue. But I think you could get away with setting a fake mongo url.
