### ISSUE TITLE
Does SSL config need to be improved?

### ISSUE THREAD

**Issue by gsabran** [zodern/meteor-up#209]
I don't much about the SSL settings, but looking at the forks I've seen that commit: https://github.com/ckiely91/meteor-up-1/commit/f8afc136109270ff4d921c09dc95f7084a74f915
Is there something to improve with the SSL setup security?

**Comment by MattiSG** [comment]
Yes, see https://github.com/arunoda/meteor-up/issues/1056 and https://github.com/arunoda/meteor-up/issues/963 for example, and https://github.com/meteorhacks/mup-frontend-server/issues/14 for the canonical reason. Currently, the default `mupx` deployment is vulnerable to [CVE2016-2107](https://blog.cloudflare.com/yet-another-padding-oracle-in-openssl-cbc-ciphersuites/).

**Comment by shadowcodex** [comment]
Is this still a vulnerability?

**Comment by shadowcodex** [comment]
@zodern have you looked into this already?

**Comment by zodern** [comment]
It is. Switching to `nginx-proxy` will fix this.

**Comment by zodern** [comment]
This is fixed when using the reverse proxy for ssl.
