### ISSUE TITLE
MUP without docker?

### ISSUE THREAD

**Issue by nick-preda** [zodern/meteor-up#210]
Hi guys,

is there any chance to deploy a meteor project without the need of using docker?

I am referring to the old mup, which is not being maintained anymore. 
I am still using the old one, but I'm afraid to update meteor from 1.3, to 1.4, as it is using a newer node version.

**Comment by madushan1000** [comment]
Take a look at this fork of the old mup. Looks like it's maintained. https://github.com/aadamsx/meteor-up-classic

**Comment by nick-preda** [comment]
oh wow!

thanks a lot, I'll try opening an issues, to ask whether it works with meteor 1.4
