### ISSUE TITLE
@ (at-sign) in mongodb password breaks mup

### ISSUE THREAD

**Issue by cunneen** [zodern/meteor-up#211]
I had an at-sign in my mongodb user's password in the MONGO_URL, and this breaks mup. For example, if the mongo user's password is ABCDEFG@HIJKLMN

While that's not surprising, it took me hours to figure out the issue because it was just reported as:

```
[example.com] Error: failed to connect to [HIJKLMN:27017]
[example.com]     at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:449:15)
```

and since the password was generated I didn't recognise it as such. 

Some basic regex checking to verify that each component of the parsed URL doesn't itself contain URL characters is needed. E.g. if the username has been parsed as USE:R, or the hostname contains a '@' character etc.

Then a more friendly message could be generated.

**Comment by madushan1000** [comment]
mup doesn't parse the mongo url. Meteor does. mup just passes whatever env vars you specify to meteor regardless of the content.

**Comment by madushan1000** [comment]
BTW try url encoding your password.

**Comment by cunneen** [comment]
OK thanks @madushan1000 .
