### ISSUE TITLE
'mup.js' file not found. Run 'mup init' first. and --config=config/environments/master/mup.js 

### ISSUE THREAD

**Issue by piotrekfracek** [zodern/meteor-up#212]
Hi,

I'm trying to run mup setup with custom config files located in subdirectory.

Command:

```
mup setup --config=config/environments/master/mup.js --settings=config/environments/master/settings.json
```

Result:
`'mup.js' file not found. Run 'mup init' first.`

I'm pretty sure path is correct.

**Comment by madushan1000** [comment]
currently the command line options are not working in the release version. Try the `cli-options` branch on the repo.

**Comment by yogiben** [comment]
@madushan1000 I can't find that branch.

Could you push or better yet merge, push and publish to npm :)

**Comment by madushan1000** [comment]
It's now merged with master branch. I have to fix a few more things. I'll do a release after them.

**Comment by madushan1000** [comment]
Install mup@1.0.2 from npm.
