### ISSUE TITLE
'mup deploy' error on windows

### ISSUE THREAD

**Issue by Errbel** [zodern/meteor-up#225]
Hi,

When I run : "mup deploy" on windows 8.1

I get the following error : 

Building App Bundle Locally
{ cwd: 'C:\Users\gnogn_000\Desktop\myProject\.deploy\Usersgnogn_000DesktopmyProject' }
{ [Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn C:\WINDOWS\system32\cmd.exe',
  path: 'C:\WINDOWS\system32\cmd.exe',
  spawnargs:
   [ '/c',
     'meteor',
     'build',
     '--directory',
     'C:\tmp\c579a69d-5fe1-4534-9678-1e267b677389',
     '--architecture',
     'os.linux.x86_64',
     '--server',
     'http://localhost:3000' ] }

=> Build Error. Check the logs printed above.

I tried to add 'C:\WINDOWS\system32' to the PATH, but error still here.

Can you please help ?
Thx
:)

**Comment by estebanutz** [comment]
@Errbel Check out your mup.js file in .deploy and make sure the "path:" it's pointing to the root of your project, it looks like it's trying to go to .deploy\Usersgnogn_000DesktopmyProject instead of "\Usersgnogn_000DesktopmyProject" See if that helps

**Comment by Errbel** [comment]
Yes you're wright @estebanutz, but hereafter my mup.js file : 

module.exports = {
  servers: {
    one: {
      host: 'xx.xx.xx.xxx',
      username: 'yyy',
      // pem:
      password: 'yyy'
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'myProject',
    path: 'C:\Users\gnogn_000\Desktop\myProject',
    servers: {
      one: {}
    },
    buildOptions: {
      //serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://myProject.com',
      MONGO_URL: 'mongodb://localhost/meteor',
      MAIL_URL: "smtp://xxxxx"
    },

```
dockerImage: 'abernix/meteord:base',//'kadirahq/meteord',
deployCheckWaitTime: 60,

// show a progress bar while uploading. 
// Make it false when you deploy using a CI box.
"enableUploadProgressBar": true
```

  },

  /_mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },_/
};

**What am I doing wrong in the "path" definition ?**

I tried several others ways like '....\myProject' etc... but seems that mup always try to go to .deploy\xxxxx

Thx for your help

**Comment by Errbel** [comment]
Ok, this is an issue in **_path2.default.resolve(api.getBasePath(), config.path)**
in the **mup\lib\modules\meteor\index.js** file, in **push()** function.

It seems that it **can't deal with '\'** character (backslash) and it **concatenate both arguments** !?!

One way to **fix/deal** with that is to **set the PATH in mup.js** file with **'escaping \'** : 

**path: 'C:\\Users\\gnogn_000\\Desktop\\myProject',**

I'm new here, is there a way to fix this in mup source code project ?

@estebanutz @madushan1000 @mnmtanish @vhf @arunoda

Otherwise, mup works perfectly on windows 8.1 and macOsx :+1: 

Thx for this tools :)

**Comment by estebanutz** [comment]
Have you tried using a relative path instead of absolute on your "path:"? Other than that I'm not sure I can help you out I develop on a mac machine so I'm not familiar with windows.
