### ISSUE TITLE
env.list is not created

### ISSUE THREAD

**Issue by reel** [zodern/meteor-up#229]
On a fresh EC2 instance running Amazon Linux AMI, seems like the start.sh script is updated and well. The env.list is never created nor updated.

**Comment by emilbryggare** [comment]
@reel: I think the same issue is discussed here [ISSUE-238](https://github.com/kadirahq/meteor-up/issues/238).

I had this problem and solved it as described [here](https://github.com/kadirahq/meteor-up/issues/238#issuecomment-241610718). 

Hope it helps.
