### ISSUE TITLE
Cannot choose container port

### ISSUE THREAD

**Issue by reel** [zodern/meteor-up#230]
If you use an external load balancer and you'd like to use a different port for the container, it's not available. 

Defaulting to 80 cannot let us run multiple docker instance on the same machine

Thanks!

**Comment by mikemeier** [comment]
@reel see here: https://github.com/kadirahq/meteor-up/blob/master/src/modules/meteor/index.js#L148

I forked the repo and removed this line and it did work then. I'm not sure how to interpret the comment part `// Changing the port is done via the start.sh script`

**Comment by zodern** [comment]
You can set the port in the config:
```
meteor: {
  ...
  port: 3000
}
```
