### ISSUE TITLE
Pure node.js deployments

### ISSUE THREAD

**Issue by tomitrescak** [zodern/meteor-up#231]
Dears, this is a fantastic tool that works so well. Coming out of Meteor for a bit of time and working on pure node.js project, I miss it a lot! I was wondering how difficult it would be to modify this to run pure node.js projects?

For what I know it would only need to skip one step ... bundling of meteor project, and instead it would just pack the node.js project and deploy it to the server.

I tried to find a spot in which I could do it, but I failed.

**Comment by zodern** [comment]
I would like to add this, but it will be a while before I have time to. It wouldn't be difficult to make the changes. If anyone wants to work on a pull request, I would be willing to list what needs to be done and advise how to do it.

**Comment by zodern** [comment]
Work has started on this: https://github.com/zodern/mup-node
