### ISSUE TITLE
MONGO_URL is not being used, looks like local DB instance is hard coded?

### ISSUE THREAD

**Issue by asidiali** [zodern/meteor-up#233]
I just switched over from mupx and I'm trying to get my server back up and running after M1.4. I wiped the DB I thought I was using, only to find the data was persisting in my app...

After further checking I realized that the data had never appeared in the remote DB I wanted to use, and was instead being stored in the local DB.

Checked the start.sh script, as well as the mongo setup scripts, and it looks like the local DB is the only one being used...?

I've quadruple checked my settings/mup files for typos.

I was surprised to not find very many other issues here on this...is it just me or are people not using/checking remote DBs? Would love to know.

**Comment by MasterJames** [comment]
Mup "setup" writes Mongo files to a share folder so the data is persistant from "deploy" while docker run commands make the contain link/mount.

**Comment by asidiali** [comment]
So are you telling me I should leave `MONGO_URL: 'mongodb://localhost/meteor'` and then have 

```
docker: {
      image:'kadirahq/meteord',//optional
      args:[ //optional, lets you add / overwrite any parameter on the docker run command
        "--link=myCustomMongoDB:myCustomMongoDB", //linking example
        "--memory-reservation 200M"//memory reservation example
      ]
    },
```

where the customMongo bit is my remote mongo URL?

If not, could you explain a bit further? Thanks for the help.

**Comment by MasterJames** [comment]
I was saying only that if you rerun 'mup setup' it would write the Mongo data to the target. 'mup deploy' will push the code and build for the target but not stomp on the database, because it uses docker it is told to mount the folder on the target in the docker container.
You'll figure it out. Take a week to learn how it works with docker etc. it's more or less opensource and diggable/viewable. (Other then when making your customizable docker image.)

**Comment by asidiali** [comment]
I used `mup setup` several time already, unfortunately to no avail :/

I've been going through the source already and that's why I'm curious if it's hard coded - as far as I could follow along (no knowledge of docker whatsoever), it seemed to just setup the local mongo instance.

Do you (or anyone?) happen to have an example `mup.js` file that uses a remote db in production? It really does seem like it's just not even being recognized so I'd love to know if I'm the only one experiencing these issues when trying to deploy with a remote db, and maybe I just am using the wrong syntax or something. Not sure.

**Comment by MasterJames** [comment]
Right what ip port are you running your custom mongodb on?

**Comment by ahxar** [comment]
just remove or comment these line in mup.js

```
  mongo: { // optional
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
```

then do
`mup setup`
`mup deploy`

it fix my problem

**Comment by asidiali** [comment]
Thanks @MasterJames for your efforts, @ahmadsafar 's answer solved my problem. Makes total sense...I was setting up mongo anyways and overwriting it.

Thanks for the help!

**Comment by wwlweihai** [comment]
You can see my deploy process at [meteor-deploy](https://github.com/wwlweihai/resume/blob/master/meteor-deploy-zh.md)

**Comment by zeekun** [comment]
Hullo, I was having the same issue as @asidiali and did what @MasterJames proposed but I keep getting this error
![meteor](https://cloud.githubusercontent.com/assets/28468199/26104635/6fe253f4-3a47-11e7-9c3f-a04915fba33f.PNG)

**Comment by zeekun** [comment]
Hullo, I am having the same issue as @asidiali and have done what @MasterJames proposed but I keep getting this error
![meteor](https://cloud.githubusercontent.com/assets/28468199/26104802/1c827170-3a48-11e7-9309-ca7a0aaa119b.PNG)

**Comment by x5engine** [comment]
you need to add this in the docs because it is confusing!

**Comment by LispyAriaro** [comment]
You may have to increase the ```deployCheckWaitTime``` in your mup.js config file
