### ISSUE TITLE
mup setup opens file instead of setting up server

### ISSUE THREAD

**Issue by kenshinman** [zodern/meteor-up#235]
Hi mup setup opens mup.js file instead of setting up server environment

**Comment by mgarf** [comment]
you need to directly reference the mup npm file.

**Comment by nicklammertyn** [comment]
@kenshinman To clarify, you should rename mup.js to something else, then pass that as a parameter, an example: mup setup --config mup-config.js

**Comment by zaklampert** [comment]
when running `mup setup` nothing happens - even when changing the filename and passing as a param as @Nlammertyn mentioned. 

EDIT: using a password instead of `pem` seemed to resolve it for me.

**Comment by zodern** [comment]
The FAQ in the readme now answers how to fix this.
