### ISSUE TITLE
Deploy an existing project and get "Error spawn meteor ENOENT"

### ISSUE THREAD

**Issue by lesliechw** [zodern/meteor-up#236]
```
mup deploy
update 1.0.1 => 1.0.2
Building App Bundle Locally
Error spawn meteor ENOENT
```

Hello all,

I deploy successfully previously and now when I want to update my app and I get this when execute "mup deploy". The above error is what I get.

How to fix this? Please advice, thank you.

**Comment by franciscohanna92** [comment]
Could you provide your mup.js file?
