### ISSUE TITLE
Fail to deploy/start the app - no such container --> docker: open /opt/app/config/env.list: no such file or directory.

### ISSUE THREAD

**Issue by vmptk** [zodern/meteor-up#238]
Hello, 

Any hints on this one?

> mup start

[46.101.98.119] x Start Meteor: FAILED

```
-----------------------------------STDERR-----------------------------------
Error response from daemon: No such container: app
Error response from daemon: No such container: app-frontend
docker: open /opt/app/config/env.list: no such file or directory.
See 'docker run --help'.
-----------------------------------STDOUT-----------------------------------
base: Pulling from abernix/meteord
5c90d4a2d1a8: Pulling fs layer
233dc252507a: Pulling fs layer
927ff6ce0b84: Pulling fs layer
233dc252507a: Verifying Checksum
233dc252507a: Download complete
5c90d4a2d1a8: Verifying Checksum
5c90d4a2d1a8: Download complete
927ff6ce0b84: Verifying Checksum
927ff6ce0b84: Download complete
5c90d4a2d1a8: Pull complete
233dc252507a: Pull complete
927ff6ce0b84: Pull complete
Digest: sha256:d8169162ee2318f8af83b9e14efa996c61db71790fbe36297402f1e641bf435a
Status: Downloaded newer image for abernix/meteord:base
----------------------------------------------------------------------------
```

while the setup and deploy seems to be successful:

DEBUG=\* mup  setup
  mup:module:default exec => mup setup +0ms
  mup:module:docker exec => mup docker setup +3ms

Started TaskList: Setup Docker
[xxx] - setup docker
[xxx] - setup docker: SUCCESS
  mup:module:meteor exec => mup meteor setup +793ms

Started TaskList: Setup Meteor
[xxx] - Setup Environment
  mup:module:mongo exec => mup mongo setup +2ms

Started TaskList: Setup Mongo
[xxx] - setup environment
[xxx] - Setup Environment: SUCCESS
[xxx] - setup environment: SUCCESS
[xxx] - copying mongodb.conf

DEBUG=\* mup deploy
  mup:module:default exec => mup deploy +0ms
  mup:module:meteor exec => mup meteor deploy +1ms
  mup:module:meteor exec => mup meteor push +2ms
Building App Bundle Locally

Started TaskList: Pushing Meteor
[xxx] - Pushing Meteor App Bundle to The Server
  nodemiral:sess:xxx copy file - src: /tmp/27c4812b-d3e7-4a8a-a961-097b2edd2bed/bundle.tar.gz, dest: /opt/app/tmp/bundle.tar.gz, vars: undefined +0ms
[xxx] - Pushing Meteor App Bundle to The Server: SUCCESS
[xxx] - Pushing the Startup Script
  nodemiral:sess:xxx copy file - src: /home/user/tools/nodejs/node-v4.5.0-linux-x64/lib/node_modules/mup/lib/modules/meteor/assets/templates/start.sh, dest: /opt/app/config/start.sh, vars: {"appName":"app","useLocalMongo":1,"port":3000,"logConfig":{"opts":{"max-size":"100m","max-file":10}},"image":"abernix/meteord:base"} +14s
[xxxx] - Pushing the Startup Script: SUCCESS
  mup:module:meteor exec => mup meteor envconfig +1m

**Comment by vmptk** [comment]
The mup.js file is:

module.exports = {
    servers: {
        one: {
            host: 'xxx',
            username: 'xxx',
            opts: {
                port: 22
            }
        }
    },

```
meteor: {
    name: 'app',
    appName: 'app',
    path: '/home/user//app',
    servers: {
        one: {}
    },
    buildOptions: {
        debug: true
    },
    dockerImage: 'abernix/meteord:base',
    env: {
        PORT: 3000,
        ROOT_URL: 'http://xxx',
        HTTP_FORWARDED_COUNT: 1,
        MONGO_URL: 'mongodb://localhost/app'
    },
    deployCheckWaitTime: 60
},

mongo: {
    oplog: true,
    port: 27017,
    servers: {
        one: {},
    },
},
```

};

**Comment by mgarf** [comment]
+1 having same issue

**Comment by nicklammertyn** [comment]
+1

**Comment by emilbryggare** [comment]
+1 - Same problem for me.

Tested on a fresh installation of Ubuntu 14.04.

**Comment by emilbryggare** [comment]
It works for me now. 

The problem for me was that I had "trailing commas" in my settings.json.

```
{
  "public": {
   "analyticsSettings": {
      "Google Analytics" : {"trackingId": "XXXX"},
    }
  }
}
```

changed to

```
{
  "public": {
   "analyticsSettings": {
      "Google Analytics" : {"trackingId": "XXXX"}
    }
  }
}
```

```
> mup reconfig
Started TaskList: Configuring  Meteor Environment Variables
[1.1.1.1] - Sending Environment Variables
[1.1.1.1] - Sending Environment Variables: SUCCESS
```

Hope it helps.

**Comment by vmptk** [comment]
I do not think that the issue is related with the training commas in the settings as I am not using at all the settings.json

**Comment by emilbryggare** [comment]
Hm, ok. Have you tried with a settings.json just containing {}?

**Comment by emilbryggare** [comment]
See end of https://github.com/kadirahq/meteor-up/issues/195 for more information regarding problems with missing settings.json.

**Comment by emilbryggare** [comment]
See end of https://github.com/kadirahq/meteor-up/issues/195 for more information regarding problems with missing settings.json.

**Comment by quape** [comment]
for me it was trailing comma problem as well :( parsing error information in mup reconfig / mup deploy would have saved me much time.

**Comment by zodern** [comment]
It should now display an error when it is unable to parse the settings file.
