### ISSUE TITLE
node-related error on Verifying Deployment

### ISSUE THREAD

**Issue by JanvanCasteren** [zodern/meteor-up#241]
When I try to deploy my meteor (1.4) app with meteor-up, things go wrong on the 'verifying deployment' step. (previous mup 'setup' and 'deploy' tasks ran ok).

The console output points to /bundle/bundle/programs/server/mini-files.js:108:24 as the place where things go wrong.

line 107/108 from that file:
`// The path.isAbsolute function is implemented in Node v4.
files.pathIsAbsolute = wrapPathFunction("isAbsolute");
`
That makes me think that the docker container uses a node version older than v4. Is this so? 
according to https://github.com/kadirahq/meteord/blob/master/base/scripts/lib/install_node.sh it should be at version 4. 

this is the console output:

`Started TaskList: Start Meteor
[188.226.242.134] - Start Meteor
[188.226.242.134] - Start Meteor: SUCCESS
[188.226.242.134] - Verifying Deployment
[188.226.242.134] x Verifying Deployment: FAILED

```
    -----------------------------------STDERR-----------------------------------

    npm WARN deprecated semver behavior.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
    => Starting meteor app on port:80

    assert.js:93
      throw new assert.AssertionError({
            ^
    AssertionError: "undefined" === "function"
        at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
        at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
        at Module._compile (module.js:456:26)
    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```

`

**Comment by wolganens** [comment]
I have the same problem here.
![selection_020](https://cloud.githubusercontent.com/assets/7290281/17873013/78856b52-6899-11e6-8833-393f29646c55.png)
![selection_019](https://cloud.githubusercontent.com/assets/7290281/17873012/7883e1d8-6899-11e6-8769-e0aa85231834.png)

**Comment by B-Stewart** [comment]
Same issue here.

**Comment by mikemeier** [comment]
Override the docker image, as described here (meteor.dockerImage): https://github.com/kadirahq/meteor-up/blob/628164f4035f867bd9968842ad0ca763861082e3/README.md

To `abernix/meteord:base`

**Comment by wolganens** [comment]
There are two keys for the docker image, right?
`docker: {
      image:'abernix/meteord:base'//optional
    },`
`dockerImage: 'abernix/meteord:base'`

I will set both that way and post the result.

**Comment by mikemeier** [comment]
@wolganens In de stable 1.0.2 its dockerImage. On dev-master (ah and since 3h also on new version 1.0.3) we got the new docker object with key image. Depends on what you're using.

**Comment by wolganens** [comment]
Ok, i will try with the 1.0.3 (updated now) and edit my answer here, thank you very much.

**Comment by wolganens** [comment]
It works! thank you very much!

**Comment by JanvanCasteren** [comment]
I can confirm: using abernix/meteord:base solves the problem.
My site is running now, my first meteor app. Thanks for the good work.
