### ISSUE TITLE
mup setup does nothing.

### ISSUE THREAD

**Issue by yrvlucero** [zodern/meteor-up#245]
when I execute mup setup in command line. It pauses for a few seconds and does nothing. I am using Windows.

Here is my mup.js:

```
'use strict';

module.exports = {
  servers: {
    one: {
      host: 'xxx.xxx.xxx.xxx',
      username: 'root',
      pem: '~/.ssh/id_rsa'
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'app',
    path: '../app',
    servers: {
      one: {}
    },
    env: {
      ROOT_URL: 'http://192.168.226.74/',
      //MONGO_URL: ''
    },

    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 10
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {}
    }
  }
};
```

**Comment by gantrim** [comment]
I was having the same issue. I was able to get 'mup setup' to work by providing a password for the remote server instead of the keyfile:

```
module.exports = {
  servers: {
    one: {
      host: 'xxx.xxx.xxx.xxx',
      username: 'root',
      password:"*********" <-------- this works
      //pem: '~/.ssh/id_rsa' <----- this did not work
      //.....
```

I haven't had the time to figure out why this is the case, but I'm thinking it may have something to do with the tilde in the path. I'm going to try an absolute path next and see if that fixes anything.

**Comment by MarcPer** [comment]
I had this issue as well and solved it by changing `~` (tilde) in the `pem` path to the explicit home directory `/home/my-user/`.

**Comment by gantrim** [comment]
I can confirm as well. Using an absolute path has fixed this issue for me. On OSX, I changed 

```
//...
servers: {
        one: {
           //...
            "pem": "~/.ssh/id_rsa",
            //...
        }
    },
//...
```

to:

```
//...
servers: {
        one: {
           //...
           "pem": "/Users/<MY_USER_NAME>/.ssh/id_rsa",
            //...
        }
    },
//...
```

and everything runs smoothly. Not ideal, but also a pretty simple fix.

**Comment by splex7** [comment]
+1, Yes gantrim's solution is finely works.
