### ISSUE TITLE
External Mongodb Setup

### ISSUE THREAD

**Issue by jkdowdle** [zodern/meteor-up#249]
I am having an issue where I am trying to deploy my meteor app to two different servers, and the two servers connect to the same database. At the moment neither server is connecting to my compose.io database, but rather creating their own mongodb locally. 

I would love for some one to be able to give me an example of where to put my mongo url in my mup.js file to have more than one app servers connected to an external mongo database. Here is my current mup.js file. 

```
`module.exports = {
  servers: {
    one: {
      "host": "xxx",
      "username": "xxx",
      "password": "xxx"
      // pem:
      // or leave blank for authenticate from ssh-agent
    },
    two: {
      "host": "xxx",
      "username": "xxx",
      "password": "xxx",
      // pem:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'xxx',
    path: '.',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      "ROOT_URL": "https://www.xxx.com",
      "MONGO_URL": "mongodb://xxx:xxx@aws-us-east-1-portal.19.dblayer.com:10960,aws-us-east-1-portal.20.dblayer.com:10812/admin"
    },
    "ssl": {
      "crt": "xxx", // this is a bundle of certificates
      "key": "xxx", // this is the private key of the certificate
      "port": 443 // 443 is the default value and it's the standard HTTPS port
    },

    dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 300
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: { },
      two: { }
    },
  },
};`
```

Again please give me a specific example of the where I should put the MONGO_URL to have it correct correctly. 

I would really appreciate help, thank you.

**Comment by madushan1000** [comment]
remove the mongo section in the config file.

**Comment by jkdowdle** [comment]
Thank you very much for getting back to me, I appreciate it!

**Comment by oychao** [comment]
@madushan1000 Thk you very much.

**Comment by fisherman818** [comment]
thanks @madushan1000 solved the problem!
