### ISSUE TITLE
Fails on pushing bundles

### ISSUE THREAD

**Issue by artpolikarpov** [zodern/meteor-up#251]
Newest version of mup so often fails on Pushing Meteor task :( When I was using mupx it was more stable.

It’s happening on deploys with lot of servers.

**Comment by artpolikarpov** [comment]
![screen shot 2016-08-27 at 00 24 22](https://cloud.githubusercontent.com/assets/870859/18020984/0f0f781e-6bed-11e6-9292-d6cdf9553749.png)

**Comment by artpolikarpov** [comment]
And if one of the servers fails it stops all the task. As I remember `mupx` was doing all tasks for one server, then for second and so on... I think it is more comfort scenario, because you can retry deploy without first succeeded servers.

**Comment by artpolikarpov** [comment]
When you deploy server after server — everything is fine always! But when try a few in parallell it fails.

**Comment by zodern** [comment]
This has been fixed since Mup 1.0.4.
