### ISSUE TITLE
[Feature] Deploy additional services with meteor

### ISSUE THREAD

**Issue by snajjar** [zodern/meteor-up#253]
Hello,

Since Meteor can be the entry point for quite complex applications, i suggest that meteor-up should allow the deployment of any kind of complex setup. I think this can be allowed in the following way:

Allow the config file to embed an additional `services` option:

```
services: [
  {
    name: "myservice1",
    install: "docker pull username/image",
    start: "docker run --name container username/image",
    stop: "docker stop container && docker rm container",
    uninstall: "docker rmi username/image"
  },
  {
    name: "myservice2"
    install: "docker pull username/image2 && docker create --name container2 username/image2",
    start: "docker start container2",
    stop: "docker stop container2",
    uninstall: "docker rm container2 && docker rmi username/image2"
  },
]
```

With the new docker args option, thoses service can easily be linked by the user to the meteor application. 

This isn't restricted to docker, the install/start/stop/uninstall commands could be used with quite anything. This could allow the full deployment of quite any kind of meteor application.

What do you think?

**Comment by madushan1000** [comment]
meteor up is intended for meteor deployments only, allowing other services to be deployed trough mup seems like out of scope and mostly redundant (take a look at tools like [ansible](https://www.ansible.com/) or [nodemiral](https://github.com/arunoda/nodemiral) )

**Comment by snajjar** [comment]
I understand your argument, but in my case (and in many many cases), thoses services are required for my meteor application to work. It's not a nice to have in any kind, it's REQUIRED.

Without this, I (and every developer in my case) will code an additionnal deployment program to loop through every server in the mup.js file and deploy all thoses services before i deploy meteor, and then launch meteorup. It won't make any sense to deploy the meteor app without the services, or the services without the app. Thoses are linked.

Sometime, a Meteor application is a little bit more than webserver + mongodb, and I think opening to the docker world with mup by allowing to manage other containers seemed a great idea to me (following the direction taken with the --arg option, it will allow to add easily any kind of service to our Meteor app).

I've built my own meteord:base image from abernix's: https://hub.docker.com/r/kunkka7/meteor-dood/~/dockerfile/
From this, i'm able to use dood (docker out of docker: control sibling containers from my meteor app). It's a very little change, and it's very powerful. I recommand you check this out next time you need to do something like this.

Anyway, assuming this won't be in the MeteorUp direction, is there some way to do this properly other than wrapping MeteorUp ? I was hoping that i could use the package.json's "postinstall" script or some other kind of npm features to hook my commands...

**Comment by madushan1000** [comment]
You could fork meteor up and add your required changes, Or you can write an ansible or nodemiral script wich make use of meteor up under the hood.
