### ISSUE TITLE
Requirements on Ubuntu server 

### ISSUE THREAD

**Issue by stefanve** [zodern/meteor-up#255]
I can deploy on my local machine which is a desktop with a whole lot of stuff installed since years, but not on a fresh install Ubuntu "minimal". I expect  something exist on my machine that is necessary, but I don't know what. 

On the remote machine all I get is:

x Pushing Meteor App Bundle to The Server: FAILED
        No such file

mup setup just give setup docker: SUCCESS, nothing else

So, if anyone knows what the server needs, it'd be highly appreciated

**Comment by mikemeier** [comment]
Did you try the docker image `abernix/meteord:base` ?

**Comment by stefanve** [comment]
I did. mup logs says 'No such container: app', so it seems... it seems something goes wrong :)

**Comment by xjonsson** [comment]
@stefanve Recently had a similar situation, make sure you have Docker installed on your server.

`sudo apt-get update; sudo apt-get install -y -q docker-engine`

**Comment by stefanve** [comment]
Docker got installed properly but after I, in desperation, installed ubuntu-desktop I got the deploy through. So there is something mup expects that not in the core. Now I only have problem with the SSL, using Letsencrypt

**Comment by CrackedBeefcake** [comment]
+1 for the docker problem 
and +1 for the ssl letsencrypt problem

**Comment by shadowcodex** [comment]
Let's Encrypt Autogenerate is now available and recommended. Base DO ubuntu server works fine for all of my deployments. You are free to reopen this issue if this problem still persists.
