### ISSUE TITLE
SSL with Letsencrypt fails

### ISSUE THREAD

**Issue by stefanve** [zodern/meteor-up#256]
I have tried many ways, first was to simply create the cerificates on my target server, copy them to my deploy server and include them in mup.js
mup setup fine, mup deploy fine
but on target server: 
nginx: [emerg] PEM_read_bio_X509_AUX("/bundle.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)

Now, I did not send any 'bundle.crt', my config is:

```
ssl: {
      crt: "../.certs/test/fullchain.pem",
      key:"../.certs/test/privkey.pem",
      port: 443
    },

```

So I don't know if mup has done some conversion or if nginx simply use some default values instead of... well, the values I would like it to use

**Comment by stefanve** [comment]
This branch of mupx handles everything beautifully
https://github.com/dtsepelev/meteor-up-letsencrypt/tree/meteor-1.4

**Comment by aarlaud** [comment]
I'm using let's encrypt certs. Works beautifully.
I do have a crt instead of a pem though. 
Simply did the below and it works.
cat fullchain.pem privkey.pem > bundle.crt
Thought that since it is NGINX, I'd comply with what NGINX expects.

**Comment by ibrahimzahoor** [comment]
https://blog.ibrahimzahoor.me/lets-encrypt-ssl-nginx-mup-deployment-meteor-3aea28b6dbd9#.w2xoa9s6o

**Comment by shadowcodex** [comment]
Let's Encrypt autogenerate is now available. You are free to reopen this issue if this problem still persists.
