### ISSUE TITLE
Weird deployment verification failure - without error reason

### ISSUE THREAD

**Issue by premcool** [zodern/meteor-up#262]
I'm deploying on a clean Ubuntu 14.04 box from linode. The deployment verification has been failing, although with no apparent error reason as below. Also the mup logs don't point a failure reason. 
I'm using abernix/meteord:base docker image, no luck as well.

Started TaskList: Start Meteor
[66.228.44.60] - Start Meteor
[66.228.44.60] - Start Meteor: SUCCESS
[66.228.44.60] - Verifying Deployment
**[66.228.44.60] x Verifying Deployment: FAILED**

```
-----------------------------------STDERR-----------------------------------
2.1 
| | +-- stringstream@0.0.5 
| | +-- tough-cookie@2.3.1 
| | `-- tunnel-agent@0.4.3 
| +-- rimraf@2.5.4 
| +-- tar@2.2.1 
| | `-- block-stream@0.0.9 
| `-- which@1.2.10 
|   `-- isexe@1.1.2 
+-- node-pre-gyp@0.6.29 
| +-- rc@1.1.6 
| | +-- deep-extend@0.4.1 
| | +-- ini@1.3.4 
| | +-- minimist@1.2.0 
| | `-- strip-json-comments@1.0.4 
| +-- semver@5.2.0 
| `-- tar-pack@3.1.4 
|   +-- debug@2.2.0 
|   | `-- ms@0.7.1 
|   +-- fstream-ignore@1.0.5 
|   +-- readable-stream@2.1.5 
|   | +-- buffer-shims@1.0.0 
|   | +-- core-util-is@1.0.2 
|   | +-- isarray@1.0.0 
|   | +-- process-nextick-args@1.0.7 
|   | +-- string_decoder@0.10.31 
|   | `-- util-deprecate@1.0.2 
|   `-- uid-number@0.0.6 
+-- promise@7.1.1 
+-- semver@4.1.0 
+-- source-map@0.1.32 
+-- source-map-support@0.3.2 
`-- underscore@1.5.2 

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
=> Starting meteor app on port:80
-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'
```
## From mup logs

$ mup logs --tail=50
[66.228.44.60]| | |   +-- getpass@0.1.6 
| | |   | `-- assert-plus@1.0.0 
| | |   +-- jodid25519@1.0.2 
| | |   +-- jsbn@0.1.0 
| | |`-- tweetnacl@0.13.3 
| | +-- is-typedarray@1.0.0 
| | +-- isstream@0.1.2 
| | +-- json-stringify-safe@5.0.1 
| | +-- mime-types@2.1.11 
| | | `-- mime-db@1.23.0 
| | +-- node-uuid@1.4.7 
| | +-- oauth-sign@0.8.2 
| | +-- qs@6.2.1 
| | +-- stringstream@0.0.5 
| | +-- tough-cookie@2.3.1 
| |`-- tunnel-agent@0.4.3 
| +-- rimraf@2.5.4 
| +-- tar@2.2.1 
| | `-- block-stream@0.0.9 
|`-- which@1.2.10 
|   `-- isexe@1.1.2 
+-- node-pre-gyp@0.6.29 
| +-- rc@1.1.6 
| | +-- deep-extend@0.4.1 
| | +-- ini@1.3.4 
| | +-- minimist@1.2.0 
| |`-- strip-json-comments@1.0.4 
| +-- semver@5.2.0 
| `-- tar-pack@3.1.4 
|   +-- debug@2.2.0 
|   |`-- ms@0.7.1 
|   +-- fstream-ignore@1.0.5 
|   +-- readable-stream@2.1.5 
|   | +-- buffer-shims@1.0.0 
|   | +-- core-util-is@1.0.2 
|   | +-- isarray@1.0.0 
|   | +-- process-nextick-args@1.0.7 
|   | +-- string_decoder@0.10.31 
|   | `-- util-deprecate@1.0.2 
|`-- uid-number@0.0.6 
+-- promise@7.1.1 
+-- semver@4.1.0 
+-- source-map@0.1.32 
+-- source-map-support@0.3.2 
`-- underscore@1.5.2 

=> Starting meteor app on port:80
[66.228.44.60]npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

**This is the mup.js file used, am i missing anything?**

module.exports = {
servers: {
one: {
host: 'xx.xx.xx.xx',
username: 'root',
// pem:
password: 'password'
// or leave blank for authenticate from ssh-agent
}
},

meteor: {
name: 'coolapp',
path: '/home/cool/Meteor/coolapp',
servers: {
one: {}
},
buildOptions: {
serverOnly: true,
},
env: {
PORT: '3000',
ROOT_URL: 'http://mywebsite.com',
MONGO_URL: 'mongodb://localhost/coolapp'
},

//dockerImage: 'kadirahq/meteord'
dockerImage: 'abernix/meteord:base',
deployCheckWaitTime: 60

},

mongo: {
oplog: true,
port: 27017,
servers: {
o

ne: {},
},
},
};

**Comment by premcool** [comment]
This is the mup.js file used, am i missing anything?

module.exports = {
  servers: {
    one: {
      host: 'xx.xx.xx.xx',
      username: 'root',
      // pem:
      password: 'password'
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'coolapp',
    path: '/home/cool/Meteor/coolapp',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      PORT: '3000',
      ROOT_URL: 'http://mywebsite.com',
      MONGO_URL: 'mongodb://localhost/coolapp'
    },

    //dockerImage: 'kadirahq/meteord'
    dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};

**Comment by dpeet** [comment]
Same problem here although it seems to work..

**Comment by kyle-rader** [comment]
I think the verification step is defaulting to some value - not 60 seconds.  My deploys work just fine and you can keep checking `mup log` and see the deploy finish starting up just fine.
(See #265 )

**Comment by twanc** [comment]
Can be also related to https://github.com/kadirahq/meteor-up/pull/292

**Comment by premcool** [comment]
Closing issue,I finally gave up on the meteor up deployment and went to the conventional way of meteor deployment i.e. doing the setup manually in the server and then ftp the tar.gz build file. I found this to be more easy and reliable, just had to to spend sometime with the manual steps of server setup and unix commands etc which I'm familiar with.
