### ISSUE TITLE
Specify How Many Builds to Keep?

### ISSUE THREAD

**Issue by joncursi** [zodern/meteor-up#263]
Today I ran out of disk space while deploying. I started investigating why that is. It turns out, `mup` stores an infinite history of deployments within `/opt/<appName>/current/`. I.e., if you deploy enough times, this is a valid path on your server:

```
/opt/<appName>/current/last/last/last/last/last/last/last/last/last/last/last/last/last/last/last/last/last/last
```

Is there a way to specify, say, only keep a history of the 5 previous builds? It's unnecessary to keep more than a handful, and requires a server admin to constantly log into the server to clear out the old ones.

**Comment by krishaamer** [comment]
Also had this problem. Would be great to have clean-up integrated. I know some startups have built special scripts to deal with this in Docker. But I guess the Meteor Way would be for this just to work?

**Comment by shadowcodex** [comment]
Clean up is on a milestone and tracked via this issue: https://github.com/zodern/meteor-up/issues/482
