### ISSUE TITLE
Is Mup + Meteor 1.4 + SSL working?

### ISSUE THREAD

**Issue by CrackedBeefcake** [zodern/meteor-up#264]
I have been trying to get an `SSL encrypted Meteor 1.4` app to work on DigitalOcean with `mup deploy` for about a week now. without much success. 
SSL + 1.3 works fine.
1.4 without SSL works also fine. 
Is is the problem with my code or do others have the same experience?

**Comment by stefanve** [comment]
I could not make it run, ended up using
https://github.com/dtsepelev/meteor-up-letsencrypt/tree/meteor-1.4

**Comment by CrackedBeefcake** [comment]
Works!

**Comment by eric-burel** [comment]
Same issue, nothing seems to happen when I set up SSL and my app is not available over HTTPS. I have created my certificate and key using the following command `sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ssl.key -out ssl.crt`.

**Comment by eric-burel** [comment]
Actually it does work with Meteor 1.4, I had another issue (see #287), after fixing it I managed to set up SSL on my app.

**Comment by gsabran** [comment]
Meteor 1.4.1 is working fine for me with SSL
