### ISSUE TITLE
Suggestion: Legacy support for the first mup version

### ISSUE THREAD

**Issue by rune-bk** [zodern/meteor-up#268]
Please add support for the initial mup version that ran non-docker.
Perhaps like this:
mup -v1 deploy 
mup -legacy deploy
Something like that?

I have Meteor 1.2 apps that are deployed with the old non-docker solution.
[arunoda/meteor-up](https://github.com/arunoda/meteor-up)
It was all fine when you used 2 namespaces.
mup for the old, mupx for the new with docker.
Now you have taken over the old name again. I believe this is a mistake.
I love the new features, but I feel it should have either remained in mupx, or been renamed yet again.

Currently I'm forced to fork the old and change the bin in package.json in order to use it simultaneously with the new stable mup.

It shouldn't be too much work :smile:

**Comment by aarlaud** [comment]
Hi Greblak,
Would you mind sharing how you do this currently? (like where is what exactly)
thanks !

**Comment by rune-bk** [comment]
Change all occurences of meteorhacks/meteord:base in [this](https://github.com/arunoda/meteor-up/blob/mupx/templates/linux/start.sh) file to a docker file of your choice that runs whatever node version you need.
I currently use this for meteor 1.4: [oleurud/meteor-graphicsmagick](https://hub.docker.com/r/oleurud/meteor-graphicsmagick/)
It's the right node version and includes graphicsmagick.

**Comment by aarlaud** [comment]
Thanks

**Comment by s7dhansh** [comment]
@Greblak instead of forking you can use the git code directly and create a symlink for the new mup as /usr/local/bin/mupx. Thus you don't need to maintain a repo and a simple git pull updates your mupx.
