### ISSUE TITLE
mobileSettings

### ISSUE THREAD

**Issue by lesliechw** [zodern/meteor-up#269]
Anywhere I can get more info about this build option?

`mobileSettings: {
      public: {
        'meteor-up': 'rocks',
      }`

What is does? What setting option available?

Please advice, thank you.

**Comment by shadowcodex** [comment]
Check out the readme now, and this PR: https://github.com/zodern/meteor-up/pull/317. If the issue still persist please feel free to reopen this issue.

**Comment by zodern** [comment]
For future reference: There strangely is no documentation on mobile settings in the meteor docs or guide. The only thing I have found is in their cli help where it says:

```
Set optional data for the initial value of Meteor.settings
in your mobile application. A new value for
Meteor.settings can be set later by the server as part of
hot code push.
```
