### ISSUE TITLE
module is undefined

### ISSUE THREAD

**Issue by marczzio** [zodern/meteor-up#274]
Hi, I got this error `module is undefined` when I tried to `mup setup`
do you know whats the problem is??

here is my mup.js

```
module.exports = {
  servers: {
    one: {
      host: 'localhost',
      username: 'root'
      // pem:
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'testMup',
    path: '../testMup',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true
    },
    env: {
      ROOT_URL: 'app.com',
      MONGO_URL: 'mongodb://localhost/test'
    },

    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {}
    }
  }
};
```

refering to this  post https://github.com/kadirahq/meteor-up/issues/63, I don't get any solution, I reallu don't know what happend and I don't know what to do

**Comment by twanc** [comment]
Probably you don't do it within .deploy folder. Try to move mup.js to .deploy according to documentation.

**Comment by marczzio** [comment]
Ok i'll try. thanks for reply

**Comment by neurosoup** [comment]
Hi,
I have the same issue on windows 7. Windows Script Host take precedence over nodejs ?
I've tried mup setup from within .deploy but with no success. Do you have a clue on what to do ?

**Comment by nikkiczx** [comment]
Hi, 

Anybody found a solution for this yet? I'm working on Windows 10. Thanks.

------------------------------------------------------------------------------------

Update:

Running mup.cmd setup actually works.

**Comment by Papudi** [comment]
Its strange, it used to give me this error on cmd, but when I ran the same in powershell it just worked without any changes.
