### ISSUE TITLE
How to clean up failed deploys?

### ISSUE THREAD

**Issue by anothermohit** [zodern/meteor-up#277]
After some failed deploys, initial load end up slow (`https://forums.meteor.com/t/first-visit-loads-are-ridiculously-slow/3028`). 

What is the best way to work around this to clean up the mess completely from the server?

For the time being, I created a brand new droplet and deployed there again but one of the deploys again got terminated immaturely. So, I am worried it will add on to the load time again.

**Comment by zodern** [comment]
If the build gets canceled during upload, start, configuring or during verify, there shouldn't be any extra files, and if there are they will get removed during the next deploy.
