### ISSUE TITLE
My production system failed... 

### ISSUE THREAD

**Issue by elmor34** [zodern/meteor-up#28]
My production system was working fine since 6 months, But after the last update, I get the following message, and cannot connect to server. All user accounts and right same. nothing changed.

Any idea?
Regards

on client 

> GET http://localhost:3000/sockjs/info?cb=wxlvulz3gi net::ERR_CONNECTION_REFUSED

on mup log 

> > cd: can't cd to /opt/earn
> > /proc/self/fd/9: 3: cd: can't cd to /opt/earn
> > stepping down to gid: meteoruser
> > stepping down to uid: meteoruser
> > stepping down to gid: meteoruser

**Comment by MasterJames** [comment]
First thought is if it updated to meteor 1.2 you need to set the mupx settings file to use 0.10.40 version of nodejs.
 Second thought if you used mup before an d are having problems, try the development branch mupx.

**Comment by arunoda** [comment]
Hey @elmor34 could you try using our [other repo](https://github.com/arunoda/meteor-up) to post issues. This is a currently re-factoring version.

And thanks @MasterJames

**Comment by MasterJames** [comment]
Right I'll try to watch better which repo these are in. I thought this was the other one.

**Comment by elmor34** [comment]
Thanks all...

I made a clean install and solved...
