### ISSUE TITLE
Multi-Server Deploy

### ISSUE THREAD

**Issue by guilcorp** [zodern/meteor-up#281]
Any improvement on multi server deployment? (not working at all)

I still do it one by one (working) but if someone got a solution, I'll take it.

Thanks!

**Comment by PauloMarceloNogueira** [comment]
Same problem...
Any news?

**Comment by qhello** [comment]
Same on my side, would appreciate a fix.

**Comment by clayne11** [comment]
I have a branch where I fixed the issue by deploying in series rather than in parallel.

https://github.com/clayne11/meteor-up/tree/multi-server-deployment

There must be a race condition somewhere. Not sure about the race condition but at least this fixes the issue.
