### ISSUE TITLE
Backing up Mongo

### ISSUE THREAD

**Issue by torayeff** [zodern/meteor-up#282]
I have successfully deployed my meteor application using [mup deploy](https://github.com/kadirahq/meteor-up/). As stated in documentation to access database we need to run this command:

```
docker exec -it mongodb mongo <appName>
```

How can I use mongodump command with this setup? I have tried running

```
docker exec -it mongodb mongodump --db appName --archive=baza.gz --gzip
```

Command runs successfully, but I can not find baza.gz archive

**Comment by aarlaud** [comment]
I believe the archive is in the container (not sure where. Do docker exec -it mongodb /bin/bash to get a CLI to look for it potentially)

I personally use these commands:
- docker exec -it mongodb bash -c 'mongodump -d mongodbname -o dir_in_container'

Then compress it however you want and cp the file from container to filesystem.
- docker cp mongodb:dir_in_container/mongodbname.tgz dir_in_fs/backup_name.tgz

I run it to create the file in the container and then get it out to my fs to ship it to S3.
It works for me. No clue if this is the clean/pro way to go, but I had never used docker CLI until 2 days ago....

**Comment by allenfuller** [comment]
Thanks @aarlaud! -- I'd spent the better part of the afternoon trying to get a command based off of `docker run -it --rm --link mongodb:mongo` to work, but your `docker exec` script did the trick.
