### ISSUE TITLE
SSL key and certificate created as folders when ssl config is incorrect

### ISSUE THREAD

**Issue by eric-burel** [zodern/meteor-up#287]
Hi, 
I only found a corresponding issue on `arunoda/meteor-up` [#651](https://github.com/arunoda/meteor-up/issues/651), so I open it here too as it happened to me using this version too.

I am using Meteor 1.4, and I had a mistake in my `mup.js`, as I set up 

``` js
ssl : {
certificate : "./foo.crt",
key : "./bar.crt",
...
```

instead of 

``` js
ssl : {
crt: "./foo.crt",
...
```

This mistake led to the creation of `/opt/myWonderfulApp/config/bundle.crt/` and `/opt/myWonderfulApp/config/private.key/` **folders** instead of files on the server.

After fixing my `mup.js`, `mup setup` failed with the `Copying SSL Certificate Bundle: FAILED` message, as it could not create the  `bundle.crt` and `private.key` files on server.

Deleting `/opt/myWonderfullApp` fixed it.

That's clearly tricky to debug, as there are no message when the ssl config is wrong and mup (or docker ?) creates folders instead of files in this case.

**Comment by vedovato** [comment]
Yo tip to delete the app from /opt/ saved me from wasting more than 2 already wasted weeks! Tks

**Comment by lfilho** [comment]
Same here. Not sure what caused it my case as I don't recall changing my config (apart that i didn't had SSL section at first).
Deleting my app from /opt and redeploying it fixed it. Now I'm get the 502 Bad Gateway error but that is something already reported in another issue... 😊  The quest for deploying with ssl continues...

**Comment by zeroasterisk** [comment]
yup - same here - fixed w/:

```
// on remote server
rmdir /opt/myappfolder/config/*

// on local machine
mup setup
```

ideally, if cert copy fails, it cleans up after itself automatically.

**Comment by jaredtmartin** [comment]
Same thing here, thanks for posting! Saved me hours of work!

**Comment by rogeriojs** [comment]
Thanks, very usefull!

**Comment by zodern** [comment]
In the next release it will delete the old certificate and key before uploading. The validator currently warns about many problems with the SSL config.
