### ISSUE TITLE
Erro connect MongoDB instance

### ISSUE THREAD

**Issue by PauloMarceloNogueira** [zodern/meteor-up#290]
Hello.
I launched some instance EC2 (ubuntu). With SSH, this new instance has knowledge and access my MongoDB instance (ec2).

When i run deploy with MUP, console say error (Error: failed to connect to [xx.x.x.xxx:27017]).

And now, this instance lost permission to access MongoDB instance with SSH.
This instance does not know more how connect in MongoDB instance.

Has anyone ever had problem like this? 

INFOS
mup.js
`module.exports = {
  servers: {
    one: {
      host: 'xx.xx.xxx.xx',
      username: 'username'
    }
  },

  meteor: {
    name: 'linteMup',
    path: '../',
    servers: {
      one:{}
    },

```
env: {
  PORT:80,
  ROOT_URL: 'https://stg.xxxx.co',   
  MONGO_URL: 'mongodb://xx.xx.xx:27017/dbname'
},

ssl: {
  port: 443,
  crt: './xxx.crt',
  key: './xxx.key',
},

deployCheckWaitTime: 30
```

  }` 

TNKS

**Comment by zodern** [comment]
A lot has changed in Mup over the last couple of years. If you can reopen this issue if you still have the problem.
