### ISSUE TITLE
Simple Working example of mup.js

### ISSUE THREAD

**Issue by muscaiu** [zodern/meteor-up#296]
I was able to deploy my Meteor app using **mupx**, but that only works for Meteor 1.3.5. The mupx `mup.json` file looks to me much easy to understand what it does then the examples found here.

Also always when i try a configuration and i do mup setup or mup deploy, it just opens the mup.json file in a new editor window. Is that supposed to be a warning that i messed something up?
I don't understand many of the options in the mup.js examples found here.

Can someone post a simple example of a working mup.json for a newbie with these details?
- app location is my windows 10 pc `d:/meteor/App`  
- the ip of the ubuntu server is x.x.x.x and the port is 80
- the username of the ubuntu server is `root`, password is `password`

Thank you.

**Comment by lucnat** [comment]
Hi,
Just do `mup init` and that creates a file `mup.js` that is quite similar to your familiar `mup.json`. The file that is being automatically generated _is_ that simple example that you are looking for.

**Comment by muscaiu** [comment]
Yes, that i know how to do on my own :smile:  

What i wanted is an example with **the details i gave** for the `mup.js` file: 

```
module.exports = {
  servers: {
    one: {
      host: '1.2.3.4',
      username: 'root'
      // pem:
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'app',
    path: '../app',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'app.com',
      MONGO_URL: 'mongodb://localhost/meteor'
    },

    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by muscaiu** [comment]
Anyone please? This should be easy.
I need to try mup, because mupx is not working on a clean copy of ubuntu server locally.

**Comment by rohithb** [comment]
@muscaiu try adding 

```
docker: {
      image:'abernix/meteord:base',// !important for meteor 1.4
    },
```

to `meteor` section.  This image is build using node 4.4. (Source: [kadirahq/meteor-up#172](https://github.com/kadirahq/meteor-up/issues/172)  )
My full `mup.js` file :  

```
module.exports = {
  servers: {
    one: {
      host: '1.2.3.4',
      username: 'root',
      pem: "/absolute/path/to/your/ssh/private/key",
    }
  },

  meteor: {
    name: 'app',
    path: '/absolute/path/to/your/app',
    docker: {
      image:'abernix/meteord:base',// !important for meteor 1.4
    },
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://yourapp.com',
      MONGO_URL: 'mongodb://localhost/meteor',
    },
    deployCheckWaitTime: 60 
  },

  mongo: { 
    oplog: true,
    servers: {
      one: {},
    },
  },
};
```

**Comment by muscaiu** [comment]
I have tries this and it's the same thing. 
When i do mup setup, it opens the mup.js file in a new editor window, and i don't know why it's doing that it's so annoying!! ............

```
module.exports = {
  servers: {
    one: {
      host: '192.168.0.163',
      username: 'root',
      // pem:
      password: 'pass'
      // or leave blank for authenticate from ssh-agent
    }
  },
  meteor: {
    name: 'hr',
    path: '../hr',
    docker: {
      image: 'abernix/meteord:base',// !important for meteor 1.4
    },
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://192.168.0.163',
      MONGO_URL: 'mongodb://192.168.0.163/meteor',
    },
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    servers: {
      one: {},
    },
  },
};
```

**Comment by FrancoisDeBellescize** [comment]
This is a path problem on Windows.
You have to write : "/Users/my-user/" instead of "~/"

**Comment by suyuti** [comment]
I have same problem.
I installed mup and used to generate mup files properly.
mup init works and generates 2 files in my .deploy folder.
But mup setup opens editor.

**Comment by albertonaperijr** [comment]
If you're on windows, try running `mup.cmd setup` instead of `mup setup`.

**Comment by nikonikoCW** [comment]
How to set up the port
