### ISSUE TITLE
Capturing server console in Meteor App

### ISSUE THREAD

**Issue by skywalkerlw** [zodern/meteor-up#298]
We have a meteor app deployed to DigitalOcean.
There have been times where we have had an issue, and it would be helpful to have a look at the server console. Is there any way I can do with meteor-up and how?

thanks

**Comment by lucnat** [comment]
As written in the documentation, you can do 
`mup logs -f` to get a "live-stream" of the server console
`mup logs --tail=50` to get read last 50 lines from the server console
