### ISSUE TITLE
restart after output to cli /opt/meteord/run_app.sh: line 44:   148 Killed node main.js

### ISSUE THREAD

**Issue by avishaan** [zodern/meteor-up#303]
I get the above output to the CLI and then my deployment goes into an endless loop starting with 

![image](https://cloud.githubusercontent.com/assets/5360982/18742825/0c8691bc-806b-11e6-8435-26b54a781600.png)

and ending with 

![image](https://cloud.githubusercontent.com/assets/5360982/18742835/18aebeec-806b-11e6-9ed2-f7afe980357f.png)

at which point my mup log command is exited back to bash

here is a youtube video that shows the loop happening

http://youtu.be/8xZP6Q7Udt4

**Comment by zodern** [comment]
@codeHatcher did you solve this?

**Comment by avishaan** [comment]
I created a new server and just did mup setup mup deploy and it seemed to work. Never truly figured it out but I appreciate the follow up
