### ISSUE TITLE
Separate build & upload process

### ISSUE THREAD

**Issue by mariusglauer** [zodern/meteor-up#305]
It would be really awesome to separate the build and upload processes. Sometimes my internet is not really the best and I would have to re-build the whole project just because the upload failed.

**Comment by etyp** [comment]
Working on this now. See my comment in #336 .....open to insights/ideas here, definitely need the help.

**Comment by zodern** [comment]
In version 1.2.4, you will be able to use the `--cached-build` flag to skip rebuilding.
