### ISSUE TITLE
where to put mongodb auth credentials?

### ISSUE THREAD

**Issue by Alino** [zodern/meteor-up#306]
I know there is in mup.js 
env: { MONGO_URL: '...', MONGO_OPLOG_URL: '...' }

but should we really put sensitive auth credentials into mup.js and to make it as a part of git repository? How do you people set this up?
I would expect to make env variable with credentials on the server where I want to deploy, and load that env var into this MONGO_URL string. How could this be done?

**Comment by v3rron** [comment]
@Alino you shouldn't push mup.js to your git repo.
I'm not sure if MONGO_OPLOG_URL is even used in MUP, since it's not listed in Documentation and I couldn't find anything related to this variable in the source code.

**Comment by Alino** [comment]
ok, so its recommended to not make mup.js part of the git repo.

MONGO_OPLOG_URL is maybe not used by MUP, but it is being used by meteor,
here is a list of env variables that meteor can use http://meteorpedia.com/read/Environment_Variables

**Comment by clayne11** [comment]
Personally, I have a separate Git repo that I only use for deployment. I include my main Meteor project as a submodule and I commit all of my sensitive deployment variables into the separate Git repo that only the dev ops / deployment teams have access to.
