### ISSUE TITLE
Error:  All configured authentication methods failed

### ISSUE THREAD

**Issue by s7dhansh** [zodern/meteor-up#309]
This is happening with all my 3 setups on DigitalOcean (I haven't tried any other server yet) since yesterday. The deploys that were working a couple of days ago are failing now.
I have one old mup (non-docker) that is working on one of the servers though.

I am using ssh-agent and can directly ssh into the machines.

How can I debug what commands are being run to make the connection?
`DEBUG=* mup ..` does not give enough info

**Comment by s7dhansh** [comment]
Found out the issue. It seems somehow my identity was removed from the ssh-agent. Had to add it again.
`ssh-add /path/to/private_rsa`

**Comment by sibeduli** [comment]
how tf you even change that without accessing the console? im really confused

**Comment by Piyush-Use-Personal** [comment]
> how tf you even change that without accessing the console? im really confused

You can click reset password then you will get a recovery link in email login using that link in recovery console
