### ISSUE TITLE
Error reading config file: Permission denied

### ISSUE THREAD

**Issue by bompi88** [zodern/meteor-up#31]
I'm getting this error in the mongo logs, when setting up mongo container on a VM provided by my university:

``` bash
Error reading config file: Permission denied
```

This is not happening elsewhere. If I run the following to create a container it works perfectly:

``` bash
sudo docker run \
  -d \
  --restart=always \
  --publish=127.0.0.1:27017:27017 \
  --volume=/var/lib/mongodb:/data/db \
  --name=mongodb \
  mongo mongod
```

Will `mup` add an option to provide custom config file to mongo in the future? If not, isn't the config file redundant? Mongo `dbpath` is `/data/db` as default, and the config file is not needed as is.

If the config file is necessary somehow, I'll close this issue. My problem is probably a result of how my university sets up their VMs.

**Comment by madushan1000** [comment]
We are hoping to add some mongo config options like oplog and replicaset name. That's why the config file is still there. I'll try to reporduce the other issue.

**Comment by bompi88** [comment]
@madushan1000 I expected you would use it for doing something like that. If I `chown` the config file before running the container, it seems to be working. Setting the owner to be the mongo user/group  `999` in the `mongo-start.sh`:

``` bash
# make sure mongo can access config file
sudo chown 999:999 /opt/mongodb/mongodb.conf
```
