### ISSUE TITLE
Error on deploy: 'No such file'

### ISSUE THREAD

**Issue by Obiwarn** [zodern/meteor-up#310]
Just upgraded from mupx (where everything worked fine).

I wish there would be more verbose error messages.

This is what I get on deploy:

```
DEBUG=* mup deploy
  mup:module:default exec => mup deploy +0ms
  mup:module:meteor exec => mup meteor deploy +0ms
  mup:module:meteor exec => mup meteor push +9ms
Building App Bundle Locally

Started TaskList: Pushing Meteor
[138.68.154.57] - Pushing Meteor App Bundle to The Server
  nodemiral:sess:138.68.154.57 copy file - src: /tmp/98c8b086-9d0a-44ee-b05a-08a981cf7ad5/bundle.tar.gz, dest: /opt/hoardAdminProduction/tmp/bundle.tar.gz, vars: undefined +0ms
[138.68.154.57] x Pushing Meteor App Bundle to The Server: FAILED
        No such file
```

My mup.js:

```
module.exports = {
  servers: {
    one: {
      host: '138.68.154.57',
      username: 'root',
      pem: '../keys/server/id_rsa'
    }
  },

  meteor: {
    name: 'hoardAdminProduction',
    path: '../../',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'https://admin.hoardspot.com',
      MONGO_URL: 'mongodb://admin:XXX',
      MONGO_OPLOG_URL: "mongodb://admin:XXX"
    },
    ssl: {
      certificate: "../keys/ssl/bundle.crt", // this is a bundle of certificates
      key: "../keys/ssl/wildcard.key", // this is the private key of the certificate
      port: 443 // 443 is the default value and it's the standard HTTPS port
    },
    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 180
  },
};
```

**Comment by nadeemja** [comment]
Same here. @arunoda, please advise. :)

**Comment by magp3** [comment]
@obiwarn Does your directory /opt/hoardAdminProduction exist?

**Comment by Obiwarn** [comment]
I switched to Galaxy. 

But isn't that mups job to create this folder on the server?

**Comment by madushan1000** [comment]
Did you run `mup setup`?

**Comment by Obiwarn** [comment]
yes

##

**Comment by magp3** [comment]
@obiwarn Did you change the app name after running mup setup? I encountered this issue when I did that..

**Comment by Obiwarn** [comment]
yes.

from hoard-bla-bla to hoardBlaBla.

However I reinstalled my server Droplet before the change. So the second
mup setup ran on a new droplet.

**Comment by lfilho** [comment]
Had the same problem. My app name had a space on it.
Removing the space and then `mup setup && mup deploy` fixed it.

**Comment by masca88** [comment]
After hours of changing special characters and other things from configuration file I've discovered that in the ssl section, the "certificate" key is now changed to "crt".  Alleluja!

I think that it's also your problem @obiwarn

**Comment by zodern** [comment]
> My app name had a space on it.
Removing the space and then mup setup && mup deploy fixed it.

> the "certificate" key is now changed to "crt"

Mup 1.2 will validate the mup.js. Two of the things it checks for are spaces in the app name, and unknown properties in the config.

**Comment by frankFree** [comment]
first step: mup setup
then: muo deoloy
perfect fix it
