### ISSUE TITLE
Per server env configuration

### ISSUE THREAD

**Issue by clayne11** [zodern/meteor-up#313]
We need to be able to set an environment configuration per server. This is necessary for `cluster`. The old `mupx` set the `CLUSTER_ENDPOINT_URL` automatically however this is no longer happening and so we need per server environment configuration.

**Comment by elie222** [comment]
I agree. There's a PR for this here:
https://github.com/kadirahq/meteor-up/pull/248

**Comment by jamesgibson14** [comment]
1+

**Comment by zodern** [comment]
Duplicate of #244
