### ISSUE TITLE
Using certbot

### ISSUE THREAD

**Issue by mattlinares** [zodern/meteor-up#315]
Has anyone got a straightforward set of instructions for using https://certbot.eff.org with meteor-up SSL?

**Comment by mattlinares** [comment]
I found this:

https://github.com/arunoda/meteor-up/wiki/Setting-up-SSL-with-LetsEncrypt-and-MeteorUp

**Comment by lfilho** [comment]
@mattlinares I just tried this and didn't work... After doing everything I tried my live https URL in the browser but it redirected to `https://localhost/` which of course is wrong.

Any clues?

**Comment by jimmytidey** [comment]
Hey - Fancy seeing you here @mattlinares! 

The Arundoa guide is for an old version on MUP. It's confusing. 

For the new version, use the files you got from running letsencrypt on your server as follows (you don't need to do the combining files step any more).  

```
meteor: {
    ssl: {
      crt: 'fullchain.pem', // this is a bundle of certificates
      key: 'privkey.pem', // this is the private key of the certificate
      port: 443 // 443 is the default value and it's the standard HTTPS port
    },
   ....
}
```

**Comment by mandreko** [comment]
Wouldn't this require me to re-push new certs every 3 months or so when they expire? Is there no way to automate it, so it re-runs on a cron task?

**Comment by zodern** [comment]
Meteor Up now has Let's Encrypt support with auto-renewal.
