### ISSUE TITLE
where is mongodb located on docker container?

### ISSUE THREAD

**Issue by sdabdoub** [zodern/meteor-up#322]
I previously had a working mup project (it died unexpectedly on Sunday), I was able to create a dump of the mongodb within the docker container. 
Sadly, the container is restarting indefinitely , but I do have an export of the container.
Where/How could I locate the database/dump file for my previously deployed project.

**Comment by zodern** [comment]
@sdabdoub did you find the export?

**Comment by sdabdoub** [comment]
Yeah you can close this. I don't recall completely but it was hiding in plain sight
