### ISSUE TITLE
mup opens mup.js in a new editor window

### ISSUE THREAD

**Issue by muscaiu** [zodern/meteor-up#323]
If i do `mup setup` or `mup deploy` or just `mup blabla` it just opens the mup file in a new editor window.
Is this normal? Did my mup not installed correctly?

I want to mention that with the old **mupx**  i managed to deploy my app on meteor 1.3.5, but with this **mup** i can't get pass this issue.
What am i doing wrong??

**Comment by catin-black** [comment]
+1

**Comment by pxwee5** [comment]
+1 Anyone got any idea why its calling the default text editor when invoked mup setup ?

I also tried it on git bash but nothing happened.

**Comment by pikausp** [comment]
I had the same issue. For me the workaround was to run mup from parent directory and provide path for mup.js & settings file via parameters

**Comment by gaillota** [comment]
@pikaupet What are the flags to provide the path as you said ?

**Comment by muscaiu** [comment]
How did you do that? Please give an example.

**Comment by pikausp** [comment]
`mup --config .deploy/mup.js --settings .deploy/settings.json deploy`

**Comment by gaillota** [comment]
According to the documentation, it's more like `mup deploy --config=.deploy/mup.js --settings=.deploy/settings.json`

**Comment by pikausp** [comment]
I copy pasted my deploy bat..

**Comment by muscaiu** [comment]
I tried and it it sais `mup.js file not found. Run 'mup init' first.`
Note that i have a deploy folder under root and i have run mup init in it.

I don't think it's going in the deploy folder, because if i do mup init in root folder and i do your commands it opens mup.js in a new editor window like before. 
Any ideas?

**Comment by albertonaperijr** [comment]
Try `mup deploy --config=deploy/mup.js --settings=settings.json`.

**Comment by muscaiu** [comment]
Same thing as the title of the issue sais ..for 2 months :(

I don't know if i mentioned that i'm on Windows 10.

![2016-12-09_11h25_29](https://cloud.githubusercontent.com/assets/11426309/21044058/aba697a4-be02-11e6-964a-8240ceda1e3d.gif)

**Comment by gaillota** [comment]
Can you please show us your project structure ?

**Comment by pikausp** [comment]
With the following structure
ProjectRoot
ProjectRoot/.deploy
ProjectRoot/.deploy/mup.js
ProjectRoot/.deploy/settings.json

You'd execute the the following command when you are in ProjectRoot

`mup --config .deploy/mup.js --settings .deploy/settings.json deploy`

**Comment by muscaiu** [comment]
Yes i have that structure and i did execute all commands posted here.

![2016-12-09_11h47_05](https://cloud.githubusercontent.com/assets/11426309/21044663/cba5c4a0-be05-11e6-9bc2-c1ab0db68acb.png)

**Comment by albertonaperijr** [comment]
Ah, I see. I think you need to put `deploy` after `mup` and not in the end.
E.g. `mup deploy --config=.deploy/mup.js --settings=settings.json`

**Comment by pikausp** [comment]
@muscaiu Your folder name is `deploy`, but you are using `.deploy` in the command

**Comment by albertonaperijr** [comment]
I think you need to remove the `app` in your `meteor path`. Change `path: '../app'` to `path: '../'`.

**E.g.**

```
meteor: {
    name: 'app',
    path: '../', // mup doesn't support '~' alias for home directory
    ...
```

**Comment by muscaiu** [comment]
@albertonaperijr same thing happens.

@pikaupet tried without the `.` `mup deploy --config=deploy/mup.js --settings=settings.json` same thing

**Comment by muscaiu** [comment]
If i do `mup banana` same thing happens. So no matter what i try after `mup` it is useless.

**Comment by albertonaperijr** [comment]
@muscaiu Try to do my latest [comment](https://github.com/kadirahq/meteor-up/issues/323#issuecomment-265976270) then run `mup deploy --config=.deploy/mup.js --settings=.deploy/settings.json`

**Comment by gaillota** [comment]
Is your application located in the `mydeploy` folder ? Otherwise, it might be because the `mup.js` doesn't point to your app folder and mup can't find the app...

**Comment by muscaiu** [comment]
@albertonaperijr i also did `npm install -g mup`. Same thing. It's starting to make me sick to my stomach.
@gaillota 
- my app is in D:\Meteor\mydeploy
- my deploy folder is in D:\Meteor\mydeploy\deploy
I tried also with other projects same thing always.

**Comment by gaillota** [comment]
Try to add `./` in front of the path, from your `mydeploy` folder, like so:
```
mup deploy --config ./deploy/mup.js --settings ./deploy/settings.js
```

**Comment by albertonaperijr** [comment]
@muscaiu Did you try changing `path: '../app'` to `path: '../'`.
I just noticed that your `mup.js` file is inside `deploy` folder so you have to run `mup deploy --config=deploy/mup.js --settings=deploy/settings.json` instead of `mup deploy --config=.deploy/mup.js --settings=.deploy/settings.json`

**Comment by muscaiu** [comment]
Oh crap, i forgot i did a mup init in the root folder and that was why it kept doing so. Now it seems to start giving error like the mup.js is not configured right, because it isn't.

`mup deploy --config=deploy/mup.js --settings=.deploy/settings.json`
```
Building App Bundle Locally
{ cwd: 'D:\\Meteor\\mydeploy\\app' }
{ [Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn C:\\WINDOWS\\system32\\cmd.exe',
  path: 'C:\\WINDOWS\\system32\\cmd.exe',
  spawnargs:
   [ '/c',
     'meteor',
     'build',
     '--directory',
     'D:\\tmp\\16719968-3292-4105-848e-af50736ceebd',
     '--architecture',
     'os.linux.x86_64',
     '--server',
     'http://localhost:3000',
     '--server-only' ] }

=> Build Error. Check the logs printed above.
```

So guys 1 more thing i need to ask. 
I have an VMWare Ubuntu server running locally on 192.168.0.185, username: root pass: passwd

Now that you know my folder structure, can you please post an example mup.js file that could work for me?

**Comment by muscaiu** [comment]
I tried with this mup.js file:
```
module.exports = {
  servers: {
    one: {
      host: '192.168.0.185',
      username: 'root',
      password: 'passwd'
    }
  },

  meteor: {
    name: 'deployapp',
    path: '..',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://192.168.0.185',
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```
`mup deploy --config=deploy/mup.js --settings=.deploy/settings.json`
```
Building App Bundle Locally

Started TaskList: Pushing Meteor
[192.168.0.185] - Pushing Meteor App Bundle to The Server
[192.168.0.185] x Pushing Meteor App Bundle to The Server: FAILED
        No such file
```

**Comment by gaillota** [comment]
Try changing the `path` to `'../'`

**Comment by albertonaperijr** [comment]
Just like @gaillota's comment, try changing `path` to `../` but also change `.deploy` to `deploy`.
**E.g.** `mup deploy --config=deploy/mup.js --settings=deploy/settings.json`

**Comment by muscaiu** [comment]
I installed a fresh copy of ubuntu server and changed ip to 192.168.0.158.
Before i try to deploy, do i need to install things like node, mongo, docker on the ubuntu server?

Right now it's saying:
`mup deploy --config=deploy/mup.js --settings=deploy/settings.json`
```
module.exports = {
  servers: {
    one: {
      host: '192.168.0.158',
      username: 'root',
      password: 'passwd'
    }
  },

  meteor: {
    name: 'deployapp',
    path: '../',
    servers: {
      one: {}
    },
    buildOptions: {
      //serverOnly: true,
    },
    env: {
      PORT: 80,
      ROOT_URL: 'http://192.168.0.158',
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    docker: {
      //image: 'kadirahq/meteord', // (optional)
      //image: 'abernix/meteord:base', // use this image if using Meteor 1.4+
    },

    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```
```
Building App Bundle Locally

Started TaskList: Pushing Meteor
[192.168.0.158] - Pushing Meteor App Bundle to The Server
Error connect ECONNREFUSED 192.168.0.158:22
```

**Comment by muscaiu** [comment]
By the way my `settings.json` file is 
```
{
  "public": {

  }
}
```
I tried `mup setup --config=deploy/mup.js --settings=.deploy/settings.json`
```
Started TaskList: Setup Docker
[192.168.0.158] - setup docker
Error connect ECONNREFUSED 192.168.0.158:22
```

**Comment by muscaiu** [comment]
I managed to get pass a zillion errors, and got stuck here:

![2016-12-09_13h55_50](https://cloud.githubusercontent.com/assets/11426309/21048353/86a4b9f8-be17-11e6-9a39-9f95f75a16a2.png)

```
[192.168.0.158] x start mongo: FAILED

        -----------------------------------STDERR-----------------------------------
        docker: Error response from daemon: driver failed programming external connectivity on endpoint mongodb (ddbe5537d4ea7423f9ea2f93a8efdad89be67fdcd3e1e73ecb546def9c6b9be7): Error starting userland proxy: listen tcp 127.0.0.1:27017: bind: address already in use.
        -----------------------------------STDOUT-----------------------------------
        latest: Pulling from library/mongo
        Digest: sha256:d929ffc5d0871712198be82c475397e5e9c71f3d2a9fa4b304f623ad09ad204b
        Status: Image is up to date for mongo:latest
        mongodb
        b26737b3472888334c621ae3172c140b0e769fd77c93525efd24776e71debd6c
        ----------------------------------------------------------------------------
```

Any Ideas?

**Comment by muscaiu** [comment]
I fixed this by installing meteor on Ubuntu server.
Next error i fixed by adding this:
```
    docker: {
      image: 'abernix/meteord:base', // use this image if using Meteor 1.4+
    },
```

**ALL SUCCESS!** 
Thank you all!

**Comment by gaillota** [comment]
FYI, Meteor Up uses dockers images, one for **mongo** and one for **meteor** (containing node and stuff), and it previously check if docker is installed on your machine.

You don't have to do anything before deploying.
