### ISSUE TITLE
How to use a custom domain

### ISSUE THREAD

**Issue by kalepail** [zodern/meteor-up#327]
I'm new to Docker so I don't know exactly how to set this up.
My app is working fine on my droplet IP but I'd like a way to forward the IP to the domain name so that when I visit `xxx.xxx.xxx.xxx` it will redirect to `example.com`. Is there a way to achieve this through the `mup.js` file?

**Comment by lunatolun** [comment]
You need to

1: Configure name servers and point your domain to digital ocean (I'm assuming you are using digital ocean since you said droplet)
2: Configure your droplet (Networking > Add domain then configure it's settings)
3: Configure it in MUP

```
env: {
      ROOT_URL: 'http://yourdomain.com', //this can be https also
      PORT: 80
}
```

**Comment by zodern** [comment]
@tyvdh did you solve this?

**Comment by kalepail** [comment]
Yeah all good.

**Comment by birganovrus** [comment]
@tyvdh Hi! Can you please post your nginx conf? I got some annoying situation when I only have an access to my meteor app using "mydomain.com:3000". When I open "mydomain.com" I see nginx welcome page

Thanks
