### ISSUE TITLE
Hot code push

### ISSUE THREAD

**Issue by timothyarmes** [zodern/meteor-up#33]
I'm curious about mup and hot-code-push.

Since mup reply creates a new Docker container rather than copying the code over the previous version, that suggests to me that there's no support for hot code push. 

Moreover, it also suggests that all connected users get disconnected when a new version is deployed.

Is this this case? If not, how??

**Comment by mnmtanish** [comment]
Hi @timothyarmes,

As far as I know, the way the meteor application is deployed shouldn't affect hot code push. Meteor uses a couple of hashes to detect version changes. For an example check the `__meteor_runtime_config__` global variable on some meteor app.

![screen shot 2016-01-22 at 1 49 29 pm](https://cloud.githubusercontent.com/assets/136691/12505683/1e83f5c4-c10f-11e5-8605-fabf2619871d.png)

When these versions change, meteor will try to update the client or it will do a hot-code-push.

@arunoda can you verify this?

**Comment by timothyarmes** [comment]
Surely if an entirely new container is starting up then it won't know anything about the previously connected users. When the client try to start talking to the new container how does meteor know that they were previously connected? What does it do about merge box?

**Comment by mnmtanish** [comment]
When a client re-connects to a meteor server, it simply starts a new session. The `DDP` protocol does support resuming sessions but Meteor has not implemented it yet. [source-code](https://github.com/meteor/meteor/blob/5b4e1c6d39f846198ea3fc987bbca6c1a5293131/packages/ddp-server/livedata_server.js#L1420)

**Comment by timothyarmes** [comment]
OK. So what happens after a redeploy: does the user see a hot code push or a reload?

**Comment by mnmtanish** [comment]
It will try to do a host code push without a reload (example: css only changes). If it can't do that, it will do a hot code push with a reload.

**Comment by markoshust** [comment]
In my experience, deploying a new instance with Docker disconnects connected users. You'll receive multiple disconnect notices. When the new instance deploys, the client will reconnect. It's not a fatal solution, but it's not ideal.

I believe the only way to get around this is to have a load balancer within mup that has support for sticky sessions. When a new Docker instance is deployed, it is confirmed as up and the load balancer switches to that new Docker instance. After all traffic is re-routed, the old Docker container is removed.

**Comment by timothyarmes** [comment]
Anyone know what Galaxy does?

**Comment by MasterJames** [comment]
If you push a new file into the deployment later in some other way with a ssh cp for instance, then the server will hotcode push as expected. The deployment box is separated. Once it's up via mupx do as you will. Certainly you can code sticky Sessions or what have you as deemed necessary by the app and already suggested techniques for cluster rolling updates. You could build a no new session way of showing preference to a session centric design over release update session restarts. Meaning a cluster node could wait to redeploy after all sessions have been rerouted or timed/logged out. This tool should not be cluttered (PRs welcome?).
It's a deployment server you realistically don't want to hot push to that do you? 
Anyway my unofficial opinion is I'm 99% sure that's not a current or future feature for mup to address. 
What you want is some file watch to scp secure copy 3rd party solution, that mup could in theory add on.
