### ISSUE TITLE
Failing: SSL + Multiple Apps + Different domains + Single VPS & IP

### ISSUE THREAD

**Issue by ghost** [zodern/meteor-up#330]
I followed this:

> SSL Support
> Meteor Up can enable SSL support for your app. It uses the latest version of Nginx for that.
> To do that, just add following configuration to your mup.js file.
> 
> ```
> meteor: {
>   ...
>   ssl: {
>     crt: './bundle.crt', // this is a bundle of certificates
>     key: './private.key', // this is the private key of the certificate
>     port: 443 // 443 is the default value and it's the standard HTTPS port
>   }
>   ...
> }
> ```
> 
> Now simply do mup setup and then mup deploy. Your app is now running with a modern SSL setup.
> If your certificate and key are already in the right location on your server and you would like to prevent Mup from overriding them while still needing an SSL setup, you can add upload: false to mup.js in the meteor.ssl object.
> To learn more about the SSL setup, refer to the [mup-frontend-server](https://github.com/meteorhacks/mup-frontend-server) project.

I was not able to learn more about my type of setup from the mup-frontend-server link.

These are the settings I am using in mup.js:
App1:

```
  ...
  env: {
    PORT: 3000,
    UPSTART_UID: 'meteoruser',
    ROOT_URL: 'https://www.domain.com',
    MONGO_URL: 'mongodb://localhost/meteor'
  },
  ssl: {
    crt: './fullchain.pem',
    key: './privkey.pem',
    port: 443
  }
  ...
```

App2: 

```
  ...
  env: {
    PORT: 3002,
    UPSTART_UID: 'meteoruser',
    ROOT_URL: 'https://www.adifferentdomain.com',
    MONGO_URL: 'mongodb://localhost/meteor'
  },
  ssl: {
    crt: './fullchain2.pem',
    key: './privkey2.pem',
    port: 443
  }
  ...
```

For testing: Nginx is listening on port 80 only without returning 301 to https. To test SSL: I type in https:// in front of the domain in the browser address bar.

Result:
- App1 SSL work perfectly
- App2 gives the following error: 

> ```
>     x Start Meteor: FAILED
>     -----------------------------------STDERR-----------------------------------
>     Error response from daemon: No such container: App2
>     Error response from daemon: No such container: App2-frontend
>     docker: Error response from daemon: driver failed programming external connectivity on endpoint App2-frontend (...a bunch of random numbers...): Bind for 0.0.0.0:443 failed: port is already allocated.
>     -----------------------------------STDOUT-----------------------------------
> 
>     base: Pulling from abernix/meteord
> ```

Deployment is a success (ONLY ON App1) when I use a non-standard SSL port (such as 4433), but when I go to https://www.adifferentdomain.com it loads App1 and https is red/not private in the browser address bar. I know the the cert is correct as I can use https://www.adifferentdomain.com:4433 and it works. This result is undesirable.

Is this carried over from the original mup? https://github.com/arunoda/meteor-up/issues/653 If so should I use the idea from sferoze commented on Apr 12 and have my main Nginx configuration files handle all the SSL?

**Comment by ghost** [comment]
I decided to use nginx configuration file SSL support before the request reaches the (docker/nginx/meteor-app) that mup deploys. Hopefully this doesn't create adverse behavior in other areas of the app later on.

**Comment by zodern** [comment]
Were both apps on the same server?
