### ISSUE TITLE
Deployement fails with no good log

### ISSUE THREAD

**Issue by gsabran** [zodern/meteor-up#331]
My deployement is failing with: 

```
>>  => Starting meteor app on port:80
>>  
>>  /bundle/bundle/programs/server/node_modules/fibers/future.js:313
>>                          throw(ex);
>>                          ^
>>  [object Object]
>>   
>>  => Redeploying previous version of the app
```

I've no clue what's happening since all the info seems to be hidden in `[object Object]`. I'm using the image:

```
docker: {
  image: 'abernix/meteord:base',
},
```

that was recommended for meteor 1.4

**Comment by marquesgabriel** [comment]
Hello, did you try the command `mup logs --tail=50`?

**Comment by gsabran** [comment]
yes, I get the same output, just a bit more context that's useless for me. I've been trying to change `fibers/future.js` to get better logs, but I guess it's useless since it's gonna use the code from `abernix`'s container.

**Comment by zodern** [comment]
@gsabran did you find a solution?

**Comment by gsabran** [comment]
Yes if I remember correctly. I had an issue with my db connection and the mongo node driver had an issue reporting the error: https://jira.mongodb.org/browse/NODE-838 so I was getting shitty logs. This has been fixed now: https://github.com/christkv/mongodb-core/commit/aaaa4e45f75e24a5b0cfd8b101e1851c0672a3b9 and I think Meteor included the fix by upgrading the mongo version it's using (even though I'm not 100% sure)
