### ISSUE TITLE
[SOLVED] Deploying not working

### ISSUE THREAD

**Issue by bilinkis** [zodern/meteor-up#333]
Hello guys, i'm having trouble deploying with meteor-up.
Whenever I try to deploy, the terminal says `Building App Bundle Locally` and after several minutes I get this error: `/home/nicolas/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-16991xn/plugin.compileCoffeescript.os/program.json'
    at Error (native)

=> Build Error. Check the logs printed above.`
Do you have any kind of solution?

**Comment by marquesgabriel** [comment]
Hi
Try to add `docker:{ image: 'abernix/meteord:base'},` on your mup.js file inside meteor definitions

**Comment by msj121** [comment]
I have a similar error; however, @marquesgabriel this idea didn't help me. I have also tried to update via `sudo npm update mup -g` and I still get the update message below... I am also running at `Meteor 1.4.1.2`

```
(node:69980) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
update 1.0.0 => 1.0.4
Building App Bundle Locally
/Users/msj/.meteor/packages/meteor-tool/.1.4.1_2.fpzmec++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/tmp/mt-koh548/os.json'
    at Error (native)

=> Build Error. Check the logs printed above.
(node:69980) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: build-error
```

**Comment by bilinkis** [comment]
@marquesgabriel Thanks for your answer, but it didn't help me though. Already have that image in my mup file.

**Comment by marquesgabriel** [comment]
I had this problem and having the image in the mup file solved the problem. Sorry for not helping as expected @bilinkis and @msj121

**Comment by bilinkis** [comment]
@marquesgabriel don't worry, thanks for your answer

**Comment by msj121** [comment]
I removed mup and  re-installed, still getting this issue.

I am running OSx and it looks like @bilinkis is running linux... I am not sure what the culprit is.

**Comment by bilinkis** [comment]
@msj121 yes, i am indeed using Ubuntu 16.04. I had to use a different workspace and was able to deploy.

**Comment by msj121** [comment]
@bilinkis I am not too familiar with Ubuntu, what do you mean by a new workspace? On the client computer? I am just trying to find a solution, do you think it meant deleting all node_modules or something?

**Comment by msj121** [comment]
```
export METEOR_WAREHOUSE_URLBASE=https://d3fm2vapipm3k9.cloudfront.net
```

This helped me

**Comment by bilinkis** [comment]
@msj121 thanks bro! that seems to solve the issue!

**Comment by bilinkis** [comment]
I actually use Cloud9, so I just created a new workspace. Hope that solves
your issue
