### ISSUE TITLE
Deployment Failuire

### ISSUE THREAD

**Issue by gitMonks** [zodern/meteor-up#334]
My deployment fails with the following error:

[XXX.XX.XX.XX] x Verifying Deployment: FAILED

```
-----------------------------------STDERR-----------------------------------
package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
=> Starting meteor app on port:80

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------
```

Its my first ever deployment. Please, be little bit more descriptive than you would normally be. Thanks

**Comment by ghost** [comment]
Assuming you have a vps: ssh into your server and do as the STDOUT says. Type the command: mup logs --tail=50 . Read each line of the output to pinpoint the issue. My hunch is that you will find something in your mup.js is not supported.

**Comment by gitMonks** [comment]
@sgatlf Thanks for your suggestion. I have updated npm package to the latest 3.10.8 but still no luck Here is the mup logs:

![image](https://cloud.githubusercontent.com/assets/18562694/19568036/e7d86348-96e7-11e6-9833-c475c7e92818.png)

Thanking again for your time and help

**Comment by gitMonks** [comment]
I have managed to get rid of the error by using  a docker image  suggeste by abernix kadirahq/mup here: https://github.com/meteor/meteor/issues/7475. Even though my app is successfully deployed and verified now but it's still not live and shows nginx welcome page.

**Comment by ghost** [comment]
Do you have nginx setup on the server to direct request, before mup setup?

**Comment by Deadlyweed** [comment]
cd yourapp
meteor
xxx.xx.xxx.xx:3000. Now if it show up that way. You miss up some where like i did but i gave up on using nginx. I had my nginx set up first tho. Hope that help you out a little.

**Comment by gitMonks** [comment]
@sgatlf Yes I am hosting on digitalocean (Ubunut & nginx). I followed this https://gist.github.com/jamiewilson/4e1d28f9a200cb34ad59 tutorial to the word and I was running into the Verfication failure error and I solved it with the solution I mentioned in my previous comment. 

@Deadlyweed Yeah you are right it works by following the http://url.co.uk:3000. How did you fix this?

Thanks a lot to both of you for your time. I hope one day I will be able give something back to this community.

**Comment by ghost** [comment]
Instead of site-enabled I use `/sites-available` per http://julian.io/how-do-i-host-multiple-meteor-apps-on-one-digitalocean-droplet/
Although, since you are editing the file directly I would think it should still work. But I like the symlink way in case I need to take the address down for any unknown reason.
Otherwise do some double checks:
Use command `sudo nano /etc/nginx/sites-enabled/yourappname.com.conf`

Verify :3000 port is specified in `proxy_pass http://yourappname.com:3000;`

Ensure that updates were made by using command `sudo services nginx reload`

In mup.js verify 3000 port is specified under the `env` object `PORT: 3000,`

If this doesn't work post your mup.js and your nginx yourappname.com.conf file with personal information redacted so that I or someone else can help you troubleshoot further.

**Comment by gitMonks** [comment]
@sgatlf Here are the contents of myapp.com.conf & mup.js

**myapp.com.conf**

server {
    listen 80;
    server_name myapp.co.uk;
    access_log /var/log/nginx/app.dev.access.log;
    error_log /var/log/nginx/app.dev.error.log;
        location / {
            proxy_pass http://XXX.XX.XXX.XX:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header X-Forwarded-For $remote_addr;
        }

}

**mup.js**

module.exports = {
  servers: {
    one: {
      host: 'XXX.XX.XXX.XX',
      username: 'USERNAME',
      pem: '/Users/gitMonk/.ssh/id_rsa'
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'myApp',
    path: '/Users/gitMonk/Desktop/projects/myApp',
    dockerImage: 'abernix/meteord:base',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://myapp.co.uk',
      PORT: 3000,
      MONGO_URL: 'mongodb://localhost/meteor'
    },

```
//dockerImage: 'kadirahq/meteord'
deployCheckWaitTime: 600
```

  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};

I am able to reload nginx with`sudo nginx -s reload` doesn't recognise sudo services nginx reload.

Problem still persists.

**Comment by Deadlyweed** [comment]
@gitMonks I never got it to work right. 
This might help you both out. The tutorials i used for nginx
they use the todos app in the tutorial from meteor web site
https://www.digitalocean.com/community/tutorials/how-to-deploy-a-meteor-js-application-on-ubuntu-14-04-with-nginx

don't do this part on it tho. It screw me up big time the sec time trying it on new a droplet 
add-apt-repository ppa:chris-lea/node.js

**Comment by ghost** [comment]
Try in conf file:
`proxy_pass http://127.0.0.1:3000;`

Also, in mup.js file try changing server information to:

```
servers: {
      one: {
        host: 'xxx.xx.xxx.xx',
        username: 'yourusername'
      },
},
```

And env information to:

```
env: {
  PORT: 3000,
  UPSTART_UID: 'meteoruser',
  ROOT_URL: 'http://myapp.co.uk',
  MONGO_URL: 'mongodb://localhost/meteor'
},
```

Just an observation not related to the issue, do you mean to have 600 deployCheckWaitTime or did you mean 60 ?

**Comment by gitMonks** [comment]
People suggested in some forums that they were able to resolve the Verification failure by increasing the deployCheckWaitTime to 80. I was so frustrated that I made it 600. Now that should give you an idea how much I am appreciating your help. :))

**Comment by gitMonks** [comment]
@sgatlf Sorry no luck even with these settings. By the way proxy_pass was already http://xxx.xx.xxx.xx:3000. Did you literally mean http://127.0.0.1:3000

I opened a support ticket with digitalocean and they have come back with the following message:

> Thank you for contacting us! You can adjust the Nginx configuration as desired. You're basically configuring a reverse proxy. This may help as a reference:
> 
> https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-web-server-and-reverse-proxy-for-apache-on-one-ubuntu-16-04-server
> 
> If you have any further questions, do feel free to ask!

sgatlf if you are busy, please don't worry about it. I am conscious of taking up too much of your time. Thank you for all your help.

**Comment by ghost** [comment]
Yes proxy pass should point to the local host 127.0.0.1. It appears that you redacted it to xxx.xx.xxx.xx which could have meant that you were pointing it at something else. I just wanted to make sure you were pointing it at http://127.0.0.1:3000

Self managed hosting can definitely have it's issues and growing pains, which is why Meteor Galaxy managed hosting is a little pricey. But if you get it right yourself, you have learned something and if you continue to use meteor you have saved money over time.

It is alright, hopefully this forum can help someone else along the way.

**Comment by gitMonks** [comment]
I found an article that talks about setting up proper url and removing ports. As suggested by you it asks to point at http://127.0.0.1:3000. 

https://johngibby.com/blog/How_to_deploy_your_meteor.js_app_on_Digital_Ocean#removing-port

I copied paste the whole contents but still no luck. I don't know honestly what would help. It's been 3 days I am searching for a solution. But as you say on the brighter side I am learning something valuable.

**Comment by gitMonks** [comment]
@sgatlf  I am happy for you to access my server. Maybe you can figure out something please email me. I'll owe you a coffee, you will only have to come to London.

**Comment by ghost** [comment]
It is nice to help solve a mystery, but I have a few issues I am combing through myself and probably wouldn't be of much further help. Thank you for the offer of a coffee though. The best advice I can give is check your logs and research the things you do not understand. Also, start over on a fresh slate if it doesn't work after a few hours.

**Comment by ghost** [comment]
Here is my example. It is successfully loading the meteor app, correctly displaying www in browser, and correctly loading the app requested (I am setting up multiple apps on Linode). Also, this setup has received an A in [ssl lab](https://www.ssllabs.com/ssltest/) test. Although I have not finished testing everything like mongodb functionality, maybe this can help you.

/etc/nginx/sites-available/domain.com file (if you use sites available make symlink from /etc/nginx/sites-enabled/domain.com):

```
server {
        listen *:80;
        listen [::]:80;
        server_name www.domain.com domain.com;
        return 301 https://www.domain.com$request_uri;
}

server {
        # SSL configuration
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        # gzip on = speed, gzip off = security
        # gzip off

        server_name www.domain.com domain.com;

        ssl_certificate /etc/nginx/ssl/domain.com/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/domain.com/privkey.pem;
        ssl_dhparam /etc/nginx/ssl/domain.com/dhparam.pem;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
        ssl_prefer_server_ciphers on;

        ssl_stapling on;
        ssl_stapling_verify on;

        ssl_trusted_certificate /etc/nginx/ssl/domain.com/fullchain.pem;

        # Increase max-age after setup is solid.
        add_header Strict-Transport-Security "max-age=86400; includeSubDomains" always;

        root /var/www/html/domain.com/public_html;

        index index.html index.htm index.nginx-debian.html;

        access_log /var/log/nginx/domain.com/app.dev.access.log;
        error_log /var/log/nginx/domain.com/app.dev.error.log;

        error_page 401 403 404 /404.html;

        #location / {
                #try_files $uri $uri/ =404;
        #}

        location / {
                proxy_pass http://127.0.0.1:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header X-Forwarded-For $remote_addr;
        }
}
```

mup.js file:

```
module.exports = {
  servers: {
    one: {
      host: 'xxx.xxx.xxx.xxx',
      username: 'login username here',
      pem: 'path to .rsa file here',
    }
  },

  meteor: {
    name: 'your unique app name',
    path: 'path to app here',
    servers: {
      one: {
        host: 'xxx.xxx.xxx.xxx',
        username: 'root'
      },
    },
    docker: {
      image:'abernix/meteord:base',
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      PORT: 3000,
      UPSTART_UID: 'meteoruser',
      ROOT_URL: 'https://www.domain.com',
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    //If hosting multiple apps ssl will not work with mup
    //ssl: {
    //  crt: 'path to fullchain.pem',
    //  key: 'path to privkey.pem',
    //  port: 443
    //},
    deployCheckWaitTime: 60
  },
  //remove this if you have setup mongodb separately
  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by ghost** [comment]
Also, the "default" configuration file is in /etc/nginx/sites-available/ which points toward the welcome to nginx page. That is probably what is giving you issues and blocking you from seeing your app. You can remove the symlink between /etc/nginx/sites-available/ and /etc/nginx/sites-enabled or move/remove the "default" file from /etc/nginx/sites-available.

**Comment by gitMonks** [comment]
You are right, If  I try to change the settings in my /etc/nginx/sites-available/default Welcome page stops working but the app is still available on mydomain.co.uk:3000. With following configuration the welcome page is being served and the app is available on mydomain.co.uk:3000. I suspect that my server block right at the bottom of the page is not working. 

![image](https://cloud.githubusercontent.com/assets/18562694/19603729/0a90b95e-97aa-11e6-900c-2a876a575ab8.png)

Thanks again. Meanwhile, I am reading the nginx tutorials and configurations. :)

**Comment by ghost** [comment]
In the shell run the command:

```
ls /etc/nginx/sites-available/
```

And also run:

```
ls /etc/nginx/sites-enabled/
```

And reply with what is printed out to screen. If you want you can redact information printed out with fake app names...

Also, run: (you may not need sudo)

```
sudo mv /etc/nginx/sites-available/default ~/
sudo service nginx reload
```

Then clear history in your browser or use incognito mode and then reload your app url.

**Comment by gitMonks** [comment]
**ls /etc/nginx/sites-available**

`default myapp.com`

**ls /etc/nginx/sites-enabled**

`default myApp.com.conf`

contents of these files are

**/sites-available/default**

``````
 Default server configuration
#
server {
        listen 80 default_server;
        listen [::]:80 default_server;


```        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        #server_name *.mydomain.co.uk;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #       include snippets/fastcgi-php.conf;
        #
        #       # With php7.0-cgi alone:
        #       fastcgi_pass 127.0.0.1:9000;
        #       # With php7.0-fpm:
        #       fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        #}
       # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}


# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
#server {
#       listen 80;
#       listen [::]:80;
#
#       server_name example.com;
#
#       root /var/www/example.com;
#       index index.html;
#
#       location / {
#               try_files $uri $uri/ =404;
#       }
#}
server {
    listen 80;
    # to redirect all subdomains use *.yourdomain.com instead of www.yourdomain$
    server_name *.mydomain.co.uk;
    return 301 $scheme://mydomain.co.uk$request_uri;
}


``````

**/sites-available/myapp.com**
`blank`

**/sites-enabled/myapp.com.conf**

```
server {
    listen 80;
    server_name mydomain.co.uk;
    access_log /var/log/nginx/app.dev.access.log;
    error_log /var/log/nginx/app.dev.error.log;
        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header X-Forwarded-For $remote_addr;
        }
}
```

**/sites-enabled/default**

```
# Default server configuration
#
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        #server_name *.mydomain.co.uk;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #       include snippets/fastcgi-php.conf;
        #
        #       # With php7.0-cgi alone:
        #       fastcgi_pass 127.0.0.1:9000;
        #       # With php7.0-fpm:
        #       fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        #}
       # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}


# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
#server {
#       listen 80;
#       listen [::]:80;
#
#       server_name example.com;
#
#       root /var/www/example.com;
#       index index.html;
#
#       location / {
#               try_files $uri $uri/ =404;
#       }
#}
server {
    listen 80;
    # to redirect all subdomains use *.yourdomain.com instead of www.yourdomain$
    server_name *.mydomain.co.uk;
    return 301 $scheme://mydomain.co.uk$request_uri;
}

```

**Comment by ghost** [comment]
Below are the steps I would take.

Whether you need it now or not it is good practice to use symlinks between sites-enables and sites-available. Refer to this explanation: http://serverfault.com/questions/527630/what-is-the-different-usages-for-sites-available-vs-the-conf-d-directory-for-ngi

The directory /etc/nginx/sites-enabled/ should not have any files in it, just symlinks.

First backup both directories to some temporary directory of your choice.

Remove or unlink "all" files in /etc/nginx/sites-enabled.
For example:
`unlink /etc/nginx/sites-enabled/myapp.com.conf`
or
`rm /etc/nginx/sites-enabled/myapp.com.conf`

Remove all files in /etc/nginx/sites-available.

Now create a new mydomain.co.uk.conf file in /etc/nginx/sites-available and use the following:

```
server {
    listen *:80;
    server_name *.mydomain.co.uk mydomain.co.uk;
    return 301 http://www.mydomain.co.uk$request_uri;
}
server {
    listen *:80;
    server_name *.mydomain.co.uk mydomain.co.uk;

    access_log /var/log/nginx/app.dev.access.log;
    error_log /var/log/nginx/app.dev.error.log;

    root /var/www/html/mydomain.co.uk/public_html;

    index index.html index.htm index.nginx-debian.html;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```

After saving, make the symlink through the command:
`sudo ln -s /etc/nginx/sites-available/mydomain.co.uk.conf /etc/nginx/sites-enabled/mydomain.co.uk.conf`

**Comment by gitMonks** [comment]
Strangest update!

I think Gods of nginx have listened to my prayers. Couple of minutes after posting my last comment, the app started working at mydomain.co.uk without the :3000.   All my files contents somehow got deleted including the defaults.  I have just blank files now

App started working and my permission to leave further comments here stopped. :)) Maybe, I had posted too many comments so I couldn't inform you of this development earlier.

I am confused, happy and terrified all at the same time. I need to deploy some updates but I am not doing it yet until I understand what the heck was going wrong. 

I'll definitely follow your advice and try these steps if I run into problems again.

Thanks a million for helping me out!
