### ISSUE TITLE
Error Timed Out while waiting for handhsake - While setup docker

### ISSUE THREAD

**Issue by rollin-s** [zodern/meteor-up#341]
Hello, my trouble here, is that I can't 'mup setup'.. 

When I try to run mup setup, I have this output : 

```
Started TaskList: Setup Docker
[1.2.3.4] - setup docker
Error Timed out while waiting for handshake
```

So, I tried to see the logs, but even if I do mup logs, I have the same output.. "Error timed out while waiting for handshake"

And this is my mup.js

```
module.exports = {
  servers: {
    one: {
      host: '1.2.3.4',
      username: 'root'
      // pem:                                                                                                                                                                                               
      // password:                                                                                                                                                                                          
      // or leave blank for authenticate from ssh-agent                                                                                                                                                     
    }
  },

  meteor: {
    name: 'app',
    path: '../app',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'app.com',
      MONGO_URL: 'mongodb://localhost/meteor'
    },

    //dockerImage: 'kadirahq/meteord'                                                                                                                                                                       
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by Deadlyweed** [comment]
Change  host: '1.2.3.4', on your mup.js to your server IP address and that should fix that problem
What os are you building it on?

**Comment by rollin-s** [comment]
Hrm. But if I want to deploy on a local machine, can't localhost work ?

Or I do have to write like :"192.168.0.1" ? 

If I want to deploy on my server, I should write my server ip ? or localhost ? Not sure how this works..

**Comment by Deadlyweed** [comment]
meteor create appname
cd appname
meteor
in browser put localhost:3000
you can see your app there

**Comment by rollin-s** [comment]
Yes, my app is already working ! 

What I don't understand is what I have to put inside the "host".. 
My app is runnning in localhost:3000.
Event if I change my host to localhost:3000, I have Error connect ECONNREFUSED.

I just don't understand how this "host" works

**Comment by Deadlyweed** [comment]
im using windows to linux and making a new readme file to be easy to under stand it
https://github.com/Deadlyweed/meteor-up/blob/master/README_NEW.md

**Comment by rollin-s** [comment]
Oh great, thank's !

**Comment by Deadlyweed** [comment]
@rollin-s    host: 'xxx.xxx.xx.xx', // Your IP for test or production server. I just updated my file to show that.

**Comment by rollin-s** [comment]
Ok, I tried to do as you said, but I'm still having issues.

This is my "new" mup.js

```
module.exports = {
  servers: {
    one: {
      host: '192.168.0.1',
      username: 'root'
      // pem:                                                                                                                                                                                               
      // password:                                                                                                                                                                                          
      // or leave blank for authenticate from ssh-agent                                                                                                                                                     
    }
  },

  meteor: {
    name: 'myApp',
    path: '../',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'app.com',
      MONGO_URL: 'mongodb://localhost/meteor'
    },

    //dockerImage: 'kadirahq/meteord'                                                                                                                                                                       
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

When I try to 'mup setup', I do have a "EHOSTUNREACH" error.

What should I do if I want to build mup LOCALLY ?
I don't understand at all how mup works.. Could you help me ?

**Comment by Deadlyweed** [comment]
@rollin-s  yes i will help and sorry if i confuse. you. Give me a couple and i will post a mup.js for you to copy and i will mark the spot where your info go. You work on it your own pc and want deploy it to a site like digital ocean for a single app sever. you have windows right. Do you use the command line on digital ocean or putty

**Comment by rollin-s** [comment]
Yes, exactly  !

No, I am on ubuntu 16.04 (Sorry, forgot to tell that !)

**Comment by Deadlyweed** [comment]
Do you have a domain name or just using ur ip? you can use a sub domain name too

**Comment by rollin-s** [comment]
I want to see how this work locally before I can export it in my server ! 
So, I'm just using localhost for testing

**Comment by Deadlyweed** [comment]
@rollin-s 
// thought two mark comment out this line, so it doesnt get read by meteor. 
// If you remove the // it will uncomment the line, so the line will be read by meteor and not green in
 // the mup.js file
module.exports = {
  servers: {
    one: {

```
  // the ip that digital oceans give you for your droplet
  host: '204.34.234.19', // <---goes there (Your IP for Linux test or production server)

  username: 'root',
  // pem: '/home/user/.ssh/id_rsa', // mup doesn't support '~' alias for home directory

  // your password for your droplet after you change it
  password: 'demo', // <---goes there

  // or leave blank for authenticate from ssh-agent
  // opts: { // (optional)
  // port: 22,
  // },
}
```

  },
  meteor: {

```
// the name of you app goes here
name: 'appname',  // <---goes there

path: './', // mup for a single app (best for windows to linux)
  // path: './home/multipleapp/', // mup for multiple app
  // useful when deploying multiple instances (optional) //
  // port: 000,
  // lets you add docker volumes (optional) //
  // volumes: { 
              // passed as '-v /host/path:/container/path' to the docker run command
  // "/host/path": "/container/path", 
  // "/second/host/path": "/second/container/path"
  // },
docker: {
  image:'kadirahq/meteord:base', // (optional) //
  // image: 'abernix/meteord:base', // use this image if using Meteor 1.4+ //

  // lets you add/overwrite any parameter on the docker run command (optional) //
  // args:[
  // "--link=myCustomMongoDB:myCustomMongoDB", // linking example
  // "--memory-reservation 200M" // memory reservation example
  // ]
},
servers: {
  one: {}, two: {}, three: {} // list of servers to deploy, from the 'servers' list
},
buildOptions: {
  // (--server-only--) Skip building mobile apps even if mobile platforms 
  // have been added. (optional)  //
  serverOnly: true,

  // (--architecture--) Builds the server for a different architecture than your developer
  // machine's architecture. //

  // You want to build it for liunx because your using windows and want to deploy on linux
  // architecture: 'os.linux.x86_64',// Builds for a single app (best for windows and mac deploy to linux)

  // (--debug--) Build in debug mode (don't minify, etc). (optional) // 
  // debug: true,

  // (--server--) Location where mobile builds connect to the Meteor server. Defaults to localhost:3000. //

  // if you have a domain name 
  server: 'http://example.com:80',// // <---goes there

  // if you don't have a domain name use your droplet ip
  // server: 'http://204.34.234.19:80',

  // I have a web site that host my game on, so i can make a sub domain in my cpanel 
  // or you can sign up for noip and point it to you droplet ip
  // server: 'http://sub.example.com:80',

  // default (optional) //
  // cleanAfterBuild: true,

  // (--directory--) Output a directory (rather than a tarball) for the application server
      // bundle. If the output location exists, it will be recursively deleted first. 
  // Defaults to /tmp/<uuid> (optional) //
  // buildLocation: '/my/build/folder',

  // (--mobile-settings--) Set optional data for the initial value of Meteor.settings in your mobile application. A new value for Meteor.settings can be set later by the server as part of hot code push. (optional) //
  // mobileSettings: { 
  // yourMobileSetting: "setting value"
  // }

  // (--allow-incompatible-update--) Allow packages in your project to be upgraded or downgraded to versions that are potentially incompatible with the current versions, if required to satisfy all package version constraints. (optional) //
},
env: {
  //(Example 1, http://sub.example.com Example 2, http://xxx.xxx.xx.xx). 
  // You can even use NoIP for this as long you point the domain to your IP on your server. //

  // if you don't have a domain name or sub domain name use your droplet ip
  ROOT_URL: 'http://example.com',// <---goes there
  MONGO_URL: 'mongodb://localhost/meteor'
},
  // log: { // (optional)
  // driver: 'syslog',
  // opts: {
  // "syslog-address":'udp://syslogserverurl.com:1234'
  // }
  // },
  // ssl: {
  // port: 443,
  // crt: 'bundle.crt',
  // key: 'private.key',
  // },
deployCheckWaitTime: 60 // default 10
```

  },
  mongo: { // (optional)
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};

**Comment by Deadlyweed** [comment]
@rollin-s let me know if you dont understand anything. I started to use meteor, so i can move my game all over to JavaScript from php. Meteor Up is just to deploy your app and it doesn't work on local PC(home) but you can use meteor up to deploy it to a server. Unless your use Linux server or you have Ubuntu Server OS installed on a local PC(home). Then you could install the gnome(desktop ver) on it. So you will have the server/desktop. The best of both world.

**Comment by rollin-s** [comment]
Oh. This worked perfectly.

I just have one problem, and I think this'll be finish after.

I can "mup setup".. but in my server, I already have one mongodb running, and I can't stop my running mongodb.

When I run "mup setup",  mongo start failed because my adress (127.0.0.1:27017) is already in use one my server (yes, because I already have mongodb running.)

I tried to change the "MONGO_URL", but "mup setup" still try to connect on the previous address.

Do you have any idea how I can setup that ? I can't stop, or change my mongodb server ports.

**Comment by Deadlyweed** [comment]
@rollin-s get bitvise ssh client, it has ssh and sftp. its way better then putty or using digital ocean comment line. sftp is just like filezilla. i will walk you throw the set up on that too. thats what i use

**Comment by Deadlyweed** [comment]
@rollin-s 
http://prntscr.com/czluhp
http://prntscr.com/czluyk
open sftp
http://prntscr.com/czlvqp
find the folder opt and open it, that's the folder where your app is deploy too
http://prntscr.com/czlwnj
http://prntscr.com/czm34s
you might be able to change that in those to files. 
I'm doing a test really fast to make sure this work right tho. 
if that doesnt work, delete everything in opt and then
meteor mup setup
meteor mup deploy
your folder will show back up. If you use digital ocean, you can delete your droplet and create a new one.

**Comment by rollin-s** [comment]
It worked. Thank's !!!

**Comment by Deadlyweed** [comment]
@rollin-s Your weclome

**Comment by rashmimhatre100** [comment]
Hi All,
I am also facing the same issue.
My mup.js file looks like,
` module.exports = {
         servers: {
    one: {
      host:'54.186.xx.xxx',
      username: 'ubuntu',
      pem: '~/.ssh/mypem.pem'
    }
  },
  app: {
    name: 'myapp',
    path: '/var/www/meteor/myapp',
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://ec2-54-186-xx-xxx.us-west-2.compute.amazonaws.com',
      MONGO_URL: 'mongodb://127.0.0.1:27017/myapp',
      PORT: 3027,
    },

 docker: {
      image: 'abernix/meteord:node-8.4.0-base',
    },
    deployCheckWaitTime : 60,
    enableUploadProgressBar: true
  },
  mongo: {
    port:27017,
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};
`

Meteor version is 1.6.
Thanks in advance!
