### ISSUE TITLE
Unable to deploy with meteor 1.4.2

### ISSUE THREAD

**Issue by WayneUong** [zodern/meteor-up#342]
The deploy process is stuck here:

```
  mup:module:default exec => mup deploy +0ms
  mup:module:meteor exec => mup meteor deploy +1ms
  mup:module:meteor exec => mup meteor push +4ms
Building App Bundle Locally
```

When I revert back to 1.4.1, it deploys fine.

**Comment by WayneUong** [comment]
The bundling and deploying process is done on an EC2 server to another EC2 server.

**Comment by WayneUong** [comment]
It works fine when I deploy from my Mac to the EC2 Ubuntu server, but bcrypt is missing, because of the difference in architecture. However, the bundling time is much longer than 1.4.1, around 10-15 minutes.

**Comment by WayneUong** [comment]
I tested with a VM Ubuntu, it works, but it takes 5 minutes to bundle. Still no idea why it doesn't work on EC2 Ubuntu after updating.

**Comment by andy4545** [comment]
I am getting the same issue.  "Building App Bundle Locally" has been running for 2 hours now. 
I am deploying Windows 10, using Meteor 1.4.2 and kadirahq/meteor-up 1.0.4

```
$ DEBUG=* mup deploy --settings ../config/development/settings.json
  mup:module:default exec => mup deploy +0ms
  mup:module:meteor exec => mup meteor deploy +3ms
  mup:module:meteor exec => mup meteor push +13ms
Building App Bundle Locally
```

**Comment by zodern** [comment]
There now is a `--verbose` flag that will show the output from `meteor build`. This issue can be reopened if anyone encounters this problem again.
