### ISSUE TITLE
'mup.js' file not found. Run 'mup init' first.

### ISSUE THREAD

**Issue by castlefields** [zodern/meteor-up#346]
I have a meteor project which I use mup to deploy, but an older version 1.0.1. The server is heavily modified - not by me, and it is impossible for me to just spin up a new server and use the 'New' mup configuration here.

My question is that I have a simple update to my old application and on running mup deploy - as usual I get the following error:-

'mup.js' file not found. Run 'mup init' first.

What do I have to do to just use the old mup way of doing things?? I've tried removing mup and then installing 1.0.1 but the above error remains.

Can anyone point me in the right direction to solve this...

Thanx

**Comment by castlefields** [comment]
[https://forums.meteor.com/t/need-good-old-mup/27677](url)

To get back an old version of mup run: npm -g install mup@0.11.3

This installs the pre mup.js version

**Comment by digz6666** [comment]
@castlefields thanks man!
