### ISSUE TITLE
docker args updated on deploy only

### ISSUE THREAD

**Issue by sirpy** [zodern/meteor-up#348]
when i do mup reconfig or start/stop the docker arguments are not reflected in the scripts on the target /opt/../config
only when doing mup deploy do the scripts seem to be changed

**Comment by appleparan** [comment]
Yes, it does. I finally find out why my mup reconfig & mup setup doesn't work. Thanks for inspection.

**Comment by zodern** [comment]
In the latest version, `mup reconfig` will update docker args.
