### ISSUE TITLE
Archiving failed

### ISSUE THREAD

**Issue by timothyarmes** [zodern/meteor-up#35]
When I try to deploy my app I get this error:

```
macpro:do Tim$ DEBUG=* mup-test deploy
  mup:module:default exec => mup deploy +0ms
  mup:module:meteor exec => mup meteor deploy +0ms
  mup:module:meteor exec => mup meteor push +12ms
Bulding App Bundle Locally
=> Archiving failed: ENOENT, stat '/tmp/ee280d18-a4fc-4820-b11f-4d2289d81ae6/bundle/programs/server/npm/react-runtime-prod/node_modules/react/node_modules/envify/node_modules/jstransform/node_modules/esprima-fb/.#README.md'
Error: ENOENT, stat '/tmp/ee280d18-a4fc-4820-b11f-4d2289d81ae6/bundle/programs/server/npm/react-runtime-prod/node_modules/react/node_modules/envify/node_modules/jstransform/node_modules/esprima-fb/.#README.md
```

Unfortunately there's absolutely no indication as to what could be going wrong :(

**Comment by markoshust** [comment]
I remember this error message. Are you using a newer React version (0.14.4?).

**Comment by timothyarmes** [comment]
Yes, I am.

I've also just tried to use mupx instead, and it's failing with the same error.

**Comment by timothyarmes** [comment]
OK, I've just downgraded React and that's worked. Nevertheless I'll leave this bug report open since there's no reason it should be failing. Note that I can push to Galaxy without any issues too.

**Comment by markoshust** [comment]
Yes, this was an issue in current mup, definitely should be open :) It's a bug with mup when using React 0.14.4.

**Comment by MasterJames** [comment]
I think it's a file lock error or most likely permissions?

**Comment by arunoda** [comment]
This is pretty hard to solve for whatever the reason and we don't anything fancy here. Just build it using Meteor's command.

So, my suggestion is not to use 0.14.4.
With Meteor 1.3, you don't need this package.
See: [Getting Started with Meteor 1.3 and React](https://voice.kadira.io/getting-started-with-meteor-1-3-and-react-15e071e41cd1)

**Comment by timothyarmes** [comment]
Well, this time it's failed with React. Next time the same issue could
affect another package, no?

Also, moving away from the React package can only be done once it's
no longer required by any 3rd party packages that we're using.

What is the actual issue? Why doesn't meteor deploy suffer from it?

**Comment by markoshust** [comment]
I also fail to understand why 0.14.4 is not working with this, as everything is standard. There is something that is mup-specific causing this to fail, and this may lead to other packages not loading as well. I really think this should be solved as 0.14.4 is starting to become the standard version of React install at this point in time.

**Comment by arunoda** [comment]
Here's the build related code. There is nothing mup specific.
See: https://github.com/kadirahq/meteor-up/blob/master/lib/modules/meteor/build.js#L26

I'm open to any reason why it's failed and happy to fix it's an issue on mup.

**Comment by ghost** [comment]
I would add that it may not be limited to 0.14.4. I am running 0.14.3 and had the exact same error.

NOTE: However I was using mupx, not _this_ mup. I'm trying to sort out all of the different mups. It's my first time using mup, so I'm just getting starteding.

**Comment by gsabran** [comment]
running React `0.14.7` gives the same issue. By how much should I downgrade React?
Also what do you mean by `with Meteor 1.3 you don't need this package` ? In your [post](https://voice.kadira.io/getting-started-with-meteor-1-3-and-react-15e071e41cd1#.71t06gtuq) you do `npm i --save react react-dom` right?
Thanks!

**Comment by timbrandin** [comment]
I solved this by removing `.meteor/local` and `node_modules`, and re-installed npm modules using `meteor npm install`, I guess having multiple versions of npm on my machine caused this issue and using meteor npm makes meteor use the correct version that works with node 0.12 which meteor ships with at the moment.
