### ISSUE TITLE
[Meteor 1.4.2] Unable to bundle bcrypt

### ISSUE THREAD

**Issue by WayneUong** [zodern/meteor-up#350]
I'm deploying from ubuntu to ubuntu. I already included the bcrypt package in `packages.json`, but this error still shows:

```
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
```

**Comment by CaptainChemist** [comment]
A little late, but if you just run that command `meteor npm install --save bcrypt` and you should be all set. I used the `abernix/meteord:base` docker image and as of Nov 22, 2016 it worked great.
