### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by paulo2nd** [zodern/meteor-up#351]
I think i don't know how to do it, but the error is:

```
mup setup

Started TaskList: Setup Docker
[0.0.0.0] - setup docker
Error Invalid username
```

my mup.js
```
module.exports = {
  servers: {
    one: {
      host: '0.0.0.0',
      user: 'root',
      pem: "/home/webaula/.ssh/id_rsa"
    }
  },

  meteor: {
    name: 'app',
    path: '../',
    servers: {
      one: {},
    },
    env: {
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};

```

**Comment by Deadlyweed** [comment]
@paulo2nd mup.js should look like this. This is set up for one app deploy and from windows to Linux tho.  Let me know if you have any problem.

// To comment lines out put // and to uncomment something just remove //. The lines will be green, when they are comment out and they will not be read. You uncomment them and they will be read.
module.exports = {
  servers: {
    one: {
      host: 'The IP for your Digital Oceans, AWS, or EC2', // Your IP for Linux test or production server IP
      username: 'root',
      // pem: '/home/user/.ssh/id_rsa', // mup doesn't support '~' alias for home directory  
      password: 'your password for your droplet after you change it', 
      // or leave blank for authenticate from ssh-agent
      // opts: { // (optional)
      // port: 22,
      // },
    }
  },
  meteor: {
      // 
    name: 'the name of you app goes here',
    path: './', 
      // lets you add docker volumes (optional) //
      // volumes: {
      // passed as '-v /host/path:/container/path' to the docker run command //
      // "/host/path": "/container/path",
      // "/second/host/path": "/second/container/path"
      // },
    docker: {
      image:'kadirahq/meteord:base', 
      // image: 'abernix/meteord:base', // use this image if using Meteor 1.4+ (optional)
      // lets you add/overwrite any parameter on the docker run command (optional) //
      // args:[
      // "--link=myCustomMongoDB:myCustomMongoDB", // linking example
      // "--memory-reservation 200M" // memory reservation example
      // ]
    },
    servers: {
      one: {}, two: {}, three: {} // list of servers to deploy, from the 'servers' list
    },
    buildOptions: {
      // (--server-only--) Skip building mobile apps even if mobile platforms have been added. (optional)  //
      serverOnly: true,
      // (--architecture--) Builds the server for a different architecture // 
      // than your developer machine's architecture. //
      architecture: 'os.linux.x86_64',
      // (--debug--) Build in debug mode (don't minify, etc). (optional) // 
      // debug: true,
      // (--server--) Location where mobile builds connect to the Meteor server. //
      server: 'http://example.com:80', // Use this if you using a domain name
      // server: 'http://xxx.xx.xxx.xx:80', // Use this if you dont have a domain name or sub domain name
      // server: 'http://sub.example.com:80', // Use this if you using a sub domain name
      // default (optional) //
      // cleanAfterBuild: true,
      // (--directory--) Output a directory (rather than a tarball) for the //
      // application server bundle. If the output location exists, it will be //
      // recursively deleted first. Defaults to /tmp/<uuid> (optional) //
      // buildLocation: '/my/build/folder',
      // (--mobile-settings--) Set optional data for the initial value of //
      // Meteor.settings in your mobile application. A new value for //
      // Meteor.settings can be set later by the server as part of hot code push. (optional) //
      // mobileSettings: { 
      // yourMobileSetting: "setting value"
      // }
      // (--allow-incompatible-update--) Allow packages in your project to be //
      // upgraded or downgraded to versions that are potentially incompatible //
      // with the current versions, if required to satisfy all package version //
      // constraints. (optional) //
    },
    env: {
      // You can even use NoIP for this as long you point the domain to your //
      // IP on your server. //
      // ROOT_URL: 'http://xxx.xx.xxx.xx', // use this if you dont have a domain name or sub domain
      ROOT_URL: 'http://example.com', // Use this if you using a domain name
      // ROOT_URL: 'http://sub.example.com', // Use this if you using a sub domain name
      MONGO_URL: 'mongodb://localhost/meteor'
    },
      // log: { // (optional)
      // driver: 'syslog',
      // opts: {
      // "syslog-address":'udp://syslogserverurl.com:1234'
      // }
      // },
      // ssl: {
      // port: 443,
      // crt: 'bundle.crt',
      // key: 'private.key',
      // },
    deployCheckWaitTime: 60 // default 10
  },
  mongo: { // (optional)
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};

**Comment by paulo2nd** [comment]
Thanx  Deadlyweed, This will be a Linux (Debian) test server. Do I need to install Docker or Mup will install it for me?

**Comment by Deadlyweed** [comment]
@paulo2nd If you are working on it on a the Linux server and deploy it on it. You will need to set up mup but this version of Meteor Up is powered by Docker, making deployment easy to manage and reducing a lot of server specific errors.. If your using windows and going to Linux use this to help you out. I know Ubuntu support it but I don't know about Debian tho. 
https://github.com/Deadlyweed/Meteor-Up-Noobs/blob/master/windowssinglemup.md
Kadirahq has more Table of Contents then I do. If you want to know more about the other stuff I have comment out then check his out. 
https://github.com/kadirahq/meteor-up/blob/master/README.md

**Comment by madhan5000** [comment]
@paulo2nd Mup will install docker on the target machine. 

here is the log that you will get when you issue mup setup

`$ mup setup

Started TaskList: Setup Docker
[10.4.35.134] - setup docker
[10.4.35.134] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[10.4.35.134] - Setup Environment

Started TaskList: Setup Mongo
[10.4.35.134] - setup environment
[10.4.35.134] - setup environment: SUCCESS
[10.4.35.134] - copying mongodb.conf
[10.4.35.134] - Setup Environment: SUCCESS
[10.4.35.134] - copying mongodb.conf: SUCCESS

Started TaskList: Start Mongo
[10.4.35.134] - start mongo
[10.4.35.134] - start mongo: SUCCESS`

**Comment by paulo2nd** [comment]
Changed my server to ubuntu 16.04.1 LTS, now my problem is:

[10.61.1.8] - setup docker
Error All configured authentication methods failed

I tried with password and pem (RSA without passphrase). root or user with sudo permissions, same error...

**Comment by madhan5000** [comment]
@paulo2nd You probably did this but just want to make sure you did username + password and commented out "pem :" entry 

Also, from the mup.js that you have posted, I see you are referring to 

`pem: "/home/webaula/.ssh/id_rsa"`

which is not a pem file. you can certainly put a pem file in that folder but I believe it needs to be referenced explicitly.  for example

`pem: "/home/webaula/.ssh/id_rsa/my_secret.pem"`

hope that helps

**Comment by paulo2nd** [comment]
@madhan5000 thank you, the problem was ssh rootlogin disabled.

now i have:

Started TaskList: Setup Docker
[10.61.1.8] - setup docker
[10.61.1.8] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[10.61.1.8] - Setup Environment

Started TaskList: Setup Mongo
[10.61.1.8] - setup environment
[10.61.1.8] - setup environment: SUCCESS
[10.61.1.8] - copying mongodb.conf
[10.61.1.8] - Setup Environment: SUCCESS
[10.61.1.8] - copying mongodb.conf: SUCCESS

Started TaskList: Start Mongo
[10.61.1.8] - start mongo
[10.61.1.8] - start mongo: SUCCESS

Thanks all :)
