### ISSUE TITLE
Port doesn't change according to mup.js file

### ISSUE THREAD

**Issue by avishaan** [zodern/meteor-up#355]
Anytime I change the port in my config file, it still deploys to port 80. Here is my config

```js
module.exports = {
  servers: {
    one: {
      host: "107.175.239.xxx",
      username: "root",
      pem: "/Users/avi/.ssh/id_rsa.pem",
    }
  },

  meteor: {
    name: 'dashboard',
    port: 2080,
    path: '../../',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
      cleanAfterBuild: true,
    },
    env: {
      ROOT_URL: 'http://107.175.239.xxx',
      MONGO_URL: 'mongodb://localhost:27017'
    },
    docker: {
      image: 'abernix/meteord:base',
      //image: 'kadirahq/meteord',
      //image: 'ulexus/meteor:v1.4',
    },
    // dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 120
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

but in docker you can see that it is actually deployed on port 80

![pasted_image_11_7_16__11_14_am](https://cloud.githubusercontent.com/assets/5360982/20071944/618548a4-a4db-11e6-8a07-7ef581a5fc25.png)

**Comment by avishaan** [comment]
This is not intuitive, I had to change my `meteor.env.PORT` property in order to get this to work the way I wanted. It seems to be completely independent of the `meteor.port` property. Is this the intended use, if so it needs to be cleared up in the README. If not then it may need to be fixed to act inline with the README

Here is the equivalent config that works

``` js
module.exports = {
  servers: {
    one: {
      host: "107.175.239.xxx",
      username: "root",
      pem: "/Users/avi/.ssh/id_rsa.pem",
    }
  },

  meteor: {
    name: 'dashboard',
    //port: 2080,
    path: '../../',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
      cleanAfterBuild: true,
    },
    env: {
      PORT: 2080,
      ROOT_URL: 'http://107.175.239.xxx',
      MONGO_URL: 'mongodb://localhost:27017'
    },
    docker: {
      image: 'abernix/meteord:base',
      //image: 'kadirahq/meteord',
      //image: 'ulexus/meteor:v1.4',
    },
    // dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 120
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

which results in 

``` shell
CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS              PORTS                        NAMES
98726778e737        abernix/meteord:base   "/bin/sh -c 'bash $ME"   About a minute ago   Up About a minute   0.0.0.0:2080->80/tcp         dashboard
e876172cf7f3        mongo                  "/entrypoint.sh mongo"   4 hours ago          Up 4 hours          127.0.0.1:27017->27017/tcp   mongodb
```

**Comment by ivanthemeh** [comment]
@codeHatcher I am having a similar issue and not able to set the meteor.port at all no matter what I put it to and when I set the meteor.env.PORT to 3000 like you did my site is only available at that specific port instead of being available on port 80 and mapping the container to 3000. Any ideas? 

https://github.com/zodern/meteor-up/issues/471

**Comment by avishaan** [comment]
Can you share your mup file?

**Comment by maxmatthews** [comment]
I submitted a pull request for this issue (https://github.com/zodern/meteor-up/pull/472). I don't think the port setting does anything in the `meteor: {}` object unless it goes in the `env` section and is capitalized. That seems to make everything magically work. Removing the `port` key outside the `env` object seems to have no effect.

**Comment by avishaan** [comment]
Yes, that's what I mentioned above as well
