### ISSUE TITLE
mup setup fails silently if pem file doesn't exist

### ISSUE THREAD

**Issue by edemaine** [zodern/meteor-up#356]
`mup setup` does/prints nothing if the pem file specified for a server doesn't exist, e.g. a typo in the path, or upgrading from old-mup where I had a `~` at the beginning of the filename.  (I saw the documentation that that wasn't allowed, but it was difficult to know that the pem part was reasonable for the no response...)  

Could we add an error message?  (Similar in spirit to #339.)

**Comment by edemaine** [comment]
Sorry, duplicate of #189

**Comment by shadowcodex** [comment]
no this is good too because I forgot tou pdate my pem path when moving to my deploy server.
