### ISSUE TITLE
How to access log files when deploying to multiple servers?

### ISSUE THREAD

**Issue by satyavh** [zodern/meteor-up#357]
I can't seem to access logs files (using mup logs), gives an error. Which makes sense because I think that each server has its own log files and Mup can't figure out what to do. So I guess this concept is not going to work here.

So how to access log files of individual servers using mup log? Or do I need to view the log file on the server? If so where is it located?

**Comment by zodern** [comment]
Mup supports showing logs from multiple servers, In 1.3, you will be able to get logs from an individual server with the `--servers` option.

If you have the error again, please post it here.
