### ISSUE TITLE
babel-runtime not working

### ISSUE THREAD

**Issue by edemaine** [zodern/meteor-up#358]
I'm getting the following error during `mup deploy`:

        [...] x Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        app on port:80
        /bundle/bundle/programs/server/boot.js:348
        }).run();
           ^

        Error: Can't find npm module 'babel-runtime/helpers/typeof'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
            at Object.require (/bundle/bundle/programs/server/boot.js:200:17)
            at options.fallback (packages/modules-runtime.js:445:18)
            at Module.require (packages/modules-runtime.js:112:16)
            at Module.Mp.import (/bundle/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:70:16)
            at meteorInstall.node_modules.meteor.webapp.webapp_server.js (/bundle/bundle/programs/server/packages/webapp.js:33:26)
            at fileEvaluate (packages/modules-runtime.js:181:9)
            at require (packages/modules-runtime.js:106:16)
            at /bundle/bundle/programs/server/packages/webapp.js:842:1
            at /bundle/bundle/programs/server/packages/webapp.js:855:3
            at /bundle/bundle/programs/server/boot.js:295:34

        => Redeploying previous version of the app

        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------

By contrast, running `meteor` locally works fine (unlike others who have had this error message locally: https://github.com/meteor/meteor/issues/6918 and https://github.com/meteor/meteor/issues/8032).

Context: I just upgraded Meteor to 1.4.2 (from 1.3.x) and switched from old mup to new mup.  I'm deploying from one Ubuntu machine to another.  I tried my best to delete everything from the deploy machine, but maybe I missed something?  I'm using `dockerImage: 'abernix/meteord:base'`.

**Comment by benjamn** [comment]
This is a Meteor problem, sorry! https://github.com/meteor/meteor/issues/8032#issuecomment-259431609

**Comment by edemaine** [comment]
Wow, what timing.  Thanks, it's working now.  (I assumed it was something mup specific because it was running fine locally, but apparently not!)
