### ISSUE TITLE
/tmp still used with buildLocation set

### ISSUE THREAD

**Issue by edemaine** [zodern/meteor-up#360]
I have `meteor: buildOptions: buildLocation` set to a directory, and the build does get placed there, but I also get builds in temporary directories in `/tmp`.  The problem is that my builds are big, and my `/tmp` partition is relatively small, so I can only build a few times before I run out of space and have to manually delete the directories in `/tmp`.  Am I missing an option that will prevent this space-leaking behavior?

**Comment by etyp** [comment]
@edemaine as far as I can tell, the `cleanAfterBuild` option is not actually implemented anywhere in the code. I think the option in the readme is there because it used to exist in older versions of mup but now does not.

**Comment by zodern** [comment]
I am not able to reproduce this. If buildLocation is set, it shouldn't put anything in temp.

**Comment by edemaine** [comment]
Agreed; I think the last version fixed this?
