### ISSUE TITLE
SSL not working

### ISSUE THREAD

**Issue by edemaine** [zodern/meteor-up#361]
I just got the latest mup working on my project, but I'm still having trouble when enabling SSL.  Has anyone seen this behavior before?  When my Meteor project is running on the target, I experience:

- Port 80 properly sends a redirect to https (using Meteor package `force-ssl`)
- Port 443 accepts connections from localhost, but then immediately disconnects.
- Port 443 rejects connections from all outside, even when telnetting to the hostname from the same host.
- Yet `netstat -tulpn` lists ports 80 and 443 as listening properly (I think -- not really an expert on IPv6 addresses):

      Active Internet connections (only servers)
      Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
      tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      1790/docker-proxy
      tcp6       0      0 :::80                   :::*                    LISTEN      4940/docker-proxy
      tcp6       0      0 :::22                   :::*                    LISTEN      1186/sshd
      tcp6       0      0 :::443                  :::*                    LISTEN      5023/docker-proxy

As far as I can tell (from `iptables` and my OpenStack configurator), it's not an issue with my own firewall. I also haven't changed anything since old-mup was working and was properly serving https over port 443.

Here is the relevant part of my `mup.js` (sanitized to remove hostnames):

    module.exports = {
      meteor: {
        ...
        dockerImage: 'abernix/meteord:base',
        buildOptions: {
          serverOnly: true,
          buildLocation: '/scratch/build'
        },
        env: {
          ROOT_URL: 'https://hostname.domainname',
          PORT: 80,
          MONGO_URL: 'mongodb://localhost/meteor'
        },
        ssl: {
          // pem: '../host.ssl/host.pem'
          crt: '../host.ssl/host.crt',
          key: '../host.ssl/host.key',
          port: 443
        },
        deployCheckWaitTime: 150
      }
      mongo: {
        oplog: true,
        port: 27017,
        servers: {one: {}}
      }
    }

Maybe there's some issue with my SSL crt/key pair?  (With old mup, I used the .pem file.  I also tried setting crt and key to the pem file.)  Are there logs somewhere I can investigate to see what's wrong with the SSL proxy?

`mup deploy` is working fine, and `mup logs` shows nothing of interest.

**Comment by aleritty** [comment]
I have the same trouble, and inside the syslog I found this:
No such image: meteorhacks/mup-frontend-server:latest
this is for sure the problem with SSL.

If I comment out the SSL part my app deploy correctly.

**Comment by edemaine** [comment]
Any updates/ideas on this?  I tried updating to the new Meteor, but still can't deploy my server, which is pretty annoying.  No error messages (as Meteor is running, and is correctly redirecting http to https), but telnetting to localhost port 443 leads to immediate disconnect, while telnetting to the host at port 443 gives "connection refused".

Here is the bottom of my syslog, which doesn't seem to reveal much (but I'm not very familiar with docker). Does docker have its own firewall?...

```
Nov 22 18:33:14 hostname kernel: [1126112.223654] docker0: port 2(veth0502b1c) entered disabled state
Nov 22 18:33:14 hostname kernel: [1126112.270872] docker0: port 2(veth0502b1c) entered disabled state
Nov 22 18:33:14 hostname kernel: [1126112.271316] device veth0502b1c left promiscuous mode
Nov 22 18:33:14 hostname kernel: [1126112.271323] docker0: port 2(veth0502b1c) entered disabled state
Nov 22 18:33:15 hostname kernel: [1126112.568493] docker0: port 3(veth17beb2f) entered disabled state
Nov 22 18:33:15 hostname kernel: [1126112.568851] device veth17beb2f left promiscuous mode
Nov 22 18:33:15 hostname kernel: [1126112.568858] docker0: port 3(veth17beb2f) entered disabled state
Nov 22 18:33:16 hostname ntpd[2439]: Deleting interface #17 veth0502b1c, fe80::84b8:61ff:fe8d:adec#123, interface stats: received=0, sent=0, dropped=0, active_time=1112619 secs
Nov 22 18:33:16 hostname ntpd[2439]: Deleting interface #16 veth17beb2f, fe80::cd2:4ff:fe8a:8f82#123, interface stats: received=0, sent=0, dropped=0, active_time=1112619 secs
Nov 22 18:33:16 hostname ntpd[2439]: peers refreshed
Nov 22 18:33:49 hostname kernel: [1126146.758827] device veth52af827 entered promiscuous mode
Nov 22 18:33:49 hostname kernel: [1126146.759117] IPv6: ADDRCONF(NETDEV_UP): veth52af827: link is not ready
Nov 22 18:33:49 hostname kernel: [1126146.935929] IPv6: ADDRCONF(NETDEV_CHANGE): veth52af827: link becomes ready
Nov 22 18:33:49 hostname kernel: [1126146.935963] docker0: port 2(veth52af827) entered forwarding state
Nov 22 18:33:49 hostname kernel: [1126146.935966] docker0: port 2(veth52af827) entered forwarding state
Nov 22 18:33:50 hostname kernel: [1126147.457174] device veth3e550ff entered promiscuous mode
Nov 22 18:33:50 hostname kernel: [1126147.457322] IPv6: ADDRCONF(NETDEV_UP): veth3e550ff: link is not ready
Nov 22 18:33:50 hostname kernel: [1126147.457326] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:33:50 hostname kernel: [1126147.457331] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:33:50 hostname kernel: [1126147.683912] IPv6: ADDRCONF(NETDEV_CHANGE): veth3e550ff: link becomes ready
Nov 22 18:33:54 hostname kernel: [1126152.034066] docker0: port 3(veth3e550ff) entered disabled state
Nov 22 18:33:54 hostname kernel: [1126152.040855] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:33:54 hostname kernel: [1126152.040863] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:33:55 hostname ntpd[2439]: Listen normally on 18 veth3e550ff fe80::dc9a:49ff:feaa:5c1d UDP 123
Nov 22 18:33:55 hostname ntpd[2439]: Listen normally on 19 veth52af827 fe80::6ce7:14ff:fe2b:3532 UDP 123
Nov 22 18:33:55 hostname ntpd[2439]: peers refreshed
Nov 22 18:33:55 hostname ntpd[2439]: new interface(s) found: waking up resolver
Nov 22 18:33:58 hostname kernel: [1126155.862066] docker0: port 3(veth3e550ff) entered disabled state
Nov 22 18:33:58 hostname kernel: [1126155.869040] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:33:58 hostname kernel: [1126155.869047] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:34:04 hostname kernel: [1126161.952015] docker0: port 2(veth52af827) entered forwarding state
Nov 22 18:34:11 hostname kernel: [1126168.852165] docker0: port 3(veth3e550ff) entered disabled state
Nov 22 18:34:11 hostname kernel: [1126168.853351] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:34:11 hostname kernel: [1126168.853359] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:34:26 hostname kernel: [1126183.904096] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:34:53 hostname kernel: [1126210.813757] docker0: port 3(veth3e550ff) entered disabled state
Nov 22 18:34:53 hostname kernel: [1126210.815290] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:34:53 hostname kernel: [1126210.815298] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:35:08 hostname kernel: [1126225.824038] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:37:27 hostname kernel: [1126364.972239] docker0: port 3(veth3e550ff) entered disabled state
Nov 22 18:37:27 hostname kernel: [1126364.973589] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:37:27 hostname kernel: [1126364.973600] docker0: port 3(veth3e550ff) entered forwarding state
Nov 22 18:37:42 hostname kernel: [1126380.000047] docker0: port 3(veth3e550ff) entered forwarding state
```

**Comment by edemaine** [comment]
I found the issue.  Three problems:

1. I didn't run `mup setup` after adding the SSL configuration.  Obvious, in hindsight.  Would have been helpful to have an error message, but this is definitely on the side of user error.

2. For some reason, there were existing `bundle.crt` and `private.key` **directories** which prevented the copy from working.  (I got good error messages saying the copy failed.)  I'm guessing these were leftovers from the old mup or from some previous poor configurations.

```
$ ssh host ls -l /opt/projectname/config/
total 16
drwxr-xr-x 2 ubuntu root   4096 Nov  9 17:36 bundle.crt
-rw-r--r-- 1 ubuntu ubuntu  549 Nov 22 18:33 env.list
drwxr-xr-x 2 ubuntu root   4096 Nov  9 17:36 private.key
-rw-r--r-- 1 ubuntu ubuntu 1167 Nov 22 18:33 start.sh
```

3. I needed to specify my `.pem` file instead of my `.crt` file as my `crt`.  Otherwise I got the following message:

```
nginx: [emerg] PEM_read_bio_X509_AUX("/bundle.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
        nginx: configuration file /opt/nginx/conf/nginx.conf test failed
```

Anyway, now everything is working!
