### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by buhrmi** [zodern/meteor-up#362]
Hello,

sorry I'm not that familiar with docker. Assuming my app has some dependencies, eg imagemagick, how do I instruct mup to install them in the docker container? I assume I can't just somewhere say "hey docker, please also run `sudo apt-get install imagemagick imagemagickcore-dev libmagick++-dev`". Or can I?

Cheers.

**Comment by bogdan-bodnaruk** [comment]
Also interested in that. For example I need to install wkhtmltopdf and others

**Comment by srokatonie** [comment]
Any updates on this?

**Comment by y0-0y** [comment]
bump

**Comment by zodern** [comment]
Customizing the docker image created during Prepare Bundle will be available in the next update. You can check the [docs](https://github.com/zodern/meteor-up/blob/dev/docs/docs.md#customize-docker-image) to see how it will work. Let me know if this will work for you.

**Comment by zodern** [comment]
It is available in mup 1.4.4.
