### ISSUE TITLE
js not minified after mup deploy

### ISSUE THREAD

**Issue by quape** [zodern/meteor-up#371]
Hi there,
I managed to deploy a meteor app using mup but when I show the html source of the page all those dozen js files are there. How is that possible? When I run my local meteor app with production flag minifying works fine.

**Comment by quape** [comment]
Oh, found the problem. I had `debug: true` in `buildOptions` in `mup.js` config file!

**Comment by SachaG** [comment]
Just realized the same thing… I don't know if it's a good idea to have `debug: true` by default in the example…
