### ISSUE TITLE
Order of tasks

### ISSUE THREAD

**Issue by artpolikarpov** [zodern/meteor-up#373]
I often get situation when `start` is not waiting for `envconfig` to complete:

<img width="440" alt="screen shot 2016-11-19 at 08 36 05" src="https://cloud.githubusercontent.com/assets/870859/20453362/6818fbc8-ae33-11e6-8d81-8a6fa7d09f91.png">

Sometimes I even get server restarted _before_ new environment variables copied. Is the promise resolve too soon?

**Comment by shadowcodex** [comment]
This shouldn't be happening because of the promise string here.. `modules/meteor/index.js:226`

```js
return push(api).then(() => envconfig(api)).then(() => start(api));
```

If you can point me in the right direction I can fix this in my current PR.

**Comment by shadowcodex** [comment]
@zodern on the nodemiral stuff is list.run async or sync?

I wonder if this is returning resolve before it's completely finished with all the tasks... 

```js
export function runTaskList(list, sessions, opts) {
  return new Promise((resolve, reject) => {
    list.run(sessions, opts, summaryMap => {
      for (var host in summaryMap) {
        if (summaryMap.hasOwnProperty(host)) {
          const summary = summaryMap[host];
          if (summary.error) {
            reject(summary.error);
            return;
          }
        }
      }

      resolve();
    });
  });
}
```

**Comment by zodern** [comment]
This morning I looked into the bug, and it seems to no longer exist.

**Comment by shadowcodex** [comment]
awesome
