### ISSUE TITLE
[Question] Remove app deployed with mup completely

### ISSUE THREAD

**Issue by cyclops24** [zodern/meteor-up#374]
Hi please guide me how we can remove app deployed with mup completely (app, database, ...)?
Thanks

**Comment by magp3** [comment]
@cyclops24 just do `mup stop` to stop the docker containers from running. If you wish to also remove the containers:
use docker rm to remove the containers which mup created. e.g.:
as root:
`
docker ps -a
`
`docker rm <containerId>`

**Comment by cyclops24** [comment]
Thanks @magp3. I want to remove app and DB that deployed with MUP. With `docker rm <containerId>` database also will remove?

**Comment by magp3** [comment]
@cyclops24 By default mup installs mongo in a container. Use `docker ps -a` to list all containers and see
if you have a container running mongo and use `docker rm` to remove that too.

**Comment by cyclops24** [comment]
@magp3 So it's install one mongo container for each app?
for example this is my `docker ps -a` output:
```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                PORTS                        NAMES
c4148d5e3bf4        abernix/meteord:base   "/bin/sh -c 'bash $ME"   7 days ago          Removal In Progress                                myApp
3a1880d7d150        mongo                  "/entrypoint.sh mongo"   7 days ago          Up 4 days             127.0.0.1:27017->27017/tcp   mongodb
```
Is `3a1880d7d150` contain all db or just one db for `c4148d5e3bf4` and myApp container?
In previous version we remove db with mongo commands like `db.dropDatabase()`

**Comment by cyclops24** [comment]
When I try remove db container it's return below error:
```
Error response from daemon: You cannot remove a running container 3a1880d7d150374a9aa89276ef5cd17d0b2167c03ef6376f14916ba4ecfa3b28. Stop the container before attempting removal or use -f
```

**Comment by cyclops24** [comment]
Also when I stop project using `mup stop` it's remove from `docker ps -a` result. I think we need another approach.

**Comment by magp3** [comment]
Ok then I guess using `mup stop` is enough. Why do you need another approach?

**Comment by cyclops24** [comment]
@magp3 `mup stop` only stop app and remove and remove container from `docker ps -a` output but I want to remove app and database totaly. @arunoda later said somewhere that we should use `db.dropDatabase()`. I can't found it now. 😞

**Comment by cyclops24** [comment]
Guys I need your help...
I have this issue for more a week. 😞

**Comment by zodern** [comment]
@cyclops24 did you find how to completely remove the app and database?

**Comment by cyclops24** [comment]
@zodern unfortunately no and I switch to other deployment approach.

**Comment by shadowcodex** [comment]
To remove database just log into mongo as instructed in docs. Drop database in there. Then stop all docker instances and remove them.

**Comment by zodern** [comment]
I am going to close this in favor of #395
