### ISSUE TITLE
mup deploy failed to build [Error: spawn meteor ENOENT]

### ISSUE THREAD

**Issue by Fred-J** [zodern/meteor-up#375]
Local machine Mac El Capitan.
Remote server AWS ubuntu 16.04

.deploy$ mup setup
Started TaskList: Setup Docker
 - setup docker
 - setup docker: SUCCESS

Started TaskList: Setup Meteor
 - Setup Environment
 - Setup Environment: SUCCESS

////////////////// ERROR DEPLOYING \\\\\\\\\\\\\\\\\\\\\\\
.deploy$ mup deploy
Building App Bundle Locally
{ cwd: '/Users/empl1/Documents/meteor/apps/carsinfo/carsinfo' }
{ [Error: spawn meteor ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn meteor',
  path: 'meteor',
  spawnargs: 
   [ 'build',
     '--directory',
     '/tmp/2d5190b5-dc96-4716-924a-d3716bcab8c1',
     '--architecture',
     'os.linux.x86_64',
     '--server',
     'http://localhost:3000' ] }

=> Build Error. Check the logs printed above.

//mup.js
`module.exports = {
  servers: {
    one: {
      host: 'ec2.ip.address',
      username: 'ubuntu',
      pem: "path-to-file.pem"
    }
  },

  meteor: {
    name: 'appname',
    path: '../appname',
    servers: {
      one: {}
    },
    env: {
      ROOT_URL: 'http://example.com',
      MONGO_URL: 'mongodb://link-provided-by-mongodb-cloud-provider'
    },
    deployCheckWaitTime: 60
  }
};`

**Comment by magp3** [comment]
@Fred-J Your path looks suspect. Do you really have a meteor project in ../appname? :)

**Comment by Fred-J** [comment]
OK. Got it. ../../appname fixed it. Thanks for that .

**Comment by janjackson** [comment]
I have the exact same error but triple checked my path, that's not it :( any help greatly appreciated

**Comment by w3jimmy** [comment]
Hi guys, I just had the same error and came here looking for help. 

My app's path was correct, but in my case I fixed the issue by changing the value of buildOptions.executable from './meteor' to 'meteor' in the mup settings file.

I was actually surprised, because my meteor version installed globally is exactly the same as the local meteor version (1.4.4.2).

I hope this helps someone else!
