### ISSUE TITLE
mup file included in production app (visible for everyone)

### ISSUE THREAD

**Issue by 33Fraise33** [zodern/meteor-up#376]
Hello,

Recently I created a few extra mup files to deploy to multiple servers with different settings. Now we noticed that these files are included into the production app online. So in fact everyone has access to our database now.

This is a huge vulnerability issue and should be resolved asap. My project structure is the following:

Project folder
 -> mup-default.js
 -> mup-beta.js
 -> settings.json

at the bottom of the website's source file there's literally this: require("./mup-default.js");

**Comment by albertonaperijr** [comment]
@stubbegianni Thanks for the info. I just noticed it too. This is a huge problem especially when you put your server password in **mup.js**  file. I hope this will be fix soon.

**Comment by 33Fraise33** [comment]
I think I have resolved the issue. Put your mup files inside a hidden folder (e.g. .mup) change the path to ../. of your project inside your mup files and run the mup command from inside the folder. 

that's why in the how to they mention 

`mkdir .deploy`

**Comment by albertonaperijr** [comment]
That's exactly what I did. I think that's the fix for now.

**Comment by abernix** [comment]
You shouldn't have your `mup.js` in the root of your application.  As with ANY Meteor `.js` file in the root of your app, it will be executed on the client and the server.  This is why the `server` and `client` directories exist.

As stated above, the instructions in the very first section of the README which explains how to use MUP (under ["Creating a Meteor Up Project"](https://github.com/kadirahq/meteor-up#creating-a-meteor-up-project)) explicitly say to create a `.deploy` directory.

Additionally, the default `mup.js` (and the one in the README) uses `../` as the location of the app to signify going up a level to find the app.  You must have changed this when you created your app, or not followed those instructions.

MUP could warn about this, but it can't fix it.  It's really a core concept of Meteor that you should have been aware of.

**Comment by 33Fraise33** [comment]
Well yes a warning wouldn't be bad. And we didn't read the readme completely as we changed from the old mup where the mup file was still a mup.json. Also in the readmy it is not specified why the mup file should be placed inside a .deploy folder. At the time it seemed more complicated to me and unnecessary. 

It would be a good idea to update the readme that it is strongly adviced to have the mup file in a .deploy folder for security reasons.

**Comment by abernix** [comment]
Agree! Submit a PR!  (Not my project!  Open Source!) 🙂
