### ISSUE TITLE
502 gateway error when accessing AWS S3 Browser Policy

### ISSUE THREAD

**Issue by CaptainChemist** [zodern/meteor-up#378]
Hi everyone,
I am having an issue with the BrowserPolicy package in conjunction with Meteor-up that I hope someone can help me identify. When I add certain policies, it will work perfectly locally but it produces a `502 Bad Gateway` error when I deploy to my website. This is an example s3 policy that gives me trouble:
`BrowserPolicy.content.allowOriginForAll('*.amazonaws.com');`
I am using meteor 1.4.2.3, node 7.1.0 and npm 4.0.2, but I was having this issue even with the older meteor version of 1.4.2. I am using the docker image `abernix/meteord:base`. I have also run into the 502 gateway error previously with the bootstrap cdn url but I was able to work around that by just hosting the font myself. 

If it is helpful, I am using my s3 to load images (jpg, svg). Clearing my browser cache or using a different browser does not help.

I have [read](https://github.com/meteorhacks/mup-frontend-server/issues/7) that this problem can be due to the header size being too large and that it can be fixed by changing `proxy_buffer_size 8k;` in the `/var/lib/docker/aufs/mnt/CHECKEDID/opt/nginx/conf/nginx.conf` file. Can anyone tell me how I can clone, modify, and publish a corrected `abernix/meteord:base` docker image? I am happy to make it publicly available for others, I just don't really understand how docker images work.

I checked a random svg file and the header size was 449 which is suspicious because when I compared the header size of a youtube embedded player which loads fine, that header size is 906 and there I used `BrowserPolicy.content.allowOriginForAll('www.youtube.com');` with no problems. Is it possible that this gateway error is something other than the header size?

Thanks so much!

**Comment by zodern** [comment]
@CaptainChemist did you find a solution?

**Comment by ivanthemeh** [comment]
@zodern @CaptainChemist did you?


its because these settings need to be added in the docker containers nginx server block 

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;

**Comment by Cu4rach4** [comment]
how we can solve this?, can we modified directly nginx, wish file needs to be modified?

Thnaks

**Comment by ivanthemeh** [comment]
I had to fork the github repo for jwilder/nginx-proxy then create an automated build on docker hub. Trigger the build and the go the the file at /src/modules/meteor/assets/templates/start.sh to reflect your docker hub repo. Don't forget to update your forked repo with config settings before triggering the automated build.

**Comment by zodern** [comment]
Mup 1.4 allows [customizing the nginx config](https://github.com/zodern/meteor-up/issues/475#issuecomment-363908889).

**Comment by pisacode** [comment]
try this https://stackoverflow.com/a/77419342/5069866
