### ISSUE TITLE
mup logs with custom mup.js file name

### ISSUE THREAD

**Issue by albertonaperijr** [zodern/meteor-up#379]
Hello,

I'd tried running `mup logs -f --tail=50` with custom mup.js file name (mup-staging.js) and it seems that it didn't find the mup-staging.js file.
I'd also tried running `mup logs -f --tail=50 --config=mup-staging.js` but it doesn't seems to be working.

Here's the error:

```
$ mup logs -f --tail=50 --config=mup-staging.js
[xxx.xxx.xxx.xxx]flag provided but not defined: --tail
[xxx.xxx.xxx.xxx]See 'docker --help'.
```

Is there any right command to do this?

Thanks.

**Comment by 33Fraise33** [comment]
Jup I just had the same problem:
`mup logs --config=mup-beta.js` gives the error: 
`[x.x.x.x]docker: '<appname>' is not a docker command.`

**Comment by 33Fraise33** [comment]
I am able to view the logs by logging into the webserver and typing: 
`docker logs <appname>
`

**Comment by albertonaperijr** [comment]
I did the same thing. I'm just hoping that there's a way without manually accessing the server.

**Comment by ilan-schemoul** [comment]
same problem

**Comment by masca88** [comment]
+1

**Comment by zodern** [comment]
`mup --config mup-staging.js logs -f --tail 50` works for me.

~~The config needs to be before `logs`.~~

**Comment by masca88** [comment]
Same problem also putting config before logs

**Comment by zodern** [comment]
> mup logs -f --tail=50 --config=mup-staging.js

`--tail=50` needs to be `--tail 50`

> Same problem also putting config before logs

Is your problem `flag provided but not defined: --tail` or `[x.x.x.x]docker: '<appname>' is not a docker command.`

**Comment by masca88** [comment]
My problem is [x.x.x.x]docker: '<appname>' is not a docker command.

**Comment by ilan-schemoul** [comment]
@zodern when there's a problem with mup it logs at the end `To see more logs type 'mup logs --tail=50'
` I think it explain why some try "mup logs -f --tail=50"

**Comment by zodern** [comment]
I have done some more testing, and it should work with --tail=50. Both errors have the same cause.
