### ISSUE TITLE
Errors during verification deployment

### ISSUE THREAD

**Issue by mzygmunt** [zodern/meteor-up#38]
I got a few errors during the verification of the deployment on different operating systems:

Under Centos 7 and Ubuntu 14.04:

> Started TaskList: Start Meteor
> [xxx.xxx.xxx.xxx] - Start Meteor
> [xxx.xxx.xxx.xxx] - Start Meteor: SUCCESS
> [xxx.xxx.xxx.xxx] - Verifying Deployment
> [xxx.xxx.xxx.xxx] x Verifying Deployment: FAILED
>        -----------------------------------STDERR-----------------------------------
>        d.
>        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
>        > fibers@1.0.5 install /bundle/bundle/programs/server/node_modules/fibers
>        > node ./build.js
>        `linux-x64-v8-3.14` exists; testing
>        Binary is fine; exiting
>        ansi-regex@0.2.1 node_modules/ansi-regex
>        ansi-styles@1.1.0 node_modules/ansi-styles
>        escape-string-regexp@1.0.3 node_modules/escape-string-regexp
>        chalk@0.5.1 node_modules/chalk
>        strip-ansi@0.3.0 node_modules/strip-ansi
>        supports-color@0.2.0 node_modules/supports-color
>        has-ansi@0.1.0 node_modules/has-ansi
>        eachline@2.3.3 node_modules/eachline
>        type-of@2.0.1 node_modules/type-of
>        amdefine@1.0.0 node_modules/amdefine
>        asap@2.0.3 node_modules/asap
>        underscore@1.5.2 node_modules/underscore
>        meteor-promise@0.5.0 node_modules/meteor-promise
>        promise@7.0.4 node_modules/promise
>        source-map-support@0.3.2 node_modules/source-map-support
>        semver@4.1.0 node_modules/semver
>        source-map@0.1.32 node_modules/source-map
>        fibers@1.0.5 node_modules/fibers
>        => Starting meteor app on port:80
>        -----------------------------------STDOUT-----------------------------------
>        To see more logs type 'mup logs --tail=50'
>        ----------------------------------------------------------------------------
> Error: 
> -----------------------------------STDERR-----------------------------------
> d.
> npm WARN package.json meteor-dev-bundle@0.0.0 No README data
> 
> fibers@1.0.5 install /bundle/bundle/programs/server/node_modules/fibers
> node ./build.js
> linux-x64-v8-3.14` exists; testing
> Binary is fine; exiting
> ansi-regex@0.2.1 node_modules/ansi-regex
> ansi-styles@1.1.0 node_modules/ansi-styles
> escape-string-regexp@1.0.3 node_modules/escape-string-regexp
> chalk@0.5.1 node_modules/chalk
> strip-ansi@0.3.0 node_modules/strip-ansi
> supports-color@0.2.0 node_modules/supports-color
> has-ansi@0.1.0 node_modules/has-ansi
> eachline@2.3.3 node_modules/eachline
> type-of@2.0.1 node_modules/type-of
> amdefine@1.0.0 node_modules/amdefine
> asap@2.0.3 node_modules/asap
> underscore@1.5.2 node_modules/underscore
> meteor-promise@0.5.0 node_modules/meteor-promise
> promise@7.0.4 node_modules/promise
> source-map-support@0.3.2 node_modules/source-map-support
> semver@4.1.0 node_modules/semver
> source-map@0.1.32 node_modules/source-map
> fibers@1.0.5 node_modules/fibers
> => Starting meteor app on port:80
> -----------------------------------STDOUT-----------------------------------
> ## To see more logs type 'mup logs --tail=50'
> 
>    at /Users/mzygmunt/Desktop/jakis/meteor-up/node_modules/nodemiral/lib/coreTasks.js:39:16
>    at /Users/mzygmunt/Desktop/jakis/meteor-up/node_modules/nodemiral/lib/session.js:146:9
>    at Channel.<anonymous> (/Users/mzygmunt/Desktop/jakis/meteor->up/node_modules/nodemiral/lib/ssh.js:125:9)
>    at emitOne (events.js:90:13)
>    at Channel.emit (events.js:182:7)
>    at SSH2Stream.<anonymous> (/Users/mzygmunt/Desktop/jakis/meteor->up/node_modules/ssh2/lib/Channel.js:124:14)
>    at SSH2Stream.g (events.js:273:16)
>    at emitNone (events.js:80:13)
>    at SSH2Stream.emit (events.js:179:7)
>    at parsePacket (/Users/mzygmunt/Desktop/jakis/meteor-up/node_modules/ssh2->streams/lib/ssh.js:3435:10)
>    at SSH2Stream._transform (/Users/mzygmunt/Desktop/jakis/meteor-up/node_modules/ssh2->streams/lib/ssh.js:552:13)
>    at SSH2Stream.Transform._read (_stream_transform.js:166:10)
>    at SSH2Stream._read (/Users/mzygmunt/Desktop/jakis/meteor-up/node_modules/ssh2->streams/lib/ssh.js:213:15)
>    at SSH2Stream.Transform._write (_stream_transform.js:154:12)
>    at doWrite (_stream_writable.js:292:12)
>    at writeOrBuffer (_stream_writable.js:278:5)

Under Debian 7 and Debian 8:

> Started TaskList: Start Meteor
> [51.255.41.243] - Start Meteor
> [51.255.41.243] - Start Meteor: SUCCESS
> [51.255.41.243] - Verifying Deployment
> [51.255.41.243] x Verifying Deployment: FAILED
>        -----------------------------------STDERR-----------------------------------
>        WARN deprecated 
>        npm WARN deprecated To upgrade to the latest stable version, run:
>        npm WARN deprecated 
>        npm WARN deprecated   npm -g install npm@latest
>        npm WARN deprecated 
>        npm WARN deprecated (Depending on how Node.js was installed on your system, you
>        npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
>        npm WARN deprecated on Windows, run them from an Administrator prompt.)
>        npm WARN deprecated 
>        npm WARN deprecated If you're running the version of npm bundled with
>        npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
>        npm WARN deprecated will be bundled with a version of npm@2, which has some small
>        npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
>        npm WARN deprecated semver behavior.
>        npm WARN package.json meteor-dev-bundle@0.0.0 No description
>        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
>        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
>        => Starting meteor app on port:80
>        -----------------------------------STDOUT-----------------------------------
>        To see more logs type 'mup logs --tail=50'
>        ----------------------------------------------------------------------------
> Error: 
> -----------------------------------STDERR-----------------------------------
> WARN deprecated 
> npm WARN deprecated To upgrade to the latest stable version, run:
> npm WARN deprecated 
> npm WARN deprecated   npm -g install npm@latest
> npm WARN deprecated 
> npm WARN deprecated (Depending on how Node.js was installed on your system, you
> npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
> npm WARN deprecated on Windows, run them from an Administrator prompt.)
> npm WARN deprecated 
> npm WARN deprecated If you're running the version of npm bundled with
> npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
> npm WARN deprecated will be bundled with a version of npm@2, which has some small
> npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
> npm WARN deprecated semver behavior.
> npm WARN package.json meteor-dev-bundle@0.0.0 No description
> npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
> npm WARN package.json meteor-dev-bundle@0.0.0 No README data
> => Starting meteor app on port:80
> -----------------------------------STDOUT-----------------------------------
> ## To see more logs type 'mup logs --tail=50'
> 
>    at /Users/mzygmunt/Desktop/jakis/meteor-up/node_modules/nodemiral/lib/coreTasks.js:39:16
>    at /Users/mzygmunt/Desktop/jakis/meteor-up/node_modules/nodemiral/lib/session.js:146:9
>    at Channel.<anonymous> (/Users/mzygmunt/Desktop/jakis/meteor->up/node_modules/nodemiral/lib/ssh.js:125:9)
>    at emitOne (events.js:90:13)
>    at Channel.emit (events.js:182:7)
>    at SSH2Stream.<anonymous> (/Users/mzygmunt/Desktop/jakis/meteor->up/node_modules/ssh2/lib/Channel.js:124:14)
>    at SSH2Stream.g (events.js:273:16)

**Comment by madushan1000** [comment]
It seems like your app is properly starting but mup sends a timeout error because it takes more time to start web interface than `deployCheckWaitTime`. Try increasing it. (Checkout the code from this PR https://github.com/kadirahq/meteor-up/pull/41)
Note, the `mup.js` format has changed a bit.
```javascript 
module.exports = {
  servers: {
    one: {
      host: '162.243.19.238',
      user: 'root'
    }
  },

  meteor: {
    name: 'Telescope',
    path: '../Telescope',
    servers: {
      one: {}, two: {}, three: {}
    },
    env: {
      ROOT_URL: 'http://162.243.19.238',
      MONGO_URL: 'mongodb://localhost/meteor'
    },
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
  setupMongo: 1,
  deployCheckWaitTime: 20
};
```

**Comment by mzygmunt** [comment]
Still error:

>MBP-Mateusz:test3 mzygmunt$ mup deploy
>Bulding App Bundle Locally

>Started TaskList: Pushing Meteor
>[178.62.22.101] - Pushing Meteor App Bundle to The Server
>[178.62.22.101] - Pushing Meteor App Bundle to The Server: SUCCESS
>[178.62.22.101] - Pushing the Startup Script
>[178.62.22.101] - Pushing the Startup Script: SUCCESS

>Started TaskList: Configuring  Meteor Environment Variables
>[178.62.22.101] - Sending Environment Variables
>[178.62.22.101] - Sending Environment Variables: SUCCESS

>Started TaskList: Start Meteor
>[178.62.22.101] - Start Meteor
>[178.62.22.101] - Start Meteor: SUCCESS
>[178.62.22.101] - Verifying Deployment
>[178.62.22.101] x Verifying Deployment: FAILED
        
>        -----------------------------------STDERR-----------------------------------
>        u're running the version of npm bundled with
>        npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
>        npm WARN deprecated will be bundled with a version of npm@2, which has some small
>        npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
>        npm WARN deprecated semver behavior.
>        npm WARN package.json meteor-dev-bundle@0.0.0 No description
>        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
>        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
>        => Starting meteor app on port:80
        
>        /bundle/bundle/programs/server/node_modules/fibers/future.js:245
>                                                        throw(ex);
                                                              ^
>        ReferenceError: module is not defined
>            at mup.js:1:1
>            at /bundle/bundle/programs/server/app/mup.js:39:4
>            at /bundle/bundle/programs/server/boot.js:242:10
>            at Array.forEach (native)
>            at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
>            at /bundle/bundle/programs/server/boot.js:137:5
>        -----------------------------------STDOUT-----------------------------------
        
>        To see more logs type 'mup logs --tail=50'
        
>----------------------------------------------------------------------------
>    at /Users/mzygmunt/Desktop/custom_npm/meteor-up/node_modules/nodemiral/lib/coreTasks.js:39:16
>    at /Users/mzygmunt/Desktop/custom_npm/meteor-up/node_modules/nodemiral/lib/session.js:146:9
>    at Channel.<anonymous> (/Users/mzygmunt/Desktop/custom_npm/meteor-up/node_modules/nodemiral/lib/ssh.js:125:9)
>    at emitOne (events.js:90:13)
>    at Channel.emit (events.js:182:7)
>    at SSH2Stream.<anonymous> (/Users/mzygmunt/Desktop/custom_npm/meteor-up/node_modules/ssh2/lib/Channel.js:124:14)
>    at SSH2Stream.g (events.js:273:16)
>    at emitNone (events.js:80:13)
>    at SSH2Stream.emit (events.js:179:7)
>    at parsePacket (/Users/mzygmunt/Desktop/custom_npm/meteor-up/node_modules/ssh2-streams/lib/ssh.js:3435:10)
>    at SSH2Stream._transform (/Users/mzygmunt/Desktop/custom_npm/meteor-up/node_modules/ssh2-streams/lib/ssh.js:552:13)
>    at SSH2Stream.Transform._read (_stream_transform.js:166:10)
>    at SSH2Stream._read (/Users/mzygmunt/Desktop/custom_npm/meteor-up/node_modules/ssh2-streams/lib/ssh.js:213:15)
>    at SSH2Stream.Transform._write (_stream_transform.js:154:12)
>    at doWrite (_stream_writable.js:292:12)
>    at writeOrBuffer (_stream_writable.js:278:5)

In addition, after command "mup init" meteor return error:
>20160125-21:55:17.017(1)? (STDERR) 
>W20160125-21:55:17.018(1)? (STDERR) /Users/mzygmunt/.meteor/packages/meteor->tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
>W20160125-21:55:17.018(1)? (STDERR) 						throw(ex);
>W20160125-21:55:17.018(1)? (STDERR) 						      ^
>W20160125-21:55:17.023(1)? (STDERR) ReferenceError: module is not defined
>W20160125-21:55:17.023(1)? (STDERR)     at mup.js:1:1
>W20160125-21:55:17.023(1)? (STDERR)     at >/Users/mzygmunt/Desktop/meteor_apps/test3/.meteor/local/build/programs/server/app/mup.js:39:4
>W20160125-21:55:17.023(1)? (STDERR)     at >/Users/mzygmunt/Desktop/meteor_apps/test3/.meteor/local/build/programs/server/boot.js:242:10
>W20160125-21:55:17.023(1)? (STDERR)     at Array.forEach (native)
>W20160125-21:55:17.023(1)? (STDERR)     at Function._.each._.forEach >(/Users/mzygmunt/.meteor/packages/meteor->tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt->os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
>W20160125-21:55:17.023(1)? (STDERR)     at >/Users/mzygmunt/Desktop/meteor_apps/test3/.meteor/local/build/programs/server/boot.js:137:5
>=> Exited with code: 8

My configuration:
Dev machine:
OSX El Capitan, Node v5.5.0, NPM v3.5.3
Production machine: clear Ubuntu 14.04 x64 vmlinuz-3.13.0-71-generic from DigitalOcean

**Comment by mnmtanish** [comment]
Hi @mzygmunt,
Is the `mup.js` file inside your meteor app directory? If it is, that might be the problem.
Please move it outside or use a hidden directory. Example: `.deploy/mup.js`

**Comment by madushan1000** [comment]
@mzygmunt Can you post your mup.js file here? Take a look at the referance again, I changed it a bit again.

**Comment by mzygmunt** [comment]
Thank you for your answers. @mnmtanish you're right! It helped me a lot. But some errors were related with a damaged version of Node. Complete reinstallation Node definitively resolved the issue.

**Comment by wanglian** [comment]
@mzygmunt I came cross the same problem. Can you explain a little bit about how to reinstall Node? It seems it's not necessary to install Node by myself.

**Comment by mikeifomin** [comment]
I have the same. 
Add `deployCheckWaitTime: 60` helped

**Comment by prawee** [comment]
working for me  deployCheckWaitTime: 120
