### ISSUE TITLE
Setup OK; Deploy OK; But can't access app

### ISSUE THREAD

**Issue by ifalldev** [zodern/meteor-up#381]
Hi, I'm trying to deploy my app to DigitalOcean in a droplet using Ubuntu 16.04.

`mup setup` and `mup deploy` ran ok.

In my droplet docker seems good(to me):

```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                        NAMES
c97df00753d6        abernix/meteord:base   "/bin/sh -c 'bash $ME"   14 hours ago        Up 14 hours         0.0.0.0:80->80/tcp           Geekble
8f4cb27bf786        mongo                  "/entrypoint.sh mongo"   18 hours ago        Up 18 hours         127.0.0.1:27017->27017/tcp   mongodb
```

But when I try to access my app through the browser (w/ URL or IP), I get nothing but the 'can't access' warning. And when I try with curl the return is `Failed to connect (...): Connection refused`.

with `mup logs -f` the end of log is:

```
=> Starting meteor app on port:80
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run
meteor npm install --save bcrypt
in the root directory of your application.
```

This is my `mup.js`

```
module.exports = {
  servers: {
    one: {
      host: 'xxx.xxx.xx.xx',
      username: 'root',
      // pem:
      password: 'xxxxxxx',
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'Geekble',
    path: '../',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://xxxxxx.com/',
      MONGO_URL: 'mongodb://localhost/meteor'
    },

    //dockerImage: 'kadirahq/meteord',
    dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

I would appreciate some help! Thank you guys!

**Comment by ifalldev** [comment]
'Fixed it'.

I don't know why but I deployed my app again, and I stopped and started my container manually and it ran ok.

Its as crazy as it sounds.

**Comment by guillim** [comment]
I have the exact same issue. any additional feedbacks you could add to troubleshoot this ?

my config is almost the same: DigitalOcean in a droplet using Ubuntu 16.04 and:
```
module.exports = {
  servers: {
    one: {
      host: 'xxx.xxx.xxx.xxx',
      username: 'xxxx',
      pem:'/Users/xxxx/.ssh/xxx,
    }
  },

  meteor: {
    name: 'todos',
    path: '/Users/xxx/projectname',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://websitename.com',
      MONGO_URL: 'mongodb://localhost/meteor',
    },

    dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 120
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by ifalldev** [comment]
Hi @guillim! 

It wasn't me who created the droplet and it was gave to me with LAMP and a little trouble which was that the _DNS pointing to wrong IP_.

LAMP was not a big challenge, _I just turned Apache off_.

About the DNS it's confusing because I always tested the connection with the URL and IP without success.

After my last test I noticed that accessing IP returned ok, but the URL did not, so I found that the pointing was wrong. 

But just before I was about to _put docker to another port_ (3000) and use Nginx to link :80 to that, I was just trying to turn the app on anyway.

So while doing that I changed the container port from 80->80 to 3000->80 and then put 3000->80 to 80->80 back. I don't know why but when I returned to 80->80, it worked ok.

I hope this can help you anyway.

**Comment by guillim** [comment]
Tks for your response.
I had actually an issue on a forced redirection from https to http that an underlaying package was doing. It is commented on the issue i opened and closed afterwards. (attached to this issue BTW)

But I spent a lot of time at the begining modifying nginx.conf cause I thought it came from that !
