### ISSUE TITLE
meteor-up deploy failed to start the app assert.js:93

### ISSUE THREAD

**Issue by Fred-J** [zodern/meteor-up#382]
Developing this 1.4.2.3 Meteor App on local mac machine and using the latest meteor-up to deploy to AWS EC2 ubuntu 16.04.

on the local machine:
meteor node -v => v4.6.2
node -v => v5.5.0

mup setup went all good, mup deploy almost there with the following errors:

.deploy$mup logs --tail=
    []    at wrapPathFunction (/bundle/bundle/programs/server/mini-filesjs:77:)
    []    at Object<anonymous> (/bundle/bundle/programs/server/mini-filesjs:8:)
    []    at Module_compile (modulejs:6:6)
    []    at ObjectModule_extensionsjs (modulejs:7:)
    []    at Moduleload (modulejs:6:)
    []    at FunctionModule_load (modulejs::)
    []    at Modulerequire (modulejs:6:7)
    []    at require (modulejs:8:7)
    []    at Object<anonymous> (/bundle/bundle/programs/server/bootjs::)
    []    at Module_compile (modulejs:6:6)
    []npm WARN deprecated This version of npm lacks support for important features,
    []npm WARN deprecated such as scoped packages, offered by the primary npm
    []npm WARN deprecated registry Consider upgrading to at least npm@, if not the
    []npm WARN deprecated latest stable version To upgrade to npm@, run:
    []npm WARN deprecated 
    []npm WARN deprecated   npm -g install npm@latest-
    []npm WARN deprecated 
    []npm WARN deprecated To upgrade to the latest stable version, run:
    []npm WARN deprecated 
    []npm WARN deprecated   npm -g install npm@latest
    []npm WARN deprecated 
    []npm WARN deprecated (Depending on how Nodejs was installed on your system, you
    []npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
    []npm WARN deprecated on Windows, run them from an Administrator prompt)
    []npm WARN deprecated 
    []npm WARN deprecated If you're running the version of npm bundled with
    []npm WARN deprecated Nodejs  LTS, be aware that the next version of  LTS
    []npm WARN deprecated will be bundled with a version of npm@, which has some small
    []npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
    []npm WARN deprecated semver behavior
    []npm WARN packagejson meteor-dev-bundle@ No description
    []npm WARN packagejson meteor-dev-bundle@ No repository field
    []npm WARN packagejson meteor-dev-bundle@ No README data
    []npm WARN cannot run in wd meteor-dev-bundle@ node npm-rebuildjs (wd=/bundle/bundle/programs/server)
    []=> Starting meteor app on port:80
    []
    []assertjs:
    []  throw new assertAssertionError({
    []        ^
    []AssertionError: "undefined" === "function"
    []    at wrapPathFunction (/bundle/bundle/programs/server/mini-filesjs:77:)
    []    at Object<anonymous> (/bundle/bundle/programs/server/mini-filesjs:8:)
    []    at Module_compile (modulejs:6:6)
    []    at ObjectModule_extensionsjs (modulejs:7:)
    []    at Moduleload (modulejs:6:)
    []    at FunctionModule_load (modulejs::)
    []    at Modulerequire (modulejs:6:7)
    []    at require (modulejs:8:7)
    []    at Object<anonymous> (/bundle/bundle/programs/server/bootjs::)
    []    at Module_compile (modulejs:6:6)
    .deploy$

//mup.js

```javascript
module.exports = {
  servers: {
    one: {
      host: '1.2.3.4',
      username: 'ubuntu',
      pem: "../path/to/file/myKey.pem"
    }
  },

  meteor: {
    name: 'example',
    path: '../../example',
    servers: {
      one: {}
    },
    env: {
      ROOT_URL: 'http://example.com',
      MONGO_URL: 'mongodb://username:password@cluster0-shard-00-00-oko1k.mongodb.net:27017,cluster0-shard-00-01-oko1k.mongodb.net:27017,cluster0-shard-00-02-oko1k.mongodb.net:27017/myDB?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin'
    },
    deployCheckWaitTime: 60
  }
};
```

**Comment by abernix** [comment]
You need to change the `docker` `image` defined in the `mup.js` for apps using Meteor >= 1.4.  See the [Example File](https://github.com/kadirahq/meteor-up#example-file) in the README which shows the correct use of `abernix/meteord:base`.

A [search on existing issues](https://github.com/kadirahq/meteor-up/issues?utf8=%E2%9C%93&q=is%3Aissue%20AssertionError) before opening this would have brought you to many similar issues which answer this.
