### ISSUE TITLE
CPU stuck at 100%

### ISSUE THREAD

**Issue by SachaG** [zodern/meteor-up#384]
I'm running into a weird issue where my CPU gets stuck at 100%. That in itself isn't so weird, and can happen for a number of reasons. But the problem is that even when I do `mup restart`, manually kill node, or reboot my Digital Ocean droplet, it doesn't change anything and the CPU goes right back to 100%…

Any idea what's going on, and what I could do to at least reset it back down to 0?

**Comment by codingwaysarg** [comment]
Same issue here

**Comment by zodern** [comment]
Did either of you find what was causing this?

**Comment by SachaG** [comment]
I'm not 100% sure, but my problem may have been due to all connected users reconnecting at the same time after a restart. I don't think mup includes a way to do stagged restarts, but Galaxy does fyi.

**Comment by ostrowr** [comment]
I'm also running into this issue - also on DigitalOcean. No problem at all when running locally. I don't know if it's a mup problem or if it's somehow related to meteor itself a la https://forums.meteor.com/t/meteor-bundle-on-production-100-cpu/30837

This is happening on what should be a mostly idle server with only me connected, so I don't think @SachaG's explanation applies here.

**Comment by shadowcodex** [comment]
@ostrowr Can you look at `top` or `htop` and find out what is using all the CPU? Is it really meteor?

**Comment by ostrowr** [comment]
@shadowcodex `top` says node, and `docker stats` has the meteor container at 10x% cpu. But I'm not able to replicate right now for some reason - I'll let you know what I can puzzle out if I run into this issue again.
