### ISSUE TITLE
Setup OK; Deploy OK; can't access: xxxx.com refused to connect... https issue ?

### ISSUE THREAD

**Issue by guillim** [zodern/meteor-up#388]
Configuration: DigitalOcean in a droplet using Ubuntu 16.04

Setup OK
Deploy OK
no pb in the logs
dockers look good as well

THE ISSUE IS: when I try to reach the app from my browser typing "http://mywebsitename.com" I get redirected to "https://mywebsitename.com"  and i got an issue like "mywebsitename.com refused to connect."

Note: I have a similar issue as [ifalldev](https://github.com/kadirahq/meteor-up/issues/381) but it wasn't solved really and was closed. 

For info, here is my conf file:
```
module.exports = {
  servers: {
    one: {
      host: 'xxx.xxx.xxx.xxx',
      username: 'xxxx',
      pem:'/Users/xxxx/.ssh/xxx,
    }
  },

  meteor: {
    name: 'todos',
    path: '/Users/xxx/projectname',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://websitename.com/',
      MONGO_URL: 'mongodb://localhost/meteor',
    },

    dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by guillim** [comment]
if it can help, here are what my dockers look like:

```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                        NAMES
429f2b2c3746        abernix/meteord:base   "/bin/sh -c 'bash $ME"   37 minutes ago      Up 37 minutes       0.0.0.0:80->80/tcp           todos
f4e92cd0af78        mongo                  "/entrypoint.sh mongo"   39 minutes ago      Up 39 minutes       127.0.0.1:27017->27017/tcp   mongodb
```

**Comment by guillim** [comment]
Found out: 
I was actually testing on the todos list example from Meteor. I didn't know that it was relying on force-ssl package.

I deleted this package from the project on my computer, and then mup deploy worked fine. I could access the project straight on "http://mywebsitename.com" without the https redirection !

**Comment by achirkof** [comment]
For somebody who may also faced same problem:
In my case root cause of force redirection from `http` to `https` was meteor package **force-ssl**. I spend a day to find a cause because in development mode it is not appear.
