### ISSUE TITLE
Copying SSL Certificate Bundle: FAILED, no such file or directory

### ISSUE THREAD

**Issue by fisherman818** [zodern/meteor-up#389]
Hi all,

When I 

> mup setup

, it keep showing this issues: 

> Copying SSL Certificate Bundle: FAILED
> 	ENOENT: no such file or directory, open '/etc/letsencrypt/live/domain.com/fullchain.pem

The **mup.js**
    ssl: {
      port: 443,
      crt: '/etc/letsencrypt/live/domain.com/fullchain.pem',
      key: '/etc/letsencrypt/live/domain.com/privkey.pem'
    },

Any idea how to solve the problem?

Thanks!!!

**Comment by gaillota** [comment]
You forget to add `upload: false` in the `ssl` config
