### ISSUE TITLE
How to call scripts present outside container?

### ISSUE THREAD

**Issue by nitinkumarmedia** [zodern/meteor-up#392]
Hi,

Our application is using some scripts which is written in Python and staying at /var/www/example.py. These files are using sys logs and doing some major work on system level. I need to execute those scripts from application. We can't keep those scripts within the container. Older version of mup was not using meteor and hence we were good to call those scripts. But now, application is within the container and it doesn't recognize those scripts. How can we call those scripts without much of hacks?

Regards,
Nitin

**Comment by zodern** [comment]
You can try mounting them as volumes. The example file in the readme shows how to do that.
