### ISSUE TITLE
[Question] Use custom name for database

### ISSUE THREAD

**Issue by cyclops24** [zodern/meteor-up#393]
Hi guys,
I want to use a custom database name for my deploy process but my mup always generate db with name same as app name in mup.js.
Please help me to set custom db name for my app.

**Comment by maxmatthews** [comment]
Take a look at this config file:
```
module.exports = {
	servers: {
		one: {
			host: 'myserver.com',
			username: 'myusername',
			pem: '/path/to/cert'
		}
	},
	setupMongo: false,
	meteor: {
		name: 'myProject',
		path: '/my/project/path',
		servers: {
			one: {}
		},
		env: {
			PORT: 3000,
			ROOT_URL: 'https://mysite.com',
			MONGO_URL: 'mongodb://databaseIP:27017/databaseName'
		},
		dockerImage: 'abernix/meteord:base', //temp necessary for meteor 1.4
		deployCheckWaitTime: 60
	},
};
```
specifically this line: `MONGO_URL: 'mongodb://databaseIP:27017/databaseName'`
Just change the databaseIP, the port if necessary, then add a slash and change the database name to the one of your choosing. 

Note that with `setupMongo` set to `false` you'll have to set up the database yourself.
