### ISSUE TITLE
How to add dependencies in Docker Container 

### ISSUE THREAD

**Issue by anshul-budhiraja** [zodern/meteor-up#394]
Hi,

I recently moved my application from old mup to new mup which contains the application in docker. Earlier I faced issue to access the files outside the docker. I resolved this issue by mounting my folder as container via --volume option of mup.js.  Now I am able to access the files from the location I want but facing the dependencies issue. 

For example error is "ImportError: No module named MySQLdb". 

Not sure but might be Dockerfile can help me. I don't know how to use it with meteor. I am new to Docker.

When my application was out of docker all my python script were working fine but now no :(
@arunoda can you please help me asap.

**Comment by bensventures** [comment]
Sorry if this comes a bit late but here are some ideas. 

I think what might be happening is that the docker image you are using to run the app does not have that particular dependency you need. 

I am no Docker expert but as far as I understand, docker images are like mini operating systems, a bundle with all the things you need but nothing else. By default `meteor-up` uses a specific image built for Meteor and it is very likely that it does not have the MYSQL dependency.

One option would be for you to build your own custom image based on the one used by `meteor-up`, or better still, based on the one most people must use now with meteor 1.4: https://hub.docker.com/r/abernix/meteord/

You can then specify your own image in the config:
```
meteor : {
...
    docker: {
            image: 'abernix/meteord:base'
    },
... 
}
```

I have never built my own image so you'll have to do some research on that but I am hoping it is fairly straight forward.

Good luck.

**Comment by anshul-budhiraja** [comment]
I have already resolved my issue. Thanks for the response.
