### ISSUE TITLE
[Feature Request] 'mup undeploy' app command

### ISSUE THREAD

**Issue by cyclops24** [zodern/meteor-up#395]
First thanks for your awesome tools.
Please add a MUP command for completely delete an app and it mongodb data, will be very useful.

Usage Example:

```
mup undeploy
```

Related Issues:
[[Question] Remove app deployed with mup completely](https://github.com/kadirahq/meteor-up/issues/374)

**Comment by zodern** [comment]
In mup 1.5, there is a new `mup meteor destroy` command to remove the app. It does not remove the mongo data. To do that, you need to run `mup mongo stop` and delete `/opt/mongodb`, though please note that all apps deployed by mup on that server share the same mongodb folder.

**Comment by philipmjohnson** [comment]
Quick note for others who come across this issue:

In addition to deleting `/opt/mongodb`, you also need to delete `/var/lib/mongodb` in order to completely remove mup's Mongo installation.
