### ISSUE TITLE
**** It seems this project is Dead ****

### ISSUE THREAD

**Issue by cyclops24** [zodern/meteor-up#396]
Hi guys it seems this project is dead please join us to talk about MUP alternatives here:
[MUP OR PM2-Meteor OR any other deployment tools after lost arunoda and kadira?](https://forums.meteor.com/t/mup-or-pm2-meteor-or-any-other-deployment-tools-after-lost-arunoda-and-kadira/31845)

**Comment by wiserweb** [comment]
This project is not dead. It works quite well. It just needs a new maintainer.

**Comment by guillim** [comment]
@wiserweb is right Indeed. It takes some time and troubleshooting to make it work, but works great afterwards !

**Comment by cyclops24** [comment]
@wiserweb new mup version (this repo based on docker) has a lot of bug or limitation. I suggest you to check [PM2-Meteor](https://github.com/andruschka/pm2-meteor) for more stable deployment tool.

**Comment by bensventures** [comment]
I've been using mupx and now this mup for the past year and a half and even if it was sometimes a bit tricky to get to work with meteor updates, it has been a great tool. 

Having the choice between a few tools is always good. PM2-Meteor is a great project, and I hope the maintainers keep it going but I like how mup works and I'm hoping to continue using it for as long as possible.

But we can't ignore the fact that Kadira is phasing out its support. Has anyone forked this and is ready to take over? I don't think I can cope being the owner of the project but I would happily contribute to it as it is essential to my deploy strategy and my company.

**Comment by distalx** [comment]
Thanks @zodern for taking over,  can this be closed?
