### ISSUE TITLE
how to set up a persistent files folder/directory

### ISSUE THREAD

**Issue by kenshinman** [zodern/meteor-up#399]
Hi, I'm finally getting a hang of this new version. Used to use the mupx version so I'm like a first time user here, Please how can I set up a persistent uploads folder. With mupx, after every build, the uploaded files get deleted, but i think with this new version there is a way around it. Please how can i go about this? Thanks

**Comment by albertonaperijr** [comment]
You can do that by declaring `volumes` with the `host path` and `container path` in your `mup.js` file just like the example in `README.md`.

**E.g.**

```
volumes: { // lets you add docker volumes (optional)
    "/host/path": "/container/path", // passed as '-v /host/path:/container/path' to the docker run command
    "/second/host/path": "/second/container/path"
}
```

**Comment by kenshinman** [comment]
@albertonaperijr Thanks. So, how will I reference this location from within my deployed app. Thanks. Sorry for the funny questions, I'm actually new to this 👍

**Comment by albertonaperijr** [comment]
**E.g.** you want to save files inside `/var/uploads` directory on your host server. You can declare it as `'/var/uploads': '/var/uploads'`.
So what if you want to save files inside `/var/uploads` directory on your host server but your meteor app is setup to save files inside `/uploads` directory. You can declare it as `'/var/uploads': '/uploads'`.

**Note:** Based on my observation/experience in using `docker volume`. I always declared the same directory/path on both `host path` and `container path` just like the example above `'/var/uploads': '/var/uploads'`.

**Comment by kenshinman** [comment]
Hi, all a kinda new issue here I have deployed the app and from the logs
`$ mup deploy --config mup-config.js
Building App Bundle Locally
Started TaskList: Pushing Meteor
[138.197.79.81] - Pushing Meteor App Bundle to The Server
[138.197.79.81] - Pushing Meteor App Bundle to The Server: SUCCESS
[138.197.79.81] - Pushing the Startup Script
[138.197.79.81] - Pushing the Startup Script: SUCCESS`

Here is my mup.-config.js file

`module.exports = {
    servers: {
        one: {
            "host": "138.197.79.81",
            "username": 'root',
            "pem": "C:/Users/KenshinMan.DESKTOP-PU4PNV5/.ssh/id_rsa",
            opts: {
                port: 22,
            },
            // password:
            // or leave blank for authenticate from ssh-agent
        }
    },

    meteor: {
        name: 'sesewa',
        path: 'C:/projects/meteor/sesewa',
        volumes: { // lets you add docker volumes (optional)
            "/var/uploads": "/var/uploads", // passed as '-v /host/path:/container/path' to the docker run command
            //"/second/host/path": "/second/container/path"
        },
        docker: {
            //image: 'kadirahq/meteord', // (optional)
            image: 'abernix/meteord:base', // use this image if using Meteor 1.4+
        },
        servers: {
            one: {}
        },
        buildOptions: {
            serverOnly: true,
        },
        env: {
            "PORT": 22,
            "ROOT_URL": "http://138.197.79.81/"
        },

        //dockerImage: 'kadirahq/meteord'
        deployCheckWaitTime: 60
    }
};`

it shows that deployment was successful, but when i visit the IP address, the app does not load. Just like there was no deployment. any suggestions on how to make it work?

Like I mentioned earlier, I used mupx before now and it worked

**Comment by albertonaperijr** [comment]
I guess the issue is with your `env` port declaration. I think you cannot use `port 22`. You can change it to `port 80` or any port you want to use.

**E.g.**

```
env: {
    "PORT": 80,
    "ROOT_URL": "http://138.197.79.81/"
}
```

**Comment by kenshinman** [comment]
@albertonaperijr same thing after i tried this. I guess it's because I'm using meteor 1.4.2.3,
Let me revert to 1.3.5.1 if it will work. Thanks

**Comment by zodern** [comment]
The documentation for 1.5 will include a section on volumes.
