### ISSUE TITLE
New for deploying on my own hardware!

### ISSUE THREAD

**Issue by thearabbit** [zodern/meteor-up#40]
Excuse me, I am new for deploying to production.
Now I created `POS System`, and then I would like to deploy to my own hardware (Dell i5, Ram 8).
Please tell me for pre requirement:
- OS: Window/Ubuntu
  -..............
  (Sorry if I issue out of this package, because I am not sure how to use `MUP`)
  Thanks for your reply.

**Comment by madushan1000** [comment]
Meteor Up currently only supports deploy to Ubuntu 14.04 LTS servers. If you have that ubuntu version on your hardware, you'll definatly be able to deploy. And this repo is the devellopment version of meteor-up (not usable yet) you should probably post your issues at  the stable repo (https://github.com/arunoda/meteor-up)

**Comment by thearabbit** [comment]
Thanks for your reply.
I will check.
