### ISSUE TITLE
ENOENT while running mup deploy from a Bitbucket pipeline

### ISSUE THREAD

**Issue by kaamodt** [zodern/meteor-up#403]
Hi!

I have used mup for years, but I have always just deployed from my local environment. Now, I am trying to deploy a meteor app to a Digital Ocean droplet from a Bitbucket pipeline, but I am having troubles.

The error I get from mup is:
```Building App Bundle Locally
{ cwd: '/opt/atlassian/pipelines/agent/build' }
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
```
From googling I believe this could be caused by that the path or file does not exist or is malformed. I have used `pwd` in order to find the path and it is `/opt/atlassian/pipelines/agent/build` which to me seems to match the path in the error message above. `{ cwd: '/opt/atlassian/pipelines/agent/build' }` 

Does anyone have a successful Bitbucket Pipeline running that deploys a meteor app with mup or have any idea on what is going on here and could help me?

My pipeline configuration for now (which kind of shows the steps I have tried for getting it to work):
```image: kadirahq/meteord

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mkdir -p ~/.ssh
          - ls
          - pwd
          - cd .deploy
          - cat my_known_hosts >> ~/.ssh/known_hosts
          - cat id_rsa.pub >> ~/.ssh/id_rsa.pub
          - (umask 077; echo $SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
          - npm install -g mup@1.0.4
          - npm install -g ssh2
          - mup deploy```

**Comment by zodern** [comment]
@kaamodt did you find a solution?

**Comment by kaamodt** [comment]
@zodern No, I did not. For now I have given up and I am still doing manual deploys from my local environment. Have you encountered a simular issue?

**Comment by zodern** [comment]
No. I am trying to identify which open issues still need to be solved.

It looks like your configuration was missing a step to install meteor.

**Comment by kaamodt** [comment]
If I understand you correctly I need to install meteor in the pipeline (bitbucket) in order to deploy a Meteor app?

**Comment by zodern** [comment]
Yes. It uses the `meteor build` command to build the app when deploying.

**Comment by kaamodt** [comment]
Ok. I will try that out when I am front of my computer and report back.

**Comment by zodern** [comment]
Two things MUP can do to improve this in the future:
- [x] give a better error message when `meteor` is not installed
- [ ] Add a section on deploying from CI and document that `meteor` needs to be installed.

**Comment by kaamodt** [comment]
@zodern Installing meteor as part of the pipeline did the trick :) Thanks for your help. This is the new pipeline for Bitbucket that I have working now

```image: kadirahq/meteord

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mkdir -p ~/.ssh
          - curl https://install.meteor.com/ | sh
          - export METEOR_ALLOW_SUPERUSER=true
          - cd .deploy
          - cat my_known_hosts >> ~/.ssh/known_hosts
          - cat id_rsa.pub >> ~/.ssh/id_rsa.pub
          - (umask 077; echo $SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
          - npm install -g mup@1.0.4
          - npm install -g ssh2
          - mup deploy
```

As you can see I had to install meteor as well as setting the `METEOR_ALLOW_SUPERUSER` env var. It turns out I had thought of installing meteor earlier. A detail that I had not included in my original issue were which Docker image I based my pipeline from. It is the 'kadirahq/meteord'. It has been awhile, so I had forgotten. Where I failed was assuming that the 'meteor' command is available (by default) inside that Docker image. 

As for your last comment. Yes, a better error message/validation of requirements would be appreciated! I am not sure if deploying with mup from a CI (or CDelivery pipeline as I would call it :)) is "best practice" or not. I was familiar with the tool, so I thought it easiest just to continue using it from the Bitbucket pipeline as well. I would expect there to be differences when deploying from other CD pipelines out there.

Thanks again for your help. This issue can be closed.

**Comment by SimonatoLucaManuele** [comment]
I would share with you this docker and pipelines that works for me.

Meteor installation and mup installation are set inside Dockerfile. I'm not a pro in docker so feel free to try and modify it.

Docker - simonatoluca/bitbucket-pipelines-mup - [link](https://hub.docker.com/r/simonatoluca/bitbucket-pipelines-mup/)

Pipelines
````
image: simonatoluca/bitbucket-pipelines-mup

pipelines:
  default:
    - step:
        script:
          - rm -r node_modules
          - meteor npm install
          - cd .deploy
          - export METEOR_ALLOW_SUPERUSER=true
          - mup deploy
````

I hope this will help in future.

**Comment by kaamodt** [comment]
Thanks @SimonatoLucaManuele, but I was able to solve this earlier on :) I had not put the installment of Meteor as part of the pipeline steps and the error message was not really helping me understand that.

**Comment by brianlukoff** [comment]
@SimonatoLucaManuele Are you using BitBucket Pipeline's stored SSH keys? When I try to do that I get the following from running `mup` in a BitBucket pipeline:
````
error: server worker doesn't have password, ssh-agent or pem
````

**Comment by kaamodt** [comment]
It has been awhile since I worked with this, but what type of credentials you need depends on the server you are trying to deploy to. Typically, this will be a SSH key pair. 

For `mup` there is configuration for what type of credentials you need to accessing the target server. If you look at my script above I have three lines for making the SSH key pair available for the deploy pipeline.

```
- cat my_known_hosts >> ~/.ssh/known_hosts
- cat id_rsa.pub >> ~/.ssh/id_rsa.pub
- (umask 077; echo $SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
```` 
where the `my_known_hosts` and the `id_rsa.pub` is part of the code base, while the private key is stored in the Bitbucket variable `SSH_KEY`. Not sure if this is the best way of doing this, but it worked for me at least (and I think it is secure?). 

Regards, 

Kjetil

**Comment by SimonatoLucaManuele** [comment]
@brianlukoff I try to use pipelines ssh key but without success. I've to redeploy the previous version! I'm going to do it today!

**Comment by brianlukoff** [comment]
@kaamodt @SimonatoLucaManuele BitBucket now has a built-in feature for storing an SSH key that is automatically added to images used for pipelines. I was finally able to determine that the private key is placed at `/opt/atlassian/pipelines/agent/data/id_rsa`, so setting `pem` to that file let me get `mup` deployments working.

**Comment by SimonatoLucaManuele** [comment]
thank you @brianlukoff! So i can try to copy them in a more accessible folder.. ~/ssh/id_rsa maybe?
