### ISSUE TITLE
Pushing App successful but no deployment

### ISSUE THREAD

**Issue by kenshinman** [zodern/meteor-up#404]
Hello, I am having issues deploying my app. after I deploy, I get this log  

`Started TaskList: Pushing Meteor
[138.197.79.81] - Pushing Meteor App Bundle to The Server
[138.197.79.81] - Pushing Meteor App Bundle to The Server: SUCCESS
[138.197.79.81] - Pushing the Startup Script
[138.197.79.81] - Pushing the Startup Script: SUCCESS
`
but when I visit the IP address of my app, it's just blank like nothing was deployed.

When i check the server, I see the upload `bundle.tar.gz` but I don't think the deployment was successful.
Also when I check the available containers with `docker ps`, I only the mongodb container which means there was no container created for my app.

I am deploying on Ubuntu 14.04 and here below is my mup-config.js file

`module.exports = {
    servers: {
        one: {
            "host": "138.197.79.81",
            "username": 'root',
            "pem": "C:/Users/KenshinMan.DESKTOP-PU4PNV5/.ssh/id_rsa",
            opts: {
                port: 22,
            },
            // password:
            // or leave blank for authenticate from ssh-agent
        }
    },

    meteor: {
        name: 'sesewa',
        path: 'C:/projects/meteor/sesewa',
        volumes: { // lets you add docker volumes (optional)
            "/var/uploads": "/var/uploads", // passed as '-v /host/path:/container/path' to the docker run command
            //"/second/host/path": "/second/container/path"
        },
        docker: {
            image: 'kadirahq/meteord', // (optional)
            //image: 'abernix/meteord:base', // use this image if using Meteor 1.4+
        },
        servers: {
            one: {}
        },
        buildOptions: {
            serverOnly: true,
        },
        env: {
            "PORT": 80,
            "ROOT_URL": "http://138.197.79.81/"
        },

        //dockerImage: 'kadirahq/meteord'
        deployCheckWaitTime: 60
    }
};`

Thanks

**Comment by albertonaperijr** [comment]
It looks like you're deploying for both `client` and `server` but you set `serverOnly` to true. Comment it out or just set it to false. 

```
buildOptions: {
    serverOnly: false // or just comment this line out.
}
```

**Comment by kenshinman** [comment]
Hi, @albertonaperijr . I have edited the mup file as suggested and the same issue persists. I really need a way to store images that don't get deleted after every deployment. For now I'm using mupx which is not a useful for creating volumes. here is my current `mup-config.js` file:

`module.exports = {
    servers: {
        one: {
            "host": "159.203.91.134",
            "username": 'root',
            "pem": "C:/Users/KenshinMan.DESKTOP-PU4PNV5/.ssh/id_rsa",
            opts: {
                port: 22,
            },
            // password:
            // or leave blank for authenticate from ssh-agent
        }
    },

    meteor: {
        name: 'sesewa',
        path: 'C:/projects/meteor/sesewa',
        volumes: { // lets you add docker volumes (optional)
            "/data/uploads": "/uploads", // passed as '-v /host/path:/container/path' to the docker run command
            //"/second/host/path": "/second/container/path"
        },
        docker: {
            image: 'kadirahq/meteord', // (optional)
            //image: 'abernix/meteord:base', // use this image if using Meteor 1.4+
        },
        servers: {
            one: {}
        },
        env: {
            "PORT": 80,
            "ROOT_URL": "http://159.203.91.134/"
        },

        //dockerImage: 'kadirahq/meteord'
        deployCheckWaitTime: 60
    },
	buildOptions: {
      //serverOnly: false,
      debug: true,
      cleanAfterBuild: true
    }
};`

This i s the upload log 

` For setup I ran..
mup --config mup-config.js setup

Started TaskList: Setup Docker
[159.203.91.134] - setup docker
[159.203.91.134] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[159.203.91.134] - Setup Environment
[159.203.91.134] - Setup Environment: SUCCESS

and for deploy i ran 
 mup --config mup-config.js deploy

Building App Bundle Locally

Started TaskList: Pushing Meteor
[159.203.91.134] - Pushing Meteor App Bundle to The Server
[159.203.91.134] - Pushing Meteor App Bundle to The Server: SUCCESS
[159.203.91.134] - Pushing the Startup Script
[159.203.91.134] - Pushing the Startup Script: SUCCESS`

All seems to be successful but when I check the app using the IP address, it doesn't show.
When I run `docker ps`, there is no docker container on the server. is there something wrong with my deployment script or something else is wrong somewhere?

Thanks

**Comment by fisherman818** [comment]
Does it work on port 3000? the default meteor port? and are you on Nginx?

**Comment by zodern** [comment]
This issue can be reopened if anyone still encounters this.
