### ISSUE TITLE
mup setup fails silently

### ISSUE THREAD

**Issue by hems** [zodern/meteor-up#406]
````mup setup```` is yielding nothing on the command line ( after doing mup init and editing the settings ).

````mup deploy```` shows "Building App Locally" but nothing seems to happen afterwards.

I was using mupx and done dozens of deployments but out of the blue without any aparent change on server or client the deployments stopped working.

it seems to be very hard to get this right because i tried mup before docker, then mupx, then meteor-up now and all of them seems to have real issues making this smooth.

mupx used to work 100% smooth until yesterday with my ubuntu server / Darwin local computer.
Today it simply don't work anymore even on a new linux server.

really frustrating.

thank you a lot for your work and efforts tough

**Comment by fishdude** [comment]
Hey @hems i'm getting the same "silent fail" behavior, very frustrating... Did you get anywhere with this?

**Comment by asyncink** [comment]
+1
the same! what are possible solution guys?

**Comment by hems** [comment]
@git4t3ch / @fishdude i noticed some other project i had actually still deploy, so i'm wondering if that is something to be with an npm package or even if an specific meteor version ( although i didn't update my meteor project ).

My temporary solution was to copy the project to the server old school way ( rsync + ssh ) to my server and it worked okay for me, at that point my project wasn't anymore working inside a docker docker so I also had to install mongodb on my server, backup the old mongo data from inside docker and import into the new one.

hope that helps somehow

**Comment by bensventures** [comment]
Maybe post your config to see if anything looks out of the ordinary? I'm using `meteor-up` with meteor 1.3.4.2 and all is working fine. 

Do you get anything in the logs?

**Comment by haleo9000** [comment]
I'm also seeing this. This is on an existing server where I was running mupx previously, but am not running into issues with the updated nodejs libraries and have moved to this meteor-up version using the abernix/meteord:base docker image.

**Comment by danielbressan** [comment]
Anyone find a fix for this? I too am just moving from mupx. I copied and pasted a lot of the config, but I think I got everything. I'm not able to use a clean server right now....


```
ubuntu@ip-172-31-11-0:~/mercury-dev/.deploy$ mup logs -f
ubuntu@ip-172-31-11-0:~/mercury-dev/.deploy$ DEBUG=* mup setup
  mup:module:default exec => mup setup +0ms
  mup:module:docker exec => mup docker setup +15ms
ubuntu@ip-172-31-11-0:~/mercury-dev/.deploy$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
ubuntu@ip-172-31-11-0:~/mercury-dev/.deploy$ DEBUG=* mup deploy
  mup:module:default exec => mup deploy +0ms
  mup:module:meteor exec => mup meteor deploy +1ms
  mup:module:meteor exec => mup meteor push +15ms
Building App Bundle Locally
ubuntu@ip-172-31-11-0:~/mercury-dev/.deploy$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

My mup.js looks like:
```
module.exports = {
    servers: {
        one: {
            host: "xx.x.xxx.xx",
            username: "ubuntu",
            pem: "~/dev.pem"
        }
    },

    meteor: {
        name: 'mercury',
        path: '/home/ubuntu/mercury-dev',
        port: 80,
        servers: {
            one: {},
        },
        buildOptions: {
            serverOnly: true,
        },
        env: {
            ROOT_URL: "https://xyz.com",
            MONGO_URL: "mongodb://172.17.0.1:27017/mercury"
        },
        dockerImage: 'abernix/meteord:base',
        deployCheckWaitTime: 60,
        enableUploadProgressBar: false,
        ssl: {
            crt: "/etc/nginx/certs/chained.pem", 
            key: "/etc/nginx/certs/key.pem",
            port: 443
        }
    }
};
```

Any help would be awesome! Thanks!

**Comment by zodern** [comment]
Your pem path has a ~ which wasn't supported. I just released mup 1.2.1 which included a fix for that.

**Comment by danielbressan** [comment]
Wow, thanks for the quick reply!

That was it, got me past the silent fail.

**Comment by ayhid** [comment]
@zodern thanks for the takeover & the feedback

I have a pem path with ~ I am on mup 1.2.1 but this does not seem to work it just fails silently

**Comment by zodern** [comment]
Does it work if you make it an absolute path without the `~`?
