### ISSUE TITLE
Deploying videos

### ISSUE THREAD

**Issue by doronsever** [zodern/meteor-up#409]
I have some videos that i want to deploy for my website(they are not uploaded via HTML).
I want to upload those files by my self and not with mup deploy because it will take a LOT of time each deployment.

How can i upload videos to my webserver/docker after the deployment was successful?
And ofcourse in a way that they won't be deleted on each deploy...
10x!

**Comment by kjp17** [comment]
One way to solve this is to use collectionfs and put it in aws s3

**Comment by doronsever** [comment]
I'm trying to enable docker's volumes...
But for now with out any success...
help to configure it out will be much appreciated

**Comment by bensventures** [comment]
Sorry if this comes a bit late but I am using docker volumes for images, I think that's what you are looking for. Here is an excerpt of my `mup.js` config file:

```
...
meteor: {
        name: 'appname',
        path: 'pathtoapp',
        port: 3001,
        volumes: {
            "/var/www/app-uploads": "/app-uploads", // First path is path on server, second is path in docker container
            "/etc/localtime": "/etc/localtime"
        },
        docker: {
            image: 'abernix/meteord:base'
        },
...
```

Hope this helps

**Comment by doronsever** [comment]
10x for the update. I did succeed to create a volume like your suggestion, but the next problem was that Meteor it self does not support public files to be added on the fly this way... So i had to move to a 3rd party solution.
