### ISSUE TITLE
Mongo_url doesn't work for me. 

### ISSUE THREAD

**Issue by kjp17** [zodern/meteor-up#410]
When I specify an external mongo server in MONGO_URL it doesn't seem to work.  It still uses local host mongo. Anyone has the same problem? I am using latest meteor  1.4.2. And abernix/meteord:base docker image for node compatibility.

**Comment by fisherman818** [comment]
I am having the same problem now. have u found a solution?

**Comment by kjp17** [comment]
Nope. I've given up.  I am using galaxy.  Other alternative is pm2, meteor build

**Comment by fisherman818** [comment]
@kjp17 I solved my issue. Refer to: https://github.com/kadirahq/meteor-up/issues/249

**Comment by kjp17** [comment]
Thank you.   that works for me too!!!!
