### ISSUE TITLE
npm WARN meteor-dev-bundle@0.0.0 No description

### ISSUE THREAD

**Issue by Sphinxxxx** [zodern/meteor-up#411]
I'm trying to deploy a Meteor (v1.4.2.3) app. The readme only says that Ubuntu is supported, but I tried to deploy my app to a hosted Debian server (Debian 8.6).

I found I needed to..

- Install docker (https://docs.docker.com/engine/installation/linux/debian/)
- Install sudo (http://sharadchhetri.com/2013/08/07/sudo-command-not-found-debian-7/)
- Change `docker > image` to `abernix/meteord:base` in **mup.js** (https://github.com/kadirahq/meteor-up/issues/172#issuecomment-235569968)

..and then things seemed to work well up until the validation stage of `mup deploy`:

    (...)
    - Verifying Deployment
    x Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------

        | +-- rimraf@2.5.4
        | +-- tar@2.2.1
        | | `-- block-stream@0.0.9
        | `-- which@1.2.12
        |   `-- isexe@1.1.2
        +-- node-pre-gyp@0.6.29
        | +-- rc@1.1.6
        | | +-- deep-extend@0.4.1
        | | +-- ini@1.3.4
        | | +-- minimist@1.2.0
        | | `-- strip-json-comments@1.0.4
        | +-- semver@5.2.0
        | `-- tar-pack@3.1.4
        |   +-- debug@2.2.0
        |   | `-- ms@0.7.1
        |   +-- fstream-ignore@1.0.5
        |   +-- once@1.3.3
        |   +-- readable-stream@2.1.5
        |   | +-- buffer-shims@1.0.0
        |   | +-- core-util-is@1.0.2
        |   | +-- isarray@1.0.0
        |   | +-- process-nextick-args@1.0.7
        |   | +-- string_decoder@0.10.31
        |   | `-- util-deprecate@1.0.2
        |   `-- uid-number@0.0.6
        +-- promise@7.1.1
        +-- semver@4.1.0
        +-- source-map@0.1.32
        +-- source-map-support@0.3.2
        `-- underscore@1.5.2

        npm WARN meteor-dev-bundle@0.0.0 No description
        npm WARN meteor-dev-bundle@0.0.0 No repository field.
        npm WARN meteor-dev-bundle@0.0.0 No license field.
        => Starting meteor app on port:80
        ** Meteor.startup **

        => Redeploying previous version of the app

        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------

The output from `mup logs -f`:

    > meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
    > node npm-rebuild.js
    
    {
      "meteor-dev-bundle": "0.0.0",
      "npm": "3.10.10",
      "ares": "1.10.1-DEV",
      "http_parser": "2.7.0",
      "icu": "56.1",
      "modules": "46",
      "node": "4.7.0",
      "openssl": "1.0.2j",
      "uv": "1.9.1",
      "v8": "4.5.103.43",
      "zlib": "1.2.8"
    }
    => Starting meteor app on port:80
    ** Meteor.startup **
    npm WARN meteor-dev-bundle@0.0.0 No description
    npm WARN meteor-dev-bundle@0.0.0 No repository field.
    npm WARN meteor-dev-bundle@0.0.0 No license field.

The "** Meteor.startup **" message is a `console.log()` inside `Meteor.startup()`, so the app clearly runs, but `mup deploy` still fails. Do I need a server that runs Ubuntu instead of Debian, or can I fix this somehow?

**Comment by Sphinxxxx** [comment]
By the way, the [FAQ](https://github.com/kadirahq/meteor-up#faq) says to increase `deployCheckWaitTime` in this situation, so I have set it to 240, which I hope is enough?

**Comment by MikeCraig418** [comment]
I'm having the same issue. 

Digital Ocean
512 MB Memory / 20 GB Disk / SFO2 - Ubuntu 16.04.1 x64

**Comment by Sphinxxxx** [comment]
@949mac  - After trying (and failing) a different way to deploy ([this one](https://github.com/AYCRAL/meteor-deployment)), `mup deploy` suddenly started working. The only important thing I did in the meantime that can think of: I installed Meteor and Nginx manually on the server. So maybe `mup setup` doesn't install Meteor properly?

Try to install Meteor on your server before you deploy (`curl https://install.meteor.com/ | sh`). If that doesn't work, try to install Nginx as well, but then you'll have to deploy your app to a different port than 80 (tutorial: https://www.bersling.com/2016/05/17/deploying-multiple-meteor-apps-on-one-digitalocean-server/)

**Comment by saiy2k** [comment]
I am getting a similar issue with fresh installation of Meteor app.

Meteor Version:
1.4.4.2

Mup Version:
1.2.8

Error on `mup deploy`:

> Started TaskList: Start Meteor
> [139.59.16.54] - Start Meteor
> [139.59.16.54] - Start Meteor: SUCCESS
> [139.59.16.54] - Verifying Deployment
> [139.59.16.54] x Verifying Deployment: FAILED
> 	
> 	-----------------------------------STDERR-----------------------------------
> 	`-- block-stream@0.0.9 
> 	| `-- which@1.2.14 
> 	|   `-- isexe@2.0.0 
> 	+-- node-pre-gyp@0.6.34 
> 	| +-- nopt@4.0.1 
> 	| +-- rc@1.2.1 
> 	| | +-- deep-extend@0.4.2 
> 	| | +-- ini@1.3.4 
> 	| | +-- minimist@1.2.0 
> 	| | `-- strip-json-comments@2.0.1 
> 	| +-- semver@5.3.0 
> 	| `-- tar-pack@3.4.0 
> 	|   +-- debug@2.6.8 
> 	|   | `-- ms@2.0.0 
> 	|   +-- fstream-ignore@1.0.5 
> 	|   +-- readable-stream@2.2.9 
> 	|   | +-- buffer-shims@1.0.0 
> 	|   | +-- core-util-is@1.0.2 
> 	|   | +-- isarray@1.0.0 
> 	|   | +-- process-nextick-args@1.0.7 
> 	|   | +-- string_decoder@1.0.1 
> 	|   | `-- util-deprecate@1.0.2 
> 	|   `-- uid-number@0.0.6 
> 	+-- promise@7.1.1 
> 	+-- semver@4.1.0 
> 	+-- source-map@0.1.32 
> 	+-- source-map-support@0.3.2 
> 	+-- strip-ansi@0.3.0 
> 	+-- supports-color@0.2.0 
> 	+-- type-of@2.0.1 
> 	`-- underscore@1.5.2 
> 	
> 	npm WARN meteor-dev-bundle@0.0.0 No description
> 	npm WARN meteor-dev-bundle@0.0.0 No repository field.
> 	npm WARN meteor-dev-bundle@0.0.0 No license field.
> 	=> Starting meteor app on port:80
> 	 
> 	=> Redeploying previous version of the app
> 	 
> 	-----------------------------------STDOUT-----------------------------------
> 	
> 	To see more logs type 'mup logs --tail=50'
> 	
> 	----------------------------------------------------------------------------

`mup logs --tail=100` shows
[139.59.16.54]
[139.59.16.54]> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
[139.59.16.54]> node npm-rebuild.js
[139.59.16.54]
[139.59.16.54]{
[139.59.16.54]  "meteor-dev-bundle": "0.0.0",
[139.59.16.54]  "npm": "3.10.10",
[139.59.16.54]  "ares": "1.10.1-DEV",
[139.59.16.54]  "http_parser": "2.7.0",
[139.59.16.54]  "icu": "56.1",
[139.59.16.54]  "modules": "46",
[139.59.16.54]  "node": "4.8.0",
[139.59.16.54]  "openssl": "1.0.2k",
[139.59.16.54]  "uv": "1.9.1",
[139.59.16.54]  "v8": "4.5.103.45",
[139.59.16.54]  "zlib": "1.2.8"
[139.59.16.54]}
[139.59.16.54]npm WARN meteor-dev-bundle@0.0.0 No description
[139.59.16.54]npm WARN meteor-dev-bundle@0.0.0 No repository field.
[139.59.16.54]npm WARN meteor-dev-bundle@0.0.0 No license field.
[139.59.16.54]=> Starting meteor app on port:80

Increased `deployCheckWaitTime` to 440.

My mup.js file

> module.exports = {
>   servers: {
>     one: {
>       // TODO: set host address, username, and authentication method
>       host: '[server_ip goes here]',
>       username: '[user_name goes here]',
>       // pem: './path/to/pem'
>       password: '[password goes here]'
>       // or neither for authenticate from ssh-agent
>     }
>   },
> 
>   meteor: {
>     // TODO: change app name and path
>     name: 'test-app',
>     path: '.',
> 
>     servers: {
>       one: {},
>     },
> 
>     buildOptions: {
>       serverOnly: true,
>     },
> 
>     env: {
>       // TODO: Change to your app's url
>       // If you are using ssl, it needs to start with https://
>       ROOT_URL: 'http://139.59.16.54/test-app',
>       PORT: 443
>       //MONGO_URL: 'mongodb://localhost/meteor',
>     },
> 
>     docker: {
>       // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
>       image: 'abernix/meteord:base',
>       // imagePort: 80, // (default: 80, some images EXPOSE different ports)
>     },
> 
>     // This is the maximum time in seconds it will wait
>     // for your app to start
>     // Add 30 seconds if the server has 512mb of ram
>     // And 30 more if you have binary npm dependencies.
>     deployCheckWaitTime: 440,
> 
>     // Show progress bar while uploading bundle to server
>     // You might need to disable it on CI servers
>     enableUploadProgressBar: false
>   },
> 
>   mongo: {
>     port: 27017,
>     version: '3.4.1',
>     servers: {
>       one: {}
>     }
>   }
> };
>

**Comment by zodern** [comment]
@saiy2k what does it show if you run `mup deploy --verbose`?

**Comment by saiy2k** [comment]
Copying my console log

```
$ mup deploy --verbose
Building App Bundle Locally
                                                                            
Started TaskList: Pushing Meteor App
[139.59.16.54] - Pushing Meteor App Bundle to The Server
[139.59.16.54] - Pushing Meteor App Bundle to The Server: SUCCESS

Started TaskList: Configuring App
[139.59.16.54] - Pushing the Startup Script
[139.59.16.54] - Pushing the Startup Script: SUCCESS
[139.59.16.54] - Sending Environment Variables
[139.59.16.54] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[139.59.16.54] - Start Meteor
test-app
Error response from daemon: endpoint test-app not found
Error response from daemon: No such container: test-app-frontend
Error response from daemon: endpoint test-app-frontend not found
Removed test-app-frontend
Error response from daemon: No such container: test-app-nginx-letsencrypt
Error response from daemon: endpoint test-app-nginx-letsencrypt not found
Removed test-app-nginx-letsencrypt
Error response from daemon: No such container: test-app-nginx-proxy
Error response from daemon: endpoint test-app-nginx-proxy not found
Removed test-app-nginx-proxy
base: Pulling from abernix/meteord
Digest: sha256:9ed85313621010dd27a08054ae9225aa1f31798647fbcfdc9cc082181c6f9c97
Status: Image is up to date for abernix/meteord:base
Pulled abernix/meteord:base
c0412af916c9e32b228bc2122b7c1e2151b9e8f0f9d9c31342257a45ec76635f
Ran abernix/meteord:base
[139.59.16.54] - Start Meteor: SUCCESS
[139.59.16.54] - Verifying Deployment

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found //This block is repeated several time

| | +-- mime-types@2.1.15 
| | | `-- mime-db@1.27.0 
| | +-- oauth-sign@0.8.2 
| | +-- performance-now@0.2.0 
| | +-- qs@6.4.0 
| | +-- safe-buffer@5.0.1 
| | +-- stringstream@0.0.5 
| | +-- tough-cookie@2.3.2 
| | | `-- punycode@1.4.1 
| | +-- tunnel-agent@0.6.0 
| | `-- uuid@3.0.1 
| +-- rimraf@2.6.1 
| +-- semver@5.3.0 
| +-- tar@2.2.1 
| | `-- block-stream@0.0.9 
| `-- which@1.2.14 
|   `-- isexe@2.0.0 
+-- node-pre-gyp@0.6.34 
| +-- nopt@4.0.1 
| +-- rc@1.2.1 
| | +-- deep-extend@0.4.2 
| | +-- ini@1.3.4 
| | +-- minimist@1.2.0 
| | `-- strip-json-comments@2.0.1 
| +-- semver@5.3.0 
| `-- tar-pack@3.4.0 
|   +-- debug@2.6.8 
|   | `-- ms@2.0.0 
|   +-- fstream-ignore@1.0.5 
|   +-- readable-stream@2.2.9 
|   | +-- buffer-shims@1.0.0 
|   | +-- core-util-is@1.0.2 
|   | +-- isarray@1.0.0 
|   | +-- process-nextick-args@1.0.7 
|   | +-- string_decoder@1.0.1 
|   | `-- util-deprecate@1.0.2 
|   `-- uid-number@0.0.6 
+-- promise@7.1.1 
+-- semver@4.1.0 
+-- source-map@0.1.32 
+-- source-map-support@0.3.2 
+-- strip-ansi@0.3.0 
+-- supports-color@0.2.0 
+-- type-of@2.0.1 
`-- underscore@1.5.2 

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
=> Starting meteor app on port:80

To see more logs type 'mup logs --tail=50'

 
=> Redeploying previous version of the app
 
[139.59.16.54] x Verifying Deployment: FAILED
	
	-----------------------------------STDERR-----------------------------------
	`-- block-stream@0.0.9 
	| `-- which@1.2.14 
	|   `-- isexe@2.0.0 
	+-- node-pre-gyp@0.6.34 
	| +-- nopt@4.0.1 
	| +-- rc@1.2.1 
	| | +-- deep-extend@0.4.2 
	| | +-- ini@1.3.4 
	| | +-- minimist@1.2.0 
	| | `-- strip-json-comments@2.0.1 
	| +-- semver@5.3.0 
	| `-- tar-pack@3.4.0 
	|   +-- debug@2.6.8 
	|   | `-- ms@2.0.0 
	|   +-- fstream-ignore@1.0.5 
	|   +-- readable-stream@2.2.9 
	|   | +-- buffer-shims@1.0.0 
	|   | +-- core-util-is@1.0.2 
	|   | +-- isarray@1.0.0 
	|   | +-- process-nextick-args@1.0.7 
	|   | +-- string_decoder@1.0.1 
	|   | `-- util-deprecate@1.0.2 
	|   `-- uid-number@0.0.6 
	+-- promise@7.1.1 
	+-- semver@4.1.0 
	+-- source-map@0.1.32 
	+-- source-map-support@0.3.2 
	+-- strip-ansi@0.3.0 
	+-- supports-color@0.2.0 
	+-- type-of@2.0.1 
	`-- underscore@1.5.2 
	
	npm WARN meteor-dev-bundle@0.0.0 No description
	npm WARN meteor-dev-bundle@0.0.0 No repository field.
	npm WARN meteor-dev-bundle@0.0.0 No license field.
	=> Starting meteor app on port:80
	 
	=> Redeploying previous version of the app
	 
	-----------------------------------STDOUT-----------------------------------
	
	To see more logs type 'mup logs --tail=50'
	
	----------------------------------------------------------------------------

```

**Comment by zodern** [comment]
The problem is `curl: (22) The requested URL returned error: 404 Not Found`. There is an issue for it #618.

**Comment by jawwadh1** [comment]
i have a same issue kindly refer to this 


https://github.com/RocketChat/Rocket.Chat/issues/9167


Using Cent-Os 

Solved 

    yum install g++ build-essential

    npm install -g node-gyp

    cd /opt/Rocket.Chat/programs/server/node_modules/fibers/

    node-gyp rebuild

    cp build/Release/fibers.node bin/linux-x64-57/fibers.node

    systemctl start rocketchat.service

This is the procedure for Upgrading rocket chat 

Hope this can be applied to new instance
