### ISSUE TITLE
seeking clarification on SSL support

### ISSUE THREAD

**Issue by fisherman818** [zodern/meteor-up#412]
I use letsencrypt to generate the SSL certs, after which the right certs are stored in:

> crt: '/etc/letsencrypt/live/domain.com/fullchain.pem',
> key: '/etc/letsencrypt/live/domain.com/privkey.pem'

At the guide, it says that:

> If your certificate and key are already in the right location on your server and you would like to prevent Mup from overriding them while still needing an SSL setup, you can add `upload: false` to mup.js in the meteor.ssl object.

I am bit confused. Since now the certs are already on server, how can I use the SSL cert directly, without the need to upload it like this:

```
ssl: {
      port: 443,
      crt: '/location/bundle.crt',
      key: '/location/private.key',
    },

```
and How should I use `upload: false`?

Thank you!

**Comment by shadowcodex** [comment]
I'm wondering this same thing too...

Wondering if I can create a symlink to the "right location"... Thus using a cron job to auto renew the certs, and not having to load them in every 3 months...
