### ISSUE TITLE
Websocket Error on setting up SSL

### ISSUE THREAD

**Issue by dominicarrojado** [zodern/meteor-up#413]
I just setup https but I get this error WebSocket connection to 'ws://example.com/sockjs/965/fwpnpvgn/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by kevinhattam** [comment]
I'm seeing this issue too. I'm wondering if setting the ROOT_URL in my mup.js to have https will resolve this. Were you able to resolve this?

**Comment by zodern** [comment]
Websockets work when using the reverse proxy in the latest version of mup.
