### ISSUE TITLE
Running mup setup just opens mup.js instead of setting up

### ISSUE THREAD

**Issue by barrymichaeldoyle** [zodern/meteor-up#416]
I'm on a Windows machine and after following the steps laid out ion the ReadMe doc, I get to the `mup deploy` command.  When I run `mup deploy` (I'm in the `myApp/.deploy` directory) instead of setting up behavior that is expected, it just opens the mup.js file in VSCode.  What am I missing here?

**Comment by gjr-qm** [comment]
Just type `mup.cmd deploy` instead of `mup deploy`

**Comment by barrymichaeldoyle** [comment]
Thanks man 👍
