### ISSUE TITLE
mup doesn't work with relative pem paths

### ISSUE THREAD

**Issue by reduxdj** [zodern/meteor-up#42]
I had to change this from:
 pem:  '~/.ssh/id_rsa'

 pem:  '/Users/Patrick_/.ssh/id_rsa'

because of this result: open '/Users/Patrick_/app/~/.ssh/id_rsa'

**Comment by madushan1000** [comment]
We use nodejs `path` module to resolve relative paths, and it doesn't support `~`(~ is not a unix standard, It's just used by bash originated shells). Take a look at these two issues in nodejs https://github.com/nodejs/node-v0.x-archive/issues/2857 https://github.com/nodejs/node/issues/684. If someone can add this to mup using a third party library, pull requests are welcome.

PS: Mup works  with relative paths like `../../yourkey` fine.

**Comment by Ben305** [comment]
Can be solved easily:

`var path = require('path');`
`var os = require('os');`
`var privateKey = path.join(os.homedir(), '.ssh', 'id_rsa');`

and then later with
`pem: privateKey`
