### ISSUE TITLE
Deployment Failed | Start Meteor -failed

### ISSUE THREAD

**Issue by ShrinathGupta** [zodern/meteor-up#420]
I am trying to deploy meteor app on ubuntu server.

**`Mup setup`** goes fine with all success logs. 
But when I tried `**mup deploy**` It throws errror while start meteor task.

![issue](https://cloud.githubusercontent.com/assets/12642711/21920854/d0e6c78a-d989-11e6-89b1-e8d8c3f537cf.png)

I checked running dockers on server but only mongo is running on server.
I also check for port 80 and no process consuming port it's free on server.
Please help me out on this.
Meteor Version --> 1.4.2.3
Mup Version --> 1.0.4

Your help will be highly appreciated..!

**Comment by srimenow** [comment]
I am in your same boat as well, 
`	-----------------------------------STDERR-----------------------------------
	Tag latest not found in repository docker.io/library/mongo
	-----------------------------------STDOUT-----------------------------------
	Pulling repository docker.io/library/mongo
	----------------------------------------------------------------------------`

.... this was only after trying to destroy my digital ocean droplet and start over again after the error
` mup logs
update 1.0.0 => 1.0.4
[107.170.***.***]Error: No such container:********`

**Comment by mackbrowne** [comment]
Hello, I'm also stuck with this on digitalocean.  Trying to use Ubuntu 14.04 x64 image

**Comment by 06chaynes** [comment]
I will add that I had the same issue @srimenow was experiencing. I had to completely remove mup from my local system and re-install, after that setup and deployment worked as expected.

**Comment by ziedmahdi** [comment]
any luck with this?

**Comment by zodern** [comment]
> Tag latest not found in repository docker.io/library/mongo

This is from docker unable to connect to docker.io. Trying again later usually works. 

The docker error "flag provided but not defined" seem to be from the server having an old version of docker. If anyone gets this error, please post the version of docker on the server here.

**Comment by srimenow** [comment]
As I stated on another thread you should remove Mup from your system, reinstall it, and create a new digital ocean / cloud provider of choice instance to see if that fixes the issue.

I had to do both, some people only have to reinstall mup, let us know if you did this and still have the issue.

Also please note don't just destroy your instance and create a new one, you need a fresh droplet with a new IP in my experience

**Comment by zodern** [comment]
Mup 1.3 will update docker during `mup setup`, which will fix the issue reported by @ShrinathGupta .
