### ISSUE TITLE
Docker or MUP problem? Setup fails to start mongodb, please provide your input

### ISSUE THREAD

**Issue by srimenow** [zodern/meteor-up#421]
Re-running the command with slightly different errors, have experimented with fresh installs (and making sure to apt-get update) with Ubuntu 16x64; Also tried Ubuntu14x64 just for the hell of it. Currently using kadira image, but also have used the abernix/meteord:base. This is driving me crazy and coming at an awful time, everything was working perfectly earlier today until all of my deploys failed and I began the process of setting up mup again :(

I seem to be having some trouble pulling the latest image of mongodb, 
`{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Name":"library/mongo","Action":"pull"}]}]}
`
`

I took that and am trying to pull from docker via ssh:
`docker pull mongo
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/mongo/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fmongo%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
root@free:~# docker pull mongo
Using default tag: latest
latest: Pulling from library/mongo
75a822cd7888: Pull complete 
3bf369f658b6: Pull complete 
7d7cb343d20e: Pulling fs layer 
73a933a908f7: Waiting 
71e3f377cb7c: Waiting 
0c966a5ad030: Waiting 
187315b08446: Waiting 
d669318a89ab: Waiting 
3c5d7f61f934: Waiting `

myhost:.deploy dev$ DEBUG=* mup setup
  mup:module:default exec => mup setup +0ms
  mup:module:docker exec => mup docker setup +2ms

Started TaskList: Setup Docker
[192.0.0.64] - setup docker
[192.0.0.64] - setup docker: SUCCESS
  mup:module:meteor exec => mup meteor setup +854ms

Started TaskList: Setup Meteor
[192.0.0.64] - Setup Environment
  mup:module:mongo exec => mup mongo setup +2ms

Started TaskList: Setup Mongo
[192.0.0.64] - setup environment
[192.0.0.64] - setup environment: SUCCESS
[192.0.0.64] - copying mongodb.conf
  nodemiral:sess:192.0.0.64 copy file - src: /usr/local/lib/node_modules/mup/lib/modules/mongo/assets/mongodb.conf, dest: /opt/mongodb/mongodb.conf, vars: undefined +0ms
[192.0.0.64] - Setup Environment: SUCCESS
[192.0.0.64] - copying mongodb.conf: SUCCESS
  mup:module:mongo exec => mup mongo start +2s

Started TaskList: Start Mongo
[192.0.0.64] - start mongo
[192.0.0.64] x start mongo: FAILED
	
	-----------------------------------STDERR-----------------------------------
	Error response from daemon: Get https://registry-1.docker.io/v2/library/mongo/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fmongo%3Apull&service=registry.docker.io: net/http: TLS handshake timeout
	-----------------------------------STDOUT-----------------------------------
	----------------------------------------------------------------------------
myhost:.deploy dev$ DEBUG=* mup setup
  mup:module:default exec => mup setup +0ms
  mup:module:docker exec => mup docker setup +1ms

Started TaskList: Setup Docker
[192.0.0.64] - setup docker
[192.0.0.64] - setup docker: SUCCESS
  mup:module:meteor exec => mup meteor setup +740ms

Started TaskList: Setup Meteor
[192.0.0.64] - Setup Environment
  mup:module:mongo exec => mup mongo setup +1ms

Started TaskList: Setup Mongo
[192.0.0.64] - setup environment
[192.0.0.64] - setup environment: SUCCESS
[192.0.0.64] - copying mongodb.conf
  nodemiral:sess:192.0.0.64 copy file - src: /usr/local/lib/node_modules/mup/lib/modules/mongo/assets/mongodb.conf, dest: /opt/mongodb/mongodb.conf, vars: undefined +0ms
[192.0.0.64] - Setup Environment: SUCCESS
[192.0.0.64] - copying mongodb.conf: SUCCESS
  mup:module:mongo exec => mup mongo start +2s

Started TaskList: Start Mongo
[192.0.0.64] - start mongo
[192.0.0.64] x start mongo: FAILED
	
	-----------------------------------STDERR-----------------------------------
	error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/e7/e7b8f19244cd8a7f81147d29612c006aad0e4ea3a72b51b014e3badef3bb47f1/data?Expires=1484558884&Signature=Yrg6GbwSz3mjrqoP2p3QWal4y5M~e4vjZmZSWlDiDetD0xLL181UndBp~VO7gVSL7kgmaVYWtPJupXO9PUQPdtQT9~RDDysn~1Fi2s3Zdlv6EgFoWAx4h95iq5vItuv3BFxyIvI6JxebUdzWbDEiUBpAA1hAubW8S8RbxrI6q60_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout
	-----------------------------------STDOUT-----------------------------------
	latest: Pulling from library/mongo
	75a822cd7888: Pulling fs layer
	3bf369f658b6: Pulling fs layer
	7d7cb343d20e: Pulling fs layer
	73a933a908f7: Pulling fs layer
	71e3f377cb7c: Pulling fs layer
	0c966a5ad030: Pulling fs layer
	187315b08446: Pulling fs layer
	d669318a89ab: Pulling fs layer
	3c5d7f61f934: Pulling fs layer
	73a933a908f7: Waiting
	71e3f377cb7c: Waiting
	0c966a5ad030: Waiting
	187315b08446: Waiting
	d669318a89ab: Waiting
	3c5d7f61f934: Waiting
	----------------------------------------------------------------------------
myhost:.deploy dev$ DEBUG=* mup setup
  mup:module:default exec => mup setup +0ms
  mup:module:docker exec => mup docker setup +2ms

Started TaskList: Setup Docker
[192.0.0.64] - setup docker
[192.0.0.64] - setup docker: SUCCESS
  mup:module:meteor exec => mup meteor setup +801ms

Started TaskList: Setup Meteor
[192.0.0.64] - Setup Environment
  mup:module:mongo exec => mup mongo setup +3ms

Started TaskList: Setup Mongo
[192.0.0.64] - setup environment
[192.0.0.64] - setup environment: SUCCESS
[192.0.0.64] - copying mongodb.conf
  nodemiral:sess:192.0.0.64 copy file - src: /usr/local/lib/node_modules/mup/lib/modules/mongo/assets/mongodb.conf, dest: /opt/mongodb/mongodb.conf, vars: undefined +0ms
[192.0.0.64] - Setup Environment: SUCCESS
[192.0.0.64] - copying mongodb.conf: SUCCESS
  mup:module:mongo exec => mup mongo start +2s

Started TaskList: Start Mongo
[192.0.0.64] - start mongo
[192.0.0.64] x start mongo: FAILED
	
	-----------------------------------STDERR-----------------------------------
	Error response from daemon: Get https://registry-1.docker.io/v2/library/mongo/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fmongo%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
	-----------------------------------STDOUT-----------------------------------
	----------------------------------------------------------------------------
myhost:.deploy dev$ 

`

**Comment by avishaan** [comment]
@srimenow I'm seeing this same problem, something I didn't see even a few weeks ago. Did you find a solution?

**Comment by srimenow** [comment]
@codeHatcher 
I have been trying to hunt down the root source of the problem, but I am going to throw in the towel and share my solution, please let me know if it helps you.

I created a new digital ocean droplet, and after a fresh install of mup I also created a new .deploy folder .... you won't believe everything worked! 

Another solution, if your site is just down right now and you can't get it up is to host a mongoDB instance with somebody like compose.io 

Let me  know if you need anything else. I cannot trace this issue, but feel it is more related to docker or digital ocean than MUP itself. Best of luck :)
