### ISSUE TITLE
letsencrypt certbot returns .pem files. .crt expected

### ISSUE THREAD

**Issue by CrackedBeefcake** [zodern/meteor-up#423]
deploy works w/o ssl. everything is fine. 
but when I want to add SSL i run into the following problem:
```
    ssl: {
      crt: './ssl/cert.crt',
      key: './ssl/private.key',
      port: 443
    }
```
the `mup` api expects `.crt` and `.key` files. 
the `letsencrypt certbot` in standalone returns a bunch of `.pem` files. 

on another server I have the following lines in my `nginx` config. they work like a charm. 

```
        ssl on;
        ssl_certificate /etc/letsencrypt/live/<appname>/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/<appname>/privkey.pem;
```

those are my pems:
```
cert.pem  chain.pem  fullchain.pem  privkey.pem
```
who can i add `.pem`?
or if that does not work
what else can i do?

**Comment by shadowcodex** [comment]
@FinnFrotscher for future refrence you can use `fullchain.pem` as the crt file and `privkey.pem` as the key file.

Example:

```
ssl: {
    port: 443,
    crt: 'fullchain.pem',
    key: 'privkey.pem',
}
```

**_HOWEVER: Going forward for Let's Encrypt you should be using the autogenerate feature._**

**Comment by CrackedBeefcake** [comment]
yes i am using autogenerate now and it works ![just right][logo]

[logo]: http://i.imgur.com/IazJWlUl.jpg
