### ISSUE TITLE
Use specific mongo version instead of the latest

### ISSUE THREAD

**Issue by dklisiaris** [zodern/meteor-up#424]
Hello,

mongo setup always pulls the latest mongodb version.

I am having issues with the latest `3.4.1` version and `collectionFS` as seen here [wekan/issues/763](https://github.com/wekan/wekan/issues/763)

Is there a way to specify which mongo version I want to be installed?

**Comment by dklisiaris** [comment]
Looks like the mongo latest version is hard coded in `start_mongo.sh`

So currently it cannot be confugured.

**Comment by spk2piyu** [comment]
I am new to mup, please let me know where to do these changes. 
docker image abernix/meteord:base
how to resolve wekan/issues/763 with abernix/meteord:base.
