### ISSUE TITLE
Deployment stops after few days

### ISSUE THREAD

**Issue by spiotr12** [zodern/meteor-up#425]
Hi

I've not fount any other issue about this on google/github, so if there is anything like this, please redirect me to correct forum.

It happened 2 or 3 times so far, my app deployment was all good an everything, however after few days it stops working. The page can never load, but I cannot see any issues in the mup logs or in my logs. it just stops. 

It does get fixed if I do mup restart or mup reconfig but still it is a problem. 

Any idea what might be a problem? Did any one come across such a thing? Thanks a lot!

**Comment by zodern** [comment]
Next time this happens, could you please run `docker ps` on the server, and post the output here?

**Comment by shadowcodex** [comment]
@spiotr12 has this happened again?

**Comment by spiotr12** [comment]
Surprisingly not yet. We can close this issue for now.
