### ISSUE TITLE
Designate Mongo Version

### ISSUE THREAD

**Issue by shadowcodex** [zodern/meteor-up#427]
Need the option to decide which version of mongo is used on setup and deploy. Should be made configurable in mup.js. 

Currently only latest mongo is deployed which has backwards compatibility issues.

**Comment by zodern** [comment]
This is added and will be part of 1.2.

**Comment by shadowcodex** [comment]
@zodern when is 1.2 projected to be released?

**Comment by zodern** [comment]
I want to include fixes for #195 and #310
