### ISSUE TITLE
mup 1.0.0 won't build my meteor app

### ISSUE THREAD

**Issue by reduxdj** [zodern/meteor-up#43]
mup deploy
Bulding App Bundle Locally
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn meteor ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
QuadCore-iMac:parooz Patrick_$ DEBUG=\* mup deploy
  mup:module:default exec => mup deploy +0ms
  mup:module:meteor exec => mup meteor deploy +1ms
  mup:module:meteor exec => mup meteor push +3ms
Bulding App Bundle Locally
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn meteor ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
QuadCore-iMac:parooz Patrick_$ node -v
v4.2.6

**Comment by reduxdj** [comment]
Updated node v5.5.0 and same results happen

**Comment by reduxdj** [comment]
I think the issue might be that meteor tries to build all js files, and the result is it's trying to read my mup.js file is in my project folder. maybe mup.js should be ignored by meteor here:

// files to ignore when bundling. node has no globs, so use regexps
var ignore_files = [
    /~$/, /^\.#/, /^#.*#$/,
    /^\.DS_Store$/, /^ehthumbs\.db$/, /^Icon.$/, /^Thumbs\.db$/,
    /^\.meteor$/, /* avoids scanning N^2 files when bundling all packages */
    /^\.git$/ /* often has too many files to watch */
];

**Comment by MasterJames** [comment]
If you're having problems with mup please try the development branch mupx here and see if that helps.

Note: A new port at kadirahq is underway and might be usable in a couple of months.

You might dare to try it as a beta tester and help with feedback even!?

**Comment by reduxdj** [comment]
Ok, i am just trying to customize my docker image. I need to add openssh to the image, and nginx? But the docker image that mupx uses does not have open ssh that you support does not seem to have it. 
Any ideas how to get over this hurdle?

**Comment by madushan1000** [comment]
Seems like you don't have the meteor binary in your path. Check if it is. 
In the other case,  development version of Meteor Up supports custom docker images. It's not even in alpha release right now, use it at your own risk.

**Comment by reduxdj** [comment]
Really? what's the path variable for meteor suppose to look like?

**Comment by madushan1000** [comment]
I'm not sure, normally (on OSX) meteor binary should be in `/user/local/bin/meteor` so `/usr/local/bin` should be in path. Depending on how you installed meteor, the binary might be somewhere else. You can try defining the meteor executable explicitly in `mup.js
`Error: spawn meteor ENOENT` is normally returned by spawn when it couldn't find the binary it's supposed to run. 

And as you suggested `mup.js` file should not be in the project directory. For now move it to a hidden directory like `.deploy/mup.js`. We'll try to address this issue in the future.

**Comment by reduxdj** [comment]
mup deploy --config=.deploy/mup.js
Error: Cannot find module '/Users/plemiuex/parooz/mup.js'

**Comment by bcbrian** [comment]
For others having this problem it was resolved for me by installing meteor. Hahaha. Thats what I get for reinstalling my os, cloning my repo and just thinking it will all work.
