### ISSUE TITLE
Port requirement not specified for mongodb setup

### ISSUE THREAD

**Issue by avishaan** [zodern/meteor-up#431]
I ran into a problem in #428 where my deploy would fail because of the mongodb setup. It turned out that a port was not open that needed to be aside from 22. Do you guys know which port needs to be open? I would like to add that to the documentation. I can even add it to the docs myself if you let me know what the ports are

**Comment by avishaan** [comment]
@zodern if you let me know the port I can add it to the documentation. I never found out the required port

**Comment by avishaan** [comment]
@zodern any thoughts on where I can find this, I don't mind adding it to the docs

**Comment by zodern** [comment]
@codeHatcher sorry for not replying sooner. I honestly don't know why port 22 didn't work. It should be using scp and the same ssh configuration as all of the other steps. Though there did seem to be a relatively high failure rate while setting up Meteor and MongoDB, so version 1.2.5 changed them to be setup in serial instead of parallel.

**Comment by avishaan** [comment]
hmmm, maybe what I was seeing was a coincidence with changing the port and then having it start working?

**Comment by avishaan** [comment]
I'll play around with it a little bit and then come back here

**Comment by avishaan** [comment]
I don't remember the context of all of this so I'm going to go ahead and close the issue. Just to summarize it seems my deploy to AWS didn't work until I edited the security groups to allow incoming and outgoing traffic on all ports. I don't know if that actually made a difference or if there was some other issue and it ended up being a coincidence on why it started working
