### ISSUE TITLE
Add documentation about LetsEncrypt certificates

### ISSUE THREAD

**Issue by brylie** [zodern/meteor-up#432]
The recent pull request #337 added LetsEncrypt support. However, the README does not seem to mention LetsEncrypt support, or how to configure it. Please add instructions to the README for enabling LetsEncrypt certificates when deploying via mup.

**Comment by ilan-schemoul** [comment]
+1

**Comment by zodern** [comment]
I added the documentation. Please let me know if there is anything not clear or missing.
