### ISSUE TITLE
Should meteor-up install Node if it's not installed?

### ISSUE THREAD

**Issue by JohnAllen** [zodern/meteor-up#433]
There's mup setup, which I thought would fully setup my server for a Meteor deployment.  But it first complains about there not being a Node installed:

`/usr/bin/env: ‘node’: No such file or directory`

Are we supposed to manually install Node first (which I note could be complicated by Meteor requiring an old Node version) or should mup do this?

**Comment by JohnAllen** [comment]
If `mup setup` is supposed to be run from a local dev machine, let me know and I will make that clear in the docs and submit a PR.

**Comment by zodern** [comment]
> If mup setup is supposed to be run from a local dev machine

It is. A PR to make that clear would be appreciated.

**Comment by JohnAllen** [comment]
I'm leaving this open because of the Node install issue.  Seems like mup should install Node if it's not already.

**Comment by zodern** [comment]
MUP installs everything it needs on the remote server when `mup setup` is run, but requires Node to be on your local dev machine.
