### ISSUE TITLE
[v1.1.0]: env: node\r: No such file or directory

### ISSUE THREAD

**Issue by joncursi** [zodern/meteor-up#434]
I am getting the following error after upgrading mup to 1.1.0. I am running the mup executable out of the node_modules folder:

```
$ cd private/directory/with/mup.js/file
$ ../../../node_modules/.bin/mup deploy
env: node\r: No such file or directory
```

**Comment by yanickrochon** [comment]
Same thing. I have that it may be because of how line termination may affect this. I am on Linux, by the way.

**Comment by zodern** [comment]
I published 1.1.1 with fixed line endings.

**Comment by erperejildo** [comment]
same error here using 1.2.3v

**Comment by zodern** [comment]
@erperejildo does 1.2.6 work?

**Comment by erperejildo** [comment]
Using 1.2.6 I got this: `endpoint myApp not found`
But could be related with my Nginx because I was trying with `pm2` and I made some changes
