### ISSUE TITLE
<3 to @zodern for taking over! :D

### ISSUE THREAD

**Issue by timbrandin** [zodern/meteor-up#439]

**Comment by shadowcodex** [comment]
This is a very true statement. I love that let's encrypt was added soon after.

**Comment by ilan-schemoul** [comment]
Feel like god is among us again.

**Comment by jessb321** [comment]
Its pretty good that this is being maintained again, as many people rely on it !

**Comment by vectorselector** [comment]
I'm happy too!
But i was very confused about 5 minutes ago... 
some introductory text saying what happened would help show the way, I think. "this is the stable mainline kadirahq mup torch being carried forward" etc... as there's no word on the meteor forum and the READMEs don't say what happened...

THANK YOU! this tool is super important!

**Comment by avishaan** [comment]
I was just about to make this "issue". Sidenote: does anyone know zodern's name on twitter?
