### ISSUE TITLE
Mup doesn't recognize METEOR_PACKAGE_DIRS, only PACKAGE_DIRS

### ISSUE THREAD

**Issue by JohnAllen** [zodern/meteor-up#442]
`mup deploy` failed 

```
Errors while initializing project:

While selecting package versions:
error: unknown package in top-level dependencies:
```

when I had `METEOR_PACKAGE_DIRS` set but when I set `PACKAGE_DIRS` it passed that.  I do not understand how mup works yet but am happy to attempt to fix some of these issues I have been filing.  I searched the repo for `PACKAGE_DIRS` and didn't find anything.

**Comment by zodern** [comment]
mup uses [meteor build](https://github.com/zodern/meteor-up/blob/master/src/modules/meteor/build.js). 

What version of Meteor are you using? `METEOR_PACKAGE_DIRS` was added in 1.4.2.

**Comment by JohnAllen** [comment]
`1.4.1.3`  All I know is that `mup deploy` wasn't finding local packages until I re-set `PACKAGE_DIRS` to my package dir.

**Comment by zodern** [comment]
Meteor 1.4.1.3 only supports PACKAGE_DIRS. To use `METEOR_PACKAGE_DIRS` you will need to update to `1.4.2`.

**Comment by JohnAllen** [comment]
Thanks, closing.

**Comment by SachaG** [comment]
I just ran into the same issue. Does Mup support specifying `METEOR_PACKAGE_DIRS` in `mup.js`'s `env` block? How do you specify the environment variables you want `meteor build` to run with locally vs the environment variables for the deployed app? Or are they the same?

**Comment by zodern** [comment]
SachaG it uses the env variables on the computer it is deploying from when building.

**Comment by SachaG** [comment]
Sorry, I wasn't clear. I can confirm it does take "global" environment variables into account, but what about "local" env variables that you can specify before `meteor run`? (i.e. `METEOR_PACKAGE_DIRS="../foo" MONGO_URL="...." meteor run --port 3000`). Is there a way to specify those?

**Comment by Apollinaire** [comment]
For the people stumbling on this now : you can do `METEOR_PACKAGE_DIRS="../foo" mup deploy` **only for environment variables that are involved in the build process.** So `MONGO_URL` should stay in `mup.js`, because mup sets it in the docker.
I am doing this in mup version `1.4.5` and meteor version `1.8`
