### ISSUE TITLE
My weebsite doesn't have https even tough I activated let's encrypt

### ISSUE THREAD

**Issue by ilan-schemoul** [zodern/meteor-up#445]
I must have missed something, maybe something obvious (if it's the case shame on me) but still the https version is not reachable (https://worksheets.westeurope.cloudapp.azure.com).
1) I use azure and I open 443 (https) port
2) I launched `npm i mup -g` (BTW there may be a bug 'bout the version as `mup` prints `1.1.2 => 1.2` but `npm update mup -g` doesn't install any new version, `npm list mup` logs `mup@1.1.2`)
3) my config 
```
module.exports = {
  servers: {
    one: {
      host: 'SERVER'S IP',
      username: 'USERNAME',
      password: 'PASSWORD',
    },
  },

  meteor: {
    name: 'worksheets',
    path: '.',
    servers: { one: {} },
    env: {
      ROOT_URL: 'https://worksheets.westeurope.cloudapp.azure.com/',
      MONGO_OPLOG_URL: 'SECRET',
    },
    ssl: {
      autogenerate: {
        email: 'EXAMPLE@EXAMPLE.COM',
        domains: 'www.prepacrfpa.fr,worksheets.westeurope.cloudapp.azure.com',
      },
    },
    dockerImage: 'abernix/meteord:binbuild',
    deployCheckWaitTime: 600,
  },
};
```
4) I runned `mup setup` `mup deploy` `mup reconfig` dozens of times, they don't log any error, no bug.
Still http version works but not the https one.

**Comment by zodern** [comment]
> npm update mup -g doesn't install any new version,

Sorry, I had given you the wrong command to update. `npm i -g mup` should work.

Please run `docker ps` and `docker logs worksheets-nginx-letsencrypt --tail 30` on the server and post the output here.

**Comment by ilan-schemoul** [comment]
Hello,
Thanks for the support.
Damn it, thanks to docker logs I now know what was wrong. It was `too many certs for azure.com`, I think I should just deliver a certificate for my main domaine THANKS A LOT. You're really great.

**Comment by ilan-schemoul** [comment]
It works many many many thanks again.
