### ISSUE TITLE
nginx is started with small request entity

### ISSUE THREAD

**Issue by shadowcodex** [zodern/meteor-up#449]
I get the error: 413 Request Entity Too Large

because the nginx setup is defaulted to 1mb. I'm uploading and downloading zip files.

How to configure?

**Comment by zodern** [comment]
Currently there isn't a way to configure the nginx setup without creating your own image, but I want to change that.

What is your SSL setup? There are two different nginx containers that mup uses depending on if you are using let's encrypt or not.

**Comment by shadowcodex** [comment]
I am using the let's encrypt autogenerate.

**Comment by shadowcodex** [comment]
I can see where to edit this, if there is just a way to pass this info into the nginx docker container. 

Add following line to http{..} block in nginx config:

```
http {
	#...
        client_max_body_size 100m;
	#...
}
```

**Comment by zodern** [comment]
The first step would be to create an nginx config with better defaults ([based on the config for mup-frontend-server](https://github.com/meteorhacks/mup-frontend-server/blob/master/lib/nginx.conf#L7)), upload it to the server on deploy and add it as a volume to [nginx-proxy](https://github.com/jwilder/nginx-proxy#proxy-wide). How large do you need the `client_max_body_size` to be?

**Comment by shadowcodex** [comment]
I was thinking for my uses 100m

I'm not good at docker at all. So getting this to work manually, may take me some time.

**Comment by shadowcodex** [comment]
looks like it is already set too `        client_max_body_size 10M;`. However I'm trying to upload a 1.6mb file and it is failing, a file smaller than 1mb works.

**Comment by zodern** [comment]
For Let's Encrypt, it uses https://github.com/jwilder/nginx-proxy. Currently there is no nginx config for that so it is the default 1mb.

**Comment by shadowcodex** [comment]
Maybe this? https://github.com/zodern/meteor-up/pull/450

**Comment by shadowcodex** [comment]
New PR https://github.com/zodern/meteor-up/pull/451

**Comment by RemyLespagnol** [comment]
This problem affect my server too. 
With the upload of image <1Mb it's work, but not larger images.

For just a profil image upload I can't achieve that, so I think a PR is welcome :)
