### ISSUE TITLE
Error while validating mup.json

### ISSUE THREAD

**Issue by pavanputhra** [zodern/meteor-up#454]
I am getting following error. While my host name is valid and looks something like this 'ec2-12-12-12-12.compute-1.amazonaws.com'

> mup.js has 2 errors:
>   - "host" must be a valid ip address of one of the following versions [ipv4, ipv6] with a optional CIDR
>   - "host" must be a valid uri

**Comment by sirpy** [comment]
i think this should be a warning and not an error.
for example i use a single host alias defined in /etc/hosts

**Comment by lachesis** [comment]
We're seeing this regression as well. Old versions of mup were perfectly happy with a hostname, but new ones give us this error.

**Comment by zodern** [comment]
In version I.2.2 it will only need to be a string.
