### ISSUE TITLE
new mobileSettings still validates for old format

### ISSUE THREAD

**Issue by sirpy** [zodern/meteor-up#455]
mobileSettings is no longer an object but true/false
mup.js has 3 errors:
  - "host" must be a valid ip address of one of the following versions [ipv4, ipv6] with a optional CIDR
  - "host" must be a valid uri
  - In "meteor", "mobileSettings" must be an object

**Comment by zodern** [comment]
Technically `mobileSettings` can be. In the readme, I had added this:
```
     // Remove this property for mobileSettings to use your settings.json. (optional)
      mobileSettings: {
        yourMobileSetting: "setting value"
      },
```

I thought that was better than setting it to false to use settings.json as mobileSettings, What is your opinion?
