### ISSUE TITLE
mup needs --server for mobile

### ISSUE THREAD

**Issue by rajpa** [zodern/meteor-up#456]
Hi

version 1.2.1 throws error when deploying.. it fails asking for --server for mobile.

where should i set this --server?

cheers
rajpa

**Comment by zodern** [comment]
Please post your `mup.js`.

**Comment by rajpa** [comment]
hi @zodern 

here it is...


module.exports = {
  servers: {
    one: {
      "host": "52.6.6.1",
      "username": "ubuntu",
      "pem": "/Users/home/Google Drive/mycompany/pems/myappUbuntu04Aug16.pem"
    }
  },
  meteor: {
    name: 'myapp',
    path: '../../ubunturepository',
    docker: {
      image: 'abernix/meteord:base'
    },
    servers: {
      one: {}
    },
    ssl: {
      port: 443,
      crt: '/Users/home/Google Drive/mycompany/pems/pems/fullchain.pem',
      key: '/Users/home/Google Drive/mycompany/pems/pems/privkey.pem',
    },
    buildOptions: {
      cleanAfterBuild: true // default
    },
    env: {
      "ROOT_URL": "https://myapp.in",
      "PORT": "80",
      "MONGO_URL" : "mongodb://mongodb:27017/myapp",
      "MONGO_OPLOG_URL": "mongodb://mongodb:27017/local",
      "MOBILE_DDP_URL": "https://myapp.in:443",
      "MOBILE_ROOT_URL": "https://myapp.in:443",
      "DDP_DEFAULT_CONNECTION_URL" : "https://myapp.in:443",
      "CLUSTER_WORKERS_COUNT": "auto"      
    },
    deployCheckWaitTime: 60 //default 10
  },

  mongo: { // optional
    port: 27017,
    servers: {
      one: {}
    }
  }
};

**Comment by zodern** [comment]
If you want to build mobile apps when deploying, you can add
```
meteor {
  buildOptions: {
    server: '<server url>'
  }
}
```

If you don't want to build mobile apps, add `serverOnly: true` to the `buildOptions`.

**Comment by rajpa** [comment]
thanks @zodern ! it is working now..

cheers/rajpa
