### ISSUE TITLE
Change app port

### ISSUE THREAD

**Issue by wolganens** [zodern/meteor-up#457]
Hi, I set the port option in the meteor object to 8000 but the deploy still trying to use the port 80, by the way is there a way to forward it to the internet? I'm not talking about production server, just for showing the applications. Thank you and congratulations for the project.

**Comment by mklebrasseur** [comment]
Hi @wolganens,

Try running mup reconfigure.

**Comment by wolganens** [comment]
I make it on a new mup project

**Comment by mklebrasseur** [comment]
The below environment variables work for my config, does yours look similar? 

env: {
      PORT: 8080,
      ROOT_URL: 'http://localhost',                                         MONGO_URL: 'mongodb://localhost/myDB',
      CLUSTER_WORKERS_COUNT: 'AUTO'
    },

**Comment by wolganens** [comment]
My fault, it works, thank you.
