### ISSUE TITLE
Use same nginx container for both ssl options

### ISSUE THREAD

**Issue by zodern** [zodern/meteor-up#458]
- [ ] Improve default nginx config when using Let's Encrypt
- [ ] Support changing port when using Let's Encrypt
- [ ] Look into using https://github.com/jwilder/nginx-proxy for both ssl options

**Comment by shadowcodex** [comment]
@zodern do you have an idea of a timeline to make this change? I'm thinking about the Nginx settings file that we were discussing. If we do use this for both SSL options, then the instructions for the Nginx settings file will be the same for both uses.

**Comment by shadowcodex** [comment]
I think I have this about done.

**Comment by shadowcodex** [comment]
https://github.com/zodern/meteor-up/pull/496 pull request up.

**Comment by zodern** [comment]
This is available in 1.2.9: https://github.com/zodern/meteor-up#reverse-proxy
