### ISSUE TITLE
CDN - Clouflare - Too many redirection

### ISSUE THREAD

**Issue by RemyLespagnol** [zodern/meteor-up#459]
Hi,

I use Cloudflare CDN for my meteor apps.
Before I use the Let's encrypt ssl of meteor-up, I have the first line and the las line with the orange cloud (so with proxy (CDN)).
![image](https://cloud.githubusercontent.com/assets/2819925/22859079/ce4287a4-f0d0-11e6-94a1-e7687c79e487.png)

But with the ssl of meteor-up, now my website is redirect with loop.
So when I go to https://foo.com I see in the console that the website go to  http://foo.com and go to https://foo.com and to http://foo.com... etc...
So the browser stop the request and throw an error.

So if I desactivate the orange cloud for theses lines, no problem of redirection.
But I can't use the feature of Cloudflaire, the CDN proxy...

Do you know why this loop happen ?

**Comment by zodern** [comment]
I can reproduce this and will look into the cause.

**Comment by RemyLespagnol** [comment]
Thanks @zodern , you're rocks :)

**Comment by zodern** [comment]
In the cloudflare dashboard, go to Crypto and try changing it to `Full` or `Full (strict)`

**Comment by RemyLespagnol** [comment]
Before, I set it to off.

Now I test it with full strict.
I activate the proxy for the DNS.

My website still works.
But I think we need to wait for the DNS to be ready to be sure, don't it ?

**Comment by RemyLespagnol** [comment]
So I think it's work now :)

**Comment by PolGuixe** [comment]
@zodern I have also experienced the same. Any idea why this is happening? 
Is this redirect normal?

**Comment by PolGuixe** [comment]
Also the SSL certificate is the one from Cloudflare and not the one from Let's Encrypt. Is there a way to ensure that the Let's Encrypt certificate is working?

**Comment by zodern** [comment]
> Is there a way to ensure that the Let's Encrypt certificate is working?

If your website works when it is set to `Full (strict)`, you know Let's Encrypt is working.

> Any idea why this is happening?

In the cloudflare support, there is two articles on fixing this for Wordpress and Joomla. They seem to say it is from having mixed content.

**Comment by PolGuixe** [comment]
@zodern thanks for your reply. 
> In the cloudflare support, there is two articles on fixing this for Wordpress and Joomla. They seem to say it is from having mixed content.

Could it be due to the nginx configuration?
