### ISSUE TITLE
Expose internal port of Meteor app (different than 3000)

### ISSUE THREAD

**Issue by marcoschwartz** [zodern/meteor-up#460]
Hello,

Might be a simple question, but I wondered if it is possible to expose a port which is used by the Meteor app, other than the port of the app itself. For example, I have a Meteor app creating a Socket.io server on port 8080. It works fine locally, but once deployed I can only access the Meteor app but not the Socket.io server. Is there a way to solve that? Thanks!

**Comment by shadowcodex** [comment]
That can be controlled a lot of different ways, but most likely you will need to forward it through the nginx docker. Depending on which ssl you are using it is different.. Please see the respons @zodern did to my issue here: 

https://github.com/zodern/meteor-up/issues/449

I later created a pull request for adding the option to increase client upload size. May look into doing an array of extra ports to expose.

**Comment by shadowcodex** [comment]
Would have to dynamically add port exposes to the docker creation on the app container. If running proxy would have to map the reverse proxy for those ports as well.

**Comment by zodern** [comment]
It currently is possible to add docker args to publish additional ports in your config. It wouldn't have ssl though.

In your `mup.js` file, add:
```
meteor: {
  docker: {
    ...
    args: ["-p 8080:8080"]
  }
}

```

**Comment by rclai** [comment]
Just an FYI that you may need to do a `mup reconfig` to get this to work.
