### ISSUE TITLE
Old mupx branch

### ISSUE THREAD

**Issue by CarlQLange** [zodern/meteor-up#461]
Hey there,

First off, thanks @zodern for carrying the torch.

Does anybody have a copy of the old `mupx` branch? I have a very old (2yr+) production app, deployed with an old version of `mupx`, that I urgently need to deploy a hotfix to. The main issue is the currently-deployed version doesn't have any of the docker stuff, and I'm worried that using a newer mup version will break all the things.

Sadly it looks like the `mupx` branch here was deleted. Does anybody have a copy of it so it can be reincarnated?

Cheers,
Carl

**Comment by CarlQLange** [comment]
... perhaps I mean `mup` branch? It's been a long-ass time

**Comment by zodern** [comment]
You can find it here: https://github.com/arunoda/meteor-up-legacy/. `arunoda/meteor-up` was renamed to `arunoda/meteor-up-legacy`.

**Comment by CarlQLange** [comment]
ah, fantastic, thanks a lot!
