### ISSUE TITLE
Support Ubuntu 16

### ISSUE THREAD

**Issue by zodern** [zodern/meteor-up#462]

**Comment by shadowcodex** [comment]
I'm running on 16 in AWS and it works fine.

**Comment by zodern** [comment]
I am too with no problems. Though last week I went through all of the open issues, and there are some that  had problems with 16.

**Comment by JohnAllen** [comment]
Let's Encrypt is working fine for me at DO with 16.02

**Comment by shadowcodex** [comment]
I have just recently pushed to DO with the latest 16 image on my droplet. No issues.
