### ISSUE TITLE
502 Bad Gateway When Trying to Use LetsEncrypt/Autogenerate

### ISSUE THREAD

**Issue by maxmatthews** [zodern/meteor-up#463]
I get a 502 Bad Gateway when I include the autogenerate section of ssl below. If I comment it out and redeploy, everything works great. When I load the page, it does load with the cert over https, but it's 502ing. Running `docker logs bxlp-nginx-letsencrypt --tail 500` looks like it has the cert and says it does not need to renew it.

Here are my `mup logs`:
```
[138.197.112.225]
[138.197.112.225]> fibers@1.0.15 install /bundle/bundle/programs/server/node_modules/fibers
[138.197.112.225]> node build.js || nodejs build.js
[138.197.112.225]
[138.197.112.225]`linux-x64-46` exists; testing
[138.197.112.225]Binary is fine; exiting
[138.197.112.225]
[138.197.112.225]> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
[138.197.112.225]> node npm-rebuild.js
[138.197.112.225]
[138.197.112.225]
[138.197.112.225]> bcrypt@1.0.2 install /bundle/bundle/programs/server/npm/node_modules/bcrypt
[138.197.112.225]> node-pre-gyp install --fallback-to-build
[138.197.112.225]
[138.197.112.225]node-pre-gyp ERR! Tried to download: https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz
[138.197.112.225]node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.7.2 (node-v46 ABI) (falling back to source compile with node-gyp)
[138.197.112.225]make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
[138.197.112.225]  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
[138.197.112.225]  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
[138.197.112.225]  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
[138.197.112.225]/opt/meteord/run_app.sh: line 21:     8 Killed                  npm install --unsafe-perm
```

Here's my `mup.js`:
```js
module.exports = {
	servers: {
		one: {
			host: 'IPADDRESS',
			username: 'root',
			pem: 'KEYHERE'
			// password:
			// or leave blank for authenticate from ssh-agent
		}
	},
	meteor: {
		name: 'NAMEHERE',
		path: 'PATHHERE',
		servers: {
			one: {}
		},
		buildOptions: {
			serverOnly: true,
		},
		env: {
			ROOT_URL: 'https://DOMAIN.COM',
			MONGO_URL: 'mongodb://localhost/meteor'
		},
		dockerImage: 'abernix/meteord:base',
		ssl: {
			autogenerate: {
				email: 'EMAIL',
				domains: 'SUB.DOMAIN.COM'
			}
		},
		deployCheckWaitTime: 60
	},

	mongo: {
		oplog: true,
		port: 27017,
		servers: {
			one: {},
		},
	},
};
```

**Comment by shadowcodex** [comment]
What is the log of your nginx docker, not the lets-encrypt docker. 

Did you deploy using a different setup before trying autogenerate?

**Comment by maxmatthews** [comment]
I just wiped my Digital Ocean Droplet and loaded it with Ubuntu 14.04. Ran `mup setup`, then `mup deploy`. Here are my nginx docker logs. This line is of particular interest: 
`*24 connect() failed (111: Connection refused) while connecting to upstream, client: PERSONALIPFILTERED, server: sub.domain.com, request: "GET / HTTP/2.0", upstream: "http://172.17.0.3:80/", host: "sub.domain.com"`
```
forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | 2017/02/14 15:30:15 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
dockergen.1 | 2017/02/14 15:30:15 Running 'nginx -s reload'
dockergen.1 | 2017/02/14 15:30:15 Watching docker events
dockergen.1 | 2017/02/14 15:30:15 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2017/02/14 15:30:32 Received event start for container b3b8e62fa4a7
dockergen.1 | 2017/02/14 15:30:32 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2017/02/14 15:30:32 Received event die for container 55584faf1f41
dockergen.1 | 2017/02/14 15:30:33 Received event start for container 55584faf1f41
dockergen.1 | 2017/02/14 15:30:33 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2017/02/14 15:30:33 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx.1    | localhost 172.17.0.1 - - [14/Feb/2017:15:30:34 +0000] "GET / HTTP/1.1" 503 213 "-" "curl/7.35.0"
dockergen.1 | 2017/02/14 15:31:12 Received event die for container 55584faf1f41
dockergen.1 | 2017/02/14 15:31:12 Received event start for container 55584faf1f41
dockergen.1 | 2017/02/14 15:31:12 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2017/02/14 15:31:12 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx.1    | SERVERIPFILTERED PERSONALIPFILTERED - - [14/Feb/2017:15:31:22 +0000] "GET / HTTP/1.1" 503 615 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
nginx.1    | SERVERIPFILTERED PERSONALIPFILTERED - - [14/Feb/2017:15:31:23 +0000] "GET /favicon.ico HTTP/1.1" 503 615 "http://SERVERIPFILTERED/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
nginx.1    | sub.domain.com PERSONALIPFILTERED - - [14/Feb/2017:15:31:35 +0000] "GET / HTTP/1.1" 502 173 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
nginx.1    | 2017/02/14 15:31:35 [error] 24#24: *5 connect() failed (111: Connection refused) while connecting to upstream, client: PERSONALIPFILTERED, server: sub.domain.com, request: "GET / HTTP/1.1", upstream: "http://172.17.0.3:80/", host: "sub.domain.com"
nginx.1    | SERVERIPFILTERED PERSONALIPFILTERED - - [14/Feb/2017:15:31:38 +0000] "GET / HTTP/1.1" 503 213 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
dockergen.1 | 2017/02/14 15:31:59 Received event die for container 55584faf1f41
dockergen.1 | 2017/02/14 15:32:00 Received event start for container 55584faf1f41
dockergen.1 | 2017/02/14 15:32:00 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2017/02/14 15:32:00 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx.1    | 2017/02/14 15:32:05 [error] 24#24: *8 connect() failed (111: Connection refused) while connecting to upstream, client: PERSONALIPFILTERED, server: sub.domain.com, request: "GET /sockjs/info?cb=w9oypcshfi HTTP/1.1", upstream: "http://172.17.0.3:80/sockjs/info?cb=w9oypcshfi", host: "sub.domain.com", referrer: "http://sub.domain.com/"
nginx.1    | sub.domain.com PERSONALIPFILTERED - - [14/Feb/2017:15:32:05 +0000] "GET /sockjs/info?cb=w9oypcshfi HTTP/1.1" 502 173 "http://sub.domain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
nginx.1    | sub.domain.com 172.17.0.1 - - [14/Feb/2017:15:32:12 +0000] "GET /.well-known/acme-challenge/zN8ZRZ6hRjyZKXyYIoxt1yEAeeHv-KY0V6drR0KkqfM HTTP/1.1" 200 87 "-" "python-requests/2.8.1"
nginx.1    | sub.domain.com 66.133.109.36 - - [14/Feb/2017:15:32:13 +0000] "GET /.well-known/acme-challenge/zN8ZRZ6hRjyZKXyYIoxt1yEAeeHv-KY0V6drR0KkqfM HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
```
(Once again, sub.domain.com is actually the value of my domain and IPs are filtered)

**Comment by shadowcodex** [comment]
port 80 & 443 are open on your box right?

**Comment by maxmatthews** [comment]
Yes

**Comment by maxmatthews** [comment]
When I deploy without any SSL settings, it works great. When I deploy with them in, it crashes both port 80 and 443 with a 502 bad gateway, but it serves that error message over a successfully secured page, so I know the cert generation is working.

**Comment by gaillota** [comment]
+1

**Comment by gaillota** [comment]
Ok, I managed to make it work. Here's what I did:
1) Update Meteor with `meteor update --patch` (may not be relevant and just related to my version of Meteor)
2) Specify the images to use in the docker option:
```
docker: {
    image: 'abernix/meteord:base',
    imageFrontendServer: 'meteorhacks/mup-frontend-server'
}
```
Hope this works for you as well

**Comment by maxmatthews** [comment]
Still no luck. Tried wiping the server with a clean Ubuntu 14 image, updating meteor, adding the docker section @gaillota mentioned, running `mup setup` then `mup deploy` and I still get a 502. Would love any other suggestions.

**Comment by maxmatthews** [comment]
AH HA! Got it. It was a memory error, although I never saw any issues in the logs. I upgraded my DO droplet from 512 MB RAM to 1 gb and ran the deploy. All of a sudden, everything started working great. However, when I scale it back down to 512 mb, everything crashes again. Any suggestions on how I can make it work on only half a gig of RAM?

**Comment by ivanthemeh** [comment]
Does this not work on ubuntu 16? I am having the same issues as you except Im using an instance with 1gb of ram..

**Comment by maxmatthews** [comment]
@ivanthemeh Check out https://github.com/zodern/meteor-up/issues/462. Looks like some people were having issues with Ubuntu 16.

**Comment by ivanthemeh** [comment]
@maxmatthews SO now Im able to deploy it but my server is refusing to connect...its an aws instance and I know the ports are open but its not working...any help please!
Its starting my app on port 80 even though Im setting it to 3001 and its showing 3001=>80 in docker ps so is that the problem?


OK so that was it, how can I fix that? Its setting the port right in the docker container but doesnt start meteor on the right port?

**Comment by maxmatthews** [comment]
@ivanthemeh I would recommend wiping your AWS instance and your mup file, then reinitializing it with only the fields you absolutely need (leave the docker image alone) and only add the SSL/autogenerate section. Make sure you're on 1 GB of RAM and then rerun `mup setup` and `mup deploy`. I've spent several hours on a couple different issues and the two biggest things I've found is that mup simply doesn't like .5 gb of RAM and fails all over the place unexpectedly AND it doesn't handle issues in the `mup.js` file well.
I'm going to close this issue for now because most of my issues were RAM related, but if you continue to have issues after doing a clean install, let me know and I'll try to help out.

**Comment by gaillota** [comment]
The app start on port 80 inside the meteor container, but it exposes the port you decide in your configuration, in your case 3001. So no, I don't think that's the problem.

**Comment by maxmatthews** [comment]
@gaillota I think it was all RAM related. As soon as I upgraded to 1 GB of RAM suddenly all my issues disappeared. I was having problems with SSL and Ubuntu 14 vs 16 and both work fine on enough RAM.

**Comment by ivanthemeh** [comment]
@maxmatthews @gaillota how can I force the app to start on port 3001?
How come when I specify the app port to 80 it works? but when I set it to anything else it breaks it? Something is going on and I have no idea how to even track it down and help would be AWESOME please!

I need to be able to put more than one app on a server thats why I need to get this port thing figured out.

Please help me figure this out, Ill be eternally grateful.

**Comment by gaillota** [comment]
@maxmatthews sorry, I was answering @ivanthemeh.
Did you try to add indexes to your Mongo database. 
A friend of mine was having serious CPU overload (it went up to 120% with just a few users) and it decreased down to ~10% when he added indexes on Mongo.
It was caused by some composite publications

Maybe you can try that, see if that works

**Comment by gaillota** [comment]
@ivanthemeh I don't think you can but it doesn't matter. All that matter is the port exposes by the container, which is the port mapped to the port 80 of the container.

**Comment by ivanthemeh** [comment]
@gaillota are you talking about multiple apps on a single server? Im certain you can do that with the port mapping I used to do it with mupx.

**Comment by ivanthemeh** [comment]
@maxmatthews shouldnt this be backwards for it to work with port mapping ? ```0.0.0.0:3001->80/tcp```

**Comment by maxmatthews** [comment]
@ivanthemeh I don't think my problem was a mapping issue with docker -> meteor, I think it was meteor wasn't booting because it didn't have enough RAM.

**Comment by ivanthemeh** [comment]
@maxmatthews so you cant help? Should I make my own issue i guess?

**Comment by maxmatthews** [comment]
@ivanthemeh I'm pretty sure that you can't change the port if you're using the autogenerate option. It's listed as an enhancement here: https://github.com/zodern/meteor-up/issues/458

**Comment by ivanthemeh** [comment]
@maxmatthews Im not using the autogenerate currently

**Comment by maxmatthews** [comment]
@ivanthemeh Make your own issue and post the link here and we can jump on that thread. Will make it easier for more people to follow both our issues as I think they are separate. Happy to help you once you do that.

**Comment by ivanthemeh** [comment]
@maxmatthews https://github.com/zodern/meteor-up/issues/471

**Comment by mackbrowne** [comment]
@maxmatthews I needed this fix today.  Thank you.  After upgrading to a 1gb digitalOcean droplet, everything worked great.  It really cut down on the random fails I'd get once in a while with the smaller droplets.  

@zodern are the minimum requirements specified anywhere in the readme?  It seems if autogenerate is being used, a 1gb seems to be the minimum requirement for RAM.  Using ubuntu 14.04, etc.  I'd be happy to write a "recommended minimum requirements" section for the readme and send you a PR?  I could at least start the section for my experiences on both AWS and DigitalOcean.

**Comment by zodern** [comment]
@mackbrowne it would be appreciated if you create a PR to add a `recommended minimum requirements` section.

**Comment by janzheng** [comment]
I upgraded my DigitalOcean droplet to 1gb and still having the Bad Gateway issue. Anyone encountering the issue at 1gb?

**Comment by zodern** [comment]
@janzheng Could you please post your app logs from `mup logs --tail 100`?

**Comment by janzheng** [comment]
it worked about half an hour after I posted it. All I did was keep trying to re-setup and re-deploying with the autogenerator and ssl turned on and off.

The worst(?) part is that I can't seem to recreate the conditions for when it actually broke. Next time I redeploy and it breaks again I'll post the logs, but it seems like deploying... sometimes works and sometimes doesn't (which is never a good thing). I'll keep you posted after more testing.

Thanks for working on this @zodern

**Comment by louwers** [comment]
Deploying without SSL and after that with SSL after that worked for me.

Also use the `force-ssl` package.

**Comment by enzolutions** [comment]
@louwers force-ssl is a metero npm package or some kind of mup option or settings in mup.js? Thanks in advance

**Comment by zodern** [comment]
@enzolutions Meteor Up has [an option to force ssl](http://meteor-up.com/docs.html#redirect-http-to-https). There also is a [meteor package](https://atmospherejs.com/meteor/force-ssl) which does the same thing.
