### ISSUE TITLE
[Question] Migration from mupx-letsencrypt@meteor14 to mup

### ISSUE THREAD

**Issue by MuyBien** [zodern/meteor-up#466]
Hi!

I was using mupx-letsencrypt for meteor 1.4 to have the let's encrypt support. But I see now that mup have this now. Can I go back using mup and have the let'sencrypt support?

What can be the step to migrate a project already deployed with mupx to mup ? Maybe change the docker image to use the same as mupx? The `kadirahq:meteord` docker?

Thanks

**Comment by MuyBien** [comment]
I just SSH to a mupx-letsencrypt app deployed, and the docker used is the `abernix/meteord:base`. The same is recommended with a Meteor >1.4 for mup. MupX and Mup use both letsencrypt-companion. So I think there are compatible.

Now I'm just wondering if I need to reconfigure the server <ith mup or with a deploy I can switch from a mupx deployed app to a mup deployed app...

**Comment by zodern** [comment]
The [migration section in the readme](https://github.com/zodern/meteor-up#migrating-from-meteor-up-0x) applies to migrating from mupx to mup. If you are using the latest version of mup (1.2 or newer), it will warn you of most problems in your `mup.js` file.

In your `mup.js`, you will want to change the docker image to `abernix/meteord:base`.

**Comment by shadowcodex** [comment]
@MuyBien did you get this converted over?

**Comment by MuyBien** [comment]
I didn't convert for the moment, but someday I will... I will post here if any problem
