### ISSUE TITLE
Cannot connect to localhost while offline

### ISSUE THREAD

**Issue by ghost** [zodern/meteor-up#468]
I have deployed a meteor app to a local machine on my network. It runs perfectly fine when the machine is connected to the Internet. In fact, it still runs fine if I start with internet initially and then disconnect the internet.

However, if I disconnect from the internet and then restart the machine, I cannot access the meteor instance from the network or even 'localhost' from a browser on the machine. The docker containers for meteor and mongo keep running. (Checked it using docker ps) I can also access the mongo instance using localhost:27017. But I cannot access meteor. I have tried localhost, localhost:80, 127.0.0.1, and other variations to no avail.

But then, if I connect to Internet once and then disconnect, it starts working again.
Here's my mup.js file.

```
module.exports = {
  servers: {
    one: {
      host: '192.168.1.132',
      username: 'root',
      password:'password'
    }
  },
  meteor: {
    name: 'qmpro',
    path: '..',
    docker: {
      image: 'abernix/meteord:base' 
    },
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://localhost',
    },
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

Have been trying to get my head around this issue since 3 days. Can you suggest a path ahead?

I am trying this on a fresh install of Ubuntu 16.04.1 LTS
Browser : Firefox, Chrome

The error that I get on Chrome is - 

This site can't be reached.
The connection was reset.

**Comment by maxmatthews** [comment]
This is a shot in the dark, but try changing your `ROOT_URL` to `http://127.0.0.1` and then attempt to access your app directly through the IP. Funky things can happen sometimes with `localhost`.

**Comment by ghost** [comment]
I did try to change the URL to other values including 127.0.0.1 
But even that didn't work.

**Comment by maxmatthews** [comment]
I'm not sure if I can help at all. The meteor server is not designed to be used in an offline environment. There are certain pieces of meteor that handles if the client looses connection to a server , but not if the server is offline. 
Can you tell me a little bit more about your use case? Do you need to be able to have a server recover that looses an internet connection a lot, or are you somehow trying to run a server in another offline configuration?

**Comment by ghost** [comment]
So basically I'm using meteor to run an offline server on a local intranet. The network doesn't have internet connection. 

Now I have been running this setup for quite some time without meteor up with no issues at all. I would just manually build the code, copy it to the machine, install mongodb and node on the machine and then run the code everytime I started the machine.

Now instead of this manual process, I'm trying meteor-up  to deploy the updates.

The issue is not with using meteor offline as I've already used it before in the same configuration and environment. 

I think the issue is somewhat related to docker networking.  The docker containers run fine but maybe the internal network is unreachable from the host machine.

**Comment by shadowcodex** [comment]
I'm almost certain this is a docker related issue. I'll try to recreate from my end.
