### ISSUE TITLE
 [Question] Clarification on Accessing Mongo

### ISSUE THREAD

**Issue by JohnAllen** [zodern/meteor-up#469]
Before I do a ton of time consuming auth setup experiments to verify what the README states -- that `You can't access the MongoDB from outside the server.` -- can I ask someone to clarify this statement and in general how we can interact with MongoDB when deploying with `meteor-up`?  

Right now, I can access mongo on the same server but outside of the deployment.  So I'm wondering exactly what is the issue with external access.  Is it that the mongo instance can only be bound to `0.0.0.0` or what is it?  I do not need to run any `docker ...` commands to access mongo which is contrary to the README.

Appreciate any answers and happy to pr documentation changes if there are any needed updates.

**Comment by gjr-qm** [comment]
When you deploy Mongo with Meteor Up it spins up a seperate MongoDB container that is not accessible from the outside.

The way to get around it: I use RoboMongo with an SSH tunnel to connect to Mongo (you can configure that in the connection settings). You can also setup a tunnel manually of course, but i like RoboMongo for the job.

**Comment by zodern** [comment]
>  I do not need to run any `docker ...` commands to access mongo which is contrary to the README.

Are you able to access the mongo shell without docker commands?

**Comment by gjr-qm** [comment]
I do have to use docker commands if i deploy with mongodb. That is because mongo is not installed on the server hosting the docker containers. So i have to use the mongo within the container.

 But the most convenient way for me to access the database from my computer is to use RoboMongo with an SSH tunnel. The SSH tunnel makes the mongodb url available for Robomongo that uses my local mongo installation.

 Feel free to ask for more info if you need it.

**Comment by JohnAllen** [comment]
Thanks for your comments.

If I install `mongo-client` then I can access the mongo instance running inside the docker container.  I have not tried accessing it locally, but it sounds like this is possible and seems like it would be to me too.

I am asking this because I want to be able to insert docs from another server, really another Meteor app.

**Comment by zodern** [comment]
One option to access Mongodb from other servers might be this: https://docs.docker.com/engine/admin/ambassador_pattern_linking/

**Comment by gjr-qm** [comment]
Interesting @zodern, i will have a look at that too.

For production servers, I prefer to use a separate MongoDB replica set instead of relying on the MongoDB installation that is done with meteor-up. That way you'll have total control over security and access.

**Comment by gjr-qm** [comment]
@JohnAllen correct me if I'm wrong, but wouldn't it be better to exchange data between apps with an API (or separate DDP connection since they are both Meteor apps)?

**Comment by JohnAllen** [comment]
I have been planning on inserting content straight into the database -- as a central data store that both apps can access.  One app is a web-crawler, essentially, that inserts data into the database that is analyzed and is later served to users.  I've just thought as the DB being the optimal way of inserting, analyzing and serving data, but I will think about other ideas some more.  The data does need to be stored permanently for future display to users.  I could perhaps restructure/refactor but would probably go a normal un-dockerized Mongo instance before I do that.
