### ISSUE TITLE
 mup logs [SyntaxError: Unexpected token ILLEGAL]

### ISSUE THREAD

**Issue by chenmoran** [zodern/meteor-up#470]
First run mup setup is fine. But second run mup  setup or mup deploy , [SyntaxError: Unexpected token ILLEGAL].Why?

**Comment by maxmatthews** [comment]
Can you post your `mup.js` file and `mup logs --tail 50`?

**Comment by chenmoran** [comment]
Same wrong.
mup logs --tail 50
[SyntaxError: Unexpected token ILLEGAL]

**Comment by chenmoran** [comment]
module.exports = {
  servers: {
    one: {
      host: ’xxx.xxx.xxx.xxx’,
      username: 'root',
      // pem:
       password:’xxxx’
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: ‘test’,
    path: '/Desktop/test’,
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://xxx.xxx.xxx.xxx',
      MONGO_URL: 'mongodb://localhost/meteor',
    },

    // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
    dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 60,
    
    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: false
  },

  mongo: {
    oplog: true,
    port: 27017,
    version: '3.4.1',
    servers: {
      one: {},
    },
  },
};
This is my mup.js.
mup logs --tail 50
[SyntaxError: Unexpected token ILLEGAL]

**Comment by chenmoran** [comment]
@maxmatthews Thanks.My mup.js is wrong.

**Comment by maxmatthews** [comment]
If you've found your issue, feel free to close your issue!
