### ISSUE TITLE
unknown update text during `mup deploy`

### ISSUE THREAD

**Issue by avishaan** [zodern/meteor-up#473]
I see the following on my current deploy, my last deploy was about 2 months ago if that makes a difference. Is this saying that my mup version on the server is incorrect?

![image](https://cloud.githubusercontent.com/assets/5360982/23076404/2b87b0f6-f4f5-11e6-8437-08ce894502f9.png)

this is followed up with an error when I `mup deploy`
![pasted_image_2_17_17__9_41_am](https://cloud.githubusercontent.com/assets/5360982/23076443/58c909de-f4f5-11e6-8053-20718473841a.png)

**Comment by zodern** [comment]
The update message is shown because you are using an old version of mup. Run `npm i -g mup` to update it. Newer versions have a better message.

**Comment by avishaan** [comment]
thanks for the reply, appreciate you taking over this repo
