### ISSUE TITLE
nginx docker config

### ISSUE THREAD

**Issue by ivanthemeh** [zodern/meteor-up#475]
Im wondering if anyone is aware of how I could set these in the docker nginx server block?

proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_buffer_size          128k;
proxy_buffers              4 256k;
proxy_busy_buffers_size    256k;

**Comment by zodern** [comment]
If you are not using ssl, you can start your own nginx container on the server.
If you are using custom ssl certificates, you can fork https://github.com/meteorhacks/mup-frontend-server and modify it's nginx config.

Eventually it will be much easier to customize the nginx config.

**Comment by ivanthemeh** [comment]
@zodern does the front end not get reset on every deploy?

**Comment by zodern** [comment]
Yes. If you fork it and make your custom config part of the image, it should be fine.

**Comment by ivanthemeh** [comment]
@zodern Im not sure how to do that, how would I install my forked package instead of yours? Sorry Im a nub.

**Comment by zodern** [comment]
You will need to publish it to the docker hub.
Then, in your config add this, and change it to the name you used when publishing to the docker hub.
```js
meteor: {
  ...
  docker: {
      // (optional) Only used if using your own ssl certificates. Default is "meteorhacks/mup-frontend-server"
      imageFrontendServer: 'meteorhacks/mup-frontend-server'
  }
}
```

I'm sorry it isn't any easier right now to customize the nginx config.

**Comment by ivanthemeh** [comment]
@zodern I just tested adding those settings to the nginx-proxy and it got rid of the 502 bad gateway. SO I know it works just need to get it in the fork and publish to docker which Im working on atm.

**Comment by ivanthemeh** [comment]
@zodern how can I edit the nginx-proxy that gets used? Right now its jwilder/nginx proxy but I have no Idea where to change it to a fork of mine? Please and thanks.
I cant even figure out how to clone a github repo and make a docker hub of it that I can pull 😢 
and it sucks because all I need to add is either a file to /etc/nginx inside the container or add three lines of code to the conf.d/default.conf file..

**Comment by ivanthemeh** [comment]
@zodern ok so I figured out how to make an automated build using a fork of a github repo so thats cool, now ALL I should have to do is edit the jwilder/niginx-proxy to mine right? Where would I do that at lol? I searched through some of the mup files and folders and was unable to figure out where to put it. Please and thanks!

**Comment by zodern** [comment]
The instructions I gave you were for if you were using the `mup-frontend-server`. I am sorry if you went through extra work because of that. If you are using `nginx-proxy`, it is much simpler. You can fork `meteor-up`, and add your modifications [here](https://github.com/zodern/meteor-up/blob/master/src/modules/meteor/assets/templates/start.sh#L64).

Run `npm install -g` in the folder containing your modified version of `meteor-up` to use your version. Run `mup deploy` to update the config.

**Comment by shadowcodex** [comment]
@zodern is this something we could use the inject I made to pull in a text field from the mup.js file? So people could write their own nginx config in that text field and just import it that way?

**Comment by zodern** [comment]
yes, or copy it from a file.

**Comment by shadowcodex** [comment]
@zodern I'll look at creating a PR request for this. Look for one coming in the next week or two.

**Comment by ivanthemeh** [comment]
@shadowcodex according to the jwilder/nginx-proxy adding a file at /etc/nginx/proxy.conf allows changing the config. I have no idea how to do that it it may help you.

**Comment by shadowcodex** [comment]
@ivanthemeh I already have this system setup on this PR https://github.com/zodern/meteor-up/pull/451

Thanks!

**Comment by shadowcodex** [comment]
Gonna work on this in a few. In tandem with https://github.com/zodern/meteor-up/issues/458

**Comment by shadowcodex** [comment]
Pull request up: https://github.com/zodern/meteor-up/pull/496

**Comment by shadowcodex** [comment]
@zodern want to add this to current milestone?

**Comment by Twisterking** [comment]
+1 for being able to use my own nginx config file!
Why do I need this?
During downtimes or if something just goes badly wrong I would like to show a custom 502 error page instead of the standard "bad gateway" to show the users that there is something wrong and that the problem is being worked on. Even better would be to trigger a redirect in the nginx proxy in case of an 502 error to a predefined url.
Will I be able to do this with this option in the future?

btw: big thanks to @zodern and @shadowcodex for all the hard work your guys are putting into this project!!

**Comment by enzolutions** [comment]
Hi @ivanthemeh 

Looks like did you resolve the issue that is driving me crazy. I am wondering if you manage to publish a docker image to share with the community.

If not, could you tell me what image I have to fork and what files I need to change and the specific change, to try to do on my side.

Thanks in advance.

**Comment by zodern** [comment]
Mup 1.4 supports customizing the nginx config. You can try the beta using the instructions in #870. The docs for this feature are [here](https://github.com/zodern/meteor-up/blob/dev/docs/docs.md#custom-nginx-config).

**Comment by mvogttech** [comment]
> Mup 1.4 supports customizing the nginx config. You can try the beta using the instructions in #870. The docs for this feature are [here](https://github.com/zodern/meteor-up/blob/dev/docs/docs.md#custom-nginx-config).

Are there any updates on how to use customized Nginx images from the docker repository?

The reason I want a custom image/config is to be able to bundle Nginx with Google's Pagespeed Module. Is this possible?
