### ISSUE TITLE
Do you support Mongo outside of Docker?

### ISSUE THREAD

**Issue by dufia** [zodern/meteor-up#48]
There are issues with it on mupx:

https://github.com/arunoda/meteor-up/issues/758

I am looking for a working alternative, thanks.

**Comment by madushan1000** [comment]
You can use a separate mongodb installation by setting MONGODB_URL (This is the recomanded way by the way)

**Comment by dufia** [comment]
Hey Madushan,

I can't get it to work right now. I will give it another shot when you are closer to the final release. Currently I get this errors while trying to setup, maybe you find it helpful:

    Started TaskList: Setup Docker
    [1.2.3.4] - setup docker

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: Timed out while waiting for handshake
        at [object Object]._onTimeout (/development/node/nauka/meteor/meteor-up/node_modules/nodemiral/node_modules/ssh2/lib/client.js:138:17)
        at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)


Mupx sets up with no problems. Are you sure the new Meteor-up will support Mongo outside of the Docker? Thanks and have a great day!

**Comment by madushan1000** [comment]
This is probably related to issue https://github.com/kadirahq/meteor-up/issues/49
