### ISSUE TITLE
Install dependencies in a Docker container e.g. GraphicsMagick

### ISSUE THREAD

**Issue by PolGuixe** [zodern/meteor-up#480]
How we can specify to install GraphicsMagick or another dependency in the Docker container when we deploy?

**Comment by zodern** [comment]
Right now the only option is to use your own docker image.

**Comment by PolGuixe** [comment]
I know that I can modify abernix's image https://hub.docker.com/r/meteorhacks/meteord/

Once it's modified do I need to push that image the docker hub?

**Comment by zodern** [comment]
Yes.

**Comment by PolGuixe** [comment]
According to this: http://stackoverflow.com/questions/31901697/meteor-up-docker-and-graphicsmagick
I need to modify the DockerFile in the image, but which DockerFile 🤔 
-`base/DockerFile`
-`binbuild/DockerFile`
-`devbuild/DockerFile`
-`onbuild/DockerFile`

all of them?

**Comment by zodern** [comment]
You should modify `base/DockerFile`.

**Comment by PolGuixe** [comment]
I've just found this image that it is doing exactly what I wanted: https://github.com/c316/meteor-graphicsmagick
