### ISSUE TITLE
mongo oplog setting?

### ISSUE THREAD

**Issue by gjr-qm** [zodern/meteor-up#481]
In the mup.js example from the README.md there is an oplog setting:

```
  mongo: { // (optional)
    oplog: true, // <-------------
    port: 27017,
    version: '3.4.1' // (optional), default is 3.4.1
    servers: {
      one: {},
    },
  },
```

In the source, I see no references to this setting or references to a replication set (which is needed if you want to have oplog functionality). I suspect this setting doesn't do a thing in the current version.

Maybe remove this from the example and code and make a separate issue for implementing it?

I wish I had enough time/knowledge to help implement this...

@zodern: Keep up the good work, I really appreciate your massive efforts to keep this repo alive.

**Comment by zodern** [comment]
Your right, it currently doesn't do anything. After I finish improving the tests, I need to go through the documentation.

In issue #21 there is [this comment](https://github.com/zodern/meteor-up/issues/21#issuecomment-238032995) that explains how to enable it.

**Comment by gjr-qm** [comment]
Thanx again! Maybe I have a look into it later.
