### ISSUE TITLE
Delete bundle files after deployment

### ISSUE THREAD

**Issue by mariusglauer** [zodern/meteor-up#482]
Currently the /tmp directory is full of bundle files. If you don't restart your computer on a regular basis (what most macOS users don't do), much disk space is taken from these files.
I'd suggest to automatically delete the bundle files + the archived bundle after a successful deployment.

**Comment by shadowcodex** [comment]
@gbhrdt I don't think we should delete the created bundle file especially if someone is deploying to another server soon. I think deleting all others except the most recent one would be appropriate.

It has been talked before about reusing a bundle for a redeploy.

**Comment by zodern** [comment]
In 1.2.4, the default path for builds uses the app's absolute path as a seed when creating the uuid, so the build path will always be the same for the app. As long as you don't move the app there will only be one bundle remaining after builds.
