### ISSUE TITLE
How to verify issues with Lets Encrypt Auto generation

### ISSUE THREAD

**Issue by btbjosh** [zodern/meteor-up#483]
I have ssh access to my server but I don't know how to verify how or why the autogeneration of my certs have not worked...

I am trying to deploy to two servers simultaneously (which does work) ... both have the same sub domain for the auto gen via LetsEncrypt. Is this a problem? Are there some docker commands that I can see what happened with the LetsEncrypt?

Also, it's not clear in the docs when this actually happens. Does it happen on `mup setup` or on `mup deploy`?

Thanks!

**Comment by shadowcodex** [comment]
It's setup on deploy or start.

You can view what docker containers you have running on the server with `docker ps`.

To view the logs on the container you can do `docker logs <container>`.

In your case, you will have two Nginx dockers running. One for the let's encrypt auto generation, and one for the regular Nginx. You can use the logs command to view what is happening on them.

**Comment by btbjosh** [comment]
@shadowcodex Thanks for the help! I'll take a look and see what's going on.

**Comment by btbjosh** [comment]
Weird. My first server only shows the `abernix/meteord:base` image.. Just that one container. Shouldn't there be at least two containers if you're telling me there are separate containers for the nginx apps?

**Comment by shadowcodex** [comment]
Try `docker ps -a`

**Comment by btbjosh** [comment]
Yeah, just that one is listed. I'm redeploying now to see if I can remedy that. I was having issues with the `ssl` object in the mup.js file preventing the server from operating so I commented it out. Then both servers worked flawlessly without their ssl. So I'm trying to add it back, without much luck. 

I got my staging server (separate sub domain) working perfectly with the `ssl` generation. Not sure why these are proving to be so tricky.

**Comment by btbjosh** [comment]
ok... so I got my error now.

````2017-02-22 23:08:47,513:ERROR:acme.challenges:256: Unable to reach http://app.countmein.online/.well-known/acme-challenge/SO05QWT_hFOn3uhKqVceO2EeWkrxnB0WM0i7Y0LAniE: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
2017-02-22 23:08:47,514:WARNING:simp_le:1303: app.countmein.online was not successfully self-verified. CA is likely to fail as well!
2017-02-22 23:08:47,649:INFO:simp_le:1313: Generating new certificate private key
2017-02-22 23:08:52,441:ERROR:simp_le:1271: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/gsSlh9PyWi5Z5k27XdDho3-6MZj7IG9pYTtwFTOWz2o
Challenge validation has failed, see error log.

**Comment by btbjosh** [comment]
I think I know why it's failing but I'm not sure how to fix it. I am trying to use a Digital Ocean load balancer. The load balancer has the certificate domain a record. So it points to the load balancer ip which is not the same as the two desired backend server ips that are getting set up by mup. Anyone know how to resolve this setup? Do I need to manually generate the cert?

**Comment by shadowcodex** [comment]
I would recommend manually generating and injecting the cert.
