### ISSUE TITLE
Nginx-proxy docker image does not restart after server reboot

### ISSUE THREAD

**Issue by PolGuixe** [zodern/meteor-up#484]
**Context:** 
- Runing on ubuntu 16.04 in AWS EC2. 

**Steps to reproduce:**
- Just run `sudo reboot` and wait for restart. 
- Then do `docker ps`: 
```
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS               
0047a1075814        jrcs/letsencrypt-nginx-proxy-companion   "/bin/bash /app/en..."   13 minutes ago      Up 5 minutes                          
5e4d8f24d93d        joshjoe/meteor-graphicsmagick            "/bin/sh -c 'bash ..."   14 minutes ago      Up 5 minutes        80/tcp
```

It is missing the nginx-proxy image

**Comment by ivanthemeh** [comment]
@PolGuixe did you ever figure this out? Im having this issue as well.

**Comment by zodern** [comment]
Running `mup restart` should start the proxy again.

**Comment by ivanthemeh** [comment]
@zodern that's fine but what if it goes down and I'm not there then my app is down. Shouldn't it restart automatically?

**Comment by zodern** [comment]
It is a temporary fix.  I will add auto-restart next week.

**Comment by shadowcodex** [comment]
@zodern @ivanthemeh @PolGuixe this is fixed in https://github.com/zodern/meteor-up/pull/496

**Comment by PolGuixe** [comment]
@shadowcodex cool! thanks. 

@zodern will you publish the next version soon?

**Comment by shadowcodex** [comment]
@PolGuixe He will as soon as we finish milestones for it.

**Comment by zodern** [comment]
As soon as the pull request is merged.

**Comment by zodern** [comment]
Version 1.2.3 was just published with a fix.
