### ISSUE TITLE
Issues with certificates subdomains

### ISSUE THREAD

**Issue by PolGuixe** [zodern/meteor-up#486]
I opened this issue there: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/176

I think it should also be here.

**Comment by shadowcodex** [comment]
if you haven't yet, you need to fix your dns routing to that subdomain.

**Comment by PolGuixe** [comment]
@shadowcodex what do you exactly mean? 

This is my configuration: 
- **Server 1** with IP **XX.XX.XX.XX** host the production app. DNS points **example.com** and **www.example.com** to **XX.XX.XX.XX**. **Server 1** also hosts the SSL certificates for **example.com** and for **www.example.com**.
- **Server 2** with IP **YY.YY.YY.YY** host the staging app. DNS points **staging.example.com** to **YY.YY.YY.YY**.

**Comment by shadowcodex** [comment]
if you ping that host name, is it responding with YY.YY.YY.YY?

your mup.js should be something like this. Best practice IMO is to use separate mup.js and settings.js files for each environments.

```js
module.exports = {
  servers: {
    one: {
      host: 'YY.YY.YY.YY',
      username: 'root',
      // pem: '/home/user/.ssh/id_rsa',
      // password: 'password',
      // or leave blank to authenticate using ssh-agent
      opts: {
          port: 22,
      },
    }
  },

  meteor: {
    name: 'app',
    path: '../app',    
    },
    docker: {
      image: 'kadirahq/meteord', // (optional)   
      imageFrontendServer: 'meteorhacks/mup-frontend-server'
    },
    servers: {
      one: {}, // list of servers to deploy, from the 'servers' list
    },
    buildOptions: {
      serverOnly: true, // skip building mobile apps, but still build the web.cordova architecture
      debug: true,
      cleanAfterBuild: true, // default
      buildLocation: '/my/build/folder', // defaults to /tmp/<uuid>
    },
    env: {
      // PORT: 8000, // useful when deploying multiple instances (optional)
      ROOT_URL: 'https://staging.example.com', // set to https to force redirect from http
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    ssl: {
      // Enables let's encrypt (optional)
      autogenerate: {
        email: 'email.address@domain.com',
        domains: 'staging.example.com' // comma seperated list of domains
      }
    },
    deployCheckWaitTime: 60, // default 10

    // Shows progress bar while uploading bundle to server (optional)
    // You might need to disable it on CI servers
    enableUploadProgressBar: true // default false.
  },

  mongo: { // (optional)
    oplog: true,
    port: 27017,
    version: '3.4.1' // (optional), default is 3.4.1
    servers: {
      one: {},
    },
  },
};
```

**Comment by PolGuixe** [comment]
@shadowcodex yes, if I ping the host name it replies with YY.YY.YY.YY, when it is not routed through Cloudflare. 

This is how my configuration looks like 😉.
In the ssl, configuration, if I am missing **example.com**, from the domain field I am getting a `base domain missing error`.

Does this configuration works for you?

**Comment by shadowcodex** [comment]
Yes I don't have base domain in mine, just the subdomain.

**Comment by shadowcodex** [comment]
@PolGuixe lemme get this current PR finished up for nginx, and then I'll come back to this issue. I'm really curious as to why it's not able to verify itself. Something isn't routing right in your DNS is my assumption.
