### ISSUE TITLE
How to access the volumes of running volumes?

### ISSUE THREAD

**Issue by PolGuixe** [zodern/meteor-up#488]
How can I see the content of the volumes? 

Is the data persistent, even if I deploy again?

**Comment by zodern** [comment]
> How can I see the content of the volumes?

If you `ssh` on to the server, you can use the command line to view the volume's content. Volumes are located at the host path you provide in the config. Is that what you are asking?

The data does persist.

Volumes should be better documented in the Readme.

**Comment by PolGuixe** [comment]
I see now. I misunderstood how volumes work. I thought the volumes where inside the container. 😓
