### ISSUE TITLE
Build Error:

### ISSUE THREAD

**Issue by ja1sh** [zodern/meteor-up#490]
`$ mup deploy 
Building App Bundle Locally
{ cwd: '/media/jaisharma/72FA1EB1FA1E7199/helloMeets/web/hellomeets/HelloMakersWebApp' }
{ [Error: spawn meteor ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn meteor',
  path: 'meteor',
  spawnargs: 
   [ 'build',
     '--directory',
     '/tmp/03b22d37-b9c7-4b3d-852a-fd6c39cad4e3',
     '--architecture',
     'os.linux.x86_64',
     '--debug',
     '--server-only' ] }

=> Build Error. Check the logs printed above.
`

**Comment by Cu4rach4** [comment]
did you install meteor?

curl https://install.meteor.com/ | sh

wish version of node do you have installed?

**Comment by ja1sh** [comment]
I reinstalled meteor, and its working.
Thanks :100:
