### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by wolganens** [zodern/meteor-up#494]
Hello, at first, I was able to deploy my app to a digital ocean droplet, everything 100%, today after some changes I run  mup deploy again and there is no erros but when I try to access the app page i get this 502 bad gateway error.

Thank you very much and sorry about the bad english.

**Comment by Cu4rach4** [comment]
i have almost the same problem, but this is my logs --tail=50

> [app.vita-fx.org]  "uv": "1.9.1",
> [app.vita-fx.org]  "v8": "4.5.103.43",
> [app.vita-fx.org]  "zlib": "1.2.8"
> [app.vita-fx.org]}
> [app.vita-fx.org]npm WARN meteor-dev-bundle@0.0.0 No description
> [app.vita-fx.org]npm WARN meteor-dev-bundle@0.0.0 No repository field.
> [app.vita-fx.org]npm WARN meteor-dev-bundle@0.0.0 No license field.
> [app.vita-fx.org]=> Starting meteor app on port:80
> [app.vita-fx.org]Kadira: Successfully connected
> [app.vita-fx.org]
> [app.vita-fx.org]/bundle/bundle/programs/server/node_modules/fibers/future.js:300
> [app.vita-fx.org]						throw(ex);
> [app.vita-fx.org]						^
> [app.vita-fx.org][object Object]
> [app.vita-fx.org]
> [app.vita-fx.org]> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
> [app.vita-fx.org]> node npm-rebuild.js
> [app.vita-fx.org]
> [app.vita-fx.org]
> [app.vita-fx.org]> bcrypt@0.8.5 install /bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt
> [app.vita-fx.org]> node-gyp rebuild
> [app.vita-fx.org]
> [app.vita-fx.org]make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build'
> [app.vita-fx.org]  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
> [app.vita-fx.org]  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
> [app.vita-fx.org]  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
> [app.vita-fx.org]  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
> [app.vita-fx.org]  COPY Release/bcrypt_lib.node
> [app.vita-fx.org]make: Leaving directory '/bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build'
> [app.vita-fx.org]bcrypt@0.8.5 /bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt
> [app.vita-fx.org]bindings@1.2.1 /bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings
> [app.vita-fx.org]nan@2.0.5 /bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/nan
> [app.vita-fx.org]{
> [app.vita-fx.org]  "meteor-dev-bundle": "0.0.0",
> [app.vita-fx.org]  "npm": "3.10.10",
> [app.vita-fx.org]  "ares": "1.10.1-DEV",
> [app.vita-fx.org]  "http_parser": "2.7.0",
> [app.vita-fx.org]  "icu": "56.1",
> [app.vita-fx.org]  "modules": "46",
> [app.vita-fx.org]  "node": "4.7.2",
> [app.vita-fx.org]  "openssl": "1.0.2j",
> [app.vita-fx.org]  "uv": "1.9.1",
> [app.vita-fx.org]  "v8": "4.5.103.43",
> [app.vita-fx.org]  "zlib": "1.2.8"
> [app.vita-fx.org]}
> [app.vita-fx.org]npm WARN meteor-dev-bundle@0.0.0 No description
> [app.vita-fx.org]npm WARN meteor-dev-bundle@0.0.0 No repository field.
> [app.vita-fx.org]npm WARN meteor-dev-bundle@0.0.0 No license field.
> [app.vita-fx.org]=> Starting meteor app on port:80
> [app.vita-fx.org]Kadira: Successfully connected


Could you send your log, to compare, i believe it's a node version problem, beacause my app was create on 0.10.44 and meteor 1.2.-

**Comment by wolganens** [comment]
I run meteor npm install --save prerender-node (a package I use), deploy without ssl configuration then I could open the app. After that I deploy again with the ssl config and now its all working again..

**Comment by shadowcodex** [comment]
This can be closed as his issue was resolved.
