### ISSUE TITLE
Isn't there a better method to check if the deployment went well? Other than deployCheckWaitTime

### ISSUE THREAD

**Issue by timbrandin** [zodern/meteor-up#500]
It just feels so odd setting a timeout, instead of having the deploy tool keep track of errors or if it is live already... there must be a better way! meteor deploy doesn't have this right?

**Comment by shadowcodex** [comment]
You can always look at your logs using `mup logs`. You can also be SSH'd into your box and look if docker has started, investigate logs on each docker instance. 

There are a ton ways to check if deployment went well, the key is to figure out what is the `best` way to check. Currently it's setup to be simple and not super complex checking that ***works***.

**Comment by zodern** [comment]
> if it is live already...

Within 15 - 25 seconds of the app container starting, I think it checks if the app is live every second until `deployCheckWaitTime` runs out. I need to verify that.

> instead of having the deploy tool keep track of errors 

To do that it could check if the container has restarted 2 or more times and rollback immediately instead of waiting the full time.

> meteor deploy doesn't have this right?

As far as I know, galaxy doesn't. If the app fails to start, it will display a 503 error to anyone who visits the app until a fixed version is deployed.

**Comment by timbrandin** [comment]
I love this:
> Check if the container has restarted 2 or more times and rollback immediately instead of waiting the full time.

Also I think the logs are replaced by the rolled back container if it rolls back, so is there a way to get the full logs if that happens?

**Comment by shadowcodex** [comment]
We could write it out to an archived log file before forcing the rollback.

**Comment by zodern** [comment]
Most of the problems with the `deployCheckWaitTime` were from it having to include the time to install the app's npm dependencies. Starting in mup 1.3, with certain docker images, the app's npm dependencies are installed during `Prepare Bundle` before the app is installed.

> Check if the container has restarted 2 or more times and rollback immediately instead of waiting the full time.

The deploy validator checks if the app is running every second. In mup 1.4, if the container is restarting during at least 10 checks, the app is roll backed immediately.
