### ISSUE TITLE
Debug Output for App Bundling

### ISSUE THREAD

**Issue by shadowcodex** [zodern/meteor-up#502]
Is it possible to add more verbose output based on what is happening in the bundling process? This is currently a spot where I have no idea what is happening during a deploy process. The blinking cursor is a stress creator for me haha.

**Comment by zodern** [comment]
We could add a `--verbose` flag. The spawn process for the meteor build would have to have it's stdio set to 'inherit', and set the `METEOR_HEADLESS` env variable.

I also would like the `--verbose` flag to show the output from scripts run on the server in real time.
