### ISSUE TITLE
Add support for Passenger

### ISSUE THREAD

**Issue by yanickrochon** [zodern/meteor-up#503]
While looking for a cluster solution, I came across [Phusion Passenger Library](https://www.phusionpassenger.com/library/) and thought it would be awesome if mup could support it.

**Comment by Cu4rach4** [comment]
Why you want this?, if you want to uss this, maybe you need to deploy meteor app with direct docker + nginx + passenger.

**Comment by shadowcodex** [comment]
I think passenger is out of scope for meteor up atm.
