### ISSUE TITLE
Services down when not visited (or droplet overloaded)?

### ISSUE THREAD

**Issue by juliancwirko** [zodern/meteor-up#508]
Hi, I have a strange issue. My services when not visited are down. When I enter them I need to refresh couple of times to get them working. This is the same server (Ubuntu 14.04.4 x64) on which I have other Meteor apps deployed with old Mupx tool and they seems to work well. Could it be something with Mup or is this a standard behavior when the DO droplet is overloaded?

**Comment by shadowcodex** [comment]
Before you enter them, could you check `docker ps` and see if all the docker containers are running correctly?
Possibly dump out your `docker <container-name> logs` here for us to look at?

**Comment by juliancwirko** [comment]
Could it be related to :
```
Fix nginx-proxy not starting on server restart
```
From version 1.2.3 changelog? 
Because maybe this is the case here.

**Comment by zodern** [comment]
Run `docker ps` on the server and see if any of the containers have restarted.

**Comment by juliancwirko** [comment]
Ok, it looks like two of them which runs on `abernix/meteord:base` (deployed with this mup) restarted (5h ago) and others which run on `meteorhacks/meteord:base` are fine and not restarting for months.

**Comment by juliancwirko** [comment]
Also, there isn't anything special under `docker logs --since 10h <container-name>` just npm logs because I've deployed the site in the meantime. But it could be wrong command, I am not very experienced docker user ;) `docker <container-name> logs` doesn't work for me :/
