### ISSUE TITLE
deploy error digitalocean

### ISSUE THREAD

**Issue by maryito** [zodern/meteor-up#509]
I try to deploy to the server but when it is Checking the Deployment: FALLED shows me that

` ERR! There is likely additional logging output above.
	
	npm ERR! Please include the following file with any support request:
	npm ERR!     /bundle/bundle/programs/server/npm-debug.log
	
	> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
	> node npm-rebuild.js
	
	
	> bcrypt@1.0.2 install /bundle/bundle/programs/server/npm/node_modules/bcrypt
	> node-pre-gyp install --fallback-to-build
	
	node-pre-gyp ERR! Tried to download: https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz 
	node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.7.2 (node-v46 ABI) (falling back to source compile with node-gyp) 
	make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
	  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
	  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
	  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
	 
	=> Redeploying previous version of the app
`

**Comment by JohnAllen** [comment]
Are you sure `bcrypt` is installed properly locally before deploying?  Does your app run correctly locally?  Maybe try `meteor npm install --save bcrypt` if you haven't already?

**Comment by btbjosh** [comment]
I get this problem on my deploys too. Although I can deploy on a 1gb droplet instance just fine. Has anyone successfully gotten this to deploy to DO on a 512 instance?

**Comment by JohnAllen** [comment]
Seems like it should although I guess you couldn't have tons of users
depending on the number of subscriptions you'll have.

**Comment by btbjosh** [comment]
Yeah, I'm only trying to do it (on a 512) for an internally used app for our small company. Up until I upgraded to meteor 1.4.x it has worked just fine (thought that was with mupx and without all the es6 stuff)

**Comment by zodern** [comment]
In the log posted by @maryito it didn't have enough time to finish building bcrypt. Try adding another 60 seconds to the `deployCheckWaitTime`

**Comment by btbjosh** [comment]
I had it set to 120 at one point, which did not help. I think it actually gets done with the `bcrypt` stuff because it goes well past this line:
  ` make: Leaving directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'`

Then I get: 

    x Verifying Deployment: FAILED
	
	-----------------------------------STDERR-----------------------------------
	rver/npm/node_modules/qs
	request@2.79.0 /bundle/bundle/programs/server/npm/node_modules/request
	stringstream@0.0.5 /bundle/bundle/programs/server/npm/node_modules/stringstream
	tough-cookie@2.3.2 /bundle/bundle/programs/server/npm/node_modules/tough-cookie
	tunnel-agent@0.4.3 /bundle/bundle/programs/server/npm/node_modules/tunnel-agent
	uuid@3.0.1 /bundle/bundle/programs/server/npm/node_modules/uuid
	ssl-root-cas@1.2.3 /bundle/bundle/programs/server/npm/node_modules/ssl-root-cas
	{
	  "meteor-dev-bundle": "0.0.0",
	  "npm": "3.10.10",
	  "ares": "1.10.1-DEV",
	  "http_parser": "2.7.0",
	  "icu": "56.1",
	  "modules": "46",
	  "node": "4.7.2",
	  "openssl": "1.0.2j",
	  "uv": "1.9.1",
	  "v8": "4.5.103.43",
	  "zlib": "1.2.8"
	}
	npm WARN meteor-dev-bundle@0.0.0 No description
	npm WARN meteor-dev-bundle@0.0.0 No repository field.
	npm WARN meteor-dev-bundle@0.0.0 No license field.
	=> Starting meteor app on port:80
	 
	=> Redeploying previous version of the app

**Comment by btbjosh** [comment]
Ugh. I just resolved it... after googling this error: 

`mup UnhandledPromiseRejectionWarning: Unhandled promise rejection`

Turns out I had my ROOT_URL not set to `https` and just `http`.

**Comment by shadowcodex** [comment]
Glad to see you got it resolved

**Comment by maryito** [comment]
I solved it by removing the package
