### ISSUE TITLE
Can't deploy

### ISSUE THREAD

**Issue by erperejildo** [zodern/meteor-up#511]
After run mup deploy I get this (it takes a while):
```
Started TaskList: Pushing Meteor
[178.62.79.50] - Pushing Meteor App Bundle to The Server
Error read ECONNRESET
```

**Comment by zodern** [comment]
Are you able to ssh into the server?
How many times did you try to deploy and got that error?
Do you have the progress bar enabled in your config?

**Comment by erperejildo** [comment]
I'm able to login with my ssh key, but I'm trying the easier way right now to check the setup was ok.
I tried this just once.

Shall I change to ssh?

**Comment by JohnAllen** [comment]
I've gotten that with a slow or intermittent upload speeds.  Move closer to your router or otherwise improve your signal if you can.

**Comment by erperejildo** [comment]
My broadband connection is too bad. Could I do same deploy with gitlab-ci on pipelines?

**Comment by zodern** [comment]
That should work. Remember to have it install meteor first.

**Comment by erperejildo** [comment]
Where do I need to install Meteor? mup.js, .gitlab-ci.yml, server...

Sorry but still struggling with Meteor deployment after many days and every step sounds totally different to previous one.
What I'd like is push my commits to master and from this update my code and restart the app on my server (DigitalOcean). This server has everything configured (or that's what I thought because only can see Nginx now: http://178.62.79.50/).

I wouldn't like to deploy from my terminal but as you said from Gitlab would be possible. Do you know maybe a tutorial about this?

Thank you so much!

**Comment by shadowcodex** [comment]
I don't know of any tutorial, but using gitlab CI you would need to do the following.

**Assuming your project is pushed to the CI, and you have already done `mup setup` on the server**

1. Install Meteor
2. Install Mup
3. Run `mup deploy` command

**Comment by erperejildo** [comment]
Thanks for your answer @shadowcodex.
So running `mup deploy` I'll push my code to Gitlab? I thought it was pushed to my server.

What I don't understand then is why we need a `yml` file on Gitlab to configure our server settings.

Also if I need to push my code to develop and just deploy when I push to master I should do git `push origin develop` and `mup deploy` which sounds confusing or not easy to understand at least.

Right now when I push to master I've got some runners doing this.

Also I can avoid some compilations/deploys when I push to Gitlab adding some parameters on commits. Could I do the same with `mup` if I want to push to master?
