### ISSUE TITLE
Verifying Deployment goes forever after updating mup

### ISSUE THREAD

**Issue by qrobin** [zodern/meteor-up#512]
For some reason `Verifying Deployment` goes forever after updating mup. Can it be caused by last update or it's likely my app issue?

**Comment by shadowcodex** [comment]
How long do you have the timeout set to?

**Comment by qrobin** [comment]
`deployCheckWaitTime: 60`, but it just goes forever, not 60s

**Comment by qrobin** [comment]
Sorry, it was my app issue. I tried to add CORS header 

```
WebApp.rawConnectHandlers.use('/', function(req, res, next) {
   res.setHeader("Access-Control-Allow-Origin", "*");
   return next();
});
```
Seems it doesn't work this way. Thanks for fast response, @shadowcodex
