### ISSUE TITLE
Add support for ZSH

### ISSUE THREAD

**Issue by thsowers** [zodern/meteor-up#515]
As mentioned in #448, changing the default shell from bash to zsh causes an error similar to 

```
curl: (52) Empty reply from server
        zsh:31: = not found
        -----------------------------------STDOUT-----------------------------------
        ----------------------------------------------------------------------------
(node:31193) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zodern** [comment]
The problem is that whenever [list.executeScript is used](https://github.com/zodern/meteor-up/blob/master/src/modules/meteor/index.js#L199) it runs the script in the default shell instead of bash.

**Comment by shadowcodex** [comment]
And that is part of a package we depend on and don't have control over, right? NodeMiral if I remember correctly.

**Comment by zodern** [comment]
It is possible to register new commands with nodemiral. We could need to create a new command that forces the script to be run in bash.

**Comment by shadowcodex** [comment]
@thsowers would you like to do a PR for this new command?
