### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by shadowcodex** [zodern/meteor-up#518]
Currently I don't see a license defined for the repo. Should we add a license, and which one do we want to add if we do?

I prefer the MIT license, but that's just my personal preference.

**Comment by zodern** [comment]
In the package.json, it says the license is MIT. I would like to add a license file to make that more obvious. I probably need to ask @arunoda who the copyright holder is. On arunoda/meteor-up, it is MeteorHacks, but for most of the kadirahq projects it was kadirahq.

**Comment by shadowcodex** [comment]
sounds good
