### ISSUE TITLE
Set up SSL, but allow HTTP traffic as well

### ISSUE THREAD

**Issue by yogiben** [zodern/meteor-up#520]
I want to set up a server which has both https and http.

This is for connecting to it via DPP.

How to configure a cert, but also allow traffic for HTTP?

**Comment by zodern** [comment]
If you use custom certificates instead of let's encrypt, it will work.

**Comment by yogiben** [comment]
Thanks.

I know this might be asking a lot, but is it possible to use the let's encrypt functionality AND solve this problem?

If you point me to the part of the code that sets up the HTTP -> HTTPS redirect, I could probably do a PR with a `forceSSL` option.

**Comment by zodern** [comment]
I just found that it doesn't force ssl when using let's encrypt: https://github.com/zodern/meteor-up/blob/master/src/modules/meteor/assets/templates/start.sh#L90.
