### ISSUE TITLE
Redirect http to https or turn on nginx

### ISSUE THREAD

**Issue by danielbressan** [zodern/meteor-up#521]
This is probably me missing something, so hopefully a quick answer will do; I just couldn't find the answer searching around setup/issues. 

My app isn't correctly redirecting 80 traffic to 443. My ssl is working if you specifically go to https:// but somewhere I must have deleted a line in mup.js or something. 

1) What goes in mup.js to force this redirect?
2) OR how can I turn off the built in frontend, and I can setup my own nginx? (i.e. right now when I try and turn on nginx I get):
```
2017/03/08 21:53:44 [emerg] 23934#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2017/03/08 21:53:44 [emerg] 23934#0: bind() to 0.0.0.0:443 failed (98: Address already in use)
```

**Comment by zodern** [comment]
Are you using custom certificates or let's encrypt? I think the nginx container used for let's encrypt does this by default.

You can add the [force-ssl](https://atmospherejs.com/meteor/force-ssl) package.

**Comment by danielbressan** [comment]
Yeah I have in my mup:
```
 ssl: {
            crt: "/etc/nginx/certs/chained.pem", 
            key: "/etc/nginx/certs/key.pem", 
            port: 443 
        }
```

So is that what's creating the nginx container?

**Comment by zodern** [comment]
Yes

**Comment by shadowcodex** [comment]
I recommend the force-ssl package as well. https://atmospherejs.com/meteor/force-ssl

**Comment by danielbressan** [comment]
Awesome! For now, I just removed the 'ssl:' tags from mup.js and it allowed my to run my own nginx. I'll look into force-ssl though. Does it just 'do it for you' or what's it's benefit from using my own nginx frontend?

**Comment by shadowcodex** [comment]
It just does it for you, I believe. Simple, easy, clean setup.

Force SSL would be something in the future that could be passed in with an Nginx config file. Which we are working on getting setup in https://github.com/zodern/meteor-up/pull/496.

**Comment by btbjosh** [comment]
@shadowcodex Any eta on how far out we are on #496 ? Thanks for the hard work!

**Comment by avishaan** [comment]
I'm having this issue as well, perhaps an option that is `redirect-ssl: true` in the meantime I'll give force-ssl a shot

**Comment by avishaan** [comment]
force-ssl package didn't work for me, is it possible because I'm running on port 8443 instead of 443 (although I don't believe that should really matter) I have two meteor apps running on the same instance sharing a database, one that runs on 443 and one that runs on 8443 (portal).

**Comment by zodern** [comment]
Mup 1.3 will be able to redirect `http` to `https`.
