### ISSUE TITLE
Build Error: --server-only: option unknown

### ISSUE THREAD

**Issue by muninn9** [zodern/meteor-up#523]
I'm tried deploying for the first time with "mup deploy" and this is what it gave me in the output: 

```
Building App Bundle Locally
--server-only: unknown option.
Usage: meteor build <output path> [--debug] [--directory]
          [--mobile-settings settings.json] [--server http://example.com:3000]

...

=> Build Error. Check the logs printed above.
```

And here's what I had for `buildOptions` in `mup.js`:

```
buildOptions: {
    serverOnly: true
}
```

Then, after trying to deploy again it silently fails, immediately, with no error message. Any suggestions?

**Comment by muninn9** [comment]
Here's what I figured out in case anyone else has this problem:

I simply removed the `buildOptions` property which took care of the error message. It was silently failing because I left out `servers: { one: {} }` under the `mongo` property (see below).

```
mongo: {
    oplog: true,
    port: 27017,
    version: '3.4.1',
    servers: {
        one: {}
    }
}
```

After I did this it successfully pushed the app bundle to the server.

**Comment by xinlovedong** [comment]
hi~  I hava the same problem with you.Have  you solved?

**Comment by vurumadla** [comment]
I20171005-07:19:15.685(0)?
W20171005-07:19:15.688(0)? (STDERR) The regenerator/runtime module is deprecated; please import regenerator-runtime/runtime instead.
W20171005-07:19:15.689(0)? (STDERR) /home/centos/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171005-07:19:15.689(0)? (STDERR)                                             throw(ex);
W20171005-07:19:15.690(0)? (STDERR)                                             ^
W20171005-07:19:15.690(0)? (STDERR)
W20171005-07:19:15.691(0)? (STDERR) TypeError: Cannot read property 'deny' of undefined
W20171005-07:19:15.691(0)? (STDERR)     at exports.default (/home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:91154:18)
W20171005-07:19:15.692(0)? (STDERR)     at Object.<anonymous> (/home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:71141:22)
W20171005-07:19:15.692(0)? (STDERR)     at __webpack_require__ (/home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:62689:30)
W20171005-07:19:15.693(0)? (STDERR)     at Object.installedModules (/home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:62721:19)
W20171005-07:19:15.693(0)? (STDERR)     at __webpack_require__ (/home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:62689:30)
W20171005-07:19:15.694(0)? (STDERR)     at /home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:62709:18
W20171005-07:19:15.695(0)? (STDERR)     at meteorInstall.meteor_core.server.server.bundle.min.js (/home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:62712:10)
W20171005-07:19:15.696(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171005-07:19:15.697(0)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171005-07:19:15.698(0)? (STDERR)     at /home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:93000:1
=> Exited with code: 1

**Comment by vurumadla** [comment]
can anyone give solution to the error

**Comment by chrisbutler** [comment]
not sure why this is closed... this seems to be a real issue

```mup deploy --verbose
Building App Bundle Locally
--server-only: unknown option.
Usage: meteor build <output path> [--debug] [--directory]
          [--mobile-settings settings.json] [--server http://example.com:3000]```

**Comment by ziedmahdi** [comment]
@chrisbutler what is the meteor version?
You can omit the buildOptions in the mup.js file.

**Comment by chrisbutler** [comment]
yes, i no longer get the error if i don't include that option. but it's specified as required in the minimal config. 
i was on `1.2`  but i'm trying with `1.5` now
