### ISSUE TITLE
MONGO_URL arrival

### ISSUE THREAD

**Issue by trsh** [zodern/meteor-up#525]
So my apps don't use DB at all, but I must set this option. To what? Previous MUP releases didn't require such option. How to migrate now?

**Comment by zodern** [comment]
Meteor requires a MongoDB to work. Mupx would set `MONGO_URL` for you.

Add the `mongo` config to your `mup.js`:
```
{
...
mongo: { // (optional)
    port: 27017,
    version: '3.4.1' // (optional), default is 3.4.1
    servers: {
      one: {},
    },
  }
}
```

And set `MONGO_URL` to 'mongodb://localhost/meteor'

And then run `mup setup` and `mup deploy`

**Comment by trsh** [comment]
MONGO_URL=mongodb://localhost/meteor stopped working form me, when I introduced accounts-base meteor package. It requires DB. So I need to setup one now manually? I tough meteor does it for you.

**Comment by zodern** [comment]
> MONGO_URL=mongodb://localhost/meteor stopped working form me

What do you mean by it stopped working? Is mongodb running on the server? You can find out by running `docker ps` on the server and checking for a container named `mongo`.

> So I need to setup one now manually? I tough meteor does it for you.

If you add `mongo` to your config and run `mup setup`, meteor up will setup MongoDB for you. Meteor only does it during development.

**Comment by trsh** [comment]
OK. I'll try and report back.

**Comment by trsh** [comment]
No mango settings are required in latest release
