### ISSUE TITLE
How to access nginx logs

### ISSUE THREAD

**Issue by yogiben** [zodern/meteor-up#526]
I've been getting `500 Internal Server Error`

Nothing shows up in the `mup logs`. How do I access the nginx logs?

**Comment by zodern** [comment]
nginx container for let's encrypt:
`docker logs <appname>-nginx-proxy`

nginx container for custom ssl certificates:
`docker logs <appname>-frontend`

Run the command on the server.

**Comment by zodern** [comment]
With the new reverse proxy, it is `mup proxy logs`, and you no longer need to ssh into the server.

**Comment by cpury** [comment]
I'm also getting 500s from nginx, but `mup proxy logs` doesn't help me much:

```
GET / HTTP/1.1" 500 595 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
```

I checked the generated nginx config and it seems to be hard-wired to return 500s?

```
server {
	server_name server.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	include /etc/nginx/vhost.d/server.com;
	location / {
		proxy_pass http://server.com;
	}
}
server {
	server_name server.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	return 500;
	ssl_certificate /etc/nginx/certs/default.crt;
	ssl_certificate_key /etc/nginx/certs/default.key;
}
```

Any ideas?

**Comment by cpury** [comment]
Note: This only happens when I add multiple domains to `proxy.domains`, e.g. `'server1.com,server2.com'`. It works fine with just a single one, e.g. `server.com`

**Comment by cpury** [comment]
It now also happens with only a single URL :(

**Comment by cpury** [comment]
For anyone trying this: I created a new `.deploy` directory and a new instance with exactly the same config. Now it works, and the nginx-config doesn't have those weird `return 500;` entries... Seems like a bug in MUP to me.

**Comment by JonathanLehner** [comment]
strange...
