### ISSUE TITLE
Verifying Deployment Fails Again !!!

### ISSUE THREAD

**Issue by mokaid** [zodern/meteor-up#531]
Hello , 
I've struggling for more than 7 days , Meteor forums members are not supportive at all .. hope I can find a solution here . After the last the update with meteor 1.4.3.1 and mup 1.2.3
Everything locally is working perfectly , when it comes to deployment , I am facing a problem at the verifying stage , 
Server Settings  : 512 MB Memory / 20 GB Disk / LON1 - Ubuntu 16.04.2 x64 - Digital Ocean 

Browser  : 502 Bad Gateway - nginx/1.8.0
mup logs --tail=50 : 

[xxx.xxx.xxx.xxx]npm ERR! Please include the following file with any support request:
[xxx.xxx.xxx.xxx]npm ERR!     /bundle/bundle/programs/server/npm-debug.log
[xxx.xxx.xxx.xxx]> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
[xxx.xxx.xxx.xxx]> node npm-rebuild.js
[xxx.xxx.xxx.xxx]npm ERR! Linux 4.4.0-64-generic
[xxx.xxx.xxx.xxx]npm ERR! argv "/opt/nodejs/bin/node" "/opt/nodejs/bin/npm" "rebuild" "--update-binary"
[xxx.xxx.xxx.xxx]npm ERR! node v4.8.0
[xxx.xxx.xxx.xxx]npm ERR! npm  v3.10.10
[xxx.xxx.xxx.xxx]npm ERR! path /bundle/bundle/programs/server/npm/node_modules/meteor/npm-container/node_modules/sshpk/bin\sshpk-conv
[xxx.xxx.xxx.xxx]npm ERR! code ENOENT
[xxx.xxx.xxx.xxx]npm ERR! errno -2
[xxx.xxx.xxx.xxx]npm ERR! syscall chmod
[xxx.xxx.xxx.xxx]npm ERR! enoent ENOENT: no such file or directory, chmod '/bundle/bundle/programs/server/npm/node_modules/meteor/npm-container/node_modules/sshpk/bin\sshpk-conv'
[xxx.xxx.xxx.xxx]npm ERR! enoent ENOENT: no such file or directory, chmod '/bundle/bundle/programs/server/npm/node_modules/meteor/npm-container/node_modules/sshpk/bin\sshpk-conv'
[xxx.xxx.xxx.xxx]npm ERR! enoent This is most likely not a problem with npm itself
[xxx.xxx.xxx.xxx]npm ERR! enoent and is related to npm not being able to find a file.
[xxx.xxx.xxx.xxx]npm ERR! enoent
[xxx.xxx.xxx.xxx]npm ERR! Please include the following file with any support request:
[xxx.xxx.xxx.xxx]npm ERR!     /bundle/bundle/programs/server/npm/node_modules/meteor/npm-container/npm-debug.log
[xxx.xxx.xxx.xxx]npm WARN meteor-dev-bundle@0.0.0 No description
[xxx.xxx.xxx.xxx]npm WARN meteor-dev-bundle@0.0.0 No repository field.
[xxx.xxx.xxx.xxx]npm WARN meteor-dev-bundle@0.0.0 No license field.
[xxx.xxx.xxx.xxx]npm ERR! Linux 4.4.0-64-generic
[xxx.xxx.xxx.xxx]npm ERR! argv "/opt/nodejs/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
[xxx.xxx.xxx.xxx]npm ERR! node v4.8.0
[xxx.xxx.xxx.xxx]npm ERR! npm  v3.10.10
[xxx.xxx.xxx.xxx]npm ERR! code ELIFECYCLE
[xxx.xxx.xxx.xxx]npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
[xxx.xxx.xxx.xxx]npm ERR! Exit status 254
[xxx.xxx.xxx.xxx]npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
[xxx.xxx.xxx.xxx]npm ERR! Make sure you have the latest version of node.js and npm installed.
[xxx.xxx.xxx.xxx]npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
[xxx.xxx.xxx.xxx]npm ERR! not with npm itself.
[xxx.xxx.xxx.xxx]npm ERR! Tell the author that this fails on your system:
[xxx.xxx.xxx.xxx]npm ERR!     node npm-rebuild.js
[xxx.xxx.xxx.xxx]npm ERR! You can get information on how to open an issue for this project with:
[xxx.xxx.xxx.xxx]npm ERR!     npm bugs meteor-dev-bundle
[xxx.xxx.xxx.xxx]npm ERR! Or if that isn't available, you can get their info via:
[xxx.xxx.xxx.xxx]npm ERR!     npm owner ls meteor-dev-bundle
[xxx.xxx.xxx.xxx]npm ERR! There is likely additional logging output above.
[xxx.xxx.xxx.xxx]npm ERR! Please include the following file with any support request:
[xxx.xxx.xxx.xxx]npm ERR!     /bundle/bundle/programs/server/npm-debug.log

I did notice an error about the exit status 254 !!
Please tell me what is this all about ?

**Comment by zodern** [comment]
A similar error was reported in https://github.com/meteor/meteor/issues/7401 when using the same package. You could try manually fixing the bin path as mentioned in https://github.com/meteor/meteor/issues/7401#issuecomment-232421798. 
Another option might be to change the docker image to `abernix/meteord:binbuild`

**Comment by mokaid** [comment]
Hello 
@zodern 
Under the path  : 

current/bundle/programs/server/npm/node_modules/sshpk

 I did try the image you suggested and checked the packages.json file of sshpk and by default it looks like that :
  "bin": {
    "sshpk-conv": "bin/sshpk-conv",
    "sshpk-sign": "bin/sshpk-sign",
    "sshpk-verify": "bin/sshpk-verify"
  },

but still i am facing the same problem 

I found the same package under the following path 
current/bundle/programs/server/npm/node_modules/meteor/npm-container/node_modules/sshpk
 I tried to make the slashes issue , but the weird thing is that , after i update the package.json file . it returns back to the double back slashes by itself !!!

**Comment by emik** [comment]
Am also getting this error when verifying deployment from Windows to an Ubuntu 16.04 server. Tried abernix/meteord:binbuild and no difference.

**Comment by romiohasan** [comment]
Also having this same issue - Verifying Deployment Failed.
Tried abernix/meteord:binbuild but no difference.
Using MUP from win10 and deploying to Ubuntu 16.04 and METEOR@1.5

 `npm ERR! enoent ENOENT: no such file or directory, chmod '/bundle/bundle/programs/server/npm/node_modules/sshpk/bin\sshpk-conv'`

**Comment by romiohasan** [comment]
I really hope someone gives a fix soon for windows.
(as a temporary solution, I just deployed from my Ubuntu local VM running on windows)

**Comment by mklueh** [comment]
I have the same issue, but while using meteor-launchpad. It came out of the sudden and only occurs in a test project I´ve created to figure everything out. Any news about that?

Edit: I could solve it by removing the "mobile-experience" package

**Comment by ilan-schemoul** [comment]
I'm trying @Mklueh's solutions whatever the result is it's a pity that this haven't been fixed yet.

**Comment by zodern** [comment]
It's fixed in npm 5.4.0, which Meteor 1.6 might use.

**Comment by ilan-schemoul** [comment]
Alright

**Comment by ilan-schemoul** [comment]
How do I do right now ?

**Comment by zodern** [comment]
I created a mup plugin that fixes the bin paths: https://www.npmjs.com/package/mup-fix-bin-paths.

**Comment by stephen-mi11er** [comment]
I am also having the same issue when I deploy Meteor 1.5.2 from a Windows 10 machine to Galaxy.  I even updated to Meteor beta 1.6.27 to check if they implemented a bug fix for this but I get the same issue.

I get the following error: 

```
bcrypt@1.0.3 install /app/bundle/programs/server/npm/node_modules/bcrypt
node-pre-gyp install --fallback-to-build
[bcrypt] Success: "/app/bundle/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
npm ERR! path /app/bundle/programs/server/npm/node_modules/sshpk/bin\sshpk-conv
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/app/bundle/programs/server/npm/node_modules/sshpk/bin\sshpk-conv'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
ERR! enoent
```

The only way I can resolve this annoying error is to remove the bcrypt reference from my project. 

@zodern the mup plugin unfortunately didn't work for me

**Comment by zodern** [comment]
@stephen-mi11er did it show `Fixing bin paths for sshpk`?

**Comment by stephen-mi11er** [comment]
@zodern this is the only log that I seen in the build:

`mup-fix-bin-paths@0.1.0 /app/bundle/programs/server/npm/node_modules/mup-fix-bin-paths`

Maybe I didn't implement correctly?

**Comment by zodern** [comment]
When running `mup deploy`, it should show `Fixing npm dependencies bin paths` and list any npm packages that it fixed before it shows `Building App Bundle Locally`.

**Comment by stephen-mi11er** [comment]
I'll try again and get back to you.

**Comment by stephen-mi11er** [comment]
@zodern I can confirm that I was using mup incorrectly after re-reading the documentation. I'll get back to you in a couple days since my side project has to compete with my day job.

**Comment by stephen-mi11er** [comment]
@zodern after reading more of the documentation from meteor and mup I've determined that there isn't a need to use mup since I am deploying to Meteor Galaxy.  From my understanding mup is better utilized for hosts where Meteor isn't directly supported. Unless I read otherwise I won't be using mup to deploy to Galaxy. At this point I'm just gonna have to wait until Meteor Galaxy fixes the bug in their deployment code or switch to another service and use mup.

**Comment by kishorvaghani** [comment]
@zodern : mup was not working with 1 GB ram of EC2 ubuntu instance, i was able to test https when i used new EC2 instance with 2 GB RAM . it requires minimum of 2 GB RAM.
