### ISSUE TITLE
Having issues Deploying project

### ISSUE THREAD

**Issue by dannyd43** [zodern/meteor-up#532]
The mup setup finishes successfully although i am not able to deploy the project.
any help would be wonderful!

ubuntu@ip:~/myTrends/deployment$ mup setup

Started TaskList: Setup Docker
[ec2-52-60-49-232.ca-central-1.compute.amazonaws.com] - setup docker
[ec2-52-60-49-232.ca-central-1.compute.amazonaws.com] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[ec2-52-60-49-232.ca-central-1.compute.amazonaws.com] - Setup Environment

Started TaskList: Setup Mongo
[ec2-52-60-49-232.ca-central-1.compute.amazonaws.com] - setup environment
[ec2-52-60-49-232.ca-central-1.compute.amazonaws.com] - Setup Environment: SUCCESS
[ec2-52-60-49-232.ca-central-1.compute.amazonaws.com] - setup environment: SUCCESS
[ec2-52-60-49-232.ca-central-1.compute.amazonaws.com] - copying mongodb.conf
[ec2-52-60-49-232.ca-central-1.compute.amazonaws.com] - copying mongodb.conf: SUCCESS

Started TaskList: Start Mongo
[ec2-52-60-49-232.ca-central-1.compute.amazonaws.com] - start mongo
[ec2-52-60-49-232.ca-central-1.compute.amazonaws.com] - start mongo: SUCCESS

Next, you should run:
    mup deploy

ubuntu@ip:~/myTrends/deployment$ mup deploy
Building App Bundle Locally
{ cwd: '/home/ubuntu/myTrends',
  env: 
   { XDG_SESSION_ID: '1',
     TERM: 'xterm-256color',
     SHELL: '/bin/bash',
     SSH_CLIENT: '24.150.176.182 61111 22',
     OLDPWD: '/home/ubuntu/myTrends',
     SSH_TTY: '/dev/pts/0',
     USER: 'ubuntu',
     LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:',
     MAIL: '/var/mail/ubuntu',
     PATH: '/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin',
     PWD: '/home/ubuntu/myTrends/deployment',
     LANG: 'en_US.UTF-8',
     SHLVL: '1',
     HOME: '/home/ubuntu',
     LOGNAME: 'ubuntu',
     SSH_CONNECTION: '24.150.176.182 61111 172.31.27.154 22',
     LESSOPEN: '| /usr/bin/lesspipe %s',
     XDG_RUNTIME_DIR: '/run/user/1000',
     LESSCLOSE: '/usr/bin/lesspipe %s %s',
     _: '/usr/local/bin/mup',
     METEOR_HEADLESS: 1 },
  stdio: 'pipe' }
{ Error: spawn meteor ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn meteor',
  path: 'meteor',
  spawnargs: 
   [ 'build',
     '--directory',
     '/tmp/mup-meteor-bed33625-b22a-49c2-91fe-44f2cea65026',
     '--architecture',
     'os.linux.x86_64',
     '--server-only' ] }

=> Build Error. Check the logs printed above.
Error: build-error
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/mup/lib/modules/meteor/build.js:46:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
ubuntu@ip:~/myTrends/deployment$

**Comment by emjimadhu** [comment]
@dannyd43 Have you fixed this issue? I am having the same problem.
