### ISSUE TITLE
MongoDB data not accessible when used mup deploy

### ISSUE THREAD

**Issue by iAssureIT** [zodern/meteor-up#534]
I tried deploying my meteor app using 2 methods
1.  By simply typing  **meteor**  command. It builds and runs in the same way as it does on development machine. 
2. By using **mup setup** and **mup deploy**. 

**In method#1**, I could see all the data in the database. It was the data that we added on local machine. We could see that on server as it is. 

**In method#2**, we see the whole data has gone... No data available in app. 

What was difference in both above things?
How can I transfer the data from our development environment to production?

**Comment by JohnAllen** [comment]
Your `mongo` is run in a separate docker container.  See the README about accessing the mongo instance.

**Comment by tanutapi** [comment]
You need to dump out your database from local development and restore it into your production server.
