### ISSUE TITLE
file size

### ISSUE THREAD

**Issue by maxlibin** [zodern/meteor-up#537]
Why meteor production using so much disk space? anyway to clean up?

Usage of /:   39.3% of 19.55GB

**Comment by lc3t35** [comment]
@maxlibin could you be more precise ? why is this related to meteor-up ?

**Comment by JohnAllen** [comment]
Mongo uses quite a bit of disk space for each collection, at least it used to.  Are you sure this is a Meteor problem in the first place?

**Comment by zodern** [comment]
@maxlibin You can run these commands to see what is using the space:
```
df -h
du -h --max-depth=2 /opt
docker images
docker ps -s
```
