### ISSUE TITLE
mup logs -f doesn't print out all logs

### ISSUE THREAD

**Issue by WayneUong** [zodern/meteor-up#539]
It used to tail logs till the end, now there seems to be a limit on number of lines. And it also doesn't tail if the logs exceeds that limit.

**Comment by lc3t35** [comment]
@WayneUong can you please give an example of truncated log ? I didn't find any limitation in the mup logs command

**Comment by WayneUong** [comment]
I can't give anything right now, as we're deploying pretty often and the logs get cleared each time. But if it gets too long I have to use `--tail` to get to the latest logs. Also, running `docker logs` directly on the server shows more logs than `mup logs` (only when it gets too long).

**Comment by zodern** [comment]
@WayneUong The next time the logs gets too long, try running `DEBUG=* mup logs`. There will be a line starting with ` mup:utils getDockerLogs command:` that will contain the exact command it runs on the server to get the logs. Please try running the command and let me know if it shows the same logs as when running `mup logs`.
