### ISSUE TITLE
mup deploy fails silently after pushing the startup script

### ISSUE THREAD

**Issue by rohithb** [zodern/meteor-up#541]
I have been successfully using mup for deploying alpha versions of my meteor app.
But when I tried to deploy my latest version, mup exits after these messages

```
Started TaskList: Pushing Meteor
[x.x.x.x] - Pushing Meteor App Bundle to The Server
[x.x.x.x] - Pushing Meteor App Bundle to The Server: SUCCESS
[x.x.x.x] - Pushing the Startup Script
[x.x.x.x] - Pushing the Startup Script: SUCCESS

```
I tried updating mup,  I tried on a new EC2 instance also.  But no success. 
mup works fine with one of my other project.

` mup logs --tail=100`  gives an error `Error: No such container: `.

I was using the same `mup.js` ( which was working perfectly earlier).
In the meteor project I added  `percolate:synced-cron` from atmosphere and added `mongodb` from npm in this version.
I have a cron job which runs outside the meteor server process (using `percolate:synced-cron`). Which works perfectly on my local development server.

How this situation can be fixed?

This is the output of `DEBUG=* mup deploy`

```
update 1.0.3 => 1.2.4
  mup:module:default exec => mup deploy +0ms
  mup:module:meteor exec => mup meteor deploy +0ms
  mup:module:meteor exec => mup meteor push +2ms
Building App Bundle Locally

Started TaskList: Pushing Meteor
[35.154.203.169] - Pushing Meteor App Bundle to The Server
  nodemiral:sess:35.154.203.169 copy file - src: /tmp/0573b0d8-8486-435b-b123-cfbcf25ad25c/bundle.tar.gz, dest: /opt/ctmapp/tmp/bundle.tar.gz, vars: undefined +0ms
[35.154.203.169] - Pushing Meteor App Bundle to The Server: SUCCESS
[35.154.203.169] - Pushing the Startup Script
  nodemiral:sess:35.154.203.169 copy file - src: /usr/local/lib/node_modules/mup/lib/modules/meteor/assets/templates/start.sh, dest: /opt/ctmapp/config/start.sh, vars: {"appName":"ctmapp","useLocalMongo":1,"port":80,"logConfig":{"opts":{"max-size":"100m","max-file":10}},"docker":{"image":"abernix/meteord:base"}} +1.8m
[35.154.203.169] - Pushing the Startup Script: SUCCESS
  mup:module:meteor exec => mup meteor envconfig +4m
```

**Comment by lc3t35** [comment]
@rohithb can you please give a longer extract of mup logs so we can look what is surrounding the Error ? and your mup.js ?

**Comment by rohithb** [comment]
A trailing comma in `settings.json ` was the problem. 
I removed and reinstalled `mup 1.2.4`, its showed error in settings.json file.
