### ISSUE TITLE
"Building App Bundle Locally" takes 15-20min

### ISSUE THREAD

**Issue by nilsi** [zodern/meteor-up#542]
Deploying works perfectly but I just wonder if it is supposed to take this long? I think it got slower recently. My computer is a macbook pro mid 2010.

**Comment by zodern** [comment]
You can add the `--verbose` flag to see what `meteor build` is doing.

**Comment by themastersoda** [comment]
It takes the same amount of time for me. I believe that is related to the speed of your HDD as I have noticed that deploying from SSD drive is significantly faster.
