### ISSUE TITLE
mup log tail seems to be reversed (head and not tail)

### ISSUE THREAD

**Issue by sirpy** [zodern/meteor-up#543]
when i ran mup logs --tail=50 to see the last error it seems like it showed me the head of the logs and indeed doing mup log --tail=1000 finally showed the last error

**Comment by zodern** [comment]
If you run `docker logs <appname> --tail=50` on the server, does it do this too?

**Comment by sirpy** [comment]
non on the server it seems like it's doing indeed tail. the last line is always the same
