### ISSUE TITLE
Load balancing multiple instances

### ISSUE THREAD

**Issue by WayneUong** [zodern/meteor-up#548]
I can see that meteor-up supports deploying the same app to multiple servers or multiple instances per server. But how is it useful without a load balancer? Does meteor-up automatically setup an nginx balancer?

**Comment by zodern** [comment]
Currently it doesn't. Mup 1.3 will focus on improving deploying to multiple servers, and I'm hoping to add load balancing.

**Comment by WayneUong** [comment]
I managed to setup an AWS application load balancer. Is there a test to make sure that sticky sessions and websocket work? Thanks.

**Comment by bennygenel** [comment]
Hi @WayneUong;

I'm currently trying to setup a load balancer for my app. 

I tried to setup a basic Nginx load balancer but I couldn't figure out how o enable websocket myself too. I followed [this](http://nginx.org/en/docs/http/websocket.html) documentation but still its not working for me.
![scs](https://cloud.githubusercontent.com/assets/4287862/24262085/03787e3a-100a-11e7-86c6-7aaf94b7ab2a.jpg)

Does AWS load balancer work with only AWS products or can I use it with multiple VPS from other data centres?

You can check if websocket connection working or not by using Chrome Developer Tools. Network tab should show websocket connection.

I would really appreciate any suggestions 

Thanks

**Comment by WayneUong** [comment]
Hi @bennygenel 

websocket seems to work fine for us:
<img width="665" alt="screen shot 2017-03-23 at 1 45 16 pm" src="https://cloud.githubusercontent.com/assets/8436742/24269654/569b9d6c-0fcf-11e7-9424-9aac92e9a694.png">

I haven't figured out how to test sticky sessions though. Our app has been functioning normally so far. The only problem I'm dealing with is syncing cron jobs between instances.

AWS Application Load Balancer only works with EC2 instances. I don't think you can forward traffic to external servers. But deploying to EC2 is a breeze with mup. There's also the Classic Load Balancer. I haven't tried it yet but I heard that it's a pain to deal with if you need websocket + sticky sessions.

**Comment by hphirke** [comment]
@WayneUong 
Could you share what kind of Load balancing you have used?
Type and algorithm on balancer (Like round robin, etc)

**Comment by zodern** [comment]
This is working in the current 1.5 beta.
