### ISSUE TITLE
debug:false not working

### ISSUE THREAD

**Issue by Garbolino** [zodern/meteor-up#554]
When deploying my app debug:false is been omitted, I have also tried deleting debug parameter. Any idea?

Using mup v1.2.5, nodejs 4.7.0 (also tested with 4.8.1) npm v4.4.4.\

Thank you!

**Comment by JohnAllen** [comment]
What do you mean "`debug: false` is been omitted"?  That you didn't have that there and it's still not running production mode?  How do you know it's not running in production mode?

**Comment by Garbolino** [comment]
I mean, I have tried with debug:false and removing debug line in my mup.json file, both cases stilll not in production mode. I know it is not running in production mode because files are not compressed when rendering my app.
Thank you!

**Comment by Garbolino** [comment]
I have found the problem, sorry it was not related to mup. I do not know how but standard minifiers js package disappear from my package at the same time I upgraded mup...

Thank you anyway
