### ISSUE TITLE
Use multiple enviroments

### ISSUE THREAD

**Issue by malikperang** [zodern/meteor-up#566]
I would like to know if I can simply use multiple enviroment just like this?
```

env: {
      ROOT_URL: 'http://rooturl',
      MONGO_URL: 'mongodb://xxxxx@aws-us-east-xxxx30.dblayer.com:104xxx/mydb?ssl=true',
       MONGO_OPLOG_URL: 'mongodb://mongooplogURL'
    },

env: {
      ROOT_URL: 'http://rooturl',
      MONGO_URL: 'mongodb://xxxxx@aws-us-east-xxxx31.dblayer.com:103xxx/mydb?ssl=true',
        MONGO_OPLOG_URL: 'mongodb://mongooplogURL'
    },
```

The purpose is to use multiple node of mongodb.
Appreciate any advices.

**Comment by tomtom87** [comment]
@malikperang what is the purpose?

**Comment by IDCOLL** [comment]
@malikperang I am looking into using OPLOG TAILING and want to add the "Mongo_Oplog_Url" to my mup.json.

Do you know if this function actually works in MUP?

**Comment by zodern** [comment]
@malikperang Do you want a different `MONGO_URL` for each server?

@IDCOLL It does work if oplog is enabled for the database. The built-in Mongo does not support oplog.
