### ISSUE TITLE
node is down and deployment fails

### ISSUE THREAD

**Issue by WayneUong** [zodern/meteor-up#567]
```
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 522 response downloading https://nodejs.org/download/release/v4.8.0/node-v4.8.0-headers.tar.gz
```

Is there a way to specify a different node mirror link?

**Comment by isAlmogK** [comment]
I'm having the same issue

**Comment by isAlmogK** [comment]
This is the error that I'm getting 

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz

**Comment by tomtom87** [comment]
Got this issues also +1

**Comment by zodern** [comment]
Node should be back up now.

In the future, you can set the `NODEJS_ORG_MIRROR` env variable in your config.
