### ISSUE TITLE
Using autogenerated SSL

### ISSUE THREAD

**Issue by dominicarrojado** [zodern/meteor-up#568]
I'm getting error while putting the autogenerate SSL fields: **No responsve from the server**, But removing the SSL autogenerate field, the error won't show.

![image](https://cloud.githubusercontent.com/assets/6789191/24689795/a78a2d16-19fb-11e7-8ca1-679172fbdef9.png)

**Comment by zodern** [comment]
You are using an old mup version. Update using `npm i -g mup` and try again. Version 1.2.5 had some changes to try to fix this.

**Comment by dominicarrojado** [comment]
I updated already but somehow it's still using the old version. Whenever I execute an mup command got this at the start:

![image](https://cloud.githubusercontent.com/assets/6789191/24735157/175ddb84-1ab4-11e7-8be3-d718003d1b32.png)

How do I fix this?

**Comment by tomtom87** [comment]
@mroftalp can you try `npm uninstall mup` then install again with `npm i -g mup` and check version again

**Comment by dominicarrojado** [comment]
@tomtom87 after I `npm uninstall mup`, it's still installed

**Comment by zodern** [comment]
@mroftalp the command should be `npm uninstall -g mup`

**Comment by dominicarrojado** [comment]
@zodern This still appears
![image](https://cloud.githubusercontent.com/assets/6789191/25656387/5f0fe2ec-302b-11e7-8694-2233608ef306.png)

**Comment by dominicarrojado** [comment]
Nvm I figured out a way somehow @zodern
