### ISSUE TITLE
mup setup: UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by JohnAllen** [zodern/meteor-up#569]
Has anyone ever gotten this error when running `setup`?

**Comment by zodern** [comment]
Could you please share your config?

**Comment by JohnAllen** [comment]
Ok, not sure exactly where the problem was, but it was in my mup.js file.  If someone else runs into this, I suggest copying the default mup.js file and manually adding your params there one by one.

**Comment by zodern** [comment]
@JohnAllen do you know what it was in your config?

**Comment by JohnAllen** [comment]
Pretty sure I had `path: '../appFolder'` instead of `path: '../'`
