### ISSUE TITLE
How to install custom software in the docker image?

### ISSUE THREAD

**Issue by THPubs** [zodern/meteor-up#57]
I need to install custom software in the docker image. For example, for my app to run, I need `imagemagick` installed in the system. How can I do this?

**Comment by madushan1000** [comment]
You can build a docker image with all the stuff you want and push it to the docker registry (Use the base image `meteorhacks/meteord`). And then set `meteor.dockerImage` to your image id (ex: `meteor.dockerImage: 'meteorhacks/meteord'`). Take a look at the `mup.js` format in the readme. (BTW this feature needs testing, I'd appreciate if people can test this for me :) )

**Comment by THPubs** [comment]
@madushan1000 Great! I just created a custom docker image with imagemagick and deployed! So far so good.. everything's working fine :-) I will test it further and let you know if there's anything wrong!

**Comment by devdudeio** [comment]
can you explain how you have installed imagemagick with docker?

**Comment by madushan1000** [comment]
create a custom docker image with `meteorhacks/meteord` as the base + your libraries/software, push it to the dockerhub and set `meteor.dockerImage` to that.
