### ISSUE TITLE
Access to the meteor app only using mydomain.com:3000 address

### ISSUE THREAD

**Issue by birganovrus** [zodern/meteor-up#572]
Hi! Got this problem, here is my configs

**mup.json**
`

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://mydomain.com',
      MONGO_URL: 'mongodb://localhost/meteor',
      PORT: 3000

    },

    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/spaceglue:node-4-builddeps',
     imagePort: 3000

      
    },

    // This is the maximum time in seconds it will wait
    // for your app to start
    // Add 30 seconds if the server has 512mb of ram
    // And 30 more if you have binary npm dependencies.
    deployCheckWaitTime: 250,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true

`

**ningx conf**

`

server {
    listen 80;

    server_name mydomain.com www.mydomain.com;
    return 301 http://mydomain.com$request_uri;

}

server {
    listen 443;
    server_name mydomain.com;

    access_log /var/log/nginx/localhost.access_log;
    error_log /var/log/nginx/localhost.error_log;
	
    # Forward to meteor server                                                                                                                        
    location / {
         proxy_pass http://localhost:3000;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';
         proxy_set_header X-Forwarded-For $remote_addr;
    }
}
`

**Comment by zodern** [comment]
Are you trying to access it using port 3000? If you are, you need to add `PORT: 3000` to `meteor.env` in your config.

**Comment by birganovrus** [comment]
@zodern Not exactly, I need to have an access to my app without :3000 port in app's domain name. When I enter "mydomain.com" I see NginX splash screen, however, when I enter "mydomain.com:3000", I see my app.
If I don't add PORT setting in meteor.env, deployment gets failed, I see this " Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use"
