### ISSUE TITLE
How to generate a backup?

### ISSUE THREAD

**Issue by thijssmudde** [zodern/meteor-up#573]
I've got an app up and running and I want to create backups occasionally. Just installed mongodump, but I dont know how to connect to the mongo database.

**Comment by CrackedBeefcake** [comment]
on the server:
`mongodump -d [YOUR_DB] -c [COLLECTION] -o [PATH || ./folder]`

**Valueable Info:**
--port "port"  Default: 27017
-d "database"
-c "collection" Specifies a collection to backup. If you do not specify a collection, this option copies all collections in the specified database or instance to the dump files.


all info [here](https://docs.mongodb.com/manual/reference/program/mongodump/)

**Comment by thijssmudde** [comment]
thanks @FinnFrotscher, but the output directory is empty

Database name is myroutes, when i do 

```
mongodump -d myroutes
connected to: 127.0.0.1
2017-04-09T14:08:03.889+0000 DATABASE: myroutes	 to 	dump/myroutes

```

Filezilla shows an empty directory in dump/myroutes. Port is default and collection is not specified, I need to backup all the data.

**Comment by CrackedBeefcake** [comment]
i am connecting to my servers with `ssh`. I am not sure what your problem is then. 
try to connect to the db with the command 
`mongo` which logs you in. then
`show dbs`, `use [db]` and `show collections`
and make sure the data is there.

**Comment by thijssmudde** [comment]
Im connecting to the mongo db with:

**`docker exec -it mongodb mongo myroutes`**

then 

> show dbs

returns the correct databases (admin, local, myroutes). I cannot back up though with the command you specified (mongodump -d myroutes)

**Comment by CrackedBeefcake** [comment]
```
docker run  --rm \
  --link mongodb:mongo  \
  -v /root:/backup  mongo  bash \
  -c 'mongodump --out /backup --host $MONGO_PORT_27017_TCP_ADDR'
```

now a backup will live at `/root`.
works?

**Comment by thijssmudde** [comment]
yes this works! Thanks @FinnFrotscher
