### ISSUE TITLE
authentication methods failed ERR after not using Mup for a month

### ISSUE THREAD

**Issue by sproleee** [zodern/meteor-up#576]
Not sure what's happening here, but I cant set up my app anymore for deployment. I haven't updated my app in about a month and today, I fight this authentication error: 
`
Error All configured authentication methods failed`

Doesn't really make sense. I can log into my DigitalOcean droplet with my key just fine, but I can't even start with Mup. I did delete Node + Meteor + NPM completely off my computer before re-installing it all.

Not sure if this repository has been updated since then.

**Comment by zodern** [comment]
There have been several updates in the past month, but the authentication should work the same. When you logged into the droplet did you specify the key with `ssh -i path/to/key/in/config root@address` ?

**Comment by sproleee** [comment]
I just remembered that I created new SSH keys to push things to Github and messed everything up. Trying to fix this right now. What a nightmare.

**Comment by albach** [comment]
how did you fix it? I think I am experiencing the same issue.
