### ISSUE TITLE
Superuser permissions [mup deploy]

### ISSUE THREAD

**Issue by erperejildo** [zodern/meteor-up#577]
Deploying my app using Gitlab CI I get this issue after run `mup deploy`:
```
$ mup deploy
Building App Bundle Locally

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local
```

So I run `chown USER /home/USER/.meteor` on my server, but still having same issue so I understand I need to this also on the pipeline with `chown $CI_REGISTRY_USER /home/$CI_REGISTRY_USER/.meteor`
So I check if that folder exists:
```
$ ls -l
total 8
drwxr-xr-x. 2 node node 4096 Apr  8 08:26 node
```
And it doesn't.

I also added this 3 lines as well:
```
- npm install --unsafe-perm
- meteor npm rebuild
- export METEOR_ALLOW_SUPERUSER=true
```

If I run my app locally I don't have any issue with this.

Am I forgetting something?

**Comment by zodern** [comment]
@erperejildo when deploying from a CI, it's okay to run meteor as root. Meteor always shows that warning when it is. Without setting`METEOR_ALLOW_SUPERUSER`, it would also show [this warning](https://github.com/meteor/meteor/blob/340f0f6fd416623489d7cd904402f9c07b3c8df3/tools/cli/main.js#L808) and not build the app.

**Comment by erperejildo** [comment]
Can't run sudo on Gitlab CI. Would this fix the issue?
