### ISSUE TITLE
mkdir error with meteor application deployed using meteor up

### ISSUE THREAD

**Issue by Piyush95aadi** [zodern/meteor-up#578]
Hi, 

I am new to meteor up , I have deployed my application using meteor up on my  amazon EC2 server. The problem is that I am making directory in /opt/DI/<user_Id> , for every user. It is working fine on my local machine when I run the meteor with settings file. But gives error when registering with the application running on EC2: 

"Exception in callback of async function: Error: ENOENT: no such file or directory, mkdir '/opt/DI/dgNGaiPRChqzzsJ93' "

I am using node fs module to make dir.
I cannot find the issue since it is working fine on my local machine.

**Comment by zodern** [comment]
The `/opt` folder doesn't exist. Your app will need to create it first.
