### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by nick-preda** [zodern/meteor-up#579]
Hi guys,

i've been using mup for a while, and now decided to go full SSL.

I changed my mup.js file accordingly, setting:

1. ROOT_URL, in env, starting with https:// and not http://
2. ssl -> autogenerate -> inserted an e-mail and listed the domains pointing at my server.

tried also to install the 'force-ssl' package.

I'm getting, first, the 503 error, Service Temporarily Unavailable, and then i started getting the 502 error, Bad Gateway.

Am I missing some configuration?

Thanks a lot

**Comment by zodern** [comment]
Please install the 1.2.7 beta with `npm i -g mup@1.2.7-beta.0` and try again. It fixed a few bugs and problems with using let's encrypt.

**Comment by nick-preda** [comment]
Thanks for the reply, but still nothing to do.

tried with both
`image: 'kadirahq/meteord'`
and
`image: 'abernix/meteord:base'`

could you specify how you make it work? the real parameters from your mup.js?

**Comment by rclai** [comment]
It worked for me.

**Comment by nick-preda** [comment]
could you please show me your exact configuration of mup.js @rclai ?

**Comment by nick-preda** [comment]
OK, managed to make it work.

Is it possible that the mup with ssl cannot be built because of the `force-ssl` package?

**Comment by sethjgore** [comment]
@nick-preda I'm curious, what worked for you? I keep on getting 502 Bad Gateway.

**Comment by sethjgore** [comment]
`module.exports = {
    servers: {
        one: {
            host: 'xxx.xxx.xxx.xxx',
            username: 'xxx',
            pem: "~/Users/xxx/.ssh/id_rsa"
                // password:
                // or leave blank for authenticate from ssh-agent
        }
    },

    meteor: {
        name: 'app',
        path: '..',
        servers: {
            one: {}
        },
        buildOptions: {
            serverOnly: true,
        },
        env: {
            ROOT_URL: 'https://xxxxxxxxxxxxx',
            MONGO_URL: 'mongodb://xxxxxxxxxxxxx'
        },
        deployCheckWaitTime: 120,
        docker: {
            // image: 'abernix/meteord:base',
            image: 'kadirahq/meteord',
        },
        ssl: {
            autogenerate:{
                email:'xxxxxx@xxxx.com',
                domains:'xxxxxx.com,www.xxxxxx.com'
            }
        }
    }
};
`

**Comment by rclai** [comment]
My config follows the template in the read me.

**Comment by nick-preda** [comment]
@sethjgore i tried going multiple times with the `mup deploy`, and finally it gave me no errors, and it finally worked.

i'm using docker.image
`      image: 'abernix/meteord:base', `

and docker.imageFrontendServer
`imageFrontendServer: 'meteorhacks/mup-frontend-server',`

and for the buildOptions, i've got:
`serverOnly: true,
debug: true,
cleanAfterBuild: true, 
allowIncompatibleUpdates: true,`

for the env, i've got the ROOT_URL the link starting with https, of my real domain.

i've also have
`    deployCheckWaitTime: 120,
    deployCheckPort: 80,
    enableUploadProgressBar: true
`

it sometimes gives me error, during the mup deploy, but relaunching the command everything works, and going to the https everything works.

...still, have to understand how to enforce redirect, from http to https.

hope this helps somehow

EDIT: i'm using the beta: `npm i -g mup@1.2.7-beta.0`

**Comment by ziedmahdi** [comment]
@nick-preda to enforce redirect from http to https add `force-ssl`package to your app.
```sh
$ meteor add force-ssl
```

**Comment by nick-preda** [comment]
@wizonesolutions if I add this package, mup deploy gives me a bunch of errors. tried it, and re-tried again.

is it working for you?

**Comment by wizonesolutions** [comment]
Did you mention me by accident?

**Comment by nick-preda** [comment]
oops @wizonesolutions hahaha
i meant @ziedmahdi

**Comment by ziedmahdi** [comment]
@nick-preda yeah it's working for me.

**Comment by nick-preda** [comment]
adding `force-ssl` it always gives me the same error:

```
[x.x.x.x] x Start Meteor: FAILED

	-----------------------------------STDERR-----------------------------------
	Error response from daemon: endpoint app not found
	Error response from daemon: No such container: app-frontend
	Error response from daemon: endpoint app-frontend not found
	Error response from daemon: endpoint app-nginx-letsencrypt not found
	Error response from daemon: endpoint app-nginx-proxy not found
	--2017-05-02 17:43:25--  https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl
	Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.128.133, 151.101.0.133, 151.101.192.133, ...
	Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.128.133|:443... connected.
	HTTP request sent, awaiting response... 200 OK
	Length: 10088 (9.9K) [text/plain]
	Saving to: ‘/opt/app/config/nginx.tmpl’

	     0K .........                                             100% 24.9M=0s

	2017-05-02 17:43:25 (24.9 MB/s) - ‘/opt/app/config/nginx.tmpl’ saved [10088/10088]

	docker: Error response from daemon: grpc: the connection is unavailable.
	-----------------------------------STDOUT-----------------------------------
```

**Comment by zodern** [comment]
@nick-preda please run `mup docker restart` and try deploying again.

**Comment by nick-preda** [comment]
finally it deployed on my server, with the basic force-ssl package, but the redirect on the https just didn't happen.

i finally tried out another package, the `meteorblackbelt:force-ssl` and everything worked right away.
