### ISSUE TITLE
SSL Autogenerate

### ISSUE THREAD

**Issue by trevordowdle** [zodern/meteor-up#591]
Can setting up SSL really be as simple as adding
```
ssl: {
    autogenerate: {
      email: 'email.address@domain.com',
      domains: 'website.com,www.website.com'
    }
  }
```
To the meteor object in the mup.js file?

I tried adding this and re-running the mup deploy and mup setup commands.  Everything deploys successfully, however my domain is still unsecure.  

Are there any more steps I need to take to get this to work?  Or can someone help me with troubleshooting?  

While running mup setup and deploy I don't see any messages relating to SSL.  I'm also currently on version 1.2.5, I guess I should try this on 1.2.6 but it's my understanding that this should still work.  Here is what I'm seeing.

> mup setup
> 
> Started TaskList: Setup Docker
> [boldvue.com] - Setup Docker
> [boldvue.com] - Setup Docker: SUCCESS
> 
> Started TaskList: Setup Meteor
> [boldvue.com] - Setup Environment
> [boldvue.com] - Setup Environment: SUCCESS
> 
> Started TaskList: Setup Mongo
> [boldvue.com] - Setup Environment
> [boldvue.com] - Setup Environment: SUCCESS
> [boldvue.com] - Copying mongodb.conf
> [boldvue.com] - Copying mongodb.conf: SUCCESS
> 
> Started TaskList: Start Mongo
> [boldvue.com] - Start Mongo
> [boldvue.com] - Start Mongo: SUCCESS

And

> mup deploy
> 
> Your app is using the "force-ssl" package, but ssl is not setup in your mup config.
> This can cause unexpected redirects.
> Building App Bundle Locally
> 
> Started TaskList: Pushing Meteor App
> [boldvue.com] - Pushing Meteor App Bundle to The Server
> [boldvue.com] - Pushing Meteor App Bundle to The Server: SUCCESS
> 
> Started TaskList: Configuring App
> [boldvue.com] - Pushing the Startup Script
> [boldvue.com] - Pushing the Startup Script: SUCCESS
> [boldvue.com] - Sending Environment Variables
> [boldvue.com] - Sending Environment Variables: SUCCESS
> 
> Started TaskList: Start Meteor
> [boldvue.com] - Start Meteor
> [boldvue.com] - Start Meteor: SUCCESS
> [boldvue.com] - Verifying Deployment
> [boldvue.com] - Verifying Deployment: SUCCESS
> 

Thank you, getting the SSL to work and auto-renew is huge.  It's always been a pain to deal with in the past because I only do it once a year and so it's a struggle to plow through it every time.

**Comment by chrissanders** [comment]
I'm having the same issue, although I'm running the very latest version of mup. Redeployment ran fine, but nothing mentioning SSL and I can't connect to the site via HTTPS. I'm not seeing anything in the logs that tells me this was successful or failed.

**Comment by brylie** [comment]
I have updated **mup** to the latest version using `npm install -g mup`, but get the following error with `ssl` in my `mup.json`:

```
1 Validation Errors
  - "ssl" is an unknown property
```

**Comment by brylie** [comment]
Same here. How do we install the version of mup that contains the LetsEncrypt changes?

**Comment by brylie** [comment]
One strange thing occurred. I manually installed certbot on the server after running `mup deploy`. Within about 5 minutes, my server had an active LetsEncrypt certificate. I tried to manually install the certificates once after installing certbot, so that might have had an effect.

**Comment by chrissanders** [comment]
@brylie Can you describe the process you used to install certbot?

**Comment by brylie** [comment]
@chrissanders I followed the [Certbot Ubuntu 16.04 nginx](https://certbot.eff.org/#ubuntuxenial-nginx) instructions.

**Comment by chrissanders** [comment]
No luck after doing something similar here. I captured packets on the server and it sees the inbound connection on 443 but then responds with a TCP RST. I've confirmed via netstat that the server appears to be listening on port 443, but doesn't appear to be handling the request.

**Comment by roelvan** [comment]
I followed this guide with success: [Medium Article (mup + letsencrypt)](https://medium.com/@grahamleslie/setting-up-meteor-meteor-up-letsencrypt-ssl-and-nginx-dddb3b5a4baa)

**Comment by brylie** [comment]
> I've confirmed via netstat that the server appears to be listening on port 443, but doesn't appear to be handling the request.

I had similar errors regarding 443 being taken. I was a bit tired yesterday, so apologies for not providing more info.

**Comment by chrissanders** [comment]
I was able to get this working, although I'm not sure exactly what fixed it. Things I did were:
1. Change the ROOT_URL from http to https in mup.js
2. Only list one subdomain in the ssl section of mup.js
3. Run mup setup from mup/prod
4. Call ./bin/deploy prod

One of those things or a combination of them got me going.

**Comment by trevordowdle** [comment]
Finally got it working... 

It seems I had to install letsencrypt on the production server...  

`sudo apt install letsencrypt`

It wasn't clear... I assumed maybe mup would do this for me during the setup process.

**Comment by brylie** [comment]
We should probably re-open this issue, since the meteor-up command is not automatically installing **letsencrypt** or **certbot**. Most of the other software dependencies are handled automatically by meteor-up, so the SSL configuration would ideally be automated too.

It seems there is a bit of complexity here, with **letsencrypt** being deprecated in favor of **certbot**, and multiple installation options depending on the platform.

**Comment by rajpa** [comment]
I had a running domain+https+meteor. Now, the has certificate expired and has not got automatically renewed. Both letsencrypt and certbot are installed in the system. I deleted all the docker images and ran mup setup, but the certificate expiry problem persists. Pls help.

-rajpa

**Comment by zodern** [comment]
> I had a running domain+https+meteor. Now, the has certificate expired and has not got automatically renewed.

It is a bug in the docker image mup uses for let's encrypt: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/199. A work around is to delete `/opt/<appName>/certs` on the server, and then run `mup reconfig`, forcing it to regenerate the certificates.

**Comment by rajpa** [comment]
thanks @zodern ! 

After I deleted /opt/myapp/certs, the certificate was still not renewed. 

And then I had to open port 80 (!!!) on my domain because of an error I got from /app/letsencrypt_service which said self-certification error due to port 80 not accessible.

And then I ran /app/letsencrypt_service again and restarted the docker container and it is working now...

I wonder if I have to keep 80 open for this thing to work?

cheers
rajpa

**Comment by zodern** [comment]
Let's Encrypt uses port 80 to verify that you own the domain. If the bug with renewing the certificate gets fixed, it will need to use port 80 again in ~60 days.

**Comment by kulttuuri** [comment]
I can't seem to get the letsencrypt SSL working. Do I need to create the nginx proxy myself or should that new ssl autogenerate parameter set it up for me? I first tried with Azure Ubuntu 14.04 LTS but that didn't work and also the `apt-get install letsencrypt` did not work there. So I spinned up new Azure Ubuntu 16.06 LTS VM and ran few commands on the server as suggested on this thread before starting the mup deployment:
`sudo apt-get install letsencrypt`
`sudo apt-get install software-properties-common`
`sudo add-apt-repository ppa:certbot/certbot`
`sudo apt-get update`
`sudo apt-get install python-certbot-nginx`

Those commands ran fine and now I verified that my mup configurations we're correct and my meteor settings file pointed to right place and ran these on my local computer:
`mup setup`
`mup deploy --config=mup.js --settings=default_settings.json`

They worked fine and my app is now accessible through http. However trying to access through https just instantly gives me "This site can’t be reached". I even tried ssh:ing to the server and ran few commands to figure out if the server is listening to the port 443 and if I can access the https port locally on curl.

**Comment by kulttuuri** [comment]
Nevermind, got this one sorted out! I was trying to sign azure test server address, looked up the docker logs for the nginx meteor server instance and it did not want to grant that server an certificate. Added DNS entry to my own server subdomain address and it worked nicely.

Just heads up that with Azure's Ubuntu 14.04 server the letsencrypt did not work at all, but with 16.04 it worked out of the box. It also needs few minutes for the certificate to be signed. Good way to check for certificate signing errors is to SSH into the server computer and first run `sudo docker ps`, get container ID of jrcs/letsencrypt-nginx-proxy-companion:latest and run `sudo docker logs companionContainerID'. That's where I found the error at.

**Comment by zodern** [comment]
Mup uses https://github.com/jwilder/nginx-proxy and https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion for Let's encrypt. Everything they need is part of the docker image.

I updated the [instructions for setting up let's encrypt](https://github.com/zodern/meteor-up#autogenerate-certificates) and added a [section under troubleshooting.](https://github.com/zodern/meteor-up#lets-encrypt-is-not-working)


Some ideas on what can be done to improve this:
- [x] Add the command `mup proxy le-logs` to view the logs of the Let's Encrypt container
- [x] Some of the problems with `nginx-proxy` and `docker-letsencrypt-nginx-proxy-companion` are caused by outdated versions of docker. `mup setup` should make sure docker is a specific version.
- [ ] Add `mup proxy le-status` to see what certificates have been created, are in progress, or have errored.
- [ ] Add the command `mup proxy ssl-troubleshoot` to check for common problems.

Another possible cause of let's encrypt not working is using a CDN such as cloud flare.

**Comment by andy4545** [comment]
I resolved my version of this issue : 

Prognosis : After adding the ssl > autogenerate > email/domains in  .deploy/mup.js , my applcation deployed and verified correctly, and the server started, but trying to reach the site through a browser got a connection refused error. 

Diagnosis : The docker logs for the application container showed no errors, but the myapp-nginx-letsencrypt container logs showed that one of the domains could not be verified.  I had placed my production and staging domains in the domains list on  ssl > autogenerate > domains. 

Resolution: Make sure you only list the domains that are resolvable to the server you are running mup on.

**Comment by FBosler** [comment]
@zodern 

I checked the section under troubleshooting and ran the docker logs <AppName>-nginx-letsencrypt I got the following:

```
2017-07-31 07:32:02,262:INFO:simp_le:1213: Generating new account key
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1404, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1387, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1288, in persist_new_data
    for vhost in args.vhosts
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1288, in <genexpr>
    for vhost in args.vhosts
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 212, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 194, in request_challenges
    return self._authzr_from_response(response, identifier)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 175, in _authzr_from_response
    raise errors.UnexpectedUpdate(authzr)
UnexpectedUpdate: AuthorizationResource(body=Authorization(status=Status(pending), challenges=(ChallengeBody(chall=TLSSNI01(token='\xa0\xa6\xed\xe9\xd9\xfb\xe5\x93M\xd1\x0f\xe2\xa9\t\x8fm\xc6QJP\xd0\xe7\x89\xf6-mH\xdc\xcf\x87\xe5\x1e'), status=Status(pending), validated=None, uri=u'https://acme-v01.api.letsencrypt.org/acme/challenge/9zX5jF48XFna80Vq-fP-39_mZOs-aKqtvuH4cSZCxSY/1652328589', error=None), ChallengeBody(chall=DNS01(token='W;\x84*\xb7\xd0\xdd\xbc\xfcm\xd6\x90\xc6\xc85`\x8f\xa1\x97\xd9:\xaeC9_Z\xf6\x04G\x89\xaf!'), status=Status(pending), validated=None, uri=u'https://acme-v01.api.letsencrypt.org/acme/challenge/9zX5jF48XFna80Vq-fP-39_mZOs-aKqtvuH4cSZCxSY/1652328590', error=None), ChallengeBody(chall=HTTP01(token="\xcf\x9d\xe7\xa0\xe2I\xfb\x1f\x1df\xb1\xca\xcbk\x8ea\xef'\xaf\x9e\r\x07\xa1,\x80\xee\x85M\xfb\x8e\x063"), status=Status(pending), validated=None, uri=u'https://acme-v01.api.letsencrypt.org/acme/challenge/9zX5jF48XFna80Vq-fP-39_mZOs-aKqtvuH4cSZCxSY/1652328591', error=None)), identifier=Identifier(typ=IdentifierType(dns), value=u'bebuzzy.de'), expires=datetime.datetime(2017, 8, 7, 7, 32, 4, 136199, tzinfo=<UTC>), combinations=((2,), (1,), (0,))), new_cert_uri=None, uri='https://acme-v01.api.letsencrypt.org/acme/authz/9zX5jF48XFna80Vq-fP-39_mZOs-aKqtvuH4cSZCxSY')
```

Do you have any idea what this is about?

**Comment by gitTerebi** [comment]
I had problem where I couldn't connect over https:

In domain line, I just added one entry to the subdomain that the app sat on and after that did setup-> deploy and it worked.

**Comment by kishorvaghani** [comment]
This was not working with 1 GB ram in EC2 ubuntu instance, i was able to test https when i used new EC2 instance with 2 GB RAM . it requires minimum of 2 GB ram.

**Comment by fahadakhan96** [comment]
I have a rather dumb question. In the `ssl` part in `mup.js`, which email do I have to type in? Is it my personal email address or something else? And which domain name? Can it be the same as my root URL (which itself is the same as the hostname prefixed with https://)

**Comment by xmaxcooking** [comment]
@chrissanders Step Number 2 fixed it for me. 

Thank you for the details.

- Mup v.1.4.3
- Meteor v1.6.1
- Node v9.8.0
