### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by sethjgore** [zodern/meteor-up#594]
Hello all. Loving the new features in meteor-up now. So good to have autogenerating certificates, however it seems we're still having issues with that? 

I've killed 503 only to face "502 Bad Gateway"

1.2.7 beta won't let me successfully deploy. 

```
	=> Starting meteor app on port:80

	/bundle/bundle/programs/server/mini-files.js:74
	const unicodeNormalizePath = (path) => {
	                                     ^
	SyntaxError: Unexpected token >
```
 1.2.6 deploys succesfully. But I keep on facing 502. 

I've tried almost everything else available in the comments of the open issues.

**Comment by sethjgore** [comment]
i think this is causing the 502 troubles. 

I am getting this from my server.

```docker logs cs-nginx-proxy```

```
[error] 24#24: *50 connect() failed (111: Connection refused) while connecting to upstream, client: aaa.bbb.ccc.ddd, server: website.com, request: "GET /sockjs/info?cb=bgqcxx90nc HTTP/1.1", upstream: "http://172.17.0.2:80/sockjs/info?cb=bgqcxx90nc", host: "website.com", referrer: "https://website.com/find"
```

**Comment by zodern** [comment]
It seems the app can not successfully start. Make sure you are using the correct docker image for the app's meteor version.

**Comment by sethjgore** [comment]
@zodern thanks for replying. You're right, the app isn't starting at all.  Tried updating meteor and switching to kadirahq/meteord from abernix but still not starting. Any ideas why? 
```
docker: {
            image: 'kadirahq/meteord',
            // image: 'abernix/meteord:base',
        },
```

**Comment by sethjgore** [comment]
Finally got it to work. Used Abernix.

For anybody who's struggling, make sure "meteor.ssl.autogenerate.domains" are ACCESSIBLE. If you put down `domain.com, www.domain.com`, make sure www. is actually already set up. 

Also if you are having issues with `force-ssl`, uninstall that and add `meteorblackbelt:force-ssl` instead.

**Comment by tomtom87** [comment]
@sethjgore  I am trying to get this working, thanks for your suggestion.

Sadly I reach the point where, although there was no error the verify deployment stage fails silently and the app is not running.

Really a shame this project is so broken now, used to work great

**Comment by enzolutions** [comment]
I have Meteor 1.5.2 in my local and despite the recommendation the image of docker **abernix/meteord:base** works perfectly

**Comment by tomtom87** [comment]
Oh nice man i love it when stuff fixes itself! Lets hope i get the same luck when i try!

**Comment by ken4ward** [comment]
@sethjgore what do you mean by "make sure www. is actually already set up". Do you mean I should have bought the domain before trying to configure it? Because I do not have it ready. Just added to the config to buy the domain later.

**Comment by x5engine** [comment]
still having this issue sadly :(
