### ISSUE TITLE
help: How to access variables in settings.json

### ISSUE THREAD

**Issue by jLouzado** [zodern/meteor-up#595]
When running `mup init` it also creates a `settings.json` file but I can't seem to find any instruction or documentation regarding how to access that information from within the `mup.json` file.

For example if I don't want to put the Mongo_URL directly in the `mup.json` file and potentially expose it.

**Comment by zodern** [comment]
The `settings.json` file is used for your app.

This version of `mup` uses a `mup.js` file instead, which allows you to use everything available in Node.js.

Two options are:
1) Storing in environment variables. You can use `process.env.VARIABLE_NAME` to access it.

2) Have a `secret.json` file. At the top of your `mup.js` file, add `var secret = require('./secret.json')`, and access it with `secret.propertyName`.

**Comment by jLouzado** [comment]
Thank you. :)
