### ISSUE TITLE
babel issue

### ISSUE THREAD

**Issue by hhertogh** [zodern/meteor-up#597]
I have issues deploying my app with mup.

When doing the mup deploy (in debug mode), I have the following output:

`babel [BABEL] unknown: Start set AST +0ms                                 
  babel program.body[0] ExpressionStatement: enter +286ms
  babel program.body[0] ExpressionStatement: Recursing into... +26ms
  babel program.body[0].expression CallExpression: enter +4ms
  babel program.body[0].expression CallExpression: Recursing into... +2ms
  babel program.body[0].expression.callee FunctionExpression: enter +5ms
  babel program.body[0].expression.callee FunctionExpression: Recursing into... +0ms
  babel program.body[0].expression.callee.body BlockStatement: enter +3ms
  babel program.body[0].expression.callee.body BlockStatement: Recursing into... +14ms
  babel program.body[0].expression.callee.body.body[0] VariableDeclaration: enter +1ms
  babel program.body[0].expression.callee.body.body[0] VariableDeclaration: Recursing into... +11ms
  babel program.body[0].expression.callee.body.body[0].declarations[0] VariableDeclarator: enter +1ms
  babel program.body[0].expression.callee.body.body[0].declarations[0] VariableDeclarator: Recursing into... +1ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].id Identifier: enter +1ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].id Identifier: Recursing into... +2ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].id Identifier: exit +0ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init MemberExpression: enter +1ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init MemberExpression: Recursing into... +1ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init.object MemberExpression: enter +10ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init.object MemberExpression: Recursing into... +0ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init.object.object Identifier: enter +1ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init.object.object Identifier: Recursing into... +1ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init.object.object Identifier: exit +1ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init.object.property Identifier: enter +0ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init.object.property Identifier: Recursing into... +1ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init.object.property Identifier: exit +1ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init.object MemberExpression: exit +0ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init.property Identifier: enter +3ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init.property Identifier: Recursing into... +0ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init.property Identifier: exit +1ms
  babel program.body[0].expression.callee.body.body[0].declarations[0].init MemberExpression: exit +1ms
  babel program.body[0].expression.callee.body.body[0].declarations[0] VariableDeclarator: exit +3ms
  babel program.body[0].expression.callee.body.body[0] VariableDeclaration: exit +0ms
  babel program.body[0].expression.callee.body.body[1] VariableDeclaration: enter +1ms
  babel program.body[0].expression.callee.body.body[1] VariableDeclaration: Recursing into... +6ms
  babel program.body[0].expression.callee.body.body[1].declarations[0] VariableDeclarator: enter +2ms
  babel program.body[0].expression.callee.body.body[1].declarations[0] VariableDeclarator: Recursing into... +0ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].id Identifier: enter +1ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].id Identifier: Recursing into... +1ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].id Identifier: exit +1ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init MemberExpression: enter +1ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init MemberExpression: Recursing into... +0ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init.object MemberExpression: enter +1ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init.object MemberExpression: Recursing into... +4ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init.object.object Identifier: enter +2ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init.object.object Identifier: Recursing into... +1ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init.object.object Identifier: exit +2ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init.object.property Identifier: enter +1ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init.object.property Identifier: Recursing into... +1ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init.object.property Identifier: exit +0ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init.object MemberExpression: exit +1ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init.property Identifier: enter +1ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init.property Identifier: Recursing into... +2ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init.property Identifier: exit +15ms
  babel program.body[0].expression.callee.body.body[1].declarations[0].init MemberExpression: exit +1ms
`

and it seems to continue like this forever.. any idea how to solve this?

**Comment by zodern** [comment]
Is this while building the app, or when starting it?

**Comment by hhertogh** [comment]
I can close this issue, it was an error linked to the building process of meteor.
I could resolve it by following: https://github.com/meteor/meteor/issues/8020#issuecomment-265758830

Thanks.
