### ISSUE TITLE
[1.2.7] Unhandled promise rejection after upgrade

### ISSUE THREAD

**Issue by spinualexandru** [zodern/meteor-up#599]
After upgrading from 1.2.6, I am trying to deploy ( I am running Ubuntu 17.04 ) and I am getting the following error:
`(node:6902) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot use 'in' operator to search for 'autogenerate' in undefined
(node:6902) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I rolled back to 1.2.6 and works perfect.

**Comment by kalepail** [comment]
I'm facing this issue as well. 
Node v7.10.0

**Comment by PedroJimenez73** [comment]
How to downgrade to 1.2.6 please?

**Comment by zodern** [comment]
I just released 1.2.8, which fixes this.
