### ISSUE TITLE
Content Security Policy: The page’s settings blocked the loading of a resource

### ISSUE THREAD

**Issue by trevordowdle** [zodern/meteor-up#602]
I am getting the following error:

Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://mydomain.com

Current Settings:
 
> HTTP/1.1 200 OK
> Server: nginx/1.13.0
> Date: Mon, 08 May 2017 05:14:59 GMT
> Content-Type: text/html; charset=utf-8
> Connection: keep-alive
> X-Content-Type-Options: nosniff
> X-Frame-Options: SAMEORIGIN
> Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; connect-src * 'self'; img-src data: 'self'; style-src 'self' 'unsafe-inline';
> Vary: Accept-Encoding
> Strict-Transport-Security: max-age=31536000

The content security policy seems to be related to nginx.  If I try to add my own meta tag to allow media-src 'self' it doesn't seem to work.

Can anyone help me solve this issue?  Is there a way to address it through the mup.json file?  Or do I need to log into the server and track down the config file?  ( I have searched the server to find where the Content-Security-Policy is set without any luck)

Thanks

**Comment by zodern** [comment]
Meteor Up shouldn't be setting the `content-security-policy` header. Are you sure you are not using the `browser-policy` or similar package?

**Comment by trevordowdle** [comment]
Thank you for clarifying that Meteor Up doesn't set anything related to the **content-security-policy**

I'll review my packages this evening.

Appreciate it.
