### ISSUE TITLE
'Mup Setup' returning only 'Setup Docker'.

### ISSUE THREAD

**Issue by embub** [zodern/meteor-up#603]
Hi everyone,

when trying to setup my mup.js config, my terminal returns only this:

```
~/emvulcan/vulcan/.deploy$ mup setup

Started TaskList: Setup Docker
[localhost] - Setup Docker
```

I'm not sure what is going wrong in my mup.js, I've mostly been following the sample configuration. Has anyone else had this problem?

**Comment by zodern** [comment]
You can run `mup setup --verbose` to see what it is doing on the server.
Does it get stuck at that step, or does it exit?

**Comment by embub** [comment]
That command returns the exact same as above and exits.

**Comment by zodern** [comment]
Try running `DEBUG=* mup setup --verbose`. Could you also please share your config?

**Comment by zodern** [comment]
@embub did you get it to work?

**Comment by cry-chen** [comment]
@zodern I have the same problem; when I run the DEBUG line it says "setup: command not found"
When I run mup setup --verbose, same thing happens as when I run mup setup, which is that it gets stuck and says 
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:138:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

**Comment by Lucbug** [comment]
This error can happen if your IP address cannot SSH. Make sure your IP hasn't changed, or change your rules/IP in the security groups of the service you are using.
