### ISSUE TITLE
Latest Version Issue With SSL 

### ISSUE THREAD

**Issue by isAlmogK** [zodern/meteor-up#609]
I just update to the latest version of meteor-up and deployments are fine however there seems to be an issue with the SSL. New certificates have been generated on the server but are not being mounted correctly. Seems to be directly due to the version 1.2.7 - https://github.com/zodern/meteor-up/releases

Is there a way to roll back to an older working version.

**Comment by zodern** [comment]
You can install an older version with `npm i -g mup@<version>`.

I would like to know why it isn't working for you. I reinstalled a server, and then deployed an app to it with let's encrypt enabled, and it worked. 
- Can you please share your config?
- Were you able to use let's encrypt with that app with an older version of mup?
- Do you have the correct DNS entrees for each domain listed in `meteor.ssl.autogenerate.domains`?

**Comment by isAlmogK** [comment]
@zodern I was just testing different versions, I don't think it's mup but as the older versions did not work. It's a bit confusing as everything was working until 2 days. Maybe you have an idea. You can see the issue here https://app-staging.mentorloop.com/ 

Hosted on AWS, not using let's encrypt I remember there was some issue with it 

Here is the config file (I removed the sensitive info)

module.exports = {
  servers: {
    one: {
      host: 'Address removed',
      username: 'Removed',
      pem: '~/.ssh/cc_mentorloop_sydney.pem',
    },
  },

  meteor: {
    name: 'mentorloop-staging',
    path: '../..',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      ROOT_URL: 'https://app-staging.mentorloop.com',
      MAIL_URL: '',
      MONGO_URL: '',
      MONGO_OPLOG_URL: '',
      SEND_GRID_API_KEY: ''
    },

    docker: {
      image: 'abernix/meteord:base',
    },

    ssl: {
      // Enables let's encrypt (optional)
      // This is disabled because it doesn't work and we don't yet understand why.
      // autogenerate: {
      //   email: 'admin@mentorloop.com',
      //   domains: 'app-staging.mentorloop.com', // comma seperated list of domains
      // },

      // currently have to upload a cert and key manually
      // you only need to do this when the cert expires
      // or you're deploying to a new instance.
      // you'll need the .pem files.
      crt: './chain.pem',
      key: './privkey.pem',
      port: 443,
      upload: false, // set to true when you actually need to use the certs
    },

    // This is the maximum time in seconds it will wait
    // for your app to start
    // Add 30 seconds if the server has 512mb of ram
    // And 30 more if you have binary npm dependencies.
    deployCheckWaitTime: 60,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true,
  },
};

**Comment by zodern** [comment]
The certificate expired on May 10th.

**Comment by isAlmogK** [comment]
Thanks, I didn't see that
