### ISSUE TITLE
Deploy ignoring external mongodb / url

### ISSUE THREAD

**Issue by mariobaldini** [zodern/meteor-up#61]
Hi, 

I installed mup, set up the server and deployed it successfully (from commit t 7dfd01d). (just need to add deployCheckWaitTime: 60).

```
(...)
[logview-webapp-sl.logview.com.br] - Verifying Deployment
[logview-webapp-sl.logview.com.br] - Verifying Deployment: SUCCESS  
```

The deploy runs, but apparently from a 'fresh' mongodb, and not the custom MONGO_URL. I'm using mongolab for the mongodb -- outside the deploy VM.

With an old mup version it worked fine. I used "setupMongo": false in the mup.json, but I'm not sure where to put it in the mup.js of the newer version. Anyway, even if it gets set up, the MONGO_URL should be the one which is effectively used, right?

I'm assuming that it's using a new/fresh DB because the credentials in the deploy doesn't work. But another deploy which is using the same DB / MONGO_URL is working fine. 

My mup.js: 

```
module.exports = {
  servers: {
    one: {
      host: 'logview-webapp-sl.logview.com.br',
      username: 'XXXX',
      password: 'XXXX',
      // pem: './mykey',
    },
  },

  meteor: {
    name: 'logview',
    path: '/atto/logview-webapp',
    servers: {
      one: {},
    },

    env: {
      ROOT_URL: 'http://logview-webapp-sl.logview.com.br',
      MONGO_URL: 'mongodb://logview:XXXXXXXX@ds029435-a0.mongolab.com:29435,ds029435-a1.mongolab.com:29435/logview?replicaSet=rs-ds029435',
      LOGVIEW_EVENTLOG_ENABLE: 'false', 
      LOGVIEW_TELEGRAM_ENABLE: 'false'
    },
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

Maybe the URL having the replica set parameters is causing any issue?

PS: I confirmed that with a 'simpler' URL the issue persists. 
`mongodb://logview:XXXXX@ds029605.mongolab.com:29605/logview-dev`

Thank you!

**Comment by madushan1000** [comment]
try removing `mongo` field in `mup.js`. If that field is present, Mup automatically installs mongodb.

**Comment by mariobaldini** [comment]
Thank you @madushan1000, that worked. 

I'm closing the issue. Although I think that mup should use the MONGO_URL even if the mongo instance is installed, otherwise whats's the point of explicit setting that variable. 

Thank you,
