### ISSUE TITLE
Run Script after Deploy

### ISSUE THREAD

**Issue by slinkardbrandon** [zodern/meteor-up#610]
I've run into an issue where every time I deploy my app with mup I need to reinstall wkhtmltopdf to my docker container.

Is there any way we could build out a way to run scripts on the fresh docker instance after a deploy completes?

**Comment by zodern** [comment]
The best option is to use a docker image with wkhtmltopdf already installed. I will be working on making that easier, but for now you can fork the image you currently are using, add a step to install wkhtmltopdf, publish it to the docker hub, and in your config set it to use your image.

Another option is to have your app check if it is installed, and if not use the built-in module `child_process` to run the command or a script to install it. Using a docker image would be better.

**Comment by slinkardbrandon** [comment]
How would I set the config to use a specific image?

I didn't even know this was an option but don't even know where to start.

**Comment by slinkardbrandon** [comment]
Thanks, I've got this resolved now!

All I did was this:

1.) Created a repository on https://hub.docker.com and named it "slinkardbrandon/wkmeteor"
2.) Took my configured docker image (with wk installed) and did a docker commit (using this command):
sudo docker commit cc6728a075e5 slinkardbrandon/wkmeteor:base
3.) Changed my mup.js file to reflect the new docker repository.

Anyone looking for wkhtmltopdf pre-installed on a docker image feel free to use this in your mup file:

docker: {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;image: 'slinkardbrandon/wkmeteor:base'
},

**Comment by mark-alfonso** [comment]
Hi @slinkardbrandon -- I know this is just last year but for my use case I need to use the latest docker image `abernix/meteord:node-8-base` for meteor 1.6.1, could you share the step you did to install wkhtmltopdf?
