### ISSUE TITLE
./ is not a meteor app

### ISSUE THREAD

**Issue by zeekun** [zodern/meteor-up#611]
I recently updated mup but immediately when i run mup deploy, I get an error telling me 'is not a meteor app'. What would be the problem?

**Comment by albertonaperijr** [comment]
Where did you put your `mup.js` file? If it's inside `.deploy` folder then you need to change `path: './'` to `path: '../'`.

**Comment by zeekun** [comment]
@albertonaperijr thank you, it has worked
