### ISSUE TITLE
Let's Encrypt makes websocket fail

### ISSUE THREAD

**Issue by ghost** [zodern/meteor-up#612]
Trying Let's Encrypt for the first time with my mup deployment. Using the autogenerate clause in the SSL area of mup.js causes a websocket connection error after my app is deployed.

In Chrome's console:

`WebSocket connection to 'wss://....' failed: Error in connection establishment: net::ERR_NOT_IMPLEMENTED`

I usually use uploaded certs and that works fine. I use `abernix/meteord:base` docker image. Here is the mup.js I'm using:

    module.exports = {
		servers: {
				one: {
						host: '172.217.5.110',
						username: 'root',
						pem: '/Users/al/.ssh/id_rsa.do'
				}
		},

		meteor: {
				name: 'sub-domain',
				path: '/Users/al/cool-app',
				docker: {
						image: 'abernix/meteord:base'
				},
				servers: {
						one: {}
				},
				buildOptions: {
						serverOnly: true,
				},
				env: {
						ROOT_URL: "https://sub.domain.com",
						NODE_ENV: "production",
						MONGO_URL: "mongodb://...",
						MONGO_OPLOG_URL: "mongodb://..."
				},
				ssl: {
						port: 443,
						autogenerate: {
							email: 'admin@domain.com',
							domains: 'sub.domain.com'
						}
				},
				deployCheckWaitTime: 60
		},

    };

Is this a known issue? Is there a workaround I can currently use?

I'm on the latest mup 1.2.8.

**Comment by trevordowdle** [comment]
I'm having a simillar issue, i'm getting an errror on the client though.

WebSocket connection to 'wss://mydomain.com:3200/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Is this related? Granted, since I'm having trouble initiate the connection on the client end I don't even know if the web socket code on the server would work.

And Is there a work around for this in the meantime?

**Comment by trevordowdle** [comment]
@zodern Hey Zodern, this issue is rather urgent for me.  Could you give me any guidance for a temporary work around or a possible solution?  Maybe this is something with a little guidance that I can work on and send in a pull request.

Thank you

**Comment by zodern** [comment]
Is the app also on port 3200? Are you using Let's Encrypt or the reverse proxy?

**Comment by trevordowdle** [comment]
@zodern I just picked a random port for the WebSockets, I figured It would be good to use a different port than the app was using.

I'm using Let's Encrypt. 

Thanks

**Comment by trevordowdle** [comment]
@zodern  any thoughts?  Should I be initiating the WebSocket connection on the same port?

**Comment by ghost** [comment]
@trevordowdle a workaround for me was to simply not use let's encrypt with mup. Instead put the instance behind CloudFlare (free) and use CloudFlare SSL which auto-renews and needs no management of certs.

CloudFlare now supports websockets very well out of the box, including the ones needed for Meteor, which is why this workaround is relatively new.

**Comment by trevordowdle** [comment]
@alstephan Great thank you

**Comment by zodern** [comment]
I am not able to reproduce this. Could you please try with the mup 1.4 beta: #870 ?

**Comment by zodern** [comment]
Since I am unable to reproduce it, I will close this issue. If anyone encounters this again, the issue can be reopened.

**Comment by erwzqsdsdsf** [comment]
I had the same problem
