### ISSUE TITLE
buildOptions debug true still minifies JS files

### ISSUE THREAD

**Issue by WayneUong** [zodern/meteor-up#613]
All the js files are minified even when I set buildOptions debug to true. This wasn't the case in the past.

**Comment by zodern** [comment]
What package are you using to minify js?

**Comment by WayneUong** [comment]
@zodern I found out that its the  `--cached-build` tag that causes all the subsequent builds to be minified like the first build. So which settings are carried over and which are not with  `--cached-build`?

**Comment by zodern** [comment]
It reuses the build from the last time you deployed without the `--cached-build` flag. The bundle doesn't change until you deploy without that flag. It was mainly intended to be used after the bundle failed to upload from a connection error.
