### ISSUE TITLE
VERIFYING DEPLOYMENT FAILED 

### ISSUE THREAD

**Issue by zeekun** [zodern/meteor-up#614]
Hullo, I keep getting this error.
What would be the problem?

![meteor](https://cloud.githubusercontent.com/assets/28468199/26105048/2e37fb6e-3a49-11e7-8cc4-07523e1c289c.PNG)

**Comment by haibo32012** [comment]
I got this:
![screenshot from 2017-05-25 20 49 56](https://cloud.githubusercontent.com/assets/7117248/26450814/da64c75c-418b-11e7-8986-11e30becdf72.png)
mup logs:
![screenshot from 2017-05-25 21 01 58](https://cloud.githubusercontent.com/assets/7117248/26451178/7ee4b3d6-418d-11e7-871a-55a76dbcde22.png)

**Comment by ZubMono** [comment]
I'm getting the same error, sometimes It works after trying a lot of times.

**Comment by tomtom87** [comment]
+1 Getting same error. Glad I am not alone

**Comment by zodern** [comment]
The readme has a [troubleshooting section for this.](https://github.com/zodern/meteor-up#verifying-deployment-failed). I just pushed some changes to make it more clear.

@zeekun There wasn't enough time for `npm install` to finish. Increase `meteor.deployCheckWaitTime`.

@haibo32012 @ZubMono and @tomtom87 Make sure you have the latest version of mup (`mup --version` should show `1.2.9` or newer; update with `npm i -g mup`), and then run `mup deploy --verbose`. Please post the output after `Started TaskList: Start Meteor`
