### ISSUE TITLE
Verifying Deployment: FAILED when server returns code 401 Unauthorized

### ISSUE THREAD

**Issue by ovidyou** [zodern/meteor-up#618]
Using `DEBUG=mup* mup deploy --verbose` I found out that MUP interprets the HTTP Status Code **401 Unauthorized** as a failed deployment, but in my use case this is perfectly  valid, since I use basic authentication on the server.

The curl error is: `curl: (22) The requested URL returned error: 401 Unauthorized`

**Comment by zodern** [comment]
I added that to fix problems with verifying deployment for apps using Let's Encrypt. Is your app using it? If not, I can modify it to only fail when using Let's Encrypt.

**Comment by ovidyou** [comment]
No, the app is not using Let's Encrypt. That would help, thanks.

**Comment by tomtom87** [comment]
@zodern  I am getting an issue with let's encrypt. The server doesn't ever verify although all other stages pass to completion.

**Comment by zodern** [comment]
@ovidyou I instead created the [zodern:mup-helpers](https://atmospherejs.com/zodern/mup-helpers) meteor package to fix this. The solution I mentioned above would have only fixed this for apps not using let's encrypt, but this package works for all apps using mup. Update mup with `npm i -g mup`, add the package, and redeploy.

@tomtom87 Please add the `--verbose` flag and post the output here from the verify stage.

**Comment by ovidyou** [comment]
@zodern thanks. Unfortunately this still doesn't work when using [jabbslad:basic-auth](https://atmospherejs.com/jabbslad/basic-auth), I get the same curl error as in first post.

I guess for my use case and other use cases could be really helpful to be able to specify in the mup settings the HTTP status codes that should be treated as valid deployment. If you are willing to have this type of functionality implemented, I could offer my time to create a pull request. Let me know.

**Comment by zodern** [comment]
I released 1.2.10 which removes the HTTP status code requirements.

**Comment by tomtom87** [comment]
+1 doesnt work with force-ssl either by the way @zodern

**Comment by zodern** [comment]
What version of mup are you using (`mup --version`)?

**Comment by ovidyou** [comment]
@zodern I confirm mup 1.2.10 successfully deployed the app. Big thanks!

**Comment by sunlee-newyork** [comment]
Not sure if my issue is related to this, but I realized the basic authentication I had set up directly in my server before SSL (proxy 3000 to 80) became obsolete after I added letsencrypt ssl autogenerate and I can't figure out a way to add `basic_auth` to 443.
