### ISSUE TITLE
Meteor-Up and Docker Swarm Support

### ISSUE THREAD

**Issue by ustimb** [zodern/meteor-up#620]
Meteor-Up is very convenient for Meteor apps to a single Docker host.  Are there any plans to include support for Docker Swarm directly in the near future?

**Comment by zodern** [comment]
I am planning to look into it.

**Comment by KoenLav** [comment]
@zodern are there any specific issues you expect to run into?

I suppose adding this functionality would revolve mainly around rewriting:

docker
 run \
  -d \
  --restart=always \
  <% if(sslConfig && typeof sslConfig.autogenerate === "object")  { %> \
  --expose=80 \
  <% } else { %> \
  --publish=$BIND:$PORT:<%= docker.imagePort %> \
  <% } %> \
  --volume=$BUNDLE_PATH:/bundle \
  --hostname="$HOSTNAME-$APPNAME" \
  --env-file=$ENV_FILE \
  <% if(useLocalMongo)  { %>--link=mongodb:mongodb --env=MONGO_URL=mongodb://mongodb:27017/$APPNAME <% } %>\
  <% if(logConfig && logConfig.driver)  { %>--log-driver=<%= logConfig.driver %> <% } %>\
  <% for(var option in logConfig.opts) { %>--log-opt <%= option %>=<%= logConfig.opts[option] %> <% } %>\
  <% for(var volume in volumes) { %>-v <%= volume %>:<%= volumes[volume] %> <% } %>\
  <% for(var args in docker.args) { %> <%- docker.args[args] %> <% } %>\
  <% if(sslConfig && typeof sslConfig.autogenerate === "object")  { %> \
    -e "VIRTUAL_HOST=<%= sslConfig.autogenerate.domains %>" \
    -e "LETSENCRYPT_HOST=<%= sslConfig.autogenerate.domains %>" \
    -e "LETSENCRYPT_EMAIL=<%= sslConfig.autogenerate.email %>" \
    -e "HTTPS_METHOD=noredirect" \
  <% } %> \
  --name=$APPNAME \
  <%= docker.image %>

Right?

We are currently looking into deploying our application to a Docker Swarm (and were already making use of meteor-up). We will be testing ourselves over the next few weeks, but if there are any points you could give us that would be greatly appreciated (willing to create a PR with our test results, possibly already (semi-)working code).

**Comment by zodern** [comment]
A PR would be greatly appreciated!

I went through the [swarm tutorial](https://docs.docker.com/engine/swarm/swarm-tutorial/) today to get an overview of what is involved and how it works.

1) You probably will need a way to know which servers are a manager. The servers that are a manger could have `manager: true` in the config.  Also, `meteor.servers` would no longer be needed, and instead you could have a property with how many app containers to run.
2) To setup docker swarm, you will want to modify [docker-setup.sh](https://github.com/zodern/meteor-up/blob/master/src/modules/docker/assets/docker-setup.sh). You can run a command on an individual server and get the output using [runSSHCommand](https://github.com/zodern/meteor-up/blob/7378b98b36e5654156c3ef6077cf2f18374ef79e/src/modules/utils.js#L114). [example](https://github.com/zodern/meteor-up/blob/56676c748d28fe3feeeb006e350c64a8a55cddab/src/modules/mongo/__tests__/index.js#L53). `info` is an object from `servers` in the config.
3) You are right that it would mostly involve rewritting that section of [start.sh](https://github.com/zodern/meteor-up/blob/7378b98b36e5654156c3ef6077cf2f18374ef79e/src/modules/meteor/assets/templates/start.sh). 
4) `mup` installs docker the first time `mup setup` is run, and usually it never gets updated again on that server. What I would like to do is have `docker-setup.sh` check if docker is a specific version, and, if it is not, install that version. Or it could have a minimum docker version, and update docker if it is older than that version. This way we always know what docker features are available. 

> @zodern are there any specific issues you expect to run into?

Some potential edge cases.
1) App 1 is deployed to servers 1, 2, 3, and 4, and app 2 is deployed to servers 4, 5, 6, and 7. Is it possible to have the servers from both apps create 1 swarm, or is there another option?
2) It would need to handle the servers the manager nodes were on being reinstalled, or destroyed, or removed from the list of servers but still running as managers.

If you have any questions, please ask them.

**Comment by zodern** [comment]
I currently am planning to implement this in Mup 1.5.
1.4 will have some of the initial work.

**Comment by adamgins** [comment]
@zodern keen to understand more about this please. We have the Swarm requirements... cloud possibly help out. Or if it's already underway, keen to know if you have rough delivery date?

**Comment by zodern** [comment]
@adamgins The code is in the `dev` branch, and you can view the current status in #976 and #893. I am hoping to release it in January.

**Comment by adamgins** [comment]
@zodern happy new year... I was just checking in... is there something I could try with swarm?

**Comment by adamgins** [comment]
@zodern just checking in, if this work is still planned?

**Comment by zodern** [comment]
@adamgins it is still planned.

**Comment by zodern** [comment]
If anyone wants to try this, it is available in the Mup 1.5 beta: https://github.com/zodern/meteor-up/pull/976

The docs are at https://github.com/zodern/meteor-up/blob/0f1cac751a69ca09407ec433b454398a8b8edf0c/docs/docs.md#swarm

I would not recommend using it in production at this point.

**Comment by zodern** [comment]
There are still some rough edges, but the swarm integration is much more complete and stable in the latest 1.5 betas. I would appreciate any feedback or help testing it.
