### ISSUE TITLE
How to access my assets in the public directory?

### ISSUE THREAD

**Issue by adrprado** [zodern/meteor-up#621]
I have a few images stored in the 'public/images' directory. It works pretty fine when I run locally (meteor run), but it won't show up after deployed by MUP.

This is how I call the image in my .html file:

`<img [src]="/images/logo.png" alt="">`

I tried to locate this image inside the docker container (`docker exec -it my-app bash --login`) with no success (`find / -name "logo.png"`).

Is there a way to export and use asset files in MUP?

**Comment by zodern** [comment]
Meteor includes the files in the `public` folder in the bundle that mup uploads to the server. If anyone still has this issue, please create a new issue or we can reopen this one.
