### ISSUE TITLE
Nginx config: redirect to url on error

### ISSUE THREAD

**Issue by Twisterking** [zodern/meteor-up#622]
Hi guys!
So an idea which should be pretty easy to implement:
The user can define a `url` in the `mup.js` under the `nginx` key ...
something like `redirectOnErrorUrl` maybe.
If an error occurs in the nginx proxy, something like the usual `502 bad gateway` while a new version is being deployed, the user would just be redirected to this url, e.g. a standard "we are currently updating our service" page or something like that. I think this would be a great feature for production apps.

If someone can guide me a bit into the right direction on how to approach this I can lead the way on this, do a fork and a PR.
What do you think?

best, P

**Comment by zodern** [comment]
Thanks for offering to work on this. I don't think this feature is needed since future versions of Mup will have
- zero downtime deploys. 
- Custom nginx configs
