### ISSUE TITLE
How to access meteor shell?

### ISSUE THREAD

**Issue by znat** [zodern/meteor-up#623]
Is there something like `docker exec -it <app-name> ...` available?

**Comment by adrprado** [comment]
I believe the `meteor` command is not available after building you app, hence this command is not available in production.

**Comment by zodern** [comment]
It is not possible to access `meteor shell`. What would you use it for?

**Comment by brylie** [comment]
I need to access the Meteor shell to run a method on the server.

**Comment by brylie** [comment]
> It is not possible to access meteor shell. What would you use it for?

It would be useful for troubleshooting and data manipulation in a deployment.

Right now, I am trying to do some bulk-data processing that is specific to a deployment, where a migration would not be appropriate. If I had access to the Meteor shell, I could execute a few lines of JavaScript to get the job done, whereas I am currently wrestling with startup scripts and temporary startup.js file in my repo.
