### ISSUE TITLE
How can I tell if mup setup has worked?

### ISSUE THREAD

**Issue by Joeblockmark** [zodern/meteor-up#624]
I am trying to deploy an app to an ubuntu VPS with plesk installed. After running `mup setup` I can't see any changes new files or anything on the server. My assumption is that the the command isn't working but there is no error message. It says in the console:

Started TaskList: Setup Docker

[111.222.333.444] - Setup Docker

**Comment by Joeblockmark** [comment]
It's working now. For each task it should say:
[ip] - task
[ip] - task: SUCCESS

**Comment by zodern** [comment]
@Joeblockmark do you know what fixed it?

**Comment by Joeblockmark** [comment]
The problem was something very stupid: I was running mup deploy in the wrong folder, but it would be nice if there was a clear error message
