### ISSUE TITLE
.deploy is not a meteor app

### ISSUE THREAD

**Issue by crstn210** [zodern/meteor-up#627]
i´m trying to deploy the app just like before, executing mup from .deploy folder but its not working 

`C:\Users\crist\Google Drive\brik\.deploy>C:\Users\crist\AppData\Roaming\npm\mup.cmd deploy
Building App Bundle Locally
C:\Users\crist\Google Drive\brik\.deploy is not a meteor app

C:\Users\crist\Google Drive\brik\.deploy>`

**Comment by zodern** [comment]
Make sure `meteor.path` in your config is correct. Right now it is relative to where you run mup instead of relative to the location of the config.

**Comment by crstn210** [comment]
Thanks, my `meteor.path` was `'.'` now is `'../'` it seems to work now
