### ISSUE TITLE
Unable to run due to missing binary

### ISSUE THREAD

**Issue by pociej** [zodern/meteor-up#628]
Hi i just noticed strange behaviour so iinstalled mup gloablly 
and wanted to run. It throws : 
`/usr/local/bin/mup: No such file or directory` 
Its true but what is strange , im using nvm and currently im on 6.3.1 
and other packages like mocha i installed globally are only 
in : `.nvm/versions/node/v6.3.1/bin/` not in `/usr/local/bin/mup: ` 
and i can run it normally, only problem is mup. 
Do you think its problem with mup or my npm installation ?

**Comment by zodern** [comment]
It looks like a problem with how npm installed it. Did you change the node version since installing mup?
