### ISSUE TITLE
Two Meteor Apps sharing Single Database

### ISSUE THREAD

**Issue by iAssureIT** [zodern/meteor-up#630]
Hi All,

I am tired of reading all issues over internet with this subject line, but not able to find a credible solution. Can someone please help? 
I am using mup to deploy two meteor apps, which are using same database. But following two mup.js for two apps are not giving me the desired result. 
For two apps:  App1 & App2, I am giving same MONGO_URL. But when I do mup deploy, it creates two separate databases with same name as apps as App1 and App2. 
What is the mistake? What should I write in mup.js file in order to run two apps with same database? 
**App1:  mup.js**
`meteor: {
    // TODO: change app name and path
    name: "app1",
    path: "/var/www/meteor/app1",

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://app1.com',
      MONGO_URL: 'mongodb://127.0.0.1:27017/appdb',
      PORT: 3003,
    },
`

**App2:  mup.js**
`  meteor: {
    // TODO: change app name and path
    name: 'app2',
    path: '/var/www/meteor/app2',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://app2.com',
      MONGO_URL: 'mongodb://127.0.0.1:27017/appdb',
      PORT: 3004,
    },
`

**Comment by zodern** [comment]
For `app2`:
- Remove `mongo` from the config
- Change the `env.MONGO_URL` to `mongodb://mongodb:27017/<app1 name>`
- Your `meteor.docker` object should look similar to:
```js
    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/meteord:base',
      args: [
        '--link=mongodb:mongodb'
      ]
    },
```

**Comment by avishaan** [comment]
@zodern, nice! Going to try this out just now as I was about to ask the same question

**Comment by avishaan** [comment]
@zodern @iAssureIT that worked for me just as a heads up

**Comment by zodern** [comment]
I added it to the documentation for Mup 1.3
