### ISSUE TITLE
Error response from daemon: driver failed programming external connectivity on endpoint

### ISSUE THREAD

**Issue by thijssmudde** [zodern/meteor-up#631]
`	
	-----------------------------------STDERR-----------------------------------
	Removing docker containers. Errors about nonexistent endpoints and containers are normal.
	Error response from daemon: No such container: myroutes
	Error response from daemon: endpoint myroutes not found
	Error response from daemon: No such container: myroutes-frontend
	Error response from daemon: endpoint myroutes-frontend not found
	Error response from daemon: No such container: myroutes-nginx-letsencrypt
	Error response from daemon: endpoint myroutes-nginx-letsencrypt not found
	Error response from daemon: No such container: myroutes-nginx-proxy
	Error response from daemon: endpoint myroutes-nginx-proxy not found
	Finished removing docker containers
	docker: Error response from daemon: driver failed programming external connectivity on endpoint myroutes (8231a8806fda11ab47b00e17547623f42ecf8c68b56ac483ede958ad996135b3): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.
	-----------------------------------STDOUT-----------------------------------
	base: Pulling from abernix/meteord
	Digest: sha256:9ed85313621010dd27a08054ae9225aa1f31798647fbcfdc9cc082181c6f9c97
	Status: Image is up to date for abernix/meteord:base
	Pulled abernix/meteord:base
	8e0866a9c801125fba4ebd306ccf831b91183241034576313c3ab564fb4e9d4c
	----------------------------------------------------------------------------
`

Just tried deploying a new version of my meteor up with Meteor Up. This error appeared. I already tried:

- service docker restart on the droplet.
- mup restart

I just keep redeploying, it does not seem to help. Its quite urgent, because now the site is down.

**Comment by zodern** [comment]
Something is using port 80. You can run `mup docker ps` to see if a container is using it.

**Comment by thijssmudde** [comment]
@zodern I can see the container I created 3 months ago. What should I do next?

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                        NAMES
6c233e721193        mongo:3.4.1         "/entrypoint.sh mo..."   3 months ago        Up 2 minutes        127.0.0.1:27017->27017/tcp   mongodb

**Comment by thijssmudde** [comment]
Okay, i tried killing the container and then redeploying. This does not help sadly. Same error:

docker: Error response from daemon: driver failed programming external connectivity on endpoint myroutes (353e0cf3ad2f1c498349db93c4925e277736f08520ca9dbbad293317e3307d94): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.

**Comment by zodern** [comment]
Ssh into the server, and run `netstat -tulpn | grep :80`. It will show you what is using port 80.

**Comment by thijssmudde** [comment]
Ok thanks, I can see nginx is running:

tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      5137/nginx -g daemo
tcp6       0      0 :::80                   :::*                    LISTEN      5137/nginx -g daemo

I used sudo fuser -k 80/tcp to stop it, but its not helping. Can you please point out what I have to do to get it working?

**Comment by zodern** [comment]
Are you getting the same error? Does `netstat -tulpn | grep :80` still show anything?

**Comment by thijssmudde** [comment]
After redeploying an older version of the app while making sure nothing was running on port 80 it finally worked. Thanks @zodern for the help

**Comment by x5engine** [comment]
for anyone having this issue
just do 
`docker ps`

then get the id of the container that is running on port 80
`sudo docker stop ID`

and it will fix it

**Comment by brylie** [comment]
In my case, I needed to do:

```
mup stop
```

**Comment by vfoley** [comment]
I have this same problem but, it only goes away with a restart of docker on Windows 10. I even changed the ports of my container to try to make a difference. This had no effect. As soon as I restart the docker service everything works fine. Still now clue as to the reason.

**Comment by DarrenHaba** [comment]
@vfoley, I had the same problem on Windows 10. Restarting docker fixed it. Thanks for the advice, you gave me my sanity back...
