### ISSUE TITLE
Deploying Meteor app v1.5

### ISSUE THREAD

**Issue by dominicarrojado** [zodern/meteor-up#632]
Hi, I'm getting an error deploying the app with Meteor version 1.5. This is the screenshot of the error:

![image](https://cloud.githubusercontent.com/assets/6789191/26766830/6155c062-49cb-11e7-98c8-7cb52708e251.png)

**Comment by zodern** [comment]
It doesn't show enough of the logs to see what the error was. Please run `mup logs --tail 200`.

**Comment by dominicarrojado** [comment]
@zodern ![image](https://cloud.githubusercontent.com/assets/6789191/26766978/8da4d0e8-49cd-11e7-9f23-36def871b898.png)

**Comment by crstn210** [comment]
@mroftalp  do you solved this already?

**Comment by rootedsoftware** [comment]
I was able to get my working by deleting the node_modules folder and then doing an ```meteor npm install``` then doing ```mup deploy``` again.

**Comment by crstn210** [comment]
thanks @c316 
i've did that and now i got this: 
`x Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        e
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR!     npm owner ls meteor-dev-bundle
        npm ERR! There is likely additional logging output above.

        npm ERR! Please include the following file with any support request:
        npm ERR!     /bundle/bundle/programs/server/npm-debug.log

        > meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
        > node npm-rebuild.js


        > bcrypt@1.0.2 install /bundle/bundle/programs/server/npm/node_modules/bcrypt
        > node-pre-gyp install --fallback-to-build

        node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz
        node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.8.0 (node-v46 ABI) (falling back to source compile with node-gyp)
        make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
          CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o

        => Redeploying previous version of the app

        -----------------------------------STDOUT-----------------------------------
        localhost:80

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------`

**Comment by dominicarrojado** [comment]
@crstn210 I did the same as what @c316 did. It worked for me.

**Comment by crstn210** [comment]
@mroftalp  i´ve tried several times, i've even delete the entire folder and cloned the clean repository from github again, and this is the error I get `x Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------
         There is likely additional logging output above.

        npm ERR! Please include the following file with any support request:
        npm ERR!     /bundle/bundle/programs/server/npm-debug.log

        > meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
        > node npm-rebuild.js


        > bcrypt@1.0.2 install /bundle/bundle/programs/server/npm/node_modules/bcrypt
        > node-pre-gyp install --fallback-to-build

        node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz
        node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.8.0 (node-v46 ABI) (falling back to source compile with node-gyp)
        make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
          CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
          CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
          CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o

        => Redeploying previous version of the app

        -----------------------------------STDOUT-----------------------------------
        localhost:80

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------`

**Comment by rootedsoftware** [comment]
Another thing you might try is to make a small change to both your code and to the mup.js file. I've noticed that when I do this Mup then rebuilds something. So try this and when you make the change to mup.js do a ```mup reconfig``` and then a ```mup deploy```. If this doesn't work then try doing a ```mup setup``` then a ```mup deploy```

**Comment by michaltakac** [comment]
Resolved it by doing this (Ubuntu 16.04 on DigitalOcean, 512 MB / 1 CPU, 20 GB SSD):

1. ssh into server (`root@YOUR_SERVER_IP`)
2. `docker ps` to show docker images, find the `abernix/meteord:base` one (running your app), write down CONTAINER ID
3. `docker exec -it YOUR-CONTAINER-ID bash`
4. `npm install node-gyp -g`, wait until it install finishes
5. exit docker bash, exit server
6. `mup setup`
7. `mup deploy`

Verifying Deployment: SUCCESS 😎

**Comment by rclai** [comment]
Is that something that the `abernix/meteord:base` image needs to update for 1.5+ support? @abernix

**Comment by dominicarrojado** [comment]
Fixed by reuploading npm modules

**Comment by rclai** [comment]
Is that really a fix or a work-around?

**Comment by dominicarrojado** [comment]
@rclai I believe it's a fix.

**Comment by crstn210** [comment]
i've fixed it uninstalling bcrypt

**Comment by iamrommel** [comment]
I fixed it by using installing the packages using "meteor npm i" and not directly using "npm i". The current npm version i have is 5.1.+ where as the bundled NPM from meteor is on 4.+ only, I used the one that came from the meteor bundle and my deployment just came fine.
