### ISSUE TITLE
Verifying Deployment: FAILED meteor 1.5

### ISSUE THREAD

**Issue by crstn210** [zodern/meteor-up#633]
the error: 
` Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        n/node" "/usr/bin/npm" "install" "--unsafe-perm"
        npm ERR! node v4.8.0
        npm ERR! npm  v3.10.10
        npm ERR! code ELIFECYCLE
        npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
        npm ERR! Exit status 254
        npm ERR!
        npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
        npm ERR! Make sure you have the latest version of node.js and npm installed.
        npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node npm-rebuild.js
        npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs meteor-dev-bundle
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR!     npm owner ls meteor-dev-bundle
        npm ERR! There is likely additional logging output above.

        npm ERR! Please include the following file with any support request:
        npm ERR!     /bundle/bundle/programs/server/npm-debug.log
        -----------------------------------STDOUT-----------------------------------
        localhost:80

        To see more logs type 'mup logs --tail=50'
`
mup.js :   

`module.exports = {
  servers: {
    one: {
      host: 'xxxxxxxxxxxxxxxxxxxxxxxx',
      username: 'xxxxxxxxxxxxxxxxxxx',
      // pem: "~/.ssh/id_rsa",
      password: 'xxxxxxxxxxxxxxxxxxx'
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'BrikCMS',
    path: '.',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
      executable: 'meteor --settings settings.json'
    },
    env: {
      ROOT_URL: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      MONGO_URL: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    },

    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 60,

    dockerImage: 'abernix/meteord:base'
  }

};
`

its a fresh digital ocean droplet

**Comment by rootedsoftware** [comment]
I was able to get my working by deleting the node_modules folder and then doing an ```meteor npm install``` then doing ```mup deploy``` again.

**Comment by michaltakac** [comment]
Tried what @c316 is suggesting, also tried `mup setup` few times after it, tried changing stuff in app and doing `mup reconfig`, still the error persists.

**Comment by michaltakac** [comment]
Resolved it by doing this (Ubuntu 16.04 on DigitalOcean, 512 MB / 1 CPU, 20 GB SSD):

1. ssh into server (`root@YOUR_SERVER_IP`)
2. `docker ps` to show docker images, find the `abernix/meteord:base` one (running your app), write down CONTAINER ID
3. `docker exec -it YOUR-CONTAINER-ID bash`
4. `npm install node-gyp -g`
5. exit docker bash, exit server
6. `mup setup`
7. `mup deploy`

Verifying Deployment: SUCCESS 😎
