### ISSUE TITLE
Do not restart docker service on setup

### ISSUE THREAD

**Issue by tschneid** [zodern/meteor-up#634]
Since [one of the last commits](https://github.com/zodern/meteor-up/commit/861e7c9ebf9ae1c9f991512176529893de0c31c4), during each `mup setup` [this code](https://github.com/zodern/meteor-up/blob/861e7c9ebf9ae1c9f991512176529893de0c31c4/src/modules/docker/assets/docker-setup.sh#L27) is run:
```bash
sudo service docker start || sudo service docker restart
```
This restarts the docker service (if already running) and thereby stops ALL running containers on this server. This is imho much too intrusive (and caused me quite some work).

Why did you move this line out of the `if [ ! "$hasDocker" ]` check?
My quick solution is to not run `mup setup` at all.

**Comment by thijssmudde** [comment]
Seems like this causes many issues on my server, because the app is not online after pushing a new update.
