### ISSUE TITLE
clientUploadLimit documented wrong～

### ISSUE THREAD

**Issue by alexgzhou** [zodern/meteor-up#638]
proxy.shared.clientUploadLimit will result unknown properties, should be proxy.clientUploadLimit and be number but not string like '10M'

**Comment by zodern** [comment]
This is fixed in Mup 1.3.

**Comment by mkorban** [comment]
I have change the proxy.shared.clientUploadLimit the corresponding value appears in the file /opt/mup-nginx-proxy/config/nginx-default.conf, but no effect it does not. When the output of the command "nginx -T" shows that the specified file is not read by nginx. As a result, it is impossible to download large files and queries
