### ISSUE TITLE
doc update: minimum node version 6?

### ISSUE THREAD

**Issue by mattsouth** [zodern/meteor-up#641]
The minimum node version appears to have crept up to 6.  With a clean ubuntu 16.04 I can run mup (1.2.10) on node 6 but not node 4 where any mup command just hangs.  If this is the case (and it would be understandable if it were) the getting started guide needs updating.

**Comment by zodern** [comment]
I will try to fix running on Node 4.

**Comment by zodern** [comment]
@mattsouth It worked for me on Node 4. If you switch back to Node 4, what does `DEBUG=mup* mup setup --verbose` show you? Also, could you please share your config, and the exact version of Node 4 you used?

**Comment by mattsouth** [comment]
oh man.  it works for me today for node 4.  Yesterday I replicated the issue in clean VMs before posting the issue but I guess there may have been a confounding issue - perhaps for some period the response from the target server was especially slow. Thanks for the debug tip which will surely come in handy (and I see is in the README - the shame).  Thanks for looking at this.  I feel bad for wasting your time. Please accept my sincerest apologies.
