### ISSUE TITLE
MongoDB repeated queries when computer sleeps

### ISSUE THREAD

**Issue by Colkadome** [zodern/meteor-up#643]
I have deployed a Meteor + React app using mup to Ubuntu Amazon ec2, and I am experiencing some unusual behaviour.

A certain iMac computer in the room has a Chrome webpage open on my Meteor app that displays a list of Jobs, and each Job has a list of Roles which is fetched reactively using the publishComposite library (https://github.com/englue/meteor-publish-composite), and createContainer (https://guide.meteor.com/react.html#using-createContainer).

Occasionally, the server slows down to a crawl, and it seems to be timed with the computer entering sleep mode. The server is on Amazon ec2 and is no way linked to this particular computer. The computer just has the Jobs list open. Checking the mongoDB docker logs shows a huge number of commands per second, all trying to fetch the same Roles associated with the Jobs in this list, over and over again. When the computer is activated again (logged in with password), the server returns to normal and the queries stop repeating.

Using 'mup restart' does not fix the issue. I fixed this issue last by logging into the computer and closing the browser, then running 'mup restart'. The issue happened 2 weeks ago too, and seemed to fix itself when the computer was logged into. There are many other computers using the app and the same Jobs list, but it only happens roughly once a week, and happens when this computer is asleep.

Sorry if this is the wrong place to post this particular issue, but I can't trace the cause of it and was wondering if anyone has any insight into this.

**Comment by zodern** [comment]
I don't think this is a problem with Mup. It would be better to ask in the Meteor forums.
