### ISSUE TITLE
Meteor hangs on server startup

### ISSUE THREAD

**Issue by lmachens** [zodern/meteor-up#644]
I am not sure why it is not working anymore. mup deploy was working fine until today:

```
2017-06-13T13:34:15.117215852Z => Starting meteor app on port:80
2017-06-13T13:34:15.267713274Z | (#1) Profiling: Server startup
```
It hangs. 
mup tells me that the deployment was successful, but the http server returns a 502 Bad Gateway.

I have Meteor 1.5 and mup 1.2.10 installed.

**Comment by csellis** [comment]
This may help identify the problem

1. SSH into your server
2.  type: docker ps

Mine says mongodb is constantly restarting.

**Comment by lmachens** [comment]
Thx, but I have an extern mongo server. 
It looks like it has something to do with Windows. 
It works fine if I run mup on Ubuntu.
