### ISSUE TITLE
Can't connect with mup even though I can ssh direct to host

### ISSUE THREAD

**Issue by noahsw** [zodern/meteor-up#646]
Trying to connect with mup:
```
─± DEBUG=mup* mup logs --tail=100 --verbose
  mup:updates checking for updates +0ms
  mup:module:default exec => mup logs +303ms
  mup:module:meteor exec => mup meteor logs +1ms
  mup:utils getDockerLogs command: sudo docker logs --tail=100 --verbose myapp 2>&1 +18ms
Error All configured authentication methods failed
```

But I can successfully connect via ssh:
```
╰─± ssh root@myapp.com
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64)
```

mup.js:
```
module.exports = {
  servers: {
    one: {
      host: "myapp.com",
      username: "root",
    },
  },

...
```

The server has been up and running for months. I can successfully deploy from CI. Not sure why I can't connect from my local machine though.

**Comment by avishaan** [comment]
I just started to experience this today and I've done multiple deployments over the past months, @noahsw did you figure out what the problem was?

**Comment by avishaan** [comment]
adding the following to my .ssh/config file fixed it for me, I think....
```
Host *
  UseKeychain yes
  AddKeysToAgent yes
  IdentityFile=~/.ssh/id_rsa
  IdentityFile=~/.ssh/id_rsa.pem
```

I'm on macOS Sierra btw

**Comment by noahsw** [comment]
That worked! Thanks @codeHatcher !
