### ISSUE TITLE
Docker : ECONNREFUSED

### ISSUE THREAD

**Issue by AurelienC** [zodern/meteor-up#647]
Hello,

On a clean install of Ubuntu Server V16, I have an error when I try to perform `mup setup`.

I get this error : 
```
Setup Docker
Error connect ECONNREFUSED 127.0.0.1:22
```

The host of my `servers.one.host` is *localhost*. I have ony install `node `and `mup`. No docker, no Meteor, no MongoDB.

I don't know how I can resolve this error ?

Any idea ? Thanks :-)

Aurélien

**Comment by zodern** [comment]
It might be from running mup on the same server you are setting up. Does it work if you run `mup setup` on a computer other than the one you will deploy the app to?

**Comment by AurelienC** [comment]
No much time, really sorry.

May be it's just an network configuration error. :-)
