### ISSUE TITLE
Need help with restoring data on server from backup

### ISSUE THREAD

**Issue by thijssmudde** [zodern/meteor-up#650]
My backup data is on /root/dump/appname

I tried this:
`docker run --rm \
  --link mongodb:mongo  \
  -v /root:/dump  mongo  bash \
  -c 'mongorestore --host $MONGO_PORT_27017_TCP_ADDR /dump/appname'
`

Error:

Failed: mongorestore target '/dump/appname' invalid: stat /dump/appname: no such file or directory

**Comment by thijssmudde** [comment]
Figured it out

`docker run --rm  --link mongodb:mongo    -v /root:/appname  mongo  bash   -c 'mongorestore --host $MONGO_PORT_27017_TCP_ADDR appname/dump/appname -d <APPNAME>'`

**Comment by thearabbit** [comment]
I backup and upload it to slack.
```
docker exec mongodb mongodump --db DATABASE_NAME --out /backup/PrefixName_$(date +%Y-%m-%d)
........
```
![image](https://user-images.githubusercontent.com/4495160/34384147-d2b4d2fc-eb4c-11e7-9419-b3c74dc4b7c2.png)

But I have problem with restore
1- upload backup file to server
```
$ scp -r ./backup root@IP:/root/backup
```
2- Restore with dbName
```
docker run --rm --link mongodb:mongo -v /root:/backup mongo bash -c ‘mongorestore --drop --db NEWDBNAME --host $MONGO_PORT_27017_TCP_ADDR /backup’
```
But don't work

**Comment by thijssmudde** [comment]
I just moved to a new droplet due to Digitalocean's new droplet sizes. Which means I can do with the 5$ droplet instead of the 10$.

However I want to restore my backed up data on the new droplet, but it doesn't work using version 1.3.7. Previously I used 1.2.2 if I can recall correctly.

So I now have a brand new server which I did mup setup and mup deploy on. Now trying to restore the backup it doesnt work.

```
docker run --rm  --link mongodb:mongo -v /root:/myroutes mongo bash -c 'mongorestore --host $MONGO_PORT_27017_TCP_ADDR myroutes -d myroutes'
```

mup.js
```
module.exports = {
  servers: {
    one: {
      host: '<ip>',
      username: '<username>',
      password: '<password>'
    }
  },

  meteor: {
    name: 'myroutes',
    path: '../myroutes',
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'https://myroutes.io',
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    ssl: {
      crt: './myroutes_io.crt', // this is a bundle of certificates
      key: './private.key', // this is the private key of the certificate
      port: 443 // 443 is the default value and it's the standard HTTPS port
    },
    dockerImage: 'abernix/meteord:node-8.4.0-base',
    deployCheckWaitTime: 60,
    enableUploadProgressBar: true
  },

  mongo: {
    port: 27017,
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};
```

**Comment by thijssmudde** [comment]
Finally fixed:

docker run --rm --link mongodb:mongo -v /root/myroutes:/myroutes mongo bash -c 'mongorestore --host $MONGO_PORT_27017_TCP_ADDR ./myroutes -d myroutes'
