### ISSUE TITLE
Meteor Start: FAILED, docker Error response from daemon: no such id

### ISSUE THREAD

**Issue by NathanJeanDevs** [zodern/meteor-up#652]
When I mup setup all is well, 

when I mup deploy --settings settings.json, I get this error.

I think its an issue with docker. I'm using abernix/meteord:base

Meteor v 1.4.2.3

`Started TaskList: Pushing Meteor App
[34.211.115.208] - Pushing Meteor App Bundle to The Server
[34.211.115.208] - Pushing Meteor App Bundle to The Server: SUCCESS

Started TaskList: Configuring App
[34.211.115.208] - Pushing the Startup Script
[34.211.115.208] - Pushing the Startup Script: SUCCESS
[34.211.115.208] - Sending Environment Variables
[34.211.115.208] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[34.211.115.208] - Start Meteor
[34.211.115.208] x Start Meteor: FAILED

	-----------------------------------STDERR-----------------------------------
	ainers are normal.
	Error response from daemon: no such id: myApp
	time="2017-06-26T19:09:23Z" level=fatal msg="Error: failed to remove one or more containers"
	docker: 'network' is not a docker command. See 'docker --help'.
	Error response from daemon: no such id: myApp-frontend
	time="2017-06-26T19:09:23Z" level=fatal msg="Error: failed to remove one or more containers"
	docker: 'network' is not a docker command. See 'docker --help'.
	Error response from daemon: no such id: myAPp-nginx-letsencrypt
	time="2017-06-26T19:09:23Z" level=fatal msg="Error: failed to remove one or more containers"
	docker: 'network' is not a docker command. See 'docker --help'.
	Error response from daemon: no such id: myApp-nginx-proxy
	time="2017-06-26T19:09:23Z" level=fatal msg="Error: failed to remove one or more containers"
	docker: 'network' is not a docker command. See 'docker --help'.
	Finished removing docker containers
	flag provided but not defined: --log-opt
	See 'docker run --help'.
	-----------------------------------STDOUT-----------------------------------
	base: Pulling from abernix/meteord
	0f48656fed63: Already exists
	8d6cce8d12a6: Already exists
	2ef269bc98bc: Already exists
	e580001f6913: Already exists
	82b7f29cf12b: Already exists
	993b7f451ec3: Already exists
	71288a5ec90d: Already exists
	ff72bcaefaad: Already exists
	d270415328ce: Already exists
	0f22e3d8ee7c: Already exists
	eb91ee4d1ad7: Already exists
	b10d25b242ad: Already exists
	2ebaf3e37dcd: Already exists
	c61ec02be23b: Already exists
	Digest: sha256:7f84ed42dd555fbfbf91cd7f2c6ec580ef290461f48c1254cc6088f29cbdffa7
	Status: Image is up to date for abernix/meteord:base
	Pulled abernix/meteord:base`

**Comment by zodern** [comment]
@GenetixMedia it looks like you are using an old version of Docker. You can follow the docker install instructions to update https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/.

**Comment by rgstephens** [comment]
I ran into this problem. Was running Docker 1.9.1, upgraded to the latest version which resolved the problem. Thanks @zodern

**Comment by NathanJeanDevs** [comment]
@zodern you nailed it! Thanks!
