### ISSUE TITLE
Error read ECONNRESET with `mup setup`!

### ISSUE THREAD

**Issue by thearabbit** [zodern/meteor-up#654]
I get error with `mup setup`
```js
Started TaskList: Setup Docker
[172.104.45.......] - Setup Docker
Error read ECONNRESET
```
Please help me

**Comment by fahadakhan96** [comment]
I get this error, too, but after `START MONGO: SUCCESS`. Pls help.

**Comment by zodern** [comment]
I made a couple adjustments to Mup 1.4 that might help reduce this error. You can try the beta by following the instructions in #870 .
