### ISSUE TITLE
deploy failing when server is out of disk space

### ISSUE THREAD

**Issue by chrisbutler** [zodern/meteor-up#655]
i ran into some strangeness and i'm not entirely sure which is the symptom and which is the cause... but in the process i realized that it seems like a deploy can fail because there's no space left on the disk, and mup doesn't recognize or report this condition

my app suddenly became unreachable so i tried mup restart, which didn't fix the issue. then i tried to deploy and reconfig two or three different times, hoping that would fix things... and i ended up a full disk on the server

i seemed to have multiple nested ```last/``` directories inside the ```current/``` folder, and that ate up all of the free disk space (i think because the deploy failed, it then tried to 'roll back' the deploy)

just wanted to point these things out

**Comment by zodern** [comment]
https://github.com/zodern/mup-disk is able to fix nested `last` directories. Depending on the docker image, mup usually uses a different method to rollback that doesn't have this problem.
