### ISSUE TITLE
www leads to HTTP connection

### ISSUE THREAD

**Issue by metavaults** [zodern/meteor-up#656]
I successfully uploaded my Meteor 1.4 project to Linode servers using mup. However, if I access my website over kadabratravel.com or www.kadabratravel.com, my connection is still insecure (HTTP). If I explicitly type https://www.kadabratravel.com, I'm connected over HTTPS.
How can I forward all connections to the secure HTTPS protocol? 

My mup.js file
```
module.exports = {
  servers: {
    one: {
      host: 'XXX.XX.XXX.XXX',
      username: 'XXXXX',
      password: 'XXXXXXX',
    },
  },

  meteor: {
    name: 'myapp',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      ROOT_URL: 'https://kadabratravel.com',
      MONGO_URL: 'mongodb://localhost/meteor',
    },

    ssl: { // (optional)
      autogenerate: {
        email: 'email@gmail.com',
        domains: 'kadabratravel.com,www.kadabratravel.com',
      },
    },

    docker: {
      image: 'abernix/meteord:base',
    },

    deployCheckWaitTime: 60,
    enableUploadProgressBar: true,
  },

  mongo: {
    port: 27017,
    version: '3.4.1',
    servers: {
      one: {},
    },
  },
};
```

**Comment by metavaults** [comment]
I tried installing force-ssl package and deploy my app again, but in this case, I get a Bad Gateway error, when trying to access my app.

**Comment by lmachens** [comment]
Same problem here. Sometimes http is not redirected to https.
I think it has something to do with the new mup version and proxy changes.

**Comment by SharadKumar** [comment]
In issue #594 it has been advised to use `meteorblackbelt:force-ssl`. I am facing similar problem with force-ssl and trying this new package.

**Comment by SharadKumar** [comment]
There seems to be caching issue for some users. For example, I recently started getting 502 Bad Gateway errors on deploy... and if I try www site works, then I go without www site works!

**Comment by avishaan** [comment]
Ahhh, I'm going through something similar right now. Looking for a good way to route http to https without adding another nginx instance in front

**Comment by avishaan** [comment]
@SharadKumar suggestion of meteorblackbelt:force-ssl worked for me

**Comment by zodern** [comment]
Mup 1.3 will be able to redirect http to https.
