### ISSUE TITLE
curl: (7) Failed connect to localhost:80; Connection refused

### ISSUE THREAD

**Issue by Joeblockmark** [zodern/meteor-up#658]
I get this error after running `mup deploy --verbose`

     x Verifying Deployment: FAILED
	
	-----------------------------------STDERR-----------------------------------
	0 /bundle/bundle/programs/server/npm/node_modules/meteor/ethereum_web3/node_modules/web3
	bignumber.js@2.0.7 /bundle/bundle/programs/server/npm/node_modules/meteor/ethereum_web3/node_modules/web3/node_modules/bignumber.js
	utf8@2.1.2 /bundle/bundle/programs/server/npm/node_modules/meteor/ethereum_web3/node_modules/utf8
	xmlhttprequest@1.7.0 /bundle/bundle/programs/server/npm/node_modules/meteor/ethereum_web3/node_modules/xmlhttprequest
	underscore@1.8.3 /bundle/bundle/programs/server/npm/node_modules/meteor/ethereum_web3/node_modules/underscore
	vinyl-source-stream@1.1.0 /bundle/bundle/programs/server/npm/node_modules/meteor/ethereum_web3/node_modules/vinyl-source-stream
	xhr2@0.1.4 /bundle/bundle/programs/server/npm/node_modules/meteor/ethereum_web3/node_modules/xhr2
	
	> bson@0.2.21 install /bundle/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/bson
	> (node-gyp rebuild 2> builderror.log) || (exit 0)

The error in the title was thrown multiple times during the verifying deployment stage

**Comment by Joeblockmark** [comment]
I tried deploying to port 3000 but got the same error: `curl: (7) Failed connect to localhost:3000; Connection refused`

**Comment by zodern** [comment]
Try increasing `meteor.deployCheckWaitTime`. https://github.com/zodern/meteor-up#verifying-deployment-failed

**Comment by Joeblockmark** [comment]
@zodern what is the maximum sensible time it can be set to? I have tried up to 1400s

**Comment by zodern** [comment]
It usually doesn't need to be any higher than 120 - 300. Does your app use many native modules?

**Comment by Joeblockmark** [comment]
@zodern im not sure what you mean by native modules

**Comment by Joeblockmark** [comment]
@zodern how do i differentiate them from other modules

**Comment by zodern** [comment]
There's not really an easy way to differentiate them.

Mup doesn't show enough of the logs when verifying deployment fails (that will be fixed in the next version). If it didn't work with the `deployCheckWaitTime` set to 1400, the app probably crashed at least once.

To see the full logs, you can run `mup deploy` in one terminal window. Then, when it starts the `Verifying Deployment` task, run `mup logs --follow` in a second window.

**Comment by Joeblockmark** [comment]
@zodern I tried deploying an empty meteor app and got the same error so I don't think it is module related

**Comment by Joeblockmark** [comment]
@zodern I updated a few packages and its working now
