### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by zodern** [zodern/meteor-up#659]
Plugins are npm modules that can add functionality to Meteor Up or modify existing features. 

Examples are:
- Setup a redis database
- Deploy nodejs apps
- View disk space
- Setup load balancing
- Backup/restore MongoDB

All of the commands and task lists have been moved into a set of built-in plugins.

**Plugin Config**
The goal for the first implementation is to support all of the above use cases with a very general config. Later, we might add additional options to simplify creating specific types of plugins, or to interact more with other plugins.

Each plugin's main file should export an object with:
```js
module.exports = {
  description: 'plugin/command description',
  commands: {
    subCommandName: {
      description: 'sub-command description',
      builder(yargs) {
        // yargs command builder. Can be used to add options, among many other things.
        return yargs.option('follow', { description: 'Follow log output' });
      },
      handler(api) {
        // Run any task lists, commands, etc. here.
      }
    }
  },
  validate: {
    'rootProperty'(config, validateUtils) {
    }
  },
  hooks: {
    'post.default.setup'(api) {
      // same api as for command handlers
    }
  }
};
```

To use a plugin, the config would look like:
```js
{
  plugins: ['plugin-name', 'mup-node-deploy', 'mup-redis']
} 
```

To better support deploying non-meteor apps, the `meteor` object in the config has been renamed to `app`. There is also a new `app.type` property that defaults to `'meteor'`. mup will continue to support the `meteor` object until at least mup 2.0.

- [x] Support plugin commands
- [x] Validate root properties
- [x] Call validate methods
- [x] Support plugin hooks
- [x] Copy `meteor` object to `app`
- [x] Add documentation
- [x] Support loading plugins from
    - [x] configPath/.node_modules
    - [x] appPath/.node_modules
    - [x] globally installed
    - [x] absolute path, or path relative to config

**Comment by FrancisBou** [comment]
This is a highly anticipated feature for me so i'd like to thank @zodern for his great contribution.
I'm not used to it so pardon me is this isn't the correct place to ask but how would I go about contributing to this project, is there a roadmap somewhere, are you looking for beta testers?

**Comment by zodern** [comment]
Any contributions are appreciated. I am using [projects](https://github.com/zodern/meteor-up/projects) for a short-term road map.
