### ISSUE TITLE
Trying to redirect http to https

### ISSUE THREAD

**Issue by avishaan** [zodern/meteor-up#663]
I wanted to open a new issue other than #521 since my specific setup might be different and unable to be answered in the same manner

I have an aws application load balancer setup which works fine but I need mup to route http to https, I tried using force-ssl package but it doesn't seem to work. I wonder if it's because it's a non-standard port that I am using (because I have multiple apps running sharing a database)

I think there is a nginx rewrite or redirect rule that could be added with an option to the mup.js file `redirectSSL: true` so that during creation of the nginx docker instance, it would automatically start rerouting.

My mup.js is below

```
module.exports = {
  servers: {
    one: {
      host: "35.162.xxx.xxx",
      username: 'ubuntu',
      // pem:
      // password:
      // or leave blank for authenticate from ssh-agent
    },
  },
  meteor: {
    name: 'dashboard',
    path: '/Users/avi/Code/dashboard',
    ssl: {
      crt: './server.crt',
      key: './server.key',
      port: 8443,
    },
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
      debug: true,
    },
    deployCheckWaitTime: 220,
    docker: {
      image: 'abernix/meteord:base',
      args: [
        '--link=mongodb:mongodb'
      ],
    },
    env: {
      ROOT_URL: 'http://35.162.xxx.xxx',
      MONGO_URL: 'mongodb://mongodb:27017/staging-app-bnog',
      PORT: 8000,
      DEPLOY_TYPE: 'staging'
    },
  },
};
```

**Comment by avishaan** [comment]
For others who stumble here, my problem was I needed to:
1. use https://github.com/meteorblackbelt/meteor-force-ssl instead of the MDG one (I don't know why)
2. my `ROOT_URL` was incorrect and needed to be my https domain, not the ip address of the server since it seems force-ssl package uses that to redirect

@zodern what would it take to add a config to mup.js that would add redirect directives into nginx? If you give me some specific tasks to work on or would be willing to pair abit, I have some time I could direct to this since I have gotten so much use out of this repo

**Comment by Farkal** [comment]
After hours trying to configure nginx proxy I find that there i a simple option in [start.sh](https://github.com/zodern/meteor-up/blob/master/src/modules/meteor/assets/templates/start.sh) (on your server you can find it at _/opt/YOUR_APP_NAME/config/start.sh_ )
`HTTPS_METHOD=noredirect` so just change it to `HTTPS_METHOD=redirect` and http will be redirected to https
It should be possible to add a simple option to allow the user to define what method he want on the _mup.js_ config file.

**Comment by layik** [comment]
Thanks @Farkal worked for me and sounds straightforward.

**Comment by FBosler** [comment]
@Farkal I did change the file, what do I have to do for it to take effect? Cheers
Update: `meteor mup restart` does the trick

**Comment by avishaan** [comment]
Oh wow, good teamwork here
I'd still love to make it into a mupjs option if possible. Point me in the right direction and I'd love to contribute

**Comment by derwaldgeist** [comment]
Hi, I would also love to see mup extended that it allows to force SSL automatically. Since Meteor 1.5, the force-ssl does not work with mobile apps on Android anymore, since it forces them to use SSL for their local server. Hence, I had to take out `force-ssl` out of my Meteor app. So it would be great if redirection could happen on nginx instead.

**Comment by zodern** [comment]
Mup 1.3 will be able to redirect http to https.

**Comment by Farkal** [comment]
@zodern if you need you can check my commit adding the parameter to the config and using it in nginx template here -> https://github.com/Farkal/meteor-up/commit/40e26512a20398b4d0ee326ac9ce598c8d12072e

**Comment by markreid** [comment]
So this didn't make it into 1.3, @Farkal's PR seems to be a reasonable solution, any chance this is on the radar for 1.4?

**Comment by zodern** [comment]
@markreid it is available: http://meteor-up.com/docs.html#redirect-http-to-https

**Comment by markreid** [comment]
apologies @zodern was looking in the wrong part of the docs. thanks for your help :)

**Comment by derwaldgeist** [comment]
Awesome, that helps me a lot, thanks!
