### ISSUE TITLE
Mup will not update to version 1.2.11

### ISSUE THREAD

**Issue by pdjenera** [zodern/meteor-up#664]
Every time I try to update MUP I see

update 1.0.3 => 1.2.11

I've uninstalled and reinstalled numerous times and can't figure out why this is happening

**Comment by abhirakshit** [comment]
+1

**Comment by zodern** [comment]
Please run `npm ls -g mup` and `npm ls mup` and paste the output here.

**Comment by abhirakshit** [comment]
abhi: ~/Projects/Meteor/vibes-auth $ npm ls -g mup
/usr/local/lib
└── mup@1.0.3 

abhi: ~/Projects/Meteor/vibes-auth $ npm ls mup
Vibes-Auth@ /Users/abhi/Projects/Meteor/vibes-auth
└── (empty)

**Comment by zodern** [comment]
Try running `npm i -g mup@1.2.11`

**Comment by Sphinxxxx** [comment]
Same issue here, mup `1.2.5` can't be updated or uninstalled.
