### ISSUE TITLE
High severity vulnerability for node.js please update

### ISSUE THREAD

**Issue by x5engine** [zodern/meteor-up#665]
This is a really High severity vulnerability for node.js please update:

Updates are now available for all active Node.js release lines as well as the 7.x line. These include the fix for the high severity vulnerability identified in the initial announcement, one additional lower priority Node.js vulnerability in the 4.x release line, as well as some lower priority fixes for Node.js dependencies across the current release lines.

https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/

may be we should consider using newer versions??

Thanks

**Comment by zodern** [comment]
`abernix/meteord` is using Node 4.8.4, which has the fix.
