### ISSUE TITLE
Accessing docker and nginx.conf through remote terminal (https redirect problem)

### ISSUE THREAD

**Issue by BoyPersoon** [zodern/meteor-up#666]
I need to redirect all non-https connection to https and force-ssl gives Verifying Deployment: FAILED error. So I want to edit the server settings in the nginx files within the docker. Unfortunately I can't access the docker at all, as I can't find the directory. 

How can I access the files within the docker remotely and edit the nginx proxy settings? or how can I setup a redirect to https without using force-ssl?

**Comment by avishaan** [comment]
I had this problem also, this package worked for me https://github.com/meteorblackbelt/meteor-force-ssl make sure you have your URL set correct in the mup.js and you should be good to go

**Comment by FBosler** [comment]
@BoyPersoon there was another issue somewhere here, where a bit of a hack was described.

Log on your server go to `/opt/<YourAppName>/config` open `start.sh` and change `HTTPS_METHOD=noredirect` to `HTTPS_METHOD=redirect`

This did the trick for me.

**Comment by BoyPersoon** [comment]
Hey FBosler, Ufnortunately I can't find the https_method in start.sh file. as a matter of fact I can't find any http or https method in there.

**Comment by FBosler** [comment]
Very strange, you sure you set up nginx in your mup.js? Check https://github.com/zodern/meteor-up/issues/663

**Comment by BoyPersoon** [comment]
Actually I am not configuring nginx at all in the mup.js file. I suppose it does that automatically. Would you have any idea how to docker configures the files from the root directory. how can i find the main files of my app?

**Comment by zodern** [comment]
Mup 1.3 will be able to redirect http to https.
