### ISSUE TITLE
Docker container error after SSL setup in mup

### ISSUE THREAD

**Issue by metus08** [zodern/meteor-up#667]
After I recieved an error of: *3940 peer closed connection in SSL handshake while SSL handshaking to upstream. I figured it was because I setup nginx for ssl(letsencrypt) but didn't have it set in the mup.js folder.(The standard app ran on the IP but got a 502 error at the url). Now I get this error when I run mup setup(runs fine) then mup deploy(causes error). Client is the app name

 mup deploy
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[159.203.161.164] - Pushing Meteor App Bundle to The Server
[159.203.161.164] - Pushing Meteor App Bundle to The Server: SUCCESS

Started TaskList: Configuring App
[159.203.161.164] - Pushing the Startup Script
[159.203.161.164] - Pushing the Startup Script: SUCCESS
[159.203.161.164] - Sending Environment Variables
[159.203.161.164] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[159.203.161.164] - Start Meteor
[159.203.161.164] x Start Meteor: FAILED

        -----------------------------------STDERR-----------------------------------
        Removing docker containers. Errors about nonexistent endpoints and containers are normal.
        Error response from daemon: No such container: Client
        Error response from daemon: endpoint Client not found
        Error response from daemon: No such container: Client-frontend
        Error response from daemon: endpoint Client-frontend not found
        Error response from daemon: No such container: Client-nginx-letsencrypt
        Error response from daemon: endpoint Client-nginx-letsencrypt not found
        Error response from daemon: No such container: Client-nginx-proxy
        Error response from daemon: endpoint Client-nginx-proxy not found
        Finished removing docker containers
        docker: Error response from daemon: driver failed programming external connectivity on endpoint Client-frontend (570bf93af6efc15382e6c98b27bf16b3a44cd60672916345d3371126b81045f9): Bind for 0.0.0.0:8080 failed: port is already allocated.
        -----------------------------------STDOUT-----------------------------------
        base: Pulling from abernix/meteord
        Digest: sha256:9ed85313621010dd27a08054ae9225aa1f31798647fbcfdc9cc082181c6f9c97
        Status: Image is up to date for abernix/meteord:base
        Pulled abernix/meteord:base
        49670f85c487fd1ad96847f8c59acb6c712b37277611695100579653897ae310
        Ran abernix/meteord:base
        Using default tag: latest
        latest: Pulling from meteorhacks/mup-frontend-server
        03e1855d4f31: Already exists
        a3ed95caeb02: Already exists
        a3ed95caeb02: Already exists
        304ae4ee074b: Already exists
        963207107048: Already exists
        d9e2907e9fa4: Already exists
        4abf3e40edd9: Already exists
        3c907a5d5f8f: Already exists
        8db38a632903: Already exists
        Digest: sha256:573a1dd3e0e7829ad16e813d87e79948e9f2ef2cfa84d17c2c4c220b6e651b12
        Status: Image is up to date for meteorhacks/mup-frontend-server:latest
        5cb25faa874e5c4233abe46633a3975bc0745175906f1e22004b51b70dd3094b

here is the mup.js:

meteor: {
    // TODO: change app name and path
    name: 'Client',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      PORT: 8080,
      ROOT_URL: 'https://url.com/Client',
      MONGO_URL: 'mongodb://localhost/meteor',
    },
    

   ssl: {
      crt: '/etc/letsencrypt/live/url.com/fullchain.pem',
        key: '/etc/letsencrypt/live/url.com/privkey.pem',
        port: 8080
    },
    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/meteord:base',
        imageFrontendServer: 'meteorhacks/mup-frontend-server'
      // imagePort: 80, // (default: 80, some images EXPOSE different ports)
    },

    // This is the maximum time in seconds it will wait
    // for your app to start
    // Add 30 seconds if the server has 512mb of ram
    // And 30 more if you have binary npm dependencies.
    deployCheckWaitTime: 120,
      deployCheckPort: 8080,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    port: 27017,
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};

Any help would be appreciated

**Comment by avishaan** [comment]
I had this error recently, I don't suppose you are using the `force-ssl` package that is recommended by MDG?

**Comment by metus08** [comment]
I am not, should I be?

**Comment by metus08** [comment]
here is my nginx conf:

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name url.com www.url.com;
 
    root /var/www/html;
    index index.html index.htm;
   
    include snippets/ssl-url.com.conf;
    include snippets/ssl-params.conf;
 
    add_header Strict-Transport-Security "max-age=31536000;";
 
    location /js/ {
        root /var/www/html;
    }
 
    location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 365d;
    }
 
    if ($request_uri ~ /index\.html($|\?)) {
        rewrite ^(/.*)\.html(\?.*)?$ $1$2 permanent;
    }
 
    location / {
        try_files $uri.html $uri/ $uri =404;
    }
 
    location /Client {
        proxy_pass https://IP:8080;
        proxy_buffers 16 32k;
        proxy_buffer_size 64k;
        proxy_busy_buffers_size 128k;
        proxy_cache_bypass $http_pragma $http_authorization;
        proxy_connect_timeout 59s;
        proxy_hide_header X-Powered-By;
        proxy_http_version 1.1;
        proxy_ignore_headers Cache-Control Expires;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504 http_404;
        proxy_no_cache $http_pragma $http_authorization;
        proxy_pass_header Set-Cookie;
        proxy_read_timeout 600;
        proxy_redirect off;
        proxy_send_timeout 600;
        proxy_set_header Accept-Encoding '';
        proxy_set_header Cookie $http_cookie;
        proxy_set_header Host $host;
        proxy_set_header Referer $http_referer;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_temp_file_write_size 64k;
        proxy_set_header X-Original-Request $request_uri;
    }
}

**Comment by zodern** [comment]
@metus08 did you find a way to fix it?

> Bind for 0.0.0.0:8080 failed: port is already allocated.

A process is already using port 8080.
