### ISSUE TITLE
Base image for Docker discrepancy

### ISSUE THREAD

**Issue by amanagarwal2189** [zodern/meteor-up#670]
In the [Example config of Readme.md](https://github.com/zodern/meteor-up#example-config), it is mentioned that **image: 'abernix/meteord:base'** must be changed to **'kadirahq/meteord'** for Meteor 1.3 or older. However, on [abernix/meteord](https://github.com/abernix/meteord), the Readme says "Use kadirahq/meteord for meteor 1.4 and above."

Am I missing something?

**Comment by zodern** [comment]
The `abernix/meteord` image is a fork of ` meteorhacks/meteord`. ` meteorhacks/meteord` had that message and it hasn't been remove yet.
