### ISSUE TITLE
Server not starting after mup stop / mup start: "gzip: stdin: unexpected end of file"

### ISSUE THREAD

**Issue by derwaldgeist** [zodern/meteor-up#675]
I just stopped my server with `mup stop` and restarted it with `mup start`. Though mup reported a successful start, the server was not reachable. When I had a look at the logs, they were full of error messages like this, repeating 9x:

```
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

Repeating the `stop` / `start` sequence did not fix this.

I interrupted a `mup deploy` yesterday, since the upload got stuck at 1%. Maybe the problem is related to this?

**Comment by zodern** [comment]
You can try deploying again, which will upload a new bundle. This should be fixed in the next version of mup.

**Comment by derwaldgeist** [comment]
Ok, so this `mup` version does not allow interrupting an upload? I'm asking because this was never a problem with the old `mupx`. What happens if the network connection breaks down during an upload?

PS: A re-deploy worked.
