### ISSUE TITLE
Data loss on mup deploy

### ISSUE THREAD

**Issue by guncebektas** [zodern/meteor-up#677]
When i re-run mup deploy my app is restarting with the new build. Everything seems ok and i'm not getting any warning but some of my clients are losing recently stored data. Is anyone facing same issue? What could be the problem?

My Meteor version is 1.5.1

**Comment by htmllab** [comment]
I'm facing same issue.
Using CFS FileSystem path: "~/uploads"
All previous uploaded data lost on mup deploy.
Only mongodb data are there.

**Comment by guncebektas** [comment]
I was also using CFS and changed a lot of thing after this issue. 
@htmllab First of all we have to realise mup is not a magical tool. You should separate meteor and mongo (with replica sets) to different servers.

- I carried mongodb to mlab  (shared cluster) it's working with replica sets. The cost is 15$/month.
- Import/Export current data with Studio 3T (To export data you can use ssh tunnel)
- I'm using mup deploy to DO. The cost is 20$/month.
- I removed everything which is related with CFS. It has lots of disadvantages.
- I'm using slingshot and uploading files to s3.
- Activate cloudfront

Now everything seems great.

**Comment by htmllab** [comment]
@guncebektas thanks for your suggestion. 
I found the data in server /opt/appname/last/uploads directory that mup creates after re-deploy.
And solved my problem by copying it to current directory.
