### ISSUE TITLE
MUP - Setup Environment - Failed

### ISSUE THREAD

**Issue by JayDijkstra** [zodern/meteor-up#680]
Hey there,

First I had a problem with the `mup setup` function as it noticed me it could not setup Docker. Now I manually installed docker on my Ubuntu Server. After installing docker I get a Setup Docker - SUCCESS notification, but when It is trying to setup the Environment - I get an error that the Environment Setup did not succeed. 

While browsing the web I only see errors with the `mup deploy` command. But I did not even get to that part. 

I hope you can help me out!

Error I get:

```
my/location/to/meteor/.deploy$ mup setup --verbose

Started TaskList: Setup Docker
[my.private.ip.address] - Setup Docker
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
sudo: no tty present and no askpass program specified
[my.private.ip.address] - Setup Docker: SUCCESS

Started TaskList: Setup Meteor
[my.private.ip.address] - Setup Environment
sudo: no tty present and no askpass program specified
sudo: no tty present and no askpass program specified
sudo: no tty present and no askpass program specified
sudo: no tty present and no askpass program specified
[my.private.ip.address] x Setup Environment: FAILED
```

**Comment by zodern** [comment]
Follow the instructions in https://github.com/zodern/meteor-up/blob/ee017150591f53f7f85d0a4081a1b6018230e437/README.md#ssh-based-authentication-with-sudo
