### ISSUE TITLE
Is is possible to set Node options?

### ISSUE THREAD

**Issue by derwaldgeist** [zodern/meteor-up#681]
I would like to set Node options via TOOL_NODE_FLAGS or NODE_OPTIONS, since this was recommended to avoid server crashs caused by Node's garbage collector:

https://forums.meteor.com/t/how-to-find-memory-leaks-in-a-meteor-app/19008/21

This was impossible with the old `mupx`. Is it possible now, using the most recent `zodern:meteor-up` fork?

**Comment by zodern** [comment]
You can use the [abernix/spaceglue](https://github.com/abernix/spaceglue#meteor-up-website) docker image, which supports it.
