### ISSUE TITLE
502 Bad Gateway <= node-gyp error in production 

### ISSUE THREAD

**Issue by CrackedBeefcake** [zodern/meteor-up#683]
`mup deploy` finishes with `Verifying Deployment: SUCCESS` but server [says](https://peats.de) 502 Bad Gateway

### server
ubuntu 16.04

### docker 
dockerImage finnfrotscher/mup
meteor 1.5.1
node 4.6.2

## the env
```
apt-get remove -y gyp
apt-get install -y curl bzip2 build-essential g++ python git make gcc gcc-multilib node-gyp
```

`npm install node-pre-gyp node-gyp -g`

## the error
[log.txt](https://github.com/zodern/meteor-up/files/1219383/log.txt)

**Comment by helloncanella** [comment]
+1

**Comment by CrackedBeefcake** [comment]
issue could be reproduced on another server.
is it maybe @abernix 's docker image?

**Comment by CrackedBeefcake** [comment]
its was indeed the docker image. 
if somebody has similar problems [check](https://hub.docker.com/r/finnfrotscher/mup/) the `install_base.sh` and `install_node.sh` where extra packages are installed.

```
apt-get update -y
apt-get remove -y gyp
apt-get install -y curl bzip2 build-essential g++ python git make gcc gcc-multilib node-gyp
apt-get install -y pkg-config xserver-xorg-dev libxext-dev pkg-config libxi-dev libglu1-mesa-dev libglew-dev
npm install prebuild-install node-pre-gyp node-gyp -g
```

**Comment by FinnFrotscher** [comment]
```
set -e
apt-get update -y
apt-get remove -y gyp
apt-get install -y curl bzip2 build-essential g++ python git make gcc gcc-multilib node-gyp
apt-get install -y pkg-config xserver-xorg-dev libxext-dev pkg-config libxi-dev libglu1-mesa-dev libglew-dev
```
