### ISSUE TITLE
mup.js changing app name causes deployment to fail

### ISSUE THREAD

**Issue by mcsimenc** [zodern/meteor-up#687]
What function does the meteor app name serve? I changed it from 'app' to 'sequencedownloader' and deployment failed. I changed it back to app and it worked.

Here is the error

```
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[13.56.187.242] - Pushing Meteor App Bundle to The Server
[13.56.187.242] x Pushing Meteor App Bundle to The Server: FAILED
	No such file

```

**Comment by zodern** [comment]
The name is used for the folder it's files are stored in, the name of the docker image, and, if you are using the built-in mongodb, the name of the database.

Before changing the name, run `mup stop`. Then change the name and run `mup setup` and `mup deploy`. If you are using the built-in mongo database, it will create a new database for the app.

The docs on changing the app name need to be improved.

**Comment by mcsimenc** [comment]
So if I wanted to access a file in my meteor app directory from server side code using an absolute path it would start with appname? Like:

/appname/rest/of/path/to/file

**Comment by amanagarwal2189** [comment]
it will create the folder in your host on which docker will run at /opt/<name> and bundle your meteor application there. Inside your docker container, the bundle is copied at /bundle/bundle.
