### ISSUE TITLE
[Question] How to enable MongoDB Authentication?

### ISSUE THREAD

**Issue by fuatsengul** [zodern/meteor-up#690]
Hi, I have multiple apps using same DB instance and I also have to connect to the database from another server, just couldn't figured it out how to do it securely with default mongodb docker image used by mup. Any help will be appreciated! Thanks.

**Comment by amanagarwal2189** [comment]
I am not sure but I read [here](https://github.com/zodern/meteor-up#mongodb), mongodb instance by MUP can not be accessed by outside world.
