### ISSUE TITLE
docker: Error response from daemon: oci runtime error

### ISSUE THREAD

**Issue by aldwindelgado** [zodern/meteor-up#691]
I'm currently encounter the title's specific error

![error](https://user-images.githubusercontent.com/7079995/29316219-a8466970-81f9-11e7-8da4-2cf5edb28037.PNG)

I'm using 

docker-ce: 17.05.0
Linux kernel @ 4.10.0-32-generic
Ubuntu 16.04 OS

**Comment by giany** [comment]
@aldwindelgado  Did you solve this issue?

**Comment by aldwindelgado** [comment]
@giany Hi, we just moved to another server hosting for the meantime, I encountered that error from Google Cloud's virtual machine specifically. So we're not yet sure if it is related to just google cloud itself. Because everything is running smoothly within our digital ocean servers.

**Comment by giany** [comment]
I'm on DO also, Ubuntu 16, 4.4.0-97-generic.
Docker version 17.09.0-ce, build afdb6d4

When deploying with mup it fails with the same error you had..but if I run the docker container manually it starts ok..

**Comment by aldwindelgado** [comment]
@giany Maybe it is related to mup with regards to newer versions of docker. Did you try to revert to lower docker versions?

**Comment by zodern** [comment]
@giany what command did you use to start the container?

**Comment by giany** [comment]
@zodern, sorry for delay.  In the end I've passed multiple parameters to docker, e.g:

docker run -d --restart=always --volume=/opt/v2/tmp/:/bundle --publish=0.0.0.0:80:80 --hostname=v2 --env-file=/opt/v2/config/env.list --log-opt max-size=100m --log-opt max-file=10 --link=mongodb:mongodb --link=mongodb:mongodb --name=v2 mup_v2:latest

And the commit I pushed had these:
```

+        volumes: {
+            '/opt/volume_v2/tmp/': '/bundle'
+        },
 		docker: {
+            args: [
+                '--hostname=v2',
+                '--env-file=/opt/v2/config/env.list',
+                '--log-opt max-size=100m',
+                '--log-opt max-file=10',
+                '--link=mongodb:mongodb',
+                '--name=thoughtlounge_v2',
+                'mup-v2:latest'
+            ],
```

**Comment by hamxiaoz** [comment]
I have seen the error, and it might do so because of [host name too long](https://github.com/opencontainers/runc/issues/1437). I didn't dive deep into it but once **I renamed my app name to a shorter name**, the problem solved.

**Comment by zodern** [comment]
Docker has better error messages for this now, so I am going to close it. If anyone has an oci runtime error, please create a new issue.
