### ISSUE TITLE
default docker image causes node-fibers problem

### ISSUE THREAD

**Issue by leefurong** [zodern/meteor-up#698]
I am using Meteor 1.5.1, with mup 1.2.11

When I deploy using `kadirahq/meteord` which is the docker image suggested by comments in mup.js,
I failed:

> 
> [101.132.37.58]## There is an issue with `node-fibers` ##
> [101.132.37.58]`/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-11/fibers.node` is missing.
> [101.132.37.58]
> [101.132.37.58]Try running this to fix the issue: /opt/nodejs/bin/node /bundle/bundle/programs/server/node_modules/fibers/build

Then I use abernix/meteord:base as the image, the deployment succeed.

So Please change the comments in mup.js.

**Comment by zodern** [comment]
The comment will be fixed in 1.3
