### ISSUE TITLE
What pattern is better for dev/stage/production infrastructure?

### ISSUE THREAD

**Issue by mikeifomin** [zodern/meteor-up#70]
I mean it is useful to run command like: 

```
   mup deploy production
```

Or

```
   mup deploy stage
```

How to configure mup.js for this purpose?

**Comment by madushan1000** [comment]
you can't do this. Mup is not designed to handle different deployment stages like this. What you can do though is to create several mup.js files (maybe in `.production` and `.staging` directories) and configure them as necessary.

**Comment by mikeifomin** [comment]
@madushan1000 thank you! 

I thought a small hook can help me

``` javascript
   // mup.js 
   var args = process.argv.slice(2);

  // do some with `args` and write to `module.exports`
```

But this is absolutely dirty =(

**Comment by madushan1000** [comment]
This could be problematic since we don't directly run `mup.js` file.
