### ISSUE TITLE
[Question] SSL onredeployment

### ISSUE THREAD

**Issue by kenshinman** [zodern/meteor-up#700]
Hi, thanks for this package, 
I have been using it for a while now and i has been great. i  used it to generate LetsEncrypt SSL certificate and it worked.
What I would like to know is this: 
**When I want to redeploy (update) the app using `mup deploy`, do I comment out the SSL object or leave it. I am not sure if this will keep generating new SSL certificates update or not**

Thanks

**Comment by zodern** [comment]
It will only regenerate the certificates if they expire in less than a month. You need to leave the ssl object, otherwise it will stop working.
