### ISSUE TITLE
Permission denied error on 1.3

### ISSUE THREAD

**Issue by kulttuuri** [zodern/meteor-up#703]
Just started getting this error after upgrading to mup 1.3 and trying to deploy (setup went through without problems):

x Prepare Bundle: FAILED
	
	-----------------------------------STDERR-----------------------------------
	Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/images/create?fromImage=abernix%2Fmeteord&tag=base: dial unix /var/run/docker.sock: connect: permission denied
	-----------------------------------STDOUT-----------------------------------
	Warning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.29/info: dial unix /var/run/docker.sock: connect: permission denied). Using system default: https://index.docker.io/v1/
	----------------------------------------------------------------------------

Any ideas? Now trying to revert back to older version to prevent this from happening.

**Comment by zodern** [comment]
This will be fixed in 1.3.1

**Comment by kulttuuri** [comment]
Fantastic, thanks! Any ETA for 1.3.1?

**Comment by zodern** [comment]
It's available now. You can update with `npm i -g mup`.
