### ISSUE TITLE
[1.3.1] Did not work switching from 1.2.11

### ISSUE THREAD

**Issue by nadeemja** [zodern/meteor-up#705]
Hi,

1.2.11 worked, so I tried with 1.3.1 without changing anything and it failed and killed my site.

Here are the logs:

Started TaskList: Pushing Meteor App
[108.61.179.72] - Pushing Meteor App Bundle to The Server
[108.61.179.72] - Pushing Meteor App Bundle to The Server: SUCCESS
[108.61.179.72] - Prepare Bundle
[108.61.179.72] - Prepare Bundle: SUCCESS

Started TaskList: Configuring App
[108.61.179.72] - Pushing the Startup Script
[108.61.179.72] - Pushing the Startup Script: SUCCESS
[108.61.179.72] - Sending Environment Variables
[108.61.179.72] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[108.61.179.72] - Start Meteor
[108.61.179.72] x Start Meteor: FAILED

	-----------------------------------STDERR-----------------------------------
	rm: cannot remove 'current/bundle/programs/server': Directory not empty
	-----------------------------------STDOUT-----------------------------------
	using image
	----------------------------------------------------------------------------
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by nadeemja** [comment]
From the server side:

npm WARN enoent ENOENT: no such file or directory, open '/bundle/bundle/programs/server/package.json' 
Aug 24 04:45:51 108.61.179.72 309ff639bb26: npm WARN server No description 
Aug 24 04:45:51 108.61.179.72 309ff639bb26: npm WARN server No repository field. 
Aug 24 04:45:51 108.61.179.72 309ff639bb26: npm WARN server No README data 
Aug 24 04:45:51 108.61.179.72 309ff639bb26: npm WARN server No license field. 
Aug 24 04:45:51 108.61.179.72 309ff639bb26: => Starting meteor app on port:80 
Aug 24 04:45:51 108.61.179.72 309ff639bb26: module.js:327 
Aug 24 04:45:51 108.61.179.72 309ff639bb26:     throw err; 
Aug 24 04:45:51 108.61.179.72 309ff639bb26:     ^ 
Aug 24 04:45:51 108.61.179.72 309ff639bb26: Error: Cannot find module './programs/server/boot.js' 
Aug 24 04:45:51 108.61.179.72 309ff639bb26:     at Function.Module._resolveFilename (module.js:325:15) 
Aug 24 04:45:51 108.61.179.72 309ff639bb26:     at Function.Module._load (module.js:276:25) 
Aug 24 04:45:51 108.61.179.72 309ff639bb26:     at Module.require (module.js:353:17) 
Aug 24 04:45:51 108.61.179.72 309ff639bb26:     at require (internal/module.js:12:17) 
Aug 24 04:45:51 108.61.179.72 309ff639bb26:     at Object.<anonymous> (/bundle/bundle/main.js:9:1) 
Aug 24 04:45:51 108.61.179.72 309ff639bb26:     at Module._compile (module.js:409:26) 
Aug 24 04:45:51 108.61.179.72 309ff639bb26:     at Object.Module._extensions..js (module.js:416:10) 
Aug 24 04:45:51 108.61.179.72 309ff639bb26:     at Module.load (module.js:343:32) 
Aug 24 04:45:51 108.61.179.72 309ff639bb26:     at Function.Module._load (module.js:300:12) 
Aug 24 04:45:51 108.61.179.72 309ff639bb26:     at Function.Module.runMain (module.js:441:10) 
Aug 24 04:45:53 108.61.179.72 309ff639bb26: tar (child): *.tar.gz: Cannot open: No such file or directory 
Aug 24 04:45:53 108.61.179.72 309ff639bb26: tar (child): Error is not recoverable: exiting now 
Aug 24 04:45:53 108.61.179.72 309ff639bb26: tar: Child returned status 2

**Comment by nadeemja** [comment]
Downgrading do 1.2.11 and re-deploying brings my site back online.

**Comment by zodern** [comment]
I haven't been able to reproduce it, but it should be fixed in 1.3.2.
