### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by trevordowdle** [zodern/meteor-up#709]
I can successfully communicate between client/server when running a local instance however after deploying (SSH) I get the following error: WebSocket connection to 'wss://mydomain.com:3200/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Has anyone successfully got Websockets to work via a MUP settings/deployment?  Is installing nginx on the server something I should look at?

**Comment by zodern** [comment]
Web sockets currently don't work when using Let's Encrypt or the reverse proxy #612. 

If the websocket is on a different port than the app, you will need to expose the port: https://github.com/zodern/meteor-up/issues/460#issuecomment-283455401.

**Comment by trevordowdle** [comment]
Thank you for clarifying.
