### ISSUE TITLE
"current" directory is missing

### ISSUE THREAD

**Issue by sirpy** [zodern/meteor-up#710]
seems like this commit for meteor-start.sh  is deleting the "current"
3e9752b71db2e9dbda168d4a608eb8859b45c761
every deploy should have the current+last directories.
i dont know why but it has been modified to check if the :latest image exists and if so it deletes the current directory. i dont think this is the expected behaviour. there's no reason to delete current+last they should always be present.
i use the current directory to serve assets directly via my nginx proxy.

**Comment by zodern** [comment]
It creates a docker image with the bundle in it, which makes deployments more reliable and easier to troubleshoot, but it doesn't use `current` or `last` anymore. You can set `meteor.docker.prepareBundle` to `false` in your config to go back to how it was.

**Comment by ghost** [comment]
I'm trying to access my assets folder as well and having set `app.docker.prepareBundle` to false does not give me the current folder in /opt/app.
Am I looking in the wrong place?

**Comment by sirpy** [comment]
the correct path is meteor.docker.prepareBundle, it worked for me
in your mup settings json there's a field
meteor, under it a field docker and there you should set prepareBundle.

**Comment by zodern** [comment]
@nikna after you change it, you need to run `mup deploy`. If you did that and it didn't work, could you please share your config?

@sirpy Since mup 1.3, `meteor` is an alias of `app`, and they both do the same thing. Eventually `meteor` will be depreciated and removed.

**Comment by ghost** [comment]
@zodern Trying to reproduce my issue fixed it somehow. I suspect that it could have been caused by renaming the app (from upper case to lowercase) before changing `app.docker.prepareBundle`. 
Thanks however!
