### ISSUE TITLE
Prepare bundle allow for environment vars

### ISSUE THREAD

**Issue by jessb321** [zodern/meteor-up#711]
I need to set a http proxy for docker, and this works normally, but with the prepareBundle, it does not go through the proxy server.

**Comment by zodern** [comment]
@willyb321 could you please try with the 1.3.2 beta (install with `npm i -g mup@next`)?

**Comment by jessb321** [comment]
@zodern Yep - that went through perfectly! Thanks! I'll close this now!

**Comment by jessb321** [comment]
Actually, it doesn't seem to have worked - I didn't realize I had `prepareBundle: false` in my config.

**Comment by zodern** [comment]
It should be working correctly in 1.3.2.
