### ISSUE TITLE
Can't find ffmpeg on server

### ISSUE THREAD

**Issue by trevordowdle** [zodern/meteor-up#712]
I installed ffmpeg on my Ubuntu 16.04 server.

I verified that I could see ffmpeg in user/bin/
and set the path to an environment variable.

```
    env: {
      ROOT_URL: "https://myDomain.com",
      FFMPEG_PATH: "/usr/bin/ffmpeg",
      FFPROBE_PATH: "/usr/bin/ffprobe"
    }

```
But when I try to find the location of ffmpeg after deploy with MUP I can't see it listed.

```
   fs.readdir('/usr/bin/', (err, files) => {
       files.forEach(file => {
           console.log(file);
       });
   });
```

How can I properly install/access ffmpeg on the server?

Thanks

**Comment by zodern** [comment]
You need to create a new docker image with  ffmpeg installed.

**Comment by trevordowdle** [comment]
Thank you

**Comment by haojia321** [comment]
@zodern could you elaborate please? If I need to create a new docker image does that mean i cannot use MUP?
