### ISSUE TITLE
Document about how to deploy to server with an ios app.

### ISSUE THREAD

**Issue by leefurong** [zodern/meteor-up#713]
In my app, I need to deploy to server along with an ios app.

In [meteor deployment documents](https://guide.meteor.com/mobile.html#building-and-submitting), it suggest using `meteor build` to build a bundle for server and output files for ios or android.

How to deploy to the server while output an ios/android app?

I can't find it in mup docs.

**Comment by edemaine** [comment]
`mup` will just take care of the server deployment.  It uses `meteor build --server-only` internally to do so.

To build a mobile app, you'll have to run `meteor build` separately, and do what you normally do with the resulting apps.  (`mup` isn't designed to upload your app to the app store.)  This is probably what you want -- the mobile app needs to update much less frequently than the server, given automatic hot code pushes.
