### ISSUE TITLE
phantomjs 2.1.1

### ISSUE THREAD

**Issue by domarty** [zodern/meteor-up#722]
I'm finding that phantomjs 1.9.8 is failing any time I try to use it on a Meteor-generated site.  How can I force mup to install phantomjs 2.1.1 instead?

**Comment by thebarty** [comment]
any progress? I got the same issues with chromedriver

**Comment by zodern** [comment]
You need a docker image that uses phantomjs 2, such as [zodern/meteor](https://github.com/zodern/meteor-docker).

**Comment by zodern** [comment]
Since mup 1.4.4, it is possible to customize the docker image: http://meteor-up.com/docs#customize-docker-image. That can be used to install phantomjs 2.
