### ISSUE TITLE
This site can’t be reached after 2nd deploy

### ISSUE THREAD

**Issue by stolinski** [zodern/meteor-up#73]
Site is up and running after 1 deploy, after running deploy a 2nd time I get "This site can’t be reached".

This is on a 100% brand new Digital Ocean Ubuntu 14.04 droplet. 

Even when the site actually loaded after the first deploy I was getting an error while verifying.

```
  npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

> fibers@1.0.8 install /bundle/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js


=> Redeploying previous version of the app
```

Again, this is on a 100% brand new droplet, Meteor 1.3.  The current version of Mupx does the exact same thing. I've had mupx working previously for a long time, but the latest of either won't work on a fresh droplet.

**Comment by madushan1000** [comment]
Did the app name or the meteor version changed between deployments? Have you tried increasing `deployCheckWaitTime` ?

**Comment by ericvrp** [comment]
Whenever something is not working with mup or mupx people mention increasing deployCheckWaitTime. It looks like this should not be neccessary. Why not check frequently until aborted. With showing time and number of attempt displayed and the expected/normal case in the manual we should be ready to go and move on to real issues.

**Comment by madushan1000** [comment]
@ericvrp Sound like a good idea, If someone can make a PR with a couple of tests, we can merge it.

**Comment by timothyarmes** [comment]
I've just had the same problem because I changed the name of the app.

Is there a clean way to do this?

**Comment by madushan1000** [comment]
If you change the name of the app, you have to remove all the docker containers on the server related to your app manually.

**Comment by timothyarmes** [comment]
Since everything's installed automagically, we don't know how it's been done. What do we ned to do to remove the docker containers?

**Comment by timothyarmes** [comment]
For others who need to work out how to do this:

First, ssh into your server:

```
ssh -i <pem-file-path> <username>@<ip-address>
```

You can list all docker containers like this:

```
docker ps -a
```

In most cases there'll just be one container - the one created by mup. Something like this:

```
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                          PORTS                NAMES
8ca167a5a4ce        meteorhacks/meteord:base   "/bin/sh -c 'bash $ME"   15 hours ago        Restarting (8) 50 minutes ago   0.0.0.0:80->80/tcp   myAppName
```

The name of the container will be that of the app you'd installed using mup. Now it's easy to remove it:

```
docker stop <app-name>
docker rm <app-name>
```

Now you can rename your app inside the mup file and redeploy.
