### ISSUE TITLE
[Question] Plugin vs hook vs ???

### ISSUE THREAD

**Issue by rcurrier666** [zodern/meteor-up#731]
My app uses additional servers written in Python and I'd like to deploy them as part of MUP deploy. Would a MUP plugin be the appropriate way to setup a Python Docker container and publish my Python code or would MUP hooks be more appropriate? Or would I need to fork MUP and change the actual code?

It would seem to be a useful addition if MUP could provide some way to config additional Docker containers to be set up and deployed.

**Comment by zodern** [comment]
If you don't need to add cli commands, and it won't be useful for other apps, hooks would be easier.
