### ISSUE TITLE
Websocket Handshake Error

### ISSUE THREAD

**Issue by romans127** [zodern/meteor-up#74]
Greetings , 

I've experienced this error on the old mup mupx and now the new modular mup.  

When I deploy an app to digital ocean with nginx I'm receiving an error in the console regarding websocket and a handshake failure.  I've searched countless articles for the fix but have not found anything to suffice.  The app appears to work just fine.  But the errorbis definitely an eye sore and I believe an indicator that something is or could be failing behind the scenes . not to mention every client ive launched has noticed the error and inquired about it.  

Any suggestions on how to fix the error ? 

Also I've ensured the port and the root URL matched the site .

**Comment by MasterJames** [comment]
Could you post the errors logged, please?

**Comment by romans127** [comment]
Sure can, 

Thank you.

``` sh
WebSocket connection to 'ws://www.galenagarlic.com/sockjs/336/6z1zzsed/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
```

**Comment by madushan1000** [comment]
What nginx are you using? The one from the mup frontend server or custom one?

**Comment by romans127** [comment]
Oh I was actually using one directly in the digital ocean account Is that not needed ?

So I have a digital ocean account. And I have nginx running directly within the container.

I'm sure this is probably wrong could you refresh my memory on how to set things up or what is needed ?

**Comment by madushan1000** [comment]
No, You can run your own Nginx server. Actually, it's recommended if you need to use Nginx as a proxy. But be sure to config websocket proxying following a guide like this. https://www.nginx.com/blog/websocket-nginx/

**Comment by romans127** [comment]
awesome thank you
