### ISSUE TITLE
How to efficiently deploy multiple containers to the same server?

### ISSUE THREAD

**Issue by elie222** [zodern/meteor-up#741]
I'd like to deploy 16 instances to a single server and then load balance between those instances with my own nginx configuration. The instances will be serve at ports 80, 8000, 8001,..., 8014.

Is there a way to only do one deploy to the server instead of 16 different deploys?

We wrote a script to do this and copy the first docker container 16 times over, but I've just noticed that the containers aren't auto restarting when they go down. Any ideas?

**Comment by MichalW** [comment]
Consider this package:
https://www.npmjs.com/package/pm2-meteor
in this case it may be more reasonable

**Comment by elie222** [comment]
Thanks. This is instead of Meteor Up?

**Comment by MichalW** [comment]
Yes. You only need to deploy one instance and run: `pm2-meteor scale 16`

**Comment by elie222** [comment]
This package has a problem with sticky sessions however. Have you used it with nginx to do the load balancing?

**Comment by elie222** [comment]
Seems you'd do it like this:
https://github.com/andruschka/pm2-meteor/issues/55

**Comment by elie222** [comment]
How is the auto restarting functionality working in this package? Is it inside the docker container or handled outside of it?

**Comment by zodern** [comment]
@elie222 mup uses docker run's [--restart](https://docs.docker.com/engine/reference/commandline/run/#restart-policies-restart) option.

**Comment by elie222** [comment]
Thanks. This is the line, right?
https://github.com/zodern/meteor-up/blob/92d370354767c9c126589339484832fcbc0a556e/src/plugins/meteor/assets/templates/start.sh#L62

**Comment by elie222** [comment]
This is how we're running this process now. Created this gist if anyone else would like to use it:
https://gist.github.com/elie222/10d8d830db341551612ba38ac6f32cd9

The advantage is that you do one deploy and the other 15 instances are copied really quickly without having to upload 15 times to the same server.

**Comment by elie222** [comment]
Also, we don't use `--hostname` option. Is it needed?
