### ISSUE TITLE
Mup fails during verification

### ISSUE THREAD

**Issue by s7dhansh** [zodern/meteor-up#742]
I am facing a random bug:

In the verifying deployment stage, I get this error 80% of the times (remaining 20% of the times the deployment works, which is very weird).
```
    Verifying Deployment: FAILED       
  curl: (52) Empty reply from server
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
        curl: (52) Empty reply from server
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
        curl: (52) Empty reply from server
        npm ERR! registry error parsing json
        Error: No such image: mup-portal:previous
         
        => Redeploying previous version of the app
```

The main trouble being this line:
```
Error: No such image: mup-portal:previous
```
I do not have any docker image by this name 'mup-portal'

The error before that is not the same always. For instance once I got,
```
error from daemon in stream: Error grabbing logs: EOF    
```

If I use `--verbose`, I see the app starting properly but then abruptly stopping with the `No such image` error.

**Comment by zodern** [comment]
> Error: No such image: mup-portal:previous

This is normal, and is from mup deciding which method to use to roll back the app.  I will try to make it more clear or hide it in the output.

The error causing the problems is `npm ERR! registry error parsing json`. 

> error from daemon in stream: Error grabbing logs: EOF

What docker version does the server have installed? Docker 1.13 fixed one cause of it.

How much ram and free disk space does your server have? Is it using a proxy?

**Comment by s7dhansh** [comment]
Docker version 17.07.0-ce, build 8784753
RAM: 1GB, Disk: 20GB (14 GB free)
No proxy.

As I mentioned this error `npm ERR! registry error parsing json` is not constant. I got a different error another time - `error from daemon in stream: Error grabbing logs: EOF`
I will dig deeper tonight and try to give you a more comprehensive list of errors. It is a production environment, hence can't do many random deployments.
I do not get any errors on any other testing/prod deployments.

**Comment by s7dhansh** [comment]
So I have increased my waitTime to 200 and the deployment has succeeded the last 3 times. Closing it for now.
