### ISSUE TITLE
How to redeploy without re-uploading (using last uploaded bundle)

### ISSUE THREAD

**Issue by jaredtmartin** [zodern/meteor-up#745]
Is there a way to attempt to re-run a deployment without re-uploading the whole project using the previous uploaded bundle?

**Comment by birdage** [comment]
is this what your after? `mup deploy --cached-build`

**Comment by zodern** [comment]
@jaredtmartin could you please explain why you want to?

If you want to skip building, you can use `mup deploy --cached-build`, as @birdage  said.
To skip Prepare Bundle and everything before it, you can use `mup reconfig`.

**Comment by jaredtmartin** [comment]
I want to avoid the upload time.  It takes a long time, like 15min.

**Comment by edemaine** [comment]
@jaredtmartin Do `mup start` / `mup stop` do what you want?
