### ISSUE TITLE
How to clean server, and start clean?

### ISSUE THREAD

**Issue by jaredtmartin** [zodern/meteor-up#746]
I've had this issue a couple of times, things somehow get screwed up and I'd like to be able to just delete everything and start again clean.  Unfortunately the docs aren't specific enough for me to know how to do that.  
I've tried stopping all the docker containers, deleting them all, (except for mongo), running mup setup and then mup deploy but now I get: No such container: meteor (meteor is the name of my app)
How can I clear this out so I can get a fresh start?  In the past I've just created a new virtual server, but that's overkill and it's a pain to update the DNS and SSL.  There must be an easy way.

**Comment by zodern** [comment]
@jaredtmartin could you please show the output from `mup deploy --verbose`? `No such container: meteor` usually is a symptom for a different problem.

Besides deleting the docker containers and images, another thing you can do  is delete the `/opt/<app name>` folder.

**Comment by nzomedia** [comment]
i've juste got that error about missing <app-name> container. I checked actual containers (with `docker ps -a`) and in fact there was no container at all (i deleted them previously). To solve i juste typed `mup setup`, and it recreated missing containers.

**Comment by DavidPishchik** [comment]
Try removing bycrypt is you are using it. helped me.
