### ISSUE TITLE
Error response from daemon: No such container: meteor

### ISSUE THREAD

**Issue by jaredtmartin** [zodern/meteor-up#747]
I just created a brand new droplet on digital ocean, set the password and tried to deploy my project.  I'm getting: Error response from daemon: No such container: meteor.  "meteor" is the my appname.  when I ssh to the server sure enough I can see there is no container named "meteor" running.  But I'm not sure how to fix it, and I'm not sure why this would happen on a clean deploy.

**Comment by zodern** [comment]
I am going to close this in favor of #746.

**Comment by chrisbutler** [comment]
also having this issue with a brand new aws ubuntu server and the latest mup... going to try removing options from the config or something? ugh
