### ISSUE TITLE
Mup SSL ignored in new deploys.

### ISSUE THREAD

**Issue by wessilfie** [zodern/meteor-up#749]
I am working on an already running app and want to update it to use Let's Encrypt.
I uncommented the section of the default mup.js file in version 1.3.1 and updated it to my domain, but the https links are still not working and nothing about ssl appears in my logs when the deploy is happening. Instead, the deploy is successful, but it mentions nothing about the SSL update. Any reasons why this is happening?

My current mup.js file:
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '<My Digital Ocean IP Address>',
      username: 'username',
      password: 'password',
      // pem: 'my-public-key-link'
      // or neither for authenticate from ssh-agent
    }
  },

  meteor: {
    // TODO: change app name and path
    name: 'my-app-name',
    path: 'path-to-project',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'https://my-domain.com',
      MONGO_URL: 'mongodb://localhost/meteor',
      MAIL_URL: 'my-mail-url',
    },

     ssl: { 
      // Enables let's encrypt (optional)
       autogenerate: {
         email: 'my-email@my-domain.com',
        // comma seperated list of domains
         domains: 'domain.com,www.domain.com, mydomain.com, www.mydomain.com'
       }
     },

    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/meteord:base',
      // imagePort: 80, // (default: 80, some images EXPOSE different ports)
      prepareBundle: false,
    },

    // This is the maximum time in seconds it will wait
    // for your app to start
    // Add 30 seconds if the server has 512mb of ram
    // And 30 more if you have binary npm dependencies.
    deployCheckWaitTime: 300,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    port: 27017,
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};

The output after running mup deploy:
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[159.203.139.9] - Pushing Meteor App Bundle to The Server
[159.203.139.9] - Pushing Meteor App Bundle to The Server: SUCCESS
[159.203.139.9] - Prepare Bundle
[159.203.139.9] - Prepare Bundle: SUCCESS

Started TaskList: Configuring App
[159.203.139.9] - Pushing the Startup Script
[159.203.139.9] - Pushing the Startup Script: SUCCESS
[159.203.139.9] - Sending Environment Variables
[159.203.139.9] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[159.203.139.9] - Start Meteor
[159.203.139.9] - Start Meteor: SUCCESS
[159.203.139.9] - Verifying Deployment
[159.203.139.9] - Verifying Deployment: SUCCESS

**Comment by zodern** [comment]
@wessilfie What does `mup docker ps` show?

**Comment by wessilfie** [comment]
@zodern this is what it shows
```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                        NAMES
bac3170ed17e        abernix/meteord:base   "/bin/sh -c 'bash ..."   45 seconds ago      Up 44 seconds       0.0.0.0:80->80/tcp           app-name
7abf51081174        abernix/meteord:base   "/bin/sh -c 'bash ..."   3 days ago          Up 3 days           0.0.0.0:3016->80/tcp         otherapp-website
daf87674c310        mongo:3.4.1            "/entrypoint.sh mo..."   3 days ago          Up 3 days           127.0.0.1:27017->27017/tcp   mongodb

```

**Comment by wessilfie** [comment]
Remade mup.js and then did mup setup and mup deploy and got the following:

``` 
ID        IMAGE                                           COMMAND                  CREATED              STATUS              PORTS                                      NAMES
297cd34a3477        jrcs/letsencrypt-nginx-proxy-companion:latest   "/bin/bash /app/en..."   53 seconds ago       Up 52 seconds                                                  app-nginx-letsencrypt
36fecc56d135        jwilder/nginx-proxy:latest                      "/app/docker-entry..."   About a minute ago   Up About a minute   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   app-nginx-proxy
e0ac63806510        abernix/meteord:base                            "/bin/sh -c 'bash ..."   About a minute ago   Up About a minute   80/tcp                                     app
c372c0091dea        mongo:3.4.1                                     "/entrypoint.sh mo..."   3 minutes ago        Up 3 minutes        127.0.0.1:27017->27017/tcp                 mongodb
7abf51081174        abernix/meteord:base                            "/bin/sh -c 'bash ..."   3 days ago           Up 3 days           0.0.0.0:3016->80/tcp                       otherapp-website

```

**Comment by JonathanLehner** [comment]
any solutions?

**Comment by zodern** [comment]
It is recommended to use the reverse proxy instead: http://meteor-up.com/docs#reverse-proxy
