### ISSUE TITLE
Retrieve code, help!

### ISSUE THREAD

**Issue by devarthurribeiro** [zodern/meteor-up#751]
First of all, sorry to open an issue for questioning. but I'm desperate. I lost a lot of my code due to a crash with git more before I did a deploy. the mup clone my code somewhere before building?

**Comment by zodern** [comment]
Sorry, it doesn't copy the code. In your computer's temp folder, there will be a folder that starts with `mup-meteor-` with the bundle, but the code there would have been modified by babel, and the client code would have been minified.
