### ISSUE TITLE
clientUploadLimit not worked #proxy

### ISSUE THREAD

**Issue by mkorban** [zodern/meteor-up#755]
If i change the proxy.shared.clientUploadLimit the corresponding value appears in the file /opt/mup-nginx-proxy/config/nginx-default.conf, but no effect it does not. When the output of the command "nginx -T" shows that the specified file is not read by nginx. As a result, it is impossible to upload large files and big POST queries

**Comment by rolljee** [comment]
Any update on this ?

We are experiencing the same issue for files larger than 1GB
