### ISSUE TITLE
Need help building a mysql/mariadb plugin

### ISSUE THREAD

**Issue by nzomedia** [zodern/meteor-up#756]
Hello everyone, i'm currently making a mariadb plugin for mup to add a mariadb container to the orignal setup. The repo is here https://github.com/nzomedia/mup-mariadb .
Please take a look at it, i'm not very deep into system administration and shell commands, i'd like some critics or advices on how to improve this.
I'm currently thinking about using a lighter mariadb image to reduce size and perhaps another mongodb container to replace the default one.
My current project is about deploying a Meteor app which uses mysql as well as mongodb. I have to deploy it on a small office, if you have any advice i'll be very happy to discuss about it.

Thanks mup team and all other contributors for the great task done so far.

**Comment by zodern** [comment]
I think this is the first plugin someone built besides me. Are you still using it? I can add it to the list of plugins on Meteor Up's websites if you want, and offer some suggestions if you are interested in maintaining it.
