### ISSUE TITLE
Updating To Latest Version Breaks MUP

### ISSUE THREAD

**Issue by SevenZark** [zodern/meteor-up#757]
I am working on a Mac. In a new project, I issued the command:
`mup init`

I then got a message that I needed to update MUP. So I did this:
`npm i -g mup`

And got the following error:
```
npm ERR! path /usr/local/lib/node_modules/mup/node_modules/opencollective/dist/bin/opencollective.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/mup/node_modules/opencollective/dist/bin/opencollective.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[redacted]/.npm/_logs/2017-10-02T15_00_07_973Z-debug.log
```

Even worse, mup now appears to be broken on my system. When I issue any mup command I get this:
`bash: /usr/local/bin/mup: No such file or directory`

Which means my project is now dead in the water.

**Comment by zodern** [comment]
@SevenZark did you try running `npm uninstall -g mup` and reinstalling?

**Comment by SevenZark** [comment]
@zodern Yes, I still get the same error message when trying to install again after uninstalling.

**Comment by zodern** [comment]
It is a bug with the opencollective cli: https://github.com/opencollective/opencollective-cli/issues/3

You can install a working version of mup with `npm install -g mup@1.2.11`.

**Comment by SevenZark** [comment]
Thanks!
