### ISSUE TITLE
Migrating from a very old mup version (pre-docker) to new mup.

### ISSUE THREAD

**Issue by CarlQLange** [zodern/meteor-up#759]
Hi,

I'm in the process up updating a very old (meteor 1.1) app to a newer version of meteor. This app is deployed via a really really old mup, from the mup-legacy repo. I think I need to also update mup with this meteor updating - since newer versions of meteor use different `node` versions.

I'm worried that I'm going to lose data or something in just doing porting the `mup.json` to `mup.js` and doing `mup deploy` - can someone point me to the best migration steps?

Thanks,
Carl

**Comment by nzomedia** [comment]
Hello, perhaps the documentation can provide you some help: http://meteor-up.com/docs.html#migration-guide
But please make backups before doing anything.

**Comment by CarlQLange** [comment]
Hi,

I actually meant to close this - I'm going to do exactly what the docs say and just spin up a new server, `mongodump` off the old one, `mongorestore` on the new one, and change over DNS. Thanks for maintaining `mup` everyone, you're doing a great job!!

**Comment by sscaff1** [comment]
I just upgrade from pre-docker mup to this version of mup. I didn't control the server (nor did I want to get in a thing with my client about moving servers). However, these steps worked for me:
- Upgrade the site to the latest version of meteor
- `meteor npm i --save-dev mup@latest`
- `npx mup init`
- Add these scripts to the package.json
    ```
    {
      ...
      "setup": "cd .deploy && mup setup",
      "deploy": "cd .deploy && mup deploy",
      ...
    }
    ```
- `npm i -g mup@0.11.3`
- In your pre-docker config, run `mup stop`. This avoids the above error.
- `npm run setup`
- `npm run deploy`

I was successfully able to upgrade without moving servers. Hope this helps others. 

@zodern let me know if you'll accept a PR to add this to this migration section of the docs, and I'll submit it.
