### ISSUE TITLE
Request for convention over location of mupx settings files within a Meteor app project

### ISSUE THREAD

**Issue by VasilySizov** [zodern/meteor-up#76]
Hi,

I would like to suggest having a convention over location of Meteor Up project files within a Meteor app directory.

For me, the best way is to have the following behavior for mupx command:
1) User goes to Meteor application directory and runs command "mupx init staging". This should create a path and a file ".mupx/staging/mup.js" within Meteor application directory.
2) Then user should be allowed to to run the command "mupx deploy staging" being staying in a root directory of the app. In that case mupx just runs .mupx/staging/mup.js

This approach has the following advantages:
- User is allowed to run Meteor Up being just in a root directory of an app, like it is usually done to run "meteor" during development.
- This approach supposes that user might have more than one deployment environment, and these environments are specified by names (e.g. "staging" above, or "production")
- ".mupx" is a great place to store deployment configs and not collide with application's files.

Thanks!

**Comment by zeroasterisk** [comment]
I also agree that environments should be supported, somehow.

I've made a `deploy-dev` and a `deploy-prod` folders, each with their own `mup.js` file --- this is a bit kludgy but works.
