### ISSUE TITLE
Can't expose mongo database

### ISSUE THREAD

**Issue by funkyremi** [zodern/meteor-up#760]
I want the mongo container to expose port 27017. 
I tried to set the `"meteor.docker.port"` but I get this message with mup 1.3.4:
```
1 Validation Error
  - "meteor.docker.port" is an unknown property
```
Is there any other way to allow other machines to access mongo db?

**Comment by zodern** [comment]
You can create an ssh tunnel. Mup currently doesn't setup authentication for MongoDB, so it is only secured by preventing access outside of the server.

**Comment by AngelAlvarado** [comment]
@zodern is it possible to access the MongoDB directly these days?
