### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection during a deploy

### ISSUE THREAD

**Issue by haleo9000** [zodern/meteor-up#763]
Running into a problem when I try to deploy my app. Using a mup.config which has worked in the past and is unchanged, although the version of meteor has (I believe) been updated.

this is the console output as the build and push progresses: 

$ mup --config /mup.js --settings /settings.json deploy
update 1.0.4 => 1.3.4
Building App Bundle Locally

Started TaskList: Pushing Meteor
[35.164.149.208] - Pushing Meteor App Bundle to The Server
[35.164.149.208] x Pushing Meteor App Bundle to The Server: FAILED
	Failure
(node:13591) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failure
(node:13591) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

As I stated, I am working with a mup config which has worked in the past, but is not now. 

`
module.exports = {
    servers: {
        one: {
            host: "HOST",
            username: "USERNAME",
            pem: "KEY.pem",
            env: {
                MONGO_URL: MONGOURL" 
            } 
        } 
    },
    meteor: {
        name: "APPNAME",
        path: "../app",
        servers: {
            one: {} 
        },
        buildOptions: {
            serverOnly: true,
            debug: true,
            cleanAfterBuild: true
        },
        env: {
            ROOT_URL: "ROOTURL",
            PORT: PORT,
            NODE_ENV: "production",
            MONGO_URL: "MONGOURL" 
        },
        ssl: {
            crt: "BUNDLE.crt",
            key: "KEY.pem",
            port: PORT 
        },
        dockerImage: "abernix/meteord:base",
        deployCheckWaitTime: 500,
        enableUploadProgressBar: true 
    }
};`

This is onto an AWS instance. Any help would be greatly appreciated. I'm half-suspicious it has to do with the docker image not being up to date, but am not 100% sure. (suspicion based on issue https://github.com/zodern/meteor-up/issues/325).

Thanks!

**Comment by zodern** [comment]
@haleo9000 could you please update mup with `npm i -g mup` and try again?

**Comment by haleo9000** [comment]
@zodern it was a combination of things, I think. One was that my mup was out of date and I had updated it. Then, due to the project I'm working on being a legacy project, the deploy configs were mussed up. Finally, AWS (really the linux distro) does this fun thing where it fills up your application instance with old and unused kernels, filling the allocated drive space with essentially dead code.

Sorry for the confusion.
