### ISSUE TITLE
How to use encrypted SSH Key for auth

### ISSUE THREAD

**Issue by Slind14** [zodern/meteor-up#764]
Hi there,
how can I use an encrypted SSH Key for authentication? Mup doesn't ask for the password it just fails...

**Comment by zodern** [comment]
The docs has instructions at http://meteor-up.com/docs.html#ssh-keys-with-passphrase-or-ssh-agent-support

**Comment by Slind14** [comment]
Thank you, does this work on windows?

**Comment by zodern** [comment]
It doesn't.
