### ISSUE TITLE
Feature Request: Deploying a Meteor App with AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by nadeemja** [zodern/meteor-up#768]
Hi,

Would it be possible to have meteor-up automate what it is done manually in this guide?

https://themeteorchef.com/tutorials/how-to-deploy-a-meteor-application-to-aws-elastic-beanstalk

**Comment by zodern** [comment]
It would be possible to create a [plugin](http://meteor-up.com/docs.html#creating-a-plugin) that does. In the config, there is a property `app.type`, that when set to anything besides `meteor` (it defaults to meteor), the meteor plugin doesn't do anything, allowing other plugins to handle setup, deployment, etc.

**Comment by nadeemja** [comment]
Cool! Thanks for the answer :)

Is this something you'd be willing to work on if your efforts were sponsored?

**Comment by zodern** [comment]
What are the features you need from elastic beanstalk? Why do you want to use it?

**Comment by nadeemja** [comment]
Horizontal auto-scaling, mainly. :)

**Comment by zodern** [comment]
It will be a while before mup supports that. Yes, I would be willing to create the plugin if it was sponsored.

**Comment by nadeemja** [comment]
That's great, Zodern! 

What amounts would be needed to create the plugin?

**Comment by nadeemja** [comment]
Or, perhaps, you could indicate what different amounts, such as $500, $1000, $1500 etc.. would achieve :) 

I think a lot of different companies/developers would be interested in chipping in.

**Comment by zodern** [comment]
I can create the plugin for $850. $500 would achieve setup, deploying the app, cli commands to start/restart/stop the app, auto scaling and load balancing. The remaining $350 would finish the cli commands, viewing logs, ssl, and fine tuning the configurations.

**Comment by nadeemja** [comment]
Cool! 

Do you have a preferred method of payment? 

I'm going to see if I can get others to join in on this effort :)

**Comment by nadeemja** [comment]
Btw, any estimates on when delivery could be expected?

**Comment by zodern** [comment]
I can fit it in my schedule and get it done in 2 - 3 weeks. I can start on Friday.

Could I please get your email? You can send it to [z-modern@live.com](mailto:z-modern@live.com)

**Comment by nadeemja** [comment]
Mail sent :)

**Comment by theodorDiaconu** [comment]
I'm here to say that I'm interested in this. @zodern can you pls work on an API first ? Just the commands we would need to run and what it would achieve. If the API looks promising and dead-simple, I'll be contributing.

**Comment by zodern** [comment]
@theodorDiaconu Here is an overview of the plugin:

To use the plugin:
1) Install mup and the plugin
2) Create IAM user if needed
3) Create config
4) Run `mup deploy`

The config will probably change as I work on the plugin, but it will be similar to this:
The servers object will not be needed.

App properties will include:
- `app.type` will be set to something like `aws-beanstalk` so the plugin knows it is supposed to handle deployment (required)
- `app.env`, `app.path`, and `app.name` will still exist (required).
- `app.buildOptions` will still exist, but serverOnly will be set to true by default so this object won't need to be in most configs
- There will be an object for aws authentication (required)
- Properties for min (required) and max (optional) instances, and region (optional)
- `app.sslDomains` will be an array of domains to create certificates for (optional)

There will be a few additional properties to further customize it, but most apps won't need to use them.

It will automatically configure load balancing and auto scaling. There might be properties in the config to customize the rules for auto scaling.

CLI Commands:
- deploy
- setup (will be automatically run by deploy when needed)
- reconfig (update ssl, env, min and max instances, etc. without deploying a new version)
- start
- stop
- restart
- logs
- status (This will be a sub-command to the plugin's command, but mup 1.4 is bringing a top-level status command that plugins can add a hook for)

I will release mup 1.3.5 with a couple changes to better support this type of plugin:
- Support missing `servers` object or when the object has no keys
- Finish separating the default and meteor plugins so other plugins can completely take over managing the app

Does this sound good?
Please let me know if there is anything you want more information on.

**Comment by derwaldgeist** [comment]
Sounds good! Two questions:
- will this setup support letsencrypt?
- will it support settings.json?
After having read the original blog post and its comments, the latter seemed to be quite a challenge.

**Comment by nadeemja** [comment]
I like it, @zodern! 

Also, I've assumed that the features @derwaldgeist lists will be functional. Can you confirm?

**Comment by zodern** [comment]
`settings.json` will definitively be supported.

For SSL, the first version will use [AWS Certificate Manager](https://aws.amazon.com/certificate-manager/). It is free and automatically renews certificates. Though verifying the domain is not completely automated like it is with Let's Encrypt. From the FAQ:

> In order to validate that you control the domain name or names included in the certificate you requested, an email is sent to the registered domain owner for each domain name in the certificate request. 

> When you request a certificate, a WHOIS lookup for each domain name in the certificate request is used to retrieve contact information for the domain. Email is sent to the domain registrant, administrative contact, and technical contact listed for the domain. Email is also sent to five special email addresses, which are formed by prepending admin@, administrator@, hostmaster@, webmaster@ and postmaster@ to the domain name you’re requesting.

> The domain owner or an authorized representative (approver) can approve the certificate request by following the instructions in the email. The instructions direct the approver to navigate to the approval website and click the link in the email or paste the link from the email into a browser to navigate to the approval web site. The approver confirms the information associated with the certificate request, such as the domain name, certificate ID (ARN), and the AWS account ID initiating the request, and approves the request if the information is accurate.

I would like to switch to Let's Encrypt in a later version, but it could be a challenge to implement.

**Comment by derwaldgeist** [comment]
Thanks for the info. If I understand the description on the AWS site correctly, you get a SSL certificate for your site for free, like with letsencrypt, as long as you are using it in combination with AWS resources (like Elastic Beanstalk). Makes sense.

**Comment by nadeemja** [comment]
@zodern 

I'm at a point were I'm close to wiring funds to your Open Collective account.

But, could you first share some thoughts on the kind of support and maintenance we could expect? 

Regards,

Nadeem

**Comment by SachaG** [comment]
What's the URL for wiring funds? How much more is needed?

**Comment by Discordius** [comment]
I would also be interested in contributing funds to this, if additional funds are still needed.

**Comment by nadeemja** [comment]
Hi everyone,

@zodern and I have talked about the following arrangement per email:

1. Payments are wired to https://opencollective.com/meteor-up

2. 50%, i.e. $ 425, is to be paid upfront, and the rest upon delivery. 

I have just wired $ 125 on Open Collective via my company, Sembly. 
Please see: https://opencollective.com/meteor-up/transactions

Hopefully the remaining $ 300 on the upfront payment could be paid by those of you have indicated interest in doing so :) 

Regards,

Nadeem

**Comment by SachaG** [comment]
I tried donating $100 but then it showed up as a monthly subscription so I had to cancel it… Not sure if the initial payment went through or not. Anyway I'm happy to contribute $100 to the cause, even if I don't use AWS deployment I've gotten so much use out of Meteor Up throughout the years that it's the least I can do :)

**Comment by coagmano** [comment]
@SachaG try this page: https://opencollective.com/meteor-up/donate
It has the "once time" donation option

**Comment by SachaG** [comment]
Thanks, @zodern let me know if it didn't work and I'll try that.

**Comment by zodern** [comment]
@SachaG it did work. Thank you.

**Comment by theodorDiaconu** [comment]
@zodern put up $50 as well :) let's rock

**Comment by nadeemja** [comment]
Very nice guys! :) 

$ 150 to go before the upfront payment is funded.

Unless this sum is contributed by other members of the community come Monday, I will cover it. Also, I'm guaranteeing the payment of the post-delivery $ 425, but hopefully the community will chip in :)

**Comment by SachaG** [comment]
Maybe someone could outline the feature that will be developed and its benefits and then create a post on the Meteor forums? I'd be happy to upvote/comment/retweet :)

**Comment by nadeemja** [comment]
Great idea, @SachaG! I think @theodorDiaconu has experience using AWS and could speak to the benefits, while @zodern has already outlined the API in a comment. I wonder if this piece shouldn't go directly into the readme of MUP. What do you guys think?

**Comment by came** [comment]
I am also in with $100 :) MUP saved my ass for quite some time ...and EB would be just awesome.

**Comment by asmakam** [comment]
This is awesome! @zodern just sent $100 for the project!

**Comment by theodorDiaconu** [comment]
@zodern can you give us a delivery date ? :) Your project is already more than 50% backed.

**Comment by nadeemja** [comment]
Hi!

If I recall correctly from our emails, the delivery dates were between the 20th and 24th of November. I was supposed to post this, but have been busy with work. Will post an update today. :)

**Comment by nadeemja** [comment]
@came What name did you donate under?

**Comment by came** [comment]
...oh, I donated as kiwi / carsten

**Comment by zodern** [comment]
I've invited all of you who donated to the repository. The plugin and docs are almost finished. Deploying, load balancing, zero downtime deployments, and auto scaling are all implemented.

The one feature left is the ssl certificates. I am waiting for AWS to increase my account's limit of certificate requests since it seems my limit is 0.

**Comment by Discordius** [comment]
I donated to the repository but wasn't invited. 

Also: What's the current state of the repository? Is it basically production-ready?

**Comment by nadeemja** [comment]
I've been playing around with it. I didn't get around to push to production yet, but will do so very soon. First tests are very promising! :)

**Comment by zodern** [comment]
@Discordius sorry I didn't invite you. You should have access to it now.

**Comment by paduchurikowsik** [comment]
i donated to the repository, when can i get access to it. 
Thanks

**Comment by paduchurikowsik** [comment]
@zodern hey i didnt get any mail for any repositories, can you please tell me what should i do

**Comment by zodern** [comment]
Sorry @paduchurikowsik. You should have access to it now.

**Comment by PolybitSol** [comment]
Hey @zodern, I'm also extremely interested in the autoscaling plugin for my project. 

Is there an ETA on the public release, and if not what is the status of funding and required amount to get access to the repository? Also interested in the current functionality of the private repository. Thank you for your time!

**Comment by nadeemja** [comment]
@zodern

From my side, I'm OK in making the project public. Any reason why not?

**Comment by zodern** [comment]
It is now public!
https://github.com/zodern/mup-aws-beanstalk
Docs at: https://github.com/zodern/mup-aws-beanstalk/blob/master/docs/index.md
Install with `npm i -g mup mup-aws-beanstalk`

Thank you to all who donated toward this plugin!

**Comment by derwaldgeist** [comment]
Thanks for making this public! Good to know there's a professional scaling option once we need it.

**Comment by PolybitSol** [comment]
Brilliant, I'll be trying that out tonight @zodern, great work - thank you!

**Comment by liamrohan** [comment]
This is flipping good. Can't believe I didn't know about it until now. Thank you zodern. 

Donation on its way to you 
Thanks
