### ISSUE TITLE
createFileStream not working

### ISSUE THREAD

**Issue by kristofvanwoensel** [zodern/meteor-up#769]
I am encountering the following problem:

I would like to write files on my server during production. Eg: The user decides to download a certain document, therefore the server needs to download this document first from a cloud service and store it locally. This works perfectly in dev-mode, but when I deploy my app using MUP my files are not created. Does MUP/docker remove these files?
Here's my mup.js:

`

	meteor: {
	name: 'nascholingen',
	path: '/webserver/nascholingen',
		volumes:{
		'/webserver/nascholingen/private/uploads':'/webserver/nascholingen/private/uploads',
		'/webserver/downloads':'/webserver/downloads'
		},

	servers: {
	  one: {},
	},

	buildOptions: {
	  serverOnly: true,
	},

	env: {
	  // TODO: Change to your app's url
	  // If you are using ssl, it needs to start with https://
	  ROOT_URL: 'http://10.10.0.123',
	  MONGO_URL: 'mongodb://localhost/meteor',
		PORT:'3002'
	},

	docker: {
	  // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
	  image: 'abernix/meteord:base',
	  // imagePort: 80, // (default: 80, some images EXPOSE different ports)
	},

	// This is the maximum time in seconds it will wait
	// for your app to start
	// Add 30 seconds if the server has 512mb of ram
	// And 30 more if you have binary npm dependencies.
	deployCheckWaitTime: 60,

	// Show progress bar while uploading bundle to server
	// You might need to disable it on CI servers
	enableUploadProgressBar: false
	},
	 mongo: {
		port: 27017,
		version: '3.4.1',
		servers: {
		  one: {}
		}
	  }
	};

`

**Comment by zodern** [comment]
The files will be created in the docker container, but whenever the app is restarted, crashes, or a new version is deployed docker removes all changes to the file system. It is recommended to use [volumes (meteor.volumes in the config)](http://meteor-up.com/docs#everything-configured).

**Comment by zodern** [comment]
If you are creating it in the folders in `meteor.volumes`, docker won't remove them.

**Comment by erixtekila** [comment]
Hi @kristofvanwoensel, did you succeed in creation and make it downloadable ?
Thanks for sharing your solution.

**Comment by kristofvanwoensel** [comment]
Hi erixtekila
It has been a year now, so I'm not sure what actually did the trick. I guess it had to do with the lack of ownership or writing rights to this folder. I would suggest trying a chown & chmod of the folder.

I  can verify that my mup.js file is still like the one I posted above.
