### ISSUE TITLE
cant run mup on windows

### ISSUE THREAD

**Issue by jmwierzbicki** [zodern/meteor-up#77]
Hello, i installed M-UP as instructed in readme, mup init successfully created mup.js and settings.json, but once there is mup.js in current directory, mup command tries to open mup.js, in my case it's IDE. Looking forward for help

**Comment by MasterJames** [comment]
You ran mup setup and mup deploy after some setting adjustments?

**Comment by gjr-qm** [comment]
You can start with: `where mup` That will show you the path for mup (e.g. C:\Users\You\AppData\Roaming\npm\mup.cmd)

Then you can do 2 things:
1. Go to the directory and rename mup.cmd (for example in mupx.cmd). After that start mup in the mup directory of your project with `mupx deploy`. You have to remember you renamed mup the next time!
2. Call mup in the right directory: `C:\Users\You\AppData\Roaming\npm\mup deploy`. You will have to remember the path or check it again from now on.

**Comment by FrancoisDeBellescize** [comment]
This is a path problem on Windows.
You have to write : "/Users/my-user/" instead of "~/"
