### ISSUE TITLE
'mup' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by sproleee** [zodern/meteor-up#774]
I'm trying to set up mup on my work computer running Windows and can't get mup to work. I ran `npm install -g mup` and when I try to run mup init in my deploy folder inside my meteor app, I get the `'mup' is not recognized as an internal or external command, operable program or batch file.` error in my command prompt window.

In the `C:\Users\user\AppData\Roaming\npm` folder, I see an mup file and a mup.cmd file. Inside the `C:\Users\user\AppData\Roaming\npm\node_modules` folder, I see a `mup` folder with mup installed. So the installation worked, but I can't get this to work on this Windows 7 machine.

**Comment by sproleee** [comment]
I was able to get mup to work by running `C:\Users\user\AppData\Roaming\npm\mup.cmd init` to initialize mup, `C:\Users\user\AppData\Roaming\npm\mup.cmd setup` to set up for deployment and `C:\Users\user\AppData\Roaming\npm\mup.cmd deploy` to deploy my application.

Windows is a horror show. Not sure why I can't even set up my environmental variables anymore.

**Comment by zodern** [comment]
Do other globally installed packages work?

**Comment by sproleee** [comment]
@zodern The only other global install I have is webpack and it works fine.

**Comment by inteldon** [comment]
> I was able to get mup to work by running `C:\Users\user\AppData\Roaming\npm\mup.cmd init` to initialize mup, `C:\Users\user\AppData\Roaming\npm\mup.cmd setup` to set up for deployment and `C:\Users\user\AppData\Roaming\npm\mup.cmd deploy` to deploy my application.
> 
> Windows is a horror show. Not sure why I can't even set up my environmental variables anymore.

It worked for me when I used the regular `npm install mup --save` instead of a global install.

**Comment by marcivanmanalac** [comment]
> > I was able to get mup to work by running `C:\Users\user\AppData\Roaming\npm\mup.cmd init` to initialize mup, `C:\Users\user\AppData\Roaming\npm\mup.cmd setup` to set up for deployment and `C:\Users\user\AppData\Roaming\npm\mup.cmd deploy` to deploy my application.
> > Windows is a horror show. Not sure why I can't even set up my environmental variables anymore.
> 
> It worked for me when I used the regular `npm install mup --save` instead of a global install.

I can confirm this works. Thank you!
