### ISSUE TITLE
Sendgrid can't send emails

### ISSUE THREAD

**Issue by steinitz-zz** [zodern/meteor-up#778]
Hi,

Mup deployed without issue to a SoftLayer server running Ubuntu 16.04.3.  Bravo.  

However, Meteor doesn't seem to be able to send emails via SendGrid.  It works running on localhost.  I couldn't see anything relevant in the Softlayer logs nor the Docker container logs.  I also don't see any issues in the SendGrid reports.  Is there anything obvious that would be stopping it from working?

**Comment by takeshikriang** [comment]
I have the same problem with Postmark. Everything works on my Mac but stop working on server.

**Comment by steinitz-zz** [comment]
@Giantwannabe I had to add the SendGrid smtp string as the MAIL_URL in the mup environment like so:

```
    env: {
      ROOT_URL: 'http://x.y.z',
      MONGO_URL: 'mongodb://localhost/meteor',
      MAIL_URL: 'smtp://user:password@smtp.sendgrid.net:587',
    },
```

Then all was well.

**Comment by takeshikriang** [comment]
@steinitz Thanks, but it does not work for me. T_T

**Comment by ziedmahdi** [comment]
you need to open some ports in your firewall, usually port 25 for smtp.
