### ISSUE TITLE
tar: Malformed extended header: missing newline

### ISSUE THREAD

**Issue by ddaydd** [zodern/meteor-up#779]
Hi,

Failed to deploy from windows to ubuntu server
I suspect that this is because of the Windows line endings

```
Started TaskList: Pushing Meteor App
 - Pushing Meteor App Bundle to The Server
 - Pushing Meteor App Bundle to The Server: SUCCESS
 - Prepare Bundle
 x Prepare Bundle: FAILED

        -----------------------------------STDERR-----------------------------------
        tar: Malformed extended header: missing newline
        tar: Exiting with failure status due to previous errors
        -----------------------------------STDOUT-----------------------------------
        node-8.4.0-base: Pulling from abernix/meteord
```

**Comment by zodern** [comment]
@ddaydd could you please create an app that reproduces this error? When you do, please also [add the bundle and tar file](https://github.com/mafintosh/tar-fs/issues/21#issuecomment-341411869) to a `.build` folder in the app.

**Comment by pyrostrex** [comment]
@zodern, this happened to me too. My app was from `meteor create meteorapp`. Executed `meteor` once and then tried to use mup to deploy and this happened. `Windows 10 -> Ubuntu 17.10`. Same configuration as @ddaydd . `image: 'abernix/meteord:node-8.4.0-base'`

**Comment by idanwe** [comment]
Also happened to me on macos 10.12.6.

Tried to deploy meteor v1.6 with `mage: 'abernix/meteord:node-8.4.0-base'` and it failed.
with the following error message:
`docker: 'image' is not a docker command.`

Then, I tried to re-deploy the last deployed version of my app with meteor v1.5.2.2 and it failed too also more to the last mup version I used v1.3.2 and failed too :(
with the following error message:
`tar: Malformed extended header: missing newline`

Can I help with farther details?

**Comment by ddaydd** [comment]
@zodern the error is on a basic meteor application, do you need it anyway?

**Comment by zodern** [comment]
I'm haven't been able to reproduce it yet. @ddaydd the bundle and tar file created by `mup deploy` would help. You can get their location by running `mup deploy --cached-build`

**Comment by zodern** [comment]
I published mup@1.3.5-beta1 on npm. It uses a different package to archive the bundle (`node-tar`, which is used by npm and meteor). 

Please install it with `npm i -g mup@next` and see if you still encounter the error.

**Comment by ddaydd** [comment]
Deploy success !! Thanks :)

**Comment by pyrostrex** [comment]
Yep confirmed on my end that is a success too. Thanks!

**Comment by zodern** [comment]
Thanks for testing it. Mup 1.3.5 is no available with the fix.
