### ISSUE TITLE
Setup without reinstalling docker

### ISSUE THREAD

**Issue by SkinyMonkey** [zodern/meteor-up#783]
I would like to be able to deploy to a server that was partly configured already.

A simple local hack did the trick but it would be great to do without :)

Using an existing mongodb instance would be a good plus too!

**Comment by zodern** [comment]
It should support that. Mup only installs docker if it isn't already, or it is an old version that mup doesn't support.

If the mongodb instance was created by mup, it will use it, though it will upgrade/downgrade the mongo version to match what is in your config. If you created the mongodb instance, remove the `mongo` object from your config and set the `MONGO_URL` env variable to use it.

**Comment by SkinyMonkey** [comment]
Ah, sorry for the issue.
That might explain the other issues i have then.

Thanks a lot for the quick answer!
