### ISSUE TITLE
Application don't access MAIL_URL environment variable , Documentation required ?

### ISSUE THREAD

**Issue by enzolutions** [zodern/meteor-up#784]
Hi folks

## The Problem
I am trying to deploy my first meteor application and after fixing several issues there is only one remain related with environment variable **MAIL_URL**.

I remember not long time ago I see inside mup.js configuration file in environment settings the variable MAIL_URL next to MONGO_URL and ROOT_URL or maybe I am just dreaming.

Maybe is my misunderstanding or maybe is something that must be allocated in documentation pages.

After some debugging, I detected the environment viable $MAIL_URL is available inside docker container application, but not in meteor application.

### Added settings
I solved this issues configuring a variable inside the settings files I use to deploy

```
{
  "MAIL_URL": "smtps://MYENCODEDEMAIL:MYENCODEDPPAS@smtp.googlemail.com:465",
  "public": {},
 
}
```

Is important you set the email and password encoded, you could do that in code like
```
     let emailAccount = encodeURIComponent("myemail@example.com");
     let emailPassword = encodeURIComponent("MYPASSWORD");
```

because is not your will get an ugly error  due the "@" in your email and any special character in your password, you can do online using this website https://www.urlencoder.org/

If you don't do that, you will get this ugly error

```
[165.227.216.16]Exception while invoking method 'forgotPassword' URIError: URI malformed
[165.227.216.16]    at decodeURIComponent (<anonymous>)
[165.227.216.16]    at Url.parse (url.js:290:19)
[165.227.216.16]    at Object.urlParse [as parse] (url.js:96:5)
[165.227.216.16]    at makeTransport (packages/email.js:42:27)
[165.227.216.16]    at getTransport (packages/email.js:78:24)
[165.227.216.16]    at Object.Email.send (packages/email.js:172:19)
[165.227.216.16]    at AccountsServer.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:715:9)
[165.227.216.16]    at DDPCommon.MethodInvocation.forgotPassword (packages/accounts-password/password_server.js:546:12)
[165.227.216.16]    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
[165.227.216.16]    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
```

### Update Server code startup

I have to add a new file a server startup folder /server/email.jsx to set my MAIL_URL variable

```
import { Meteor } from 'meteor/meteor';

process.env.MAIL_URL = Meteor.settings.MAIL_URL;
```

Then in my deploy process, I do

```
$ mup deploy --settings settings.js 
```

Maybe is required to clarify in documentation that only ROOT_URL and MONGO_URL environment variables are available for meteor

**Comment by enzolutions** [comment]
Hi folks

Actually, after thinking a little bit more the problem wasn't the env variable wasn't accessible, the problem was the value wasn't encoded causing the URL for SMTP a bad formation.

I just set my environment variable to the encoded values and works like a charm.

A least, the workaround would work for someone else.

Great work BTW.

**Comment by enzolutions** [comment]
Actually, the same issue apply for MONGO_URL, if you use secure password and users with special characters 😄

**Comment by zodern** [comment]
> Actually, the same issue apply for MONGO_URL, if you use secure password and users with special characters 

Mup probably could automatically fix that. I added a card to the 1.4 project.

**Comment by enzolutions** [comment]
Awesome
