### ISSUE TITLE
[Deploy] Prepare Bundle: FAILED

### ISSUE THREAD

**Issue by thearabbit** [zodern/meteor-up#790]
Get error when `mup deploy`
```js
Prepare Bundle: FAILED

	-----------------------------------STDERR-----------------------------------
	der keyword 'SCHILY.nlink'
	tar: Ignoring unknown extended header keyword 'SCHILY.dev'
	tar: Ignoring unknown extended header keyword 'SCHILY.ino'
	tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
	tar: Ignoring unknown extended header keyword 'SCHILY.dev'
	tar: Ignoring unknown extended header keyword 'SCHILY.ino'
	tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
	tar: Ignoring unknown extended header keyword 'SCHILY.dev'
	tar: Ignoring unknown extended header keyword 'SCHILY.ino'
	tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
	tar: Ignoring unknown extended header keyword 'SCHILY.dev'
	tar: Ignoring unknown extended header keyword 'SCHILY.ino'
	tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
	The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
	Error response from daemon: Cannot link to a non running container: /mongodb AS /Samrith/mongodb
	Error: failed to start containers: Samrith
	-----------------------------------STDOUT-----------------------------------
	ERR!
	npm ERR! Failed at the libxmljs@0.18.7 install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2017-11-08T08_50_22_080Z-debug.log
	npm WARN meteor-dev-bundle@0.0.0 No description
	npm WARN meteor-dev-bundle@0.0.0 No repository field.
	npm WARN meteor-dev-bundle@0.0.0 No license field.
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2017-11-08T08_50_22_144Z-debug.log
```
Please help me

**Comment by robport** [comment]
+1
Note - this has happened since I upgraded to Meteor 1.6.

**Comment by karlreti** [comment]
+1

**Comment by robport** [comment]
Finally, resolved this for 1.6.  You need to update the docker image in mup.js.

docker: {
            // change to 'kadirahq/meteord' if your app is using Meteor 1.3 or older
            image: 'abernix/meteord:node-8.4.0-base',
        },

**Comment by sundarideaterics** [comment]
Started TaskList: Pushing Meteor App
[34.192.132.153] - Pushing Meteor App Bundle to The Server
[34.192.132.153] - Pushing Meteor App Bundle to The Server: SUCCESS
[34.192.132.153] - Prepare Bundle
[34.192.132.153] x Prepare Bundle: FAILED

        -----------------------------------STDERR-----------------------------------
        The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 126
        -----------------------------------STDOUT-----------------------------------
        6
        npm ERR!
        npm ERR! Failed at the bcrypt@1.0.2 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2017-11-11T09_44_36_855Z-debug.log
        npm WARN meteor-dev-bundle@0.0.0 No description
        npm WARN meteor-dev-bundle@0.0.0 No repository field.
        npm WARN meteor-dev-bundle@0.0.0 No license field.
        npm ERR! code ELIFECYCLE
        npm ERR! errno 126
        npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
        npm ERR! Exit status 126
        npm ERR!
        npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2017-11-11T09_44_36_876Z-debug.log


How to fix this error..pls help me

**Comment by sundarideaterics** [comment]
i am using meteor version METEOR@1.4.3.2
mup version : 1.3.3

**Comment by kodie** [comment]
Running into the same issue with METEOR@1.4.3.2 and MUP@1.3.5 :(

**Comment by kodie** [comment]
This is probably related to this: https://superuser.com/questions/318809/linux-os-x-tar-incompatibility-tarballs-created-on-os-x-give-errors-when-unt

Is everyone here that's running into the same issue using a Mac?

**Comment by kodie** [comment]
Okay so a couple of things that I have tried:

1.) Switching my node version from `v8.9.0` to `v6.12.0` using [nvm](https://github.com/creationix/nvm).
2.) Downgrading Meteor from `v1.6` to `v1.4.3.2` by running the following:
```
sudo rm /usr/local/bin/meteor
rm -rf ~/.meteor
curl https://install.meteor.com/?release=1.4.3.2 | sh
```
3.) Switching from `bsdtar` to `gtar` by running the following:
```
brew install gnu-tar
sudo unlink `which tar`
sudo ln -s `which gtar` /usr/bin/tar
```

and none of those seem to have fixed the problem. HOWEVER, after I deploy my app and get the failed error message, it seems my server goes down. After that happens, I run `mup restart` and it comes back up again and seems that everything deployed fine. 🤔

I am running OS X El Capitan.

**Comment by zodern** [comment]
Please post the output of `mup deploy --verbose`.

**Comment by thebarty** [comment]
Related but probably a different reason for the error https://github.com/zodern/meteor-up/issues/814
