### ISSUE TITLE
deploy fails - const { pause } <-- unexpected token

### ISSUE THREAD

**Issue by Ivokato** [zodern/meteor-up#794]
After updating to meteor 1.6, I get a run failure on the server when deploying,
does anyone else have this?

docker image: 'abernix/meteord:base'

`/built_app/programs/server/boot.js:50
	    const { pause } = require("./debug.js");
	          ^
`

Object destructuring or transpiling to es6 doesn't seem to work. I'm not sure if the issue is with mup or my particular setup (which is a standard meteor setup)

**Comment by stefanve** [comment]
I get 
```
SyntaxError: Unexpected token {
 at exports.runInThisContext (vm.js:53:16)

```
I think it has to do with the wrong node version. Node is packed in abernix/meteord:base I guess

**Comment by stefanve** [comment]
Try using 
`abernix/meteord:node-8.9.1-base`
That worked for me

**Comment by Ivokato** [comment]
Thank you so much, it's working!

**Comment by edwarddistel** [comment]
the answer from @stefanve is correct, but for those not using this Docker image you can upgrade (or downgrade) to 8.9.1 on the command line:

`sudo npm install n -g`
`sudo n 8.9.1`

**Comment by lucnat** [comment]
@ordinaryperson Do we have to do this on the server inside of the docker container? If so, how? I am using the `oleurud/meteor-graphicsmagick` because my app needs gm, but it doesn't work with meteor 1.6

**Comment by zodern** [comment]
@LucNaterop you can customize the docker image to use the correct version of node, or use a different base image and install graphicsmagick: http://meteor-up.com/docs#customize-docker-image
