### ISSUE TITLE
Deploy succeed but app not accessible

### ISSUE THREAD

**Issue by MuyBien** [zodern/meteor-up#795]
Hello !
I need some help here. I launch `mup setup` and `mup deploy` whithout any error but I cannot access to the app on the server... What am I doing wrong?

Thanks!

```bash
$ meteor --version
Meteor 1.5.2                                  
$ node -v
v9.1.0
$ npm -v
5.5.1
$ mup deploy --verbose
Building App Bundle Locally
                                                                            
Started TaskList: Pushing Meteor App
[54.37.xx.xx] - Pushing Meteor App Bundle to The Server
[54.37.xx.xx] - Pushing Meteor App Bundle to The Server: SUCCESS
[54.37.xx.xx] - Prepare Bundle
base: Pulling from abernix/meteord
c20dc0c5afeb: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
3858f3c461ce: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
94f04cfa6fe8: Already exists
0eb4eea50fdc: Already exists
2fd6c025a55b: Already exists
32823e805333: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
Digest: sha256:512bea3d03802e0dc03a6172c862db67c3451d5172a04bfc53edf97e6cbf7014
Status: Image is up to date for abernix/meteord:base
quiz-des-copinoux
Sending build context to Docker daemon  110.3MB
Step 1/6 : FROM abernix/meteord:base
# Executing 1 build trigger
 ---> Using cache
 ---> e400392cf52c
Step 2/6 : RUN mkdir /built_app
 ---> Using cache
 ---> a95789123edc
Step 3/6 : COPY ./ /built_app
 ---> Using cache
 ---> 7ee29842df22
Step 4/6 : ENV ROOT_URL=https://domain.com
 ---> Using cache
 ---> 1a3c2e9949bb
Step 5/6 : ENV MONGO_URL=mongodb://mongodb:27017/quiz-des-copinoux
 ---> Using cache
 ---> 1c2429f4b552
Step 6/6 : RUN cd  /built_app/programs/server &&     npm install --unsafe-perm
 ---> Using cache
 ---> 58fb90f98031
Successfully built 58fb90f98031
Successfully tagged mup-quiz-des-copinoux:build
quiz-des-copinoux
Total reclaimed space: 0B
[54.37.xx.xx] - Prepare Bundle: SUCCESS

Started TaskList: Configuring App
[54.37.xx.xx] - Pushing the Startup Script
[54.37.xx.xx] - Pushing the Startup Script: SUCCESS
[54.37.xx.xx] - Sending Environment Variables
[54.37.xx.xx] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[54.37.xx.xx] - Start Meteor
using image
removing last
Image mup-quiz-des-copinoux:latest
Volume
Removing docker containers. Errors about nonexistent endpoints and containers are normal.
quiz-des-copinoux
Error response from daemon: endpoint quiz-des-copinoux not found
Error: No such container: quiz-des-copinoux-frontend
Error response from daemon: endpoint quiz-des-copinoux-frontend not found
quiz-des-copinoux-nginx-letsencrypt
Error response from daemon: endpoint quiz-des-copinoux-nginx-letsencrypt not found
quiz-des-copinoux-nginx-proxy
Error response from daemon: endpoint quiz-des-copinoux-nginx-proxy not found
Finished removing docker containers
2777e04aef35f42bb85bdb8d5b452b4e45623691395338e949035ed14581898a
Ran abernix/meteord:base
Running autogenerate
--2017-11-12 23:44:27--  https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11745 (11K) [text/plain]
Saving to: ‘/opt/quiz-des-copinoux/config/nginx.tmpl’

     0K .......... .                                          100% 6.91M=0.002s

2017-11-12 23:44:27 (6.91 MB/s) - ‘/opt/quiz-des-copinoux/config/nginx.tmpl’ saved [11745/11745]

latest: Pulling from jrcs/letsencrypt-nginx-proxy-companion
Digest: sha256:5bb2e91c0503baf9357c3b5eee659a8b259cf65c49cbf86717fb1a4f2307c0ba
Status: Image is up to date for jrcs/letsencrypt-nginx-proxy-companion:latest
latest: Pulling from jwilder/nginx-proxy
Digest: sha256:c7ea3c006fc8cf36db714f2533e2f705732270fe83bcbf7f09ba76e4e260f86f
Status: Image is up to date for jwilder/nginx-proxy:latest
Pulled autogenerate images
754a8941620b9a7c66e7d00ac08e53a350604d97f81ec24966d3532a994d2205
Ran nginx-proxy
35e53a23644c5075832dc5c4fcbb5b34d3e454c18f2d9e030718235c8fd686e1
Ran jrcs/letsencrypt-nginx-proxy-companion
[54.37.xx.xx] - Start Meteor: SUCCESS
[54.37.xx.xx] - Verifying Deployment
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[54.37.xx.xx] - Verifying Deployment: SUCCESS
```

And here is my mup.js
```javascript
module.exports = {
  servers: {
    one: {
      host: '54.37.xx.xx',
      username: 'root',
      // pem: './path/to/pem'
      password: 'xxxxxx'
      // or neither for authenticate from ssh-agent
    }
  },

  app: {
    name: 'quiz-des-copinoux',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'https://domain.com',
      MONGO_URL: 'mongodb://localhost/meteor',
    },

    ssl: { // (optional)
      // Enables let's encrypt (optional)
      autogenerate: {
        email: 'mymail@gmail.com',
        // comma separated list of domains
        domains: 'domain.com'
      }
    },

    docker: {
      // change to 'abernix/meteord:node-8.4.0-base' if your app is using Meteor > 1.5
      image: 'abernix/meteord:base',
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};

```

**Comment by MuyBien** [comment]
It's maybe due to the nodeJS in my meteor: 
```
$ meteor node -e 'console.log(process.version);'
v4.8.4
```
Any help, or hint?
Thanks!

**Comment by MuyBien** [comment]
I updated to Meteor 1.6 and change the docker image to `abernix/meteord:node-8.4.0-base` but I still have a deploy with success but no application deployed :(

**Comment by mpowaga** [comment]
It seems like you are missing a PORT env variable. Try this:

```
env: {
  PORT: '80'
}
```

**Comment by MuyBien** [comment]
Hi @mpowaga!
It says in the docs that PORT is 80 by default if not specified.
Anyway I will try it.

**Comment by MuyBien** [comment]
When I set the port I have an error : 
`- "app.env" PORT can not be set when using ssl.autogenerate`

 But I made a `mup logs` and I see that there is an error while starting the app:
```
[54.37.xx.xx]Error: The babel-runtime npm package could not be found in your node_modules 
[54.37.xx.xx]directory. Please run the following command to install it:
[54.37.xx.xx]
[54.37.xx.xx]  meteor npm install --save babel-runtime
[54.37.xx.xx]
[54.37.xx.xx]    at babel-runtime.js (packages/babel-runtime.js:36:9)
[54.37.xx.xx]    at fileEvaluate (packages/modules-runtime.js:333:9)
[54.37.xx.xx]    at require (packages/modules-runtime.js:228:16)
[54.37.xx.xx]    at packages/babel-runtime.js:155:15
[54.37.xx.xx]    at packages/babel-runtime.js:166:3
[54.37.xx.xx]    at infos.forEach.info (/built_app/programs/server/boot.js:414:13)
[54.37.xx.xx]    at Array.forEach (<anonymous>)
[54.37.xx.xx]    at /built_app/programs/server/boot.js:413:9
[54.37.xx.xx]    at /built_app/programs/server/boot.js:463:5
[54.37.xx.xx]    at Function.run (/built_app/programs/server/profile.js:510:12)
[54.37.xx.xx]=> Starting meteor app on port:80
```

I did the `meteor npm install --save babel-runtime` but apparently I have already installed...
Any hint?

**Comment by MuyBien** [comment]
I made fresh install of the server and now the deploy is marked as success but I still can't open my app on the URL.
Now when I make a `mup logs` I only have one line with 
`[54.37.xx.xx]=> Starting meteor app on port:80`

I don't understand... :( I don't want to go back to mupx-letsencrypt (I manage to deploy with this one in another project) because it's a fork for letsencrypt but now mup handle it...

**Comment by rafahoro** [comment]
Did you solve this?

**Comment by MuyBien** [comment]
Nope.
Still getting all deploy markers as success but app is not accessible and the log just says `Starting meteor app on port:80`

I don't know what to look at anymore :(

**Comment by rafahoro** [comment]
Did you check http://meteor-up.com/docs.html#common-problems ?
May be the section Let’s Encrypt is not working

> Make sure your meteor.env.ROOT_URL starts with https://. Also, check that the DNS for all of the domains in ssl.autogenerate.domains is correctly configured to point to the server. Port 80 needs to be open on the server so it can verify that you control the domain.
> 
> You can view the Let’s Encrypt logs by running this command on the server:
> 
> docker logs <AppName>-nginx-letsencrypt
> Replace <AppName> with the name of the app

**Comment by rafahoro** [comment]
Im having the same issue. I don't know if related with the changes I did in mup.js, trying to get 2 different instance on the same server (reverse proxy, ssl). 
But having same problem, even when I roll back to previous mup.js. I even started a fresh instance on AWS, but no luck.

**Comment by MuyBien** [comment]
Yes I checked the common problems and I didn't found anything.
Maybe I can test whithout the Let's Encrypt configuration... I'll be back!

**Comment by rafahoro** [comment]
try deleting all the docker containers on your server:
`ls /opt/` make sure there are only docker containers here, before deleting *
` sudo rm -rf /opt/*`
restart your server
then from your client
`mup setup; mup deploy`
it helped me

**Comment by MuyBien** [comment]
Did you desactive the SSL option ?

**Comment by crstn210** [comment]
same problem here, no errors, and the page doesn't load at all it gives me 502 error

**Comment by mpowaga** [comment]
@MuyBien See what's the output of `docker port [your app name]` when you ssh into the server. It's likely that you don't have any port mappings. At least it was in my case.

**Comment by rafahoro** [comment]
No, but I deactivated the reverse proxy. 
This is my working config:

```

module.exports = {
  servers: {
    one: {
      host: 'prod.example.com',
      username: 'ubuntu',
      pem: '/example.pem'
    }
  },

  meteor: {
    name: 'prod',
    path: '../..', // as we run it from .deploy/xxxx, relative path to app

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
      server: 'https://prod.example.com'
    },

    env: {
      ROOT_URL: 'https://prod.example.com',
      MONGO_URL: 'mongodb://USER:PASS@XYZ.com:15740/example'
    },

    ssl: { // (optional)
      autogenerate: {
        email: 'support@example.com.ar',
        domains: 'prod.example.com'
      }
    },

    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/meteord:base',
    },
    deployCheckWaitTime: 60,
    enableUploadProgressBar: true
  },
};

```

But if I use reverse proxy, it doesn't work

Update, I tried this same config in a fresh-new server and is not working :(

**Comment by MuyBien** [comment]
@mpowaga here is the output. Seems good.
```
root@vps477638:~# docker port quiz-des-copinoux
80/tcp -> 0.0.0.0:80
```

**Comment by MuyBien** [comment]
I just tried something I did not try before... I can access the app throw the IP!!!!
So it's the DNS that is not working??

**Comment by MuyBien** [comment]
I added the SSL again (the SSL part in mup.js, the s to the https of the roor URL and the force-ssl package) and I cannot access the app again (event by IP). I get the error : `DNS_PROBE_FINISHED_NXDOMAIN`

:thinking: I don't understand!

**Comment by rafahoro** [comment]
I think is the nginx and/or letsencript docker container that is not working.  And I think that is related to the version. Need to check.
BTW: I tried again the config I posted a couple of hours ago in a fresh-new server and is not working :(

**Comment by jonmc12** [comment]
We are running into this issue as well.  Using Meteor 1.6.0, abernix/meteord:node-8.4.0-base, no ssl.  Our deploy is to an Azure VM - other docker containers work as expected in this same environment.

When running `docker run -dti --net=host <name>`  we can curl`0.0.0.0:80`

When running `docker run -dti  -p 80:80 <name>` we can not curl`0.0.0.0:80`

Looking at ifconfig, the IP addresses for `eth0` and `docker0`, can ping these, but not curl.  Seems the `docker0` inet address is not mapped to `0.0.0.0`.

**Comment by domparise** [comment]
I'm having the same problem. Might be related to the recent update to letsencrypt's ToS https://github.com/zodern/meteor-up/issues/802. both issues came up on the same day the ToS was updated

**Comment by MuyBien** [comment]
@domparise Even whithout the SSL part, I can't access my app with the domain name, only by IP...

**Comment by jonmc12** [comment]
fyi, using latest release of `jrcs/letsencrypt-nginx-proxy-companion`, we were successfully able to re-deploy, and access ports as expected.

Well, technically its only working when ssl is enabled.  I think there also may be some issues in the way that `start.sh` is generated when not using ssl, but thats likely another issue.

**Comment by MuyBien** [comment]
Some news about this issue?
I still cannot access my app with the app name only by the IP.

**Comment by edemaine** [comment]
@MuyBien Just catching up on this thread, but did you check that the domain is indeed registered? NXDOMAIN means that the domain doesn't exist, so either you don't have your DNS servers set right, or the domain isn't registered at all.

**Comment by MuyBien** [comment]
:thinking: I have the domain.com. I'm trying to deploy to a subdomain. I've already did that in another domain but with mupx-letsencrypt... Maybe it's different with mup. How can I know if the domain it's well configured?

**Comment by edemaine** [comment]
@MuyBien You can check whether the subdomain is registered correctly using a DNS lookup tool, e.g., https://mxtoolbox.com/DNSLookup.aspx

**Comment by MuyBien** [comment]
Thanks @edemaine !
Apparently it's not registered...
![image](https://user-images.githubusercontent.com/1921522/33998991-7ddc011e-e0e9-11e7-97a7-415038977ff3.png)

Sorry I forgot that for my other app, I added an entry for the subdomain in my server client interface.
I will check again to deploy with mup. Thanks @edemaine!! 😖

**Comment by MuyBien** [comment]
Just for info, it's working!
Thanks!
