### ISSUE TITLE
I can not link my mlab database address in meteor up

### ISSUE THREAD

**Issue by beriliox** [zodern/meteor-up#796]
I am trying to deploy my meteor application to digitalocean. I have set my mlab database address in the mup.js in the environment variables, but when I log into my mlab profile to manage my database. My application does not register the data in the mlab address but in another part that I do not know where. When I set my address in mup.js in the environment variables.

Where is this application inserting data? Because it is not doing it in my mlab address as I defined it before.

```
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '1.2.3.4',
      username: 'root',
      pem: '~/.ssh/id_carlo_digital'
      // password: 'server-password'
      // or neither for authenticate from ssh-agent
    }
  },

  app: {
    // TODO: change app name and path
    name: 'perfilesgs',
    path: '.',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://1.2.3.4',
      MONGO_URL: 'mongodb://user:pass@mlab_server:port/perfilesgs',
    },

    // ssl: { // (optional)
    //   // Enables let's encrypt (optional)
    //   autogenerate: {
    //     email: 'email.address@domain.com',
    //     // comma separated list of domains
    //     domains: 'website.com,www.website.com'
    //   }
    // },

    docker: {
      // change to 'kadirahq/meteord' if your app is using Meteor 1.3 or older
      image: 'abernix/meteord:base',
      prepareBundle: false
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};

```

**Comment by MarceloPrado** [comment]
What is the database name that you expected to appear on mLab? `perfilesgs`?

**Comment by beriliox** [comment]
@MarceloPrado  yes. just like that
![screen shot 2017-11-13 at 4 14 58 pm](https://user-images.githubusercontent.com/14999385/32744321-da0891a6-c88d-11e7-878b-a9aa38a17b02.png)

**Comment by beriliox** [comment]
I solved it removing this part:

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }

**Comment by zodern** [comment]
Mup can probably detect this and warn the user. I added a card to the 1.4 project: https://github.com/zodern/meteor-up/projects/3#card-5841575

**Comment by theshook** [comment]
@beriliox it is working fine? having the same trouble, thank you!

**Comment by zodern** [comment]
@theshook make sure the `mongo` object isn't in your config.

**Comment by theshook** [comment]
@zodern thanks! having another issue I don't know how to add SSL certificate on my server
