### ISSUE TITLE
[1.3.5] "wrong arguments"

### ISSUE THREAD

**Issue by nadeemja** [zodern/meteor-up#798]
Hi,

When doing `mup deploy`, I'm getting the following:

    Building App Bundle Locally
    to: wrong arguments
    toEnd: wrong arguments

**Comment by zodern** [comment]
Could you please try setting the `DEBUG` env variable to `mup*` and running again? That will show if this is happening during `meteor build` or when creating the archive.

**Comment by nadeemja** [comment]
Here you go :) 

  bash-3.2$ DEBUG=mup* mup deploy 
  mup:plugin-loader loading plugin mup-aws-beanstalk +0ms
  mup:plugin-loader plugin installed locally with mup +3ms
  mup:updates checking for updates +0ms
  mup:module:default exec => mup deploy +0ms
=> Setting up
=> Ensuring IAM Roles and Instance Profiles are setup
Building App Bundle Locally
  mup:module:meteor Build Path: /Users/Nadeem/Code/Meteor/Sembly +0ms
  mup:module:meteor Build Command:  meteor build --directory /var/folders/66/4twr7b_5773gsqx67dxmkm000000gn/T/mup-meteor-ede9e102-e491-47fc-a371-4b5cf7d0e9d1 --architecture os.linux.x86_64 --server-only +0ms
to: wrong arguments

toEnd: wrong arguments

=> Archiving Bundle
....

**Comment by zodern** [comment]
It looks like that is a warning by a meteor or a meteor package.
