### ISSUE TITLE
Deployment with reverse proxy success, iOS not connecting

### ISSUE THREAD

**Issue by BenjaminMerlynS** [zodern/meteor-up#806]
Hello,

I've deployed my app with mup setting up a reverse proxy (to force SSL) with a self signed SSL certificate. Everything in the browser is working fine. Only my iOS app does not seem to be able to connect to the server. 

When I removed to whole SSL and reverse proxy, the app connected without any problems... So there has to be a problem with the NGINX proxy?

**My mup.js config file:** 
`
       module.exports = {
         servers: {
         one: {
        // TODO: set host address, username, and authentication method
        host: 'SERVERIP',
        username: '***',
        // pem: './path/to/pem'
        password: '***'
        // or neither for authenticate from ssh-agent
      }
       },

    meteor: {
    // change app name and path
    name: 'KYOKO-prod',
    path: '/Users/merlyn/Documents/Coding work/KYOKO-dev',

    volumes: {
        // passed as '-v /host/path:/container/path' to the docker run command
        //'/mnt/storage/KYOKO/KYOKO-deploy': '/app',
        '/mnt/storage/KYOKO/KYOKO-media': '/media',
        '/mnt/storage/KYOKO/KYOKO-fonts': '/home/app/.fonts'
    },

    docker: {
        // Change the image to 'kadirahq/meteord' if you
        // are using Meteor 1.3 or older
        image: 'abernix/meteord:node-8.9.1-base',

        // lets you add/overwrite any parameter on
        // the docker run command (optional)
        args: [
            '--net domain-mongo-cluster',
            '--net bridge',
        ],

        // Only used if using your own SSL certificates.
        // Default is "meteorhacks/mup-frontend-server" (optional)
        imageFrontendServer: 'meteorhacks/mup-frontend-server',

        // lets you bind the docker container to a
        // specific network interface (optional)
        //bind: '127.0.0.1',

        // lets you add network connections to perform after run
        // (runs docker network connect <net name> for each network listed here)
        networks: [
            'domain-mongo-cluster'
        ]
    },
    servers: {
      one: {},
    },

    buildOptions: {
        serverOnly: false,
        server: 'https://DOMAIN.COM',
        buildLocation: '/path/',

    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'https://DOMAIN.COM',
      MONGO_URL: 'mongodb://DOMAIN-mongo1:27017/meteor?replicaSet=domain-mongo-set',
      MONGO_OPLOG_URL: 'mongodb://DOMAIN-mongo1:27017/local?replicaSet=domain-mongo-set',
        MOBILE_ROOT_URL: "https://DOMAIN.COM"
    },

    // Show progres s bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true,
    type: 'meteor',
      deployCheckWaitTime: 1400,
    },
    proxy: {
        domains: 'DOMAIN.COM,IPADDRESS',
        ssl: {
            crt: './server.crt', // this is a bundle of certificates
            key: './server.key', // this is the private key of the certificate
            forceSSL: true
        },
    },
    };`

**Does anybody have an idea?**

Thanks in advance !

**Comment by LarsBuur** [comment]
@BenjaminMerlynS: I have just deployed a server with reverse proxy and letsencrypt ssl and our iOS app is still working. 

I have both ROOT_URL and HOST set in env:{ROOT_URL:'https://domain.com', HOST:'domain.com'}

**Comment by zodern** [comment]
@BenjaminMerlynS Are you still having this problem?

If you are, please share the output of `mup logs --tail=40` and `mup docker ps`.
