### ISSUE TITLE
git info to environment variables

### ISSUE THREAD

**Issue by Slind14** [zodern/meteor-up#807]
Hi,
would it be possible for mup to include the git info (branch, tag, commit hash) in the meteor environment variables?

**Comment by zodern** [comment]
It would be possible to create a plugin or a hook that does. 

The hook would be similar to:

```js
function (api) {
  const config = api.getConfig();

  config.app.env.GIT_COMMIT = 'commit hash',

  api.setConfig(config);
}
```

**Comment by Slind14** [comment]
Thank you, so this would be this part of the doc, unless I'm mistaken?
http://meteor-up.com/docs.html#hooks-1
Which event would be best suited for this?

**Comment by zodern** [comment]
That is the documentation for adding hooks in a plugin. If you want to add the hook in your mup config, the documentation is at http://meteor-up.com/docs.html#hooks. The hook `pre.reconfig` would work.

**Comment by zodern** [comment]
I just remembered that one of my apps adds the commit in an env variable.

```js
// top of the config
var childProcess = require('child_process');

module.exports = {
  // ... rest of config
  meteor: {
    env: {
      SOURCE_VERSION: childProcess.execSync('git rev-parse HEAD').toString().trim()
    }
  }
}

**Comment by Slind14** [comment]
Thank you :)

**Comment by Slind14** [comment]
I totally forgot that the env var is only available on the server. Any chance that the settings can be patched the same way, so that it works with offline apps(once downloaded/updated)?

**Comment by zodern** [comment]
The docs for 1.4 will have an example of that: https://github.com/zodern/meteor-up/blob/dev/docs/docs.md#hooks

**Comment by eric-burel** [comment]
Hi, the command `git rev-parse HEAD` is not very robust, it does not find a `.git` folder on my machine when executed
Tagging @SachaG

**Comment by SachaG** [comment]
That's weird, it seems to work for me.
