### ISSUE TITLE
Cannot link to a non running container

### ISSUE THREAD

**Issue by themastersoda** [zodern/meteor-up#809]
Hello, i've been using mup without any issues for over a year now, but recently i've received an error during one of the routine deployments.

```
The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 254
        Error response from daemon: Cannot link to a non running container: /mongodb AS /myproject/mongodb
        Error: failed to start containers: myproject
```

My config has not been changed, im deploying to ubuntu 17.04 on digitalocean. As i said, deployments worked up until now, even today, so i'm really bummed about this issue.

**Comment by themastersoda** [comment]
More info: this error happens when mup is trying to start the application container. Mongo container is already running, so this error makes no sense. @zodern , do you have any ideas what's happening?
Here's the docker ps output:
```
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                                      NAMES
ed6c9bffb90a        mongo:3.4.1                                     "/entrypoint.sh mong…"   30 minutes ago      Up About a minute   127.0.0.1:27017->27017/tcp                 mongodb
7147fff3dd28        jrcs/letsencrypt-nginx-proxy-companion:latest   "/bin/bash /app/entr…"   20 hours ago        Up 19 hours                                                    myproject-nginx-letsencrypt
0f421e261f35        jwilder/nginx-proxy:latest                      "/app/docker-entrypo…"   20 hours ago        Up 19 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   myproject-nginx-proxy
```

**Comment by themastersoda** [comment]
Sorry for multiple comments, but this seems to be an even bigger issue.

Gave up trying to revive the server, so made a database backup and created a new droplet. Deploying to this new droplet yelds same results though:

```
Started TaskList: Pushing Meteor App
[xxx.xxx.xxx.xxx] - Pushing Meteor App Bundle to The Server
[xxx.xxx.xxx.xxx] - Pushing Meteor App Bundle to The Server: SUCCESS
[xxx.xxx.xxx.xxx] - Prepare Bundle
[xxx.xxx.xxx.xxx] x Prepare Bundle: FAILED

        -----------------------------------STDERR-----------------------------------
        Error response from daemon: No such container: myproject
        The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 254
```
Here's the docker ps -a:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                        PORTS                        NAMES
7a2157b2acaa        22886aac8590        "/bin/sh -c 'cd  /bu…"   10 minutes ago      Exited (254) 10 minutes ago                                heuristic_colden
274ff089d989        mongo:3.4.1         "/entrypoint.sh mong…"   34 minutes ago      Up 34 minutes                 127.0.0.1:27017->27017/tcp   mongodb
```
It seems that something prevents mup from creating container, but it does not stop proceeding further.

**Comment by zodern** [comment]
@themastersoda Is there any stdout output from Prepare Bundle? 

The `Error response from daemon: No such container: myproject` error is normal when the app is stopped or during the first deploy. I should probably add some output to make that more clear.

**Comment by themastersoda** [comment]
@zodern no significant output after this error whatsoever, however, the workaround is deploying from linux or windows subsystem for linux. Deploying straight from windows 10 seems to not work, but linux works every time. There was no more useful output in the console after this error appeared, the only thing that might be related is that the errors started popping up after trying to redeploy to server when i had a constantly crashing app there. After the endless crashes it could not finish bundle publishing operation, so this might be related to it. 

Since deploying from linux seems to have fixed the issue, i haven't tried deploying from windows after that.

About the error being expected when having a first deploy, how is it supposed to be normal when the deployment fails because of it? The meteor app container did not start and wasn't even created. I was not able to start it even when manually sshed into the server.

**Comment by AstonBraham** [comment]
So what was the fix please ?
I'm on linux but i'm facing that same issue

**Comment by themastersoda** [comment]
@AstonBraham in my case the fix was simply using linux for deployments.

**Comment by iAssureIT** [comment]
I am facing this issue on Ubuntu 18.04. 
I am getting this error when I shifted the project to a new Ubuntu server. 
On my earlier server and this new server, I have separate nodejs projects running, which use mongodb on port 27017. 

**Can someone please tell me what must be the issue and how to resolve it?** 


`
Started TaskList: Start Meteor                                                                                           
[xxx.xx.xx.xx] - Start Meteor                                                                                           
[xxx.xx.xx.xx] x Start Meteor: FAILED                                                                                                                                                                                                                           
------------------------------------STDERR------------------------------------                                            
Removing docker containers. Errors about nonexistent endpoints and containers are normal.                           
Error: No such container: myproject
Error response from daemon: endpoint myproject not found                                                         
Error: No such container: myproject-frontend                                                                     
Error response from daemon: endpoint myproject-frontend not found                                                
Error: No such container: myproject-nginx-letsencrypt                                                            
Error response from daemon: endpoint myproject-nginx-letsencrypt not found                                       
Error: No such container: myproject-nginx-proxy                                                                  
Error response from daemon: endpoint myproject-nginx-proxy not found                                             
Finished removing docker containers                                                                                       
docker: Error response from daemon: Cannot link to a non running container: /mongodb AS /myproject/mongodb. 
                                                                                                                                                                                                                                                               ------------------------------------STDOUT------------------------------------                                           
 using image                                                                                                        
 removing last                                                                                                            
 Image mup-myproject:latest                                                                                       
Volume                                                                                                                    b9bc1f562ce6b5ef56a6f0ee83c5308f35a89bef9a640b9a091c185be79a9a2d                                                                                                                                                                                          ------------------------------------------------------------------------------                              
`
