### ISSUE TITLE
"Verifying Deployment" fails when using "docker.bind"

### ISSUE THREAD

**Issue by lauff** [zodern/meteor-up#810]
When using docker.bind with an address different to "0.0.0.0" the deployment fails at "Verifying Deployment".

Looking into `command-handlers.js` at line starting with `list.executeScript('Verifying Deployment',` I can see that it passes the `deployCheckPort` of an changed port, but for the address it only checks whether a proxy was set, not what was changed with `bind.port`.

As a consequence the script tests `localhost` which fails.

**Comment by lauff** [comment]
I solved it by adding one line (marked with a comment) to `command-handlers.js`
(the below code below exists twice (for start and restart)

```javascript
  list.executeScript('Verifying Deployment', {
    script: api.resolvePath(__dirname, 'assets/meteor-deploy-check.sh'),
    vars: {
      deployCheckWaitTime: config.deployCheckWaitTime || 60,
      appName: config.name,
      deployCheckPort: config.deployCheckPort || config.env.PORT || 80,
      deployCheckPath: '',
      host: api.getConfig().proxy ? api.getConfig().proxy.domains.split(',')[0] : null,
      bind: api.getConfig().app.docker.bind ? api.getConfig().app.docker.bind : 'localhost' // consider bind address for deployment check
    }
  });
```

and also changing the `DEPLOY_CHECK_URL` in `mup\lib\plugins\meteor\assets\meteor-deploy-check.sh` to 

```javascript
DEPLOY_CHECK_URL=<%= `${bind}:${deployCheckPort}${deployCheckPath}` %>
```

(files are attached)
[changed files.zip](https://github.com/zodern/meteor-up/files/1492834/changed.files.zip)

**Comment by lauff** [comment]
submitted pull request https://github.com/zodern/meteor-up/pull/812

**Comment by zodern** [comment]
I merged your PR. Thank you.
