### ISSUE TITLE
Docker: Permission Denied Error

### ISSUE THREAD

**Issue by nloui** [zodern/meteor-up#816]
Hi there!

I'm running Meteor 1.6 // mup 1.3.6 // abernix/meteord:node-8.4.0-base image and am getting this error:

[X.X.X.X] x Prepare Bundle: FAILED
	
	-----------------------------------STDERR-----------------------------------
	bash: line 28: Dockerfile: Permission denied
	-----------------------------------STDOUT-----------------------------------
	node-8.4.0-base: Pulling from abernix/meteord
	Digest: sha256:XXXXXXXXXXXXXXXXXXXX
	Status: Image is up to date for abernix/meteord:node-8.4.0-base

	----------------------------------------------------------------------------

Was working until yesterday, so not sure what could be going on?

Thanks!

**Comment by nloui** [comment]
Fwiw - I was able to get it working by using mup 1.3.5, but hopefully there's a better forward moving fix!

**Comment by Slind14** [comment]
Same issue with 1.3.6

**Comment by mikkelking** [comment]
Same problem, I also discovered that the trailing slash on the path is necessary, eg

```
  meteor: {
    name: 'admin',
    path: '../../app/',
```

Reverting to 1.3.5 does fix it. I am working with Meteor 1.6. Spent a lot of time today messing with this

**Comment by bogdanrn** [comment]
same error. going back to 1.3.5 fixed it for me as well

**Comment by html5-ninja** [comment]
same

**Comment by stefanve** [comment]
Same here, permission denied. Downgrading to 1.3.5 helped

**Comment by elie222** [comment]
Got it working reverting to 1.3.3. A few hours gone. Always get headaches when I update MUP these days... Bit problematic.

**Comment by zodern** [comment]
I am working on a fix.

**Comment by zodern** [comment]
I haven't been able to reproduce the bug. I published 1.3.7 beta 0 with a possible fix.

Please install it with `npm i -g mup@next` and let me know if the problem is fixed. If it isn't, please share the output of `mup deploy --verbose` and the output from running this command on the server:`cd /opt/<app name>/tmp && ls -la`

**Comment by fschaeffler** [comment]
@elie222 got the same feeling too :/

**Comment by stefanve** [comment]
@fschaeffler and @elie222, there's a million things that can go wrong in a rather complex puzzle like MUP. Just make a it a routine to test directly after updating and rollback and report if it does not work. I am sure @zodern would like to have access to a huge test team and a QA group, but let's face it - we need this software and we get it for no money. Sometimes we need to put in hours though. We share our joy with the product with it's developer/s, the disappointments we carry alone.

**Comment by hanimay** [comment]
@zodern version 1.3.7 beta 0 works for me. Thanks for the quick fix :smiley:

**Comment by rooch84** [comment]
@zodern.  I have the same issue with 1.3.6, but only on Ubuntu 16.04 server running inside Docker.  It works fine on OSX.  

I can also confirm that 1.3.7 fixes the issue and works fine on Ubuntu.  Do you still want a verbose output?

**Comment by zodern** [comment]
@hanimay  and @rooch84 Thank you for trying it. I do not need the verbose output. 

I will publish 1.3.7 today.

**Comment by zodern** [comment]
1.3.7 is now available.

**Comment by fschaeffler** [comment]
@stefanve I agree that there can get a million things wrong. However, this issue described here isn't some kind of edge case, but the most import use case (a deployment). That makes it a perfect candidate for an automated test case, which runs before a version deployment.

**Comment by edemaine** [comment]
@fschaeffler The trouble with this bug was that it was somehow specific to our setups (maybe Linux distro?) so @zodern didn't see it his testing and couldn't reproduce it (as written above). Automated testing can only go so far... As users, we serve a more global testing role. It's not that hard for us to report bugs we encounter and downgrade meanwhile -- downgrading is one command. This is why we have versions.
