### ISSUE TITLE
Cloudflare SSH - Error 502 bad gateway on https

### ISSUE THREAD

**Issue by trevordowdle** [zodern/meteor-up#819]
For a little [background,](https://github.com/zodern/meteor-up/issues/612) I was having issues with WebSockets when using the autogenerate Let's encrypt ssl option available through MUP.

Yesterday I decided to let Cloudflare take care of the SSL for me in hopes that it would not have the same WebSocket issues.

I signed up for Cloudflare and turned on their SSL option.  Everything went smoothly and I was able to access my server via https.  Then I went to update the code in my project and do a mup deploy.  MUP timed out and I realized that my host was set to the non IP address, and the cloudFlare implementation was blocking it.  I changed my host to the IP and was able to deploy.

After this I went back to the server and to my dismay https was no longer working.  Cloudflare returns an Error 502 Bad gateway over https...  I know the server is running because if don't use https then the webpage loads just fine.

I've tried to track down the logs to get an idea of why this is happening but maybe I'm not looking in the right places because I haven't found the error in the logs.  I've even tried deleting the page from Cloudflare and re-adding it in order to simulate the same process that worked for me the first time but I'm still getting the bad gateway error :(

Any ideas or guidance on how to find and resolve this issue?

**Comment by trevordowdle** [comment]
I enabled let's encrypt autogenerate and then the Cloudflare ssh was able to take over and load the page.  I assumed that I would want the autogenerate turned off when using Cloudflare but perhaps that is not the case...

That said I am still getting the "WebSocket connection to 'wss://mydomain.com:3200/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED"

Could it be that I still get the error because I have the two SSH implementations overlapping?

**Comment by trevordowdle** [comment]
@alstephan Were you able to get the SSH on Cloudflare working without using the ssl autogenerate option in mup.js:


`
ssl: {
    autogenerate: { ...
    }
}
`

**Comment by ghost** [comment]
Using CloudFlare SSL now without issues. No Let's Encrypt certs configured manually.

502 errors usually means there's something wrong with the server or application. I'd try a fresh install and make sure your server is accepting SSL connections without issues (e.g. access and error logs could help).

**Comment by trevordowdle** [comment]
Thank you @alstephan, I was using a port not supported by Cloudflare.

It seems I getting closer, the client and server seem to actually be communicating, but now I am getting an error during the handshake.

WebSocket connection to 'wss://boldvue.com:2053/' failed: Error during WebSocket handshake: Unexpected response code: 525

Any thoughts on how to diagnose/resolve the handshake issue?

**Comment by ghost** [comment]
525 usually means your app is not set up to accept SSL requests. I'd check the server logs, if you have nginx on there I would also check those logs. I'd also try running the app without a proxy server (nginx), so a bare node app, since your nginx cipher suites may not be compatible with Cloudflare's.

Also if you're using strict mode for Cloudflare SSL try removing it (use just Full mode).

Perhaps this is obvious but also make sure you actually issued a cert with Cloudflare, since your origin server does not have a cert.

**Comment by trevordowdle** [comment]
@alstephan 

Thank you for the advice!  I finally got it working.  I did as you said and tried to get some websocket connections working via a node server.  Unfortunately I was still getting the 525 error.

So then I looked into node https server settings and saw that you need to authenticate with the certificate and key files. 

https://nodejs.org/api/https.html#https_https

I found those on the server at /opt/appname/certs/

Then it worked!  I'm sure this is pretty obvious for most people but just shows how clueless I am when it comes to servers and security.  Thank you for your guidance, you gave me just enough help to get the ball rolling on a solution.

Appreciate it!

**Comment by SachaG** [comment]
I'm also running into a 502 error with Cloudflare when using https (but http works fine). I would love more details about how exactly you fixed the issue, as I'm even more clueless than you when it comes to server stuff!

For example I don't even have an `/opt/appname/certs` directory?
