### ISSUE TITLE
Build bundle remotely

### ISSUE THREAD

**Issue by gsabran** [zodern/meteor-up#82]
Would it be possible to build the bundle remotely (and npm install remotely) ?
I'm not very aware of the pros and cons, but I run into [this issue](http://stackoverflow.com/questions/15809611/bcrypt-invalid-elf-header-when-running-node-app) because the bundle is made on mac and deploy on linux.

**Comment by madushan1000** [comment]
It shouldn't happen. When mup builds the meteor app, It uses the linux-x86_64 target (read this https://www.meteor.com/services/build). Make sure you are using either this version of mup or [mupx](https://www.npmjs.com/package/mupx). Old [mup](https://www.npmjs.com/package/mup) had bugs like this.

**Comment by gsabran** [comment]
Ah nice (I'm moving from old mup)

**Comment by madushan1000** [comment]
Great, If it works. You can close the issue :)
