### ISSUE TITLE
Error from daemon, no such container....

### ISSUE THREAD

**Issue by mannyhenri** [zodern/meteor-up#825]
When I used the following config deploying to digitalocean, I did a $ mup setup with no errors and then ran $ mup deploy and everything went well until it tried to prepare bundle...what am I missing here?

This is the error I'm getting with the following config when deploying... 
![ievle](https://user-images.githubusercontent.com/8015930/33838950-e23d5fa0-de5e-11e7-846d-152756aaafdb.png)
```
module.exports = {
  servers: {
   one: {
    host: 'xxx.xxx.xxx.xxx',
    username: 'root',
    pem: "~/.ssh/id_rsa"
  }
},

app: {
  name: 'hotel',
  path: '../hotel', 
  // this is my local path to the application root

servers: {
  one: {},
},

buildOptions: {
  serverOnly: true,
},

env: {
  ROOT_URL: 'http://xxx.xxx.xxx.xxx',
  MONGO_URL: 'mongodb://localhost/meteor',
},

docker: {
  image: 'abernix/meteord:base',
},

// Show progress bar while uploading bundle to server
// You might need to disable it on CI servers
enableUploadProgressBar: true
},

mongo: {
  version: '3.4.1',
  servers: {
    one: {}
   }
 }
};
```

Link to full code of the issue:
[https://stackoverflow.com/questions/47618191/using-mup-returned-a-container-error](https://stackoverflow.com/questions/47618191/using-mup-returned-a-container-error)

**Comment by AstonBraham** [comment]
Same here.. I really wonder why.
My app is based on Meteor 1.6

**Comment by zodern** [comment]
@mannyhenri and @AstonBraham are you still encountering this error?
