### ISSUE TITLE
graphicsmagick and phantomjs - new docker image

### ISSUE THREAD

**Issue by micktaiwan** [zodern/meteor-up#826]
My applications needs graphicksmagick and phantomjs for seo to work
1) I get a error: cfs:graphicsmagick could not find "graphicsMagic" or "imageMagic" on the system
2) view-source:http://localhost/?_escaped_fragment_= has a empty body (???)

My question is: how do I create a docker image that will be used by default when I deploy ?
Someone could point me to a tutorial ?
Thanks. Mickael.

**Comment by thebarty** [comment]
Hi man,
any progress? Right now I am struggeling with a similar issue: I need to have chromedriver installed and running BEFORE starting the app.

Maybe checking out the hooks can help you. I have played with something like this (DIRTY CODE, but you'll see what I mean)
```
const setupChromeCommandScript = `
  docker exec lc apt install wget -y;
  # install chromedriver (NOT necessary)
  # docker exec lc wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -;
  # docker exec lc sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >>    /etc/apt/sources.list.d/google.list';
  # docker exec lc apt-get install google-chrome-stable -y --force-yes
  # fix chromedriver "error while loading shared libraries"...
  docker exec lc apt-get install libglib2.0-dev -y --force-yes;
  docker exec lc apt-get install libnss3-dev -y --force-yes;
  docker exec lc apt-get install libgconf-2-4 -y --force-yes;
  docker exec lc apt-get install netcat -y --force-yes;
  docker exec lc apt-get update;
  docker exec lc chromedriver &>/dev/null &  # start in background and continue to use it in terminal;
  docker exec lc sleep 10; ps;
  docker exec lc curl -v http://127.0.0.1:9515/wd/hub/status  # check status of chrome;
  docker exec lc nc -zv localhost 9515  # check status of chrome;
  # docker exec lc PATH=/built_app/programs/server/npm/node_modules/chromedriver/lib/chromedriver:$PATH
  # docker exec lc google-chrome --version;
`

...

  hooks: {
    'post.deploy': {
      // SET UP CHROME so we can hopefully connect
      remoteCommand: setupChromeCommandScript,
    },
  },
```

**Comment by ddaydd** [comment]
See my answer on SO

https://stackoverflow.com/questions/47651328/meteor-up-mup-new-docker-image/47920666#47920666

**Comment by micktaiwan** [comment]
@thebarty unfortunately I still don't know how to create docker images based on an existing one to be reused in my apps. I guess I'll have to read more on Docker, but @ddaydd answer solved my most urgent problems, so that will be for later....

**Comment by zodern** [comment]
Since mup 1.4.4, it is now possible to customize the docker image: http://meteor-up.com/docs#customize-docker-image
