### ISSUE TITLE
Step 3/8 taking abnormally long time

### ISSUE THREAD

**Issue by brylie** [zodern/meteor-up#827]
When deploying a Meteor 1.6 app using meteor-up 1.3.6, there is an abnormal amount of delay (5-10 minutes) on step 3 of 8:

```
Finished Extracting
Creating Dockerfile
Finished creating Dockerfile
Building image
Sending build context to Docker daemon  352.3MB
Step 1/8 : FROM abernix/meteord:node-8.4.0-binbuild
 ---> e5c01572b179
Step 2/8 : RUN mkdir /built_app
 ---> Using cache
 ---> c84525bca07f
Step 3/8 : COPY ./ /built_app
```

The app was originally deployed using the `abernix/meteord:base` image, but seems to have significantly slower deployment times using the `abernix/meteord:node-8.4.0-binbuild` image. I am not completely certain that the Docker image is the problem, it just seems strongly correlated.

**Comment by thsowers** [comment]
I cannot say for certain if this is the cause, but I have been experiencing slower deployment times as well (Delay at "Preparing Bundle") since I switched to the `abernix/meteord:node-8.4.0-base` image

**Comment by jasongrishkoff** [comment]
I can also confirm that the "prepare bundle" stage takes quite a while -- roughly 10 minutes.

**Comment by brylie** [comment]
Is there a flag to add a timer to the sub-processes, so we can see how long each step takes? That might also be helpful for debugging purposes.

**Comment by zodern** [comment]
@brylie your bundle is over 352 MB large. Step 3 is coping it into the docker image. The prepare bundle step does slow down deployment, and slightly increases ram usage, but it does increase the reliability of deployments and makes failed deployments easier to debug.

[This](https://github.com/zodern/meteor-up/projects/3#card-4580347) might make it much faster when dependencies don't change between deployments.

The prepare bundle script is [here](https://github.com/zodern/meteor-up/blob/dev/src/plugins/meteor/assets/prepare-bundle.sh) if anyone has any suggestions on speeding it up.

**Comment by ziedmahdi** [comment]
@zodern I noticed that the old app container is stopped while/before the new image is prepared (by the prepare bundle script). I think if we only stop the app after the bundle is prepared it will reduce app downtime and it will make it easier to rollback to previous version if the image was not created or the container failed to run.

What do you think?

**Comment by zodern** [comment]
I would like to avoid stopping the container. This is the reason for the current behavior:

Without prepare bundle, it:
1) removes old container
2) Starts new container
3) `npm install` is run by docker image
4) App is started

Running the app and running `npm install` both can use a lot of ram, and only one happens at a time.

Prepare bundle replaces step 3, but uses more ram than step 3. The app is stopped during Prepare Bundle so there will be more ram available. Even with stopping the app, some servers don't have enough.

The container is always started again after prepare bundle finishes, [even if it failed](https://github.com/zodern/meteor-up/blob/dev/src/plugins/meteor/assets/prepare-bundle.sh#L10).



For now, I would like to continue to support servers as small as 512mb. The script would need to decide if it should stop the container or not.
Some ideas are (not all of them are good):
- It could look at how much ram is available.
- Look at how many native dependencies the app has
- It could also store if it ran out of ram during the last time it was run.
- If it decides to not stop the app, and it runs out of ram, it could run again with the app stopped

**Comment by ziedmahdi** [comment]
so basically the only problem is with memory. Knowing how much ram is available is possible, but knowing how much of ram the prepare bundle will take that may be a problem, and also we should look into swap memory.
I think a configuration option is not a bad solution, let the developer decides wether to run prepare bundle and keep the app running at the same time or not.
btw, what is the technical solution for no down time deployment? and does it have some memory/cpu requirements?

**Comment by timbrandin** [comment]
this should def be a config option, we cannot have it so that prepare bundle takes down all instances of the app before starting them up again, especially painful to witness when having multiple machines with same slow prepare bundle step.

**Comment by Floriferous** [comment]
This is starting to make our deployments with mup extremely painful, each deployment takes >30 minutes on our CI, and we're doing 3 of them each time in parallel costing us a lot of container time.

Plus, the added duration during which our websites are completely down is immense given that rolling deployments isn't available yet.

We're really feeling the need for more "production-quality" improvements in terms of performance and availability :)

**Comment by zodern** [comment]
Version 1.4.5 is now available which adds the option [`app.docker.stopAppDuringPrepareBundle`](http://meteor-up.com/docs#everything-configured). When enabled the downtime is only the amount of time it takes to create the docker container and start the app, which can be as low as a few seconds.

**Comment by zodern** [comment]
Mup 1.5 (#976) has a number of performance improvements. Two of them are related to Prepare Bundle:

1. When building the image during Prepare Bundle, it set each environment variable in a separate build instruction in the docker file, which resulted in a new layer for each environment variable. It now sets all of the environment variables in one instruction. One of mup's tests is 30 seconds faster due to this.
2. The `Start Meteor` task would wait 15 seconds after creating the docker container before verifying deployment. Since Prepare Bundle helps the app to start faster, the task now only waits 3 seconds when it is enabled.

**Comment by zodern** [comment]
With `mup 1.5`, Prepare Bundle will be faster. Also, it seems Docker is working on improving build performance, which will help with this.
