### ISSUE TITLE
sh: 31: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by mklueh** [zodern/meteor-up#830]
Hello,

I´m facing an error I cannot reproduce

OS: Windows 10
Meteor: 1.6

My mup.js is freshly generated with mup init, I only added the server credentials.

What I´ve tried so far:

- Reinstalling mup
- Deleting all configs and re-init mup

Which did not work

This is the error. What am I doing wrong?

> Started TaskList: Setup Docker
> [xxx.xx.xx.xx] - Setup Docker
> sh: 31: Syntax error: "(" unexpected
> [xxx.xx.xx.xx] x Setup Docker: FAILED

        
        -----------------------------------STDERR-----------------------------------
        sh: 31: Syntax error: "(" unexpected
        -----------------------------------STDOUT-----------------------------------
        ----------------------------------------------------------------------------

**Comment by mklueh** [comment]
This only happens with a separate user I´ve created for my application. With my main user it works

**Comment by zodern** [comment]
What is the default shell for that user?

**Comment by ferdiemcdaniel** [comment]
I am also experiencing this.

**Comment by archi0309** [comment]
try to change default bash for demouser in deploy server side.
$ sudo chsh -s /bin/bash demouser

**Comment by zodern** [comment]
In the last update, `mup status` will now warn if the default shell isn't bash.
