### ISSUE TITLE
How to set swap-file?

### ISSUE THREAD

**Issue by thebarty** [zodern/meteor-up#832]
Hi guys,

I ran into `out of memory` issues and just want to make sure that I am getting this right.

Is it correct that the best way to do it (using MUP) is to set the swap file in the Droplet itself, and NOT in the docker-containers?

So this is what I did in the droplet:
```
  fallocate -l 4G /swapfile  # allocate 4B on harddrive
  ls -lh /swapfile  # SHOW swap on harddrive
  chmod 600 /swapfile  # PERMISSIONS
  mkswap /swapfile  # MARK file as swapfile
  swapon /swapfile  # ENABLE swapfile for system
  swapon --show  # SHOW swap file
```

Those are the resources for your reference
https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04
https://forums.docker.com/t/docker-swap-space/3908

**Comment by zodern** [comment]
> Is it correct that the best way to do it (using MUP) is to set the swap file in the Droplet itself, and NOT in the docker-containers?

Yes
