### ISSUE TITLE
Proxy requires shared settings

### ISSUE THREAD

**Issue by edemaine** [zodern/meteor-up#836]
I just tried using reverse-proxy for the first time, with these settings:

```javascript
  proxy: {
    domains: 'coauthor2.csail.mit.edu',
    ssl: {
      crt: '....pem',
      key: '....key',
      forceSSL: true,
    },
  },
```

Here's the error message I got during `mup setup`:

```
Started TaskList: Start proxy
[coauthor2.csail.mit.edu] - Start proxy
[coauthor2.csail.mit.edu] x Start proxy: FAILED

        -----------------------------------STDERR-----------------------------------
        config/start.sh: line 7: /opt/mup-nginx-proxy/config/shared-config.sh: No such file or directory
        Error response from daemon: No such container: mup-nginx-proxy
        Error response from daemon: endpoint mup-nginx-proxy not found
        Error response from daemon: No such container: mup-nginx-proxy-letsencrypt
        Error response from daemon: endpoint mup-nginx-proxy-nginx-proxy not found
        docker: open /opt/mup-nginx-proxy/config/env.list: no such file or directory.
        See 'docker run --help'.
```

The fix was simple: add `shared` settings under proxy (and then run `mup proxy reconfig-shared` -- this doesn't seem to be implied by `mup setup` which was also confusing):

```javascript
  proxy: {
    domains: 'coauthor2.csail.mit.edu',
    ssl: {
      crt: '....pem',
      key: '....key',
      forceSSL: true,
    },
    shared: {
      clientUploadLimit: '0', // disable upload limit
    },
  },
```

I wanted to disable the `clientUploadLimit` anyway, so this is fine for my purposes, but maybe you want to avoid crashing when there's no `shared`, as the documentation calls it "Advanced configuration".

**Comment by edemaine** [comment]
Actually, I now wonder if it's just `mup proxy reconfig-shared` that fixed things.  I tried using the correct configuration on another server that was using mup-frontend-server, and I got the same error during `mup setup`:

```
Started TaskList: Setup Docker
[coauthor.csail.mit.edu] - Setup Docker
[coauthor.csail.mit.edu] - Setup Docker: SUCCESS

Started TaskList: Setup proxy
[coauthor.csail.mit.edu] - Setup Environment
[coauthor.csail.mit.edu] - Setup Environment: SUCCESS
[coauthor.csail.mit.edu] - Pushing the Startup Script
[coauthor.csail.mit.edu] - Pushing the Startup Script: SUCCESS
[coauthor.csail.mit.edu] - Cleaning Up SSL Certificates
[coauthor.csail.mit.edu] - Cleaning Up SSL Certificates: SUCCESS
[coauthor.csail.mit.edu] - Copying SSL Certificate Bundle
[coauthor.csail.mit.edu] - Copying SSL Certificate Bundle: SUCCESS
[coauthor.csail.mit.edu] - Copying SSL Private Key
[coauthor.csail.mit.edu] - Copying SSL Private Key: SUCCESS
[coauthor.csail.mit.edu] - Setup SSL Certificates for Domains
[coauthor.csail.mit.edu] - Setup SSL Certificates for Domains: SUCCESS

Started TaskList: Start proxy
[coauthor.csail.mit.edu] - Start proxy
[coauthor.csail.mit.edu] x Start proxy: FAILED
```

```
$ mup proxy reconfig-shared
The shared settings affect all apps using this reverse proxy.

Started TaskList: Configuring Proxy's Shared Settings
[coauthor.csail.mit.edu] - Sending shared variables
[coauthor.csail.mit.edu] - Sending shared variables: SUCCESS
[coauthor.csail.mit.edu] - Sending proxy environment variables
[coauthor.csail.mit.edu] - Sending proxy environment variables: SUCCESS
[coauthor.csail.mit.edu] - Sending let's encrypt environment variables
[coauthor.csail.mit.edu] - Sending let's encrypt environment variables: SUCCESS

Started TaskList: Start proxy
[coauthor.csail.mit.edu] - Start proxy
[coauthor.csail.mit.edu] - Start proxy: SUCCESS
```

It looks like `mup setup` didn't run `TaskList: Configuring Proxy's Shared Settings`.

**Comment by jwjordan** [comment]
I can confirm that simply running "mup proxy reconfig-shared" also fixed this problem for me.  Thanks for sharing!

**Comment by zodern** [comment]
This is fixed in mup 1.4. You can try the beta using the instructions in #870.

**Comment by john-guerra** [comment]
Just faced this same error when trying to add SSL support to an already running application. Running `mup proxy reconfig-shared` didn't help. I managed to fix the error by running 
```
mup reconfig
```
Leaving this here just in case finds this same issue

**Comment by domramirez** [comment]
Thanks, @john-guerra! All the documentation I saw (especially [Meteor Up SSL Docs](http://meteor-up.com/docs.html#ssl)) seemed to want me to run `mup setup` AND THEN `mup reconfig`. I guess running those in reverse order shook things loose.

**Comment by GraemeFulton** [comment]
for me i ran `# netstat -tulpn | grep :80` to see what's running on port 80..it was apache2, so i ran `sudo service stop apache2`...from there `mup setup` worked fine

**Comment by ojczeo** [comment]
I have the same issues.
`sudo netstat -tulpn | grep :80` has showed me that `apache2` is running as well as `nginx`/
I also have to disable it both, and also uninstalled `nginx` with `sudo apt-get purge nginx nginx-common`.
After resolving that `mup setup` and `mup deploy` works fine! 🚀 🚀 🚀

**Comment by LordA98** [comment]
Running `mup reconfig` before running `mup setup` solved my issue too.  Thanks!
