### ISSUE TITLE
App runs slowly with frequent error messages "net::ERR_CONNECTION_REFUSED"

### ISSUE THREAD

**Issue by Shelagh-Lewins** [zodern/meteor-up#842]
My server is running slowly and frequently fails to connect with error messages such as:

```
GET http://xxxx.xx.xx.xx/sockjs/info?cb=r92ietxcxz net::ERR_CONNECTION_REFUSED
GET http://xxxx.xx.xx.xx/favicon-32x32.png net::ERR_CONNECTION_REFUSED
```

Sometimes the page loads, sometimes it doesn't. If it does load, static images on pages sometimes appear, sometimes don't.

My app runs perfectly on the local machine; the problem only happens on the server.
This is an upgrade of a Meteor 1.2 app to Meteor 1.6.01. The database is not very large. Everything works fine on the current live 1.2 version; it's only the test upgrade server that shows a problem.

Meteor version: 1.6.0.1
Local node version: 8.9.2
Server: Digital Ocean droplet running Ubuntu 14.04.5 x 64
If I run `meteor mongo` in my project directory, I see `MongoDB shell version: 3.2.15`

mup.js
```
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: 'xxx.xx.xx.xx',
      username: 'root',
      pem: "~/.ssh/id_rsa"
      // password: 'server-password'
      // or neither for authenticate from ssh-agent
    }
  },

  app: {
    // TODO: change app name and path
    name: 'myapp',
    path: '.',

    servers: {
```
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://xxx.xx.xx.xx',
      MONGO_URL: 'mongodb://localhost/meteor',
    },

    // ssl: { // (optional)
    //   // Enables let's encrypt (optional)
    //   autogenerate: {
    //     email: 'email.address@domain.com',
    //     // comma separated list of domains
    //     domains: 'website.com,www.website.com'
    //   }
    // },

    docker: {
      image: 'abernix/meteord:node-8.9.3-base'
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};

Has anybody got any idea what might be causing this?

**Comment by zodern** [comment]
@Shelagh-Lewins sorry for not responding sooner. Are you still experiencing this problem?

**Comment by Shelagh-Lewins** [comment]
Hi, I gave up on Meteor-up and switched to Phusion Passenger.
