### ISSUE TITLE
Cannot see correct clientAddress 

### ISSUE THREAD

**Issue by stefanve** [zodern/meteor-up#844]
Normally when run outside docker, this.connection.clientAddress will give the clients IP adress, but using MUP it just gives me a private address: 172.x.x.x

Id there a way we can change that? Or is this something that that unique to my system?

**Comment by stefanve** [comment]
Am I really the only one that see a problem with this?

**Comment by zodern** [comment]
@stefanve what is your mup config?

**Comment by stefanve** [comment]
They are slightly different, but one production is:

`
module.exports = {
    servers: {
        one: {
            // TODO: set host address, username, and authentication method
            "host": "xxx.xxx.xxx.xxx",
            "username": "xxx"
        }
    },
    hooks:{

        'post.deploy': {
            remoteCommand: "/opt/pdftk-to-docker.sh"
        }
    },
    meteor: {
        name: 'XX',
        path: '../../',

        servers: {
            one: {}
        },

        buildOptions: {
            serverOnly: true
        },

        volumes: {
            '/opt/gtdocs/store': '/opt/gtdocs/store',
            '/opt/gtdocs/temp': '/opt/gtdocs/temp'
        },

        env: {
            ROOT_URL: 'https://www.xxx.xx',
            MONGO_URL: 'mongodb://localhost/meteor'
        },

       ssl: {

           autogenerate: {
               email: 'xx.xx@xx.com',

               domains: 'xx.xx.com, ' +
               'xx1.xx.com '
           }

       },


       docker: {
           // change to 'kadirahq/meteord' if your app is using Meteor 1.3 or older
           image: 'abernix/meteord:node-8.9.1-base'
       },

       // Show progress bar while uploading bundle to server
       // You might need to disable it on CI servers
       enableUploadProgressBar: true
   },

   mongo: {
       version: '3.4.1',
       servers: {
           one: {}
       }
   }
};

`

**Comment by jehartzog** [comment]
This is a Meteor configuration issue, although you do set the env variables inside the MUP config.

Set the [`HTTP_FORWARDED_COUNT`](https://docs.meteor.com/api/connections.html) env variable to the number of proxies you have in front of your Meteor app. If you are using MUP with reverse proxy, this is probably 1. If you are also using CloudFlare as a CDN/Proxy, then it's probably 2.

@zodern This would probably be a good thing to add to documentation, especially with the recent changes making the reverse proxy the default setting. I'd be happy to do a PR if you want it :D. I'm loving the work you're doing with MUP btw, keep it up!

**Comment by stefanve** [comment]
I will try that, thanks

**Comment by stefanve** [comment]
Worked perfectly, @jehartzog, thanks!

**Comment by zodern** [comment]
@jehartzog Thanks. A pr to update the docs would be appreciated.

**Comment by zodern** [comment]
`HTTP_FORWARDED_COUNT` probably could default to 1 when using the reverse proxy.
