### ISSUE TITLE
mup setup FAILS at asset docker-setup.sh

### ISSUE THREAD

**Issue by ferdiemcdaniel** [zodern/meteor-up#847]
`parsedVersion=( ${serverVersion//./ })`
![default](https://user-images.githubusercontent.com/21697529/34472449-d2af1722-ef9d-11e7-9697-92ba681fd9d5.png)

**Comment by stefanve** [comment]
I think you need to give us some more...

**Comment by zodern** [comment]
@ferdiemcdaniel make sure the default shell is bash.

**Comment by zodern** [comment]
`mup status` should check if the default shell is bash, and if it isn't show a warning.

**Comment by zodern** [comment]
>mup status should check if the default shell is bash, and if it isn't show a warning.

This will be added in the next update.

**Comment by MWPAWAR** [comment]
+1
