### ISSUE TITLE
Improvements to checking for updates

### ISSUE THREAD

**Issue by zodern** [zodern/meteor-up#850]
- [x] Reduce effect checks have on delay before starting mup command
- [x] support disabling checks with environment variable
- [x] Show updates for plugins

**Comment by mikkelking** [comment]
If you are not happy with the PR, I can look further into possibly porting the beta checking code into the update-notifier module, or providing a command line option to disable the check, or doing a spawn of the check like update-notifier does, or passing through the http_proxy environment variable to silent-npm-registry-client.

Please let me know what you think

**Comment by zodern** [comment]
mup@1.5.2-beta.6 will show updates for plugins.
