### ISSUE TITLE
Cannot install mup

### ISSUE THREAD

**Issue by bouchepat** [zodern/meteor-up#852]
This is what I get when I run:  npm install --global mup
Using node 8.9.4, npm 5.6.0

```
npm ERR! code E404
npm ERR! 404 Not Found: pinkie-promise@https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz
```

**Comment by codemers** [comment]
Same!

**Comment by zodern** [comment]
https://github.com/floatdrop/pinkie-promise/issues/4

**Comment by zodern** [comment]
https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by bouchepat** [comment]
This seems to be fixed now.
