### ISSUE TITLE
Cannot deploy - no such container

### ISSUE THREAD

**Issue by bouchepat** [zodern/meteor-up#853]
The setup runs fine, but htis is what I get when I try to deploy:

```
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[192.168.15.103] - Pushing Meteor App Bundle to the Server
[192.168.15.103] - Pushing Meteor App Bundle to the Server: SUCCESS
[192.168.15.103] - Prepare Bundle
[192.168.15.103] x Prepare Bundle: FAILED

        -----------------------------------STDERR-----------------------------------
        Error response from daemon: No such container: zeteor
        The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 254
        Error response from daemon: No such container: zeteor
        Error: failed to start containers: zeteor
        -----------------------------------STDOUT-----------------------------------
        ndle@0.0.0 No description
        npm WARN meteor-dev-bundle@0.0.0 No repository field.
        npm WARN meteor-dev-bundle@0.0.0 No license field.
        npm ERR! code ELIFECYCLE
        npm ERR! errno 254
        npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
        npm ERR! Exit status 254
        npm ERR!
        npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2018-01-06T22_20_49_745Z-debug.log

        ----------------------------------------------------------------------------
```

Running on windows: mup.cmd deploy

**Comment by zodern** [comment]
You can run `mup deploy --verbose` to see the full output from `npm install`.

**Comment by webmagnets** [comment]
neisen@neisen-PC:~/devel/scheduling-payroll/.deploy$ mup logs --tail=100
[45.32.204.114]Error response from daemon: No such container: 3fold-scheduling-payroll
neisen@neisen-PC:~/devel/scheduling-payroll/.deploy$ mup deploy --verbose
Building App Bundle Locally
                                                                            
Started TaskList: Pushing Meteor App
[45.32.204.114] - Pushing Meteor App Bundle to the Server
[45.32.204.114] - Pushing Meteor App Bundle to the Server: SUCCESS
[45.32.204.114] - Prepare Bundle
node-8.4.0-base: Pulling from abernix/meteord
Digest: sha256:04f44cf999da383d11de77027ced8b70818222c9890a405ce10803af3ee5a642
Status: Image is up to date for abernix/meteord:node-8.4.0-base
Error response from daemon: No such container: 3fold-scheduling-payroll
Finished Extracting
Creating Dockerfile
Finished creating Dockerfile
Building image
Sending build context to Docker daemon  96.13MB
Step 1/6 : FROM abernix/meteord:node-8.4.0-base
# Executing 1 build trigger
 ---> Using cache
 ---> c321ee80fd3a
Step 2/6 : RUN mkdir /built_app
 ---> Using cache
 ---> 2419023e1bd9
Step 3/6 : COPY ./ /built_app
 ---> Using cache
 ---> 47b3b9ce047f
Step 4/6 : ENV ROOT_URL=http://45.32.204.114
 ---> Using cache
 ---> 8044acdec7d3
Step 5/6 : ENV MONGO_URL=mongodb://mongodb:27017/3fold-scheduling-payroll
 ---> Using cache
 ---> c0a91f4c9269
Step 6/6 : RUN cd  /built_app/programs/server &&     npm install --unsafe-perm
 ---> Running in e4bcbdbb0271

> fibers@2.0.0 install /built_app/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /built_app/programs/server
> node npm-rebuild.js


> bcrypt@1.0.3 install /built_app/programs/server/npm/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

module.js:491
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/built_app/programs/server/npm/node_modules/.bin/node-pre-gyp:15:20)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-10T20_27_05_429Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-10T20_27_05_460Z-debug.log
The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
Error response from daemon: No such container: 3fold-scheduling-payroll
Error: failed to start containers: 3fold-scheduling-payroll
[45.32.204.114] x Prepare Bundle: FAILED
        
        -----------------------------------STDERR-----------------------------------
        Error response from daemon: No such container: 3fold-scheduling-payroll
        The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
        Error response from daemon: No such container: 3fold-scheduling-payroll
        Error: failed to start containers: 3fold-scheduling-payroll
        -----------------------------------STDOUT-----------------------------------
        above.
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2018-01-10T20_27_05_429Z-debug.log
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2018-01-10T20_27_05_460Z-debug.log
        
        ----------------------------------------------------------------------------

**Comment by webmagnets** [comment]
This worked for me:
I deleted the node_modules directory.
Then, `meteor npm update`
Then `mup setup`
Then `mup deploy`
