### ISSUE TITLE
Where is mongod.log

### ISSUE THREAD

**Issue by rgstephens** [zodern/meteor-up#855]
I see the `mup mongo logs` command but I want to try the [mtools](https://github.com/rueckstiess/mtools) package to troubleshoot and monitor mongo and it needs to read the `mongod.log` which I can't seem to find in or out of the container.

**Comment by zodern** [comment]
Mongo in the container logs to stdout, and docker saves that by default in json files. I could add an option to customize the docker options for the mongo container, which would allow you to change how logs are stored.
