### ISSUE TITLE
[SOLVED] [TypeError: Buffer.alloc is not a function] Unable to load plugin meteor

### ISSUE THREAD

**Issue by massimosgrelli** [zodern/meteor-up#857]
I installed mup and everything went well until I did `mup deploy` 
Then I got this error:
```
[TypeError: Buffer.alloc is not a function]
Unable to load plugin meteor
```
I tried `npm install` and `meteor npm` install but nothing changed.
I'm using Meteor 1.6.0.1

Any ideas?

PS: my code is not using Buffer

**Comment by massimosgrelli** [comment]
Updated node locally on my dev environment to version 8.9.3.
Then I updated the docker image to abernix 8.9.3 base. Now the bundle is created, but I have another problem during the verification phase " 0curl: (7) Failed to connect to localhost port 80: Connection refused". I will open a different issue for this case.

**Comment by zodern** [comment]
Mup 1.4 will have a better message when using an old version of Node that doesn't have `Buffer.alloc`.
