### ISSUE TITLE
SSH based authentication with sudo for Windows 10

### ISSUE THREAD

**Issue by thearabbit** [zodern/meteor-up#864]
I would like to deploy to `Window Local Server`.
1- Enable `ssh` access is OK
2- `sudo visudo` -> don't understand on Window
Please help me.

**Comment by stefanve** [comment]
There's no sudo in Windows. There is a similar thing in 'runas'
https://technet.microsoft.com/en-us/lib

Usually you do not have any SSH by default either, have you tried sunning 
`ssh localhost`
in a terminal window?
