### ISSUE TITLE
mup setup : Error: Timed out while waiting for handshake

### ISSUE THREAD

**Issue by rashmimhatre100** [zodern/meteor-up#865]
Hi All,
Problem here is when I am trying to run command mup setup
there is  error...
Started TaskList: Setup Docker
[54.186.xx.xxx] - Setup Docker
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:138:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

My mup.js file looks like,
 module.exports = {
servers: {
one: {
host:'54.186.xx.xxx',
username: 'ubuntu',
pem: '~/.ssh/mypem.pem'
}
},
app: {
name: 'myapp',
path: '/var/www/meteor/myapp',
servers: {
one: {},
},
buildOptions: {
serverOnly: true,
},
env: {
ROOT_URL: 'http://ec2-54-186-xx-xxx.us-west-2.compute.amazonaws.com',
MONGO_URL: 'mongodb://127.0.0.1:27017/myapp',
PORT: 3027,
},

docker: {
image: 'abernix/meteord:node-8.4.0-base',
},
deployCheckWaitTime : 60,
enableUploadProgressBar: true
},
mongo: {
oplog: true,
port:27017,
version: '3.4.1',
servers: {
one: {}
}
}
};

Meteor version is 1.6.
Thanks in advance!

**Comment by Lucbug** [comment]
See https://github.com/zodern/meteor-up/issues/603#issuecomment-359283445
