### ISSUE TITLE
debugOnly flag being ignored with MeteorToys

### ISSUE THREAD

**Issue by ghost** [zodern/meteor-up#869]
I use MeteorToys for developing and don't want it to deploy to the live site. It is supposed to be ignored when building the production package however it's not. It appears as though it is ignoring the debugOnly flag. 

There are a few people hitting this problem, however, I haven't been able to find a solution. 

Any guidance would be appreciated.

**Comment by ghost** [comment]
See answer here [https://github.com/MeteorToys/meteor-devtools/issues/106#issuecomment-361756170](url) .

You have have to change the debug settings to false. `debug: false`

**Comment by zodern** [comment]
I updated the docs for the next version to better explain the debug option. Also, I set it to false in all of the example configs.
