### ISSUE TITLE
can't use relative path (from home) for pem

### ISSUE THREAD

**Issue by gsabran** [zodern/meteor-up#87]
doing 

```
one: {
      host: 'ip',
      username: 'ubuntu',
      pem: '~/.ssh/mykey.pem',
    },
```

fails with `Error: ENOENT: no such file or directory, open '/pathTo.deploy/~/.ssh/mykey.pem'`, because this is the output of `path.resolve` (from https://github.com/kadirahq/meteor-up/blob/master/lib/mup-api.js#L105)

**Comment by madushan1000** [comment]
Yes, `~` is a bash-specific way of referring to  the home directory. `path.resolve` doesn't support it. So doesn't mup.

**Comment by gsabran** [comment]
All right. What about using https://github.com/sindresorhus/os-homedir ?

**Comment by madushan1000** [comment]
If you can send a PR with the logic, I'm happy to merge it :)

**Comment by gsabran** [comment]
Cool, will do

**Comment by mariusglauer** [comment]
You can also just use

```
var privateKey = path.join(process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME'], '.ssh', 'id_rsa');
```
