### ISSUE TITLE
After Deploying via MeteorUp, App doesn't let login; Login forbidden

### ISSUE THREAD

**Issue by Prospus-AnimeshSharma** [zodern/meteor-up#873]
Hi.

I have an app running fine on my localhost server. I deployed the app using MeteorUp on an ubuntu server. The app is loading login page but not letting user login. I’ve used “useraccounts:bootstrap” package. Login attempt throws error: Login forbidden.

Please suggest what could be wrong there?

**Comment by zodern** [comment]
The app uses a different database on the server, and it doesn't have your account.
