### ISSUE TITLE
Need to setup SSL on app running on port 3001

### ISSUE THREAD

**Issue by dev5-CloudNine** [zodern/meteor-up#875]
Hello there.
My application is running on my own server on port 3001.
demo.magicurehealthcare.com:3001

I want to set up SSL to this address, so that I can run it on https://demo.magicurehealthcare.com:3001/

The following is my mup.js configuration:

module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '192.168.2.191',
      username: 'myUserName',
      // pem: './path/to/pem'
      password: 'myPassword'
      // or neither for authenticate from ssh-agent
    }
  },

  proxy: {
    domains: 'demo.magicurehealthcare.com',
    ssl: {
      letsEncryptEmail: 'yashwanth.sagar@magicurehealthcare.com'
    }
  },

  app: {
    // TODO: change app name and path
    name: 'app',
    path: '.',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      PORT: 3001,
      ROOT_URL: 'https://192.168.2.191',
      MONGO_URL: 'my_mongo_url_here'
    },

    docker: {
      // change to 'abernix/meteord:base' if your app is using Meteor 1.4 - 1.5
      image: 'abernix/meteord:node-8.4.0-base',
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  }
};

**Comment by zodern** [comment]
You can change the ports using `proxy.shared`. The docs for it are [here](http://meteor-up.com/docs#advanced-configuration).

**Comment by dev5-CloudNine** [comment]
Okay, I've added the httpsPort in `proxy.shared` and pointed it to port 3001. And when I mup reconfig proxy-shared, I get the following error:

Started TaskList: Configuring Proxy's Shared Settings
[192.168.2.191] - Sending shared variables
[192.168.2.191] - Sending shared variables: SUCCESS
[192.168.2.191] - Sending proxy environment variables
[192.168.2.191] - Sending proxy environment variables: SUCCESS
[192.168.2.191] - Sending let's encrypt environment variables
[192.168.2.191] - Sending let's encrypt environment variables: SUCCESS

Started TaskList: Start proxy
[192.168.2.191] - Start proxy
[192.168.2.191] x Start proxy: FAILED
	
	-----------------------------------STDERR-----------------------------------
	Error response from daemon: endpoint mup-nginx-proxy not found
	Error: No such container: mup-nginx-proxy-letsencrypt
	Error response from daemon: endpoint mup-nginx-proxy-nginx-proxy not found
	docker: Error response from daemon: driver failed programming external connectivity on endpoint mup-nginx-proxy (d951dd1748af2e687b4fb1e28b8b0de07832e9a24f6bfc6093a4518932373b5a): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.
	-----------------------------------STDOUT-----------------------------------
	mup-nginx-proxy
	Removed mup-nginx-proxy
	Removed mup-nginx-proxy-letsencrypt
	latest: Pulling from jrcs/letsencrypt-nginx-proxy-companion
	Digest: sha256:68adf23860109597c0dc2f5302f05e7f42342bf586a1a439af0dcf632223e5a8
	Status: Image is up to date for jrcs/letsencrypt-nginx-proxy-companion:latest
	Using default tag: latest
	latest: Pulling from jwilder/nginx-proxy
	Digest: sha256:41506b2095779e6e64f34e26ccba35cb3668ee56a735cd740ac8c183af583294
	Status: Image is up to date for jwilder/nginx-proxy:latest
	Pulled jwilder/nginx-proxy and jrcs/letsencrypt-nginx-proxy-companion
	b98d3e07785a8ed04d96499152dacd0e727da31e6bbc0210f4a32a6f492bb69c
	----------------------------------------------------------------------------
Do I have to configure nginx to setup SSL? Point me what I'm doing wrong.

**Comment by zodern** [comment]
I am not able to reproduce. There probably was something else running on the server using port 80.
