### ISSUE TITLE
Deploying with SSL does not fail but accessing with https:// is not possible

### ISSUE THREAD

**Issue by Apollinaire** [zodern/meteor-up#880]
I followed the two ways to setup SSL from the docs, [without proxy first](http://meteor-up.com/docs.html#ssl-support), then [with reverse proxy.](http://meteor-up.com/docs.html#reverse-proxy)

Both returned no errors through the console, when running mup setup, then mup deploy. But when I go to my url i'm not redirected to https, though I have configured `forceSSL: true` , connection is refused on https, it's not refused on http, but it does not work due to network errors (app is trying to fetch resources from an https endpoint). 

I have managed to make it work without ssl, but it's not a production-viable option obviously.

my mup.js file: 
```javascript
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: "123.123.123.123",
      username: "xxxx",
      // pem: './path/to/pem'
      password: "xxxx"
      // or neither for authenticate from ssh-agent
    }
  },

  app: {
    // TODO: change app name and path
    name: "Platform",
    path: "../",

    servers: {
      one: {}
    },

    buildOptions: {
      serverOnly: true
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: "https://mydomain.tech",
      MONGO_URL: "mongodb://localhost/meteor"
    },

    // ssl: { // (optional)
    //   // Enables let's encrypt (optional)
    //   autogenerate: {
    //     email: 'my.own@email.tech',
    //     // comma separated list of domains
    //     domains: 'mydomain.tech,www.mydomain.tech'
    //   }
    // },

    docker: {
      // change to 'abernix/meteord:base' if your app is using Meteor 1.4 - 1.5
      image: "abernix/meteord:node-8.4.0-base"
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    version: "3.4.1",
    servers: {
      one: {}
    }
  },

  proxy: {
    domains: "mydomain.tech,www.mydomain.tech",
    ssl: {
      letsEncryptEmail: "my.own@email.tech",
      forceSSL: true
    }
  }
};
```

I tried various times with `mup setup`, `mup reconfig`, `mup proxy reconfig-shared` but could not get stuff working. 
Any idea? 
My local machine is Ubuntu 16.04, my server is an Ubuntu 16.04 VM on Azure Cloud. I'm using Meteor 1.6.1

**Comment by zodern** [comment]
I am releasing 1.4 today, which fixed some bugs with the reverse proxy and makes it easier to troubleshoot problems like this.

**Comment by Apollinaire** [comment]
Great! I'll wait until tomorrow then and if my problems are solved i will close the issue, if not i'll come back to you here. 
Thanks for the awesome work on mup :+1:

**Comment by Apollinaire** [comment]
Hi again @zodern , 
I think i figured out part of the problem, it came from forceSSL:true, and from some strange behavior between azure public ip, azure dns name and my namedomain provider; I couldn't figure out which domain to put in ROOT_URL, in proxy.domains, and if i should set my namespace redirect to the ip or the azure dns. Anyway, i'll move out of mup and will setup nginx&mongo by hand, this way i feel like i have more control than with containers. 
I'm closing the issue
