### ISSUE TITLE
Verifying deployment fails on contabo server

### ISSUE THREAD

**Issue by brmk** [zodern/meteor-up#881]
Hello,

I am not sure if it related to Meteor Up. I already have deployed a lot of applications using this tool, but currently, I am struggling with a server hosted on contabo.
I think that there is something with firewall, but can it be enhanced somehow? The app is accessible in the browser for some time during the verification and after the error is thrown, it gets killed. Any ideas how to prevent this happening?

the error is 

>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> 	                                 Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 172.17.0.3 port 3000: Connection refused

Here is my mup.js:

```

module.exports = {
  servers: {
    one: {
      host: *host*
      username: 'root',
      pem: '~/.ssh/id_rsa'
    }
  },

  app: {
    name: 'backend',
    path: '.',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://*host*:3000',
      MONGO_URL: 'mongodb://localhost/meteor',
      PORT: 3000
    },

    docker: {
      //I also tried to use abernix/meteord:node-8-base
      image: 'abernix/meteord:node-8.9.3-base',
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
  },
  meteor: {
    enableUploadProgressBar: true,
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  },

};

```

Thanks guys for the awesome tool!

mup@ mup@1.4.0-beta5

**Comment by brmk** [comment]
switched back to mup@1.3.5 and now it works :)

**Comment by tsangwailam** [comment]
I also got this error in 1.4.0. Is it a bug?
