### ISSUE TITLE
Proxy slow to (re)start

### ISSUE THREAD

**Issue by edemaine** [zodern/meteor-up#882]
With the new proxy, the "Prepare Bundle" step during `mup deploy` seems to take down the proxy, and it doesn't restart until the next step (which for me takes multiple minutes).  I believe the old proxy restarted quickly, so I immediately got a "502 Bad Gateway" error when trying to load `https://myserver`.  I now only get "502 Bad Gateway" briefly while the new Meteor server starts up.

Is there a way to fix this?  It makes deploying new code more embarrassing... (once I succeed in customizing the Bad Gateway message)

**Comment by edemaine** [comment]
FYI, I got the custom Bad Gateway message working as follows:

```
  proxy: {
    ...
    nginxServerConfig: 'proxy.config'
  }
```

with this `proxy.config`:

```
error_page 502 /502.html;
location /502.html {
  add_header Content-Type text/html;
  return 502 '<html>
...arbitrary HTML, but careful not to use single quotes...
</html>';
}
```

Let me know if you'd like this in a documentation PR. Or feel free to add it yourself.

**Comment by zodern** [comment]
I am going to close this in favor of #877.
