### ISSUE TITLE
Prepare Bundle: FAILED

### ISSUE THREAD

**Issue by mattmedroso** [zodern/meteor-up#884]
Hi @zodern, i badly need your help! This is the verbose output when I try to deploy to my server: 

npm ERR! Invalid version: "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-20T01_23_33_369Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-20T01_23_33_468Z-debug.log
The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1

	
	      ------------------------------------STDERR------------------------------------
	      The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
	
	      ------------------------------------STDOUT------------------------------------
	      im-newlines
	nan@2.4.0 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/nan
	node-gyp@3.4.0 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/node-gyp
	nopt@3.0.6 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/nopt
	npmlog@3.1.2 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/npmlog
	set-blocking@2.0.0 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/set-blocking
	osenv@0.1.3 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/osenv
	os-homedir@1.0.1 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/os-homedir
	os-tmpdir@1.0.1 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/os-tmpdir
	path-array@1.0.1 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/path-array
	request@2.74.0 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/request
	node-uuid@1.4.7 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/node-uuid
	oauth-sign@0.8.2 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/oauth-sign
	qs@6.2.1 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/qs
	stringstream@0.0.5 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/stringstream
	tough-cookie@2.3.1 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/tough-cookie
	tunnel-agent@0.4.3 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/tunnel-agent
	tar@2.2.1 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/tar
	node-sass@3.8.0 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/node-sass
	sass-graph@2.1.2 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/sass-graph
	yargs@4.8.1 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/yargs
	os-locale@1.4.0 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/os-locale
	require-directory@2.1.1 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/require-directory
	require-main-filename@1.0.1 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/require-main-filename
	which-module@1.0.0 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/which-module
	window-size@0.2.0 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/window-size
	y18n@3.2.1 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/y18n
	yargs-parser@2.4.1 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/yargs-parser
	camelcase@3.0.0 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/yargs-parser/node_modules/camelcase
	tweetnacl@0.13.3 /built_app/programs/server/npm/node_modules/meteor/lookback_emails/example/node_modules/tweetnacl
	npm ERR! Invalid version: "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz"
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2018-02-20T01_23_33_369Z-debug.log
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2018-02-20T01_23_33_468Z-debug.log

**Comment by mattmedroso** [comment]
But before these logs I have this error log for node-sass. I don't know if this is somewhat connected:

Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/linux-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

**Comment by zodern** [comment]
Those are interesting errors, and the normal causes seem to not be happening. Try removing `node_modules` and running `meteor npm install` before deploying again..

**Comment by mattmedroso** [comment]
Hi @zodern! I didn't know what happened but my setup got fixed miraculously. All I did in the server was a simple 'sudo apt-get update'. I'll close this issue thank you.
