### ISSUE TITLE
Issue to deploy Meteor app with 1.4

### ISSUE THREAD

**Issue by marcoschwartz** [zodern/meteor-up#887]
Hello,

First off thanks so much for maintaining this project, it's awesome!

I just updated to 1.4 and since then can't deploy my app anymore, it results in:

curl: (7) Failed to connect to 172.17.0.3 port 3000: Connection refused

Any idea of this? I didn't change anything, I just reverted back to 1.3.6 for now and it works like a charm.

**Comment by zodern** [comment]
Could you please share your mup config?

**Comment by ipstas** [comment]
Same here. 1.4 and 1.4.1 tries to connect to 172.17.0.3 and fails
1.3.6 works

Config:
`module.exports = {
	servers: {
		one: {
			"host": "stg.graffitiover.com",
			"username": "root",
		}
	},

	meteor: {
		name: 'graffiti-stg',
		path: '/srv/www/meteor/graffiti-meteor',
		volumes: {
			'/localfiles':'/localfiles'
		},
		servers: {
			one: {}
		},
		buildOptions: {
			server: 'https://stg.graffitiover.com:443', // your app url for mobile app access (optional)
			serverOnly: true, // skip building mobile apps, but still build the web.cordova architecture
			debug: true,
			cleanAfterBuild: true, // default
			allowIncompatibleUpdates: false //adds --allow-incompatible-updates arg to build command (optional)
		},
		env: {
			PORT: '8081',
			ROOT_URL: 'https://stg.graffitiover.com',
			MONGO_URL: 'mongodb://mongodb/graffiti',
			MAIL_URL: 'smtp://172.17.0.1:25',
			//host should be set for sparkpostmail
			METEOR_ENV: 'staging'
		},
		docker: {
			//image: 'abernix/meteord:base',
			image: 'abernix/meteord:node-8.9.1-base',
			args: [
				'--link=mongodb:mongodb'
			],

		},

		deployCheckWaitTime: 80,
		enableUploadProgressBar: true
	},
	
	mongo: {
	 oplog: true,
	 port: 27017,
	 servers: {
		one: {}
	 },
	},

};
`

**Comment by marcoschwartz** [comment]
Sure, here it is (with IP and app info removed):

module.exports = {
  servers: {
    one: {
      host: 'xx.xx.xx.xx',
      username: 'root',
      pem: "/Users/xx/.ssh/id_rsa"
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'xx',
    port: 3000,
    path: '../',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'https://xx.io',
      MONGO_URL: 'mongodb://localhost/meteor',
      PORT: 3000,
      METEOR_SKIP_NPM_REBUILD: 1
    },
    docker: {
      image: 'abernix/meteord:node-8.9.3-base',
    },
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};

**Comment by bogdanrn** [comment]
i get the same error with: `Failed to connect to 172.17.0.13 port 3009`

**Comment by bogdanrn** [comment]
logging in to my machine and doing `curl 172.17.0.13` returns the correct output, even if the app is set to run on port 3009 (in my case), the docker network interface works on port 80 it seems

**Comment by bogdanrn** [comment]
I found a fix for this problem. By default, the docker image works on port 80 (as i found [here](https://github.com/zodern/meteor-up/blob/185342835ea354097cb8435e50dc0369ee8df82a/src/plugins/meteor/command-handlers.js#L243)). My app was configured to run on port `3009`.

The new verify deployment function takes the network interface directly from docker. Docker was accessible at local_ip:80. The verify function instead of checking `local_ip:image_port`, checks for `local_ip:meteor_port`. You can use this temp fix to get your builds going. Even after the patch, I don't think it will matter if you leave it like this in your config. 

```
module.exports = {
  ....
  "meteor": {
     ....
    "docker": {
      "imagePort": 3009
    },
    "env": {
      "PORT": "3009",
       ....
     }
    ....
   }
}
```
P.S. the docs are not correct, it says to use `meteor.docker.port` but instead, we have to use `meteor.docker.imagePort`

**Comment by zodern** [comment]
Thanks for looking into it @bogdanrn. This will be fixed in the next update. I have also fixed the docs for `meteor.docker.imagePort`.
