### ISSUE TITLE
Reconfig does not delete the deleted env variables

### ISSUE THREAD

**Issue by giordanocardillo** [zodern/meteor-up#894]
Mup version (`mup --version`):  1.4.2
 
The bug I found is simple to reproduce, I deployed using a `MONGO_OPLOG_URL` env variable, then I removed it because I removed oplogs and gave `mup reconfigure`, that env variable wasn't removed and I had to deploy again. I was banging my head up a wall because of the `MongoError: Authentication failed.`, then I had the idea to `docker inspect` the container and I've seen the `MONGO_OPLOG_URL` was still there

**Comment by zodern** [comment]
I am not able to reproduce this. The correct command is `mup reconfig`.

**Comment by giordanocardillo** [comment]
Yep, I wrote reconfigure by mistake. I'll try again, but It happened to me three times. I'll keep you updated.

**Comment by zodern** [comment]
Let me know if you encounter this again.

If it helps, `mup meteor status` lists all of the environment variables set in the app's docker container.
