### ISSUE TITLE
SSL/Let's Encrypt instructions

### ISSUE THREAD

**Issue by SachaG** [zodern/meteor-up#898]
I can't find detailed instructions on how to set up Let's Encrypt with Mup, and how to test if it's working properly?

So far I've followed the instructions here: https://certbot.eff.org/#ubuntuxenial-nginx and added the `proxy` block to my `mup.js` file, but I don't see anything different? Did I miss something?

**Comment by SachaG** [comment]
Actually I did see something different, the app went down and I started getting 521 errors. I'm looking into it, but I still feel like a more detailed guide would be super helpful :)

**Comment by lucnat** [comment]
I would love some more instructions as well in the docs.

**Comment by zodern** [comment]
The docs are at http://meteor-up.com/docs#ssl. They do need to be improved.

After changing the config, run `mup reconfig`. It can take up to a couple of minutes for the certificates to be created.

`mup status` and `mup proxy status` will show any certificates for the app, and when they expire. `mup proxy logs-le` shows the logs from the Let's Encrypt docker container.

**Comment by SachaG** [comment]
Thanks for the added details! Some of the things I would like the docs to address:

- How do you get `letsEncryptEmail`?
- If you use custom certificates, how do you obtain them? Should you run Certbot in manual mode? Should you run it on your production machine or local development machine?
- If you use custom certificates, how is renewal handled?

I'll open a separate issue for my own specific problems and leave this as a thread about docs.

**Comment by SachaG** [comment]
Another question - should you use the `certonly` flag when running Certbot?

**Comment by SachaG** [comment]
So I think I can answer some of my own questions:

- You can use any arbitrary email for `letsEncryptEmail`. This is simply the email Mup will use when it registers the certificate. 
- To use custom certificates, run Certbot in manual mode either on your local or production machine. Nginx mode will not work. 
- I don't know about renewal. 

The key in all this was to set up the `proxy` config *before* doing `mup setup`. If the server was already setup, I wasn't able to set SSL properly even by running `mup setup` again; I had to wipe the instance and start over from scratch.

**Comment by Apollinaire** [comment]
>  I had to wipe the instance and start over from scratch.

@zodern is there a command to clean the instance from everything that mup has setup on it? That would be awesome. I had issues too with ssl, and i had to wipe an instance too to make it work

**Comment by zodern** [comment]
> The key in all this was to set up the proxy config before doing mup setup. If the server was already setup, I wasn't able to set SSL properly even by running mup setup again; I had to wipe the instance and start over from scratch.

@SachaG did you stop the apps before running `mup setup`? They both use port 80, so you have to stop the apps, run `mup setup`, and then run `mup reconfig` or `mup deploy`.

> is there a command to clean the instance from everything that mup has setup on it?

There is a feature request at #395.

**Comment by SachaG** [comment]
No I thought `mup setup` would stop the app already?

**Comment by zodern** [comment]
`mup setup` doesn't stop the app.

#915 will make this a little simpler.

When setting up the proxy fails, mup could look at the output  to see if the error is from an app using port 80 and give the user instructions.

In #916 I updated the [Let's Encrypt docs](https://github.com/zodern/meteor-up/pull/916/files#diff-c331e99b809715805fe7447af020d198R479).

**Comment by zodern** [comment]
Mup 1.4.4 has been released, which includes the improvements to the docs.

**Comment by davidrea** [comment]
Came across this issue while searching for how to renew LE certs... Looks like just running `mup setup` again will renew certs. If this is true and doesn't have other side effects, I'm happy to add with a PR.

**Comment by x5engine** [comment]
@davidrea just do it.

**Comment by x5engine** [comment]
I have evberything setup and deployed but when I try to access the website from the https I get a warning on chrome : NET::ERR_CERT_AUTHORITY_INVALID

which means the letsencrypt certificate wasn't verified but I didn't get the email too!

**Comment by x5engine** [comment]
Doing `mup proxy logs-le` which gives the prox letsencrypt logs I get this error which clearly shows an issue.
mup version 1.3.7

```
Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
[35.238.236.162]2019-02-04 20:34:03,716:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/I2dHz2RyzeySycmtB2nkqUtMYTbfphXhADplGJq4wec
[35.238.236.162]Challenge validation has failed, see error log.
```

Can you clearly show what's the issue? and also say what steps should we take to setup ssl properly!
Docs are not clear tbh
Thanks
