### ISSUE TITLE
Help - how to pass arguments in mup config for meteor run command?

### ISSUE THREAD

**Issue by sidzan** [zodern/meteor-up#904]
Mup version (`1.4.3`):

```js
module.exports = {
    servers: {
       
    },

    meteor: {
        // TODO: change app name and path
        name: 'e-commerce',
        path: '../../store',    //diff
        servers: {
            // one: {},
            two: {},
            three: {},
            four: {},
            five: {},
            six: {},
            seven: {}
        },

        buildOptions: {
            serverOnly: true,
            cleanAfterBuild: false,
        },

        env: {
            // TODO: Change to your app's url
            // If you are using ssl, it needs to start with https://
            ROOT_URL: 'https://xxx.com',
            MONGO_URL: 'xxx',
        },

        docker: {
            // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
            //image: 'abernix/meteord:base',
            image: 'abernix/meteord:node-8.4.0-base'
            // imagePort: 80, // (default: 80, some images EXPOSE different ports)
        },
        deployCheckWaitTime: 80,
        enableUploadProgressBar: true
    }
};
```

Output of command (use the `--verbose` option. Remember to remove sensitive information)
```bash
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

I have detailed my error in meteor forum [here](https://forums.meteor.com/t/fatalprocessoutofmemory-help/42574)

Turns out not enough memory is located and i need to increase memory as included in [here](https://stackoverflow.com/questions/48006869/meteor-app-ran-with-pm2-fatal-error-call-and-retry-last-allocation-failed-jav/48166231#48166231)

I need to pass environment Variable when mup runs my app, how do i put that example `main.js --node-args="--max-old-space-size=6144"`

**How do i pass arugments with mup config ?**
Any suggestion or help is much appreciated.

**Comment by zodern** [comment]
You can use the `NODE_OPTIONS` env variable: https://nodejs.org/api/cli.html#cli_node_options_options
