### ISSUE TITLE
 WARNING: The output directory is under your source tree.

### ISSUE THREAD

**Issue by Hereward** [zodern/meteor-up#905]
Mup version (`mup --version`): 1.4.3

Any idea what this warning means? Can it be ignored?

> **WARNING**: The output directory is under your source tree. Your generated files may get interpreted as source code! Consider building into a different directory instead meteor build ../output

**Comment by mikkelking** [comment]
It is probably ok now, if you are on Meteor 1.3+ as it no longer automatically loads files.

You should have your mup files outside your meteor structure. It's usual for your repo to have an app directory, which is where the meteor project goes. And you create a deployment folder which is where you put the mup file and the settings file

**Comment by zodern** [comment]
@Hereward did you set `buildLocation` in your config?
