### ISSUE TITLE
Make git SHA accessible as an environmental variable

### ISSUE THREAD

**Issue by houshuang** [zodern/meteor-up#907]
Would it be possible to grab the git SHA of the Meteor directory, and make this available to the Docker image as an environmental variable? We use mup to deploy code for experiments, and we just had an experiment that showed a small bug that we thought we had fixed - now I'm not sure if we ever deployed the new version or not.

Thus, if we could show the git SHA of the currently deployed version in our admin panel, and embed this in our automatically generated logs, append it to automatic monitoring messages (Sentry) etc, that would make our workflow much better!

Is there a way of doing this currently, by running some hook or something, or could something like this be baked into mup?

**Comment by zodern** [comment]
The [hooks documentation](http://meteor-up.com/docs#hooks) has an example of adding the git SHA to the `settings.json`. It would also be possible to modify the app's environment instead.
