### ISSUE TITLE
Bug with tail=XX

### ISSUE THREAD

**Issue by xanatas** [zodern/meteor-up#909]
Mup version (`mup --version`): 1.4.3 but hat this issue since a couple of releases

Ubuntu 16, AWS

```js
mup logs --tail=40
```

Output 

All the log data, not the last 40 rows, it grows massively if you want to debug and risks crashing the terminal if its REALLY LONG

**Comment by zodern** [comment]
Thanks for catching that! It works correctly with `mup logs --tail 40` (space instead of equal sign). This will be fixed in the next update.
