### ISSUE TITLE
Monitoring tools with meteor-up

### ISSUE THREAD

**Issue by ghost** [zodern/meteor-up#924]
This is not an issue, it's a question, and I don't know where to ask it. Apologies for this.

First, meter-up has been great. I'm using it to host my apps on AWS and it's working really well. I use to host on Galaxy. Galaxy had tools to monitor your app. I was wondering if there were tools that people used with Meteor-Up that do similar things.

**Comment by zodern** [comment]
That is a good question. I would also like to hear what people are using.

One option is [net data](https://my-netdata.io/). In the future, I am planning to integrate it with Meteor Up.
For one of my projects, I am using [Node Query](https://nodequery.com/). Other companies offer similar products.

For a Meteor APM, you can use [Node Chef's Meteor APM](https://www.nodechef.com/docs/node/meteor-apm). I am launching a similar service, which is in private beta (let me kow if you want to join).

**Comment by ghost** [comment]
Yes, I'd be interested in checking it out. Thanks.

**Comment by Silverutm** [comment]
I would like join the private beta, I'm currently running a server that could help you test the beta

**Comment by zodern** [comment]
Thanks for being willing to help test it! I can send you the information for joining in a private message on the Meteor forums. Could you please give me your username, or send me a message on the Meteor Forums?

**Comment by Silverutm** [comment]
My Meteor forums user
https://forums.meteor.com/u/Silverutm/

**Comment by cunneen** [comment]
We've had success with this on a t2.small ec2 instance :
https://github.com/lmachens/meteor-apm-server

It's kadira, the same as node chef's meteor apm AFAICT.

**Comment by adammoisa** [comment]
@zodern Leaving a comment here too :) Interested!

**Comment by zodern** [comment]
It is now available at https://montiapm.com/.

**Comment by adammoisa** [comment]
Yup found it in another thread, looks great!
