### ISSUE TITLE
How to use existing tarball to deploy app? needed for cordova apps

### ISSUE THREAD

**Issue by hridayeshgupta** [zodern/meteor-up#928]
I want create android app and server build.
as per meteor documentation I used `meteor build` command to generate apk. This also generates server build tarball. This tarball has correct hashes of this build which are included in apk.

Now when I deploy app using `mup deploy`, it does not use existing tarball which has same hashes as apk, but it builds tarball again which has different hashes. As a result app would to try to download assets again on start.
How can I use existing tarball to avoid this problem?

**Comment by zodern** [comment]
You can set `app.buildOptions.buildLocation` to the folder with the tarball. Then deploy using `mup deploy --cached-build` for it to use the existing tarball.

**Comment by hridayeshgupta** [comment]
Thanks! it solves the problem
