### ISSUE TITLE
mup setup doesn't do anything

### ISSUE THREAD

**Issue by mattiLeBlanc** [zodern/meteor-up#93]
Hi,

I migrated to Meteor 1.3 and now mupX is not working anymore. Some posts forwarded me to kadirahq's mup version so I am trying that now.
I follwed the npm intall and link and installed mup.
I have setup my mup.js file as follows:

```
'use strict';

module.exports = {
  servers: {
    one: {
      host: '{host ip}',
      username: 'ubuntu',
      pem: '~/.ssh/prospa'
    }
  },

  meteor: {
     name: 'app',
     path: '~/www/prospa/app,
     servers: {
       one: {} //list of servers to deploy, from the 'servers' list
     },
     env: {
       ROOT_URL: 'http://thedomain.com',
       MONGO_URL: 'mongodb://localhost/27017'
     },
     dockerImage: 'madushan1000/meteord-test', //optional
     deployCheckWaitTime: 60 //default 10
   },

  mongo: { //optional
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

When I run `mup setup` nothing happens. Just a 0.5 second lag and another shell line shows up.
When I remove the mup.js I get an error telling me the mup.js is missing. So it is doing something.

What am I doing wrong?

Also, will this config setup a mongo in a docker image like mupx?
We will move to a separate mongoDB soon so I will use the mongo_url for that.

I am a bit stressed because we are going live in 4 weeks and since the Meteor 1.3 upgrade a lot of stuff is broken/had to be fixed and now the deployment is down too.

Help would be very much appreciated.

**Comment by mattiLeBlanc** [comment]
After some digging I found that the PEM can't start with `~/.shh/pemfile` but it has to be `/Users/{name}/.ssh/pemfile.
(on osX).
I didn't get any error message on this.
Maybe add some error message if _fs2.default.readFileSync is not retrieving the pem file?
This was the file mup-api.js, function _loadSessions.

**Comment by madushan1000** [comment]
Yes. `~` is not supported yet. So is it working correctly now? 
I'll try to find why an error wouldn't trigger.

**Comment by mattiLeBlanc** [comment]
well I can deploy but Node is missing. I assumed it would install Node automatically. I installed version 4 now manually. 
I added a node symlink because I have installed nodejs. Hope it works  @now.

Also, MongoDb is in a docker container but the Meteor app is not.
Is there a reason this is different then mupX where both would run in a docker container? Not sure if it is a bad or good thing, just noticing.

**Comment by mattiLeBlanc** [comment]
okay, it is not working

```
x Verifying Deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    2435 s in the future
    tar: bundle/programs/server/npm-require.js: time stamp 2016-04-01 07:52:03 is 4.8821594 s in the future
    tar: bundle/programs/server/program.json: time stamp 2016-04-01 07:52:03 is 4.8423316 s in the future
    tar: bundle/programs/server/server-json.js: time stamp 2016-04-01 07:52:03 is 4.8422255 s in the future
    tar: bundle/programs/server/shell-server.js: time stamp 2016-04-01 07:52:03 is 4.8421069 s in the future
    tar: bundle/programs/server: time stamp 2016-04-01 07:52:03 is 4.8420645 s in the future
    tar: bundle/programs: time stamp 2016-04-01 07:52:03 is 4.8183891 s in the future
    tar: bundle/star.json: time stamp 2016-04-01 07:52:03 is 4.8182357 s in the future
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    => Starting meteor app on port:80
    Meteor requires Node v0.10.41 or later.

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

```

Not even sure what the real error is, when I do mup logs --tail=50 I only see 

```
> Starting meteor app on port:80
>Meteor requires Node v0.10.41 or later.
```

Shit..I just see that by using the package manager It is installing Node 0.10.25. 
No idea why I am not getting the newest version. Looking into it.

**Comment by mattiLeBlanc** [comment]
Okay...running out of options here. I just installed node v5.10.0 and still getting the same error message.
I don't know what to do anymore. Maybe its time for weekend lol

**Comment by madushan1000** [comment]
Meteor runs in a docker container, not outside. 
It seems like you copied your `mup.js` file from one of the test directories, right?
`dockerImage` field is only meant to be present only if you want to use a custom docker image.

> `dockerImage: 'madushan1000/meteord-test', //optional` line pulls an old meteord image I careated just for testing.

remove that line and app should work fine.

> In the futuere, use `mup init` to create a new mup.js file.

**Comment by mattiLeBlanc** [comment]
yes, I used the example from your README.MD file. The one generated by mup
init added require stuff and a sourcemap that looked to be incorrect?
Running meteor locally was trying to interpret those requires and generated
an error. So I reverted back to the example config in the readme.
Should I use another dockerImage or remove the line and it gets the default?

I guess to setup again, I have to remove the containers from docker and do
a new setup to see how it goes?

**Comment by madushan1000** [comment]
yeah, remove the line and try `mup setup` again. It'll pull the default docker image. I'll take a look at the other issue.

**Comment by mattiLeBlanc** [comment]
Yes, no it works!
Great job :)

**Comment by mattiLeBlanc** [comment]
Maybe update the readme a little bit so that others people have success
quicker

**Comment by mattiLeBlanc** [comment]
@madushan1000  Second deployment triggered an error again :(.
I don't understand why mup, mupx, can be so unreliable. What could trigger this issue? It is always happing during deployment verification.
Is there a workaround or way to find what really is messing up the verification?

```

/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
    throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
          ^
Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by madushan1000** [comment]
Can you post your new `mup.js` file?

**Comment by mattiLeBlanc** [comment]
```
'use strict';

// source of package: https://github.com/kadirahq/meteor-up

module.exports = {
  servers: {
    one: {
      host: '[ip]',
      username: '[user]',
      pem: '/Users/[user]/.ssh/prospa'
    }
  },

  meteor: {
     name: 'app',
     path: '/Users/[user]/www/app,
     servers: {
       one: {} //list of servers to deploy, from the 'servers' list
     },
     env: {
       ROOT_URL: [the url],
       MONGO_URL: 'mongodb://localhost/27017'
     },
     deployCheckWaitTime: 60 //default 10
   },

  mongo: { //optional
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },

};
```

I must say, I did.update NPM too because that was also a error message in the log, and then the deployment went okay. But I am not sure if it is resolved now for every deployment. But I will find out soon cause we are deploying to staging pretty often

**Comment by madushan1000** [comment]
I don't see anything wrong with the config. You don't have to install node or npm on the server because meteor app runs in a container. It looks like this is a problem with https://github.com/meteorhacks/meteord, try meteord issues page.

**Comment by mattiLeBlanc** [comment]
The weird thing is , when the first deployment of the day fails, a second attempt has been successful on a couple occasions.

**Comment by llqgit** [comment]
I got the same problem at first. But I solved then.
That README makes people confuse.
for example: 
You have a project called meteor_test

```
cd meteor_test
```

then current dir is:

```
>meteor_test
```

then mkdir .deploy

```
>meteor_test/.deploy
```

then cd .deploy and run mup init

```
>meteor_test/.deploy
                                  \_mup.js
                                  \_settings.json
```

at last run mup setup like this:

```
>meteor_test/.deploy > mup setup
```

You are under the .deploy dir to run _mup setup_ and _mup deploy_ . This is important...
Then there will be some things appeared....

**Comment by vectorselector** [comment]
I beat my head upon the wall for hours, nay, days,  upon end, never imagining that support for a home-directory tilde was something that even COULD change in an npm module.

WHY ON EARTH IS THIS INFO NOT ON THE FRONT PAGE OF THE GITHUB REPO!!!!??????

silent failure is not the right way... when i commented the pem line out, i get an obvious error. this failure was not cool... especially as our entire software framework community seems to be dependent upon this particular script.  (node bundling etc being what it is...)
