### ISSUE TITLE
How to specifec `node version` when deploy?

### ISSUE THREAD

**Issue by thearabbit** [zodern/meteor-up#934]
Mup version (`1.4.2`):

I would like to set specific `node version` when deploy.
I base on `Meteor 1.4.2.2`, and `Node 4.6.2`

**Comment by zodern** [comment]
You can change the docker image to one with the node version you want. The list of meteord images is at https://hub.docker.com/r/abernix/meteord/tags

**Comment by thearabbit** [comment]
very thanks
