### ISSUE TITLE
"current" dir missing - but app works!

### ISSUE THREAD

**Issue by Twisterking** [zodern/meteor-up#939]
So I already read https://github.com/zodern/meteor-up/issues/710, but it didn't really help unfortunately.

Mup version (`mup --version`): 1.4.4

Mup config
```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "root",
      "pem": "~/.ssh/pem"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "volumes": {
      "/opt/files": "/files"
    },
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "http://1.2.3.4", // no domain yet, just IP!
      "MONGO_URL": "mongodb://mongodb:27017/my-app"
    },
    "docker": {
      "image": "abernix/meteord:node-8.4.0-base",
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "mongo": {
    "version": "3.4.1",
    "servers": {
      "one": {}
    }
  }
}
```

It all works just fine, the very weird thing is though: **there is no `/opt/my-app/current` directory**! I just don't get it. Why is this working? How do I fix this?

**Comment by zodern** [comment]
Meteor Up creates a docker image for the app when deploying. The image contains the app's bundle (the files that used to be in `current`), so the `current` directory isn't needed anymore to run the app.

Did you use the current directory for something?
