### ISSUE TITLE
mup setup fails if docker is not installed

### ISSUE THREAD

**Issue by Floriferous** [zodern/meteor-up#941]
I just created a new digital ocean droplet, which apparently didn't come with `docker` preinstalled.

Here's what I saw in my console:

```sh
Florians-MacBook-Pro:www Florian$ mup setup

Started TaskList: Setup Docker
[xxxxxx] - Setup Docker
[xxxxxx] x Setup Docker: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      sudo: docker: command not found
	sudo: docker: command not found
	rm: cannot remove '/var/cache/apt/archives/lock': No such file or directory
	E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
	E: Unable to lock directory /var/lib/apt/lists/
	
	      ------------------------------------STDOUT------------------------------------
	      
	Major
	Minor
	Reading package lists...
	
	      ------------------------------------------------------------------------------
```

Does this package automatically install docker? If not, since it requires it, shouldn't it check if docker is installed and install it if not?

**Comment by zodern** [comment]
It is supposed to install docker if it isn't.

It first checks if docker is installed, and then the version of docker (it isn't, which is the reason for the first two lines). It then runs the install script, which is failing with the error:
```
	E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
	E: Unable to lock directory /var/lib/apt/lists/
```

**Comment by Floriferous** [comment]
So it was a temporary issue?

I ended up installing docker manually as instructed by the droplet, and then it worked again:

`apt install docker.io`

**Comment by derwaldgeist** [comment]
Just for the records. It took me three attempts, and suddenly it went through. Strange.
