### ISSUE TITLE
Reverse proxy to another nginx/apache container

### ISSUE THREAD

**Issue by ahmadsholehin** [zodern/meteor-up#946]
I'm looking to host another static virtual host (using either nginx or apache) alongside nginx-proxy that mup uses. Been trying a couple of times, but no dice.

Created a proxy object and then `mup setup` and `mup deploy`
```
proxy: {
  domains: 'domain1.com'
}
```

`docker ps` reports that `mup-nginx-proxy` is running and therefore I presume that another docker container can make use of it by just passing in a `VIRTUAL_HOST=domain2.com`. Realised that the other container needs to be in the same docker network and I can't happen to figure out how to set `mup-nginx-proxy` to use a specific docker network.

Can anyone help?

**Comment by zodern** [comment]
mup-nginx-proxy uses the bridge network. In Mup 1.5, it uses the mup-proxy network when swarm is enabled.
