### ISSUE TITLE
Expose additional port to nginx proxy

### ISSUE THREAD

**Issue by clesquir** [zodern/meteor-up#947]
I want to expose a port to the nginx proxy additionally to the standard 80 and 443. I easily did it without using the proxy with the `app.docker.args`:
https://github.com/zodern/meteor-up/blob/fff181ebe21751ea7687394e12facd368fdf5708/src/plugins/meteor/assets/templates/start.sh#L77

but there is no such `proxy.docker.args`:
https://github.com/zodern/meteor-up/blob/185342835ea354097cb8435e50dc0369ee8df82a/src/plugins/proxy/assets/templates/start.sh#L45

Is there a workaround for this or should I ask for this change?

Thanks!

**Comment by clesquir** [comment]
I've created a pull request for this change: https://github.com/zodern/meteor-up/pull/948

**Comment by zodern** [comment]
Thanks for creating the pull request.

This issue is a duplicate of #706.
