### ISSUE TITLE
How to check node version on Docker

### ISSUE THREAD

**Issue by thearabbit** [zodern/meteor-up#954]
Mup version (`mup 1.4.4`):

How to check `node version` on Docker, and I could specific version node?

**Comment by naterich2** [comment]
```docker exec  <app_name> /usr/bin/node --version``` will check node version when replaced with your app name.  I believe you can install a specific version if you choose the right docker image in your config, for example ```abernix/meteord:node-8.4.0-base``` will install node 8.4.0, but there are many others availeble [here](https://hub.docker.com/r/abernix/meteord/)

**Comment by thearabbit** [comment]
Very thank for your reply
