### ISSUE TITLE
Allow oplog to be disabled

### ISSUE THREAD

**Issue by merlinstardust** [zodern/meteor-up#955]
Add an option to disable oplog if you don't want it or need it.

Ideally, it would be great to just not specify it and have mup not complain.

```
  "env": {
    "ROOT_URL": "https://xx.xx.xxx.xx",
    "MONGO_URL": "mongodb://staging:27017,staging:27018,staging:27019/staging?replicaSet=rs0",
    // just removing the below line should still work
    // "MONGO_OPLOG_URL": "mongodb://staging:27017,staging:27018,staging:27019/local?authSource=admin",
    "MAIL_URL": "smtp://localhost:25",
    "CLUSTER_WORKERS_COUNT": "auto",
    "KADIRA_PROFILE_LOCALLY": 1
  },
```

But if the line must be specified (for legacy reasons or something), then this should be as simple as `MONGO_OPLOG_URL: false` or similar

**Comment by zodern** [comment]
Setting the environment variable should be optional.  Where does mup complain?

**Comment by merlinstardust** [comment]
It says that `MONGO_OPLOG_URL` is required when I run `mup setup`.

Also, in #21, you stated that it is not possible to disable the oplog.

**Comment by zodern** [comment]
Could you please show the output of the command?

It currently isn't possible to disable mup from setting up the MongoDB replica set and oplog, but setting the environment variable or using the oplog in your app is optional.
