### ISSUE TITLE
Disable builtin PhantomJS installation?

### ISSUE THREAD

**Issue by alvara** [zodern/meteor-up#959]
I would like to use a different npm prebuilt version of phantom JS rather than the MUP phantom js that is pre-installed. 

On a prior version of MUP, it was possible to disable this in mupjs, I think with:

`        setUpPhantom: false
`
However, it doesnt seem to work anymore with the latest version of MUP. How can I disable the pre-installed phantom js with the current MUP version?

**Comment by zodern** [comment]
You can use a docker image that doesn't have Phantom js, such as [abernix/spaceglue](https://github.com/abernix/spaceglue)
