### ISSUE TITLE
dotenv doesn't work together with mupx ? 

### ISSUE THREAD

**Issue by hems** [zodern/meteor-up#96]

**Comment by madushan1000** [comment]
I haven't used it, But I see no reason for it not to work.

**Comment by hems** [comment]
i had this issue in a different project again, variables on my .env file were not being loaded on the server, so i end up having to copy my variables into `mup.json`

**Comment by hems** [comment]
was this tested or just closed? was it my mistake ? 

i don't recall having this issue locally and i had it after pushing the project..
