### ISSUE TITLE
How to setup wildcard proxy and SSL?

### ISSUE THREAD

**Issue by matsuki820** [zodern/meteor-up#960]
I was looking at the docs and I was able to accurately setup proxy and SSL and with added support from Let's encrypt for wildcard certs I wanted to add this into my deployment. 

My first thought was to setup "proxy.domains" to "*.mydomain.com" and this worked fine for non https requests but https requests wouldn't get through.

Which is weird as I have "forceSSL" set to true.

So my question is, is it possible to set up wildcard subdomains with SSL from let's encrypt with MUP?

My current setup is like this:
```js
{
    servers: {
        one: {
            host: 'IP_ADDRESS',
            username: 'USERNAME',
            pem: './path/to/pem'
        }
    },

    app: {
        name: 'app-name',
        path: '../app',

        servers: {
            one: {},
        },

        buildOptions: {
            serverOnly: true,
        },

        env: {
            ROOT_URL: 'https://app.mydomain.com',
            MONGO_URL: 'mongodb://mongodb/meteor',
            MONGO_OPLOG_URL: 'mongodb://mongodb/local',
        },
        docker: {
            image: 'abernix/meteord:node-8.4.0-base',
        },
        enableUploadProgressBar: true
    },

    mongo: {
        version: '3.4.1',
        servers: {
            one: {}
        }
    },
    proxy: {
        domains: '*.mydomain.com',

        ssl: {
            letsEncryptEmail: 'test@example.com',
            forceSSL: true,
        }
    }
}
```

**Comment by jwjordan** [comment]
I'm stuck on this as well, but I can tell you that using LetsEncrypt for a wildcard domain is no easy feat.  It requires a DNS-challenge based authentication of the domain, so I can't see that coming in mup anytime soon.  However, if you generate your own wildcard certs using LetsEncrypt, I would think mup could support them.  It doesn't appear that is true for wildcard domains, or at least it's only partially true.  The wildcard certs themselves do appear to work, yet mup will not let you set "*.example.com" as your domain name in the nginx proxy.  If it could, then I think using your own wildcard certs would "just work" with a mup deploy.

**Comment by mishli** [comment]
I'm also having issue setting wildcard domains in proxy object and using custom cert (includes wildcard), but when running mup setup i get error 'Pushing Nginx Config: FAILED' and then: 

`rm: cannot remove 'mydomain_location': No such file or directory
	rm: cannot remove '*.mydomain_location_location': No such file or directory
	rm: cannot remove 'seconddomain_location': No such file or directory
	bash: line 31: *.seconddomain: ambiguous redirect`

when i remove the wildcard domains from proxy -  mup setup runs with no errors.
dns wildcard is set up on both domains.

does mup or meteor even support wildcard domains?

this is my mup setup:

```
module.exports = {
  servers: {
    one: {
      host: "ip_address",
      username: "root",
      pem: "path/to/pem"
    }
  },

  meteor: {
    name: 'my-app',
    path: '../',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
      debug: false,
      cleanAfterBuild: true
    },
    env: {
      ROOT_URL: 'https://domain.com',
      MONGO_URL: 'mongodb://mongodb/meteor',
      MONGO_OPLOG_URL: 'mongodb://mongodb/local'
    },
    docker: {
      image: 'zodern/meteor:root',
    },
    deployCheckWaitTime: 120,
    enableUploadProgressBar: true
  },

  proxy: {
    domains: 'domain.com, *.domain.com, domain2.com, *.domain2.com',
    ssl: {
      crt: './ssl/fullchain.pem',
      key: './ssl/privkey.pem'
    }
  },

  mongo: {
    oplog: true,
    port: 27017,
    version: '3.4.2',
    servers: {
      one: {}
    }
  }
};
```

**Comment by mishli** [comment]
UPDATE:
I managed to solve it!

Here the solution for anybody who run into this..
The trick was to define a shared proxy host under SHARED object, which will then support all of incoming hosts under the domain. 
I used the main subdomain which is the one our app is sitting on (it serves all other subdomains) and not the root domain and everything is working perfectly.

this is the added code that fixed it:

```
proxy: {
    domains: 'mainsubdomain.domain.com',
    ssl: {
        crt: './ssl/fullchain.pem',
        key: './ssl/privkey.pem'
    },
    shared: {
        env: {
            DEFAULT_HOST: 'mainsubdomain.domain.com'
        }
    }
},
```

**Comment by andrei-markeev** [comment]
One sneaky detail: in order to apply `DEFAULT_HOST` value, you need to run `mup proxy reconfig-shared`. It is [documented](http://meteor-up.com/docs.html#advanced-configuration), but I somehow missed it, and lost many hours trying to understand why it doesn't work 😄
