### ISSUE TITLE
MUp deploy fail on Ubuntu server

### ISSUE THREAD

**Issue by thirtyfoursoft** [zodern/meteor-up#968]
App is working fine on local, but when I try to push it on server, it fails and show the below errors.

Mup version (`mup --version`): 1.4.5

'
        Step 6/6 : RUN cd  /built_app/programs/server &&     npm install --unsafe-perm
         ---> Running in f924239aaa65

        > fibers@1.0.13 install /built_app/programs/server/node_modules/fibers
        > node build.js || nodejs build.js

        `linux-x64-v8-4.5` exists; testing
        Binary is fine; exiting

        > meteor-dev-bundle@0.0.0 install /built_app/programs/server
        > node npm-rebuild.js

        > bcrypt@1.0.3 install /built_app/programs/server/npm/node_modules/bcrypt
        > node-pre-gyp install --fallback-to-build

        sh: 1: node-pre-gyp: not found
        npm ERR! file sh
        npm ERR! code ELIFECYCLE
        npm ERR! errno ENOENT
        npm ERR! syscall spawn
        npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
        npm ERR! spawn ENOENT
        npm ERR!
        npm ERR! Failed at the bcrypt@1.0.3 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2018-06-26T06_25_33_869Z-debug.log
        npm WARN meteor-dev-bundle@0.0.0 No description
        npm WARN meteor-dev-bundle@0.0.0 No repository field.
        npm WARN meteor-dev-bundle@0.0.0 No license field.
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2018-06-26T06_25_33_907Z-debug.log
`

**Comment by zodern** [comment]
Could you please show your config (`mup validate --scrub --show`)?

**Comment by thirtyfoursoft** [comment]
Hi @zodern ,

Thanks for replying, Here is the output of your given command.

![download](https://user-images.githubusercontent.com/5276424/41910271-ccfeb1a4-7966-11e8-89b9-df8ff1f2124e.png)

Thanks

**Comment by zodern** [comment]
Your app needs `node-pre-gyp`, which the docker image you are using doesn't have. It is possible to [customize the docker image](http://meteor-up.com/docs#customize-docker-image) with `app.docker.buildInstructions`:

```js
module.exports {
  app: {
    docker: {
      buildInstructions: [
        'RUN npm install node-pre-gyp -g'
      ]
    }
  }
};
```

**Comment by thirtyfoursoft** [comment]
Thanks for your update.

Earlier it was using : 
`
    docker: {
      image: 'abernix/meteord:base',
    }
`

And now I have changed it to :
`
 docker: {
      image: 'abernix/meteord:base',
	  buildInstructions: [
        'RUN npm install node-pre-gyp -g'
      ]
    }

Please let me know if it is okay?

**Comment by thirtyfoursoft** [comment]
@zodern , Thanks a lot, your solution did the great job, it is working correctly.
