### ISSUE TITLE
Meteor Application Load Balancer SSL and Letsencrypt issue.

### ISSUE THREAD

**Issue by thirtyfoursoft** [zodern/meteor-up#972]
I am trying to deploy my app on AWS with Application load balancer, I also have installed Letsencrypt and it is working perfectly, when I try to setup ALB it will setup a new SSL See screenshot

![image](https://user-images.githubusercontent.com/5276424/42162557-b9155bba-7e1c-11e8-84e8-f783812afb6e.png)

Mup version : 1.4.5

and it is creating problem on deplyment , is there any solution, now it is showing "503 service temporarily unavailable"

Thanks

**Comment by LevanArabuli** [comment]
You don't need both `letsencrypt` and ALB level SSL handling, just use one of them.

Screenshot you provided only shows SSL Certificate setup. It needs to be attached to `Application Load Balancer`.

**Comment by thirtyfoursoft** [comment]
Meteor is using the letsencrypt to run the docker on secure connection, otherwise it will work on non https, and ALB can't handle the App to work with https.

Otherside it is mandatory to add SSL on load balancer (in case https support.)

**Comment by tomtom87** [comment]
Use Route 53, not letsencrypt and should be working
