### ISSUE TITLE
Sudo required if not running on port 80?

### ISSUE THREAD

**Issue by Josvanegmond** [zodern/meteor-up#977]
The docs state:
> Please ensure your key file (pem) is not protected by a passphrase. This setup process will require NOPASSWD access to sudo. (Since Meteor needs port 80, sudo access is required.)

I run meteor on a different port. I think either sudo is not always necessary or this explanation is too specific.

Seems like a safety concern to demand direct root access over ssh or allow a useraccount sudo access without the need for a password. Is there a way to avoid this?

**Comment by zodern** [comment]
The docs do need to be updated. Sudo is also used whenever a docker command is run and when creating folders in /opt.

> Seems like a safety concern to demand direct root access over ssh or allow a useraccount sudo access without the need for a password. Is there a way to avoid this?

There currently isn't a way to avoid it. This is related to #770

**Comment by zodern** [comment]
The docs were updated.
