### ISSUE TITLE
Can't Pass NODE_VERSION to the zodern/meteor image

### ISSUE THREAD

**Issue by marcoschwartz** [zodern/meteor-up#979]
Hello,

I want to switch my Meteor apps to use the zodern/meteor:root image, as I need PhantomJS installed. However, I can't seem to manage to install it with Node.js in version 8.11.3 (the latest for Meteor 1.7.x). It always ends up installed with Node 4.8.4.

I tried with: 

- zodern/meteor:0.5.0-root and zodern/meteor:root
- ONBUILD ARG NODE_VERSION='8.11.3' or ARG NODE_VERSION='8.11.3' in buildInstructions

Is there something I am doing wrong here? Thanks!

**Comment by zodern** [comment]
With Mup 1.4, it uses node 4 during prepare bundle and the correct version when running the app. `buildInstructions` is run after the node version has been set.

Mup 1.5 (#976) will set the correct value for `NODE_VERSION` during Prepare Bundle.

**Comment by marcoschwartz** [comment]
Got it, will wait for 1.5 then :)
