### ISSUE TITLE
Got permission denied while trying to connect to the Docker daemon socket

### ISSUE THREAD

**Issue by Jaggar** [zodern/meteor-up#982]
Mup version (mup --version): 1.4.5
Hey! I've been getting this error when deploying my app with MUP. I looked up but I couldn't find any solution anywhere:

**mup setup:** 

> Started TaskList: Setup Docker
[48.**.***.*] - Setup Docker
[48.**.***.*] - Setup Docker: SUCCESS

>Started TaskList: Setup Meteor
[48.**.***.*] - Setup Environment
[48.**.***.*] - Setup Environment: SUCCESS

>Started TaskList: Setup Mongo
[48.**.***.*] - Setup Environment
[48.**.***.*]- Setup Environment: SUCCESS
[48.**.***.*]- Copying mongodb.conf
[48.**.***.*] - Copying mongodb.conf: SUCCESS

>Started TaskList: Start Mongo
[48.**.***.*] - Start Mongo
[48.**.***.*]- Start Mongo: SUCCESS

**mup deploy:**

> Started TaskList: Pushing Meteor App
> [48.**.***.*] - Pushing Meteor App Bundle to the Server
> [48.**.***.*] - Pushing Meteor App Bundle to the Server: SUCCESS
> [48.**.***.*]- Prepare Bundle
> [48.**.***.*]- Prepare Bundle: SUCCESS
> 
> Started TaskList: Configuring App
> [48.**.***.*] - Pushing the Startup Script
> [48.**.***.*]- Pushing the Startup Script: SUCCESS
> [48.**.***.*] - Sending Environment Variables
> [48.**.***.*]- Sending Environment Variables: SUCCESS
> 
> Started TaskList: Start Meteor
> [48.**.***.*] - Start Meteor
> [48.**.***.*] - Start Meteor: SUCCESS
> [48.**.***.*] - Verifying Deployment
> [48.**.***.*] - x Verifying Deployment: FAILED
> 	
> 	      ------------------------------------STDERR------------------------------------
> 	      Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/containers/pre-sale-app/json: dial unix /var/run/docker.sock: connect: permission denied
> 	Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/containers/pre-sale-app/json: dial unix /var/run/docker.sock: connect: permission denied
> 	Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/containers/pre-sale-app/json: dial unix /var/run/docker.sock: connect: permission denied
> 	Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/containers/pre-sale-app/json: dial unix /var/run/docker.sock: connect: permission denied
>unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/containers/pre-sale-app/json: dial unix /var/run/docker.sock: connect: permission denied

> 	Container spent too much time restarting.
> 	=> Starting meteor app on port:80
> 	 
> 	=> Redeploying previous version of the app
> 	 
> 	
> 	      ------------------------------------STDOUT------------------------------------
> 	      Container has no IP Address, likely from the app crashing.
> 	Container has no IP Address, likely from the app crashing.
> 	Container has no IP Address, likely from the app crashing.
> 	Container has no IP Address, likely from the app crashing.
> 	Container has no IP Address, likely from the app crashing.
> 	Container has no IP Address, likely from the app crashing.
> 	Container has no IP Address, likely from the app crashing.
> 	Container has no IP Address, likely from the app crashing.
> 	Container has no IP Address, likely from the app crashing.
> 	Container has no IP Address, likely from the app crashing.
> 	=> Container status:
> 	restarted: 0 times 
> 
> To see more logs type 'mup logs --tail=200'
> 

 I then run 

> mup logs --tail=200
and it brings:

> [48.**.***.*]=> Starting meteor app on port:80
> [48.**.***.*] {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"email sender\" next run @0","time":{"$date":1532244795169},"level":"info"}

Thanks in advance!

**Comment by Jaggar** [comment]
Solved it: you have to login to your remote server run this command 

> sudo usermod -a -G docker $USER

then log out of the server then run the usual commands **mup setup** and **mup deploy**

**Comment by copleston** [comment]
For me, using `image: 'zodern/meteor:root'` in my docker config in mup.js did the trick
