### ISSUE TITLE
MUP always use the initial docker image but not the latest build

### ISSUE THREAD

**Issue by Noboxulus** [zodern/meteor-up#985]
Mup version (`mup --version`): 1.4.5

Hi, I just started using MUP today and successfully deployed my meteor app to AWS EC2.

However, I changed the color of one button in my app from blue to green and even though the change reflects when I run meteor on my local development environment, AWS EC2 still show the initial version after I re-run `mup.cmd deploy`.

I have tried to re-run `mup.cmd deploy` more than 5 times to no joy.

I also tried to run `mup.cmd setup` before I run `mup.cmd deploy` as well but it still show blue button (initial version).

Snippet of the `mup.cmd deploy` output for redeployment:

>Removing intermediate container 25d0b3ad9365
 ---> 00c811073edd
Successfully built 00c811073edd
Successfully tagged mup-appxxx:build
Deleted Images:
deleted: sha256:8fb2df254826ee9ffc0799532e860c2f94a2ac7cd81b2b1349f0baca00fdae65
deleted: sha256:315ce418e1f9b6f513b0402720a214a4e724ff7ddd3c448849bdf1cf2ea12027
deleted: sha256:31db6b4ddd448678d1871db8841a2f82424083a98bffd51d920837dd6248bea3
deleted: sha256:18aa8d26f43a51fae36d3c7b73bf38d40b7dfa43e801c577c8d017f46dd08bd5
> 
> Total reclaimed space: 21.33MB
> [my.ip.add.ress] - Prepare Bundle: SUCCESS
> 
> Started TaskList: Configuring App
> [my.ip.add.ress] - Pushing the Startup Script
> [my.ip.add.ress] - Pushing the Startup Script: SUCCESS
> [my.ip.add.ress] - Sending Environment Variables
> [my.ip.add.ress] - Sending Environment Variables: SUCCESS
> 
> Started TaskList: Start Meteor
> [my.ip.add.ress] - Start Meteor
> using image
> removing last
> Image mup-appxxx:latest
> Volume
> Removing docker containers. Errors about nonexistent endpoints and containers are normal.
> Error: No such container: appxxx
> Error response from daemon: endpoint appxxx not found
> Error: No such container: appxxx-frontend
> Error response from daemon: endpoint appxxx-frontend not found
> Error: No such container: appxxx-nginx-letsencrypt
> Error response from daemon: endpoint appxxx-nginx-letsencrypt not found
> Error: No such container: appxxx-nginx-proxy
> Error response from daemon: endpoint appxxx-nginx-proxy not found
> Finished removing docker containers
> fc93b30e74323e9e175bfb906de1dfa1f2f3597616c49d1f559215582a4bc5a5
> Ran abernix/meteord:node-8.11.2-base
> [my.ip.add.ress] - Start Meteor: SUCCESS

Edit:
Changing the app name in `mup.js` config and rerunning `mup.cmd setup` and `mup.cmd deploy` every time for a redeployment works, but I would rather not use this workaround if I could.

**Comment by zodern** [comment]
@Noboxulus do you still have this problem?
