### ISSUE TITLE
mup set failed, 

### ISSUE THREAD

**Issue by zuizuihao** [zodern/meteor-up#99]
I failed to use mup setup. is there anything wrong i do? used docker in my sever.
`module.exports = {
  servers: {
    one: {
      host: '',
      username: 'ubuntu',
      pem: ''
    },
  },

  meteor: {
    name: '',
    path: '',
    servers: {
      one: {},
    },
    env: {
      PORT: 30000,
      ROOT_URL: '',
      MONGO_URL: ''
    },
    // setupMongo: false,
    // dockerImage: '', //optional
    deployCheckWaitTime: 60 //default 10
  },

  mongo: {
    oplog: true,
    servers: {
      one: {},
    },
  },
};
`
Error response from daemon: Cannot start container a94b6d943a856534d1a05bdf0d164d2986cbd7f23bbace2b5cef59e219dd5659: failed to create endpoint mongodb on network bridge: Error starting userland proxy: listen tcp 127.0.0.1:27017: bind: address already in use
    -----------------------------------STDOUT-----------------------------------
    latest: Pulling from library/mongo
    Digest: sha256:be6bbba5cf0f206632fb0e782def85214d45b896f700be370cbdac421f53441a
    Status: Image is up to date for mongo:latest
    mongodb
    a94b6d943a856534d1a05bdf0d164d2986cbd7f23bbace2b5cef59e219dd5659

**Comment by madushan1000** [comment]
You don't have to setup docker yourself. Mup will automatically set it up
