### ISSUE TITLE
Suggestion: support color control codes in mup logs

### ISSUE THREAD

**Issue by wildhart** [zodern/meteor-up#990]
I've started using control codes to add color to my app's server-side console.logs (e.g. https://stackoverflow.com/questions/9781218/how-to-change-node-jss-console-font-color)

The colors come through if I ssh into the server and run `docker logs <containername>`

But the colors do not come through with `mup logs` - the control codes are converted to other characters.

Is it possible to bring the control codes through?

**Comment by zodern** [comment]
I am merging this with #762
